import { SeedProblemData } from '../src/types/problem';

// - incorrectOptions の要素たちは japaneseSentence とほぼ同じ文字数で生成すること
// - incorrectOptionsの内容は、依頼や質問や提案や意見や情報共有のような、話しかける形式のセリフであること。japaneseSentenceとは無関係なセリフであること。
// - 日本語の文について。「500円」などの数値は「五百円」と表記すること

const problems: SeedProblemData[] = [
  {
    englishSentence: 'Excuse me, is there a convenience store nearby?',
    japaneseSentence: 'すみません、この近くにコンビニはありますか？',
    japaneseReply: 'はい、あの角を曲がったところにありますよ。',
    incorrectOptions: [
      '明日の打ち合わせは何時から始まりますか？',
      '今度一緒に旅行に行きませんか？',
      'この書類を先に確認してもらえますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '旅行者',
    receiverVoice: 'female',
    receiverRole: '地元の人',
    place: '道',
  },
  {
    englishSentence: 'The movie we watched yesterday was really interesting, wasn’t it?',
    japaneseSentence: '昨日見た映画はとても面白かったですね。',
    japaneseReply: 'そうですね。特に最後のシーンが印象的でした。',
    incorrectOptions: [
      '新しくできたカフェにもう行きましたか？',
      '来週のテストは難しいと思いませんか？',
      '最近読んだ本をおすすめしてもいいですか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '友達',
    receiverVoice: 'male',
    receiverRole: '友達',
    place: 'カフェ',
  },
  {
    englishSentence: 'Does this train go to the airport?',
    japaneseSentence: 'この電車に乗れば空港まで行けますか？',
    japaneseReply: 'はい、直通で空港まで行けます。',
    incorrectOptions: [
      'その荷物を少し持ってあげましょうか？',
      '駅前で新しい店がオープンしたそうですよ。',
      '今週末は予定が空いていますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '旅行者',
    receiverVoice: 'female',
    receiverRole: '駅員',
    place: '駅',
  },
  {
    englishSentence: 'Excuse me, do you have any tables available without a reservation?',
    japaneseSentence: 'すみません、予約していないのですが席はありますか？',
    japaneseReply: '少々お待ちください。はい、大丈夫です、ご案内します。',
    incorrectOptions: [
      '最近体調を崩してしまって会社を休みました。',
      '新しいプロジェクトのメンバーに入りませんか？',
      'この後で駅まで一緒に歩きませんか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '客',
    receiverVoice: 'male',
    receiverRole: '店員',
    place: 'レストラン',
  },
  {
    englishSentence: 'Could you send me the materials from last week’s meeting by email?',
    japaneseSentence: '先週の会議の資料をメールで送っていただけますか？',
    japaneseReply: 'はい、後ほどお送りします。',
    incorrectOptions: [
      '最近習い始めたギターがすごく楽しいんです。',
      '次の休みに映画を一緒に見に行きませんか？',
      '明日は雨が降るみたいだから気をつけてね。',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '同僚',
    receiverVoice: 'female',
    receiverRole: '同僚',
    place: '会社',
  },
  {
    englishSentence: 'Could you help me carry this heavy box upstairs?',
    japaneseSentence: 'すみません、この重い箱を二階まで運ぶのを手伝ってもらえますか？',
    japaneseReply: 'もちろんです。一緒に運びましょう。',
    incorrectOptions: [
      '昨日のプレゼンはとてもよくできていましたね。',
      '駅までタクシーを呼んでいただけませんか？',
      '今週の宿題を手伝ってもらえますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '学生',
    receiverVoice: 'male',
    receiverRole: '友達',
    place: '学校',
  },
  {
    englishSentence: 'Do you know where I can buy a SIM card around here?',
    japaneseSentence: 'この辺りでSIMカードを買える場所を知っていますか？',
    japaneseReply: 'はい、駅前の電気屋で買えますよ。',
    incorrectOptions: [
      'その新しいアプリはもう試してみましたか？',
      '明日の朝一緒にジョギングしませんか？',
      '先週のイベントは楽しかったですよね。',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '旅行者',
    receiverVoice: 'female',
    receiverRole: '地元の人',
    place: '道',
  },
  {
    englishSentence: 'Would it be possible to change my appointment to next Monday?',
    japaneseSentence: '予約を来週の月曜日に変更することは可能ですか？',
    japaneseReply: 'はい、大丈夫です。変更しておきます。',
    incorrectOptions: [
      'この近くでおすすめのレストランはありますか？',
      '明日から新しい仕事が始まるんです。',
      '来月一緒に旅行を計画しませんか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '患者',
    receiverVoice: 'male',
    receiverRole: '受付',
    place: '病院',
  },
  {
    englishSentence: 'Could you tell me how long it takes to get to the museum from here?',
    japaneseSentence: 'ここから博物館までどのくらい時間がかかりますか？',
    japaneseReply: '徒歩で十五分ほどです。',
    incorrectOptions: [
      '最近新しい趣味を始めたんですが面白いですよ。',
      'その本を貸してもらうことはできますか？',
      '週末にピクニックに行くのはどうですか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '旅行者',
    receiverVoice: 'female',
    receiverRole: '通行人',
    place: '道',
  },
  {
    englishSentence: 'Do you know if there is Wi-Fi available in this café?',
    japaneseSentence: 'このカフェにWi-Fiはありますか？',
    japaneseReply: 'はい、パスワードはこちらです。',
    incorrectOptions: [
      '明日のプレゼンの準備は進んでいますか？',
      '新しいドラマをもう見ましたか？',
      '週末に一緒に買い物に行きませんか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '客',
    receiverVoice: 'male',
    receiverRole: '店員',
    place: 'カフェ',
  },
  {
    englishSentence: 'Could you please lower the volume a little bit?',
    japaneseSentence: 'すみません、音量を少し下げてもらえますか？',
    japaneseReply: 'はい、今下げますね。',
    incorrectOptions: [
      '明日のランチはどこに行きたいですか？',
      '新しいスマホをもう買いましたか？',
      '週末に映画を見に行きませんか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '客',
    receiverVoice: 'female',
    receiverRole: '店員',
    place: 'カフェ',
  },
  {
    englishSentence: 'Would you mind opening the window for some fresh air?',
    japaneseSentence: 'すみません、空気を入れたいので窓を開けてもらえますか？',
    japaneseReply: 'いいですよ、開けましょう。',
    incorrectOptions: [
      '最近読んだ本はとても面白かったです。',
      'この後駅まで一緒に歩きませんか？',
      '新しいゲームをもう試しましたか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '乗客',
    receiverVoice: 'male',
    receiverRole: '乗客',
    place: '電車',
  },
  {
    englishSentence: 'Could you tell me which bus goes to the airport?',
    japaneseSentence: '空港に行くバスはどれか教えていただけますか？',
    japaneseReply: 'はい、あの青いバスが空港行きです。',
    incorrectOptions: [
      '最近仕事が忙しくて疲れています。',
      '明日の試験は難しそうですね。',
      '来週一緒に旅行に行きませんか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '旅行者',
    receiverVoice: 'female',
    receiverRole: '案内係',
    place: 'バスターミナル',
  },
  {
    englishSentence: 'Would you like to join us for dinner tomorrow evening?',
    japaneseSentence: '明日の夜、一緒に夕食に行きませんか？',
    japaneseReply: 'いいですね、楽しみにしています。',
    incorrectOptions: [
      '新しい映画をもう見に行きましたか？',
      '今日は体調があまりよくありません。',
      '駅の近くに新しいカフェができましたよ。',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '友達',
    receiverVoice: 'male',
    receiverRole: '友達',
    place: '公園',
  },
  {
    englishSentence: 'Do you know if this shop accepts credit cards?',
    japaneseSentence: 'このお店はクレジットカードを使えますか？',
    japaneseReply: 'はい、使えます。こちらに機械があります。',
    incorrectOptions: [
      '新しい靴を買いたいと思っているんです。',
      '昨日のドラマはとても面白かったですね。',
      '来週の天気はどうなると思いますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '客',
    receiverVoice: 'female',
    receiverRole: '店員',
    place: '店',
  },
  {
    englishSentence: 'Could you please explain this problem to me once more?',
    japaneseSentence: 'すみません、この問題をもう一度説明していただけますか？',
    japaneseReply: 'もちろんです。ゆっくり説明しますね。',
    incorrectOptions: [
      'この映画の続編はもう公開されていますか？',
      '新しいアルバムを聴きましたか？',
      '週末にみんなで集まりませんか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '学生',
    receiverVoice: 'male',
    receiverRole: '先生',
    place: '学校',
  },
  {
    englishSentence: 'Could you tell me how to get to the nearest pharmacy?',
    japaneseSentence: '一番近い薬局へはどう行けばいいですか？',
    japaneseReply: 'あの信号を渡ってすぐです。',
    incorrectOptions: [
      '最近運動不足で体重が増えてしまいました。',
      '昨日の夜はなかなか眠れませんでした。',
      '今度新しいスポーツを始めてみませんか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '旅行者',
    receiverVoice: 'female',
    receiverRole: '通行人',
    place: '道',
  },
  {
    englishSentence: 'Would you mind if I borrowed your pen for a moment?',
    japaneseSentence: 'ちょっとペンを貸していただけますか？',
    japaneseReply: 'どうぞ、使ってください。',
    incorrectOptions: [
      '昨日の宿題はもう終わりましたか？',
      'この後で一緒に昼ご飯を食べませんか？',
      '最近新しい趣味を始めたんです。',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '学生',
    receiverVoice: 'male',
    receiverRole: '学生',
    place: '学校',
  },
  {
    englishSentence: 'Could you show me how to use this machine?',
    japaneseSentence: 'この機械の使い方を教えていただけますか？',
    japaneseReply: 'はい、ここを押すと動きます。',
    incorrectOptions: [
      '明日の会議には何時に来られますか？',
      '駅の近くに美味しい店があるそうですよ。',
      '新しい映画を一緒に見に行きませんか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '客',
    receiverVoice: 'female',
    receiverRole: '店員',
    place: '店',
  },
  {
    englishSentence: 'Would it be okay if I open this package here?',
    japaneseSentence: 'ここでこの荷物を開けてもいいですか？',
    japaneseReply: 'はい、大丈夫ですよ。',
    incorrectOptions: [
      '昨日の試合はとても盛り上がりましたね。',
      '今度新しいプロジェクトを始めませんか？',
      'この本を貸していただけますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '客',
    receiverVoice: 'male',
    receiverRole: '店員',
    place: '郵便局',
  },
  {
    englishSentence: 'Could you please call me a taxi to the station?',
    japaneseSentence: '駅まで行くタクシーを呼んでいただけますか？',
    japaneseReply: 'はい、すぐに手配いたします。',
    incorrectOptions: [
      '明日の試験はどの教室で行われますか？',
      '新しくできたパン屋にもう行きましたか？',
      '週末にみんなで集まりませんか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '客',
    receiverVoice: 'female',
    receiverRole: 'ホテルスタッフ',
    place: 'ホテル',
  },
  {
    englishSentence: 'Would you mind taking a photo of us with this camera?',
    japaneseSentence: 'このカメラで写真を撮っていただけますか？',
    japaneseReply: 'もちろんです。どの角度がいいですか？',
    incorrectOptions: [
      '昨日のドラマは本当に面白かったですね。',
      '駅の近くに新しいカフェができましたよ。',
      '今度一緒に山登りに行きませんか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '旅行者',
    receiverVoice: 'male',
    receiverRole: '通行人',
    place: '観光地',
  },
  {
    englishSentence: 'Could you please repeat the last part more slowly?',
    japaneseSentence: '最後の部分をもう少しゆっくり繰り返してもらえますか？',
    japaneseReply: 'はい、ゆっくり説明しますね。',
    incorrectOptions: [
      '昨日はあまりよく眠れなかったんです。',
      '週末にサッカーを一緒にしませんか？',
      'その本を貸していただけませんか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '学生',
    receiverVoice: 'female',
    receiverRole: '先生',
    place: '学校',
  },
  {
    englishSentence: 'Do you know if this bus stops at the museum?',
    japaneseSentence: 'このバスは博物館に停まりますか？',
    japaneseReply: 'はい、三つ目の停留所で停まります。',
    incorrectOptions: [
      '今度の週末に花見に行きませんか？',
      '最近始めた趣味がすごく楽しいんです。',
      '明日の夜はどこで会いますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '旅行者',
    receiverVoice: 'male',
    receiverRole: '運転手',
    place: 'バス',
  },
  {
    englishSentence: 'Would it be possible to extend my stay for another night?',
    japaneseSentence: '宿泊をもう一泊延長することはできますか？',
    japaneseReply: 'はい、空室がありますので可能です。',
    incorrectOptions: [
      'その映画を一緒に見に行きませんか？',
      '新しいレストランにもう行きましたか？',
      '来週の予定を確認していただけますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '客',
    receiverVoice: 'female',
    receiverRole: 'ホテルスタッフ',
    place: 'ホテル',
  },
  {
    englishSentence: 'Could you tell me when the next train to Tokyo leaves?',
    japaneseSentence: '東京行きの次の電車は何時に出発しますか？',
    japaneseReply: '10分後に発車します。',
    incorrectOptions: [
      '昨日は久しぶりに映画館に行きました。',
      '週末に友達と旅行に行く予定です。',
      'その本を貸していただけませんか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '旅行者',
    receiverVoice: 'male',
    receiverRole: '駅員',
    place: '駅',
  },
  {
    englishSentence: 'Would you mind watching my bag for a few minutes?',
    japaneseSentence: '少しの間、私の荷物を見ていてもらえますか？',
    japaneseReply: 'はい、大丈夫ですよ。',
    incorrectOptions: [
      '昨日の試合はとても盛り上がりましたね。',
      'この後で駅まで一緒に行きませんか？',
      '新しいアプリをもう試しましたか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '旅行者',
    receiverVoice: 'female',
    receiverRole: '通行人',
    place: '駅',
  },
  {
    englishSentence: 'Could you tell me the password for the Wi-Fi here?',
    japaneseSentence: 'ここのWi-Fiのパスワードを教えていただけますか？',
    japaneseReply: 'はい、レシートに書いてあります。',
    incorrectOptions: [
      '明日の会議の資料はもう準備できましたか？',
      '最近体調を崩してしまって大変でした。',
      '来週の土曜日に一緒に出かけませんか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '客',
    receiverVoice: 'male',
    receiverRole: '店員',
    place: 'カフェ',
  },
  {
    englishSentence: 'Would it be alright if I paid separately?',
    japaneseSentence: '別々にお会計してもいいですか？',
    japaneseReply: 'はい、大丈夫です。分けて計算しますね。',
    incorrectOptions: [
      'その映画は本当に感動的でしたね。',
      '駅の近くに新しい店ができましたよ。',
      '今度一緒に運動を始めませんか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '客',
    receiverVoice: 'female',
    receiverRole: '店員',
    place: 'レストラン',
  },
  {
    englishSentence: 'Could you tell me how to get to the nearest police station?',
    japaneseSentence: '一番近い交番へはどう行けばいいですか？',
    japaneseReply: 'あの信号を渡ってすぐです。',
    incorrectOptions: [
      '昨日は雨が降ってとても寒かったです。',
      '明日の予定を一緒に確認しませんか？',
      '最近は料理を練習するのが楽しいです。',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '旅行者',
    receiverVoice: 'male',
    receiverRole: '通行人',
    place: '道',
  },
];

export default problems;
