import { SeedProblemData } from '../src/types/problem';

const problems: SeedProblemData[] = [
  {
    englishSentence: 'Are you okay?',
    japaneseSentence: '大丈夫？',
    japaneseReply: 'うん、大丈夫だよ。',
    incorrectOptions: ['危ないよ。', '眠いよ。', 'すぐ帰るよ。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '友達',
    receiverVoice: 'male',
    receiverRole: '友達',
    place: '学校',
  },
  {
    englishSentence: 'Where is the station?',
    japaneseSentence: '駅はどこですか？',
    japaneseReply: 'この道をまっすぐ行くとあります。',
    incorrectOptions: ['駅で働いています。', '駅は嫌いです。', '駅に行きたくないです。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '旅行者',
    receiverVoice: 'female',
    receiverRole: '地元の人',
    place: '道',
  },
  {
    englishSentence: 'Water, please.',
    japaneseSentence: '水をください。',
    japaneseReply: 'かしこまりました。',
    incorrectOptions: ['水が嫌いです。', '水は高いです。', '水は外にあります。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '客',
    receiverVoice: 'female',
    receiverRole: '店員',
    place: 'レストラン',
  },
  {
    englishSentence: 'How much is this?',
    japaneseSentence: 'これいくらですか？',
    japaneseReply: '500円です。',
    incorrectOptions: ['今日は雨です。', '安くないです。', 'わかりません。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '客',
    receiverVoice: 'male',
    receiverRole: '店員',
    place: '店',
  },
  {
    englishSentence: 'Where do you live?',
    japaneseSentence: 'どこに住んでいますか？',
    japaneseReply: '東京に住んでいます。',
    incorrectOptions: ['学校に行きます。', '今日は忙しいです。', '仕事は楽しいです。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '友達',
    receiverVoice: 'female',
    receiverRole: '友達',
    place: '公園',
  },
  {
    englishSentence: 'Do you have plans for tomorrow?',
    japaneseSentence: '明日の予定はありますか？',
    japaneseReply: 'はい、友達と会います。',
    incorrectOptions: ['今日は疲れました。', 'お金がありません。', '家が遠いです。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '同僚',
    receiverVoice: 'male',
    receiverRole: '同僚',
    place: '会社',
  },
  {
    englishSentence: 'Excuse me, where is the restroom?',
    japaneseSentence: 'すみません、トイレはどこですか？',
    japaneseReply: '奥の左にあります。',
    incorrectOptions: ['お金が必要です。', '外は寒いです。', '駅にあります。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '客',
    receiverVoice: 'female',
    receiverRole: '店員',
    place: 'カフェ',
  },
  {
    englishSentence: 'What time is it now?',
    japaneseSentence: '今何時ですか？',
    japaneseReply: '3時です。',
    incorrectOptions: ['今日は日曜日です。', '駅は遠いです。', '私は元気です。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '旅行者',
    receiverVoice: 'male',
    receiverRole: '通行人',
    place: '道',
  },
  {
    englishSentence: 'What is your name?',
    japaneseSentence: '名前は何ですか？',
    japaneseReply: '田中です。',
    incorrectOptions: ['元気です。', 'お腹がすきました。', '今日は雨です。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '新入生',
    receiverVoice: 'female',
    receiverRole: '学生',
    place: '学校',
  },
  {
    englishSentence: 'Help!',
    japaneseSentence: '助けて！',
    japaneseReply: '大丈夫ですか？警察を呼びますか？',
    incorrectOptions: ['いい天気ですね。', 'お腹がすきました。', '遊びに行きましょう。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '人',
    receiverVoice: 'male',
    receiverRole: '通行人',
    place: '道',
  },
  {
    englishSentence: 'What day is it today?',
    japaneseSentence: '今日は何曜日ですか？',
    japaneseReply: '火曜日です。',
    incorrectOptions: ['5時です。', '駅に行きます。', '元気です。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '旅行者',
    receiverVoice: 'female',
    receiverRole: '店員',
    place: 'ホテル',
  },
  {
    englishSentence: 'What’s your hobby?',
    japaneseSentence: '趣味は何ですか？',
    japaneseReply: '読書が好きです。',
    incorrectOptions: ['駅に行きます。', '今日は雨です。', '私は会社員です。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '友達',
    receiverVoice: 'male',
    receiverRole: '友達',
    place: '公園',
  },
  {
    englishSentence: 'Whose bag is this?',
    japaneseSentence: 'これは誰のカバンですか？',
    japaneseReply: '私のカバンです。',
    incorrectOptions: ['駅にあります。', '雨が降っています。', '美味しいです。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '学生',
    receiverVoice: 'female',
    receiverRole: '学生',
    place: '学校',
  },
  {
    englishSentence: 'Is this seat free?',
    japaneseSentence: '席、空いていますか？',
    japaneseReply: 'はい、どうぞ。',
    incorrectOptions: ['駅は遠いです。', 'お金がありません。', '今日は眠いです。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '乗客',
    receiverVoice: 'male',
    receiverRole: '乗客',
    place: '電車',
  },
  {
    englishSentence: 'Where is the hospital?',
    japaneseSentence: '病院はどこですか？',
    japaneseReply: 'あの角を左に曲がるとあります。',
    incorrectOptions: ['学校に行きます。', '私は医者です。', '今日は忙しいです。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '通行人',
    receiverVoice: 'female',
    receiverRole: '地元の人',
    place: '道',
  },
  {
    englishSentence: 'Are you sleepy?',
    japaneseSentence: '眠いですか？',
    japaneseReply: 'はい、少し眠いです。',
    incorrectOptions: ['駅に行きます。', 'お金がありません。', '今日は雨です。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '友達',
    receiverVoice: 'male',
    receiverRole: '友達',
    place: '学校',
  },
  {
    englishSentence: 'Excuse me, do you speak English?',
    japaneseSentence: 'すみません、英語は話せますか？',
    japaneseReply: '少しだけ話せます。',
    incorrectOptions: ['私は学生です。', '駅は遠いです。', '今日は日曜日です。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '旅行者',
    receiverVoice: 'female',
    receiverRole: '地元の人',
    place: '道',
  },
  {
    englishSentence: 'Coffee, please.',
    japaneseSentence: 'コーヒーをください。',
    japaneseReply: 'かしこまりました。',
    incorrectOptions: ['私は医者です。', '今日は暑いです。', '駅に行きます。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '客',
    receiverVoice: 'male',
    receiverRole: '店員',
    place: 'カフェ',
  },
  {
    englishSentence: 'Did you finish your homework?',
    japaneseSentence: '宿題は終わりましたか？',
    japaneseReply: 'はい、もう終わりました。',
    incorrectOptions: ['今日は暑いです。', '駅に行きます。', '私は眠いです。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '先生',
    receiverVoice: 'female',
    receiverRole: '学生',
    place: '学校',
  },
  {
    englishSentence: 'I’m hungry.',
    japaneseSentence: 'お腹がすきました。',
    japaneseReply: 'じゃあ、ご飯を食べに行きましょう。',
    incorrectOptions: ['今日は日曜日です。', '駅は近いです。', '私は学生です。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '友達',
    receiverVoice: 'male',
    receiverRole: '友達',
    place: '公園',
  },
  {
    englishSentence: 'It’s hot today.',
    japaneseSentence: '今日は暑いですね。',
    japaneseReply: '本当に暑いですね。アイスを食べたいです。',
    incorrectOptions: ['駅に行きます。', '私は先生です。', 'お金がありません。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '友達',
    receiverVoice: 'female',
    receiverRole: '友達',
    place: '道',
  },
  {
    englishSentence: 'Where is the bus stop?',
    japaneseSentence: 'バス停はどこですか？',
    japaneseReply: 'あの建物の前にあります。',
    incorrectOptions: ['駅は近いです。', '今日は眠いです。', '私は元気です。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '旅行者',
    receiverVoice: 'male',
    receiverRole: '地元の人',
    place: '道',
  },
  {
    englishSentence: 'Will it rain tomorrow?',
    japaneseSentence: '明日、雨が降りますか？',
    japaneseReply: '天気予報では晴れです。',
    incorrectOptions: ['今日は暑いです。', '私は医者です。', '駅に行きます。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '旅行者',
    receiverVoice: 'female',
    receiverRole: 'ホテルスタッフ',
    place: 'ホテル',
  },
  {
    englishSentence: 'Please turn off the light.',
    japaneseSentence: '電気を消してください。',
    japaneseReply: 'はい、わかりました。',
    incorrectOptions: ['駅は近いです。', '今日は日曜日です。', '私は学生です。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '同居人',
    receiverVoice: 'male',
    receiverRole: '同居人',
    place: '家',
  },
  {
    englishSentence: 'What would you like to drink?',
    japaneseSentence: '何を飲みますか？',
    japaneseReply: 'コーヒーをお願いします。',
    incorrectOptions: ['駅に行きます。', '今日は雨です。', '私は眠いです。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '友達',
    receiverVoice: 'female',
    receiverRole: '友達',
    place: 'カフェ',
  },
  {
    englishSentence: 'How old are you?',
    japaneseSentence: '何歳ですか？',
    japaneseReply: '20歳です。',
    incorrectOptions: ['今日は雨です。', '私は先生です。', '駅に行きます。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '新入生',
    receiverVoice: 'male',
    receiverRole: '学生',
    place: '学校',
  },
  {
    englishSentence: 'Did you enjoy the trip?',
    japaneseSentence: '旅行は楽しかったですか？',
    japaneseReply: 'はい、とても楽しかったです。',
    incorrectOptions: ['今日は雨です。', '駅に行きます。', '私は眠いです。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '友達',
    receiverVoice: 'female',
    receiverRole: '友達',
    place: 'カフェ',
  },
  {
    englishSentence: 'Does this train go to Shinjuku?',
    japaneseSentence: 'この電車は新宿に行きますか？',
    japaneseReply: 'はい、新宿に行きます。',
    incorrectOptions: ['今日は雨です。', '私は医者です。', '駅に行きます。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '旅行者',
    receiverVoice: 'male',
    receiverRole: '駅員',
    place: '駅',
  },
  {
    englishSentence: 'Are you free this weekend?',
    japaneseSentence: '今週末、暇ですか？',
    japaneseReply: 'はい、空いています。',
    incorrectOptions: ['駅に行きます。', '私は医者です。', '今日は眠いです。'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '友達',
    receiverVoice: 'female',
    receiverRole: '友達',
    place: '学校',
  },
];

export default problems;
