import type { ProblemWithAudio } from '@/lib/problem-service';

const problems: ProblemWithAudio[] = [
  {
    id: `cmfx5ayr30010s94fsjuaki0y`,
    wordCount: 11,
    englishSentence: `Would it be possible to change my appointment to next Monday?`,
    japaneseSentence: `予約を来週の月曜日に変更することは可能ですか？`,
    japaneseReply: `はい、大丈夫です。変更しておきます。`,
    englishReply: `Yes, that’s fine. I’ll change it to Monday.`,
    incorrectOptions: [
      '先生の診察時間を教えていただけますか？',
      '薬の受け取りはいつが便利ですか？',
      'すみません、次の予約は何時か確認していただけますか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30010s94fsjuaki0y_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30010s94fsjuaki0y_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30010s94fsjuaki0y_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr30010s94fsjuaki0y_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `患者`,
    receiverVoice: 'male',
    receiverRole: `受付`,
    place: `病院`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧で落ち着いた、少し不安そうに予定変更を尋ねる`,
    receiverVoiceInstruction: `親切で落ち着いた丁寧な話し方、安心させるトーン`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-08T07:14:49.613Z`),
  },
  {
    id: `cmfx5ayr4001hs94fr95e03ag`,
    wordCount: 11,
    englishSentence: `Would it be possible to extend my stay for another night?`,
    japaneseSentence: `宿泊をもう一泊延長することはできますか？`,
    japaneseReply: `はい、空室がありますので可能です。`,
    englishReply: `Yes, we have a room available.`,
    incorrectOptions: [
      'チェックアウトの時間を教えてください。',
      '朝食の時間は何時からですか？',
      '部屋をとても散らかしてしまったので早く掃除してください。',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001hs94fr95e03ag_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001hs94fr95e03ag_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001hs94fr95e03ag_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr4001hs94fr95e03ag_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `客`,
    receiverVoice: 'female',
    receiverRole: `ホテルスタッフ`,
    place: `ホテル`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧で控えめに、滞在延長が可能か尋ねる`,
    receiverVoiceInstruction: `親切で落ち着いた丁寧な話し方、安心させるトーン`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-08T07:14:52.829Z`),
  },
  {
    id: `cmfx5ayr3000zs94f6i4nl25s`,
    wordCount: 12,
    englishSentence: `Do you know where I can buy a SIM card around here?`,
    japaneseSentence: `この辺りでSIMカードを買える場所を知っていますか？`,
    japaneseReply: `はい、駅前の電気屋で買えますよ。`,
    englishReply: `Yes, you can buy one at the electronics store near the station.`,
    incorrectOptions: [
      'すみません、近くにカフェはありますか？',
      'この道をまっすぐ行くと駅に着きますか？',
      'この辺りでポ〇モンカードを買える場所を知っていますか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr3000zs94f6i4nl25s_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr3000zs94f6i4nl25s_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr3000zs94f6i4nl25s_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr3000zs94f6i4nl25s_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `旅行者`,
    receiverVoice: 'female',
    receiverRole: `地元の人`,
    place: `道`,
    scenePrompt: null,
    senderVoiceInstruction: `落ち着いて丁寧に、困っている様子を含めて話す`,
    receiverVoiceInstruction: `親切で落ち着いた丁寧な話し方`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-08T07:14:52.025Z`),
  },
  {
    id: `cmfx5ayr30011s94f1q3eth2a`,
    wordCount: 15,
    englishSentence: `Could you tell me how long it takes to get to the museum from here?`,
    japaneseSentence: `ここから博物館までどのくらい時間がかかりますか？`,
    japaneseReply: `徒歩で十五分ほどです。`,
    englishReply: `It takes about fifteen minutes on foot.`,
    incorrectOptions: [
      'すみません、この道は駅まで続いていますか？',
      'あの、この近くにバス停はありますか？教えてください。',
      'この辺りでおすすめのレストランはありますか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30011s94f1q3eth2a_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30011s94f1q3eth2a_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30011s94f1q3eth2a_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr30011s94f1q3eth2a_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `旅行者`,
    receiverVoice: 'female',
    receiverRole: `通行人`,
    place: `道`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧で落ち着いたトーンで、少し興味を持って質問する`,
    receiverVoiceInstruction: `親切で明快に、はっきりと答える丁寧な口調`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-08T07:14:51.226Z`),
  },
  {
    id: `cmfx5ayr30019s94f4xp54zsf`,
    wordCount: 11,
    englishSentence: `Could you tell me how to get to the nearest pharmacy?`,
    japaneseSentence: `一番近い薬局へはどう行けばいいですか？`,
    japaneseReply: `あの信号を渡ってすぐです。`,
    englishReply: `Cross that light and it’s right there.`,
    incorrectOptions: [
      'すみません、駅まではどうやって行きますか？',
      '近くのコンビニはどちらの方向ですか？',
      'この道をまっすぐ行くと公園がありますか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30019s94f4xp54zsf_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30019s94f4xp54zsf_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30019s94f4xp54zsf_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr30019s94f4xp54zsf_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `旅行者`,
    receiverVoice: 'female',
    receiverRole: `通行人`,
    place: `道`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧で落ち着いたトーンで、礼儀正しく質問する`,
    receiverVoiceInstruction: `シンプルで親切、わかりやすく案内する優しい口調`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-08T07:14:53.228Z`),
  },
  {
    id: `cmfx5ayr4001as94fhose3uon`,
    wordCount: 11,
    englishSentence: `Would you mind if I borrowed your pen for a moment?`,
    japaneseSentence: `ちょっとペンを貸していただけますか？`,
    japaneseReply: `どうぞ、使ってください。`,
    englishReply: `Sure, go ahead.`,
    incorrectOptions: [
      'すみません、ノートを見せてもらえますか？',
      '先生、質問してもよろしいですか？',
      '先生、何も分からないので宿題の答えを教えてもらえますか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001as94fhose3uon_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001as94fhose3uon_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001as94fhose3uon_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr4001as94fhose3uon_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `学生`,
    receiverVoice: 'male',
    receiverRole: `学生`,
    place: `学校`,
    scenePrompt: null,
    senderVoiceInstruction: `カジュアルで親しみやすく、軽くお願いするようなトーン`,
    receiverVoiceInstruction: `明るく快く、フレンドリーに応じる話し方`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-08T07:14:50.016Z`),
  },
  {
    id: `cmfx5ayr4001ms94fjn0tr2m9`,
    wordCount: 12,
    englishSentence: `Could you tell me how to get to the nearest police station?`,
    japaneseSentence: `一番近い交番へはどう行けばいいですか？`,
    japaneseReply: `あの信号を渡ってすぐです。`,
    englishReply: `Cross that light and it’s right there.`,
    incorrectOptions: [
      'すみません、駅まではどの道を行きますか？',
      '近くにバス停はありますか、教えてください。',
      'この辺りでおすすめのレストランはありますか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001ms94fjn0tr2m9_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001ms94fjn0tr2m9_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001ms94fjn0tr2m9_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr4001ms94fjn0tr2m9_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `旅行者`,
    receiverVoice: 'male',
    receiverRole: `通行人`,
    place: `道`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧に道を尋ねる、少し困惑した感じで`,
    receiverVoiceInstruction: `明るく親切に、簡潔に答える`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-08T07:14:51.625Z`),
  },
  {
    id: `cmfx5ayr4001es94fvtz61wmh`,
    wordCount: 11,
    englishSentence: `Would you mind taking a photo of us with this camera?`,
    japaneseSentence: `このカメラで写真を撮っていただけますか？`,
    japaneseReply: `もちろんです。どの角度がいいですか？`,
    englishReply: `Of course. Which angle do you prefer?`,
    incorrectOptions: [
      'この場所のおすすめスポットはどこですか？',
      '近くに美味しいレストランはありますか？',
      'このカメラを100万円で買ってもらえますか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001es94fvtz61wmh_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001es94fvtz61wmh_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001es94fvtz61wmh_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr4001es94fvtz61wmh_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `旅行者`,
    receiverVoice: 'male',
    receiverRole: `通行人`,
    place: `観光地`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧でお願いするような柔らかいトーン`,
    receiverVoiceInstruction: `快く引き受ける明るく親しみやすい話し方`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-08T07:14:50.828Z`),
  },
  {
    id: `cmfx5ayr3000ws94fzqbktx12`,
    wordCount: 11,
    englishSentence: `Excuse me, do you have any tables available without a reservation?`,
    japaneseSentence: `すみません、予約していないのですが席はありますか？`,
    japaneseReply: `少々お待ちください。はい、大丈夫です、ご案内します。`,
    englishReply: `Please wait a moment. Yes, we have a table for you.`,
    incorrectOptions: [
      'すみません、メニューをもう一度見せてください。',
      'すみません、今日のおすすめ料理は何ですか？',
      'すみません、予約しているのですが私なんて入店できませんよね？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr3000ws94fzqbktx12_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr3000ws94fzqbktx12_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr3000ws94fzqbktx12_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-10-09/cmfx5ayr3000ws94fzqbktx12_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `客`,
    receiverVoice: 'male',
    receiverRole: `店員`,
    place: `レストラン`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧で控えめに、予約なしで席があるか尋ねる`,
    receiverVoiceInstruction: `丁寧で落ち着いた、少し待ってもらうことを詫びる気持ちを込めて`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-09T06:22:34.444Z`),
  },
  {
    id: `cmfx5ayr3000xs94fqe74oiqz`,
    wordCount: 12,
    englishSentence: `Could you send me the materials from last week’s meeting by email?`,
    japaneseSentence: `先週の会議の資料をメールで送っていただけますか？`,
    japaneseReply: `はい、後ほどお送りします。`,
    englishReply: `Yes, I’ll send them to you later.`,
    incorrectOptions: [
      '来週のプレゼンの準備はやめて、これから飲みに行きましょう。',
      '今日の会議は何時から始まりますか？',
      '新しいプロジェクトの詳細を教えてください。',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr3000xs94fqe74oiqz_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr3000xs94fqe74oiqz_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr3000xs94fqe74oiqz_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr3000xs94fqe74oiqz_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `同僚`,
    receiverVoice: 'female',
    receiverRole: `同僚`,
    place: `会社`,
    scenePrompt: null,
    senderVoiceInstruction: `ビジネスライクで丁寧、しかしフレンドリーなトーンで依頼するように`,
    receiverVoiceInstruction: `丁寧で落ち着いたビジネス的な話し方`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-08T07:14:49.195Z`),
  },
  {
    id: `cmfx5ayr30012s94fkghbjiem`,
    wordCount: 11,
    englishSentence: `Do you know if there is Wi-Fi available in this café?`,
    japaneseSentence: `このカフェにWi-Fiはありますか？`,
    japaneseReply: `はい、パスワードはこちらです。`,
    englishReply: `Yes, here is the password.`,
    incorrectOptions: [
      'このカフェの営業時間は何時ですか？',
      'おすすめのケーキはどれですか？',
      '店内は禁煙ですか、教えてください。',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30012s94fkghbjiem_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30012s94fkghbjiem_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30012s94fkghbjiem_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr30012s94fkghbjiem_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `客`,
    receiverVoice: 'male',
    receiverRole: `店員`,
    place: `カフェ`,
    scenePrompt: null,
    senderVoiceInstruction: `カジュアルで興味を持っている様子を込めて、穏やかなトーン`,
    receiverVoiceInstruction: `明るく親切に、はっきりと教える丁寧な話し方`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-08T07:15:03.959Z`),
  },
  {
    id: `cmg3a4qu20005bleknloiypst`,
    wordCount: 15,
    englishSentence: `When did the pain start, and how has it changed over the last few days?`,
    japaneseSentence: `痛みがいつ始まって、この数日でどう変化したのか教えていただけますか？`,
    japaneseReply: `月曜日から始まって、どんどん悪化しています。`,
    englishReply: `It started on Monday and has been getting worse.`,
    incorrectOptions: [
      '症状がいつから始まったかは言わないでください。表情で何もかも分かりますので。',
      'ゆっくりでいいので、最近の体調の変化について詳しく話してください。',
      '痛みの程度や頻度について教えてもらえますか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu20005bleknloiypst_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu20005bleknloiypst_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu20005bleknloiypst_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-28/cmg3a4qu20005bleknloiypst_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `医者`,
    receiverVoice: 'male',
    receiverRole: `患者`,
    place: `病院の診察室`,
    scenePrompt: null,
    senderVoiceInstruction: `真剣で慎重な医者らしい落ち着いた問いかけのトーン`,
    receiverVoiceInstruction: `やや辛そうで正直に状況を伝える、落ち着いた口調`,
    createdAt: new Date(`2025-09-28T05:49:03.573Z`),
    updatedAt: new Date(`2025-10-08T07:14:56.395Z`),
  },
  {
    id: `cmg3a4qu3000eblekn4yv0u4o`,
    wordCount: 15,
    englishSentence: `How long will I need to wait before the doctor can see me this afternoon?`,
    japaneseSentence: `今日の午後、先生に診てもらうまでどのくらい待ちますか？`,
    japaneseReply: `あと二十分ほどで診察に呼ばれると思います。`,
    englishReply: `It should be about twenty minutes from now.`,
    incorrectOptions: [
      'すみません、いま診察の順番はどのくらいですか？',
      '受付の時間は何時までですか？',
      '予約はしていないのですが、診てもらえますか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu3000eblekn4yv0u4o_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu3000eblekn4yv0u4o_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu3000eblekn4yv0u4o_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-28/cmg3a4qu3000eblekn4yv0u4o_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `患者`,
    receiverVoice: 'male',
    receiverRole: `看護師`,
    place: `病院の待合室`,
    scenePrompt: null,
    senderVoiceInstruction: `不安そうに丁寧に確認する話し方`,
    receiverVoiceInstruction: `優しく安心させるように、丁寧で落ち着いた話し方`,
    createdAt: new Date(`2025-09-28T05:49:03.573Z`),
    updatedAt: new Date(`2025-10-08T07:14:57.977Z`),
  },
  {
    id: `cmg3a4qu3000cblekf6t3q9e5`,
    wordCount: 14,
    englishSentence: `How long is the wait for a table for four without a reservation tonight?`,
    japaneseSentence: `今夜予約なしで四人席を待つ場合、どのくらいかかりますか？`,
    japaneseReply: `お席まで三十分ほどお待ちいただきます。`,
    englishReply: `It’ll be about thirty minutes for a table.`,
    incorrectOptions: [
      'この間、いろんなものを壊してしまったのですが、また入店できますか？',
      '今夜の空席状況について走りたくないので教えないでください。',
      '二人なんですが、今って入店できますか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu3000cblekf6t3q9e5_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu3000cblekf6t3q9e5_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu3000cblekf6t3q9e5_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-28/cmg3a4qu3000cblekf6t3q9e5_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `客`,
    receiverVoice: 'male',
    receiverRole: `ホスト`,
    place: `レストランの入り口`,
    scenePrompt: null,
    senderVoiceInstruction: `少し焦り気味でカジュアルに尋ねる話し方`,
    receiverVoiceInstruction: `落ち着いて丁寧に、現状を説明する話し方`,
    createdAt: new Date(`2025-09-28T05:49:03.573Z`),
    updatedAt: new Date(`2025-10-08T07:14:54.414Z`),
  },
  {
    id: `cmg3a4qu3000hblek8cksc51y`,
    wordCount: 12,
    englishSentence: `I forgot my PIN. How can I reset it on this machine?`,
    japaneseSentence: `暗証番号を忘れてしまったので、この機械でリセットする方法を教えていただけますか？`,
    japaneseReply: `こちらではできませんので窓口でお手続きください。`,
    englishReply: `You can’t reset it here, please apply at the counter.`,
    incorrectOptions: [
      'すみません、ATMの使い方を詳しく教えてもらえますか？悪いことはしませんので。',
      'カードの紛失時の対応方法を教えていただけますか？',
      '現金の引き出し手順をもう一度説明してもらえますか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu3000hblek8cksc51y_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu3000hblek8cksc51y_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu3000hblek8cksc51y_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-28/cmg3a4qu3000hblek8cksc51y_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `利用客`,
    receiverVoice: 'female',
    receiverRole: `銀行員`,
    place: `銀行のATM前`,
    scenePrompt: null,
    senderVoiceInstruction: `困惑しつつも丁寧に質問するトーンで`,
    receiverVoiceInstruction: `丁寧で冷静に、手続き方法を案内する話し方で`,
    createdAt: new Date(`2025-09-28T05:49:03.573Z`),
    updatedAt: new Date(`2025-10-08T07:14:58.770Z`),
  },
  {
    id: `cmg3a4qu20009blekr6wkeo0l`,
    wordCount: 15,
    englishSentence: `Could you make this coffee extra hot? It usually gets cold very quickly for me.`,
    japaneseSentence: `このコーヒーを特に熱くしてもらえますか？いつもすぐ冷めてしまうので。`,
    japaneseReply: `もちろんです、今回は熱めにお作りします。`,
    englishReply: `Of course, I’ll make sure it’s very hot this time.`,
    incorrectOptions: [
      'すみません、メニューのおすすめはどれですか？一番人気のコーヒーを教えてください。',
      'すみません、もう食べてしまったんですが、注文を変更してもいいですか？',
      'すみません、お会計をお願いします。',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu20009blekr6wkeo0l_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu20009blekr6wkeo0l_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu20009blekr6wkeo0l_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-28/cmg3a4qu20009blekr6wkeo0l_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `客`,
    receiverVoice: 'male',
    receiverRole: `店員`,
    place: `カフェのカウンター`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧で少し心配そうに、熱さに対する要望をはっきり伝える話し方`,
    receiverVoiceInstruction: `親切で落ち着いた丁寧な口調で、安心させるように優しく話す`,
    createdAt: new Date(`2025-09-28T05:49:03.573Z`),
    updatedAt: new Date(`2025-10-08T07:14:56.790Z`),
  },
  {
    id: `cmg3a4qu3000bblek3iyxpztn`,
    wordCount: 15,
    englishSentence: `Does this boarding pass allow me to bring both a carry-on and a personal bag?`,
    japaneseSentence: `この搭乗券で機内持ち込み荷物と手荷物を両方持って入れますか？`,
    japaneseReply: `はい、手荷物と小物の二点は持ち込み可能です。`,
    englishReply: `Yes, one carry-on and one personal item are allowed.`,
    incorrectOptions: [
      'すみません、搭乗手続きはどこで行われるか教えていただけますか？',
      '手荷物の重量制限が何キロまでなのか教えていただけますか？',
      '搭乗口はどの方向にありますか？あちらの方向ですか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu3000bblek3iyxpztn_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu3000bblek3iyxpztn_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu3000bblek3iyxpztn_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-10-09/cmg3a4qu3000bblek3iyxpztn_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `乗客`,
    receiverVoice: 'female',
    receiverRole: `係員`,
    place: `空港の搭乗ゲート`,
    scenePrompt: null,
    senderVoiceInstruction: `フォーマルで落ち着いた質問口調、確認したい気持ちを込めて話す`,
    receiverVoiceInstruction: `丁寧で明確に説明する、落ち着いた安心感のある話し方`,
    createdAt: new Date(`2025-09-28T05:49:03.573Z`),
    updatedAt: new Date(`2025-10-09T06:44:53.899Z`),
  },
  {
    id: `cmg3a4qu3000gblekb68m3set`,
    wordCount: 13,
    englishSentence: `Can I use both a coupon and a point card for this purchase?`,
    japaneseSentence: `この買い物でクーポンとポイントカードを両方使えますか？`,
    japaneseReply: `はい、今回は両方一緒にご利用いただけます。`,
    englishReply: `Yes, you can use both together for this purchase.`,
    incorrectOptions: [
      'ポイントカードを作りたいんですが、どこで作れますか？',
      'クーポンの利用条件を教えてください。',
      'いきなり何なんですか！私は何も盗んでいません！',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu3000gblekb68m3set_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu3000gblekb68m3set_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu3000gblekb68m3set_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-28/cmg3a4qu3000gblekb68m3set_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `客`,
    receiverVoice: 'male',
    receiverRole: `レジ係`,
    place: `スーパーのレジ`,
    scenePrompt: null,
    senderVoiceInstruction: `疑問を持ちながらも控えめに尋ねる丁寧な話し方`,
    receiverVoiceInstruction: `はきはきと親切に、安心させる丁寧な話し方`,
    createdAt: new Date(`2025-09-28T05:49:03.573Z`),
    updatedAt: new Date(`2025-10-09T06:48:27.587Z`),
  },
  {
    id: `cmg3a4qu10003blekzvzn5k0s`,
    wordCount: 14,
    englishSentence: `I’d like you to prepare a report on recent sales trends and customer feedback.`,
    japaneseSentence: `最近の売上動向と顧客の声をまとめた報告書を用意してください。`,
    japaneseReply: `承知しました、明日までに詳しい報告書を作成します。`,
    englishReply: `Understood, I’ll prepare a detailed report by tomorrow.`,
    incorrectOptions: [
      '次回の会議の資料を準備していただきますようお願いいたします。',
      '新しいプロジェクトの進捗を報告してください。',
      '今月の売上データを作ったのは誰ですか？内容が間違っていると思うのですが。',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu10003blekzvzn5k0s_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu10003blekzvzn5k0s_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu10003blekzvzn5k0s_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-28/cmg3a4qu10003blekzvzn5k0s_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `上司`,
    receiverVoice: 'male',
    receiverRole: `部下`,
    place: `会社の会議室`,
    scenePrompt: null,
    senderVoiceInstruction: `厳しくも丁寧で指示を出すフォーマルな話し方`,
    receiverVoiceInstruction: `真面目で誠実に、責任感を込めた丁寧な話し方`,
    createdAt: new Date(`2025-09-28T05:49:03.573Z`),
    updatedAt: new Date(`2025-10-08T07:14:55.598Z`),
  },
  {
    id: `cmg3a4qu20006blekspmijepd`,
    wordCount: 13,
    englishSentence: `Are there still any seats available in the middle rows for tonight’s show?`,
    japaneseSentence: `今日の夜の上映で真ん中の列に空席はありますか？`,
    japaneseReply: `はい、真ん中の席が少し残っています。`,
    englishReply: `Yes, there are still a few seats left in the middle.`,
    incorrectOptions: [
      '今日の上映時間は何時からですか？',
      'チケットはまだ買えますか？',
      'とても混んでいますね。この映画はそんなに人気なんですか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu20006blekspmijepd_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu20006blekspmijepd_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu20006blekspmijepd_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-28/cmg3a4qu20006blekspmijepd_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `客`,
    receiverVoice: 'female',
    receiverRole: `スタッフ`,
    place: `映画館のチケットカウンター`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧で少し不安げに、静かに質問する話し方`,
    receiverVoiceInstruction: `落ち着いて親切に、安心させる丁寧な話し方`,
    createdAt: new Date(`2025-09-28T05:49:03.573Z`),
    updatedAt: new Date(`2025-10-08T07:15:00.743Z`),
  },
  {
    id: `cmg3a4qu4000iblekmblsc820`,
    wordCount: 13,
    englishSentence: `Would you like your latte with regular milk, or almond or soy milk?`,
    japaneseSentence: `ラテは普通の牛乳にしますか、それともアーモンドか豆乳にしますか？`,
    japaneseReply: `豆乳でお願いします、ありがとうございます。`,
    englishReply: `Soy milk would be great, thank you.`,
    incorrectOptions: [
      'すみません、メニューのおすすめを教えてください。',
      'すみません、注文を変更してもいいですか？パインジュースは無しにしてください。',
      'すみません、お会計をお願いします。',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu4000iblekmblsc820_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu4000iblekmblsc820_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu4000iblekmblsc820_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-28/cmg3a4qu4000iblekmblsc820_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `店員`,
    receiverVoice: 'male',
    receiverRole: `客`,
    place: `カフェのカウンター`,
    scenePrompt: null,
    senderVoiceInstruction: `明るく親しみやすく、カジュアルに聞く話し方`,
    receiverVoiceInstruction: `礼儀正しく丁寧に、感謝の気持ちを込めて`,
    createdAt: new Date(`2025-09-28T05:49:03.573Z`),
    updatedAt: new Date(`2025-10-08T07:14:59.955Z`),
  },
  {
    id: `cmg3a4qu10001blekabvxo21d`,
    wordCount: 14,
    englishSentence: `Could you confirm if my luggage will be checked through to my final destination?`,
    japaneseSentence: `荷物が最終目的地まで運ばれるか確認していただけますか？`,
    japaneseReply: `はい、お荷物は最終目的地まで直行します。`,
    englishReply: `Yes, your bag will go directly to your last stop.`,
    incorrectOptions: [
      '搭乗手続きがどこで行われるか教えていただけますか？',
      '手荷物の重量制限が何キロまでなのか教えていただけますか？',
      '初めて来たのですが、搭乗口はどちらにありますか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu10001blekabvxo21d_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu10001blekabvxo21d_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu10001blekabvxo21d_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-28/cmg3a4qu10001blekabvxo21d_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `乗客`,
    receiverVoice: 'male',
    receiverRole: `係員`,
    place: `空港のチェックインカウンター`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧で不安げに確認する話し方`,
    receiverVoiceInstruction: `落ち着いて親切に、安心感を与える丁寧な話し方`,
    createdAt: new Date(`2025-09-28T05:49:03.573Z`),
    updatedAt: new Date(`2025-10-08T07:14:55.204Z`),
  },
  {
    id: `cmg3a4qu3000dblekfprve2vv`,
    wordCount: 12,
    englishSentence: `Could you explain step by step how you solved this math problem?`,
    japaneseSentence: `その数学の問題を解いた手順を順番に説明してください。`,
    japaneseReply: `はい、まず両辺を二で割りました。`,
    englishReply: `Okay, I started by dividing both sides by two.`,
    incorrectOptions: [
      'この問題の答えを自分で説明してください。',
      '教科書の内容を自分の言葉で話してください。',
      'ノートにパラパラ漫画ばかり書いていないで勉強してください。',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu3000dblekfprve2vv_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu3000dblekfprve2vv_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu3000dblekfprve2vv_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-28/cmg3a4qu3000dblekfprve2vv_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `教師`,
    receiverVoice: 'female',
    receiverRole: `生徒`,
    place: `学校の教室`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧で落ち着いた、説明を求めるトーンで`,
    receiverVoiceInstruction: `分かりやすく丁寧に、落ち着いて説明する話し方で`,
    createdAt: new Date(`2025-09-28T05:49:03.573Z`),
    updatedAt: new Date(`2025-10-08T07:14:59.167Z`),
  },
  {
    id: `cmg3a4qu20007blekqqh8gmel`,
    wordCount: 13,
    englishSentence: `Could you explain how to transfer money internationally and what the fees are?`,
    japaneseSentence: `海外送金の方法と手数料について教えていただけますか？`,
    japaneseReply: `はい、手順と費用を今ご説明します。`,
    englishReply: `Yes, I’ll explain the steps and costs to you now.`,
    incorrectOptions: [
      '口座開設に必要な書類を持ってきました。すぐに口座を開設してもらえますか？',
      'ATMの利用時間を教えてください。',
      '振込手数料が毎回無料になる裏技を教えてください。',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu20007blekqqh8gmel_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu20007blekqqh8gmel_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu20007blekqqh8gmel_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-28/cmg3a4qu20007blekqqh8gmel_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `客`,
    receiverVoice: 'male',
    receiverRole: `銀行員`,
    place: `銀行の窓口`,
    scenePrompt: null,
    senderVoiceInstruction: `真剣で分かりやすく説明する丁寧な話し方`,
    receiverVoiceInstruction: `落ち着いて理解しようとする丁寧な話し方`,
    createdAt: new Date(`2025-09-28T05:49:03.573Z`),
    updatedAt: new Date(`2025-10-08T07:15:01.142Z`),
  },
  {
    id: `cmg3a4qu3000fbleknon0vmu3`,
    wordCount: 12,
    englishSentence: `Can I borrow this magazine, or is it only for reading inside?`,
    japaneseSentence: `この雑誌は借りられるのか、それとも館内だけで読むものなのか教えていただけますか？`,
    japaneseReply: `雑誌は館内閲覧専用で貸出はできません。`,
    englishReply: `Magazines are only for in-library use, not for borrowing.`,
    incorrectOptions: [
      'この本の貸出期間はどのくらいですか？',
      'この書籍は発売終了していて貴重なものですね。私に譲っていただくことはできますか？',
      'カードを持っていないのですが、予約の方法を教えていただけますか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu3000fbleknon0vmu3_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu3000fbleknon0vmu3_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu3000fbleknon0vmu3_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-28/cmg3a4qu3000fbleknon0vmu3_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `利用者`,
    receiverVoice: 'female',
    receiverRole: `司書`,
    place: `図書館の受付`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧で落ち着いた質問のトーンで`,
    receiverVoiceInstruction: `はっきりとした丁寧語で、規則を説明する冷静な話し方で`,
    createdAt: new Date(`2025-09-28T05:49:03.573Z`),
    updatedAt: new Date(`2025-10-08T07:14:59.559Z`),
  },
  {
    id: `cmg3a4qu20008blek9nwgc56d`,
    wordCount: 15,
    englishSentence: `Can this book be renewed again, or do I have to return it by tomorrow?`,
    japaneseSentence: `この本をもう一度延長できるのか、それとも明日までに返さないといけないのか教えてください。`,
    japaneseReply: `明日までに返却が必要で、延長はできません。`,
    englishReply: `You need to return it tomorrow, renewals aren’t allowed.`,
    incorrectOptions: [
      'この本の貸出期間はどのくらいですか？',
      'この図書館はいつからあって、どんな歴史を辿ったのか教えてくださいませんか？',
      '私は隣町に住んでいるのですが、この図書館で本を借りることはできますか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu20008blek9nwgc56d_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu20008blek9nwgc56d_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu20008blek9nwgc56d_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-28/cmg3a4qu20008blek9nwgc56d_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `利用者`,
    receiverVoice: 'female',
    receiverRole: `司書`,
    place: `図書館の受付`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧で確認したい気持ちが伝わる穏やかな話し方`,
    receiverVoiceInstruction: `フォーマルで事務的に、しかし親切に説明する話し方`,
    createdAt: new Date(`2025-09-28T05:49:03.573Z`),
    updatedAt: new Date(`2025-10-08T07:14:55.996Z`),
  },
  {
    id: `cmg3a4qu2000ablekg3aczxow`,
    wordCount: 14,
    englishSentence: `Is breakfast included in the room rate, or do I need to pay separately?`,
    japaneseSentence: `宿泊料金に朝食が含まれているのか、別料金なのか教えていただけますか？`,
    japaneseReply: `朝食は含まれておりますので追加料金は不要です。`,
    englishReply: `Breakfast is included, you don’t need to pay extra.`,
    incorrectOptions: [
      'すみません、チェックアウトの時間は何時になりますか？',
      '早めに部屋の掃除に来てもらうことはできますか？',
      '駐車場の利用料金は宿泊料金に含まれていますか？それとも別ですか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu2000ablekg3aczxow_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu2000ablekg3aczxow_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu2000ablekg3aczxow_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-28/cmg3a4qu2000ablekg3aczxow_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `宿泊客`,
    receiverVoice: 'male',
    receiverRole: `フロントスタッフ`,
    place: `ホテルのフロント`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧に疑問を持って穏やかに尋ねる話し方`,
    receiverVoiceInstruction: `親切で落ち着いた丁寧な話し方`,
    createdAt: new Date(`2025-09-28T05:49:03.573Z`),
    updatedAt: new Date(`2025-10-08T07:14:54.810Z`),
  },
  {
    id: `cmg3a4qu20004blekhyt07zn8`,
    wordCount: 15,
    englishSentence: `Could you explain in your own words what the main idea of this paragraph is?`,
    japaneseSentence: `この段落の主な内容を自分の言葉で説明してください。`,
    japaneseReply: `はい、主に公害の原因について書かれています。`,
    englishReply: `Alright, it’s mainly about the causes of pollution.`,
    incorrectOptions: [
      'この問題の答えを自分で考えてください。',
      '教科書の内容を無視して、あなたの言いたいことを話してください。',
      'ノートを見て内容をまとめてください。',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu20004blekhyt07zn8_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu20004blekhyt07zn8_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu20004blekhyt07zn8_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-28/cmg3a4qu20004blekhyt07zn8_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `教師`,
    receiverVoice: 'female',
    receiverRole: `生徒`,
    place: `学校の教室`,
    scenePrompt: null,
    senderVoiceInstruction: `優しく問いかけるように、丁寧で分かりやすい話し方`,
    receiverVoiceInstruction: `素直で真面目に答える丁寧な話し方`,
    createdAt: new Date(`2025-09-28T05:49:03.573Z`),
    updatedAt: new Date(`2025-10-08T07:14:57.582Z`),
  },
  {
    id: `cmg3a4qu10002blekmntv194i`,
    wordCount: 16,
    englishSentence: `Can you make sure my dish is prepared without any nuts? I have a strong allergy.`,
    japaneseSentence: `強いアレルギーがあるので、料理にナッツを入れないでいただけますか？`,
    japaneseReply: `もちろんです、ナッツは一切使わないよう伝えます。`,
    englishReply: `Of course, I’ll tell the chef to avoid nuts completely.`,
    incorrectOptions: [
      'すみません、辛いナッツを大量に入れてもらえますか？大好きなんです。',
      'アレルギーがあるので卵は使わないで。',
      '料理に使う調味料を教えてもらえますか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu10002blekmntv194i_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu10002blekmntv194i_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg3a4qu10002blekmntv194i_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-28/cmg3a4qu10002blekmntv194i_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `客`,
    receiverVoice: 'female',
    receiverRole: `ウェイター`,
    place: `レストランのテーブル`,
    scenePrompt: null,
    senderVoiceInstruction: `切実で真剣なトーン、アレルギーへの注意を強調して話す`,
    receiverVoiceInstruction: `親切で丁寧、安心させるように明るく話す`,
    createdAt: new Date(`2025-09-28T05:49:03.573Z`),
    updatedAt: new Date(`2025-10-08T07:14:58.373Z`),
  },
];

export default problems;
