import type { ProblemWithAudio } from '@/lib/problem-service';

const problems: ProblemWithAudio[] = [
  {
    id: `cmfx5ayr4001ks94fdeaslk1a`,
    wordCount: 10,
    englishSentence: `Could you tell me the password for the Wi-Fi here?`,
    japaneseSentence: `ここのWi-Fiのパスワードを教えていただけますか？`,
    japaneseReply: `はい、レシートに書いてあります。`,
    englishReply: `Yes, it’s written on the receipt.`,
    incorrectOptions: [
      'すみません、メニューのおすすめを教えてください。',
      'このカフェの営業時間は何時までですか？',
      'お会計はどちらでできますか、教えてください。',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001ks94fdeaslk1a_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001ks94fdeaslk1a_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001ks94fdeaslk1a_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr4001ks94fdeaslk1a_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `客`,
    receiverVoice: 'male',
    receiverRole: `店員`,
    place: `カフェ`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧で控えめに質問するような、落ち着いたトーンで話す`,
    receiverVoiceInstruction: `親切で明確に説明する、丁寧な話し方`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-07T13:05:32.050Z`),
  },
  {
    id: `cmfx5ayr2000ts94fuo09sazm`,
    wordCount: 8,
    englishSentence: `Excuse me, is there a convenience store nearby?`,
    japaneseSentence: `すみません、この近くにコンビニはありますか？`,
    japaneseReply: `はい、あの角を曲がったところにありますよ。`,
    englishReply: `Yes, there is one just around the corner.`,
    incorrectOptions: [
      'すみません、駅まではどの道を行きますか？',
      '近くにバス停はありますか、教えてください。',
      'この辺りでおすすめのレストランはありますか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr2000ts94fuo09sazm_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr2000ts94fuo09sazm_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr2000ts94fuo09sazm_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr2000ts94fuo09sazm_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `旅行者`,
    receiverVoice: 'female',
    receiverRole: `地元の人`,
    place: `道`,
    scenePrompt: null,
    senderVoiceInstruction: `礼儀正しく少し不安そうに尋ねるように話す`,
    receiverVoiceInstruction: `親切で明るく、わかりやすく説明するトーン`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-07T13:04:57.807Z`),
  },
  {
    id: `cmfx5ayr3000ys94f8ft6b13p`,
    wordCount: 9,
    englishSentence: `Could you help me carry this heavy box upstairs?`,
    japaneseSentence: `すみません、この重い箱を二階まで運ぶのを手伝ってもらえますか？`,
    japaneseReply: `もちろんです。一緒に運びましょう。`,
    englishReply: `Of course. Let’s carry it together.`,
    incorrectOptions: [
      'すみません、教室の机を移動するのを手伝ってもらえますか？',
      'すみません、図書館の本を棚に戻すのを手伝ってもらえますか？',
      'すみません、体育館の道具を片付けるのを手伝ってもらえますか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr3000ys94f8ft6b13p_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr3000ys94f8ft6b13p_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr3000ys94f8ft6b13p_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr3000ys94f8ft6b13p_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `学生`,
    receiverVoice: 'male',
    receiverRole: `友達`,
    place: `学校`,
    scenePrompt: null,
    senderVoiceInstruction: `カジュアルで頼みやすい親しみのあるトーン`,
    receiverVoiceInstruction: `快く協力的で明るく元気に話す`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-07T13:05:57.407Z`),
  },
  {
    id: `cmfx5ayr4001ds94fsk3338go`,
    wordCount: 10,
    englishSentence: `Could you please call me a taxi to the station?`,
    japaneseSentence: `駅まで行くタクシーを呼んでいただけますか？`,
    japaneseReply: `はい、すぐに手配いたします。`,
    englishReply: `Yes, I’ll arrange one right away.`,
    incorrectOptions: [
      '部屋の掃除をお願いできますか？',
      '朝食の時間を教えてください。',
      'チェックアウトは何時ですか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001ds94fsk3338go_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001ds94fsk3338go_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001ds94fsk3338go_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr4001ds94fsk3338go_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `客`,
    receiverVoice: 'female',
    receiverRole: `ホテルスタッフ`,
    place: `ホテル`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧で礼儀正しく依頼するトーン`,
    receiverVoiceInstruction: `丁寧で迅速に対応する落ち着いた話し方`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-07T13:05:12.836Z`),
  },
  {
    id: `cmfx5ayr4001fs94f1u76gtiy`,
    wordCount: 9,
    englishSentence: `Could you please repeat the last part more slowly?`,
    japaneseSentence: `最後の部分をもう少しゆっくり繰り返してもらえますか？`,
    japaneseReply: `はい、ゆっくり説明しますね。`,
    englishReply: `Sure, I’ll explain it slowly.`,
    incorrectOptions: [
      'すみません、宿題の説明をもう一度お願いします。',
      '先生、今日の授業の内容を詳しく教えてください。',
      '授業で使う資料をもう少し分かりやすくしてください。',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001fs94f1u76gtiy_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001fs94f1u76gtiy_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001fs94f1u76gtiy_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr4001fs94f1u76gtiy_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `学生`,
    receiverVoice: 'female',
    receiverRole: `先生`,
    place: `学校`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧で控えめにお願いする、落ち着いたトーン`,
    receiverVoiceInstruction: `優しく丁寧に、相手を気遣うようにゆっくり話す`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-07T13:05:18.285Z`),
  },
  {
    id: `cmfx5ayr30015s94f75di2kr4`,
    wordCount: 10,
    englishSentence: `Could you tell me which bus goes to the airport?`,
    japaneseSentence: `空港に行くバスはどれか教えていただけますか？`,
    japaneseReply: `はい、あの青いバスが空港行きです。`,
    englishReply: `That blue bus goes to the airport.`,
    incorrectOptions: [
      '次のバスは何時に出発しますか？',
      'このバスは市内のどこに行きますか？',
      '切符はどこで買えますか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30015s94f75di2kr4_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30015s94f75di2kr4_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30015s94f75di2kr4_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr30015s94f75di2kr4_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `旅行者`,
    receiverVoice: 'female',
    receiverRole: `案内係`,
    place: `バスターミナル`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧で落ち着いた質問のトーン`,
    receiverVoiceInstruction: `親切で明るく、はっきりと案内する丁寧な話し方`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-07T13:04:59.552Z`),
  },
  {
    id: `cmfx5ayr2000vs94fxanjjdxp`,
    wordCount: 7,
    englishSentence: `Does this train go to the airport?`,
    japaneseSentence: `この電車に乗れば空港まで行けますか？`,
    japaneseReply: `はい、直通で空港まで行けます。`,
    englishReply: `Yes, this train goes directly to the airport.`,
    incorrectOptions: [
      '次の電車は何時に出発しますか？',
      'この駅のトイレはどこにありますか？',
      '切符はどこで買えますか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr2000vs94fxanjjdxp_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr2000vs94fxanjjdxp_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr2000vs94fxanjjdxp_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr2000vs94fxanjjdxp_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `旅行者`,
    receiverVoice: 'female',
    receiverRole: `駅員`,
    place: `駅`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧で少し不安げに、目的地を確認する`,
    receiverVoiceInstruction: `落ち着いて親切に、はっきりと答える丁寧な話し方`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-07T13:05:22.311Z`),
  },
  {
    id: `cmfx5ayr4001ls94fhclhh0el`,
    wordCount: 8,
    englishSentence: `Would it be alright if I paid separately?`,
    japaneseSentence: `別々にお会計してもいいですか？`,
    japaneseReply: `はい、大丈夫です。分けて計算しますね。`,
    englishReply: `Yes, that’s fine. I’ll split the bill.`,
    incorrectOptions: [
      'メニューをもう一度ください。',
      'おすすめの料理は何ですか？',
      '席は空いていますか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001ls94fhclhh0el_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001ls94fhclhh0el_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001ls94fhclhh0el_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-10-10/cmfx5ayr4001ls94fhclhh0el_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `客`,
    receiverVoice: 'female',
    receiverRole: `店員`,
    place: `レストラン`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧で控えめに、やや緊張した様子で話す`,
    receiverVoiceInstruction: `親切で柔らかく、快く了承する温かい口調`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-10T20:59:35.743Z`),
  },
  {
    id: `cmfx5ayr30016s94furnmmj92`,
    wordCount: 10,
    englishSentence: `Would you like to join us for dinner tomorrow evening?`,
    japaneseSentence: `明日の夜、一緒に夕食に行きませんか？`,
    japaneseReply: `いいですね、楽しみにしています。`,
    englishReply: `Sounds great. I’m looking forward to it.`,
    incorrectOptions: [
      '今日は天気がいいですね。',
      'このベンチは誰のものですか？',
      '子どもたちはどこにいますか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30016s94furnmmj92_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30016s94furnmmj92_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30016s94furnmmj92_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr30016s94furnmmj92_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `友達`,
    receiverVoice: 'male',
    receiverRole: `友達`,
    place: `公園`,
    scenePrompt: null,
    senderVoiceInstruction: `カジュアルで親しみやすく、楽しそうに誘う`,
    receiverVoiceInstruction: `明るく楽しみにしている気持ちを込めて`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-07T13:05:01.398Z`),
  },
  {
    id: `cmfx5ayr4001cs94f72rf8d8g`,
    wordCount: 10,
    englishSentence: `Would it be okay if I open this package here?`,
    japaneseSentence: `ここでこの荷物を開けてもいいですか？`,
    japaneseReply: `はい、大丈夫ですよ。`,
    englishReply: `Yes, that’s fine.`,
    incorrectOptions: [
      'この荷物の送り先を教えてください。',
      '郵便物の配達時間はいつですか？',
      '切手はどこで買えますか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001cs94f72rf8d8g_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001cs94f72rf8d8g_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001cs94f72rf8d8g_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr4001cs94f72rf8d8g_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `客`,
    receiverVoice: 'male',
    receiverRole: `店員`,
    place: `郵便局`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧で控えめに確認するような口調`,
    receiverVoiceInstruction: `落ち着いて親切、安心させるような丁寧な話し方`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-07T13:05:38.260Z`),
  },
  {
    id: `cmfx5ayr30013s94fpoajzud5`,
    wordCount: 9,
    englishSentence: `Could you please lower the volume a little bit?`,
    japaneseSentence: `すみません、音量を少し下げてもらえますか？`,
    japaneseReply: `はい、今下げますね。`,
    englishReply: `Sure, I’ll turn it down now.`,
    incorrectOptions: [
      'すみません、メニューをもう一度見せてください。',
      'すみません、注文を変更してもいいですか？',
      'すみません、お水をもう一杯もらえますか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30013s94fpoajzud5_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30013s94fpoajzud5_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30013s94fpoajzud5_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr30013s94fpoajzud5_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `客`,
    receiverVoice: 'female',
    receiverRole: `店員`,
    place: `カフェ`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧で控えめに、音量を少し下げてほしいという気持ちを込めて`,
    receiverVoiceInstruction: `親切で落ち着いた丁寧な話し方`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-07T13:04:55.751Z`),
  },
  {
    id: `cmfx5ayr2000us94ffm4j9atb`,
    wordCount: 10,
    englishSentence: `The movie we watched yesterday was really interesting, wasn’t it?`,
    japaneseSentence: `昨日見た映画はとても面白かったですね。`,
    japaneseReply: `そうですね。特に最後のシーンが印象的でした。`,
    englishReply: `Yes, especially the last scene was memorable.`,
    incorrectOptions: [
      'このカフェのケーキはとても美味しいですね。',
      '昨日の天気はとても良くて気持ちよかったです。',
      '新しいメニューを試してみたいと思います。',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr2000us94ffm4j9atb_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr2000us94ffm4j9atb_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr2000us94ffm4j9atb_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr2000us94ffm4j9atb_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `友達`,
    receiverVoice: 'male',
    receiverRole: `友達`,
    place: `カフェ`,
    scenePrompt: null,
    senderVoiceInstruction: `カジュアルで楽しそうに話す`,
    receiverVoiceInstruction: `共感して楽しそうに返答するカジュアルな話し方`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-07T13:05:39.862Z`),
  },
  {
    id: `cmfx5ayr30017s94fae00z789`,
    wordCount: 9,
    englishSentence: `Do you know if this shop accepts credit cards?`,
    japaneseSentence: `このお店はクレジットカードを使えますか？`,
    japaneseReply: `はい、使えます。こちらに機械があります。`,
    englishReply: `Yes, you can. Here is the machine.`,
    incorrectOptions: [
      'この商品の在庫はまだありますか？',
      '返品は可能ですか、教えてください。',
      '営業時間は何時までですか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30017s94fae00z789_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30017s94fae00z789_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30017s94fae00z789_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr30017s94fae00z789_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `客`,
    receiverVoice: 'female',
    receiverRole: `店員`,
    place: `店`,
    scenePrompt: null,
    senderVoiceInstruction: `カジュアルでやや疑問を持ったトーンで、穏やかに話す`,
    receiverVoiceInstruction: `丁寧で親切な口調で、落ち着いて答える`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-07T13:05:08.567Z`),
  },
  {
    id: `cmfx5ayr30014s94fftu08qq3`,
    wordCount: 10,
    englishSentence: `Would you mind opening the window for some fresh air?`,
    japaneseSentence: `すみません、空気を入れたいので窓を開けてもらえますか？`,
    japaneseReply: `いいですよ、開けましょう。`,
    englishReply: `Sure, I’ll open it.`,
    incorrectOptions: [
      'すみません、次の駅で降りる準備をお願いします。',
      'すみません、車内の温度を少し下げてもらえますか？',
      'すみません、座席のリクライニングを戻してください。',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30014s94fftu08qq3_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30014s94fftu08qq3_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30014s94fftu08qq3_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr30014s94fftu08qq3_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `乗客`,
    receiverVoice: 'male',
    receiverRole: `乗客`,
    place: `電車`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧に控えめにお願いする口調`,
    receiverVoiceInstruction: `快く応じる親しみやすく明るいトーン`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-07T13:05:55.431Z`),
  },
  {
    id: `cmfx5ayr4001bs94fa864f1uu`,
    wordCount: 9,
    englishSentence: `Could you show me how to use this machine?`,
    japaneseSentence: `この機械の使い方を教えていただけますか？`,
    japaneseReply: `はい、ここを押すと動きます。`,
    englishReply: `Yes, press here and it works.`,
    incorrectOptions: [
      'この商品の値段を教えてください。',
      'レジはどこにありますか？',
      '新しい商品は入荷しましたか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001bs94fa864f1uu_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001bs94fa864f1uu_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001bs94fa864f1uu_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr4001bs94fa864f1uu_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `客`,
    receiverVoice: 'female',
    receiverRole: `店員`,
    place: `店`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧で少し困惑気味に、使い方を尋ねる`,
    receiverVoiceInstruction: `親切でわかりやすく説明する、落ち着いた丁寧な話し方`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-07T13:05:04.979Z`),
  },
  {
    id: `cmfx5ayr4001gs94frq3yq6hg`,
    wordCount: 10,
    englishSentence: `Do you know if this bus stops at the museum?`,
    japaneseSentence: `このバスは博物館に停まりますか？`,
    japaneseReply: `はい、三つ目の停留所で停まります。`,
    englishReply: `Yes, it stops at the third stop.`,
    incorrectOptions: [
      '次のバス停はどこですか？',
      'このバスは駅に行きますか？',
      '切符はどこで買いますか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001gs94frq3yq6hg_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001gs94frq3yq6hg_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001gs94frq3yq6hg_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr4001gs94frq3yq6hg_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `旅行者`,
    receiverVoice: 'male',
    receiverRole: `運転手`,
    place: `バス`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧で少し不安げに、停留所の確認をする`,
    receiverVoiceInstruction: `親切で明るく、はっきりと答える丁寧な話し方`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-07T13:05:14.848Z`),
  },
  {
    id: `cmfx5ayr30018s94fzn9q64lm`,
    wordCount: 10,
    englishSentence: `Could you please explain this problem to me once more?`,
    japaneseSentence: `すみません、この問題をもう一度説明していただけますか？`,
    japaneseReply: `もちろんです。ゆっくり説明しますね。`,
    englishReply: `Of course. I’ll explain it slowly.`,
    incorrectOptions: [
      'すみません、宿題の答えをもう一度教えてください。',
      '先生、今日の授業の内容を詳しく説明してください。',
      'すみません、テストの範囲をもう一度確認したいです。',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30018s94fzn9q64lm_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30018s94fzn9q64lm_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr30018s94fzn9q64lm_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr30018s94fzn9q64lm_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `学生`,
    receiverVoice: 'male',
    receiverRole: `先生`,
    place: `学校`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧で真剣に質問する、落ち着いたトーン`,
    receiverVoiceInstruction: `優しく丁寧に、相手を気遣いながら説明する話し方`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-07T13:05:51.997Z`),
  },
  {
    id: `cmfx5ayr4001js94f38bwi7m2`,
    wordCount: 10,
    englishSentence: `Would you mind watching my bag for a few minutes?`,
    japaneseSentence: `少しの間、私の荷物を見ていてもらえますか？`,
    japaneseReply: `はい、大丈夫ですよ。`,
    englishReply: `Sure, no problem.`,
    incorrectOptions: [
      'すみません、次の電車は何時に来ますか？',
      'この駅のトイレはどこにありますか？',
      '切符はどこで買えますか、教えてください。',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001js94f38bwi7m2_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001js94f38bwi7m2_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfx5ayr4001js94f38bwi7m2_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-24/cmfx5ayr4001js94f38bwi7m2_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `旅行者`,
    receiverVoice: 'female',
    receiverRole: `通行人`,
    place: `駅`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧で控えめにお願いする、少し不安げなトーン`,
    receiverVoiceInstruction: `優しく安心させるような、柔らかい話し方`,
    createdAt: new Date(`2025-09-23T22:47:18.638Z`),
    updatedAt: new Date(`2025-10-07T13:05:35.570Z`),
  },
  {
    id: `cmfyb92fx003agvw4ehkztj2f`,
    wordCount: 7,
    englishSentence: `Could you check the figures once more?`,
    japaneseSentence: `数字をもう一度確認していただけますか？`,
    japaneseReply: `はい、確認します。`,
    englishReply: `Yes, I’ll check them.`,
    incorrectOptions: [
      '資料の内容をもう一度確認してください。',
      '会議の時間を再度お知らせします。',
      '報告書の提出期限はいつですか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fx003agvw4ehkztj2f_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fx003agvw4ehkztj2f_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fx003agvw4ehkztj2f_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-25/cmfyb92fx003agvw4ehkztj2f_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `上司`,
    receiverVoice: 'female',
    receiverRole: `部下`,
    place: `会社`,
    scenePrompt: null,
    senderVoiceInstruction: `穏やかで丁寧に再確認を求めるトーンで話す`,
    receiverVoiceInstruction: `真面目で丁寧に応じる`,
    createdAt: new Date(`2025-09-24T18:21:33.978Z`),
    updatedAt: new Date(`2025-10-07T13:04:38.228Z`),
  },
  {
    id: `cmfyb92fw0037gvw454fyl3ve`,
    wordCount: 7,
    englishSentence: `Can you update the file by tonight?`,
    japaneseSentence: `今夜までにファイルを更新できますか？`,
    japaneseReply: `はい、更新します。`,
    englishReply: `Yes, I’ll update it.`,
    incorrectOptions: [
      '今日の会議は何時に始まりますか？',
      '新しいプロジェクトの詳細を教えてください。',
      '資料の提出期限はいつですか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fw0037gvw454fyl3ve_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fw0037gvw454fyl3ve_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fw0037gvw454fyl3ve_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-25/cmfyb92fw0037gvw454fyl3ve_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `上司`,
    receiverVoice: 'male',
    receiverRole: `部下`,
    place: `会社`,
    scenePrompt: null,
    senderVoiceInstruction: `フォーマルで真剣な丁寧な話し方で、やや急ぎの依頼を伝えるトーン`,
    receiverVoiceInstruction: `丁寧で落ち着いた、責任感のある話し方`,
    createdAt: new Date(`2025-09-24T18:21:33.978Z`),
    updatedAt: new Date(`2025-10-07T13:04:43.469Z`),
  },
  {
    id: `cmfyb92fu002kgvw407dv4wwi`,
    wordCount: 7,
    englishSentence: `Do you have time for a call?`,
    japaneseSentence: `電話する時間はありますか？`,
    japaneseReply: `はい、五分後なら大丈夫です。`,
    englishReply: `Yes, in five minutes is fine.`,
    incorrectOptions: [
      '明日の会議は何時ですか？',
      '資料の準備はできましたか？',
      '休憩は何時からですか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fu002kgvw407dv4wwi_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fu002kgvw407dv4wwi_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fu002kgvw407dv4wwi_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-25/cmfyb92fu002kgvw407dv4wwi_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `同僚`,
    receiverVoice: 'female',
    receiverRole: `同僚`,
    place: `会社`,
    scenePrompt: null,
    senderVoiceInstruction: `カジュアルで親しみやすく、気軽に尋ねる明るいトーン`,
    receiverVoiceInstruction: `カジュアルで元気よく、前向きに応答する話し方`,
    createdAt: new Date(`2025-09-24T18:21:33.978Z`),
    updatedAt: new Date(`2025-10-07T06:41:48.645Z`),
  },
  {
    id: `cmfyb92fw0034gvw436qt8akp`,
    wordCount: 7,
    englishSentence: `When will the final version be ready?`,
    japaneseSentence: `最終版はいつ準備できますか？`,
    japaneseReply: `来週の月曜日です。`,
    englishReply: `It’ll be ready next Monday.`,
    incorrectOptions: [
      '会議の時間は何時ですか？',
      '今日の仕事は終わりましたか？',
      '資料はもうできていますか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fw0034gvw436qt8akp_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fw0034gvw436qt8akp_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fw0034gvw436qt8akp_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-25/cmfyb92fw0034gvw436qt8akp_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `上司`,
    receiverVoice: 'female',
    receiverRole: `部下`,
    place: `会社`,
    scenePrompt: null,
    senderVoiceInstruction: `落ち着いた丁寧な口調で尋ねる`,
    receiverVoiceInstruction: `落ち着いて丁寧に答える`,
    createdAt: new Date(`2025-09-24T18:21:33.978Z`),
    updatedAt: new Date(`2025-10-07T13:04:41.351Z`),
  },
  {
    id: `cmfyb92fw002zgvw4n22stn6g`,
    wordCount: 7,
    englishSentence: `Could you join the call at three?`,
    japaneseSentence: `三時の電話会議に参加していただけますか？`,
    japaneseReply: `はい、参加します。`,
    englishReply: `Yes, I’ll join it.`,
    incorrectOptions: [
      '今日の会議は何時に始まりますか？',
      '新しいプロジェクトの詳細を教えてください。',
      '資料の提出期限はいつですか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fw002zgvw4n22stn6g_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fw002zgvw4n22stn6g_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fw002zgvw4n22stn6g_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-25/cmfyb92fw002zgvw4n22stn6g_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `上司`,
    receiverVoice: 'male',
    receiverRole: `部下`,
    place: `会社`,
    scenePrompt: null,
    senderVoiceInstruction: `フォーマルで落ち着いた丁寧な話し方で、依頼を穏やかに伝えるトーン`,
    receiverVoiceInstruction: `丁寧で明るく、素直に応じる親切な話し方`,
    createdAt: new Date(`2025-09-24T18:21:33.978Z`),
    updatedAt: new Date(`2025-10-07T13:04:39.654Z`),
  },
  {
    id: `cmfyb92fv002ngvw4zqrejs06`,
    wordCount: 7,
    englishSentence: `Can we postpone the meeting to tomorrow?`,
    japaneseSentence: `会議を明日に延期できますか？`,
    japaneseReply: `はい、可能です。`,
    englishReply: `Yes, that’s possible.`,
    incorrectOptions: [
      '今日の予定は何ですか？',
      '資料は準備できましたか？',
      '休憩は何時からですか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fv002ngvw4zqrejs06_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fv002ngvw4zqrejs06_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fv002ngvw4zqrejs06_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-25/cmfyb92fv002ngvw4zqrejs06_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `上司`,
    receiverVoice: 'male',
    receiverRole: `部下`,
    place: `会社`,
    scenePrompt: null,
    senderVoiceInstruction: `フォーマルで丁寧、少し慎重な印象を与える穏やかな依頼のトーン`,
    receiverVoiceInstruction: `丁寧で落ち着いた、快く応じる話し方`,
    createdAt: new Date(`2025-09-24T18:21:33.978Z`),
    updatedAt: new Date(`2025-10-07T13:04:45.060Z`),
  },
  {
    id: `cmfyb92fw0031gvw41hkj3zke`,
    wordCount: 7,
    englishSentence: `Could you send me the contract today?`,
    japaneseSentence: `今日、契約書を送っていただけますか？`,
    japaneseReply: `はい、すぐに送ります。`,
    englishReply: `Yes, I’ll send it right away.`,
    incorrectOptions: [
      '今日の会議は何時に始まりますか？',
      '新しいプロジェクトの詳細を教えてください。',
      '資料の提出期限はいつですか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fw0031gvw41hkj3zke_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fw0031gvw41hkj3zke_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fw0031gvw41hkj3zke_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-25/cmfyb92fw0031gvw41hkj3zke_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `上司`,
    receiverVoice: 'male',
    receiverRole: `部下`,
    place: `会社`,
    scenePrompt: null,
    senderVoiceInstruction: `フォーマルで真剣に依頼する丁寧な話し方`,
    receiverVoiceInstruction: `明るく素早く応じる、丁寧で前向きな話し方`,
    createdAt: new Date(`2025-09-24T18:21:33.978Z`),
    updatedAt: new Date(`2025-10-07T13:04:36.510Z`),
  },
  {
    id: `cmfyb92fw0032gvw4jvhpop8d`,
    wordCount: 7,
    englishSentence: `Do we need to update the plan?`,
    japaneseSentence: `計画を更新する必要がありますか？`,
    japaneseReply: `はい、少し修正が必要です。`,
    englishReply: `Yes, some adjustments are needed.`,
    incorrectOptions: [
      '今日の会議は何時からですか？',
      '資料の準備はもうできていますか？',
      '報告書の提出はいつですか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fw0032gvw4jvhpop8d_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fw0032gvw4jvhpop8d_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fw0032gvw4jvhpop8d_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-25/cmfyb92fw0032gvw4jvhpop8d_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `部下`,
    receiverVoice: 'female',
    receiverRole: `上司`,
    place: `会社`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧で謙虚な話し方で、確認を求める穏やかなトーン`,
    receiverVoiceInstruction: `フォーマルで落ち着いた、少し説明的な丁寧な話し方`,
    createdAt: new Date(`2025-09-24T18:21:33.978Z`),
    updatedAt: new Date(`2025-10-07T13:04:47.975Z`),
  },
  {
    id: `cmfyb92fu002jgvw4vo6k52im`,
    wordCount: 7,
    englishSentence: `Could you share the report with me?`,
    japaneseSentence: `その報告書を私に共有していただけますか？`,
    japaneseReply: `はい、すぐに送ります。`,
    englishReply: `Yes, I’ll send it right away.`,
    incorrectOptions: [
      '今日の会議は何時に始まりますか？',
      '新しいプロジェクトの詳細を教えてください。',
      '資料の提出期限はいつですか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fu002jgvw4vo6k52im_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fu002jgvw4vo6k52im_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmfyb92fu002jgvw4vo6k52im_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-25/cmfyb92fu002jgvw4vo6k52im_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `同僚`,
    receiverVoice: 'male',
    receiverRole: `同僚`,
    place: `会社`,
    scenePrompt: null,
    senderVoiceInstruction: `カジュアルで親しみやすく頼むように話す`,
    receiverVoiceInstruction: `明るく迅速に応じる`,
    createdAt: new Date(`2025-09-24T18:21:33.978Z`),
    updatedAt: new Date(`2025-10-07T13:04:34.814Z`),
  },
  {
    id: `cmg39gqxp000d3gynh0vw8n40`,
    wordCount: 8,
    englishSentence: `Can I renew this book for another week?`,
    japaneseSentence: `この本をもう一週間延長できますか？`,
    japaneseReply: `はい、返却期限は来週の月曜日です。`,
    englishReply: `Yes, the due date is now next Monday.`,
    incorrectOptions: [
      'この本の返却日はいつですか？',
      '新しい本は入っていますか？',
      '予約はどのようにできますか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg39gqxp000d3gynh0vw8n40_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg39gqxp000d3gynh0vw8n40_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg39gqxp000d3gynh0vw8n40_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-28/cmg39gqxp000d3gynh0vw8n40_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `利用者`,
    receiverVoice: 'male',
    receiverRole: `司書`,
    place: `図書館の受付`,
    scenePrompt: null,
    senderVoiceInstruction: `丁寧で落ち着いた、質問するようなトーンで`,
    receiverVoiceInstruction: `親切で穏やかな丁寧語で案内するように`,
    createdAt: new Date(`2025-09-28T05:30:23.956Z`),
    updatedAt: new Date(`2025-10-08T01:17:57.793Z`),
  },
  {
    id: `cmg39gqxo00043gynhd7o0l9n`,
    wordCount: 8,
    englishSentence: `Would you like to give this a try?`,
    japaneseSentence: `こちら、試してみませんか？`,
    japaneseReply: `じゃあ、少しだけいただきます。`,
    englishReply: `Alright, I’ll taste a small piece.`,
    incorrectOptions: [
      '新しい商品です。どうぞ。',
      'こちらは人気の商品です。',
      'とても苦い余りものですが、どうぞ。',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg39gqxo00043gynhd7o0l9n_en_female.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg39gqxo00043gynhd7o0l9n_en-reply_male.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg39gqxo00043gynhd7o0l9n_ja_male.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-28/cmg39gqxo00043gynhd7o0l9n_composite.webp`,
    audioReady: true,
    senderVoice: 'female',
    senderRole: `試食スタッフ`,
    receiverVoice: 'male',
    receiverRole: `客`,
    place: `スーパーの試食コーナー`,
    scenePrompt: null,
    senderVoiceInstruction: `明るくフレンドリーで、気軽に勧めるカジュアルな話し方で`,
    receiverVoiceInstruction: `控えめで礼儀正しく、少し遠慮がちなカジュアルなトーンで`,
    createdAt: new Date(`2025-09-28T05:30:23.956Z`),
    updatedAt: new Date(`2025-10-12T12:54:36.363Z`),
  },
  {
    id: `cmg39gqxq000l3gynfmumwjhn`,
    wordCount: 8,
    englishSentence: `Would you like some help with the machine?`,
    japaneseSentence: `機械の操作をお手伝いしましょうか？`,
    japaneseReply: `はい、エラーが出てしまいます。`,
    englishReply: `Yes, it keeps showing an error.`,
    incorrectOptions: [
      'こちらのATMは24時間利用できます。',
      'カードの挿入方法を説明しましょうか？',
      '現金の引き出しはどのボタンですか？',
    ],
    audioEnUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg39gqxq000l3gynfmumwjhn_en_male.mp3`,
    audioEnReplyUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg39gqxq000l3gynfmumwjhn_en-reply_female.mp3`,
    audioJaUrl: `https://cdn.en-ma.ster.jp.net/audio/2025-10-07/cmg39gqxq000l3gynfmumwjhn_ja_female.mp3`,
    imageUrl: `https://cdn.en-ma.ster.jp.net/images/2025-09-28/cmg39gqxq000l3gynfmumwjhn_composite.webp`,
    audioReady: true,
    senderVoice: 'male',
    senderRole: `銀行員`,
    receiverVoice: 'female',
    receiverRole: `利用客`,
    place: `銀行のATM前`,
    scenePrompt: null,
    senderVoiceInstruction: `親切で丁寧な提案のトーンで`,
    receiverVoiceInstruction: `困惑気味で丁寧に状況を説明するトーンで`,
    createdAt: new Date(`2025-09-28T05:30:23.956Z`),
    updatedAt: new Date(`2025-10-07T13:04:28.417Z`),
  },
];

export default problems;
