export const words = [
  'although',
  'though',
  'even though',
  'unless',
  'once',
  'whether',
  'provided that',
  'in case',
  'above',
  'below',
  'throughout',
  'despite',
  'in spite of',
  'according to',
  'owing to',
  'except for',
  'beyond',
  'within',
  'therefore',
  'otherwise',
  'meanwhile',
  'consequently',
  'nevertheless',
  'furthermore',
  'moreover',
  'considerable',
  'considerably',
  'in advance',
  'as a result',
  'be responsible for',
  'be likely to',
  'in accordance with',
  'on behalf of',
];
