export const words = [
  'as soon as possible',
  'on schedule',
  'be in charge of',
  'according to',
  'make a reservation',
  'be postponed',
  'in advance',
  'due to',
  'take a message',
  'figure out',
  'reschedule the meeting',
  'be available',
  'handle the request',
  'at the moment',
  'for the time being',
  'in the meantime',
  'confirm the details',
  'be responsible for',
  'miss the deadline',
  'give someone a call',
];
