export const words: string[] = [
  'good morning',
  'good night',
  'thank you',
  'excuse me',
  'see you later',
  'nice to meet you',
  'how are you',
  'have a seat',
  'here you are',
  'my treat',
  'on sale',
  'cash only',
  'to go',
  'for here',
  'spicy food',
  'vegetarian',
  'extra cheese',
  'low fat',
  'sugar free',
  'take a break',
  'day off',
  'overtime',
  'rush hour',
  'traffic jam',
  'public transport',
  'subway map',
  'missed the train',
  'running late',
  'on time',
  'wait in line',
  'first floor',
  'elevator',
  'restroom',
  'lost and found',
  'pay in advance',
  'free parking',
  'opening hours',
  'closed today',
  'sold out',
  'try it on',
  'fitting room',
  'wrong size',
  'gift wrap',
  'return policy',
  'mobile payment',
  'Wi-Fi password',
  'out of battery',
  'low battery',
  'turn it off',
  'plug it in',
  'full charge',
  'set an alarm',
  'overslept',
  'skip breakfast',
  'pack my bag',
  'hand in homework',
  'pop quiz',
  'summer vacation',
  'winter break',
  'school trip',
  'locker room',
  'gym class',
  'after school',
  'part-time job',
  'save money',
  'split the bill',
  'borrow money',
  'lend a hand',
  'keep a secret',
  'make plans',
  'cancel plans',
  'rain check',
  'weather forecast',
  'terrible weather',
  'clear skies',
  'too humid',
  'catch a cold',
  'stay home',
  'call in sick',
  'feel better',
  'get well soon',
  'pet sitting',
  'walk the dog',
  'cat person',
  'dog person',
  'water the plants',
  'trash day',
  'recycle bin',
  'neighbors',
  'housewarming',
  'spare key',
  'grocery list',
  'sell by date',
  'self checkout',
  'loyalty card',
  'membership discount',
  'window seat',
  'aisle seat',
  'boarding pass',
  'baggage claim',
  'customs form',
  'jet lag',
  'hotel reservation',
  'late checkout',
  'room service',
  'do not disturb',
  'fire alarm',
  'emergency exit',
  'mind the gap',
  'single ticket',
  'round trip',
  'peak hours',
  'off peak',
  'bike lane',
  'crosswalk',
  'speed limit',
  'parking meter',
  'tow zone',
  "I'm starving",
  "it's freezing",
  "don't worry",
  "can't wait",
  "let's go",
  "what's wrong",
  "that's fine",
  "you're right",
];
