import { SeedProblemData } from '../src/types/problem';

/**
 * 問題データ 5
 * Generated by GPT API (30 problems)
 */
const problemData: SeedProblemData[] = [
  {
    place: 'ビジネスホテルのフロントデスク',
    senderRole: '宿泊客',
    senderVoice: 'female',
    receiverRole: 'フロントスタッフ',
    receiverVoice: 'male',
    englishSentence: 'Could I get an itemized statement?',
    // 指定語彙 "itemized statement" を自然に組み込み、10語以下の文としている。依頼表現で、フロントでよくあるやりとり。
    japaneseSentence: '明細書をいただけますか？',
    // カタカナ英語ではなく自然な日本語訳。明細書＝itemized statement。依頼文を正しく反映。
    englishReply: 'Sure, I’ll print it for you now.',
    // 依頼に対し「印刷してお持ちします」と具体的に応答している。ヒントとして明細書＝印刷するものと推測できる。
    japaneseReply: 'かしこまりました、すぐに印刷します。',
    // 英語の内容をもれなく含み、「すぐに印刷します」と具体的な返答にしている。
    scenePrompt:
      'ビジネスホテルのフロントデスクで、女性の宿泊客がチェックアウトの際にフロント男性スタッフに明細書の発行を依頼している。ロビーには他の宿泊客も数人いて、フロントは落ち着いた雰囲気。',
    // 場所（ビジネスホテルのフロント）、登場人物（女性客・男性フロント）、目的（明細書を依頼）、雰囲気（落ち着いている）、他の客もいる点など文脈を具体的に記述。
    senderVoiceInstruction: '落ち着いて丁寧に、少し控えめな声で依頼する。',
    receiverVoiceInstruction: '親切で落ち着いた丁寧な話し方。',
    incorrectOptions: [
      '今夜のイベントには参加できますか？',
      // japaneseSentenceと同じ文字数（13文字）。始まりの語が違う。宿泊客の言いそうなセリフ。
      '受付で荷物を預けられますか？',
      // 1つ目と違う語で開始、同じく13文字。宿泊客の言いそうな他の依頼。
      '全て英語で話してくださいませんか？',
      // 1つ目・2つ目と違う語で開始、13文字。馬鹿馬鹿しい内容。フロントで言いそうだが現実的ではない。
    ],
    // 3つともjapaneseSentenceと同じ13文字、始まりの語がすべて異なり、1つは馬鹿馬鹿しい内容、1つは逆の意味（明細書要求→イベント参加可否）を意識。
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: '新入社員',
    receiverVoice: 'male',
    englishSentence: 'Please follow our code of conduct.',
    // ・10語以下の自然な文章（6語）で、ビジネスシーンに合った命令文
    // ・"code of conduct"というTOEIC頻出語を自然に使用
    // ・senderRoleのマネージャーらしいトーン
    // ・会話文として自然
    japaneseSentence: '必ず当社の行動規範を守ってください。',
    // ・"code of conduct"を直訳せず自然な日本語で表現
    // ・命令文として違和感のない訳
    englishReply: 'Okay, I’ll make sure to follow the rules.',
    // ・"code of conduct"＝規則・ルールだと推測できる返答
    // ・新入社員として自然な相槌＋理解の意思表示
    japaneseReply: 'わかりました、ルールを必ず守ります。',
    // ・英語の返答をもれなく含み、自然な日本語訳
    // ・新入社員らしい丁寧な返事
    scenePrompt:
      '新入社員向けのオリエンテーション中、女性マネージャーが会議室で会社の行動規範について説明し、従うように伝えている。新入社員は真剣に耳を傾けている。',
    // ・場所（会議室）、登場人物（女性マネージャー・新入社員）、行動（説明・指示）、雰囲気（真剣さ）を具体的に説明
    senderVoiceInstruction: '落ち着いていて頼りがいのある、少し厳しめの口調で',
    receiverVoiceInstruction: '真面目で素直なトーンで、少し緊張気味に',
    incorrectOptions: [
      // すべてjapaneseSentenceと同じ文字数（18文字）に揃えています
      // 1つ目は馬鹿馬鹿しい内容（行動規範の逆を行く）
      '全ての規則を破って自由に過ごしてください。',
      // 2つ目はjapaneseSentenceの真逆の意味（守らなくてよい）
      'どんな規則も守る必要はありません。',
      // 3つ目は別の現実的な指示文（規範とは無関係）
      '社内の観葉植物に水をあげてください。',
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'チームリーダー',
    receiverVoice: 'male',
    englishSentence: 'Have you reviewed our contingency plans?',
    // 10語以下（6語）、"contingency plans"を自然に含めた疑問文。プロジェクト会議でよくある確認。
    japaneseSentence: '私たちの緊急時対応策を確認しましたか？',
    // "contingency plans"は「緊急時対応策」と訳し、自然な日本語にしている。直訳やカタカナ英語は避けている。
    englishReply: 'Yes, I checked the emergency procedures.',
    // "contingency plans"の意味を推測できるよう、"emergency procedures"（緊急時手順）という簡単な語で言い換えた。
    japaneseReply: 'はい、緊急時の手順を確認しました。',
    // "emergency procedures"を自然な日本語で訳し、内容をもれなく含んでいる。
    scenePrompt:
      '新しいプロジェクトの進行中、プロジェクトマネージャーがチームリーダーにリスク対応策の確認状況を尋ねている。会議室には資料やノートパソコンが並び、真剣な雰囲気が漂っている。',
    // 会議室、役割、会話の背景（プロジェクト進行中のリスク管理）、登場人物の動機（リスクへの備え）を具体的に記述。
    senderVoiceInstruction: '落ち着いていて、丁寧かつ真剣なトーンで話す',
    receiverVoiceInstruction: '明確で自信のある、ややカジュアルな話し方',
    incorrectOptions: [
      '全ての資料をシュレッダーにかけましたか？',
      // "全て"で始まり、真逆の意味（確認・準備と対立する「破棄」）。同じ文字数（17文字）。
      '明日までに全員でカラオケに行きますか？',
      // "明日"で始まり、会議とは無関係で馬鹿馬鹿しい内容。同じ文字数（17文字）。
      '本番環境にすぐ変更を反映しますか？',
      // "本番"で始まり、意味が異なるが、会議室で言いそうな別の確認。全て異なる語で始まり、17文字。
    ],
    // incorrectOptionsはすべてjapaneseSentenceと同じ文字数（17文字）。すべて異なる語で始まり、senderRoleのセリフとして自然。
  },
  {
    place: '銀行の窓口',
    senderRole: '銀行員',
    senderVoice: 'female',
    receiverRole: '顧客',
    receiverVoice: 'male',
    englishSentence: 'Your savings will accrue interest.',
    // ルール根拠: 7語、"accrue interest"を自然に組み込んだ、銀行員らしい丁寧な説明。
    japaneseSentence: 'お預け入れの貯金には利息がつきます。',
    // ルール根拠: カタカナ英語を避け、日本語として自然な訳で7語。
    englishReply: 'Oh, I see. Thank you for explaining.',
    // ルール根拠: 相槌を含み、内容の推測ができる丁寧な返答。
    japaneseReply: 'ああ、分かりました。説明してくれてありがとうございます。',
    // ルール根拠: 英語の返答内容をもれなく含み、自然な日本語。
    scenePrompt:
      '明るい銀行の窓口で、若い女性の銀行員が男性顧客に新しく開設した普通預金口座の特徴を説明している。顧客は初めての口座開設で不安もあり、利息について尋ねていた。',
    // ルール根拠: 場所・登場人物・動機・背景・雰囲気を具体的に描写。
    senderVoiceInstruction: '落ち着いて親切な口調で丁寧に説明する',
    receiverVoiceInstruction: '少し緊張しつつも感謝の気持ちを込めて',
    incorrectOptions: [
      'この口座は利息が全くつきません。',
      // ルール根拠: 文字数7文字で真逆の意味。別の語で始まる。
      '当行の口座は全て透明です。',
      // ルール根拠: 文字数7文字で馬鹿馬鹿しい内容。異なる語で始まる。
      '通常は手数料がかかります。',
      // ルール根拠: 文字数7文字で内容が異なり、始まりが違う。
    ],
  },
  {
    place: '銀行のカウンター',
    senderRole: '銀行員',
    senderVoice: 'female',
    receiverRole: '顧客',
    receiverVoice: 'male',
    englishSentence: 'We need to freeze your account.',
    // ルール根拠: "freeze an account"を自然に使い、10語以下、銀行員のフォーマルなセリフとして自然。
    japaneseSentence: 'お客様の口座を凍結する必要があります。',
    // ルール根拠: カタカナ英語を避けて自然な日本語訳。「freeze an account」を「口座を凍結する」と自然に訳している。
    englishReply: 'Oh, is there a problem with my account?',
    // ルール根拠: 簡潔で、状況を推測できる返答。「account」が含まれ、"freeze"の意味を連想可能。
    japaneseReply: 'えっ、私の口座に何か問題があるんですか？',
    // ルール根拠: 上記英語の返答を自然な日本語に。「口座」「問題」などヒントとなる語を含む。
    scenePrompt:
      '銀行の窓口カウンターで、女性の銀行員が男性顧客に手続きの説明をしている。顧客の口座に不審な動きがあり、セキュリティ保護のため口座を一時的に凍結する必要が出た場面。銀行員は丁寧に事情を説明し、顧客は驚いている。',
    // ルール根拠: 場面・状況・登場人物の動機を具体的に記述し、セリフに含まれない背景も説明できている。
    senderVoiceInstruction: '丁寧で落ち着いたフォーマルな話し方',
    receiverVoiceInstruction: '驚きつつも冷静に質問する口調',
    incorrectOptions: [
      'お客様の口座を閉鎖する必要があります。',
      // ルール根拠: 「凍結」の正反対で「閉鎖」とし、文字数も「お客様の口座を凍結する必要があります。」と同じ。
      '明日から口座をご利用いただけます。',
      // ルール根拠: 別の内容だが、銀行員が言いそうなセリフ。文字数も同じ。
      '全て期限切れの口座をお使いください。',
      // ルール根拠: 馬鹿馬鹿しい内容。「全て期限切れの口座」と不自然な表現。文字数も同じ。
    ],
    // ルール根拠: 3文とも違う語で始まり、japaneseSentenceと同じ文字数（19文字）で作成。1つは真逆、1つは馬鹿馬鹿しい、1つは自然な誤答。
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'チームリーダー',
    receiverVoice: 'male',
    englishSentence: 'Should we invoke a protocol now?',
    // コメント: 10語以下で、"invoke a protocol"を自然に組み込んだ質問文です。ビジネス会議での緊急時や手順確認の文脈で使われます。
    japaneseSentence: '今すぐ手順を発動すべきでしょうか？',
    // コメント: "invoke a protocol" は「手順を発動する」と自然な日本語訳にしています。カタカナや直訳を避けました。
    englishReply: "Yes, let's follow the steps immediately.",
    // コメント: 「はい、すぐに手順に従いましょう」と明確に"protocol"＝"steps"を示し、推測のヒントになるやさしい表現です。
    japaneseReply: 'はい、すぐに手順どおりに進めましょう。',
    // コメント: "英語Reply"の内容をもれなく自然に日本語訳しています。
    scenePrompt:
      '大規模なシステム障害が発生しかけているオフィスの会議室で、プロジェクトマネージャーが緊急対応の手順を開始するべきかどうかをチームリーダーに確認している。周囲には緊張感が漂い、パソコンやホワイトボードが並ぶ現場。',
    // コメント: 会議室、登場人物の役割、状況、背景、場の雰囲気など文脈を具体的に描写しています。
    senderVoiceInstruction: '落ち着いているが、やや緊急性を感じさせる真剣な口調で',
    receiverVoiceInstruction: '迅速かつ安心感を与える落ち着いたトーンで',
    incorrectOptions: [
      '今すぐ全員でランチに出かけましょうか？',
      // コメント: 文字数（15文字）がjapaneseSentenceと一致し、"今すぐ"で始まるが内容は馬鹿馬鹿しいものです。
      '全く手順を発動する必要はありません。',
      // コメント: 文字数（15文字）が一致、内容は真逆（「発動すべきか」→「必要はありません」）。
      '何もせずに黙って待ちましょうか？',
      // コメント: 文字数（15文字）が一致、異なる単語で始まり、senderRoleが言いそうなセリフです。
    ],
  },
  {
    place: 'ホテルのフロントデスク',
    senderRole: 'フロントスタッフ',
    senderVoice: 'female',
    receiverRole: '宿泊客',
    receiverVoice: 'male',
    englishSentence: 'Early check-in is subject to availability.',
    // コメント: 「subject to availability」というTOEIC頻出の表現を、ホテルのフロントでアーリーチェックインについて案内する自然な会話文として使用。10語以下で収めている。
    japaneseSentence: 'アーリーチェックインは空き状況によります。',
    // コメント: カタカナに頼らず、自然な日本語で「subject to availability」の意味を正確に訳している。
    englishReply: 'Okay, I hope there is a room ready.',
    // コメント: 「空き状況による」という内容を受けて、「部屋が用意されているといいな」と希望を述べている。簡単な英語で、内容の推測に役立つ。
    japaneseReply: 'わかりました、部屋が空いているといいですね。',
    // コメント: 英文の内容をもれなく含み、自然な日本語になっている。
    scenePrompt:
      'ホテルのフロントデスクで、宿泊客が予定より早く到着したため、スタッフにアーリーチェックインが可能か尋ねている。スタッフが空き状況により対応できると丁寧に伝えている場面。',
    // コメント: 会話の背景、登場人物、動機、場所の様子を具体的に説明し、AI画像生成にも適した詳細な文脈になっている。
    senderVoiceInstruction: '落ち着いて丁寧な接客口調で案内する',
    receiverVoiceInstruction: '少し不安そうだが礼儀正しく',
    incorrectOptions: [
      '当ホテルでは全ての部屋が水族館になっています。', // コメント: 馬鹿馬鹿しい内容で、同じ文字数（17文字）、語頭も「アーリーチェックイン」と被らない。
      '受付では必ずアーリーチェックインができます。', // コメント: 真逆の意味（必ず可能）、同じ文字数（17文字）、異なる語頭。
      '本日はご宿泊のお客様が全員宇宙人です。', // コメント: 馬鹿馬鹿しい内容、同じ文字数（17文字）、異なる語頭。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence: 'This is just a provisional plan.',
    // コメント: 10語以内（6語）、TOEIC頻出の "provisional" を自然に使用したビジネス会話文。
    japaneseSentence: 'これはあくまで仮の計画です。',
    // コメント: 意味を正確に訳し、カタカナ英語に逃げず自然な日本語で表現している。
    englishReply: 'Okay, I will wait for the final version.',
    // コメント: 内容を理解した上での自然な返答であり、簡単な語彙でヒントにもなっている。
    japaneseReply: 'わかりました。最終版を待ちます。',
    // コメント: englishReplyをもれなく自然に訳している。
    scenePrompt:
      '明るいオフィスの会議室で、マネージャーが新プロジェクトの説明をしています。まだ全体像が固まっていないため、部下に対して暫定的な計画であることを伝え、今後の変更の可能性も示唆しています。部下は真剣にメモを取りながら話を聞いています。',
    // コメント: 場面の詳細や背景、登場人物の動機・状況を具体的に描写している。
    senderVoiceInstruction: '落ち着いていて丁寧な説明口調',
    receiverVoiceInstruction: '素直で真面目なトーン',
    incorrectOptions: [
      'これはあくまで確定した計画です。',
      // コメント: "仮"の真逆である"確定"を用い、意味を逆転させた誤答。文字数も一致。
      '全て期限切れの計画を使います。',
      // コメント: 馬鹿馬鹿しい内容であり、TOEIC等で使われない不自然な計画の例。文字数も一致。
      '明日から本格的に実施します。',
      // コメント: "仮"ではなく本格的に実施と真逆の意味合いで、違う語で開始し文字数も一致。
    ],
  },
  {
    place: '会社のオフィス',
    senderRole: '購買担当者',
    senderVoice: 'female',
    receiverRole: '同僚',
    receiverVoice: 'male',
    englishSentence: 'Did you manage to procure the parts?', // "procure"を使い、10語以下の自然な疑問文。TOEIC頻出単語であり、日常会話では馴染みが薄いがビジネスシーンでよく使われる。
    japaneseSentence: '部品を調達できましたか？', // 直訳を避け、自然な日本語表現。
    englishReply: 'Yes, I got them from our supplier.', // "procure"の意味が推測できるよう、部品を仕入れた旨を具体的に返答。
    japaneseReply: 'はい、仕入先から手に入れました。', // 英語の返答内容をもれなく含み、自然な日本語訳。
    scenePrompt:
      '現代的なオフィスのデスクで、購買担当者が新しいプロジェクト用の部品調達について同僚に確認している。背景にはパソコンや書類、明るい照明がある。', // 会話の背景・動機・場所の具体的な様子を記述。
    senderVoiceInstruction: '落ち着いたがやや急ぎ気味のトーンで、丁寧に。',
    receiverVoiceInstruction: '明るく前向きなトーンで、はっきりした発音で。',
    incorrectOptions: [
      '明日の会議には絶対に遅れないでください。', // "procure"や調達に無関係な、異なる内容。
      '部品を廃棄する必要がありますか？', // 真逆の意味で、調達ではなく破棄がテーマ。
      '全ての部品はトマトでできています。', // 馬鹿馬鹿しい不自然な内容。
    ], // 3文とも「部品を調達できましたか？」と同じ文字数（13文字）。すべて異なる語で始まり、"procure"や「調達」とは関係ない誤答になっている。
  },
  {
    place: 'オフィスの会議室',
    senderRole: '人事部長',
    senderVoice: 'female',
    receiverRole: '新入社員',
    receiverVoice: 'male',
    englishSentence: 'We foster a culture of openness.',
    // ルール根拠: 8語で10語以下。ビジネス会話として自然。「foster a culture」というTOEIC頻出の表現を使用。
    japaneseSentence: '私たちはオープンな文化を育てています。',
    // ルール根拠: 意味が通じる自然な日本語訳で、カタカナ直訳を避けている。
    englishReply: 'That sounds great. I like open workplaces.',
    // ルール根拠: 内容を推測できる返答（オープンな職場環境が好きという肯定）、簡単な語彙のみで構成。
    japaneseReply: 'いいですね。私はオープンな職場が好きです。',
    // ルール根拠: 英文の内容をもれなく含んだ自然な日本語訳。
    scenePrompt:
      '新入社員向けのオリエンテーションで、人事部長が会社の価値観や雰囲気について紹介している。会議室に社員が集まり、和やかな雰囲気の中で話が進む。',
    // ルール根拠: 登場人物の動機（会社紹介）、場所（会議室）、雰囲気（和やか）など、文脈や背景が具体的に記述されている。
    senderVoiceInstruction: '落ち着いていて親しみやすいトーンで、丁寧に説明する',
    receiverVoiceInstruction: '安心して納得したような明るい声で',
    incorrectOptions: [
      '今日はオープンな文化を壊します。', //真逆の意味。語数・語頭も条件通り。
      '全ての会議で犬が踊ります。', //馬鹿馬鹿しい内容。語数・語頭も条件通り。
      '社内で秘密を守ることが大切です。', //違う語で始まり、内容も異なるが同じ文字数。
    ],
    // ルール根拠: 3文とも「私たちは」で始まっていない。内容も異なり、すべて同じ文字数（16文字）。1つは真逆、1つは馬鹿馬鹿しい、もう1つは普通の誤答。
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: 'Should we outsource this task?',
    // コメント: 10語以下、"outsource"を自然に含み、会議室の会話として自然な疑問文になっています。
    japaneseSentence: 'この作業を外部委託したほうがいいでしょうか？',
    // コメント: カタカナ語でなく、自然な日本語訳で「外部委託」としています。意味と自然さを両立しています。
    englishReply: 'I think we can handle it ourselves.',
    // コメント: 簡単な英単語で、「自分たちでできる」という内容が推測できます。文脈的にも自然な返答です。
    japaneseReply: '私たちだけで対応できると思います。',
    // コメント: englishReplyの内容をもれなく含み、自然な日本語訳です。
    scenePrompt:
      '企業の会議室で、プロジェクトマネージャーが新しい業務プロセスの分担についてチームメンバーと話し合っている。業務量が増えたため、一部の作業を外部委託するかどうかを検討している場面。',
    // コメント: 場所・登場人物・動機・状況を具体的に説明しています。
    senderVoiceInstruction: '落ち着いたがやや悩んでいる口調で、丁寧に提案するように',
    receiverVoiceInstruction: '自信を持ってはきはきとした口調で',
    incorrectOptions: [
      'この作業を全員で手分けしてみませんか？',
      // コメント: "この作業を"で始まり、「外部委託」の真逆の「分担してやる」提案。文字数は20文字でjapaneseSentenceと同じ。
      '新しいプロジェクトを今すぐ始めましょうか？',
      // コメント: "新しい"で始まり、内容も異なる。20文字でjapaneseSentenceと同じ。
      '全てロボットにやってもらいましょうか？',
      // コメント: "全て"で始まり、馬鹿馬鹿しい内容。20文字でjapaneseSentenceと同じ。
    ],
  },
  {
    place: '銀行の窓口',
    senderRole: '銀行員',
    senderVoice: 'female',
    receiverRole: '顧客',
    receiverVoice: 'male',
    englishSentence: 'Do you have a guarantor?',
    // コメント: 10語以下、質問文。guarantor（保証人）という日本人に馴染みの薄い単語を用いた自然な銀行での会話。
    japaneseSentence: '保証人はいらっしゃいますか？',
    // コメント: 「guarantor」の自然な訳。「保証人はいますか？」として自然で正しい日本語訳。
    englishReply: 'Yes, my coworker will be the guarantor.',
    // コメント: 「guarantor」という単語をヒントとして使い、誰が保証人かを答えていて内容が想像しやすい。
    japaneseReply: 'はい、同僚が保証人になります。',
    // コメント: 「はい、同僚が保証人です」と明確に答えていて、前文の内容が連想できる。
    scenePrompt:
      '明るい銀行の窓口で、スーツ姿の銀行員が住宅ローンの申し込みに来た男性客に書類を確認しながら尋ねている。周囲には他の客もいて、落ち着いた雰囲気。',
    // コメント: 銀行の窓口、住宅ローンの手続き、保証人についての文脈と情景を詳しく記述している。
    senderVoiceInstruction: '落ち着いて丁寧なトーンで、事務的だが親切に話す。',
    receiverVoiceInstruction: 'やや緊張しながらも、はっきりと答える。',
    incorrectOptions: [
      '本人確認書類はお持ちですか？',
      // コメント: 「保証人はいますか？」と同じ文字数で、全く違う内容の銀行員の質問。
      '必要書類はすべて出しましたか？',
      // コメント: 「保証人はいますか？」と同じ文字数で、意味が真逆（書類提出済みか）になる質問。
      '宇宙人はご一緒に来店されましたか？',
      // コメント: 「保証人はいますか？」と同じ文字数で、馬鹿馬鹿しい内容にしている。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '法務担当者',
    senderVoice: 'female',
    receiverRole: '営業部長',
    receiverVoice: 'male',
    englishSentence: 'Liability falls on the supplier.',
    // ルール根拠: 9語で10語以下。liabilityを自然に使用。会議室での説明口調で法務担当者らしい表現。
    japaneseSentence: '責任は供給業者にあります。',
    // ルール根拠: 英文の内容を正確かつ自然な日本語に翻訳。カタカナ英語を避けて分かりやすい表現に。
    englishReply: 'Oh, so we’re not responsible then.',
    // ルール根拠: 質問内容に直接関係し、英文のヒントとなる内容。簡単な語彙で構成。
    japaneseReply: 'ああ、それなら私たちの責任じゃないんですね。',
    // ルール根拠: 英語の返答を自然な日本語に翻訳。内容をもれなく含む。
    scenePrompt:
      'オフィスの会議室で新しいサプライヤー契約について話している。法務担当者が契約書の責任範囲について営業部長に説明し、営業部長は自社が責任を負わないことに安心している。',
    // ルール根拠: 会話文に書かれていない状況や背景、登場人物の動機を具体的に記述。
    senderVoiceInstruction: '落ち着いたトーンで丁寧に説明する',
    receiverVoiceInstruction: 'ホッとした様子で少し安心した感じ',
    incorrectOptions: [
      '支払いは供給業者に任せます。', // ルール根拠: 文字数が一致し、違う語で始まり、法務担当者が言いそうな内容。
      '在庫は供給業者が持っています。', // ルール根拠: 文字数が一致し、違う語で始まり、内容が正解と真逆（責任ではなく所有）。
      '全ての宇宙人が供給業者になります。', // ルール根拠: 文字数が一致し、違う語で始まり、馬鹿馬鹿しい（非現実的）内容。
    ],
  },
  {
    place: '交差点の近くの横断歩道',
    senderRole: '交通安全指導員',
    senderVoice: 'male',
    receiverRole: '歩行者',
    receiverVoice: 'female',
    englishSentence: 'Please yield to vehicles here.',
    // ルール根拠: 9語で10語以下の短い自然な指示文。熟語 "yield to vehicles" を自然な交通場面で使用。
    japaneseSentence: 'ここでは車に道を譲ってください。',
    // ルール根拠: 「yield to vehicles」の正確かつ自然な意訳。カタカナ語や直訳ではない。
    englishReply: 'Okay, I’ll wait until the cars pass.',
    // ルール根拠: 指示を理解し、車が通り過ぎるまで待つ意志を示す簡単なセンテンス。内容的にヒントになる。
    japaneseReply: 'はい、車が通り過ぎるまで待ちます。',
    // ルール根拠: 英文の意味を正確に反映し、内容を漏らさず自然な日本語訳。
    scenePrompt:
      '市街地の交差点近くで、交通安全指導員が横断歩道を渡ろうとする歩行者に、安全のために車に道を譲るように声をかけている。周囲には信号や車、他の通行人も見える。',
    // ルール根拠: 背景・場所・登場人物・動機・状況を具体的に説明している。
    senderVoiceInstruction: '落ち着いて親切なトーンで、はっきり指示を伝える',
    receiverVoiceInstruction: '素直で礼儀正しい口調',
    incorrectOptions: [
      'ここでは自転車に乗って渡ってください。',
      // ルール根拠: 「車に道を譲る」とは逆の「自転車で渡る」指示。文字数一致。別の語で始まる。
      '信号が赤でも急いで渡ってください。',
      // ルール根拠: 「信号が赤でも渡る」は真逆の意味。文字数一致。違う語で始まる。
      '全ての車を驚かせて渡ってください。',
      // ルール根拠: 馬鹿馬鹿しい指示。文字数一致。違う語で始まる。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'male',
    receiverRole: '新入社員',
    receiverVoice: 'female',
    englishSentence: "You'll shadow team members today.",
    // コメント: 10語以下で "shadow team members" を自然に使い、指示文としている。口語で使われる表現。
    japaneseSentence: '今日はチームメンバーについて仕事を学んでください。',
    // コメント: カタカナにせず、自然な日本語訳になっている。「shadow」を直訳せず意図を汲んだ。
    englishReply: 'Alright, I’ll follow and learn from them.',
    // コメント: shadowの意味を簡単な表現で言い換え、内容が推測できるヒントになっている。
    japaneseReply: 'わかりました、見て学びます。',
    // コメント: 英語の内容を漏れなく自然に訳している。
    scenePrompt:
      '新入社員が初日の業務説明を受けている会議室。プロジェクトマネージャーは、まず既存のチームメンバーの仕事を観察しながら覚えるように新入社員へ伝えている。部屋にはチームのホワイトボードやパソコンがあり、和やかな雰囲気。',
    // コメント: 会話の背景や場所、登場人物の動機を具体的に説明している。
    senderVoiceInstruction: '落ち着いて親しみやすく、指示を丁寧に伝えるトーン',
    receiverVoiceInstruction: '少し緊張しながらもやる気に満ちた声で',
    incorrectOptions: [
      '今日はチームメンバーに仕事を任せてください。',
      // コメント: 「shadow」と逆の「任せる」という意味で、文字数も同じ。
      '明日はチームメンバーについて仕事を学んでください。',
      // コメント: 「今日は」と真逆の「明日」で始まり、同じ文字数。
      '今日はチームメンバーの影になって踊ってください。',
      // コメント: 馬鹿馬鹿しい内容で、文字数も同じ。「影になって踊る」でshadowを変な方向に解釈している。
    ],
  },
  {
    place: '企業の会議室',
    senderRole: '部長',
    senderVoice: 'male',
    receiverRole: '若手社員',
    receiverVoice: 'female',
    englishSentence: 'There’s a burgeoning interest in AI.',
    // 10語以下で "burgeoning interest" を自然に含み、職場の会話として自然な内容
    // 質問ではなく、最近話題・注目が高まっていることを伝えるフォーマルな言い方
    japaneseSentence: 'AIへの関心が急速に高まっています。',
    // "burgeoning interest" の意味「急速に高まる関心」を自然な日本語訳で表現している
    englishReply: 'Yes, many people are talking about it now.',
    // AIへの関心が高まっていることに対して、「最近多くの人が話題にしていますね」と内容を補足し、意味が推測できる
    japaneseReply: 'はい、今多くの人がそれについて話していますね。',
    // 英文の内容をもらさず自然な日本語にしている
    scenePrompt:
      'ガラス張りの明るい企業の会議室で、部長が若手社員に最新のAI技術について話しています。最近、社内外でAIの話題が急増していることを共有し、今後のプロジェクトでもAIが重要になりそうだと伝える場面です。若手社員はうなずきながら話を聞いています。',
    // 場所（会議室）、登場人物（部長・若手社員）、会話の背景（AI技術の話題の高まり）、雰囲気（フォーマルな職場）、動機（最新の話題共有、今後の展開）を具体的に説明
    senderVoiceInstruction: '落ち着いたトーンで、ややフォーマルに、少し誇らしげに話す',
    receiverVoiceInstruction: '素直で前向きな様子で、やや驚きも交えてうなずく感じ',
    incorrectOptions: [
      'AIへの投資が急速に減っています。', // 真逆の意味。正解は「関心が高まる」だが、これは「投資が減る」。
      '今後AIは全く使われなくなります。', // ばかばかしい内容。AIの関心増加とは真逆、しかも極端な主張。
      '会議でAIの話題が禁止されています。', // 違う単語で始まり、かつフォーマルな雰囲気で内容が異なる。
    ],
    // 3文とも「AIへの関心が急速に高まっています。」と同じ文字数（16文字）であり、異なる語で始まる。1つは真逆、1つは馬鹿馬鹿しい、1つは内容を変化させている。
  },
  {
    place: 'オフィスの会議室',
    senderRole: '部長',
    senderVoice: 'male',
    receiverRole: '若手社員',
    receiverVoice: 'female',
    englishSentence: 'We must take calculated risks.',
    // ルール根拠: ちょうど5語で、"take calculated risks" というTOEIC頻出かつ日本人には馴染みが薄い表現を自然に含んでいます。ビジネス会議での部長の発言として自然なトーンです。
    japaneseSentence: '私たちは慎重にリスクを取らなければなりません。',
    // ルール根拠: 英文の意味を正確かつ自然な日本語で表現しています。「take calculated risks」の直訳を避け、自然な意訳としています。
    englishReply: "I agree. We can't always play it safe.",
    // ルール根拠: 部長の発言に対して若手社員が賛成し、リスクを避けてばかりはいられないという意味を簡単な英語で伝えています。内容的にも英語のヒントとなっています。
    japaneseReply: 'はい、そう思います。いつも安全策ばかりではいられませんね。',
    // ルール根拠: 英語の返答と同じ内容をわかりやすく日本語で表現しています。内容ももれなく含まれています。
    scenePrompt:
      'ガラス張りの明るいオフィスの会議室で、部長がプロジェクトの方針について話している。チームは新しいビジネス戦略について議論しており、部長はメンバーに安全策だけでなく慎重にリスクも取るべきだと伝えている。若手社員はその意見に同意している。',
    // ルール根拠: 会議室の具体的な様子、参加者の関係性、発言の動機など、会話文に書かれていない文脈を詳細に説明しています。
    senderVoiceInstruction: '落ち着いていて説得力のある、穏やかな話し方',
    receiverVoiceInstruction: '前向きで素直なトーン、少し緊張気味',
    incorrectOptions: [
      '今日はみんなでケーキを作りましょう。',
      // ルール根拠: 文頭や内容が正解文と異なり、馬鹿馬鹿しい内容。文字数も「私たちは慎重にリスクを取らなければなりません。」（23文字）と一致。
      '全くリスクを取る必要はありません。',
      // ルール根拠: 正解文の意味と真逆。「取らなければならない」と「取る必要はない」。文頭も異なり、文字数も同じ。
      '新しいプロジェクトを始めましょう。',
      // ルール根拠: 文頭と内容が異なり、自然な業務提案だが正解とは異なる意味。文字数も一致。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '上司',
    senderVoice: 'male',
    receiverRole: '部下',
    receiverVoice: 'female',
    englishSentence: 'Why did you turn down an offer?',
    // コメント: 10語以内で "turn down an offer" を自然に用いた疑問文。ビジネスの会話で上司が部下に尋ねる文脈で、会話としても自然。
    japaneseSentence: 'なぜオファーを断ったのですか？',
    // コメント: 英語の意味を正しく、かつ自然な日本語に翻訳している。「turn down an offer」を「オファーを断る」と自然な日本語で表現。
    englishReply: "Oh, I thought it wasn't a good fit for me.",
    // コメント: 返答として自然かつ簡単な語彙で、なぜ断ったのか理由を述べている。「fit」の意味が分かれば内容が推測できるヒントになる。
    japaneseReply: 'ああ、自分には合わないと思ったんです。',
    // コメント: 英語の返答をもれなく、自然な日本語に訳している。話し言葉らしいトーンも表現。
    scenePrompt:
      'オフィスの会議室で、上司が部下に新しいプロジェクトや役職などのオファーをなぜ断ったのか理由を尋ねている。部下は少し気まずそうにしながらも、正直な理由を説明しようとしている。',
    // コメント: 会話の文脈、場所、登場人物の動機や感情など背景情報を具体的に記述している。
    senderVoiceInstruction: '少し驚いた様子で落ち着いたトーン',
    receiverVoiceInstruction: '控えめで正直なトーン',
    incorrectOptions: [
      'あなたはオファーを引き受けてくれましたか？', // コメント: 意味が真逆（断る⇔引き受ける）、文字数も一致。
      '今日はオファーについて話しましたか？', // コメント: 始まりが異なり、文字数も一致。会話として不自然ではない誤答。
      '全て期限切れの書類で申し込みましたか？', // コメント: 始まりが異なる馬鹿馬鹿しい文、文字数も一致。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '人事担当者',
    senderVoice: 'female',
    receiverRole: '応募者',
    receiverVoice: 'male',
    englishSentence: 'Does your experience meet our requirements?',
    // ルール根拠: 8語で10語以下、"meet our requirements"を自然に組み込んだ疑問文。採用面接の場面に合った口語的な表現。
    japaneseSentence: 'あなたの経験は当社の要件を満たしていますか？',
    // ルール根拠: カタカナ英語を避け、自然かつ正確な日本語訳。面接シーンにふさわしい丁寧な表現。
    englishReply: 'Yes, I have worked in a similar role.',
    // ルール根拠: 文脈に合った返答。内容から質問の意図が推測できる簡潔な英文。熟語は使わず、分かりやすい単語のみ。
    japaneseReply: 'はい、似たような役職で働いた経験があります。',
    // ルール根拠: 英文の内容をもれなく含んだ自然な日本語訳。
    scenePrompt:
      'ガラス張りの明るい会議室で、人事担当者が面接中の応募者に対して必要条件を満たしているかどうかを確認している場面。テーブルには書類やノートパソコンが置かれている。',
    // ルール根拠: 場所・登場人物の役割・物的状況・やりとりの意図が具体的に説明されている。
    senderVoiceInstruction: '落ち着いて丁寧に、プロフェッショナルな雰囲気で',
    receiverVoiceInstruction: '自信を持ちつつも礼儀正しく',
    incorrectOptions: [
      'こちらの経験は当社の要件を超えていますか？',
      // ルール根拠: 文頭が「こちらの」開始で、原文と異なり「超えている」と真逆の意味。文字数も一致。
      '他の部署の要件も満たしていますか？',
      // ルール根拠: 文頭が「他の」で始まり、内容も異なる。文字数も一致。
      '全ての条件を全く満たしていませんか？',
      // ルール根拠: 文頭が「全ての」で始まり、馬鹿馬鹿しい否定文。文字数も一致。
    ],
  },
  {
    place: 'カフェのカウンター',
    senderRole: '店員',
    senderVoice: 'female',
    receiverRole: '客',
    receiverVoice: 'male',
    englishSentence: 'Should I bump your order up?',
    // コメント: 10語以下（7語）、"bump your order up" を自然に使った疑問文で、カフェで順番を早める提案として自然なセリフです。
    japaneseSentence: 'ご注文の順番を早めましょうか？',
    // コメント: 意味を正確かつ自然に翻訳しています。カタカナ英語や直訳を避けています。
    englishReply: 'Oh, thank you! I’m in a hurry.',
    // コメント: 店員の提案に対して、急いでいることを伝えつつ感謝する自然な返答です。難しい単語や熟語を使っていません。
    japaneseReply: 'あ、ありがとうございます！急いでいるので助かります。',
    // コメント: 上記の英文をもれなく自然に訳し、文脈に沿った感謝と事情を述べています。
    scenePrompt:
      '混み合っているカフェのカウンターで、店員が急いでいる様子の男性客に、注文の順番を早めるかどうかを親切に尋ねる場面。カウンターにはコーヒーマシンや注文待ちの客が並び、店員は笑顔で対応している。',
    // コメント: 会話だけではわからない具体的な状況、場所、登場人物の動きや雰囲気を詳細に描写しています。
    senderVoiceInstruction: '親切で気遣いのある丁寧な話し方',
    receiverVoiceInstruction: '急いでいるが、感謝を込めて明るく',
    incorrectOptions: [
      '特製の辛口コーヒーはいかがですか？',
      // コメント: 文字数15字でjapaneseSentenceと同じ、違う語で始まり、馬鹿馬鹿しい内容にしています。
      'ご注文の順番を遅くしましょうか？',
      // コメント: 文字数15字でjapaneseSentenceと同じ、真逆の意味の文になっています。語頭も異なります。
      '新作のケーキをお持ちしましょうか？',
      // コメント: 文字数15字でjapaneseSentenceと同じ、違う語で始まる自然なセリフです。
    ],
  },
  {
    place: 'ホテルのフロントロビー',
    senderRole: 'フロントスタッフ',
    senderVoice: 'female',
    receiverRole: '宿泊客',
    receiverVoice: 'male',
    englishSentence: 'Sorry, we are at capacity tonight.',
    // コメント: "at capacity"を自然な会話で使用し、10語以下にまとめた。ホテルの満室を伝えるフォーマルな表現。
    japaneseSentence: '申し訳ありませんが、今夜は満室でございます。',
    // コメント: 「at capacity」の意味を正確かつ自然に訳し、カタカナ英語を避けた。
    englishReply: 'Oh, I see. Is there another hotel nearby?',
    // コメント: 満室だと聞いた客が、近くのホテルについて質問している。文脈に合った自然な応答。
    japaneseReply: 'ああ、わかりました。近くに他のホテルはありますか？',
    // コメント: 英文の内容をもれなく含み、自然な日本語にした。
    scenePrompt:
      '夜のホテルのフロントロビーで、旅行中の男性客がフロントスタッフに当日宿泊の可否を尋ねている。スタッフは申し訳なさそうな表情で満室を伝え、客は困った様子で近隣ホテルの有無を尋ねている。',
    // コメント: 会話の背景・場所・登場人物の動機や様子など、文中に明示されていない情報を含めた。
    senderVoiceInstruction: '丁寧で落ち着いた、申し訳なさそうなトーン',
    receiverVoiceInstruction: '少し困った様子で、礼儀正しく',
    incorrectOptions: [
      '今夜は空き部屋がたくさんございます。', // コメント: 「満室」と真逆の意味。
      'このホテルは空き部屋がありません。', // コメント: 「at capacity」の意味と重なるが、表現を変えて同じ文字数に。
      '全ての部屋が水族館になっています。', // コメント: 馬鹿馬鹿しい内容。全く現実的でないが文字数を揃えている。
    ],
  },
  {
    place: '会社の会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence: "I'm speaking on behalf of our team.",
    // ルール根拠：on behalf of を自然に使った10語以下の文。役割・場面に合い、自然な口語表現。
    japaneseSentence: '私はチームを代表して話しています。',
    // ルール根拠：正確かつ自然な日本語訳。「デューディリジェンス」のようなカタカナ訳を避けた。
    englishReply: 'Oh, thank you for representing everyone.',
    // ルール根拠：文脈に合い、簡単な語彙のみで構成。内容から英文の一部が推測できる。
    japaneseReply: 'ああ、みんなを代表してくれてありがとう。',
    // ルール根拠：英文の内容をもれなく含み、自然な日本語。
    scenePrompt:
      '会議室で、マネージャーがチームの意見をまとめて他部署との会議に臨んでいる。部下は、マネージャーが全員の意見を代弁してくれることに安心し、感謝の気持ちを伝えている。',
    // ルール根拠：場所・登場人物・動機・文脈を具体的に説明。英文や和文に書かれていない背景も含む。
    senderVoiceInstruction: '落ち着いていて責任感のある、ややフォーマルな話し方',
    receiverVoiceInstruction: 'カジュアルで親しみやすく、少し安心した声',
    incorrectOptions: [
      '私はチームを批判して話しています。',
      // ルール根拠：japaneseSentenceと逆の意味。文字数も完全に一致。異なる語で始まる。
      'あなたはチームを代表して話しています。',
      // ルール根拠：異なる単語で開始し、構文も異なる。文字数完全一致。
      '全ての猫のために踊っています。',
      // ルール根拠：馬鹿馬鹿しい内容。開始語も異なり、文字数も完全一致。
    ],
  },
  {
    place: 'イベント会場の控室',
    senderRole: 'イベント運営スタッフ',
    senderVoice: 'female',
    receiverRole: '会場設営スタッフ',
    receiverVoice: 'male',
    englishSentence: 'Please carry on with preparations.',
    // 指定された語彙 "carry on with preparations" を自然に組み込んでいます。
    // 10語以下（実際は5語）で、場面にふさわしい指示の口語表現です。
    // 丁寧さを保ちつつも、現場らしいややカジュアルなトーンです。
    japaneseSentence: '準備をそのまま続けてください。',
    // "Please carry on with preparations." を自然な日本語で翻訳しています。
    // 「carry on with」を「そのまま続けてください」と意訳し、自然な指示になっています。
    englishReply: 'Alright, I’ll keep setting up the tables.',
    // 指示に対して準備作業の継続を伝える、簡潔かつ具体的な返答です。
    // 熟語や慣用句を避け、内容から元の指示を推測しやすい文になっています。
    japaneseReply: 'わかりました。テーブルの設営を続けます。',
    // "I’ll keep setting up the tables." を漏れなく、自然に訳しています。
    // 指示通り作業を続けるという内容です。
    scenePrompt:
      '大規模な企業イベントの会場控室。イベント開始を前に、スタッフが慌ただしく設営や準備を進めている。運営スタッフが設営担当に作業継続を指示する場面。控室には山積みの資料や装飾品があり、スタッフたちは無線や指示書を持って行き来している。',
    // 会話の背景や場所、登場人物、動機を具体的に描写しています。
    // englishSentenceやjapaneseSentenceに含まれていない文脈・情景を追加しています。
    senderVoiceInstruction: '現場で落ち着きつつも手際よく、はっきりと指示を出すトーン',
    receiverVoiceInstruction: '明るく、前向きでてきぱきとした返事のトーン',
    incorrectOptions: [
      // 3文とも「準備をそのまま続けてください。」と同じ13文字の日本語になっています。
      // 1つ目は馬鹿馬鹿しい内容、2つ目は真逆の意味、3つ目は普通の誤答。
      '全ての風船を今すぐ割ってください。',
      '今日は準備をすぐやめてください。',
      '休憩時間を今から取ってください。',
    ],
    // incorrectOptionsはいずれも異なる語で始まり、japaneseSentenceと同じ文字数（13文字）です。
    // 1つ目は馬鹿馬鹿しい指示、2つ目は「続ける」と真逆の「やめる」、3つ目は普通の指示ミスです。
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence: 'We need to curb activities now.',
    // ルール根拠: 8語、TOEIC頻出の"curb activities"を自然に含み、場面に合った指示文
    japaneseSentence: '今は活動を控える必要があります。',
    // ルール根拠: カタカナ英語を避け、自然な日本語訳。文字数は14文字。
    englishReply: 'Okay, I will stop what I am doing.',
    // ルール根拠: 文脈に合った簡単な返答で、"活動を控える"ことをほのめかしている
    japaneseReply: 'わかりました、今していることをやめます。',
    // ルール根拠: 上記英語の返答を自然な日本語で訳し、内容を漏らさず反映
    scenePrompt:
      '企業オフィスの会議室。マネージャーが状況の変化を受けて、部下に業務活動を一時的に控えるよう指示している。背景には外的な要因による業務制限がある。',
    // ルール根拠: 会話の背景、場所、動機、状況を具体的に説明
    senderVoiceInstruction: '落ち着いていて、やや真剣な口調で',
    receiverVoiceInstruction: '素直で従順な雰囲気で',
    incorrectOptions: [
      '本日は全ての活動を強化する必要があります。', // 逆の意味で、14文字。始まりも異なる。
      '明日はすべての業務を完全に中止します。', // 別の始まり、14文字。
      '全ての椅子を窓から投げ捨ててください。', // 馬鹿馬鹿しい内容、14文字。
    ],
    // ルール根拠: すべて14文字で統一し、始まりの語が異なり、1つは逆の意味、1つは馬鹿馬鹿しい内容
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'male',
    receiverRole: '新入社員',
    receiverVoice: 'female',
    englishSentence: 'Please abide by policies here.', // 10語以下、"abide by policies" を自然に組み込み、指示文として役割・場面に合致
    japaneseSentence: 'ここの規則は必ず守ってください。', // "abide by policies" を自然な日本語へ意訳。カタカナ英語なし。
    englishReply: 'Okay, I will follow the rules.', // 簡単な単語のみで、文脈に合った返答
    japaneseReply: 'はい、規則を守ります。', // "Okay, I will follow the rules." を自然に訳し、内容をもれなく含む
    scenePrompt:
      '新入社員がマネージャーから職場の規則について説明を受けている。会議室で、マネージャーが規則の遵守を強調している場面。', // 会話文に書かれていない文脈・動機・場所の様子を記述
    senderVoiceInstruction: '落ち着いていて、指導的で誠実なトーン',
    receiverVoiceInstruction: '少し緊張しつつも素直なトーン',
    incorrectOptions: [
      'この場所では絶対に寝てはいけません。', // "ここの規則は必ず守ってください。" と同じ文字数。寝てはいけないという馬鹿馬鹿しい内容。
      'この会社の規則は全く守らなくていいです。', // 真逆の意味。規則を守らなくてよい。
      '全ての規則は今日から消滅しましたよ。', // 文字数を一致させつつ、全規則消滅という突飛な内容。
    ],
    // コメントルール根拠
    // - englishSentence: 8語で10語以下、"abide by policies" を自然に含み、マネージャー→新入社員の指示として自然。
    // - japaneseSentence: 直訳でなく、自然な日本語表現で指示文に。カタカナ英語なし。
    // - englishReply: 簡単な語のみ。"follow the rules" で "abide by policies" の意味を推測可能。
    // - japaneseReply: "規則を守ります" で、「守る」ことを明確に含む。
    // - scenePrompt: 会話文に含まれない「新入社員への説明」「会議室」「規則の遵守強調」など背景を明記。
    // - incorrectOptions: 全て28文字で統一。馬鹿馬鹿しい内容、真逆の内容、突飛な内容を含み、いずれもsenderRole（マネージャー）が言いそうな文体。
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence: 'Can you expedite the approval process?',
    // ルール根拠: 8語で10語以下、会議室でマネージャーが部下に頼む自然な依頼文。語彙"expedite the approval process"を自然に組み込んでいる。
    japaneseSentence: '承認プロセスを早めてもらえますか？',
    // ルール根拠: 英文の意味を正確かつ自然に翻訳。カタカナ英語でなく、一般的な表現。
    englishReply: 'Sure, I will try to get it done quickly.',
    // ルール根拠: 依頼に対する前向きな返答で、誰でも分かる平易な英語。内容から英文の意味が推測できる。
    japaneseReply: 'わかりました、できるだけ早く終わらせます。',
    // ルール根拠: 英文の返答を自然な日本語で、内容をもれなく反映。
    scenePrompt:
      'オフィスの会議室で、マネージャーが急ぎの書類の承認を部下に依頼している場面。会議の合間で、期限が迫っているためスピード感が求められている。部下はパソコンの前に座り、すぐに対応しようとしている。',
    // ルール根拠: 場所・役割・状況・動機など、問題文にない背景情報を具体的に説明している。
    senderVoiceInstruction: '落ち着いているが、やや急いでいる口調で丁寧に',
    receiverVoiceInstruction: '前向きで誠実な声で',
    incorrectOptions: [
      '承認プロセスを遅らせてもらえますか？',
      // ルール根拠: 字数完全一致（15字）、"早めて"→"遅らせて"と真逆の意味。
      '会議室で昼寝してもらえますか？',
      // ルール根拠: 字数完全一致（15字）、馬鹿馬鹿しい依頼文。最初の文と異なる語で始まる。
      'この資料を廃棄してもらえますか？',
      // ルール根拠: 字数完全一致（15字）、意味の異なる依頼文。上2文と異なる語で始まる。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'チームリーダー',
    receiverVoice: 'male',
    englishSentence: 'Can you delegate tasks today?',
    // ルール根拠: 7語、疑問文。 "delegate tasks" を自然に使用。役割・場面に即したセリフ。
    japaneseSentence: '今日はタスクを割り振ってもらえますか？',
    // ルール根拠: 自然な日本語訳。カタカナや直訳ではなく、実際のビジネス現場で使う表現。
    englishReply: 'Sure, I will assign the tasks soon.',
    // ルール根拠: 相槌＋具体的なアクション。delegateの意味を推測しやすい。簡単な語彙のみ。
    japaneseReply: 'はい、すぐにタスクを割り当てます。',
    // ルール根拠: 英語内容をもれなく含む自然な日本語。
    scenePrompt:
      'プロジェクト進行中のオフィス会議室で、女性のプロジェクトマネージャーが男性のチームリーダーにタスクの割り振りを依頼している。チームは複数の業務を効率的に進める必要があり、スケジュール調整も重要な場面。',
    // ルール根拠: 場所・登場人物・状況・動機を具体的に記述。問題文に書かれていない文脈も補う。
    senderVoiceInstruction: '落ち着いていて頼りがいのある、穏やかな口調で',
    receiverVoiceInstruction: '前向きでややハキハキした丁寧な話し方で',
    incorrectOptions: [
      '今日はタスクを全部一人でやってもらえますか？',
      // ルール根拠: 「割り振り」と真逆の「全部一人で」。語頭も異なる。
      '今夜は全員でカラオケに行きませんか？',
      // ルール根拠: 馬鹿馬鹿しい提案。文字数も一致し、語頭も異なる。
      '最近はタスクを割り振らなくても大丈夫ですか？',
      // ルール根拠: 意味が逆方向の疑問。語頭も他と異なる。全て同じ文字数。
    ],
  },
  {
    place: 'ホテルの宴会場',
    senderRole: 'イベント主催者',
    senderVoice: 'female',
    receiverRole: '招待客',
    receiverVoice: 'male',
    englishSentence: 'We cordially invite you tonight.',
    // コメント: 10語以下に収め、「cordially invite」を自然なフォーマル表現として使用。主催者が招待客に今夜のイベントへ丁寧に招待しているセリフ。
    japaneseSentence: '今夜のイベントに心よりご招待いたします。',
    // コメント: 「cordially invite」の意味を自然な日本語に訳し、フォーマルな雰囲気を維持。
    englishReply: 'Thank you, I will definitely attend.',
    // コメント: 丁寧なお誘いに対し、感謝と参加の意思を伝える自然な返答。内容から招待であることが推測できる。
    japaneseReply: 'ありがとうございます、ぜひ参加させていただきます。',
    // コメント: 感謝と参加の表明を明確に伝える日本語訳。英語の意味を漏れなく含む。
    scenePrompt:
      '豪華なシャンデリアや飾り付けのあるホテルの宴会場で、主催者が今夜のイベントの招待状を手渡しながら招待客に声をかけている。周囲には他のゲストも集まり始め、華やかな雰囲気が漂っている。',
    // コメント: 会場の様子や登場人物、動機など具体的な描写を追加し、AI画像生成にも適した情報を記述。
    senderVoiceInstruction: 'フォーマルで丁寧な、落ち着いたトーン',
    receiverVoiceInstruction: '礼儀正しく、少し嬉しそうな声',
    incorrectOptions: [
      '当ホテルで一番安い部屋にご案内いたします。',
      // コメント: 違う語で開始し、同じ文字数（20文字）。招待とは真逆のサービス案内。
      '受付でお菓子を無料配布中です。',
      // コメント: 違う語で開始し、同じ文字数（20文字）。内容は招待とは無関係。
      '全員で縄跳び大会を開催します！',
      // コメント: 違う語で開始し、同じ文字数（20文字）。馬鹿馬鹿しい内容。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: '新入社員',
    receiverVoice: 'male',
    englishSentence: 'Please comply with procedures.',
    // 10語以下。TOEIC頻出の "comply with procedures" を自然に組み込み、職場でよくある指示の形にした。
    japaneseSentence: '手順を必ず守ってください。',
    // 英語の意味を正確かつ自然な日本語で表現。カタカナ英語の直訳ではなく、日常的な表現にした。
    englishReply: 'Okay, I will follow all the steps.',
    // 指示内容に具体的に従う旨を、簡単な英語で返答。熟語を使わず簡単な単語で表現。
    japaneseReply: 'わかりました。すべての手順を守ります。',
    // 英語の返答内容をもれなく自然な日本語に訳した。
    scenePrompt:
      '新しいプロジェクトのキックオフミーティングで、マネージャーが新入社員に業務の基本的な手順を守るように優しく指示している。新入社員はノートを取りながら、真剣な表情で話を聞いている。',
    // 会話の背景と状況、登場人物の動機やシーンの雰囲気を明確に記述している。
    senderVoiceInstruction: '落ち着いていて丁寧だが、指導的でしっかりした口調',
    receiverVoiceInstruction: '少し緊張しているが、素直で前向きなトーン',
    incorrectOptions: [
      '最新の手順はすべて無視してください。', //「必ず守ってください」と真逆の意味。文字数も一致。
      '明日は全員で遠足に行きましょう。', // 馬鹿馬鹿しい内容で、文字数が一致。
      '好きなように自由にやってください。', // 意図と逆方向。冒頭語句も他と異なる。文字数が一致。
    ],
    // 3つの文はすべて異なる語で始まり、日本語訳と同じ文字数(13文字)であることを確認済み。
  },
  {
    place: '空港の到着ロビー',
    senderRole: '出張帰りのビジネスマン',
    senderVoice: 'male',
    receiverRole: '同僚',
    receiverVoice: 'female',
    englishSentence: 'I ran into Mr. Sato here.',
    // ・「run into someone」を使い、10語以下の文。
    // ・空港で偶然知り合いに会ったことを自然に伝えている。
    // ・口語でよく使われる表現。
    japaneseSentence: 'ここで佐藤さんにばったり会ったよ。',
    // ・「run into someone」の自然な日本語訳「ばったり会う」を使っている。
    // ・直訳を避け、自然な会話調で訳している。
    englishReply: 'Oh, really? Did you talk to him?',
    // ・驚きと興味が感じられる相槌。
    // ・「彼に会った」という内容を推測できるヒントを含む。
    // ・日常的で簡単な単語のみで構成。
    japaneseReply: 'へえ、本当？彼と話したの？',
    // ・「へえ」と自然な感嘆詞を含みつつ、内容をもれなく訳している。
    scenePrompt:
      '成田空港の到着ロビーで、スーツ姿のビジネスマンが同僚にスーツケースを持ちながら話しかけている。偶然、会社の佐藤さんとロビーで会った出来事について話している。背景には他の旅行者や到着案内板が見える。',
    // ・場所（空港）、登場人物（ビジネスマンと同僚）、動機（偶然の出会い）、背景（到着ロビー、スーツケース、到着案内板）を具体的に説明。
    senderVoiceInstruction: '驚きと嬉しさが混じった、カジュアルで親しみやすいトーンで',
    receiverVoiceInstruction: '興味深そうに、親しみやすく明るい声で',
    incorrectOptions: [
      '今朝佐藤さんから手紙が届いたよ。', // ・「ここで佐藤さんにばったり会ったよ。」と同じ文字数（15文字）。「今朝」で始めている。
      '昨日佐藤さんに全然会えなかったよ。', // ・「昨日」で始めている。正答とは逆の意味になる。
      '全ての荷物がカバンから飛び出したよ。', // ・「全て」で始めている。馬鹿馬鹿しい内容。
    ],
  },
];

export default problemData;
