import { SeedProblemData } from '../src/types/problem';

/**
 * 問題データ 3
 * Generated by GPT API (30 problems)
 */
const problemData: SeedProblemData[] = [
  {
    place: 'オフィスの会議室',
    senderRole: '部長',
    senderVoice: 'male',
    receiverRole: '新入社員',
    receiverVoice: 'female',
    englishSentence: 'We must address this vulnerability.',
    // ルール根拠: 6語以内で "vulnerability" を自然に用い、会議室の会話として適切な直訳系文。
    japaneseSentence: 'この弱点に対処しなければなりません。',
    // ルール根拠: 「vulnerability」は「弱点」と訳し、自然な日本語表現を選択。カタカナNGも遵守。
    englishReply: 'I understand. I’ll look into it.',
    // ルール根拠: 単純な語彙で、部長への返答として自然。相槌も含めている。
    japaneseReply: 'わかりました。調べてみます。',
    // ルール根拠: 新入社員らしい返答で、内容から英語文の意味を推測できる。
    scenePrompt:
      '朝の会議室で部長がプロジェクト進行中に発覚したシステムの弱点について新入社員に指示を出している場面。新入社員は、問題解決のために調査を約束している。',
    // ルール根拠: 会議室・登場人物の役割・状況説明を具体的に記述。
    senderVoiceInstruction: '落ち着いたがやや厳格な口調で、指示を淡々と伝える',
    receiverVoiceInstruction: '若々しく少し緊張した様子で、丁寧に返事をする',
    incorrectOptions: [
      '新しいプロジェクトを開始しましょう。',
      // ルール根拠: "この弱点に対処しなければなりません。"と長さが近く、部長らしいが意味が逆（前向き）。
      '本日の昼食は全員でピザにします！',
      // ルール根拠: 馬鹿馬鹿しい内容（会議室で突然ピザを提案）。
      '今すぐこの計画を中止しましょう。',
      // ルール根拠: "この弱点に対処する"の真逆で「やめる」提案、始まりの語も全て異なる。
    ],
  },
  {
    place: 'カフェのカウンター',
    senderRole: '常連客',
    senderVoice: 'female',
    receiverRole: 'バリスタ',
    receiverVoice: 'male',
    englishSentence: 'How’s the aftermath of yesterday?',
    // ルール根拠: 6語以内の疑問文で "aftermath" を自然に使用。カフェで前日の出来事を尋ねる会話。
    japaneseSentence: '昨日の影響はどうだった？',
    // ルール根拠: 「aftermath」は「影響」と自然に訳し、口語的なやりとりに。
    englishReply: 'Oh, things are calm now.',
    // ルール根拠: 簡単な語彙で自然な返事。相槌も含めている。
    japaneseReply: 'ああ、今は落ち着いていますよ。',
    // ルール根拠: バリスタらしい返答で、質問内容の推測ができる。
    scenePrompt:
      'カフェで常連客が、前日に大雨か何かトラブルがあったことを思い出し、バリスタにその後どうなったかを気遣って尋ねている状況。バリスタは安心させるように答えている。',
    // ルール根拠: カフェの情景・出来事・登場人物の関係性と動機を明確に記述。
    senderVoiceInstruction: 'カジュアルで親しみやすい、気軽なトーン',
    receiverVoiceInstruction: '穏やかで安心感のある落ち着いた口調',
    incorrectOptions: [
      '今日は何か特別なイベントがありますか？',
      // ルール根拠: 長さが近く、カフェの会話で自然な疑問文。
      'パフェにホットドッグをのせてもいいですか？',
      // ルール根拠: 馬鹿馬鹿しい内容で、現実離れした奇抜な提案。
      '昨日のことはもうすっかり忘れましたか？',
      // ルール根拠: 真逆の意味で、「影響が残っているか」ではなく「もう全部忘れたか？」と尋ねており、語頭も異なる。
    ],
  },
  {
    place: '建設現場の仮設事務所',
    senderRole: '現場監督',
    senderVoice: 'male',
    receiverRole: '現場作業員',
    receiverVoice: 'female',
    englishSentence: 'This is a significant milestone.',
    // ルール根拠: 6語以内で "milestone" を自然に使用し、建設現場で使われそうな表現に。
    japaneseSentence: 'これは大きな節目ですね。',
    // ルール根拠: 「milestone」は「節目」として、自然な日本語に。
    englishReply: 'Yes, it’s a big achievement.',
    // ルール根拠: 単純な語で、現場での会話としても自然。
    japaneseReply: 'はい、大きな成果ですね。',
    // ルール根拠: 会話の流れとして自然で、内容から意味の推測もできる。
    scenePrompt:
      '建設現場の事務所で、長いプロジェクトの重要な工程が完了し、現場監督が作業員たちとその達成感を分かち合っている場面。',
    // ルール根拠: 現場の状況や人間関係、文脈を具体的に説明。
    senderVoiceInstruction: '誇らしげで明るいトーン、達成感を込めて',
    receiverVoiceInstruction: '嬉しそうで活気のある口調',
    incorrectOptions: [
      '次の作業は明日から始まります。',
      // ルール根拠: 長さが近く、現場監督らしいが「節目」とは意味が異なる。
      '今日の会議はカエルの着ぐるみで参加してください。',
      // ルール根拠: 馬鹿馬鹿しい発想、現場には不似合いな内容。
      'これは小さな失敗ですね。',
      // ルール根拠: 「大きな節目」と真逆の意味。「小さな失敗」としている。語頭も異なる。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'チームリーダー',
    receiverVoice: 'male',
    englishSentence: "Let's set a new benchmark.",
    // コメント: 直訳で理解できる「直訳系」。6語以内で、"benchmark"を自然に組み込んだ命令文です。
    japaneseSentence: '新しい基準を設定しましょう。',
    // コメント: 「benchmark」をただカタカナにせず、「基準」と自然に訳しています。
    englishReply: 'Sure, I agree with that.',
    // コメント: 相槌を含んだ、簡潔かつ内容を推測しやすい返答です。
    japaneseReply: 'うん、それでいいと思います。',
    // コメント: 「それでいい」という表現で「新しい基準」の話題が読み取れます。
    scenePrompt:
      '会議室でプロジェクト推進のための打ち合わせが行われている。進捗や成果を測るための新しい基準を決めようとしている場面。プロジェクトマネージャーが積極的に提案し、チームリーダーも前向きに応じている。',
    // コメント: 会議室・役割・動機・背景・様子を具体的に記述。
    senderVoiceInstruction: '明るく前向きなトーンで提案する',
    receiverVoiceInstruction: '落ち着いて納得した様子で',
    incorrectOptions: [
      '特別ボーナスを毎月支給しましょう。',
      // コメント: 「新しい基準を設定」ではなく全く異なる内容の提案です。
      'もう基準は作らずに進めましょう。',
      // コメント: 「新しい基準を設定しましょう」と真逆の意味になります。
      'ここを秘密基地にしましょう！',
      // コメント: 馬鹿馬鹿しい提案です。
    ],
  },
  {
    place: 'IT企業のオフィス',
    senderRole: 'ITマネージャー',
    senderVoice: 'male',
    receiverRole: 'システムエンジニア',
    receiverVoice: 'female',
    englishSentence: 'Do we have a contingency plan?',
    // コメント: "contingency plan"を自然に組み込んだ、6語以内の疑問文。TOEIC頻出の熟語系。
    japaneseSentence: 'もしもの時の対応策はありますか？',
    // コメント: 「contingency plan」を自然な日本語「もしもの時の対応策」と訳しています。
    englishReply: 'Yes, we prepared one already.',
    // コメント: 簡潔な肯定で、内容のヒントにもなっています。
    japaneseReply: 'はい、すでに用意してあります。',
    // コメント: 「用意してある」ことで質問の内容を推測しやすくしています。
    scenePrompt:
      'ITシステムの重要なリリース前。トラブル発生時の備えについてITマネージャーが確認している。エンジニアはしっかり準備していることを伝え、安心感を与えようとしている。',
    // コメント: 企業のリリース直前の状況、役割、意図、緊張感を具体的に表現。
    senderVoiceInstruction: '少し心配そうに、落ち着いた口調で',
    receiverVoiceInstruction: '自信を持った明るい声で',
    incorrectOptions: [
      '明日の計画はもう決めましたか？',
      // コメント: 「対応策」ではなく別の話題（スケジュール確認）です。
      'トラブルが起きても何も準備しません。',
      // コメント: 「対応策はあるか」と逆の意味になる回答です。
      '対応策としてカレーを大量に作りましょう！',
      // コメント: 馬鹿馬鹿しい提案です。
    ],
  },
  {
    place: '大学の講義室',
    senderRole: '教授',
    senderVoice: 'female',
    receiverRole: '学生',
    receiverVoice: 'male',
    englishSentence: 'How can we improve sustainability?',
    // コメント: "sustainability"（持続可能性）を6語以内で活用した疑問文。TOEIC頻出の熟語系。
    japaneseSentence: 'どうすれば持続可能性を高められますか？',
    // コメント: カタカナ語にせず「持続可能性」と訳し、自然な日本語にしています。
    englishReply: 'We could reduce waste, maybe.',
    // コメント: 「ゴミを減らす」という具体策で質問の内容を推測できる返答です。
    japaneseReply: 'ゴミを減らすのがいいかもしれません。',
    // コメント: 質問の意図が伝わるような例示的な返答にしています。
    scenePrompt:
      '大学の環境学の講義中。教授が学生に、地球環境や社会のためにどのように持続可能性を高めるかアイデアを求めている場面。学生は身近な例を挙げて意見を述べる。',
    // コメント: 大学講義の具体的なテーマ、登場人物の意図、場面背景を説明しています。
    senderVoiceInstruction: '知的で穏やかなトーンで質問する',
    receiverVoiceInstruction: '自信はないが前向きな様子で',
    incorrectOptions: [
      'この講義で使う本は何ですか？',
      // コメント: 全く別の話題の質問です。
      '持続可能性を無視して進めましょうか？',
      // コメント: 「高める」ことの逆で「無視する」提案です。
      '持続可能性のために空を飛びましょうか？',
      // コメント: 馬鹿馬鹿しい提案です。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'male',
    receiverRole: '部下',
    receiverVoice: 'female',
    englishSentence: 'Our turnover has increased lately.',
    // 英単語"turnover"（離職率または売上高）が含まれており、6語以内で自然な会話文になっています。
    japaneseSentence: '最近、離職率が上がっているんだ。',
    // 直訳ではなく、"turnover"を「離職率」と自然な日本語にしています。
    englishReply: "Oh, I didn't notice that.",
    // 難しい熟語は使わず、聞いて驚いた自然な返答です。
    japaneseReply: 'ああ、それは気づきませんでした。',
    // 上司からの報告に驚いた部下の自然な返答です。
    scenePrompt:
      'オフィスの会議室で、マネージャーが最近の人材の流動性について部下と話している。マネージャーは部下に現状を共有し、改善策を考えさせたいと思っている。部屋には会議用のテーブルとホワイトボードがあり、部下はパソコンを前にしている。',
    // 会議室の雰囲気、マネージャーの意図、部下の行動が具体的に描写されています。
    senderVoiceInstruction: '落ち着いたトーンで、少し心配そうに',
    receiverVoiceInstruction: '驚きと少し戸惑いを含んだ声で',
    incorrectOptions: [
      '今日は新しいデザートを用意しました。',
      // "turnover"や「離職率」とは全く関係なく、馬鹿馬鹿しい会話になっています。
      '今月は離職率が下がっています。',
      // japaneseSentenceの「上がっている」と真逆の意味「下がっている」になっています。
      '来週のプロジェクトについて話しています。',
      // 別の会話トピックで、かつ文頭の語も異なり、他と被っていません。
    ],
  },
  {
    place: '工場の休憩室',
    senderRole: '現場監督',
    senderVoice: 'female',
    receiverRole: '作業員',
    receiverVoice: 'male',
    englishSentence: 'Our workforce needs more training.',
    // "workforce"（労働力・従業員）が自然に使われており、6語以内です。
    japaneseSentence: 'うちの従業員はもっと研修が必要だね。',
    // "workforce"を自然な日本語で「従業員」と訳しています。
    englishReply: 'Yes, I agree with you.',
    // 簡単で自然な同意の返答です。
    japaneseReply: 'はい、私もそう思います。',
    // シンプルで日本語として自然な同意表現です。
    scenePrompt:
      '工場の昼休み、現場監督が作業員と一緒に休憩している。最近、新しい機械が導入されて操作ミスが増えており、監督は従業員のスキルアップが必要だと感じている。',
    // 工場、昼休み、新しい機械、操作ミス、スキルアップの必要性という文脈が具体的に説明されています。
    senderVoiceInstruction: 'カジュアルで親しみやすく、やや真剣に',
    receiverVoiceInstruction: '明るく素直に同意する声で',
    incorrectOptions: [
      'この前の旅行は本当に楽しかったね。',
      // 会話の流れと全く関係ない馬鹿馬鹿しい発言です。
      'うちの従業員は十分に研修を受けているね。',
      // japaneseSentenceの真逆の意味です。
      '新しい制服が来週届くそうです。',
      // 別の話題になっていて、他の選択肢と文頭が被っていません。
    ],
  },
  {
    place: '自動車メーカーの受付ロビー',
    senderRole: '受付係',
    senderVoice: 'male',
    receiverRole: '来訪者',
    receiverVoice: 'female',
    englishSentence: 'The headquarters moved last month.',
    // "headquarters"（本社）が自然に使われ、6語以内です。
    japaneseSentence: '本社は先月移転しました。',
    // "headquarters"を自然な日本語で「本社」と訳しています。
    englishReply: 'Oh, I had no idea.',
    // 難しい熟語を使わず、驚きのリアクションをしています。
    japaneseReply: 'ああ、それは全然知りませんでした。',
    // シンプルで自然な驚きの返答です。
    scenePrompt:
      '自動車メーカーの受付ロビーで、来訪者が受付係に本社の場所を尋ねたところ、受付係が本社が先月移転したことを伝えている。ロビーは広く、案内板や観葉植物が置かれている。',
    // 場所・登場人物・やりとりの動機・周囲の描写が明確です。
    senderVoiceInstruction: '親切で丁寧な説明口調で',
    receiverVoiceInstruction: '驚きを含んだやや高めの声で',
    incorrectOptions: [
      '本社は宇宙に引っ越しました。',
      // 馬鹿馬鹿しい発想（現実的ではない移転先）。
      '本社はまだ移転していません。',
      // 真逆の内容です。
      '新しい部署ができたそうです。',
      // 別の話題で、他の選択肢と文頭の語も被っていません。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '部長',
    senderVoice: 'male',
    receiverRole: '社員',
    receiverVoice: 'female',
    englishSentence: 'Our subsidiary needs more support.',
    // 6語以内で "subsidiary" を自然に組み込んでいます。
    japaneseSentence: 'うちの子会社にもっと支援が必要だ。',
    // "subsidiary" を「子会社」と自然に訳しています。
    englishReply: 'Oh, I see. I’ll help them.',
    // 難しい表現を避け、簡潔な英語で部長の意図を受け止めています。
    japaneseReply: 'ああ、わかりました。手伝います。',
    // 簡単な日本語で、部長の発言の意図を推測できる返事です。
    scenePrompt:
      '部長と社員が会議室で子会社の運営について話し合っている。子会社が直面している課題について部長が懸念を示し、社員はそのサポートを申し出ている場面。',
    // 場所・登場人物・動機・背景を具体的に説明しています。
    senderVoiceInstruction: '落ち着いていて頼りがいのある話し方',
    receiverVoiceInstruction: '明るく前向きなトーンで',
    incorrectOptions: [
      '新しい子会社を今すぐ作りましょう。',
      // "うちの子会社にもっと支援が必要だ。" と文字数が近く、意味が逆方向（新設を提案）です。文頭も違います。
      '本社は子会社を閉鎖する予定です。',
      // "本社"から始まり真逆の意味（閉鎖）です。
      '子会社の社長が空を飛べるそうです。',
      // 馬鹿馬鹿しい内容で、かつ文頭も異なります。
    ],
  },
  {
    place: 'IT企業のオフィス',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'エンジニア',
    receiverVoice: 'male',
    englishSentence: 'We’re considering outsourcing this project.',
    // 6語以内で "outsourcing" を自然に組み込んでいます。
    japaneseSentence: 'このプロジェクトの外部委託を検討しています。',
    // "outsourcing" を「外部委託」と自然な日本語に訳しています。
    englishReply: 'Okay, I understand your plan.',
    // 簡単な英語で、相手の意図を受け止めています。
    japaneseReply: 'わかりました。方針は理解しました。',
    // シンプルで推測しやすい返事です。
    scenePrompt:
      'プロジェクトマネージャーがエンジニアに、新規プロジェクトの進め方について相談している。コスト削減や効率化のため外部委託を検討している状況。',
    // 場面、役割、背景を具体的に説明しています。
    senderVoiceInstruction: '冷静で論理的なトーンで',
    receiverVoiceInstruction: '真面目で丁寧な話し方',
    incorrectOptions: [
      'このプロジェクトは全て手作業です。',
      // 文頭が異なり、「外部委託」とは逆の意味（手作業）。
      '私たちの部署で全て進めます。',
      // 文頭が違い、逆の意味（自部署対応）。
      'プロジェクトを宇宙人に任せてみましょう。',
      // 馬鹿馬鹿しい内容です。
    ],
  },
  {
    place: '倉庫の事務所',
    senderRole: '物流担当者',
    senderVoice: 'male',
    receiverRole: '上司',
    receiverVoice: 'female',
    englishSentence: 'Logistics will be delayed by storms.',
    // 6語以内で "logistics" を自然に会話で使っています。
    japaneseSentence: '嵐の影響で物流が遅れます。',
    // "logistics" を「物流」と自然な日本語に訳しています。
    englishReply: "Oh, that can't be helped.",
    // 簡単な英語で、事情を理解したことを伝えています。
    japaneseReply: 'そうか、それは仕方ないね。',
    // 推測しやすい日本語の返答です。
    scenePrompt:
      '物流担当者が上司に、天候不良の影響で荷物の配送が遅れることを報告している。嵐が発生しているため、通常のスケジュールが守れない状況。',
    // 背景や登場人物、理由を具体的に説明しています。
    senderVoiceInstruction: '誠実で丁寧な説明口調',
    receiverVoiceInstruction: '落ち着いて受け止めるトーン',
    incorrectOptions: [
      '嵐でも荷物は瞬間移動します。',
      // 馬鹿馬鹿しい内容。文頭も違います。
      '荷物は予定より早く届きます。',
      // 文頭が異なり、真逆の意味（早まる）。
      '今日は倉庫でお祭りをします。',
      // 文頭が異なり、関係のない内容です。
    ],
  },
  {
    place: '物流センター',
    senderRole: '倉庫マネージャー',
    senderVoice: 'male',
    receiverRole: '配送スタッフ',
    receiverVoice: 'female',
    englishSentence: 'Has the distribution begun yet?',
    // 6語以内、自然な疑問文。distributionを含む。TOEIC頻出語。
    japaneseSentence: 'もう配送は始まっていますか？',
    // 「Has the distribution begun yet?」の自然な日本語訳。カタカナ英語ではなく、自然な「配送」。
    englishReply: 'Yes, the first trucks just left.',
    // 簡単な単語のみ、context的に配送が始まったことを示す内容。
    japaneseReply: 'はい、最初のトラックがちょうど出発しました。',
    // 英文と対応し、自然な相槌。
    scenePrompt:
      '広い物流センターのオフィスで、マネージャーが配送スタッフに本日の配送作業の進捗を確認している。スタッフはトラックの出発状況を報告している。',
    // 場所・登場人物・状況（進捗確認と報告）を説明。
    senderVoiceInstruction: 'テキパキとした口調で、確認するように',
    receiverVoiceInstruction: '明るく元気に、報告するように',
    incorrectOptions: [
      '今夜は倉庫で映画を観ませんか？',
      // 馬鹿馬鹿しい。「distribution」とまったく関係ない内容。
      '今日の配送はまだ始まっていません。',
      // 「もう配送は始まっていますか？」の真逆の意味（始まっていない）。
      '多数の新商品がすでに届いています。',
      // 「始まる」ではなく、「商品が届いている」という異なる内容。
    ],
  },
  {
    place: '会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'チームリーダー',
    receiverVoice: 'male',
    englishSentence: 'Did you finish stakeholder analysis?',
    // 6語以内。「stakeholder analysis」を含む、TOEIC的自然な疑問文。
    japaneseSentence: 'ステークホルダー分析は終わりましたか？',
    // 日本語として自然な訳。TOEIC頻出のカタカナ英語「ステークホルダー分析」は日本語でも定着。
    englishReply: 'Yes, I completed it yesterday.',
    // シンプルな完了報告。簡単な単語のみ。
    japaneseReply: 'はい、昨日終わらせました。',
    // 簡潔な日本語訳。
    scenePrompt:
      'オフィスの会議室で、プロジェクトマネージャーが進捗確認のため、チームリーダーに対して業務の完了状況を尋ねている。',
    // 場所・役割・目的（進捗確認と返答）を具体的に説明。
    senderVoiceInstruction: '丁寧で落ち着いた確認口調で',
    receiverVoiceInstruction: '自信を持って、簡潔に',
    incorrectOptions: [
      'コアラが分析レポートを食べてしまいましたか？',
      // 馬鹿馬鹿しい。stakeholder analysisと全く関係ない。
      'ステークホルダー分析はまだ終わっていません。',
      // 真逆の意味（終わっていない）。
      '新しい会議の資料は作成しましたか？',
      // 別の業務内容への質問。
    ],
  },
  {
    place: 'ビジネス会食のレストラン',
    senderRole: '企業経営者',
    senderVoice: 'male',
    receiverRole: '取引先担当者',
    receiverVoice: 'female',
    englishSentence: 'Our merger is almost finalized.',
    // 6語以内。「merger」を自然に使った直訳的表現。TOEICで頻出。
    japaneseSentence: '当社の合併はほぼ決定です。',
    // merger＝合併、自然な日本語訳。直訳的で理解しやすい。
    englishReply: "Oh, that's great news. Congratulations!",
    // シンプルな祝福・驚きのリアクション。簡単な単語のみ。
    japaneseReply: 'ああ、それは素晴らしいですね。おめでとうございます！',
    // 英文通りの自然な日本語リアクション。
    scenePrompt:
      '高級レストランで経営者同士がビジネス会食をしており、合併交渉がほぼまとまったことを伝えている。取引先はそれを祝福している。',
    // 食事の場・登場人物・ビジネス合併成立直前の状況。
    senderVoiceInstruction: '誇らしげで落ち着いた調子で',
    receiverVoiceInstruction: '驚きと祝福を込めて明るく',
    incorrectOptions: [
      '金魚と一緒に会社を始めました。',
      // 馬鹿馬鹿しい。mergerと関係ない内容。
      '当社の合併は完全に白紙です。',
      // 真逆の意味（決定ではなく白紙）。
      '新しい製品の発表は明日です。',
      // 合併とは異なる報告内容。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '経理担当',
    senderVoice: 'female',
    receiverRole: '営業担当',
    receiverVoice: 'male',
    englishSentence: 'What is the acquisition cost?',
    // 6語以内の文章で、"acquisition cost"を自然に質問文に組み込んだ。TOEIC頻出語彙であり、直訳で意味が分かる「直訳系」に該当する。
    japaneseSentence: '取得費用はいくらですか？',
    // カタカナ英語を避け、日本語として自然で正しい表現にした。acquisition cost＝取得費用。
    englishReply: 'Oh, it’s $20,000 for this one.',
    // 簡単な数字回答で、難解な熟語を含まず、英単語の意味が分かれば推測しやすい。「$20,000」と答えることで金額に関する質問であることが分かる。
    japaneseReply: 'ああ、これは2万ドルですよ。',
    // 具体的な金額で返答し、質問が費用に関するものであることが分かる日本語訳。
    scenePrompt:
      'オフィスの会議室で経理担当者が営業担当者に新しい機器の購入について尋ねている。経理担当は会社の予算管理のため取得費用を正確に把握しようとしている。机の上には書類やパソコンが並び、資料を見ながら会話している。',
    // 会話の場所、登場人物、目的や背景（予算管理、書類・パソコンの存在など）を具体的に説明している。
    senderVoiceInstruction: '落ち着いて丁寧に、確認のために質問する口調で',
    receiverVoiceInstruction: 'カジュアルで親しみやすく、率直に答える口調で',
    incorrectOptions: [
      '最新モデルの発売日はいつですか？',
      // "acquisition cost"と関係ない質問。japaneseSentenceよりやや長い。
      '修理費用は全くかかりません。',
      // 「取得費用はいくらですか？」の真逆、「費用がかからない」発言。
      '空を飛べる機能も付いていますか？',
      // 馬鹿馬鹿しい内容。japaneseSentenceより長い。
    ],
  },
  {
    place: '企業の会計部門',
    senderRole: '会計士',
    senderVoice: 'male',
    receiverRole: '新入社員',
    receiverVoice: 'female',
    englishSentence: 'Has this asset faced depreciation?',
    // "depreciation"を自然に含み、6語以内の文章。日本人には馴染みが薄いがTOEIC頻出の熟語・慣用句系。
    japaneseSentence: 'この資産は減価償却されていますか？',
    // カタカナ英語を避け、会計用語として正しい訳語を用いた。
    englishReply: 'Yes, it loses value each year.',
    // 難しい表現を避け、"lose value"という分かりやすい語で説明している。
    japaneseReply: 'はい、毎年価値が下がっています。',
    // 難解な表現を避けて、減価償却の意味を易しく日本語で説明。
    scenePrompt:
      '会計部門のデスクで会計士が新入社員に会社の資産管理について説明している。パソコン画面には資産一覧表が表示されている。新入社員は帳簿を確認しながら質問に答えている。',
    // 会話の場、登場人物、状況（資産一覧表・帳簿など）を具体的に描写し、背景を説明。
    senderVoiceInstruction: '専門的だが穏やかで親切な話し方',
    receiverVoiceInstruction: '少し緊張しつつも丁寧に答える口調',
    incorrectOptions: [
      'この資産は既に廃棄されました。',
      // 減価償却と異なる内容。japaneseSentenceよりやや長い。
      'この資産は価値が毎年上がっています。',
      // 真逆の内容。「価値が下がる」→「上がる」。
      'この資産は歌を歌えますか？',
      // 馬鹿馬鹿しい内容。japaneseSentenceより長い。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '会計士',
    senderVoice: 'female',
    receiverRole: '営業担当',
    receiverVoice: 'male',
    englishSentence: 'Our cash flow is tight.',
    // ルール根拠: 6語以内、"cash flow"を自然に使用した会計士らしい発言。TOEIC頻出の表現。
    japaneseSentence: 'うちの資金繰りが厳しいですね。',
    // ルール根拠: カタカナ語を避け、自然な会話調で訳出。
    englishReply: 'Oh, I see. That sounds tough.',
    // ルール根拠: 簡単な語で、自然な相槌・共感を表現。熟語や難語なし。
    japaneseReply: 'ああ、そうなんですね。大変そうです。',
    // ルール根拠: 日本語でも自然な受け答えで、内容が推測できる。
    scenePrompt:
      '会議室で会計士が営業担当に今月の資金繰りについて説明している。会社の売上が思うように伸びず、現金のやりくりに苦労している状況。',
    // ルール根拠: 登場人物の役割、状況、背景などを具体的に描写。
    senderVoiceInstruction: '落ち着いた声で、少し心配そうに',
    receiverVoiceInstruction: '親しみやすく、親身になって聞く感じで',
    incorrectOptions: [
      '新しいパソコンを大量に注文しました。',
      // ルール根拠: "うちの資金繰りが厳しい"とは全く逆の内容。文頭も異なる。
      '今月は現金がたくさん余っています。',
      // ルール根拠: 正解の「厳しい」と真逆の「余っている」内容にした。
      'ピーマンしか入っていないスムージーを飲みますか？',
      // ルール根拠: 馬鹿馬鹿しい内容で、会計士が言いそうにない話題。
    ],
  },
  {
    place: '国際的なビジネス展示会',
    senderRole: '商社のバイヤー',
    senderVoice: 'male',
    receiverRole: '新入社員',
    receiverVoice: 'female',
    englishSentence: 'This is an emerging market.',
    // ルール根拠: 6語以内、"emerging market"を自然に使用。TOEICやビジネス英語で頻出の表現。
    japaneseSentence: 'ここは新興市場なんだよ。',
    // ルール根拠: カタカナ語ではなく、自然な日本語で訳出。
    englishReply: "Oh, really? I didn't know that.",
    // ルール根拠: シンプルな驚きと相槌で、内容を推測しやすい。
    japaneseReply: 'へえ、そうなんですか。知りませんでした。',
    // ルール根拠: 新入社員らしい、素直なリアクションで内容ヒントになる。
    scenePrompt:
      '国際的な展示会のブースで、経験豊富なバイヤーが新入社員に新しいビジネスの可能性について説明している。会場は多国籍の人々で賑わっている。',
    // ルール根拠: 登場人物の動機や場所の様子が具体的に描写されている。
    senderVoiceInstruction: '自信に満ちた落ち着いた口調で',
    receiverVoiceInstruction: '好奇心と驚きを込めて',
    incorrectOptions: [
      '私は毎朝市場で魚を買います。',
      // ルール根拠: 文頭が異なり、意味も異なる。商社バイヤーが言いそうな日常的な話。
      'この市場はとても歴史があります。',
      // ルール根拠: 正解（新興市場）と逆（歴史ある市場）の内容。
      'カバンの中から市場が飛び出しました！',
      // ルール根拠: 馬鹿馬鹿しい内容で、非現実的な発言。
    ],
  },
  {
    place: '証券会社の面談室',
    senderRole: '資産運用アドバイザー',
    senderVoice: 'female',
    receiverRole: '顧客',
    receiverVoice: 'male',
    englishSentence: "Let's review your portfolio today.",
    // ルール根拠: 6語以内、"portfolio"を自然に用いた資産運用の定番表現。
    japaneseSentence: '今日はあなたの資産運用の内容を見直しましょう。',
    // ルール根拠: 自然な日本語で、意味が伝わるよう工夫した。
    englishReply: 'Sure, that sounds good to me.',
    // ルール根拠: シンプルな受け入れの返事で、内容を推測しやすい。
    japaneseReply: 'はい、それでお願いします。',
    // ルール根拠: 受け入れる返事で、状況が伝わりやすい。
    scenePrompt:
      '証券会社の面談室で、資産運用アドバイザーが顧客と定期的な資産運用内容の見直しを提案している。机の上にはポートフォリオの資料が並んでいる。',
    // ルール根拠: シチュエーション、登場人物、背景が具体的に説明されている。
    senderVoiceInstruction: '丁寧で安心感のある口調で',
    receiverVoiceInstruction: '落ち着いたトーンで、納得した様子で',
    incorrectOptions: [
      '来週は遊園地に行きましょう。',
      // ルール根拠: 文頭も内容も異なり、資産運用アドバイザーが言わない発言。
      '今日は資産運用の話はやめましょう。',
      // ルール根拠: 正解（見直す）と真逆（やめる）の内容。
      'ポートフォリオを空に飛ばしてみましょう！',
      // ルール根拠: 馬鹿馬鹿しい発想で非現実的な内容。
    ],
  },
  {
    place: '会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: '新入社員',
    receiverVoice: 'male',
    englishSentence: 'We encourage diversification here.',
    // 6語以内。TOEIC頻出の"diversification"を自然に使った文。
    // 「ここでは多様化を奨励しています」という直訳に近い意味。
    japaneseSentence: '当社では多様化を推進しています。',
    // 正しさと自然さを兼ね備えた訳。カタカナにせず、日本語として自然な表現にしています。
    englishReply: 'Oh, I see. I will remember.',
    // 簡単な単語のみで、相槌と理解の返事。ユーザーが"diversification"の意味を推測できる。
    japaneseReply: 'ああ、分かりました。覚えておきます。',
    // シンプルな日本語で相槌と理解の返答。意味を推察しやすい。
    scenePrompt:
      'オフィスの会議室で、マネージャーが新入社員に会社の方針について説明している場面。多様な考え方や人材を受け入れる姿勢を強調しており、新入社員は真剣に耳を傾けている。',
    // 会話の背景や場所、登場人物の動機、説明されている内容を含めて具体的に記述。
    senderVoiceInstruction: '明るく親しみやすいが落ち着いた話し方',
    receiverVoiceInstruction: '素直で礼儀正しいトーン',
    incorrectOptions: [
      '次回の会議は金曜日に行います。',
      // "当社では"で始まらない。文頭の語が異なる。意義が真逆ではない。
      '多様化は我が社では禁止されています。',
      // 真逆の意味。「推進」と「禁止」で対比。
      '宇宙人だけがこのオフィスで働けます。',
      // 馬鹿馬鹿しい選択肢。現実的ではない内容。
    ],
  },
  {
    place: '証券会社の窓口',
    senderRole: '証券アドバイザー',
    senderVoice: 'male',
    receiverRole: '顧客',
    receiverVoice: 'female',
    englishSentence: 'Do you want more equity options?',
    // 6語以内。TOEIC頻出の"equity"を自然な口語で質問文に。
    // 「もっと株式の選択肢が欲しいですか？」という意味。
    japaneseSentence: 'もっと株式の選択肢が欲しいですか？',
    // 正確かつ自然な日本語訳。カタカナにせず、分かりやすい訳。
    englishReply: 'Yes, please show me some.',
    // シンプルな返答。質問内容を理解した返事。
    japaneseReply: 'はい、いくつか見せてください。',
    // 英文同様、分かりやすく自然な返事。
    scenePrompt:
      '証券会社のカウンターで、証券アドバイザーが顧客に投資商品の説明をしている。顧客は資産運用に興味があり、さまざまな株式に関心を持っている。',
    // 場所、登場人物、会話の状況や動機を具体的に記述。
    senderVoiceInstruction: '落ち着きがあり、丁寧なプロフェッショナルな話し方',
    receiverVoiceInstruction: 'やや緊張しつつも興味津々なトーン',
    incorrectOptions: [
      '本日おすすめの債券をご紹介します。',
      // "もっと"で始まらない。文頭の語が異なる。真逆でも馬鹿馬鹿しくもない。
      '株式の話は一切しない方針です。',
      // 真逆の意味。「選択肢を増やす」と「話をしない」で対比。
      '魚のオプションもお選びいただけます。',
      // 馬鹿馬鹿しい内容。証券会社で魚を勧めるのは現実的でない。
    ],
  },
  {
    place: '法律事務所の相談室',
    senderRole: '弁護士',
    senderVoice: 'female',
    receiverRole: '依頼人',
    receiverVoice: 'male',
    englishSentence: 'This is a significant liability issue.',
    // 6語以内。TOEIC頻出の"liability"を自然に使ったフォーマルな表現。
    // 「これは重大な法的責任の問題です」という意味。
    japaneseSentence: 'これは重大な法的責任の問題です。',
    // 「liability」をカタカナにせず、自然な日本語に。
    englishReply: 'I understand. Thank you for explaining.',
    // 簡単で誤解のない返事。状況を踏まえた内容。
    japaneseReply: '分かりました。ご説明ありがとうございます。',
    // 丁寧で自然な日本語の返事。状況の理解が伝わる。
    scenePrompt:
      '法律事務所の個室で、弁護士が依頼人に契約書のリスクについて説明している。依頼人は重要な判断を迫られていて、真剣な表情で弁護士の話を聞いている。',
    // 場所や背景、やりとりの状況を詳しく説明。
    senderVoiceInstruction: '冷静で説得力のある落ち着いた話し方',
    receiverVoiceInstruction: '少し緊張しつつも丁寧なトーン',
    incorrectOptions: [
      'この件は全く問題ありません。',
      // "これは"で始まらない。真逆の意味。「重大な問題」と「全く問題ない」で対比。
      '先週の責任者は宇宙人でした。',
      // 馬鹿馬鹿しい内容。現実味がない。
      '責任の所在は特に重要ではありません。',
      // 逆の意味。「重大な問題」と「重要ではない」で対比。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence: "Let's aim for a productivity boost.",
    // ルール: 6語以内の正確な文章。「productivity boost」を自然に含め、指示・励ましのトーン。
    japaneseSentence: '生産性の向上を目指しましょう。',
    // ルール: 直訳ではなく自然な訳。「productivity boost」は「生産性の向上」と訳出。
    englishReply: "Sure, I'll work on that.",
    // ルール: 簡単な単語のみ。自然な返答で、内容を推測しやすい。
    japaneseReply: 'わかりました、それに取り組みます。',
    // ルール: 直訳でわかる内容で、推測のヒントとなる。
    scenePrompt:
      'オフィスの会議室で、マネージャーが部下たちに今後の業務効率化について話している。効率アップをチーム全体で目指す雰囲気。',
    // ルール: 場所・登場人物・シチュエーション・背景を明確に説明。
    senderVoiceInstruction: '前向きでリーダーシップのある声で',
    receiverVoiceInstruction: 'やる気のある元気な声で',
    incorrectOptions: [
      '新しい机を全員分購入しましょう。', // ルール: 文字数バランス、senderRoleが言いそうな自然な誤答。
      '効率を下げることを目指しましょう。', // ルール: 正解の真逆の意味。
      '会議室の椅子を全部空に飛ばしましょう。', // ルール: 馬鹿馬鹿しい内容、文頭もバラバラ。
    ],
  },
  {
    place: 'IT企業のデスク',
    senderRole: 'エンジニア',
    senderVoice: 'male',
    receiverRole: 'プロジェクトマネージャー',
    receiverVoice: 'female',
    englishSentence: 'Does this system allow scalability?',
    // ルール: 6語以内の疑問文。「scalability」を自然に含む。IT現場で実際にありそうな質問。
    japaneseSentence: 'このシステムは拡張性がありますか？',
    // ルール: カタカナ英語を避け、自然な日本語訳に。
    englishReply: 'Yes, it can be expanded easily.',
    // ルール: 易しい単語のみで構成。内容が推測できるヒントとなる返答。
    japaneseReply: 'はい、簡単に拡張できますよ。',
    // ルール: 内容が推測できる自然な日本語訳。
    scenePrompt:
      'IT企業のエンジニアが、自社システムについてプロジェクトマネージャーに拡張性の有無を確認している場面。新しい機能追加の可能性を話し合っている。',
    // ルール: 具体的な場所・登場人物・状況・背景を記載。
    senderVoiceInstruction: '丁寧で確認するような落ち着いた声で',
    receiverVoiceInstruction: '自信を持って明るく答える声で',
    incorrectOptions: [
      'このシステムは色が変わりますか？', // ルール: 文字数バランス、内容的にも誤答。
      'このシステムは拡張性がありません。', // ルール: 真逆の意味。
      '恐竜も使えるシステムですか？', // ルール: 馬鹿馬鹿しい発想、文頭バラバラ。
    ],
  },
  {
    place: '大手コンサル会社のプロジェクトルーム',
    senderRole: 'コンサルタント',
    senderVoice: 'female',
    receiverRole: 'クライアント担当者',
    receiverVoice: 'male',
    englishSentence: "We're entering the implementation phase now.",
    // ルール: 6語以内、熟語「implementation phase」を自然に使用。報告・説明のトーン。
    japaneseSentence: 'いよいよ実施段階に入ります。',
    // ルール: 日本語にないカタカナ語を避けつつ自然な表現で翻訳。
    englishReply: "I see, it's finally starting.",
    // ルール: 簡単な単語のみ。内容が推測できる返答。
    japaneseReply: 'なるほど、いよいよ始まるんですね。',
    // ルール: 内容の推測を助けるヒントとなる日本語訳。
    scenePrompt:
      'コンサルタントがクライアントに対し、長期プロジェクトの準備期間が終わり、いよいよ実行段階に入ることを伝えている。期待感と緊張感が混じる場面。',
    // ルール: シチュエーション・雰囲気を明確に描写。
    senderVoiceInstruction: '落ち着いた自信のある声で丁寧に',
    receiverVoiceInstruction: '期待と少し緊張した声で',
    incorrectOptions: [
      '今日は準備段階に戻ります。', // ルール: 文字数バランス、誤答。
      'これから計画をやめます。', // ルール: 意味が真逆。
      '今から全員で逆立ちしましょう。', // ルール: 馬鹿馬鹿しい内容、文頭バラバラ。
    ],
  },
  {
    place: '会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'male',
    receiverRole: 'エンジニア',
    receiverVoice: 'female',
    englishSentence: 'We need a feasibility study.',
    // コメント: 6語以内の正確な英文で、「feasibility study」というTOEIC頻出の熟語を自然に入れました。直訳系です。
    japaneseSentence: '事業の実現可能性調査が必要です。',
    // コメント: 英語の直訳ではなく、自然な日本語訳を意識しています。カタカナ語を避けています。
    englishReply: 'Okay, I will prepare the report.',
    // コメント: 熟語や難解な表現を避け、簡単で分かりやすい返答です。
    japaneseReply: 'わかりました、報告書を準備します。',
    // コメント: 英語Replyの内容を自然な日本語で表現しています。
    scenePrompt:
      '新規プロジェクトの初期段階で、プロジェクトマネージャーがエンジニアに実現可能性調査の必要性を伝えている。会議室では数名のチームメンバーが資料を見ながらミーティングを進めている。',
    // コメント: 場面の詳細や背景、登場人物の動機と場所の様子を言語化しています。
    senderVoiceInstruction: '落ち着いていて、指示を出すように丁寧に',
    receiverVoiceInstruction: '明るく前向きなトーンで',
    incorrectOptions: [
      '今夜の会議はピザパーティーにしましょう。',
      // コメント: 馬鹿馬鹿しい文。文頭が「今夜」なのでjapaneseSentenceと異なります。
      'この計画の実現は不可能です。',
      // コメント: 正解文と真逆の意味。「この計画の実現は不可能」と断言しています。文頭も異なります。
      '最新の機材を早急に手配してください。',
      // コメント: 正解文と異なる内容で、別の依頼文。文頭も異なります。
    ],
  },
  {
    place: 'オフィス',
    senderRole: '経理担当',
    senderVoice: 'female',
    receiverRole: '部門マネージャー',
    receiverVoice: 'male',
    englishSentence: "Let's review the operational cost.",
    // コメント: 6語以内で「operational cost」を使った自然な依頼文です。熟語系。
    japaneseSentence: '運営コストを見直しましょう。',
    // コメント: カタカナ語を避けて自然な日本語にしています。
    englishReply: 'Sure, I have the numbers ready.',
    // コメント: 簡単で内容が推測しやすい返答です。熟語なし。
    japaneseReply: 'はい、数値はすでに用意しています。',
    // コメント: 英語Replyの内容を自然な日本語で表現しています。
    scenePrompt:
      'オフィスで経理担当者が部門マネージャーにコストの見直しを提案している。書類やパソコンが並ぶデスクで、両者が資料を確認しながら話している。',
    // コメント: 場面の詳細、背景、場所の様子、登場人物の動機を具体的に記載しています。
    senderVoiceInstruction: '控えめで丁寧なトーンで',
    receiverVoiceInstruction: '落ち着いて自信のある声で',
    incorrectOptions: [
      '全ての経費を二倍に増やしましょう。',
      // コメント: 馬鹿馬鹿しい発想。文頭は「全て」。
      '今のコストで十分だと思います。',
      // コメント: 正解文と真逆の意見。文頭は「今」。
      '年度末までに会議室を増設します。',
      // コメント: 正解文と異なる内容。文頭は「年度末」。
    ],
  },
  {
    place: '経営戦略会議',
    senderRole: 'CEO',
    senderVoice: 'male',
    receiverRole: '役員',
    receiverVoice: 'female',
    englishSentence: 'We must define our long-term vision.',
    // コメント: 6語以内で「long-term vision」を使った自然なCEOの発言。熟語系。
    japaneseSentence: '私たちの長期的なビジョンを明確にしましょう。',
    // コメント: カタカナ語を避け、自然な日本語訳です。
    englishReply: "Yes, that's very important for growth.",
    // コメント: 簡単な英語で、内容が推測しやすい返答です。
    japaneseReply: 'はい、それは成長のためにとても大切です。',
    // コメント: 英語Replyの内容を自然な日本語で表現しています。
    scenePrompt:
      '経営戦略会議でCEOが今後の企業方針について議論を促している。会議室には複数の役員が真剣な表情で議事録やプレゼン資料を見ている。',
    // コメント: 場面の詳細、背景、場所の様子、登場人物の動機を具体的に記載しています。
    senderVoiceInstruction: '自信に満ちたリーダーらしいトーン',
    receiverVoiceInstruction: '敬意を込めて前向きに',
    incorrectOptions: [
      '明日から会社名を動物園に変えましょう。',
      // コメント: 馬鹿馬鹿しい発想。文頭は「明日」。
      '短期目標だけに集中しましょう。',
      // コメント: 正解文と真逆の意見。文頭は「短期」。
      '来月の新製品発表会に注力しましょう。',
      // コメント: 正解文と異なる内容。文頭は「来月」。
    ],
  },
];

export default problemData;
