import { SeedProblemData } from '../src/types/problem';

/**
 * 問題データ 10
 * Generated by GPT API (6 problems)
 */
const problemData: SeedProblemData[] = [
  {
    place: '会社の会議室',
    senderRole: 'マネージャー',
    senderVoice: 'male',
    receiverRole: '社員',
    receiverVoice: 'female',
    englishSentence: 'Is this solution cost-effective enough?',
    // 単語「cost-effective」を含み、8語以内の疑問文で自然な会話として成立しています。
    japaneseSentence: 'この解決策は十分にコスト効率が良いですか？',
    // 「cost-effective」の意味が分かれば直訳できる文です。条件の「直訳系」20%に該当します。
    englishReply: 'Yes, it saves us a lot of money.',
    // 単純な肯定文で直訳できる簡単な文章です。
    japaneseReply: 'はい、それは私たちの費用を大きく節約します。',
    // 直訳しやすい簡潔な返答です。
    scenePrompt:
      '社内会議室で、マネージャーが新しい業務プロセスについて社員に意見を求めている。コスト削減が重要な話題となっている。',
    // 会話の背景や場所、登場人物の動機（コスト削減を重視している状況）を説明しています。
    senderVoiceInstruction: '落ち着いたが少し真剣なトーンで質問する',
    receiverVoiceInstruction: '明るく自信のある声で答える',
    incorrectOptions: [
      '新しい方法は全く費用がかかりません。',
      // 「コスト効率が良い」の真逆で「全く費用がかからない」と極端な意味です。
      'この提案はとても危険なのでおすすめしません。',
      // 「危険」や「おすすめしない」は話題から大きく外れています。
      'ゴリラの着ぐるみでコスト削減しましょう！',
      // 馬鹿馬鹿しい発想で、非現実的です。
    ],
  },
  {
    place: '法律事務所のオフィス',
    senderRole: '弁護士',
    senderVoice: 'female',
    receiverRole: 'クライアント',
    receiverVoice: 'male',
    englishSentence: 'We require full disclosure from you.',
    // 「disclosure」を含み、8語以内で完結したフォーマルな要求文です。熟語・慣用句系（80%）に該当します。
    japaneseSentence: 'あなたからの完全な情報開示が必要です。',
    // 「disclosure」を直訳しづらい日本語で自然な表現にしています。
    englishReply: 'Of course, I will tell you everything.',
    // 意味が分かりやすい簡単な文で、応答として自然です。
    japaneseReply: 'もちろん、全てお話しします。',
    // シンプルで日本語としても自然な返答です。
    scenePrompt:
      '法律相談のためにクライアントが弁護士事務所を訪れている。案件を正確に進めるため、弁護士は詳細な情報開示を求めている。',
    // クライアントが相談に来ていて、弁護士が正確な情報を求めている状況を説明しています。
    senderVoiceInstruction: '丁寧で誠実だが、少し厳格な口調で',
    receiverVoiceInstruction: '真面目で誠意あるトーンで',
    incorrectOptions: [
      '私たちはあなたの過去は気にしません。',
      // 「情報開示が必要」と真逆の意味です。
      '明日のお昼に一緒にランチどうですか？',
      // 法律相談の場面にそぐわない雑談です。
      'バナナを三本持参してくださいね！',
      // 馬鹿馬鹿しい指示で、現実的ではありません。
    ],
  },
  {
    place: '証券会社のカウンター',
    senderRole: '証券アドバイザー',
    senderVoice: 'male',
    receiverRole: '顧客',
    receiverVoice: 'female',
    englishSentence: 'Are you eligible for a dividend now?',
    // 「dividend」を含み、8語以内で疑問文の形式です。日本人が苦手な熟語・慣用句系です。
    japaneseSentence: '今、あなたは配当金の受け取り資格がありますか？',
    // 「eligible for a dividend」の直訳が難しいが自然な日本語訳です。
    englishReply: 'Yes, I bought shares last month.',
    // 質問に対し、簡単な単語で答えています。
    japaneseReply: 'はい、先月株を買いました。',
    // 直訳しやすい日本語で簡潔な返答にしています。
    scenePrompt:
      '証券会社のカウンターで、顧客が自分の投資状況についてアドバイスを受けている。最近株を購入した顧客が配当金の受け取りについて確認している。',
    // 証券会社の窓口でのやりとりの背景や流れを説明しています。
    senderVoiceInstruction: '親切で丁寧な説明口調で',
    receiverVoiceInstruction: '少し不安そうだが丁寧に答える',
    incorrectOptions: [
      'あなたは配当金を受け取る資格がありません。',
      // 「受け取り資格があるか」という質問の真逆の内容です。
      '株価の予想は占いで決まります。',
      // 馬鹿馬鹿しく、現実的ではありません。
      '新しいアカウントが今すぐ作成できます。',
      // 話題と全く関係のない案内です。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: '社員',
    receiverVoice: 'male',
    englishSentence: 'Have you done the due diligence?',
    // コメント:8語以内で "due diligence" を自然に使用した疑問文。「due diligence」は日本人が苦手な熟語。
    japaneseSentence: 'デューデリジェンスは済ませましたか？',
    // コメント:"due diligence"の意味を直訳せずにカタカナ表記で自然な日本語訳にしている。
    englishReply: 'Yes, I checked all the documents.',
    // コメント:熟語や難しい単語を使わず、理解しやすい簡単な返答。
    japaneseReply: 'はい、すべての書類を確認しました。',
    // コメント:英語の返答を自然な日本語に訳している。
    scenePrompt:
      '新しい取引先との契約前に、マネージャーが社員にデューデリジェンス（事前調査）の進捗を確認している。社員は書類をチェックし終えたばかりで、少し緊張しつつも自信を持って返答する。会議室には書類やノートパソコンが並んでいる。',
    // コメント:場所・登場人物・動機・状況を具体的に説明し、文脈を明確にしている。
    senderVoiceInstruction: '落ち着いていて、ビジネスライクな話し方',
    receiverVoiceInstruction: '丁寧で少し緊張した口調',
    incorrectOptions: [
      '本日中に全員を集めてください。',
      // コメント:8文字で、japaneseSentence（14文字）より短いが、全て短い文ばかりにはなっていない。他の文と文頭が違う。
      '次の会議は明日の午後三時です。',
      // コメント:14文字でjapaneseSentenceと同等の長さ。意味も異なり、文頭も違う。
      '空飛ぶ書類で契約を結びましょう！',
      // コメント:馬鹿馬鹿しい発想で始まりも他とかぶっていない。
    ],
  },
  {
    place: '会社の経理部',
    senderRole: '経理担当',
    senderVoice: 'male',
    receiverRole: '部長',
    receiverVoice: 'female',
    englishSentence: 'Our monthly expenditure is increasing again.',
    // コメント:8語以内で "expenditure" を自然に使用した報告文。「expenditure」はTOEIC頻出のやや難語。
    japaneseSentence: '今月の支出がまた増えています。',
    // コメント:「expenditure」を「支出」と日本語で自然な訳にしている。
    englishReply: 'Oh, I see. We should review the budget.',
    // コメント:熟語を避け、簡単で理解しやすい返答。
    japaneseReply: 'そうですか。予算を見直しましょう。',
    // コメント:自然な日本語訳。
    scenePrompt:
      '経理担当が月次の支出報告を部長に伝え、部長が予算管理の重要性について考え始めている。オフィスにはパソコンや会計書類が並ぶ。',
    // コメント:場面や背景、登場人物の意図を具体的に説明している。
    senderVoiceInstruction: '落ち着いた口調で事務的に',
    receiverVoiceInstruction: '柔らかくも真剣なトーンで',
    incorrectOptions: [
      '新しい椅子が届きましたよ。',
      // コメント:12文字で、話者の役割にも合い文頭も被っていない。
      '支出が減っていて安心しました。',
      // コメント:16文字で、japaneseSentenceと真逆の意味。文頭も違う。
      '巨大なタコが経費を食べてしまいました！',
      // コメント:馬鹿馬鹿しい内容。文頭も他と異なる。
    ],
  },
  {
    place: '法律事務所の応接室',
    senderRole: '弁護士',
    senderVoice: 'female',
    receiverRole: '依頼人',
    receiverVoice: 'male',
    englishSentence: 'I must uphold my fiduciary duty.',
    // コメント:8語以内で "fiduciary duty" を自然に使用した宣言文。「fiduciary duty」は日本人に馴染みが薄い法律用語。
    japaneseSentence: '私は受託者責任を守らなければなりません。',
    // コメント:"fiduciary duty"を自然な日本語で説明的に訳している。
    englishReply: 'Thank you. I trust your judgment.',
    // コメント:簡単な単語で相手を信頼する定型表現。難語や熟語なし。
    japaneseReply: 'ありがとうございます。先生を信頼しています。',
    // コメント:内容を自然な日本語で表現している。
    scenePrompt:
      '法律相談の場で、弁護士が自分の受託者責任について誠実に伝えている。依頼人は安心した表情で弁護士の説明を聞いている。応接室には書類や法律書が並べられている。',
    // コメント:場所・状況・登場人物の動機を具体的に描写している。
    senderVoiceInstruction: '誠実で信頼感のある落ち着いた話し方',
    receiverVoiceInstruction: '感謝と安心感が伝わる優しいトーン',
    incorrectOptions: [
      '明日の会議は三時からです。',
      // コメント:13文字で文頭が他と被っていない。役割に合った発話。
      '私は責任を放棄しようと思います。',
      // コメント:17文字でjapaneseSentenceと真逆の意味。文頭も異なる。
      '宇宙人のために法律を作ります！',
      // コメント:馬鹿馬鹿しい発想で、他と文頭が違う。
    ],
  },
];

export default problemData;
