import { SeedProblemData } from '../src/types/problem';

// - incorrectOptions の要素たちは japaneseSentence とほぼ同じ文字数で生成すること
// - incorrectOptionsの内容は、依頼や質問や提案や意見や情報共有のような、話しかける形式のセリフであること。japaneseSentenceとは無関係なセリフであること。
// - 日本語の文について。「500円」などの数値は「五百円」と表記すること

const problems: SeedProblemData[] = [
  {
    englishSentence: 'I’ll keep you posted on the updates.',
    japaneseSentence: '進捗があればすぐに知らせるよ。', // 15文字
    japaneseReply: 'うん、助かるよ。',
    englishReply: 'Great, I appreciate that.',
    incorrectOptions: [
      '昨日の宿題は難しかったのかな？',
      '週末はどこか出かけるつもり？',
      '今日は早めに帰る予定なの？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '同僚',
    receiverVoice: 'female',
    receiverRole: '同僚',
    place: 'オフィス',
  },
  {
    englishSentence: 'Let’s grab a bite before the meeting.',
    japaneseSentence: '会議の前に軽く食べようよ。', // 13文字
    japaneseReply: 'いいね、小腹が空いてたんだ。',
    englishReply: 'Sure, I was getting hungry.',
    incorrectOptions: [
      '昨日の試合は盛り上がったのかな？',
      '今日は映画を観に行くのかな？',
      '週末は誰かと会う予定あるの？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '同僚',
    receiverVoice: 'male',
    receiverRole: '同僚',
    place: '会社近くのカフェ',
  },
  {
    englishSentence: 'Don’t jump the gun on this project.',
    japaneseSentence: 'このプロジェクトを早まって進めないで。', // 17文字
    japaneseReply: 'わかった、落ち着いて進めるよ。',
    englishReply: 'Got it, I’ll take it slow.',
    incorrectOptions: [
      '昨日の本は読み終えたのかな？',
      '今日は電車で帰るつもりなの？',
      '週末は買い物に行ったのかな？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '上司',
    receiverVoice: 'female',
    receiverRole: '部下',
    place: '会議室',
  },
  {
    englishSentence: 'This new app is a game changer.',
    japaneseSentence: 'この新しいアプリは革命的だよ。', // 13文字
    japaneseReply: '本当に便利そうだね。',
    englishReply: 'Yeah, it looks really useful.',
    incorrectOptions: [
      '昨日の夕飯は何を食べたのかな？',
      '今日は誰かに会ったのかな？',
      '週末は外で過ごすのかな？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '友達',
    receiverVoice: 'male',
    receiverRole: '友達',
    place: 'カフェ',
  },
  {
    englishSentence: 'She’s keeping me in the loop.',
    japaneseSentence: '彼女は私に情報を共有してくれている。', // 18文字
    japaneseReply: 'それはありがたいね。',
    englishReply: 'That’s really helpful.',
    incorrectOptions: [
      '昨日のイベントは楽しかったの？',
      '週末はどこか行ったのかな？',
      '今日は雨が降っていたのかな？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '同僚',
    receiverVoice: 'female',
    receiverRole: '同僚',
    place: 'オフィス',
  },
  {
    englishSentence: 'We’re on the same page now.',
    japaneseSentence: 'これでお互い理解が一致したね。', // 15文字
    japaneseReply: 'うん、スムーズに進められるね。',
    englishReply: 'Exactly, we can move forward.',
    incorrectOptions: [
      '昨日の試合はどうだったの？',
      '週末は買い物に行ったのかな？',
      '今日は新しい服を着ているの？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '同僚',
    receiverVoice: 'male',
    receiverRole: '同僚',
    place: 'プロジェクトルーム',
  },
  {
    englishSentence: 'He always thinks outside the box.',
    japaneseSentence: '彼はいつも型にはまらない発想をするね。', // 18文字
    japaneseReply: 'そういう人は貴重だよね。',
    englishReply: 'Yeah, he’s really creative.',
    incorrectOptions: [
      '昨日の映画は楽しかったかな？',
      '週末は友達と会ったのかな？',
      '今日はどこに出かけるのかな？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '友達',
    receiverVoice: 'female',
    receiverRole: '友達',
    place: '図書館',
  },
  {
    englishSentence: 'Let’s touch base tomorrow morning.',
    japaneseSentence: '明日の朝に改めて打ち合わせしよう。', // 16文字
    japaneseReply: 'うん、忘れないようにしよう。',
    englishReply: 'Alright, I’ll remember that.',
    incorrectOptions: [
      '昨日の宿題は終わらせたの？',
      '週末はどこで過ごしたのかな？',
      '今日は外で食事したのかな？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '上司',
    receiverVoice: 'male',
    receiverRole: '部下',
    place: 'オフィス',
  },
  {
    englishSentence: 'That dress costs an arm and a leg.',
    japaneseSentence: 'そのドレスはすごく高いんだよ。', // 14文字
    japaneseReply: '本当に手が出せない値段だね。',
    englishReply: 'Yeah, it’s way too expensive.',
    incorrectOptions: [
      '昨日の天気はどうだったの？',
      '今日は誰かに会ったのかな？',
      '週末はどこか出かけたのかな？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '友達',
    receiverVoice: 'female',
    receiverRole: '友達',
    place: 'ショッピングモール',
  },
  {
    englishSentence: 'He threw in the towel after losing twice.',
    japaneseSentence: '二度負けて彼は諦めてしまったんだ。', // 17文字
    japaneseReply: 'まあ、気持ちはわからなくもないね。',
    englishReply: 'Yeah, I can’t blame him.',
    incorrectOptions: [
      '昨日のイベントは盛り上がったのかな？',
      '今日は雨が降っていたのかな？',
      '週末は何をして過ごしたのかな？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '友達',
    receiverVoice: 'male',
    receiverRole: '友達',
    place: '公園',
  },
  {
    englishSentence: 'He bent over backwards to help me.',
    japaneseSentence: '彼は本当に親身になって助けてくれたよ。', // 18文字
    japaneseReply: 'いい友達を持ったね。',
    englishReply: 'Yeah, I’m lucky to have him.',
    incorrectOptions: [
      '昨日のニュースは見たのかな？',
      '週末は外で過ごしたのかな？',
      '今日は宿題をやったのかな？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '友達',
    receiverVoice: 'female',
    receiverRole: '友達',
    place: '自宅',
  },
  {
    englishSentence: 'We need to get our ducks in a row.',
    japaneseSentence: 'きちんと準備を整える必要があるね。', // 16文字
    japaneseReply: 'そうだね、計画的に進めよう。',
    englishReply: 'Right, let’s stay organized.',
    incorrectOptions: [
      '昨日の映画は観に行ったのかな？',
      '今日は新しい服を買ったの？',
      '週末は誰かと会ったのかな？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '同僚',
    receiverVoice: 'male',
    receiverRole: '同僚',
    place: '会議室',
  },
  {
    englishSentence: 'He really dropped the ball this time.',
    japaneseSentence: '彼は今回本当に失敗してしまったんだ。', // 17文字
    japaneseReply: 'ああ、残念だったね。',
    englishReply: 'Yeah, that’s unfortunate.',
    incorrectOptions: [
      '昨日の試合は勝てたのかな？',
      '今日は遅くまで起きていたの？',
      '週末は買い物に行ったのかな？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '上司',
    receiverVoice: 'female',
    receiverRole: '部下',
    place: 'オフィス',
  },
  {
    englishSentence: 'This task is right up your alley.',
    japaneseSentence: 'この仕事は君にぴったりだよ。', // 14文字
    japaneseReply: 'うん、やってみるよ。',
    englishReply: 'Sure, I’ll give it a try.',
    incorrectOptions: [
      '昨日の本は読み終わったのかな？',
      '週末は出かける予定あるの？',
      '今日は早めに帰るのかな？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '同僚',
    receiverVoice: 'male',
    receiverRole: '同僚',
    place: 'オフィス',
  },
  {
    englishSentence: 'She’s on cloud nine after the promotion.',
    japaneseSentence: '昇進して彼女はとても幸せそうだよ。', // 16文字
    japaneseReply: '本当に努力が報われたんだね。',
    englishReply: 'She truly earned it.',
    incorrectOptions: [
      '昨日のイベントは楽しかったのかな？',
      '週末は誰かと会ったのかな？',
      '今日は外で食事したのかな？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '友達',
    receiverVoice: 'female',
    receiverRole: '友達',
    place: 'カフェ',
  },
  {
    englishSentence: 'That rule is set in stone.',
    japaneseSentence: 'その規則は絶対に変えられないよ。', // 15文字
    japaneseReply: 'そうか、仕方ないね。',
    englishReply: 'Alright, I’ll follow it.',
    incorrectOptions: [
      '昨日の天気はどうだったの？',
      '今日は新しい靴を買ったの？',
      '週末は友達と会ったのかな？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '先生',
    receiverVoice: 'male',
    receiverRole: '生徒',
    place: '教室',
  },
  {
    englishSentence: 'Let’s call it quits for today.',
    japaneseSentence: '今日はここまでにしようよ。', // 13文字
    japaneseReply: 'そうだね、疲れてきたよ。',
    englishReply: 'Yeah, I’m getting tired.',
    incorrectOptions: [
      '昨日の映画は面白かったの？',
      '今日は雨が降っていたのかな？',
      '週末は買い物に行ったのかな？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '友達',
    receiverVoice: 'female',
    receiverRole: '友達',
    place: '自宅',
  },
  {
    englishSentence: 'He’s skating on thin ice at work.',
    japaneseSentence: '彼は職場で危うい立場にいるんだ。', // 16文字
    japaneseReply: 'うわ、それは心配だね。',
    englishReply: 'Yeah, that’s risky.',
    incorrectOptions: [
      '昨日の試合は勝ったのかな？',
      '今日は誰かに会ったのかな？',
      '週末は何をして過ごしたの？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '同僚',
    receiverVoice: 'male',
    receiverRole: '同僚',
    place: 'オフィス',
  },
  {
    englishSentence: 'Let’s break the ice with a joke.',
    japaneseSentence: '冗談で場を和ませようよ。', // 13文字
    japaneseReply: 'うん、それで楽になるね。',
    englishReply: 'Sure, that’ll ease the mood.',
    incorrectOptions: [
      '昨日の宿題は終わったのかな？',
      '今日は外で夕飯を食べたの？',
      '週末は友達と遊んだのかな？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '友達',
    receiverVoice: 'female',
    receiverRole: '友達',
    place: '飲み会',
  },
  {
    englishSentence: 'She’s biting off more than she can chew.',
    japaneseSentence: '彼女は無理なことを引き受けすぎてるよ。', // 18文字
    japaneseReply: '本当に心配になってきたよ。',
    englishReply: 'Yeah, I’m worried too.',
    incorrectOptions: [
      '昨日の映画は面白かったかな？',
      '今日は雨が降っていたの？',
      '週末はどこに行ったのかな？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '同僚',
    receiverVoice: 'male',
    receiverRole: '同僚',
    place: 'オフィス',
  },
  {
    englishSentence: 'He’s always beating around the bush.',
    japaneseSentence: '彼はいつも遠回しな言い方をするね。', // 16文字
    japaneseReply: 'はっきり言ってほしいよね。',
    englishReply: 'Yeah, I’d prefer straight talk.',
    incorrectOptions: [
      '昨日の本は全部読めたのかな？',
      '今日は早めに帰るのかな？',
      '週末は誰かに会ったのかな？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '友達',
    receiverVoice: 'female',
    receiverRole: '友達',
    place: '公園',
  },
  {
    englishSentence: 'She hit the books for the exam.',
    japaneseSentence: '彼女は試験勉強に本気で取り組んだよ。', // 17文字
    japaneseReply: 'その努力は報われるはずだよ。',
    englishReply: 'Her effort will pay off.',
    incorrectOptions: [
      '昨日の映画は楽しかったの？',
      '今日は外で食事したのかな？',
      '週末はどこかに行ったの？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '友達',
    receiverVoice: 'male',
    receiverRole: '友達',
    place: '図書館',
  },
  {
    englishSentence: 'We’re back to square one again.',
    japaneseSentence: 'また振り出しに戻ってしまったね。', // 15文字
    japaneseReply: '仕方ない、やり直そう。',
    englishReply: 'Alright, let’s restart.',
    incorrectOptions: [
      '昨日の試合は勝てたのかな？',
      '今日は宿題をやったのかな？',
      '週末は誰かに会ったのかな？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '同僚',
    receiverVoice: 'female',
    receiverRole: '同僚',
    place: 'オフィス',
  },
  {
    englishSentence: 'She turned a blind eye to the mistake.',
    japaneseSentence: '彼女はそのミスを見て見ぬふりをしたよ。', // 18文字
    japaneseReply: 'まあ、穏便に済ませたんだね。',
    englishReply: 'Yeah, she let it slide.',
    incorrectOptions: [
      '昨日の天気はどうだったの？',
      '今日は何を食べたのかな？',
      '週末は誰かと出かけたの？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '上司',
    receiverVoice: 'male',
    receiverRole: '部下',
    place: '会議室',
  },
  {
    englishSentence: 'He went the extra mile for the client.',
    japaneseSentence: '彼は顧客のために一段と頑張ったんだよ。', // 17文字
    japaneseReply: '立派だね、信頼されるよ。',
    englishReply: 'That’s why he’s trusted.',
    incorrectOptions: [
      '昨日の宿題は難しかったのかな？',
      '今日は誰と会ったのかな？',
      '週末は映画を観たのかな？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '同僚',
    receiverVoice: 'female',
    receiverRole: '同僚',
    place: 'オフィス',
  },
  {
    englishSentence: 'This idea is out of left field.',
    japaneseSentence: 'このアイデアは全く予想外だね。', // 14文字
    japaneseReply: 'でも面白い発想だよ。',
    englishReply: 'True, it’s quite creative.',
    incorrectOptions: [
      '昨日のニュースは見たのかな？',
      '今日は遅くまで起きてたの？',
      '週末はどこに出かけたの？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '友達',
    receiverVoice: 'male',
    receiverRole: '友達',
    place: 'カフェ',
  },
  {
    englishSentence: 'He cut corners to finish quickly.',
    japaneseSentence: '彼は急いで手を抜いて仕上げたよ。', // 15文字
    japaneseReply: '品質が心配になるね。',
    englishReply: 'Yeah, the quality may suffer.',
    incorrectOptions: [
      '昨日の映画はどうだったの？',
      '今日は新しい服を買ったの？',
      '週末は誰と過ごしたの？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '同僚',
    receiverVoice: 'female',
    receiverRole: '同僚',
    place: '会議室',
  },
  {
    englishSentence: 'She passed the exam with flying colors.',
    japaneseSentence: '彼女は試験に見事に合格したんだよ。', // 16文字
    japaneseReply: 'すごいね、本当に頑張ったね。',
    englishReply: 'Yeah, she did amazing.',
    incorrectOptions: [
      '昨日の天気はどうだった？',
      '今日はどこで食事したの？',
      '週末は誰かに会ったの？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '友達',
    receiverVoice: 'male',
    receiverRole: '友達',
    place: '駅前',
  },
  {
    englishSentence: 'He finally saw the light.',
    japaneseSentence: '彼はようやく理解したんだよ。', // 13文字
    japaneseReply: 'それはよかったね。',
    englishReply: 'Glad he got it now.',
    incorrectOptions: [
      '昨日の本は面白かったの？',
      '今日は何を食べたのかな？',
      '週末は買い物に行ったの？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '先生',
    receiverVoice: 'female',
    receiverRole: '生徒',
    place: '教室',
  },
  {
    englishSentence: 'We’ll cross that bridge when we come to it.',
    japaneseSentence: 'その問題は起きたときに考えようよ。', // 17文字
    japaneseReply: 'そうだね、今は気にしすぎないでおこう。',
    englishReply: 'Yeah, no need to worry now.',
    incorrectOptions: [
      '昨日の試合はどうだったの？',
      '今日は外で夕飯を食べたの？',
      '週末は誰かと遊んだのかな？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '友達',
    receiverVoice: 'male',
    receiverRole: '友達',
    place: '公園',
  },
];

export default problems;
