import { SeedProblemData } from '../src/types/problem';

const problemData: SeedProblemData[] = [
  {
    place: '町のクリニック受付',
    senderRole: '受付係',
    senderVoice: 'female',
    receiverRole: '患者',
    receiverVoice: 'male',
    englishSentence: 'We’re a bit short-staffed today—could I slot you in at noon instead?',
    japaneseSentence: '本日は人手不足で、正午に変更でもよろしいですか？',
    englishReply: 'No problem. Noon works for me. Do I need to bring anything?',
    japaneseReply: '大丈夫です。正午で構いません。何か持ち物はありますか？',
    scenePrompt:
      '小さな町の内科クリニックの受付前。午前中に予約が集中しており、受付係は人員不足で時間変更の協力をお願いしている。患者は近所に住む常連で、落ち着いた雰囲気の待合室には観葉植物と雑誌が置かれている。',
    senderVoiceInstruction: '丁寧で申し訳なさをにじませる落ち着いた口調で、迅速に事情を説明する。',
    receiverVoiceInstruction: '落ち着いた口調で理解を示し、穏やかに確認する。',
    incorrectOptions: [
      'ただちに診察へご案内が可能でございます。本日中。',
      '診察は月の満ち欠け次第で決めます。宇宙基準です。',
      '夕方に空きがなく、本日は受付終了です。申し訳なし。',
    ],
  },
  {
    place: 'カフェのバックヤード',
    senderRole: '店長',
    senderVoice: 'male',
    receiverRole: 'コーヒー豆の卸担当',
    receiverVoice: 'female',
    englishSentence: 'Our house blend is back-ordered; could you expedite a partial shipment?',
    japaneseSentence: '看板ブレンドが入荷待ちで、部分出荷を早められますか？',
    englishReply: 'I can rush a half pallet today and the rest tomorrow. Does that help?',
    japaneseReply: '本日半パレット、明日残りを急送できます。お役に立ちますか？',
    scenePrompt:
      '昼どきの繁忙前、カフェの在庫棚を確認しながら店長が卸業者に電話。看板ブレンドの在庫が切れかけており、部分出荷の前倒しを交渉している。店内は挽きたての香りと低いBGMが流れている。',
    senderVoiceInstruction: '切迫感を軽くにじませつつ、実務的で礼儀正しい口調。',
    receiverVoiceInstruction: '手際よく事務的に、即答できる自信のある口調で。',
    incorrectOptions: [
      '在庫は十分あり、納期は通常通りです。ご安心ください。',
      '豆は自家栽培なので宇宙から届きます。たぶん明日も、ね',
      '欠品のため、本日の受注は見合わせとなります。ご了承ね',
    ],
  },
  {
    place: '本社オフィスのITヘルプデスク',
    senderRole: 'ヘルプデスク担当者',
    senderVoice: 'female',
    receiverRole: '社員',
    receiverVoice: 'male',
    englishSentence:
      'Heads-up: there’s a planned outage tonight—could you back up your files beforehand?',
    japaneseSentence: '今夜は計画停止のため、事前にファイルをバックアップしてください。',
    englishReply: 'Got it. I’ll save everything to the shared drive before I leave.',
    japaneseReply: '了解です。退勤前に共有ドライブへ保存しておきます。',
    scenePrompt:
      '夕方のフロア。定期メンテナンスでファイルサーバーが夜間停止予定。担当者が社内チャットと口頭で周知し、社員は作業締めに入っている。周囲にはデュアルモニターと書類が並ぶ。',
    senderVoiceInstruction: '端的でフレンドリー、注意喚起をはっきり伝える口調。',
    receiverVoiceInstruction: '落ち着いた確認のトーンで、協力する意思を明快に示す。',
    incorrectOptions: [
      '今夜の停止はなく、準備は不要ですのでそのままで大丈夫です。本日中。',
      '停電の代わりに満月が光るので、PCを月光充電してください。今夜も',
      '明日の朝に停止予定で、今夜の対応は必要ありません。ご了承ください。',
    ],
  },
  {
    place: 'シティホテルのフロント',
    senderRole: 'コンシェルジュ',
    senderVoice: 'male',
    receiverRole: '宿泊客',
    receiverVoice: 'female',
    englishSentence:
      'As a goodwill gesture, we can comp your breakfast and upgrade you, if that works.',
    japaneseSentence: 'お詫びとして朝食を無料にし、客室のアップグレードも承ります。',
    englishReply: 'Thank you. That would make up for the delay. I appreciate it.',
    japaneseReply: 'ありがとうございます。遅延の件もそれで納得できます。助かります。',
    scenePrompt:
      'チェックインで部屋準備が遅れ、コンシェルジュが誠意を示して提案。大理石のロビー、柔らかな照明、静かなピアノ曲が流れている。宿泊客は出張中で時間に余裕は少ない。',
    senderVoiceInstruction: '丁寧で誠実、落ち着いた声でお詫びと提案を伝える。',
    receiverVoiceInstruction: '安心した様子で感謝を述べる穏やかな口調。',
    incorrectOptions: [
      '追加料金をいただき、客室は下位タイプへの変更となります。本日。',
      '朝食は雲の上で提供し、部屋は宇宙船に変形します。夢の演出です',
      '本日は満室ですが、ラウンジの利用権は無償でご用意します。特典',
    ],
  },
  {
    place: '物流倉庫の出荷カウンター',
    senderRole: '出荷担当',
    senderVoice: 'female',
    receiverRole: '取引先担当者',
    receiverVoice: 'male',
    englishSentence:
      'We’re in a last-minute crunch, but I can bump your order up if you’re flexible on quantity.',
    japaneseSentence: '大詰めですが、数量に融通いただければご注文を前倒しできます。',
    englishReply: 'I can accept fewer units this week. Please ship whatever you can.',
    japaneseReply: '今週は数量を減らして構いません。可能な分で出荷してください。',
    scenePrompt:
      '月末の締めで倉庫は慌ただしい。出荷担当は優先度を入れ替えながらフォークリフトの動きを指示。取引先は発売に間に合わせたい事情があり、数量調整を相談している。',
    senderVoiceInstruction: '迅速で実務的、配慮を感じさせるはっきりした口調。',
    receiverVoiceInstruction: '前向きで協力的、ていねいに依頼を受け入れるトーン。',
    incorrectOptions: [
      '前倒しは不可で、数量の変更も受け付けられません。以上ですね',
      'ご注文は魔法で増やせるので、今から空に放り投げます。多分嘘です',
      '本日は混雑のため、通常順での出荷しか対応できませんですね。',
    ],
  },
  {
    place: '企業の会議室',
    senderRole: '部長',
    senderVoice: 'male',
    receiverRole: '課長',
    receiverVoice: 'female',
    englishSentence: 'Could you consolidate the feedback and circulate the summary before noon?',
    japaneseSentence: '午前中までにフィードバックをまとめて、要約を回覧してもらえますか？',
    englishReply: 'Absolutely. I’ll compile everything and share it by eleven.',
    japaneseReply: '承知しました。十一時までにまとめて共有します。',
    scenePrompt:
      '会議終了直後の会議室。部長が各部署の意見をまとめた報告書を昼までに共有するよう依頼している。課長はノートPCを開きながらメモを取っている。窓際にはコーヒーが冷めかけている。',
    senderVoiceInstruction: '落ち着いたが明確に指示を出すフォーマルな口調で。',
    receiverVoiceInstruction: 'きびきびとした応答で、即行動に移す姿勢を示す。',
    incorrectOptions: [
      '午後までに全員の意見を破棄して報告書を削除しておきます。',
      '内容は未確認のまま全社員に即時送信しますのでご安心を。',
      '明日の午後に共有しますので、今日は何もしませんね。',
    ],
  },
  {
    place: '空港の搭乗ゲート',
    senderRole: '地上係員',
    senderVoice: 'female',
    receiverRole: '乗客',
    receiverVoice: 'male',
    englishSentence: 'Due to a gate change, your flight will now depart from Gate 32B.',
    japaneseSentence: 'ゲート変更のため、便は32Bゲートから出発いたします。',
    englishReply: 'Got it. Thanks for the heads-up. Do I need to recheck in?',
    japaneseReply: '了解です。知らせてくれてありがとうございます。再チェックインは必要ですか？',
    scenePrompt:
      '空港の出発ロビー。搭乗口付近のアナウンスに合わせて、地上係員が個別に案内している。乗客はスーツケースを持ち、掲示板を見上げている。',
    senderVoiceInstruction: '丁寧かつ事務的に、落ち着いたトーンで案内を行う。',
    receiverVoiceInstruction: '礼儀正しく感謝を述べながらも確認する穏やかな口調で。',
    incorrectOptions: [
      '搭乗口はそのままなので走らずにゆっくり寝ていてください。',
      '便はキャンセルされ、代わりに徒歩で向かっていただきます。',
      '変更はありません。全ての便が同じゲートから出ます。',
    ],
  },
  {
    place: '企業の受付ロビー',
    senderRole: '受付担当',
    senderVoice: 'female',
    receiverRole: '来訪者',
    receiverVoice: 'male',
    englishSentence: 'Could you sign in here and wait until Ms. Rivera comes down to meet you?',
    japaneseSentence: 'こちらにご署名の上、リベラ様がお迎えに来るまでお待ちください。',
    englishReply: 'Of course. I’ll take a seat right over there.',
    japaneseReply: 'かしこまりました。あちらの席でお待ちします。',
    scenePrompt:
      '企業ビルの明るい受付。ガラスの扉越しに外の通りが見える。受付係が来客用タブレットを差し出し、来訪者は丁寧に頷いて署名をしている。',
    senderVoiceInstruction: '丁寧で親切な口調で、案内するように落ち着いて話す。',
    receiverVoiceInstruction: '穏やかに応じ、礼儀正しく受け答えする。',
    incorrectOptions: [
      'リベラ様は本日退社しましたので、屋上でお待ちください。',
      '署名の代わりにサインペンを食べていただけますか？',
      '署名不要です。そのまま執務室に突撃して構いません。',
    ],
  },
  {
    place: '社内会議',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'male',
    receiverRole: 'チームメンバー',
    receiverVoice: 'female',
    englishSentence: 'If we streamline the approval process, we could cut turnaround time by half.',
    japaneseSentence: '承認プロセスを効率化すれば、対応時間を半減できるはずです。',
    englishReply: 'That makes sense. I’ll draft a simpler workflow for review.',
    japaneseReply: 'なるほどです。確認用に簡易なワークフロー案を作ってみます。',
    scenePrompt:
      '社内の打ち合わせ室。ホワイトボードには進行中の案件フロー図。マネージャーが改善案を提示し、メンバーがノートパソコンを操作しながら反応している。',
    senderVoiceInstruction: '分析的で落ち着いた口調。論理的に提案する。',
    receiverVoiceInstruction: '賛同を示し、前向きに行動を提案する明るい声で。',
    incorrectOptions: [
      '承認を複雑にして三倍の時間をかけましょう。',
      '効率化の代わりに全員で紙芝居をしましょう。',
      '現状維持で問題ないので、何も変えなくていいです。',
    ],
  },
  {
    place: '商談用の会議室',
    senderRole: '営業担当',
    senderVoice: 'female',
    receiverRole: 'クライアント',
    receiverVoice: 'male',
    englishSentence:
      'We can tailor the proposal to your budget if you could share your upper limit.',
    japaneseSentence: 'ご予算の上限をお知らせいただければ、提案を調整いたします。',
    englishReply: 'Sure, our ceiling is around thirty thousand dollars. Please work within that.',
    japaneseReply: 'わかりました。上限は三万ドルほどです。その範囲でお願いします。',
    scenePrompt:
      '会議室で営業担当がプレゼン資料を開きながら柔らかい口調で説明。クライアントは慎重に頷きながら予算について具体的な数字を提示している。',
    senderVoiceInstruction: '柔らかく誠実な営業トーンで、調整可能であることを示す。',
    receiverVoiceInstruction: '落ち着いて具体的に回答し、信頼感を持って話す。',
    incorrectOptions: [
      '上限は無限大です。宇宙までどうぞ。',
      '予算を超えてでも全力で破産しますので問題ありません。',
      '予算の話は後日で構いません。今日は世間話だけにしましょう。',
    ],
  },
  {
    place: '企業のオフィス廊下',
    senderRole: '人事担当',
    senderVoice: 'female',
    receiverRole: '社員',
    receiverVoice: 'male',
    englishSentence:
      'Just a heads-up, your performance review has been moved to next Wednesday afternoon.',
    japaneseSentence: 'お知らせですが、人事評価面談は来週の水曜午後に変更になりました。',
    englishReply: 'Thanks for letting me know. Should I prepare any documents?',
    japaneseReply: '教えてくださってありがとうございます。何か資料を用意すべきですか？',
    scenePrompt:
      'オフィスの廊下で、人事担当が通りがかりの社員に声をかけてスケジュール変更を伝えている。周囲にはコピー機の音が響く静かな午後。',
    senderVoiceInstruction: '事務的で落ち着いたトーンで、フレンドリーに伝える。',
    receiverVoiceInstruction: '礼儀正しく確認の意を込めて穏やかに返答する。',
    incorrectOptions: [
      '面談は本日10分後に変更されました。走ってください！',
      '面談は無期限延期です。永遠に準備しなくて大丈夫です。',
      '次回は先週に行われました。時間旅行が必要ですね。',
    ],
  },
  {
    place: 'レストランのキッチン',
    senderRole: '料理長',
    senderVoice: 'male',
    receiverRole: '副料理長',
    receiverVoice: 'female',
    englishSentence: 'We’re running low on basil—could you check if the delivery has arrived?',
    japaneseSentence: 'バジルの在庫が少ないので、納品が届いているか確認してもらえますか？',
    englishReply: 'On it. I’ll ask the delivery staff right away.',
    japaneseReply: '了解です。すぐに納品担当に確認します。',
    scenePrompt:
      'ディナー前の忙しいキッチン。料理長がハーブ棚を見てバジルが足りないことに気づき、副料理長に確認を頼む。周囲は調理音とスチームの匂いが立ちこめている。',
    senderVoiceInstruction: '少し急ぎの様子で実務的に指示を出す。',
    receiverVoiceInstruction: '即座に行動に移る意志を明るく示す。',
    incorrectOptions: [
      'バジルではなくパセリで全部代用しておきました！',
      '納品確認は来週に回します。気が向いたら。',
      'バジルは空から降ってくると思うので待ちましょう。',
    ],
  },
  {
    place: '企業の商談会議室',
    senderRole: '購買担当',
    senderVoice: 'female',
    receiverRole: '営業担当',
    receiverVoice: 'male',
    englishSentence: 'Before we move forward, could you clarify the warranty coverage?',
    japaneseSentence: '先に進む前に、保証の範囲を明確にしてもらえますか？',
    englishReply: 'Of course. It covers all manufacturing defects for two years.',
    japaneseReply: 'もちろんです。製造上の不具合は2年間保証されます。',
    scenePrompt:
      '明るい会議室。契約書のドラフトをテーブルに広げ、購買担当が確認事項を質問。営業担当がパンフレットを指しながら説明している。',
    senderVoiceInstruction: '落ち着いて、確認を求める丁寧なトーンで。',
    receiverVoiceInstruction: '誠実かつ安心感のある口調で説明する。',
    incorrectOptions: [
      '保証は一切ありませんが、気持ちはこもっています。',
      '保証は100年間有効で、月にも対応します。',
      '保証内容は非公開ですので想像でお願いします。',
    ],
  },
  {
    place: 'コワーキングスペースのラウンジ',
    senderRole: '起業家',
    senderVoice: 'male',
    receiverRole: '共同創業者',
    receiverVoice: 'female',
    englishSentence: 'Let’s touch base tomorrow to finalize the pitch deck revisions.',
    japaneseSentence: '明日打ち合わせをして、ピッチ資料の修正版を確定しましょう。',
    englishReply: 'Sounds good. I’ll review the slides tonight.',
    japaneseReply: 'いいですね。今夜スライドを確認しておきます。',
    scenePrompt:
      'ノートパソコンを開いてコーヒーを飲む二人。スタートアップのピッチ資料を修正しており、夕方の日差しが窓から差し込む。',
    senderVoiceInstruction: 'リラックスしつつ前向きなトーンで、軽やかに提案する。',
    receiverVoiceInstruction: '明るく即答し、行動意欲を見せる自然な口調で。',
    incorrectOptions: [
      '打ち合わせは100年後で構いません。急ぎませんから。',
      '資料は完成済みなので二度と触れません。',
      '明日の会議は資料なしで歌って乗り切りましょう。',
    ],
  },
  {
    place: '企業の倉庫オフィス',
    senderRole: '在庫管理担当',
    senderVoice: 'female',
    receiverRole: '配送チームリーダー',
    receiverVoice: 'male',
    englishSentence:
      'The shipment’s been held up at customs, so we might need to adjust the delivery schedule.',
    japaneseSentence:
      '出荷が税関で止まっているため、納品スケジュールを調整する必要がありそうです。',
    englishReply: 'Understood. I’ll notify the clients about the possible delay.',
    japaneseReply: '了解しました。納期遅延の可能性を取引先に伝えます。',
    scenePrompt:
      '在庫管理室。モニターには物流システムのトラッキング画面。担当者が画面を見つめながらリーダーに報告している。外ではフォークリフトの音が響く。',
    senderVoiceInstruction: '冷静で事務的に、状況を正確に報告する。',
    receiverVoiceInstruction: '責任感を持ち、冷静に次の対応を伝える落ち着いた口調で。',
    incorrectOptions: [
      '税関で止まってません。むしろ宇宙に届きました。',
      '遅延ではなく、未来に先行出荷しました。時間逆行です。',
      'スケジュール通りですが、納品先を忘れました。',
    ],
  },
  {
    place: '本社のプレゼン会場',
    senderRole: 'マーケティング部長',
    senderVoice: 'male',
    receiverRole: 'チームリーダー',
    receiverVoice: 'female',
    englishSentence:
      'Could you walk the executives through the campaign metrics during the presentation?',
    japaneseSentence: '発表の際に、経営陣へキャンペーン指標の説明をお願いできますか？',
    englishReply: 'Of course. I’ll prepare clear visuals to make it easy to follow.',
    japaneseReply: '承知しました。理解しやすい資料を準備します。',
    scenePrompt:
      '広い会議室。スクリーンにグラフが映り、部長が発表内容を確認している。チームリーダーはノートPCでスライドを最終調整している。',
    senderVoiceInstruction: 'フォーマルで落ち着いた口調、期待を込めて頼む。',
    receiverVoiceInstruction: '自信を持って応じ、誠実なトーンで答える。',
    incorrectOptions: [
      '発表中に寝てしまうと思うので説明はやめておきます。',
      '指標ではなくジョークを披露して盛り上げます。',
      '経営陣には数値は秘密にしておきましょう。',
    ],
  },
  {
    place: 'ホテルの宴会場',
    senderRole: 'イベントコーディネーター',
    senderVoice: 'female',
    receiverRole: '司会者',
    receiverVoice: 'male',
    englishSentence:
      'Just to confirm, could you announce the award winners right after the keynote speech?',
    japaneseSentence: '確認ですが、基調講演の直後に受賞者を発表していただけますか？',
    englishReply: 'Got it. I’ll cue the list as soon as the speech ends.',
    japaneseReply: '了解です。講演終了後すぐに受賞者を読み上げます。',
    scenePrompt:
      '華やかなホテルの宴会場。照明が柔らかく、音響チェックの最中。イベントコーディネーターが進行表を手にし、司会者とタイミングを確認している。',
    senderVoiceInstruction: '明るくプロフェッショナルな口調で、丁寧に確認する。',
    receiverVoiceInstruction: 'きびきびとした自信あるトーンで応答する。',
    incorrectOptions: [
      '受賞者は明日の朝に発表します。寝不足対策です。',
      '講演の前に発表してサプライズを台無しにします。',
      '受賞者を発表せずに全員で黙祷します。',
    ],
  },
  {
    place: 'メーカーの設計室',
    senderRole: '品質管理担当',
    senderVoice: 'male',
    receiverRole: '設計エンジニア',
    receiverVoice: 'female',
    englishSentence:
      'We’ve spotted a minor defect in the prototype. Could you take another look at the design file?',
    japaneseSentence: '試作品に小さな欠陥が見つかったので、設計データを再確認してもらえますか？',
    englishReply: 'Sure thing. I’ll check the dimensions and tolerance again.',
    japaneseReply: 'わかりました。寸法と許容差を再確認します。',
    scenePrompt:
      '設計図面が広がる静かな設計室。品質担当者が3Dモデルを指差しながら説明し、エンジニアがノートPCを操作して修正点を確認している。',
    senderVoiceInstruction: '冷静で分析的な口調。落ち着いて事実を伝える。',
    receiverVoiceInstruction: '集中して作業に向かう意思を示す、落ち着いたトーンで。',
    incorrectOptions: [
      '欠陥は気のせいです。問題は心の中にあります。',
      '確認は来世に回します。今日は終わりです。',
      '欠陥は放置してデザインを派手にします。',
    ],
  },
  {
    place: '商業ビルのエレベーターホール',
    senderRole: '清掃スタッフ',
    senderVoice: 'female',
    receiverRole: 'ビル管理者',
    receiverVoice: 'male',
    englishSentence: 'One of the elevators is acting up—it keeps stopping between floors.',
    japaneseSentence: 'エレベーターの一台が不調で、階の途中で止まることがあります。',
    englishReply: 'Thanks for catching that. I’ll call maintenance right away.',
    japaneseReply: '気づいてくれて助かります。すぐに保守業者へ連絡します。',
    scenePrompt:
      'ビルのエレベーターホール。清掃スタッフがモップを持ちながら管理者に報告している。廊下には警告ランプが点滅している。',
    senderVoiceInstruction: '落ち着いたが少し心配そうな声で報告する。',
    receiverVoiceInstruction: '冷静に感謝を伝え、行動を約束する誠実なトーンで。',
    incorrectOptions: [
      'エレベーターは踊りたがっているだけなので問題ありません。',
      '止まるのは仕様です。冒険気分を楽しんでください。',
      '動作に問題はなく、むしろ速すぎるくらいです。',
    ],
  },
  {
    place: 'IT企業のオンラインミーティング',
    senderRole: 'プロダクトマネージャー',
    senderVoice: 'male',
    receiverRole: 'デザイナー',
    receiverVoice: 'female',
    englishSentence: 'If we tweak the layout slightly, the user flow will feel much smoother.',
    japaneseSentence: 'レイアウトを少し調整すれば、ユーザー導線がより自然になります。',
    englishReply: 'I agree. I’ll adjust the spacing and margins tonight.',
    japaneseReply: '賛成です。今夜スペースと余白を調整します。',
    scenePrompt:
      'オンライン会議中。画面共有でUIデザインを確認しながら、改善案を話し合う二人。背後にはそれぞれ自宅オフィスの様子が見える。',
    senderVoiceInstruction: '柔らかく前向きなトーンで、提案を自然に伝える。',
    receiverVoiceInstruction: '明るく賛同し、行動を引き受ける声で答える。',
    incorrectOptions: [
      '調整せずに画面を上下逆にして個性を出しましょう。',
      '導線を消して迷子体験を提供しましょう。',
      '今のままで完璧です。むしろ触らないでおきましょう。',
    ],
  },
  {
    place: '大学の事務室',
    senderRole: '事務スタッフ',
    senderVoice: 'female',
    receiverRole: '学生',
    receiverVoice: 'male',
    englishSentence:
      'You’ll need to submit your transcript request by Friday to meet the application deadline.',
    japaneseSentence:
      '出願締切に間に合わせるためには、成績証明書の申請を金曜日までに提出してください。',
    englishReply: 'Thanks for the reminder. I’ll drop it off this afternoon.',
    japaneseReply: '教えてくださってありがとうございます。今日の午後に提出します。',
    scenePrompt:
      '大学の事務室で、窓口に学生が来て書類を確認している。事務スタッフがパソコンを操作しながら締切を伝え、学生は頷いてスケジュールを確認している。',
    senderVoiceInstruction: '穏やかで丁寧に案内する口調で話す。',
    receiverVoiceInstruction: '礼儀正しく安心したトーンで答える。',
    incorrectOptions: [
      '締切は昨日でしたが、気にせず出さなくて大丈夫です。',
      '金曜日ではなく、金星までに提出してください。',
      '申請は来年でも間に合うと思います。',
    ],
  },
  {
    place: '病院の受付カウンター',
    senderRole: '受付スタッフ',
    senderVoice: 'female',
    receiverRole: '患者',
    receiverVoice: 'male',
    englishSentence: 'Could you fill out this consent form before your examination?',
    japaneseSentence: '診察の前に、こちらの同意書にご記入をお願いいたします。',
    englishReply: 'Sure. Do you need both copies signed?',
    japaneseReply: 'わかりました。両方の用紙に署名が必要ですか？',
    scenePrompt:
      '病院の受付で、スタッフが書類を渡し、患者がボールペンを手に取る。周囲には待合室で静かに順番を待つ人々がいる。',
    senderVoiceInstruction: '丁寧で落ち着いたトーン、穏やかに案内する。',
    receiverVoiceInstruction: '控えめながらも確認するような落ち着いた口調で。',
    incorrectOptions: [
      '同意書は燃やしていただいて結構です。',
      '記入は必要ありません。占いで判断します。',
      '診察の後に同意を取り消せば問題ありません。',
    ],
  },
  {
    place: 'コールセンターのオフィス',
    senderRole: 'スーパーバイザー',
    senderVoice: 'male',
    receiverRole: '新人オペレーター',
    receiverVoice: 'female',
    englishSentence:
      'If a customer sounds frustrated, try acknowledging their concern before offering solutions.',
    japaneseSentence: 'お客様が苛立っているようなら、解決策を出す前にまず共感を示してください。',
    englishReply: 'Got it. I’ll make sure to do that during my next call.',
    japaneseReply: '了解しました。次の対応から意識してやってみます。',
    scenePrompt:
      'オフィス内のコールセンター。スーパーバイザーが新人の席に立ち、ヘッドセット越しに指導している。新人はメモを取りながら頷いている。',
    senderVoiceInstruction: '穏やかで教える姿勢を持つ落ち着いた声で。',
    receiverVoiceInstruction: '前向きで真剣に受け止める明るいトーンで。',
    incorrectOptions: [
      '苛立っていたら電話を切って休憩しましょう。',
      '共感の代わりに謎かけをして落ち着かせましょう。',
      '無視してスクリプトを早口で読み続けてください。',
    ],
  },
  {
    place: 'カフェカウンター',
    senderRole: '店員',
    senderVoice: 'female',
    receiverRole: '客',
    receiverVoice: 'male',
    englishSentence:
      'Your order will be ready in about five minutes. Would you like it for here or to go?',
    japaneseSentence:
      'ご注文は5分ほどでご用意できます。店内でお召し上がりですか？お持ち帰りですか？',
    englishReply: 'To go, please. I’m in a bit of a hurry.',
    japaneseReply: '持ち帰りでお願いします。少し急いでいるので。',
    scenePrompt:
      'カフェのカウンターで店員が笑顔でオーダーを確認している。客はスマートフォンを手にしながら財布を取り出している。',
    senderVoiceInstruction: '明るく親しみやすい口調で、丁寧に尋ねる。',
    receiverVoiceInstruction: '急いでいる様子を穏やかに表す自然なトーンで。',
    incorrectOptions: [
      'お持ち帰りではなく、永住でお願いします。',
      '5分では遅いので1秒でお願いします。',
      'ここで食べますが、席は空港でお願いします。',
    ],
  },
  {
    place: '出版社の編集部',
    senderRole: '編集長',
    senderVoice: 'male',
    receiverRole: 'ライター',
    receiverVoice: 'female',
    englishSentence: 'Your draft looks solid, but could you trim down the introduction a bit?',
    japaneseSentence: '原稿はよくできていますが、冒頭を少し短くしてもらえますか？',
    englishReply: 'Sure, I’ll tighten it up and send a revised version tonight.',
    japaneseReply: 'わかりました。簡潔にして今夜修正版をお送りします。',
    scenePrompt:
      '編集部のデスク周り。原稿のプリントが散らばり、編集長が赤ペンを持ちながらライターにアドバイスしている。窓の外には夕焼け。',
    senderVoiceInstruction: '冷静で穏やかに、肯定を含む丁寧な口調で話す。',
    receiverVoiceInstruction: '前向きで自信を持ちながら応じる声で。',
    incorrectOptions: [
      '冒頭を三倍に伸ばして圧倒させましょう。',
      '短くする代わりに詩を100行足します。',
      '冒頭は削除せず、終わりを消して完結させます。',
    ],
  },
  {
    place: '空港の搭乗ゲート',
    senderRole: '搭乗スタッフ',
    senderVoice: 'female',
    receiverRole: '乗客',
    receiverVoice: 'male',
    englishSentence:
      'Your flight’s been slightly delayed due to weather conditions. We expect boarding to start in thirty minutes.',
    japaneseSentence: '天候の影響でフライトが少し遅れています。搭乗は30分後に開始予定です。',
    englishReply: 'Thanks for the update. I’ll wait nearby.',
    japaneseReply: 'お知らせありがとうございます。近くで待機します。',
    scenePrompt:
      '空港の搭乗ゲート付近。大型モニターに遅延情報が表示され、スタッフがマイク越しに乗客へ案内している。周囲には待合客が静かに座っている。',
    senderVoiceInstruction: '落ち着いた丁寧なトーンで、安心感を与えるように話す。',
    receiverVoiceInstruction: '穏やかに理解を示す声で応答する。',
    incorrectOptions: [
      '遅延ではなく、飛行機が逆方向に飛んでいます。',
      '30分後ではなく、30年前に出発しました。',
      '天候は完璧ですが、気分で遅らせています。',
    ],
  },
  {
    place: '会社の受付ロビー',
    senderRole: '受付スタッフ',
    senderVoice: 'female',
    receiverRole: '訪問客',
    receiverVoice: 'male',
    englishSentence: 'Could you please sign in here before heading to the meeting room?',
    japaneseSentence: '会議室へお進みになる前に、こちらでご署名をお願いいたします。',
    englishReply: 'Of course. Do I need to show my ID as well?',
    japaneseReply: 'かしこまりました。身分証の提示も必要ですか？',
    scenePrompt:
      '企業の受付ロビー。来客用のサインインシートが置かれ、受付スタッフが微笑みながらペンを差し出している。',
    senderVoiceInstruction: '丁寧で親しみやすい声で案内する。',
    receiverVoiceInstruction: '礼儀正しく確認する柔らかなトーンで。',
    incorrectOptions: [
      '署名は後ほど夢の中で行います。',
      'ここではなく、屋上でサインしてください。',
      '署名せずに忍び足で通り抜けます。',
    ],
  },
  {
    place: 'IT企業のプロジェクト会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'male',
    receiverRole: 'デベロッパー',
    receiverVoice: 'female',
    englishSentence: 'Let’s circle back to the API issue after lunch and finalize the fix plan.',
    japaneseSentence: '昼食後にAPIの問題に戻って、修正計画を確定しましょう。',
    englishReply: 'Sounds good. I’ll prepare the updated logs by then.',
    japaneseReply: '了解です。その時間までに最新のログを用意しておきます。',
    scenePrompt:
      'モニターにコードのログが映る会議室。マネージャーが議事をまとめ、デベロッパーがノートPCを操作しながら頷いている。',
    senderVoiceInstruction: '実務的で落ち着いたトーン、前向きに提案する。',
    receiverVoiceInstruction: '明るく責任感のある声で返答する。',
    incorrectOptions: [
      'APIではなく、AIに祈りを捧げましょう。',
      '修正は来世で行う予定です。',
      '昼食後は昼寝なので作業は来週にします。',
    ],
  },
  {
    place: '病院の診察室',
    senderRole: '医師',
    senderVoice: 'male',
    receiverRole: '患者',
    receiverVoice: 'female',
    englishSentence:
      'Your test results look normal, but I’d still recommend a follow-up in a month.',
    japaneseSentence: '検査結果は正常ですが、念のため1か月後に再診をお勧めします。',
    englishReply: 'Thank you, doctor. I’ll make an appointment before I leave.',
    japaneseReply: 'ありがとうございます。帰る前に予約を取ります。',
    scenePrompt: '明るい診察室。医師がタブレットで検査結果を見せ、患者が安心した表情で聞いている。',
    senderVoiceInstruction: '穏やかで安心感を与えるトーンで説明する。',
    receiverVoiceInstruction: '感謝と安堵を込めて穏やかに答える。',
    incorrectOptions: [
      '結果は正常ですが、宇宙旅行を控えてください。',
      '再診は必要ありません。永遠に健康です。',
      '結果は正常なので祝勝パーティーを開きましょう。',
    ],
  },
  {
    place: 'ホテルのフロント',
    senderRole: 'フロントスタッフ',
    senderVoice: 'female',
    receiverRole: '宿泊客',
    receiverVoice: 'male',
    englishSentence: 'If you need a late check-out, please let us know by noon.',
    japaneseSentence: 'レイトチェックアウトをご希望の場合は、正午までにお知らせください。',
    englishReply: 'Got it. I might need an extra hour, so I’ll inform you later this morning.',
    japaneseReply: '承知しました。1時間延長するかもしれないので、午前中にお伝えします。',
    scenePrompt:
      'ホテルのフロントで、スタッフが笑顔で案内している。客はキャリーバッグを持ち、出発時間を検討している。',
    senderVoiceInstruction: '丁寧で柔らかな口調で案内する。',
    receiverVoiceInstruction: '落ち着いて検討する様子で、礼儀正しく返答する。',
    incorrectOptions: [
      'チェックアウトは正午どころか正月になります。',
      '延長ではなく、永住を希望します。',
      'レイトチェックアウトではなく早朝チェックインを希望します。',
    ],
  },
];

export default problemData;
