import { SeedProblemData } from '../src/types/problem';

/**
 * 問題データ 8
 * Generated by GPT API (6 problems)
 */
const problemData: SeedProblemData[] = [
  {
    place: '大手IT企業の本社会議室',
    senderRole: 'マーケティング部マネージャー',
    senderVoice: 'female',
    receiverRole: '新人営業担当',
    receiverVoice: 'male',
    englishSentence: 'Are you an affiliate of ours?', // 8語以内、"affiliate"を自然に使用、質問文、会議室での役割に沿った内容
    japaneseSentence: 'あなたは当社の提携先ですか？', // "affiliate"の意味を直訳で理解できる直訳系
    englishReply: 'No, I just joined the company.', // 簡単な単語で状況に合った返答
    japaneseReply: 'いいえ、私は入社したばかりです。', // 自然な日本語訳
    scenePrompt:
      '大手IT企業の会議室で、新人営業担当が初めて部署のマネージャーに自己紹介をしている。マネージャーは名簿を見ながら、新人がグループ会社や提携先企業の人間なのかどうかを確認している。', // 英文や訳に書かれていない背景・動機・場所の様子
    senderVoiceInstruction: 'ビジネスライクで丁寧な話し方',
    receiverVoiceInstruction: 'やや緊張気味に、誠実そうに',
    incorrectOptions: [
      '本日からあなたも正社員ですね。',
      '実は当社とは全く無関係です。',
      'カエルがピアノを弾くのを見たいですか？',
      // 1つ目: 直訳と異なる「正社員」、2つ目: 真逆の「全く無関係」、3つ目: 馬鹿馬鹿しい内容
    ],
  },
  {
    place: '建設会社の現場監督事務所',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'male',
    receiverRole: '現場アシスタント',
    receiverVoice: 'female',
    englishSentence: 'We need to allocate resources efficiently.', // 8語以内、"allocate resources"を自然に含めた依頼表現
    japaneseSentence: '私たちは資源を効率よく配分する必要があります。', // 熟語・慣用句系、allocate resourcesの直訳では意味が掴みにくい
    englishReply: 'Okay, I will make a plan.', // 簡単な単語で、依頼に応じる自然な返答
    japaneseReply: '分かりました、計画を立てます。', // 自然な日本語訳
    scenePrompt:
      '建設現場の事務所で、プロジェクトマネージャーが資材や人員の割り振りについて現場アシスタントに指示を出している。工期が迫っており、効率的な運用が求められている。', // 場所や状況、背景が具体的に説明されている
    senderVoiceInstruction: '落ち着いたが、少し急ぎの口調で',
    receiverVoiceInstruction: '真面目で前向きなトーン',
    incorrectOptions: [
      'この現場に全ての資材を集めてください。',
      '資源をまったく使わないでください。',
      'サンドイッチを空に向かって投げてください。',
      // 1つ目: 直訳と異なる「集める」、2つ目: 真逆の「使わない」、3つ目: 馬鹿馬鹿しい内容
    ],
  },
  {
    place: '中小企業の経理部オフィス',
    senderRole: '経理部長',
    senderVoice: 'female',
    receiverRole: '新入社員',
    receiverVoice: 'male',
    englishSentence: "Let's discuss this year's amortization schedule.", // 8語以内、"amortization"を使った提案表現
    japaneseSentence: '今年の償却スケジュールについて話し合いましょう。', // 熟語・慣用句系、amortizationの意味が日本人には馴染みにくい
    englishReply: 'Sure, I have the documents ready.', // 簡単な単語で提案への肯定的な返答
    japaneseReply: 'はい、資料を用意しています。', // 自然な日本語訳
    scenePrompt:
      '中小企業の経理部で、期末を控えた部長が新入社員に償却（減価償却）の年間スケジュールについて説明しようとしている。細かい会計処理の確認が必要なタイミング。', // 英文や訳に書かれていない背景や動機
    senderVoiceInstruction: '落ち着いていて、教育的な口調で',
    receiverVoiceInstruction: '素直でやや緊張したトーン',
    incorrectOptions: [
      '来年の予算案を決めましょう。',
      '今年の償却は一切行いません。',
      'ピザの配達スケジュールを考えましょう。',
      // 1つ目: 「予算案」で直訳から外す、2つ目: 真逆の内容、3つ目: 馬鹿馬鹿しい内容
    ],
  },
  {
    place: '美術品オークション会場',
    senderRole: '鑑定士',
    senderVoice: 'male',
    receiverRole: 'バイヤー',
    receiverVoice: 'female',
    englishSentence: 'I need to appraise this painting.',
    // 指定語彙 "appraise" を8語以内で自然に組み込み、鑑定士が鑑定を必要と伝えるシーンの自然な文
    japaneseSentence: 'この絵画を鑑定する必要があります。',
    // 上記英文の直訳に近い自然な日本語訳
    englishReply: 'Okay, please take your time.',
    // 熟語を避けた、内容が直訳しやすい自然な返答。鑑定士への了承や配慮が伝わる文
    japaneseReply: 'はい、ごゆっくりどうぞ。',
    // オークション会場で鑑定士がバイヤーの依頼を受け、絵画の価値を評価しようとする場面。人々が行き交い、静かな緊張感が漂う会場で、バイヤーが持ち込んだ作品の前に2人が立っている。周囲には他の美術品や展示台、オークションスタッフの姿もある。
    scenePrompt:
      '美術品オークション会場で、鑑定士がバイヤーから預かった絵画を慎重に鑑定しようとしている。静かな空気の中、周囲には他のバイヤーや美術品が並び、落札の瞬間を待つ雰囲気が漂っている。',
    senderVoiceInstruction: '落ち着いていて専門的な、やや低めの声で',
    receiverVoiceInstruction: '丁寧で控えめなトーン、やや緊張気味に',
    incorrectOptions: [
      'この作品は本物かどうか分かりますか？',
      // "この絵画を鑑定する必要があります。"と異なる語で始まり、内容も異なる
      '展示室に新しい絵を持ってきてください。',
      // "展示室"で始まり異なる内容。長さもバラけさせている
      '当会場で一番古い絵を食べてみませんか？',
      // 馬鹿馬鹿しい内容。食べるという非現実的な提案
    ],
  },
  {
    place: 'IT企業の会議室',
    senderRole: '開発チームリーダー',
    senderVoice: 'female',
    receiverRole: '新入社員',
    receiverVoice: 'male',
    englishSentence: 'Let’s set a new benchmark today.',
    // 指定語彙 "benchmark" を8語以内で自然に組み込み、会議での提案として成立
    japaneseSentence: '今日は新しい基準を設定しましょう。',
    // 上記英文の自然な日本語訳。会議で使われる表現
    englishReply: 'Sounds good. I’m ready.',
    // 簡潔で前向きな返答。熟語なし
    japaneseReply: 'いいですね。準備できてます。',
    // IT企業の会議室。開発チームのリーダーが新入社員やチームに向けて、今後のプロジェクト進行のため新しいパフォーマンス基準（ベンチマーク）の策定を提案している。会議テーブルの周りに数人が座り、資料やノートPCが並んでいる。
    scenePrompt:
      'IT企業の会議室で、開発チームリーダーが新入社員を含むメンバーにプロジェクトの新たなベンチマークを設定することを提案している。ホワイトボードやノートPCが並ぶ現代的な空間。',
    senderVoiceInstruction: '明るく前向きでリーダーシップのあるトーン',
    receiverVoiceInstruction: '少し緊張しつつもやる気のある若々しい声',
    incorrectOptions: [
      '今日は締め切りを延期しましょう。',
      // "今日は新しい基準を設定しましょう。"と逆の意味
      '明日の会議で結果を発表します。',
      // "明日"で始まり、異なる内容
      '今夜はこの部屋でダンス大会を開きましょう！',
      // 馬鹿馬鹿しい内容
    ],
  },
  {
    place: '不動産競売会場',
    senderRole: 'オークション司会者',
    senderVoice: 'male',
    receiverRole: '入札者',
    receiverVoice: 'female',
    englishSentence: 'Is there another bidder in the room?',
    // 指定語彙 "bidder" を8語以内で自然な疑問文に組み込み
    japaneseSentence: '他に入札者はいらっしゃいますか？',
    // 英文の丁寧で自然な日本語訳。オークションで使われる表現
    englishReply: 'No, I am the only one.',
    // 簡単な返答。熟語なし
    japaneseReply: 'いいえ、私だけです。',
    // 不動産のオークション会場。司会者が会場を見渡しながら、現在の入札者以外に手を挙げる人がいないかを確認している。周囲には椅子に座った入札者や、物件資料を手にしたスタッフがいる。
    scenePrompt:
      '不動産競売会場で、司会者が最終確認のために他に入札者がいるかどうか会場全体に問いかけている。入札者たちが静かに司会者を見つめている。',
    senderVoiceInstruction: 'はっきりと聞き取りやすい、やや高めの声で',
    receiverVoiceInstruction: '落ち着いて自信のある口調',
    incorrectOptions: [
      '他に落札済みの人はいませんか？',
      // "入札者"ではなく"落札済み"で始まり、意味も異なる
      'この物件の写真はご覧になりましたか？',
      // "この物件"で始まり、内容が異なる
      '会場の椅子と机を全部逆さまにしますか？',
      // 馬鹿馬鹿しい提案。オークションの場面に不釣り合い
    ],
  },
];

export default problemData;
