import { SeedProblemData } from '../src/types/problem';

/**
 * 問題データ 4
 * Generated by create-problems.ts (6 problems)
 */
const problemData: SeedProblemData[] = [
  {
    place: '【1コマ目】会議室、【2コマ目】会議室のテーブル向かい側',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: 'チームリーダー',
    receiverVoice: 'male',
    englishSentence: 'In accordance with the new policy, I need your approval.',
    japaneseSentence: '新しい方針に従って、あなたの承認が必要です。',
    englishReply: 'Sure, I will review it and give my approval soon.',
    japaneseReply: 'わかりました。内容を確認して、すぐに承認します。',
    scenePrompt:
      '対面での会話。平日の午前中、オフィスの会議室で女性マネージャーが会議テーブル越しに男性チームリーダーへ新しい会社方針に基づく承認を求めている。1コマ目は女性が資料を手に説明している。2コマ目では男性が真剣な表情で返答している。まだ承認のサインはしていない。',
    senderVoiceInstruction: null,
    receiverVoiceInstruction: null,
    incorrectOptions: [
      '新しい方針に従って、カレーを食べる時間です。',
      '新しい方針に従って、あなたの承認は不要です。',
      '新しい方針に従って、今日は雨が降る予定です。',
    ],
    difficultyLevel: null,
  },
  {
    place: '【1コマ目】会議室、【2コマ目】会議室のテーブル向かい側',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: 'チームリーダー',
    receiverVoice: 'male',
    englishSentence: 'In accordance with the new policy, I need your approval first.',
    japaneseSentence: '新しい方針に従って、まずはあなたの承認が必要なんです。',
    englishReply: "Understood. I'll review everything and give my approval today.",
    japaneseReply: 'わかりました。内容を確認して、今日中に承認しますね。',
    scenePrompt:
      '対面での会話。平日の午前中、明るい会議室で女性マネージャーが会議テーブル越しに男性チームリーダーへ新しい会社方針について承認を求めて説明している。1コマ目は女性が資料を手に前向きな姿勢で話しかける場面。2コマ目は男性がテーブル越しに真剣な表情で返答している。まだ書類へのサインや承認は行われていない。',
    senderVoiceInstruction: null,
    receiverVoiceInstruction: null,
    incorrectOptions: [
      '新しい方針に従って、まずはカレーを作る必要があるんです。',
      '新しい方針に従って、あなたの承認は全く必要ありません。',
      '新しい方針に従って、昨日の天気について話し合うことが重要です。',
    ],
    difficultyLevel: null,
  },
  {
    place: '【1コマ目】会議室、【2コマ目】会議室のテーブル向かい側',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: 'チームリーダー',
    receiverVoice: 'male',
    englishSentence:
      'In accordance with the new company policy, I’ll need your official approval before moving forward with this budget request.',
    japaneseSentence:
      '新しい会社の方針に従って、この予算申請を進める前にあなたの正式な承認が必要になります。',
    englishReply: 'Understood. Please send me the details so I can review them.',
    japaneseReply: 'わかりました。内容を確認したいので、詳細を送ってください。',
    scenePrompt:
      '対面での会話。平日の午前中、明るい会議室で女性マネージャーがテーブル越しに男性チームリーダーへ新しい会社方針に基づく承認を求めている。1コマ目は女性が資料を持ちながら説明している。2コマ目では男性が真剣な表情で内容確認を依頼している。まだ資料は手渡されていないし、テーブルの上にも何も置かれていない。',
    senderVoiceInstruction: null,
    receiverVoiceInstruction: null,
    incorrectOptions: [
      '新しい会社の方針に従って、予算申請には巨大なピザの写真が必要になりますのでご注意ください。',
      '新しい会社の方針に従い、あなたの承認はまったく不要なので勝手に進めてください。',
      'この予算申請を進めるには、明日の天気予報を確認する必要がありますのでよろしくお願いします。',
    ],
    difficultyLevel: null,
  },
  {
    place: '【1コマ目】会議室、【2コマ目】会議室のテーブル席',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: 'The schedule is subject to change.',
    japaneseSentence: 'スケジュールは変更になる可能性があります。',
    englishReply: 'Understood. I will check for any updates before the meeting.',
    japaneseReply: 'わかりました。会議前に最新情報を確認します。',
    scenePrompt:
      '対面での会話。水曜の朝、オフィスの会議室で女性マネージャーが会議テーブル越しに男性チームメンバーへ会議日程の変更可能性を伝えている。1コマ目は女性が落ち着いた表情で説明している。2コマ目では男性がテーブル席でうなずきながら返答している。まだ会議資料や飲み物はテーブルに出ていない。',
    senderVoiceInstruction: null,
    receiverVoiceInstruction: null,
    incorrectOptions: [
      'スケジュールは宇宙人によって作られています。',
      'スケジュールは絶対に変更されることはありません。',
      'スケジュールと天気予報は全然関係ありません。',
    ],
    difficultyLevel: null,
  },
  {
    place: '【1コマ目】会議室、【2コマ目】会議室のテーブル席',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: 'Please note, the schedule may be subject to change this week.',
    japaneseSentence: '今週のスケジュールは変更になる可能性があるのでご注意ください。',
    englishReply: "Understood. I'll check for updates before the meeting.",
    japaneseReply: 'わかりました。会議前に最新情報を確認します。',
    scenePrompt:
      '対面での会話。水曜の朝、明るい会議室で女性マネージャーが会議テーブル越しに男性チームメンバーへ会議日程変更の可能性を伝えている。1コマ目は女性が座って説明し、2コマ目は男性が落ち着いた様子で頷きながら返答している。まだ資料や飲み物はテーブルに何も置かれていない。',
    senderVoiceInstruction: null,
    receiverVoiceInstruction: null,
    incorrectOptions: [
      '今週のスケジュールは宇宙人が決めるのでピザをご用意ください。',
      '今週のスケジュールは絶対に変更されることはありませんのでご安心ください。',
      '今週の天気予報はとても美味しいケーキが食べられる予定です。',
    ],
    difficultyLevel: null,
  },
  {
    place: '【1コマ目】会議室、【2コマ目】会議室のテーブル席',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence:
      'Please keep in mind that the schedule for Friday’s meeting is subject to change depending on client availability.',
    japaneseSentence:
      '金曜日の会議のスケジュールは、お客様の都合によって変更になる可能性があるので、その点を念頭に置いておいてください。',
    englishReply: 'Understood. I’ll check for updates before making any plans.',
    japaneseReply: '分かりました。予定を立てる前に最新情報を確認します。',
    scenePrompt:
      '対面での会話。水曜の朝、明るい会議室で女性マネージャーが会議テーブル越しに男性チームメンバーへ会議日程変更の可能性を伝えている。1コマ目は女性が立って説明し、2コマ目は男性が椅子に座ってうなずきながら返事をしている。まだ会議資料や飲み物はテーブルに置かれていない。',
    senderVoiceInstruction: null,
    receiverVoiceInstruction: null,
    incorrectOptions: [
      '金曜日の会議のスケジュールは、宇宙人の襲来によって変更になる可能性があるので、ヘルメットの準備を忘れないでください。',
      '金曜日の会議のスケジュールは、お客様の都合によって絶対に変更されることはありませんので、安心して大丈夫です。',
      '金曜日の会議のスケジュールは、最近流行しているパンケーキのお店について話し合う予定なので、お腹を空かせてきてください。',
    ],
    difficultyLevel: null,
  },
];

export default problemData;
