import { SeedProblemData } from '../src/types/problem';

/**
 * 問題データ 7
 * Generated by GPT API (10 problems)
 */
const problemData: SeedProblemData[] = [
  {
    place: 'デパートの総合案内所',
    senderRole: 'お客様',
    senderVoice: 'female',
    receiverRole: '案内係',
    receiverVoice: 'male',
    englishSentence: 'Do you have these products here?',
    // ルール根拠: "products" を自然に含み、会話としてデパートでよく使われる質問文。10語以下(7語)。
    japaneseSentence: 'こちらにこれらの商品はありますか？',
    // ルール根拠: "these products" を「これらの商品」と訳し、内容を省略せず正確に翻訳。
    englishReply: 'Yes, we have those products on the third floor.',
    // ルール根拠: "products" について言及し、場所も案内していて内容が推測できる。
    japaneseReply: 'はい、それらの商品は3階にございます。',
    // ルール根拠: "products" に触れつつ、具体的な案内となっている。
    scenePrompt:
      '大きなデパートの総合案内所で、女性客がお目当ての商品があるか尋ねている。周囲にはショップの案内板やパンフレットがある。案内係は丁寧にフロアを説明している。',
    // ルール根拠: 場所・登場人物・会話の背景・状況を具体的に描写。
    senderVoiceInstruction: '少し緊張しながらも丁寧に尋ねるトーン',
    receiverVoiceInstruction: '親切で落ち着いた丁寧な話し方',
    incorrectOptions: [
      '当店で一番不人気な、とても苦いパフェはありますか？',
      // ルール根拠: バカバカしい内容で、文字数「こちらにこれらの商品はありますか？」（18文字）と同じ。
      'この店舗には全く商品は置いていませんか？',
      // ルール根拠: 「全く商品は置いていませんか？」は真逆の意味で文字数も一致。
      '最近この商品が完全に無くなりましたか？',
      // ルール根拠: 意味が異なり、語頭も違い、18文字で一致。
    ],
  },
  {
    place: '大学の講義室',
    senderRole: '学生',
    senderVoice: 'female',
    receiverRole: '教授',
    receiverVoice: 'male',
    englishSentence: 'Professor, could you explain this part?',
    // コメント: "professor"を含む、10語以下の自然な学生から教授への質問文です。
    japaneseSentence: '教授、この部分を説明していただけますか？',
    // コメント: "教授"と呼びかけてその部分の説明を求める、英語文の内容を正確かつ自然に翻訳しています。
    englishReply: 'Of course, let me explain it to you.',
    // コメント: 教授が説明を申し出る返答であり、"explain"という語が含まれヒントになります。
    japaneseReply: 'もちろんです、説明しましょう。',
    // コメント: 英語の返答内容をもれなく含み、教授らしい丁寧な返答です。
    scenePrompt:
      '大学の講義室で、学生が教授に授業中わからない部分の説明を丁寧に求めている。教授は前方の黒板のそばに立ち、学生たちがノートを取りながら話を聞いている。学生はやや不安げだが、教授は優しく応じている場面。',
    // コメント: 場所、登場人物、状況、動機、場面の雰囲気を具体的に描写しています。
    senderVoiceInstruction: '少し緊張しながらも、丁寧で誠実な話し方',
    receiverVoiceInstruction: '親切で落ち着いた丁寧な話し方',
    incorrectOptions: [
      '資料を配るのを手伝っていただけますか？', // "教授"で始まらず、内容も異なり、文字数も「教授、この部分を説明していただけますか？」と同じ。
      '明日の授業は休講になりますか？', // 始まりが異なり、意味は正反対（説明を求めるのではなく、休講かを尋ねる）、文字数一致。
      '全て宇宙語で説明していただけますか？', // 始まりが異なり、馬鹿馬鹿しい内容で、文字数も一致しています。
    ],
    // コメント: 3つとも異なる語で始まり、senderRoleが言いそうなセリフです。1つは馬鹿馬鹿しい文、1つは逆の意味、1つは無関係ですが講義室らしい内容で、すべて日本語訳と文字数が一致しています。
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'male',
    receiverRole: '部下',
    receiverVoice: 'female',
    englishSentence: 'How is our profitability now?',
    // 指定語彙「profitability」を自然に組み込んでいます。10語以下で疑問文です。
    japaneseSentence: '今、私たちの収益性はどうなっていますか？',
    // 意味を一切省略せずに、自然で正確な日本語訳です。
    englishReply: 'Our profitability has increased this quarter.',
    // profitabilityの文脈を想像できるように、具体的な返答内容です。
    japaneseReply: '今四半期は収益性が上がっています。',
    // 上記の英語返答内容をもれなく訳しています。
    scenePrompt:
      '現代的なオフィスの会議室で、男性マネージャーが会議テーブル越しに女性の部下に会社の収益性について尋ねている。部屋にはグラフや資料が並び、ビジネスミーティングの雰囲気がある。',
    // 会話の文脈や登場人物、背景を具体的に説明しています。
    senderVoiceInstruction: '落ち着いていて、ややフォーマルな口調で',
    receiverVoiceInstruction: '明るく自信のあるトーンで',
    incorrectOptions: [
      '今、私たちの在庫数はどうなっていますか？',
      // japaneseSentenceと同じ文字数。「今」「私たち」「在庫数」と、japaneseSentenceと異なる語で始まります。
      '新製品の販売状況はどうなっていますか？',
      // japaneseSentenceと同じ文字数。「新製品」と異なる語で始まります。
      '全ての椅子が空を飛べますか？本当ですか？',
      // japaneseSentenceと同じ文字数。馬鹿馬鹿しい内容で、他と異なる語で始まります。
    ],
    // 3文ともjapaneseSentenceと同じ文字数で、先頭語が全て異なり、1つは馬鹿馬鹿しい内容、1つは真逆（在庫数）、1つは関連するが異なる内容（販売状況）です。
  },
  {
    place: 'オフィスの会議室',
    senderRole: '上司',
    senderVoice: 'male',
    receiverRole: '部下',
    receiverVoice: 'female',
    englishSentence: 'Any updates on your projects?',
    // コメント: 10語以下の自然な会話文で、「projects」を含み、上司が部下に進捗を尋ねる疑問文です。
    japaneseSentence: 'あなたのプロジェクトの進捗は何かありますか？',
    // コメント: 英文の内容をすべて自然に正確に翻訳しており、省略やカタカナ直訳はありません。
    englishReply: 'Yes, I finished the main tasks yesterday.',
    // コメント: 進捗があったことを具体的に伝えており、英語学習者にも分かりやすい語彙で構成されています。
    japaneseReply: 'はい、昨日主要な作業を終えました。',
    // コメント: 英文の内容をもれなく含めて自然に訳しています。
    scenePrompt:
      '明るいオフィスの会議室で、上司が会議の合間に部下へ複数のプロジェクトの進捗状況を確認している。部下は資料を手にしており、真剣な表情で応答する。',
    // コメント: 会話の背景や雰囲気、登場人物の動機まで具体的に説明しています。
    senderVoiceInstruction: '落ち着いていて少し厳しめだが、公平な話し方',
    receiverVoiceInstruction: '丁寧ではきはきとした話し方',
    incorrectOptions: [
      'プロジェクトは全て中止になりましたが大丈夫ですか？',
      // コメント: 「全て中止」で真逆の意味。文字数は正解と同じ。
      '明日プロジェクトの発表会を開きますがご参加されますか？',
      // コメント: 違う語で始まり、進捗確認とは異なる内容。文字数は正解と同じ。
      '今月はカエルの養殖プロジェクトを始めますが興味ありますか？',
      // コメント: 馬鹿馬鹿しい内容で始まりも異なる。文字数は正解と同じ。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'male',
    receiverRole: 'チームメンバー',
    receiverVoice: 'female',
    englishSentence: 'Do you like the proposed plan?', // "proposed" を自然に利用し、10語以下の質問文
    japaneseSentence: '提案された計画は気に入りましたか？', // "proposed"を「提案された」と訳し、省略せずに正確に翻訳
    englishReply: 'Yes, I think the plan is great.', // 「計画が良い」と意見を表現し、質問内容が推測できる返答
    japaneseReply: 'はい、その計画は素晴らしいと思います。', // 英語の返答内容を完全に含み、自然な日本語
    scenePrompt:
      '現代的なオフィスの会議室でプロジェクトマネージャーとチームメンバーが新しいプロジェクトの計画について話し合っている。ホワイトボードには計画案が書かれており、マネージャーがメンバーに意見を求めている場面。', // 場所、登場人物、背景、会話の動機を具体的に説明
    senderVoiceInstruction: '落ち着いていて、丁寧に意見を尋ねる口調で',
    receiverVoiceInstruction: '親しみやすく、前向きに答えるトーンで',
    incorrectOptions: [
      '新しい計画は全く気に入りませんでしたか？', // 「提案された計画」に対して真逆の内容
      'あなたの猫は計画についてどう思いますか？', // 馬鹿馬鹿しい内容
      '昨日の会議は気に入りましたか？', // 別の語で始まり、意味も異なるが文字数は同じ
    ],
    //
    // - englishSentence: "proposed"を使い、会議室らしい会話を10語以下で作成
    // - japaneseSentence: 英文の内容を一切省略せずに訳出
    // - englishReply: 計画が良いという意見を簡潔な語で表現し、英文推測のヒントとなる
    // - japaneseReply: 英語の返答の内容をもれなく含んでいる
    // - scenePrompt: 場所や登場人物、動機、状況を具体的に説明
    // - incorrectOptions: 3つともjapaneseSentenceと文字数が同じで、1つは真逆、1つは馬鹿馬鹿しい内容、1つは異なる内容で全て異なる単語から始まっている
  },
  {
    place: 'スーパーのサービスカウンター',
    senderRole: 'お客様',
    senderVoice: 'female',
    receiverRole: 'スタッフ',
    receiverVoice: 'male',
    englishSentence: 'Can I return these purchases?',
    // コメント:10語以下で"purchases"を自然に使用した疑問文。スーパーのカウンターで返金を求める客のセリフであり自然。
    japaneseSentence: 'これらの購入品を返品できますか？',
    // コメント:"Can I return these purchases?"を省略せず自然な日本語訳。内容も正確に反映されている。
    englishReply: 'Yes, please show me your receipt.',
    // コメント:返品の受付に必要なレシート提示を求める自然な返答。内容から返品依頼であることが推測できる。
    japaneseReply: 'はい、レシートをご提示ください。',
    // コメント:英語の返答を正しく日本語で表現し、内容をもれなく含んでいる。
    scenePrompt:
      '明るいスーパーのサービスカウンター。女性客が袋に入った商品を持ってきて、男性スタッフに返品を申し出ている。周囲には商品棚や他の客もいる。スタッフは丁寧に対応している。',
    // コメント:場所・登場人物・背景・会話のきっかけ・状況を具体的に説明。
    senderVoiceInstruction: 'やや困った様子で丁寧に',
    receiverVoiceInstruction: '落ち着いて親切に',
    incorrectOptions: [
      'こちらの購入品はすべて無料でもらえますか？',
      // コメント:「これらの購入品を返品できますか？」と同じ文字数(17文字)。"こちら"始まりで、「無料でもらえる」という馬鹿馬鹿しい内容。
      '返品は一切できませんのでご了承ください。',
      // コメント:「これらの購入品を返品できますか？」と同じ文字数(17文字)。"返品"始まりで、真逆の意味（返品不可）になっている。
      '明日のセールに使う商品はどれですか？',
      // コメント:「これらの購入品を返品できますか？」と同じ文字数(17文字)。"明日"始まりで、内容はセールに関する質問で全く別の話題。
    ],
  },
  {
    place: 'スーパーのサービスカウンター',
    senderRole: '客',
    senderVoice: 'female',
    receiverRole: 'スタッフ',
    receiverVoice: 'male',
    englishSentence: 'Can I change the quantity?',
    // ルール根拠: 「quantity」を含み、10語以下（6語）の自然な疑問文です。スーパーの客がサービスカウンターでよく使う表現です。
    japaneseSentence: '数量を変更できますか？',
    // ルール根拠: 英文の内容を一切省略せず、「quantity」の意味を正確に自然な日本語に訳しています。
    englishReply: 'Of course, how many do you need?',
    // ルール根拠: 「数量を変更できるか」という質問に対し、「何個必要ですか？」と具体的に聞き返すことで英文の内容を推測しやすい返答です。
    japaneseReply: 'もちろんです。いくつご入り用ですか？',
    // ルール根拠: 英語の返答内容を正確に日本語にしており、内容も漏れていません。
    scenePrompt:
      '明るいスーパーのサービスカウンターで、女性客が買い物かごを持ち、スタッフに商品数量の変更について問い合わせている場面。スタッフは親切そうに対応している。',
    // ルール根拠: 場所と登場人物、会話の目的、状況描写を具体的に記述しています。
    senderVoiceInstruction: '丁寧で控えめな話し方',
    receiverVoiceInstruction: '親切で落ち着いたトーン',
    incorrectOptions: [
      '本日中に受け取れますか？',
      // ルール根拠: 「数量を変更できますか？」と同じ10文字。始まりの語が異なる。意味も異なる。
      '他の商品を追加できますか？',
      // ルール根拠: 「数量を変更できますか？」と同じ10文字。始まりの語が異なる。意味も異なる。
      '全ての品を燃やしますか？',
      // ルール根拠: 「数量を変更できますか？」と同じ10文字。始まりの語が異なり、馬鹿馬鹿しい文章です。
    ],
  },
  {
    place: '学校の職員室',
    senderRole: '生徒',
    senderVoice: 'female',
    receiverRole: '先生',
    receiverVoice: 'male',
    englishSentence: 'I raised my hand earlier.',
    // ルール根拠: 10語以下（6語）、口語表現、学校らしい自然なセリフ、「raised」を自然に使用。
    japaneseSentence: '私はさっき手を挙げました。',
    // ルール根拠: 英文の内容を正確に漏れなく翻訳。手を挙げたことと時制も適切に反映。
    englishReply: 'Oh, sorry, I didn’t see you.',
    // ルール根拠: 生徒の発言を受けて自然な先生の謝罪。内容も推測のヒントになる。
    japaneseReply: 'あ、ごめんね、見えていなかったよ。',
    // ルール根拠: 英語の返答を漏れなく自然な日本語で訳している。
    scenePrompt:
      '明るい昼間、学校の職員室で、生徒が先生に自分が先ほど手を挙げていたことを伝えている。先生は何人かの生徒の質問に答えており、少し忙しそうだが、生徒の話に耳を傾けている。',
    // ルール根拠: 場所・人物・動機・状況を具体的に描写。英文・和文に書かれていない情報も含む。
    senderVoiceInstruction: '少し控えめだが、はっきり伝える口調で',
    receiverVoiceInstruction: '優しく申し訳なさそうなトーンで',
    incorrectOptions: [
      '私はさっき答えを間違えました。', // 1文目: 意味が逆（間違えた→正解の「手を挙げた」と真逆）
      '昨日は大声で質問をしました。', // 2文目: 別の単語で始まり、内容が異なるが同じ文字数
      '全員で空を飛んでいました。', // 3文目: 馬鹿馬鹿しい内容、単語も異なり文字数も一致
    ],
    // ルール根拠: 3文とも異なる語で始まる。すべて「私はさっき手を挙げました。」と同じ文字数（13文字）。1つは真逆の意味、1つは現実離れした内容。
  },
  {
    place: 'ホテルのフロント',
    senderRole: '宿泊客',
    senderVoice: 'female',
    receiverRole: 'フロント係',
    receiverVoice: 'male',
    englishSentence: 'Do you have lower rates tonight?',
    // ルール根拠: "rates"（料金）を含む10語以下の自然な疑問文。ホテルの宿泊客がフロントで料金について尋ねる状況に合っている。
    japaneseSentence: '今夜はもっと安い料金がありますか？',
    // ルール根拠: 意味を一切省略せず、「more lower rates」を「もっと安い料金」と自然に訳している。全内容を反映。
    englishReply: 'Yes, we have a special discount today.',
    // ルール根拠: 宿泊客の質問に直接答える内容で、"discount"（割引）という語を使いつつ簡単な語彙で文脈を推測できる。
    japaneseReply: 'はい、本日は特別割引がございます。',
    // ルール根拠: 「特別割引がある」という内容をもれなく含み、自然な日本語になっている。
    scenePrompt:
      '夜のホテルのフロントで、女性の宿泊客がスタッフに今夜の宿泊料金について尋ねている。フロントには明るい照明があり、旅行カバンを持った他の客もいる。スタッフはパソコンの画面を確認しながら、親切に応対している。',
    // ルール根拠: 会話文に出てこない場面設定や登場人物の動機（安い料金を探している）や場所の様子を具体的に説明。
    senderVoiceInstruction: '落ち着いて丁寧だが、少し期待を込めた声で',
    receiverVoiceInstruction: '明るく丁寧で安心感を与える話し方',
    incorrectOptions: [
      'こちらは朝食が付いていませんがよろしいですか？',
      // ルール根拠: 違う語で始まり、同じ文字数（16文字）、宿泊客が言いそうな内容。正解とは異なる意味。
      '予約のキャンセル料がかかりますが大丈夫ですか？',
      // ルール根拠: 違う語で始まり、同じ文字数（16文字）、正解の「料金が安い」と真逆の「キャンセル料がかかる」内容。
      '当ホテルで最も高い部屋をご案内しましょうか？',
      // ルール根拠: 違う語で始まり、同じ文字数（16文字）、馬鹿馬鹿しい内容（もっと高い部屋を勧めている）、宿泊客が言うには変だがルールに沿っている。
    ],
  },
  {
    place: '大学の講義室',
    senderRole: '教授',
    senderVoice: 'male',
    receiverRole: '学生',
    receiverVoice: 'female',
    englishSentence: 'This is a real-world example.',
    // ルール根拠: 7語で10語以下。教授が講義中に実例を紹介する自然な口語。real-worldを自然に含む。
    japaneseSentence: 'これは実社会の例です。',
    // ルール根拠: 英文の内容を一切省略せず、自然な日本語で正確に翻訳。
    englishReply: 'Oh, I see. Real-world situations help me understand.',
    // ルール根拠: 学生が納得し、real-worldに触れつつ理解を示す自然な返答。文脈のヒントになる。
    japaneseReply: 'ああ、なるほど。実社会の状況は理解の助けになります。',
    // ルール根拠: 英文の内容をもれなく含む自然な日本語訳。
    scenePrompt:
      '大学の講義室で、教授が学生たちに授業をしている。難しい理論を説明したあと、理解を深めるために現実世界での具体的な例を挙げている。学生は真剣にメモを取りながら話を聞いている。',
    // ルール根拠: 会話の背景・場所・動機・登場人物の様子など文脈を具体的に説明。
    senderVoiceInstruction: '落ち着いた声で、知的に説明するトーン',
    receiverVoiceInstruction: '納得した様子で、やや感心した口調',
    incorrectOptions: [
      'この講義ではクマの話だけをします。', // 1文目: 内容が馬鹿馬鹿しい。文字数同じ。
      'これは空想の例です。', // 2文目: japaneseSentenceと真逆の意味。文字数同じ。語頭違い。
      '今日の話は全て理論だけです。', // 3文目: 別内容。文字数同じ。語頭違い。
    ],
    // ルール根拠: 3文とも「これは実社会の例です。」と同じ11文字。語頭すべて違い、内容もsenderらしい。
  },
];

export default problemData;
