import { SeedProblemData } from '../src/types/problem';

/**
 * 問題データ 26
 * Generated by GPT API (3 problems)
 */
const problemData: SeedProblemData[] = [
  {
    place: 'フードコート',
    senderRole: 'フードコートの店員',
    senderVoice: 'female',
    receiverRole: 'お客さん',
    receiverVoice: 'male',
    englishSentence: 'We’re about to run out of dessert.',
    japaneseSentence: 'デザートがもうすぐ売り切れそうです。',
    englishReply: 'Thanks for letting me know. I’ll order now.',
    japaneseReply: '教えてくれてありがとうございます。今注文します。',
    scenePrompt:
      'ショッピングモールのフードコート。夕方で混み合い始め、人気のデザートが残り少なくなってきたため、女性店員がお客さんに早めの注文を促している。',
    senderVoiceInstruction: '親しみやすく、気づかいのある優しい口調で伝える。',
    receiverVoiceInstruction: '丁寧かつ前向きな雰囲気で、すぐ注文する意思を伝える。',
    incorrectOptions: [
      '本日はデザートのご用意は一切ありません。', // 真逆
      'トナカイだけが注文できるデザートです。', // 馬鹿馬鹿しい
      '他のスイーツも人気ですのでお早めに。',
    ],
  },
  {
    place: 'リハビリ室',
    senderRole: '理学療法士',
    senderVoice: 'male',
    receiverRole: '患者',
    receiverVoice: 'female',
    englishSentence: 'Don’t put off your rehabilitation exercises.',
    japaneseSentence: 'リハビリ運動は後回しにしないでくださいね。',
    englishReply: 'I understand. I’ll make it a habit.',
    japaneseReply: 'わかりました。習慣にします。',
    scenePrompt:
      'リハビリ室で理学療法士が患者に、回復のためにリハビリ運動を毎日実施することの大切さを優しく伝えている。',
    senderVoiceInstruction: '親切で励ますようなトーンで、寄り添う気持ちを込めて。',
    receiverVoiceInstruction: '前向きかつ決意を込めて返事をする。',
    incorrectOptions: [
      '今日から運動は全部やめましょう。', // 真逆
      'サボテンも一緒にリハビリできますよ。', // 馬鹿馬鹿しい
      'ストレッチを終えたらお声かけください。',
    ],
  },
  {
    place: '商店街の通り',
    senderRole: 'イベントスタッフ',
    senderVoice: 'female',
    receiverRole: '通行人',
    receiverVoice: 'male',
    englishSentence: 'Today’s admission fee is complimentary.',
    japaneseSentence: '本日は入場料が無料となっています。',
    englishReply: 'Oh, that’s nice! I’ll check it out.',
    japaneseReply: 'それはうれしいですね。ちょっと見てみます！',
    scenePrompt:
      '商店街の特設会場でチャリティーイベントがあり、スタッフが通行人に入場無料を明るく案内している。',
    senderVoiceInstruction: '明るく親しみやすく、イベントへの参加を促すトーンで。',
    receiverVoiceInstruction: '興味を持ち、軽やかな感じで返事をする。',
    incorrectOptions: [
      '今日は入場料が通常より高くなっています。', // 真逆
      'カバだけが無料で入場できますよ。', // 馬鹿馬鹿しい
      'パンフレットは会場入口で配布しています。',
    ],
  },
];

export default problemData;
