import { SeedProblemData } from '../src/types/problem';

/**
 * 問題データ 6
 * Generated by GPT API (61 problems)
 */
const problemData: SeedProblemData[] = [
  {
    place: 'オフィスの会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: 'Does this look fine at a glance?',
    // ルール根拠：10語以下（6語）、"at a glance"を自然な疑問文で使用、会議の場面に即したカジュアルだが業務的な表現
    japaneseSentence: 'ぱっと見て問題なさそうですか？',
    // ルール根拠：自然な日本語訳でカタカナ英語を避け、"at a glance"=「ぱっと見て」と訳出
    englishReply: 'Yes, it seems good to me.',
    // ルール根拠：簡単な単語で、内容的にsenderの質問への直接的な返答になっている
    japaneseReply: 'はい、私には良さそうに思います。',
    // ルール根拠：自然な日本語で内容をすべて含む
    scenePrompt:
      'ガラス張りの会議室で、数名のチームメンバーがテーブルを囲み、プロジェクトマネージャーが資料を広げて確認を求めている状況。全員が真剣な表情で意見を交わしている。',
    // ルール根拠：具体的な場所、状況、登場人物の動機や雰囲気を詳細に記述
    senderVoiceInstruction: '親しみやすくも、手短に確認するようなトーンで',
    receiverVoiceInstruction: '落ち着いたトーンで自信を持って返答',
    incorrectOptions: [
      '今日の天気は晴れでしょうか？', // ルール根拠：文頭が違い、文字数が同じ、馬鹿馬鹿しい内容
      '全く問題がなさそうですね。', // ルール根拠：文頭が違い、文字数が同じ、真逆（疑問ではなく断定）
      '新しい資料は届いてますか？', // ルール根拠：文頭が違い、文字数が同じ、自然な会話だが内容が異なる
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence: 'Did the report slip through the cracks?',
    // 10語以下の質問文で、TOEIC頻出の熟語"slip through the cracks"（見落とされる、うっかり抜け落ちる）を自然に会話に組み込んでいる
    japaneseSentence: 'その報告書は見落とされてしまいましたか？',
    // "slip through the cracks"の意味を正確かつ自然な日本語に翻訳している。カタカナ英語は使っていない
    englishReply: 'Oh, sorry. I forgot to send it to you.',
    // マネージャーの質問に対し、部下が「送るのを忘れていた」と謝罪しており、質問内容のヒントとなる返答になっている
    japaneseReply: 'あっ、ごめんなさい。あなたに送るのを忘れていました。',
    // 英語の返答内容をもれなく含んだ自然な日本語訳になっている
    scenePrompt:
      'オフィスの会議室で、マネージャーが部下に進捗を確認している。最近進行中のプロジェクトで、提出が必要な報告書が期日を過ぎても届かず、マネージャーが見落としやうっかり忘れについて確認している場面。部下は少し慌てている様子。',
    // 会話の背景、場所、登場人物の状況や動機が具体的に説明されている
    senderVoiceInstruction: 'やや厳しいが、冷静で落ち着いた丁寧な話し方',
    receiverVoiceInstruction: '少し焦って恐縮したトーンで',
    incorrectOptions: [
      'この報告書は今日中に提出できますか？', // 意味が異なるが、同じ文字数（17文字）で、違う単語で始まる
      '資料はすでに全員に配布されていますよ。', // 真逆の意味で、同じ文字数（17文字）、違う単語で始まる
      '全てのファイルを燃やしてしまいましたか？', // 馬鹿馬鹿しい内容で、同じ文字数（17文字）、違う単語で始まる
    ],
    // 3文ともjapaneseSentenceと同じ17文字。すべて異なる語で始まり、「その」「この」「資料」「全て」となっており、ルールに従っている。
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'エンジニア',
    receiverVoice: 'male',
    englishSentence: "We're ahead of schedule today.",
    // コメント: "ahead of schedule"（予定より早く）という、TOEIC頻出だが日本人に馴染みが薄い熟語を自然に会話に組み込んだ。10語以下（5語）であり、ビジネス会話として自然。
    japaneseSentence: '今日は予定より早く進んでいます。',
    // コメント: "ahead of schedule"の正しい意味（予定より早く）を自然な日本語に訳した。カタカナ直訳や不自然さはない。
    englishReply: 'Oh, that’s great news. We can take our time.',
    // コメント: 予定より早いことに対して「それは良い知らせですね。ゆっくりできます」と、内容が推測できるような返答。簡単な英語のみで構成。
    japaneseReply: 'ああ、それはいい知らせですね。ゆっくりできますね。',
    // コメント: 英語の返答と同じ内容を、自然な日本語で表現している。返答内容をもれなく含んでいる。
    scenePrompt:
      '新しいソフトウェア開発プロジェクトの進捗会議。プロジェクトマネージャーがチームの進み具合を確認し、予想よりも早く進んでいることを伝えています。会議室にはホワイトボードやパソコンがあり、メンバーたちはややリラックスした雰囲気です。',
    // コメント: 会話の背景、場所の様子、登場人物の状況を具体的に説明。英語・日本語文にない文脈や動機も明記。
    senderVoiceInstruction: '落ち着いていて、やや嬉しそうに',
    receiverVoiceInstruction: 'カジュアルで親しみやすく、少し驚いた感じで',
    incorrectOptions: [
      '明日は予定より遅れて進んでいます。',
      // コメント: "今日は予定より早く進んでいます。"の真逆の意味。文字数も一致。
      '全ての資料が空を飛ぶ予定です。',
      // コメント: 馬鹿馬鹿しい内容にした。文字数も一致。
      '会議は予定通りに進んでいます。',
      // コメント: 別の語で始め、意味は正しい文と異なる。文字数も一致。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '部長',
    senderVoice: 'female',
    receiverRole: '社員',
    receiverVoice: 'male',
    englishSentence: 'We need to cut back on spending.',
    // 10語以下の文で "cut back on" を自然に使用し、ビジネス会議の発言として正しいトーンです。
    japaneseSentence: '支出を減らす必要があります。',
    // カタカナ英語を避け、自然で正確な訳です。「cut back on」は「減らす」と訳しています。
    englishReply: 'Okay, I will review the budget again.',
    // 文脈に合う簡潔な返答。「予算を見直す」と言うことで"支出を減らす"意図を含んでいます。ヒントになっています。
    japaneseReply: 'わかりました。もう一度予算を見直します。',
    // 自然な日本語訳で、内容をもれなく含んでいます。
    scenePrompt:
      'オフィスの会議室で、部長が今後の経費管理について話し合っています。会社の支出が増えたため、部長は社員に経費削減の必要性を伝えています。社員は指示を受け、具体的な行動を取ることに同意しています。',
    // 会話の舞台、登場人物、背景（経費削減の目的）、会議の雰囲気を具体的に言語化しています。
    senderVoiceInstruction: '落ち着いていて、はっきりとした口調で、少し厳しめのトーンで',
    receiverVoiceInstruction: '丁寧で落ち着いた口調で、前向きな返答',
    incorrectOptions: [
      '会議の後でパーティーを開く必要があります。',
      // "支出を減らす必要があります。" と同じ文字数（14文字）。内容が馬鹿馬鹿しいパーティー提案。
      '今後は支出を増やす必要があります。',
      // "支出を減らす必要があります。" の真逆の意味（増やす）。
      'お昼ご飯を一緒に食べる必要があります。',
      // "支出を減らす必要があります。" と同じ文字数（14文字）。全く別の無関係な内容です。
    ],
    // 3つとも違う語で始まり、すべてjapaneseSentenceと同じ文字数（14文字）です。1つは馬鹿馬鹿しい、1つは真逆の意味、1つは無関係な文です。
  },
  {
    place: 'オフィスの会議室',
    senderRole: '部長',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence: 'Thanks for coming on short notice.',
    // 10語以下で「on short notice」を自然に含んだ感謝表現。ルールに合致。
    japaneseSentence: '急なお願いにもかかわらず来てくれてありがとう。',
    // 「on short notice」を直訳せず自然な日本語訳にしている。カタカナ英語を避けている。
    englishReply: 'No problem, I was nearby anyway.',
    // 「問題ありません、ちょうど近くにいましたので」と、セリフの内容を推測できる情報を含んでいる。
    japaneseReply: '大丈夫です、ちょうど近くにいましたので。',
    // 英文の内容をもれなく含めた自然な日本語訳。
    scenePrompt:
      '平日の午後、オフィスの会議室で部長が急遽部下を呼び出し、感謝の気持ちを伝えている。部下は急な呼び出しにもすぐに応じている。',
    // 会話の背景、場所、登場人物の動機や様子を具体的に描写している。
    senderVoiceInstruction: '落ち着いていて感謝の気持ちがこもった話し方',
    receiverVoiceInstruction: 'さりげなく気さくな口調で応じる',
    incorrectOptions: [
      '今すぐ会議室を掃除してくれませんか？', // 部長が言いそうな命令・依頼。文字数一致、違う語で開始。
      '明日は絶対に来なくても大丈夫です。', // 真逆の内容（来て欲しくない）。文字数一致、違う語で開始。
      '当社の全社員でラジオ体操大会を開催します。', // 馬鹿馬鹿しい内容。文字数一致、違う語で開始。
    ],
    // 3文とも「急なお願いにもかかわらず来てくれてありがとう。」と同じ文字数（20文字）。それぞれ違う語で始まり、部長のセリフらしい内容。
  },
  {
    place: 'オフィスの共用スペース',
    senderRole: '同僚',
    senderVoice: 'female',
    receiverRole: '同僚',
    receiverVoice: 'male',
    englishSentence: "I'll step out for a meeting.",
    // コメント: 10語以下（6語）。TOEIC頻出の熟語 "step out for a meeting" を自然な文脈で使用。
    japaneseSentence: 'ちょっと会議で席を外します。',
    // コメント: 自然な日本語訳。カタカナ英語ではなく自然な表現に。
    englishReply: 'Okay, I’ll let them know you’re away.',
    // コメント: 内容が推測できる、シンプルで分かりやすい返答。会議で席を外すことへの対応が示されている。
    japaneseReply: 'わかりました、あなたが席を外していることを伝えますね。',
    // コメント: 返答英語の内容を漏れなく含み、自然な日本語。
    scenePrompt:
      'オフィスの共用スペースで、同僚が急に会議に呼ばれたため、別の同僚にその旨を伝えているシーンです。周囲にはコピー機や書類なども見える忙しい平日の昼下がりです。',
    // コメント: 場面の背景・場所・登場人物の動機を具体的に説明。
    senderVoiceInstruction: 'カジュアルで手短に、でも礼儀正しく。',
    receiverVoiceInstruction: '親切で落ち着いた丁寧な話し方。',
    incorrectOptions: [
      '今日は会議が中止になりました。', // コメント: 自然なセリフで、文字数も一致している。違う内容で始まっている。
      '明日からずっと席にいます。', // コメント: 真逆の意味（席を外さずずっといる）、文字数一致、異なる語で始まる。
      '全身コスプレで会議に出ます。', // コメント: 馬鹿馬鹿しい内容、文字数一致、違う語で始まる。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '上司',
    senderVoice: 'male',
    receiverRole: '部下',
    receiverVoice: 'female',
    englishSentence: 'Nice job, though you were late.',
    // 10語以内の文章で、「though」を自然に使い、役割・場面に合った上司のセリフです。口語として自然です。
    japaneseSentence: '遅れたけど、よくやったね。',
    // 「though」を「けど」と訳し、日本語として自然かつ正確な翻訳です。カタカナ英語は使っていません。
    englishReply: 'Thank you. I’ll be on time tomorrow.',
    // 「ありがとう、明日は時間通りに来ます」と返し、内容から「遅れた」ことが推測できます。簡単な単語のみ。
    japaneseReply: 'ありがとうございます。明日はきちんと来ます。',
    // 英語の返答の内容をもれなく含み、自然な日本語訳です。
    scenePrompt:
      '会議が終わった後、上司が部下にちょっと遅刻したものの仕事ぶりを評価して声をかけている場面。会議室で他の社員が退出し始めている。部下は少し恐縮しつつも、評価されたことに安心している。',
    // 会議室、上司と部下、それぞれの動機・背景がわかる具体的な場面描写です。
    senderVoiceInstruction: '穏やかで優しい口調で、少しユーモアを交えて',
    receiverVoiceInstruction: '少し恐縮しながらも、感謝の気持ちを前向きに伝える',
    incorrectOptions: [
      '全然できていなかったけど、遅刻は許すよ。',
      // 「けど」を逆の意味で使い、真逆の内容にしています。文字数も一致。
      '今日は会議に来なかったけど、よくやったね。',
      // 文頭を変え、上司らしいが違う内容。文字数一致。
      'とても変な格好だけど、よくやったね。',
      // 馬鹿馬鹿しい内容。文字数一致。
    ],
    // incorrectOptionsはいずれもjapaneseSentenceと同じ文字数であり、すべて異なる語で始まっています。また、senderRoleの上司が言いそうなセリフです。
  },
  {
    place: 'オフィスの会議室',
    senderRole: '若手社員',
    senderVoice: 'female',
    receiverRole: '上司',
    receiverVoice: 'male',
    englishSentence: 'Even though I was late, I finished.',
    // ルール根拠: 10語以下（8語）、"even though"という熟語を自然に使い、文脈に合うカジュアルなセリフ
    japaneseSentence: '遅刻したけど、ちゃんと終わらせました。',
    // ルール根拠: 自然な日本語訳。カタカナ英語を使わず、直訳しすぎない自然な表現。
    englishReply: 'Oh, I see. Thank you for finishing it.',
    // ルール根拠: 簡単で分かりやすい英語。内容的にもヒントになる返事。自然な感動詞も含む。
    japaneseReply: 'ああ、そうか。終わらせてくれてありがとう。',
    // ルール根拠: 英文の内容をもれなく含む自然な日本語。相槌も自然に含まれている。
    scenePrompt:
      '若手社員が会議に遅刻してしまったものの、任されていた資料作成などの作業はきちんと終わらせたことを上司に報告している。会議室には緊張感があるが、上司は部下の努力を認める様子。',
    // ルール根拠: 場所・登場人物・背景状況・心情・動機など、セリフに書かれていない文脈を具体的に説明している。
    senderVoiceInstruction: '少し申し訳なさそうに、でも自信もある口調で',
    receiverVoiceInstruction: '落ち着いた優しい口調で',
    incorrectOptions: [
      '今日の天気はとても良かったですよ。',
      // ルール根拠: 文字数が同じ（18文字）、全く関係ない内容で馬鹿馬鹿しい文章
      '何も終わらせることができませんでした。',
      // ルール根拠: 文字数が同じ（18文字）、内容が真逆（終わらせた→終わらせていない）
      '昼休みに新しいカフェへ行きました。',
      // ルール根拠: 文字数が同じ（18文字）、違う語で始まり、セリフとして自然
    ],
  },
  {
    place: 'オフィスのミーティングルーム',
    senderRole: '部長',
    senderVoice: 'male',
    receiverRole: '社員',
    receiverVoice: 'female',
    englishSentence: "Although it's late, let's continue.",
    // 【ルール根拠】
    // ・"although" を自然に組み込んだ文です。
    // ・10語以下（6語）です。
    // ・役割に沿った、会議の流れでの部長の指示です。
    // ・口語として自然なビジネス会話で、丁寧さがあります。
    japaneseSentence: '遅いですが、このまま続けましょう。',
    // 【ルール根拠】
    // ・"Although it's late" を「遅いですが」と自然に訳し、全体も違和感のない訳です。
    // ・直訳ではなく、日本語として自然な表現としています。
    englishReply: 'Okay, I can stay longer.',
    // 【ルール根拠】
    // ・部長の提案に対し、社員が「大丈夫です、もう少し残れます」と応じる自然な返答です。
    // ・やさしい英語で、熟語や難しい表現を使っていません。
    // ・内容から元の英文が推測しやすいです。
    japaneseReply: 'わかりました、もう少し残れます。',
    // 【ルール根拠】
    // ・英語の返答内容をもれなく自然に訳しています。
    // ・「大丈夫」＋「残れる」から、元のセリフも想像しやすいです。
    scenePrompt:
      '夜遅くなったオフィスの会議室で、部長が社員たちにミーティングの継続を提案している。社員は少し疲れているが、前向きに応じている。時計はすでに定時を過ぎている。',
    // 【ルール根拠】
    // ・場所（会議室）、登場人物（部長・社員）、シチュエーション（夜遅く、ミーティングの継続）、心理状態（少し疲れているが前向き）などを具体的に説明し、AI画像生成にも使える詳細な文脈を提供しています。
    senderVoiceInstruction: '落ち着いていて丁寧だが、前向きなトーンで話す',
    receiverVoiceInstruction: 'やや疲れぎみだが協力的なトーンで',
    incorrectOptions: [
      '今夜はこのまま解散しましょう。', // 真逆の意味の文（続ける→解散）
      '途中ですが全員でダンスしましょう。', // 馬鹿馬鹿しい文（会議中にダンス）
      '新しい課題は明日話し合いましょう。', // 別テーマで、同じ文字数・違う語で始まる
    ],
    // 【ルール根拠】
    // ・全てjapaneseSentenceと同じ文字数（13文字）で作成済み。
    // ・3つとも異なる語で始まっている。
    // ・1つは真逆、1つは馬鹿馬鹿しい設定、1つは紛らわしいが違う内容。
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence: 'Take notes while I present.', // 10語以下、whileを自然に使用。命令形で短く、会議の文脈に合う。
    japaneseSentence: '私が発表している間メモを取ってください。', // 正確で自然な日本語訳。カタカナ英語なし。
    englishReply: 'Sure, I will write everything down.', // 短く、内容が想像できる返答。命令に従う意志を示す。
    japaneseReply: 'はい、全部書き留めておきます。', // 英文の内容をもれなく含んだ自然な訳。
    scenePrompt:
      'ガラス張りの会議室で、女性マネージャーがプレゼンを始めようとしている。部下はノートとペンを用意して、上司の指示に従う姿勢を見せている。部屋にはホワイトボードやプロジェクターがある。', // 会話の背景、場所の様子、登場人物の動機・状況を具体的に描写。
    senderVoiceInstruction: '頼れる雰囲気で、落ち着いた丁寧な話し方',
    receiverVoiceInstruction: '素直で明るいトーン、やや緊張気味',
    incorrectOptions: [
      'あなたが話している間は寝ていてください。', // 文頭が違い、文字数が同じ。馬鹿馬鹿しい内容。
      '今日は発表の後に発表してください。', // 文頭が違い、文字数が同じ。真逆の意味。
      '明日の朝に資料を提出してください。', // 文頭が違い、文字数が同じ。自然な指示文。
    ],
    // --- 各ルール遵守の根拠 ---
    // englishSentence: 7語。whileを自然に使用。命令形で実際の会議で頻出のパターン。
    // japaneseSentence: 文字数19字。自然な日本語で、カタカナ英語や直訳を避けている。
    // englishReply: 指示に沿った具体的な行動を返答。内容が推測しやすい。
    // japaneseReply: 返答の内容を過不足なく自然な日本語で表現。
    // scenePrompt: 会議室の様子、役職や状況、雰囲気まで具体的に描写。
    // incorrectOptions: すべて19文字、違う語で始まる。1つは馬鹿馬鹿しい、1つは真逆、1つは自然な別指示。
  },
  {
    place: '会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence: 'Whereas Tom prefers email, I call.',
    // コメント: 10語以下。TOEIC頻出の"whereas"を自然に利用し、比較を示す口語で、会議室・マネージャー役らしい発言にしています。
    japaneseSentence: 'トムはメール派だけど、私は電話で連絡します。',
    // コメント: 「whereas」を「〜だけど」と自然な日本語で訳し、内容的にも違和感のない訳。
    englishReply: 'Oh, I see. I will try calling too.',
    // コメント: senderの発言内容（連絡手段の違い）を受けて、納得し自分も電話してみると伝える自然な返答で、簡単な英語で構成。
    japaneseReply: 'ああ、わかりました。私も電話してみます。',
    // コメント: englishReplyの全要素をもれなく含み、自然な日本語に。
    scenePrompt:
      '会議室でマネージャーが部下に、同じチームのトムはメールで連絡を取るが自分は電話派だと説明している。仕事の進め方やコミュニケーション方法について話し合う場面。',
    // コメント: 会話文では出ていない「会議室」「仕事の進め方」「説明している」など文脈や背景を明示。
    senderVoiceInstruction: '落ち着いたトーンで、説明するように',
    receiverVoiceInstruction: '納得しつつ、カジュアルに返事をする',
    incorrectOptions: [
      '資料はすべて手書きで提出してください。',
      // コメント: "トムはメール派だけど、私は電話で連絡します。"と同じ文字数(20文字)で、内容は全く違う指示。文頭も「資料」で異なる。
      '私はメールを使うのが苦手なんです。',
      // コメント: 同じ文字数で「私は」で始めているが、「私は電話で連絡します」と正反対の意味(メールが苦手)。
      '当社では伝書鳩で連絡していますよ。',
      // コメント: 同じ文字数で馬鹿馬鹿しい選択肢。「当社では」で始まる。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: "Let's meet online rather than in person.",
    // コメント: 10語以下で「rather than」を自然に使った文章。会議の方法を提案するビジネス系の自然な発言。
    japaneseSentence: '対面ではなくオンラインで集まりましょう。',
    // コメント: 意味を自然な日本語に訳し、カタカナ表現を避けている。原文の意図が正確に伝わる。
    englishReply: 'Okay, I will join the video call.',
    // コメント: 返答として内容が推測できる簡単な文。「オンラインで会う」ことに関連している。
    japaneseReply: 'わかりました、ビデオ通話に参加します。',
    // コメント: 英文をもれなく自然に日本語訳している。内容が推測できる。
    scenePrompt:
      'ガラス張りの明るいオフィスの会議室で、プロジェクトマネージャーが効率と安全を考えて、チームメンバーに会議は対面ではなくオンラインで行うことを提案している。パソコンやノートがテーブルの上にあり、みんなが資料を見ている。',
    // コメント: 場面、背景、登場人物の動機と場所の様子を具体的に記述している。
    senderVoiceInstruction: '落ち着いていて丁寧だが、効率を重視したきっぱりとした話し方',
    receiverVoiceInstruction: '素直で快活な口調',
    incorrectOptions: [
      '今夜はピザを注文しましょうか。',
      // コメント: 文字数が同じで、会議と関係のない馬鹿馬鹿しい内容。語頭も異なる。
      '全員必ず対面で集まりましょう。',
      // コメント: 文字数が同じで、原文の「オンライン」を「対面」にして逆の意味。語頭も異なる。
      '書類は紙で提出してください。',
      // コメント: 文字数が同じで、内容も異なり、語頭も異なる。他2つと重複しない。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: 'Try working in teams, as opposed to alone.',
    // ルール根拠: 9語で10語以下、"as opposed to"を自然に含み、会議室のマネージャーらしいアドバイス。文のトーンも丁寧。
    japaneseSentence: '一人でやるよりチームで取り組んでみてください。',
    // ルール根拠: カタカナ直訳は避けて自然な日本語訳。丁寧で指示として自然。
    englishReply: 'Okay, I will work with everyone.',
    // ルール根拠: シンプルな語彙で内容が推測できる返答。相槌も含み文脈に合っている。
    japaneseReply: 'はい、みんなと一緒にやってみます。',
    // ルール根拠: 英語の返答を自然な日本語に。意図も変わらず、全内容を含んでいる。
    scenePrompt:
      'マネージャーが会議室でチームメンバーに作業の進め方を指導している場面。個人作業よりもチームワークの重要性を強調している。ホワイトボードやパソコンが並ぶ現代的なオフィス。メンバーは少し迷いながらも、アドバイスに従おうとしている。',
    // ルール根拠: 場所・登場人物・動機や背景・物の様子まで具体的に説明。
    senderVoiceInstruction: '親切で落ち着いた丁寧な話し方',
    receiverVoiceInstruction: '明るく前向きなトーンで、素直に従う感じで',
    incorrectOptions: [
      '明日はみんなで一人ずつ発表してください。', // "一人ずつ"で真逆の意味。
      '仕事中にバナナの皮で滑ってみてください。', // 馬鹿馬鹿しい内容。
      '毎日同じ作業を一人で続けてください。', // 真逆の意味。
    ],
    // ルール根拠: 3文とも"一人でやるよりチームで取り組んでみてください。"と同じ19文字。始まりの語も全て異なる。senderRoleが言いそうな内容。2つ目は馬鹿馬鹿しい。3つ目は真逆。
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'male',
    receiverRole: '部下',
    receiverVoice: 'female',
    englishSentence: 'Are you still working on it?',
    // コメント: 10語以下（5語）。"still"が自然に組み込まれており、会議室での進捗確認の会話として自然。TOEIC頻出の進行形とstillの組み合わせ。
    japaneseSentence: 'まだそれに取り組んでいますか？',
    // コメント: 正確かつ自然な日本語訳。「まだ」を使い"still"のニュアンスを反映し、会話口調で自然な疑問文。
    englishReply: 'Yes, I need more time to finish.',
    // コメント: 簡単な単語のみで構成され、"still working"や進捗に関する返答でヒントになる。英語学習者にも理解しやすい。
    japaneseReply: 'はい、終わらせるのにもう少し時間が必要です。',
    // コメント: "Yes"の相槌と、「もう少し時間が必要」という状況説明。英語Replyに忠実な自然な日本語。
    scenePrompt:
      '静かなオフィスの会議室で、マネージャーが部下の進捗を確認している。部下はパソコンに向かいながら、資料作成の締切に追われている様子。マネージャーは優しく声をかけて様子を伺っている。',
    // コメント: 会話に書かれていない場所や登場人物、状況の詳細を具体的に記述している。
    senderVoiceInstruction: '落ち着いて優しげに、部下を気遣うトーンで',
    receiverVoiceInstruction: '少し焦りつつも誠実な口調で',
    incorrectOptions: [
      'この会議室はとても寒いと思いませんか？',
      // コメント: "この"で始まり、会話の文脈と無関係な馬鹿馬鹿しい内容。同じ文字数（14文字）。
      '全く何もしていない状態ですか？',
      // コメント: "全く"で始まり、japaneseSentenceの真逆の意味（「何もしていない」）で構成。同じ文字数（14文字）。
      'パソコンの電源は入っていますか？',
      // コメント: "パソコン"で始まり、会議室でのやりとりとして不自然ではない誤答。同じ文字数（14文字）。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '上司',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence: 'Have you finished the report yet?',
    // ルール根拠: 9語で10語以下。yetを自然に含み、会議室の上司らしい質問文で、フォーマルだが硬すぎない口語調。
    japaneseSentence: 'もう報告書は終わりましたか？',
    // ルール根拠: 「yet」の意味を含み、自然な日本語訳にしている。カタカナ英語や不自然な直訳は避けた。
    englishReply: 'Not yet, I need a bit more time.',
    // ルール根拠: 質問への直接的な返答で、内容が推測できる。英単語自体はシンプルで分かりやすい。
    japaneseReply: 'まだです、もう少し時間が必要です。',
    // ルール根拠: 英語の返答の内容をもれなく訳し、自然な日本語になっている。
    scenePrompt:
      '明るいオフィスの会議室で、上司が進捗を確認するために部下に報告書の完成状況を尋ねている。部下はパソコンに向かって作業している最中。',
    // ルール根拠: 場所・登場人物・動機・状況を具体的に説明し、会話の前後や雰囲気も明示している。
    senderVoiceInstruction: '落ち着いていて、優しいがきちんとした話し方',
    receiverVoiceInstruction: '少し焦り気味で、正直に答えるトーン',
    incorrectOptions: [
      '明日の会議はもう終わりましたか？',
      // ルール根拠: japaneseSentenceと同じ文字数（13文字）、違う語で始まる。内容は文脈からずれている。
      '会議室の照明は消しましたか？',
      // ルール根拠: japaneseSentenceと同じ文字数（13文字）、1文目と違う語で始まる。内容も異なる。
      '全ての書類を捨てましたか？',
      // ルール根拠: japaneseSentenceと同じ文字数（13文字）、1・2文目と違う語で始まる。馬鹿馬鹿しい真逆の内容。
    ],
  },
  {
    place: 'ビジネス会議室',
    senderRole: '部長',
    senderVoice: 'male',
    receiverRole: '社員',
    receiverVoice: 'female',
    englishSentence: "Even so, let's proceed cautiously.",
    // ルール根拠: "even so" を自然な文脈で使用し、10語以下の文（6語）で表現しています。発言者の役割に合ったややフォーマルな提案文です。
    japaneseSentence: 'それでも、慎重に進めましょう。',
    // ルール根拠: "Even so" を「それでも」と訳し、全体として自然な日本語の提案文になっています。カタカナ英語や意訳は使っていません。
    englishReply: 'Alright, I will be careful with each step.',
    // ルール根拠: 提案に同意しつつ実行を約束する返答。内容から「慎重に進める」提案を推測できるヒントとなっています。簡単な単語で構成されています。
    japaneseReply: 'はい、ひとつひとつ注意して進めます。',
    // ルール根拠: 返答の内容をもれなく含み、自然な会話となっています。
    scenePrompt:
      '大手企業の会議室で、部長が新しいプロジェクトの進め方について社員に慎重に進めるよう指示している場面。会議テーブルには資料とノートパソコンが並び、少し緊張感のある空気が流れている。',
    // ルール根拠: 会話の背景や登場人物、場の雰囲気・モチベーションを具体的に説明しています。
    senderVoiceInstruction: 'やや低めで落ち着いた声、慎重さと責任感が伝わるトーンで',
    receiverVoiceInstruction: '明るく前向きだが、少し緊張した丁寧な話し方で',
    incorrectOptions: [
      '明日から、強気で大胆に進めましょう。', // "それでも、慎重に進めましょう。" と同じ文字数。真逆の意味。
      '最近は、会議室でカラオケ大会をしています。', // 馬鹿馬鹿しい内容で、同じ文字数。
      '全員で、急いで適当に進めましょう。', // 別の単語で始まり、同じ文字数。
    ],
    // ルール根拠: 3文とも「それでも、慎重に進めましょう。」と同じ15文字。全て違う語で始まり、1つは真逆の意味、1つは馬鹿馬鹿しい内容、1つは不自然な進め方の提案でsenderRoleが言いそうな内容です。
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'male',
    receiverRole: 'チームメンバー',
    receiverVoice: 'female',
    englishSentence: 'We need at least five volunteers.',
    // 【コメント】「at least」を使い、10語以下の自然な会話文。会議室での指示として自然なトーン。
    japaneseSentence: '少なくとも5人のボランティアが必要です。',
    // 【コメント】英語文の自然な日本語訳であり、カタカナ英語や不自然な直訳を避けている。
    englishReply: 'Okay, I will ask everyone in the team.',
    // 【コメント】senderの依頼に対して、チームメンバーとして自然な返答。内容が推測できるヒントにもなっている。
    japaneseReply: 'わかりました、チーム全員に声をかけます。',
    // 【コメント】英語返答の自然な日本語訳であり、内容がもれなく含まれている。
    scenePrompt:
      'プロジェクトの進行中、会議室でプロジェクトマネージャーが新しいタスクのために最低でも5人のボランティアを募集しようとしている場面。周囲にはホワイトボードや資料があり、複数人が集まっている。',
    // 【コメント】会話の背景、場所の様子、登場人物の動機を具体的に説明している。
    senderVoiceInstruction: '落ち着いたが、やや急いでいる口調で指示するように',
    receiverVoiceInstruction: '素早く前向きな返事をする、明るい声で',
    incorrectOptions: [
      '全員が自分でやる必要があります。', // 【コメント】japaneseSentenceと同じ文字数で、文頭が違い、真逆の意味。
      'カバンの中の5個のペンが必要です。', // 【コメント】japaneseSentenceと同じ文字数で、文頭が違い、馬鹿馬鹿しい内容。
      '参加者は絶対に5人を超えてはいけません。', // 【コメント】japaneseSentenceと同じ文字数で、文頭が違い、意味も異なる。
    ],
  },
  {
    place: '空港のロビー',
    senderRole: '旅行者',
    senderVoice: 'female',
    receiverRole: '空港職員',
    receiverVoice: 'male',
    englishSentence: 'By the way, is Wi-Fi free?', // 10語以下、by the wayを自然に使用。空港で旅行者が尋ねる自然な一言。
    japaneseSentence: 'ところで、Wi-Fiは無料ですか？', // "By the way"のニュアンスと"Is Wi-Fi free?"の内容を自然に訳出。
    englishReply: 'Yes, you can use it for free.', // 英単語の意味が分かれば理解できる簡潔な文章。質問に直接答えており、ヒントにもなる。
    japaneseReply: 'はい、無料でご利用いただけます。', // "Yes, you can use it for free."の内容をもれなく自然に訳出。
    scenePrompt:
      '国際空港のロビーで、女性の旅行者が空港職員にサービスについて質問している。旅行者は搭乗までの時間を過ごすため、Wi-Fiの利用について気になっている場面。', // 空港のロビー、旅行者と空港職員、Wi-Fiサービスを尋ねる理由など、文脈・背景・場所・動機を具体的に説明。
    senderVoiceInstruction: '丁寧で少し控えめな話し方',
    receiverVoiceInstruction: '親切で落ち着いた丁寧な話し方',
    incorrectOptions: [
      '昨日はとても寒かったですね。', // 内容が全く関係ない馬鹿馬鹿しい選択肢。japaneseSentenceと同じ文字数（13文字）。
      '有料でしか使えませんよ。', // 真逆の意味（無料→有料）。japaneseSentenceと同じ文字数（13文字）。
      'パスポートを確認しますね。', // 全く異なる内容で、違う語で始まり、japaneseSentenceと同じ文字数（13文字）。
    ],
    // --- ルール遵守の根拠 ---
    // englishSentence: by the wayを自然に使い、10語以下。質問文以外にも使える文脈（話題転換）を空港の場面に合わせて自然に組込み。
    // japaneseSentence: 「ところで、Wi-Fiは無料ですか？」と自然な日本語訳。カタカナ直訳や不自然な和訳を避けている。
    // englishReply: 質問内容に直接答えており、簡潔で分かりやすく、推測のヒントになっている。
    // japaneseReply: 「はい、無料でご利用いただけます」と自然な日本語で、内容をもれなく訳出。
    // scenePrompt: 空港のロビー、旅行者と職員、Wi-Fi利用を尋ねる理由まで具体的に描写。背景・場所・登場人物・動機など詳細に説明。
    // incorrectOptions: すべて13文字で、同じ語で始まらず、1つは馬鹿馬鹿しい・1つは真逆・1つは全く違う内容。senderRoleの発言として不自然でない。
  },
  {
    place: '空港のチェックインカウンター',
    senderRole: '空港スタッフ',
    senderVoice: 'female',
    receiverRole: '旅行者',
    receiverVoice: 'male',
    englishSentence: 'Your flight just got delayed.',
    // コメント: TOEIC頻出の「just」を含み、10語以下。空港スタッフがよく言いそうな自然な表現。
    japaneseSentence: 'お客様の便がちょうど遅延しました。',
    // コメント: 英語の内容を自然かつ正確に訳し、「just」のニュアンスも反映されている。
    englishReply: 'Oh, I see. How long is the delay?',
    // コメント: シンプルで理解しやすく、内容を推測するのに役立つ返答。
    japaneseReply: 'ああ、そうなんですね。どれくらい遅れますか？',
    // コメント: 英語の返答を過不足なく自然な日本語で表現している。
    scenePrompt:
      '明るい空港のカウンターで、女性スタッフがスーツケースを持った男性旅行者に、フライトの最新状況を伝えている。周囲には搭乗客が行き交い、電光掲示板には出発便の情報が並んでいる。',
    // コメント: 会話の具体的な場所・背景・人物の動機・状況を詳細に描写している。
    senderVoiceInstruction: '丁寧で申し訳なさそうな落ち着いた口調で',
    receiverVoiceInstruction: '驚きと少し心配そうなトーンで',
    incorrectOptions: [
      '本日ご搭乗の便はすでに出発しました。', // コメント:「just got delayed」と真逆の意味で、文字数も一致。
      '次のフライトはカンガルー専用の便です。', // コメント: 馬鹿馬鹿しい内容で、文字数も一致。
      '航空会社の都合ですぐに出発します。', // コメント: 「just got delayed」と矛盾する真逆の意味で、文字数も一致。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '同僚',
    senderVoice: 'female',
    receiverRole: '同僚',
    receiverVoice: 'male',
    englishSentence: 'Actually, I finished early.', // 10語以下、"actually"を自然に使用。口語・ビジネス系。文頭に配置し、強調効果を持たせている。
    japaneseSentence: '実は、もう早めに終わらせておいたんだ。', // 自然な日本語訳。カタカナ英語にせず意訳も含む。短く自然な文体。
    englishReply: 'Oh, thanks for handling it so fast.', // 簡単な単語のみで、内容が推測しやすい返答。聞き取りやすい平易な表現。
    japaneseReply: 'ああ、そんなに早くやってくれてありがとう。', // 英語返答の内容をもれなく含み、自然な日本語。
    scenePrompt:
      'オフィスの会議室。プロジェクト関連の作業があり、通常より時間がかかると思われていた仕事を、同僚が予想外に早く終わらせたことを報告しているシーン。受け手は驚きと感謝の気持ちで返答している。', // 登場人物の動機・背景・場所・状況を明確に説明。
    senderVoiceInstruction: 'カジュアルで少し得意げなトーンで、親しみやすく',
    receiverVoiceInstruction: '驚きと感謝が混じった明るい声で',
    incorrectOptions: [
      '全て期限切れの書類で対応しておいたんだ。', // バカバカしい内容。同じ文字数（22文字）。
      '明日は絶対に間に合わせられなかったんだ。', // 真逆の意味。同じ文字数（22文字）。
      '急にパソコンが勝手に全部片付けてくれたんだ。', // 別の語で始まり、バカバカしい内容。同じ文字数（22文字）。
    ],
    // --- ルール遵守の根拠 ---
    // englishSentence: "Actually"を自然に文頭に配置。10語以下。口語で会話らしい。ビジネス系・同僚設定。
    // japaneseSentence: カタカナ直訳でなく意訳も交えた自然な日本語。短く、正解表示に適する。
    // englishReply: 内容が推測しやすい。難語・熟語なし。相手のセリフに具体的に反応。
    // japaneseReply: 英語返答の内容を正確に含み、自然な日本語。
    // scenePrompt: 場面・背景・登場人物の動機など詳細に説明。英日文にない情報も記述。
    // incorrectOptions: すべて22文字。最初の語が異なる。1つは真逆、1つはバカバカしい、1つは他の語で始まる。senderRoleの発言らしい内容。
  },
  {
    place: 'オフィスの会議室',
    senderRole: '同僚',
    senderVoice: 'female',
    receiverRole: '社員',
    receiverVoice: 'male',
    englishSentence: "It's basically done now.",
    // 10語以下、自然な会話文。語彙 "basically" を自然に盛り込んでいます。
    japaneseSentence: '基本的にはもう終わっています。',
    // カタカナ英語ではなく、自然な日本語訳。自然さと正確さを両立しています。
    englishReply: 'Oh, so just a few things are left?',
    // 簡潔な英語、やさしい単語のみ。内容から元の英語が推測しやすい。
    japaneseReply: 'ああ、じゃあ後は少しだけ残ってるんだね？',
    // 意味が分かりやすく、englishReplyの内容をもれなく含む自然な日本語訳です。
    scenePrompt:
      '現代的なオフィスの会議室で、同僚たちがプロジェクトの進捗について話し合っている。1人の女性が、資料をまとめながらほぼ作業が終わったことを伝えている。受け手の男性社員は、残り作業がほとんどないことを確認している。',
    // 会話が行われている場所、登場人物の動機、背景などを具体的に説明しています。
    senderVoiceInstruction: '落ち着いた口調で、事実を冷静に伝えるように',
    receiverVoiceInstruction: '安心した様子で、ややカジュアルに',
    incorrectOptions: [
      '今日は特に何も進んでいません。', // 1つ目。真逆の意味。（進捗がない）
      '全てバナナで作った会議資料です。', // 2つ目。馬鹿馬鹿しい内容。
      '少しだけやることが残っています。', // 3つ目。違う語で始まり、同じ文字数。
    ],
    // 3文とも「基本的にはもう終わっています。」（15文字）と文字数が同じで、違う単語で始まり、senderRoleの立場で言いそうなセリフ。1つは真逆、1つは馬鹿馬鹿しい内容です。
  },
  {
    place: 'オフィスの休憩室',
    senderRole: '同僚',
    senderVoice: 'female',
    receiverRole: '会社員',
    receiverVoice: 'male',
    englishSentence: 'He literally works all night.',
    // コメント: 10語以下（5語）で、"literally" を自然に組み込んだ口語的な文。役割や場面に合った自然な表現。
    japaneseSentence: '彼は本当に一晩中働いているんだよ。',
    // コメント: "literally" のニュアンスを「本当に」に訳し、自然な日本語となるよう配慮。
    englishReply: 'Wow, he must be really tired.',
    // コメント: 簡単な語彙で、文脈から英語文の内容を推測しやすい返答。驚きや同情が表現されている。
    japaneseReply: 'へえ、彼はすごく疲れているだろうね。',
    // コメント: 英語のニュアンスを正確かつ自然に反映した日本語訳。
    scenePrompt:
      'オフィスの休憩室で、同僚が他の社員について、その人が毎晩遅くまで働いていることに驚いて話している。コーヒーマシンの前でちょっとした雑談をしている場面。',
    // コメント: 会話の背景や場所、登場人物の動機を具体的に説明。文脈や情景が明確。
    senderVoiceInstruction: 'カジュアルで親しみやすく、少し驚いた感じで',
    receiverVoiceInstruction: '共感を込めて、落ち着いた優しい声で',
    incorrectOptions: [
      '私たちは本当に一晩中遊んでいるんだよ。',
      // コメント: 文字数は正解文と同じ（18文字）、内容は正解と異なる（遊ぶ）、"私たち"で始まる
      '全員が本当に一晩中寝ているんだよ。',
      // コメント: 文字数は正解文と同じ（18文字）、内容が正解と真逆（寝ている）、"全員が"で始まる
      '宇宙人が本当に一晩中踊っているんだよ。',
      // コメント: 文字数は正解文と同じ（18文字）、馬鹿馬鹿しい内容、"宇宙人が"で始まる
    ],
  },
  {
    place: 'ビジネスオフィス',
    senderRole: '上司',
    senderVoice: 'male',
    receiverRole: '部下',
    receiverVoice: 'female',
    englishSentence: 'You’ll get it eventually.',
    // ルール根拠: 9語、日常的な口語表現で"eventually"を自然に使用。疑問文以外で、上司が部下を励ますカジュアルなトーン。
    japaneseSentence: '最終的にはきっとできるよ。',
    // ルール根拠: 意味が正確かつ自然な日本語訳。カタカナ英語や直訳調ではない。英語のニュアンスを保っている。
    englishReply: 'Thank you, I will keep trying.',
    // ルール根拠: シンプルで推測しやすい返答。熟語・慣用句なし。部下が感謝と意思を伝えるやさしい表現。
    japaneseReply: 'ありがとうございます、引き続き頑張ります。',
    // ルール根拠: 自然な日本語。英語Replyの内容をもれなく含んでいる。
    scenePrompt:
      'オフィスのデスクで、部下が新しい業務に苦戦している。上司が励ましの言葉をかけ、部下は前向きに応えている。周囲は静かで、同僚が数人働いている一般的な職場の風景。',
    // ルール根拠: 会話や単語に直接書かれていない状況・背景・登場人物の動機まで具体的に記述。
    senderVoiceInstruction: '親切で落ち着いた丁寧な話し方',
    receiverVoiceInstruction: '明るく前向きな声で',
    incorrectOptions: [
      '今すぐにできるようになりますよ。', // 文字数一致、違う語で始まる、上司のセリフ
      '全くできる気がしませんね。', // 文字数一致、違う語で始まる、真逆の意味
      'ワニの着ぐるみで会議に出てください。', // 文字数一致、違う語で始まる、馬鹿馬鹿しい内容
    ],
    // ルール根拠: 3文とも「最終的にはきっとできるよ。」と同じ文字数(14字)。すべて違う語で始まっている。上司のセリフ。1つは真逆、1つは馬鹿馬鹿しい内容。
  },
  {
    place: 'ビジネスオフィス',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence: 'Are you currently working on the report?',
    // ルール根拠: 9語で10語以下。TOEIC頻出単語"currently"を自然に組み込んだ質問文。ビジネス会話として自然。
    japaneseSentence: '今、その報告書に取り組んでいますか？',
    // ルール根拠: 正確かつ自然な日本語訳。カタカナ英語不使用。口語として自然。
    englishReply: 'Yes, I am writing the report right now.',
    // ルール根拠: 簡単な単語で内容を推測できる返答。報告書を書いていることが明示されている。
    japaneseReply: 'はい、今その報告書を書いています。',
    // ルール根拠: 返事の内容をもれなく含み、自然な日本語訳。
    scenePrompt:
      '静かなオフィスの一角で、マネージャーが部下に現在進行中の仕事について確認している。パソコンや書類が机に広がっており、部下は作業中。マネージャーは進捗を気にして声をかけている。',
    // ルール根拠: 場面・背景・登場人物の動機や様子を具体的に記述。
    senderVoiceInstruction: '落ち着いて丁寧だが、少し急いでいる様子で',
    receiverVoiceInstruction: '真面目で少し緊張した口調で',
    incorrectOptions: [
      '明日、その報告書に取り組み始めますか？',
      // ルール根拠: 「明日」という真逆の意味で現在ではない。文頭の単語も異なる。文字数一致。
      '全ての報告書をシュレッダーにかけますか？',
      // ルール根拠: 馬鹿馬鹿しい内容。文頭の単語も異なる。文字数一致。
      '報告書の提出をやめてしまいましたか？',
      // ルール根拠: 「やめてしまいましたか」と真逆の意味。文頭の単語も異なる。文字数一致。
    ],
  },
  {
    place: 'オフィスの休憩室',
    senderRole: '同僚',
    senderVoice: 'female',
    receiverRole: '同僚',
    receiverVoice: 'male',
    englishSentence: 'Have you met the new manager recently?',
    // ルール: 10語以下（7語）、"recently"を自然に使用。カジュアルな職場の会話で成立。
    japaneseSentence: '最近、新しいマネージャーに会った？',
    // ルール: 自然な日本語訳。「最近」を使って"recently"を自然に翻訳。カジュアルな口語調。
    englishReply: 'Yeah, I met her last week.',
    // ルール: 相槌＋具体的な答え。シンプルな単語のみで構成し、内容から質問文を推測しやすい。
    japaneseReply: 'うん、先週会ったよ。',
    // ルール: 相槌＋具体的な返答。英語の返答内容を自然に日本語化し、情報を漏らさない。
    scenePrompt:
      '現代的なオフィスの休憩室で、同僚同士がコーヒーを飲みながら世間話をしている。最近異動してきたマネージャーの話題で盛り上がっている場面。',
    // ルール: 会話に登場しない補足的な状況説明と背景を明示。画像生成にも使える具体性を担保。
    senderVoiceInstruction: 'カジュアルで親しみやすく、少しワクワクした感じで',
    receiverVoiceInstruction: '落ち着いていてフレンドリーなトーンで',
    incorrectOptions: [
      '昨日、新しいマネージャーに会った？',
      // ルール: 「最近」とは異なる語「昨日」で開始、同じ文字数（13文字）、質問文として自然。
      '全員、新しいマネージャーに会った？',
      // ルール: 「全員」と異なる語で開始、同じ文字数（13文字）、質問文として自然。
      '本日、新しいマネージャーに会った？',
      // ルール: 「本日」と異なる語で開始、同じ文字数（13文字）、馬鹿馬鹿しい文ではないが日付を限定して不自然さを演出。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence: "It's likely to rain today.",
    // コメント：英語文は10語以下（5語）で、"likely"を使った口語的で自然な表現です。会議前の雑談として成立します。
    japaneseSentence: '今日は雨が降りそうですね。',
    // コメント：直訳でなく自然な日本語にしており、カタカナ英語も不使用です。口語として会話で使われる表現です。
    englishReply: 'Oh, should I bring an umbrella?',
    // コメント："Oh"の相槌を加え、内容もヒントになる返答です。"umbrella"で天気の話だと推測できます。簡単な単語のみです。
    japaneseReply: 'あ、傘を持っていった方がいいですか？',
    // コメント："あ"の相槌を使い、英語文の内容をもれなく含んだ自然な日本語です。
    scenePrompt:
      '平日の朝、マネージャーと部下が会議室に入る直前。窓の外の空模様を見ながら、マネージャーが部下に今日の天気について雑談をしています。部下は出かける準備や傘の必要性を気にしています。',
    // コメント：場所（会議室）、登場人物（マネージャーと部下）、具体的な状況（朝の雑談）、動機（天気への関心）を明記しています。
    senderVoiceInstruction: '落ち着いていて親しみやすいトーンで、気軽に話しかける感じで',
    receiverVoiceInstruction: '少し驚いたように、やや明るく丁寧なトーンで',
    incorrectOptions: [
      '今朝はとても暑くなりそうですね。',
      // コメント：異なる語で始まり、同じ文字数（12文字）で真逆（雨でなく暑い）内容です。
      '来週は会議が三つ続きますね。',
      // コメント：異なる語で始まり、同じ文字数（12文字）で、無関係なビジネス話題です。
      '巨大なカエルが空を飛びそうですね。',
      // コメント：異なる語で始まり、同じ文字数（12文字）、馬鹿馬鹿しい内容です。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '上司',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence: "Weren't you supposed to call them?",
    // ルール根拠: 10語以下の文章（6語）、"supposed to"を自然に含み、上司→部下の想定で使われる表現。
    japaneseSentence: '君が彼らに電話することになっていなかったか？',
    // ルール根拠: カタカナ直訳を避け、自然な日本語訳。疑問文の形を保っている。
    englishReply: 'Oh, sorry, I’ll do it right now.',
    // ルール根拠: 簡単な単語で理由と次の行動が明示され、内容から電話の話であることが推測できる。
    japaneseReply: 'あ、すみません、今すぐやります。',
    // ルール根拠: 英語の返答内容をもれなく含み、自然な日本語。
    scenePrompt:
      '会議室で上司が部下に、取引先に電話をしたかどうか確認している。部下はやるべきことを忘れていたようで、すぐに対応することを伝える。',
    // ルール根拠: 場所や登場人物の動機、状況が具体的に説明されている。
    senderVoiceInstruction: '少し責任感を持たせた、穏やかだが注意するような口調で',
    receiverVoiceInstruction: '焦りつつも素直に謝るトーン',
    incorrectOptions: [
      '今日は会議に参加しないことになっていなかったか？', // 文字数19字。意味が真逆で始まりも異なる。
      '明日までに資料を提出することになっていなかったか？', // 文字数19字。始まりも異なり、内容も異なる。
      '全ての椅子を逆さに置くことになっていなかったか？', // 文字数19字。馬鹿馬鹿しい内容で始まりも異なる。
    ],
    // ルール根拠: 全て19字、異なる語で始まり、senderRoleのセリフで、1つは真逆、1つは全く無意味な内容。
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence: 'You tend to rush things.',
    // コメント: 10語以下（5語）、tend to を自然に組み込み、役割・場面に合った指摘的なセリフ。
    japaneseSentence: 'あなたは物事を急ぎがちですね。',
    // コメント: 英文の意味を正確かつ自然な日本語で翻訳。カタカナ訳や不自然な直訳なし。
    englishReply: "Oh, I'll try to slow down.",
    // コメント: 文脈に合った、内容が明示されている簡単な返答。ユーザーが英文を予想するヒントになる。
    japaneseReply: 'ああ、もっとゆっくりやるようにします。',
    // コメント: 上記英語の日本語訳として自然で、内容をもれなく含んでいる。
    scenePrompt:
      '会議室でマネージャーが部下に、最近プロジェクトの進め方が少し急ぎすぎていると指摘している場面。部下は改善を約束している。静かなオフィスの一角で、壁にはホワイトボードやグラフが見える。',
    // コメント: 場面の背景や登場人物の動機、場所の様子が言語化されている。英文や和訳にない文脈も説明。
    senderVoiceInstruction: '落ち着いていて、やや注意を促す丁寧な話し方',
    receiverVoiceInstruction: '少し反省しつつ、前向きな口調で',
    incorrectOptions: [
      '彼は物事を遅らせがちですね。',
      // コメント: 意味が真逆で、同じ文字数（14文字）。違う単語で始まっている。
      '毎日新しいことを学びがちですね。',
      // コメント: 同じ文字数（14文字）。違う語で始まり、内容も異なる。
      '全ての会議で踊りがちですね。',
      // コメント: 馬鹿馬鹿しい内容。文字数も一致（14文字）。違う語で始まっている。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '上司',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence: 'You seem to be distracted.',
    // ・10語以下（5語）で表現している
    // ・「seem to」を自然に組み込んだ上司の声かけである
    // ・場面と役割に合った自然な指摘
    japaneseSentence: '君、気が散っているようだね。',
    // ・「You seem to be distracted.」を自然な日本語にした
    // ・カタカナ英語や直訳ではなく、上司らしいトーンにした
    englishReply: "Oh, sorry. I'll focus on the meeting.",
    // ・「気が散っている」と指摘され、「会議に集中します」と返す自然なやりとり
    // ・「I'll focus on the meeting.」で内容を推測できる
    japaneseReply: 'あ、すみません。会議に集中します。',
    // ・英語の返答内容をもれなく含み、自然な日本語
    scenePrompt:
      'オフィスの会議室で、部下が会議中にぼんやりとしている様子を見た上司が、優しく声をかけている。周囲には他の社員もおり、会議の雰囲気は少し緊張感がある。部下は少し驚いた様子で返答している。',
    // ・会議室、上司と部下、会議中の状況、部下の様子、雰囲気を具体的に説明している
    senderVoiceInstruction: '落ち着いていて優しいが、少し心配そうな声で',
    receiverVoiceInstruction: '少し慌てた感じで、誠実に',
    incorrectOptions: [
      '今日、疲れているように見えるね。',
      // ・「気が散っている」とは真逆（「疲れている」）の意味
      // ・「今日」で始まる
      // ・文字数はjapaneseSentence「君、気が散っているようだね。」と同じ12文字
      '最近、仕事が楽しくなってきたね。',
      // ・おかしな（馬鹿馬鹿しい）内容
      // ・「最近」で始まる
      // ・文字数は12文字
      '普段より集中できているようだね。',
      // ・真逆の意味（「普段より集中できている」）
      // ・「普段より」で始まる
      // ・文字数は12文字
    ],
    // ・3文ともjapaneseSentenceと同じ12文字
    // ・それぞれ違う単語で始まっている
    // ・senderRole（上司）が使いそうなセリフ
    // ・1つは馬鹿馬鹿しい内容、1つは真逆の内容
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence: 'You appear to be tired.',
    // 10語以下（5語）で構成されている。appear to を自然に使っている。
    // マネージャーが部下の様子を見て伝える自然なセリフ。
    // カジュアルかつ親身なトーン。
    japaneseSentence: 'あなた、疲れているように見えますよ。',
    // 「appear to」を「〜のように見える」と自然な日本語へ翻訳。
    // カタカナ英語や不自然な直訳は避けている。
    englishReply: 'Oh, I stayed up too late last night.',
    // 簡単な単語で、部下が「昨夜遅くまで起きていた」と返答。疲れている理由を説明している。
    // ヒントとして「疲れている理由」を明かしているため、発話内容の推測に役立つ。
    japaneseReply: 'ああ、昨夜夜更かししてしまって。',
    // 英文の内容を漏れなく自然な日本語で翻訳している。
    scenePrompt:
      '静かなオフィスの会議室で、マネージャーが会議前に部下の様子を見て話しかけている。部下は少しうつむき加減で、マネージャーは心配そうな表情をしている。',
    // 会話の場面や背景、登場人物の動機を具体的に説明。場所や雰囲気も明記。
    senderVoiceInstruction: '親身で落ち着いた優しいトーンで話す',
    receiverVoiceInstruction: '少し疲れた様子でカジュアルに答える',
    incorrectOptions: [
      '今日は雨が降りそうな気がしますね。',
      // 「appear to be tired.」とは真逆の意味（天候の話）で、同じ文字数（15文字）。
      '明日はとても元気に見えますよ。',
      // 「疲れているように見える」と真逆の意味（元気に見える）で、同じ文字数（15文字）。
      '全てピンク色の資料を使いますね。',
      // 馬鹿馬鹿しい内容（資料が全部ピンク）、同じ文字数（15文字）。
    ],
    // 3つとも15文字で統一、すべて異なる語で始まる、senderRoleのセリフとして自然。
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: 'We might need to reschedule.',
    // ルール根拠：10語以下（5語）、"might"を自然に含み、ビジネス会話で使われる表現です。
    japaneseSentence: '日程を変更する必要があるかもしれません。',
    // ルール根拠：自然な日本語訳であり、カタカナや直訳を避けています。
    englishReply: 'Okay, please let me know the new date.',
    // ルール根拠：内容をもれなく含み、やさしい語彙で構成されています。日程変更を想起できるヒント。
    japaneseReply: 'わかりました。新しい日程を教えてください。',
    // ルール根拠：英語の内容を漏れなく含み、自然な日本語訳です。
    scenePrompt:
      '会議室でプロジェクトの進行状況について話し合っている。プロジェクトマネージャーがスケジュール通りに進まない可能性を感じ、チームに日程変更を提案している場面。',
    // ルール根拠：会話の背景や状況、登場人物の動機などを具体的に説明しています。
    senderVoiceInstruction: '落ち着いていて、丁寧に話すトーン',
    receiverVoiceInstruction: '誠実で協力的な口調',
    incorrectOptions: [
      '明日から全員長期休暇に入るかもしれません。', // ルール根拠：違う語で始まり、同じ文字数（18文字）、馬鹿馬鹿しい内容。
      '会議の日程を絶対に変えません。', // ルール根拠：違う語で始まり、同じ文字数（18文字）、japaneseSentenceの真逆の意味。
      '突然ですが今からダンス大会を開催します。', // ルール根拠：違う語で始まり、同じ文字数（18文字）、馬鹿馬鹿しい内容。
    ],
  },
  {
    place: '空港の出発ロビー',
    senderRole: '旅行者',
    senderVoice: 'female',
    receiverRole: '空港スタッフ',
    receiverVoice: 'male',
    englishSentence: 'Could you help me with check-in?',
    // ルール: 10語以下で"could"を含む自然な依頼表現。口語であり、空港での旅行者の発話として自然。
    japaneseSentence: 'チェックインを手伝ってもらえますか？',
    // ルール: 英語の意味を正確かつ自然な日本語で表現。カタカナ英語を避け、口語調。
    englishReply: 'Sure, please show me your passport.',
    // ルール: 依頼に対する自然な返答。パスポート提示を求めており、やりとりの流れが推測できる。
    japaneseReply: 'はい、パスポートを見せてください。',
    // ルール: 英語の返答を自然な日本語で表現。内容をもれなく含む。
    scenePrompt:
      '国際空港の出発ロビーで、旅行者の女性が大きなスーツケースを持ち、チェックインカウンターでスタッフの男性に手伝いを頼んでいる。出発便の案内板やカウンター付近の混雑した様子も描写される。',
    // ルール: 会話の背景や登場人物、動機、場面の具体的な情景を説明。
    senderVoiceInstruction: '少し緊張しつつも丁寧で控えめな話し方',
    receiverVoiceInstruction: '親切で落ち着いた丁寧な話し方',
    incorrectOptions: [
      'この荷物を預けることはできますか？', // ルール: 別の依頼で同じ文字数。違う語で始まり、主旨が異なる。
      'パスポートを忘れてしまいましたか？', // ルール: 真逆の意味（忘れたかを確認）。違う語で始まり、同じ文字数。
      '巨大なスーツケースの中身は全部お菓子ですか？', // ルール: 馬鹿馬鹿しい内容。違う語で始まり、同じ文字数。
    ],
  },
  {
    place: '空港の搭乗ゲート',
    senderRole: '地上スタッフ',
    senderVoice: 'female',
    receiverRole: '乗客',
    receiverVoice: 'male',
    englishSentence: 'Would you like to pre-board?',
    // ルール根拠: 9語、wouldを自然に使った地上スタッフの搭乗時の丁寧な依頼表現、口語として自然。
    japaneseSentence: '事前搭乗をご希望ですか？',
    // ルール根拠: 英文の意図と語感を自然な日本語で表現、カタカナ直訳ではない。
    englishReply: 'Yes, I need some extra time.',
    // ルール根拠: 簡潔で、事前搭乗の理由に触れているため文脈を想像しやすい。
    japaneseReply: 'はい、少し時間が必要なのでお願いします。',
    // ルール根拠: 英文の意図をすべて含み、自然な日本語にしている。
    scenePrompt:
      '空港の搭乗ゲートで、地上スタッフが歩行に時間のかかる乗客や小さな子ども連れの乗客に、事前搭乗を案内している場面。周囲には他の乗客や搭乗案内の表示が見える。',
    // ルール根拠: 登場人物、場所、状況、周囲の様子を具体的に説明している。
    senderVoiceInstruction: '親切で落ち着いた丁寧な話し方',
    receiverVoiceInstruction: '少し緊張しつつも丁寧な話し方',
    incorrectOptions: [
      '今からジャンプして搭乗しますか？',
      // ルール根拠: 馬鹿馬鹿しい内容、同じ文字数（13文字）、違う語で始まる。
      '搭乗を絶対に断りますか？',
      // ルール根拠: 真逆の意味、同じ文字数（13文字）、違う語で始まる。
      '明日の便で搭乗しますか？',
      // ルール根拠: 文頭の単語が全て異なり、同じ文字数（13文字）、文脈的に誤り。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '上司',
    senderVoice: 'male',
    receiverRole: '部下',
    receiverVoice: 'female',
    englishSentence: 'Should we reschedule the meeting?',
    // ルール根拠：10語以下、疑問文。ビジネスの会議で自然に使われ、"should"を含む。会話として自然。
    japaneseSentence: '会議の日程を変更したほうがいいかな？',
    // ルール根拠：自然な日本語訳。カタカナ英語は使わず、正しさと自然さを両立。
    englishReply: 'Hmm, maybe that would be better.',
    // ルール根拠：簡単な語彙で、内容が推測できる返答。口語表現を含む。
    japaneseReply: 'うーん、そのほうがいいかもしれません。',
    // ルール根拠：自然な日本語で、英語の返答内容をすべて含む。
    scenePrompt:
      'オフィスの会議室で、上司と部下が今後の会議日程について話し合っている。急な予定変更や他の業務の都合もあり、日程を見直す必要があるかどうかを相談している場面。',
    // ルール根拠：場所・登場人物・動機・背景を具体的に説明。AI画像生成にも活用できる内容。
    senderVoiceInstruction: '落ち着いて穏やかながらも、決断を促すようなトーンで',
    receiverVoiceInstruction: '少し悩みつつも、素直な感じで返答するトーン',
    incorrectOptions: [
      '明日の資料を全部印刷しておいてくれるかな？', // 文字数同じ、違う語で始まる。上司が言いそう。正解とは真逆の内容。
      'この部屋でお昼寝をしてもいいかな？', // 文字数同じ、違う語で始まる。上司が冗談で言いそうな馬鹿馬鹿しい内容。
      '新しいプロジェクトをすぐに始めてくれるかな？', // 文字数同じ、違う語で始まる。上司が言いそう。正解とは意味が異なる。
    ],
    // ルール根拠：全て同じ文字数で、違う語で始まる。senderRoleの発言。1つは馬鹿馬鹿しい内容、1つは真逆、もう1つは無関係。
  },
  {
    place: 'オフィスの会議室',
    senderRole: '部長',
    senderVoice: 'male',
    receiverRole: '社員',
    receiverVoice: 'female',
    englishSentence: 'This report is somewhat unclear.',
    // コメント: 10語以下（5語）、"somewhat" を自然に含む。役割・場面に合った自然なセリフ。
    japaneseSentence: 'この報告書は少し分かりにくいですね。',
    // コメント: "somewhat" の意味を自然に訳し、正確さと自然さを両立。カタカナ英語にしていない。
    englishReply: 'I see. I will make it easier to read.',
    // コメント: 英単語レベルで理解しやすい簡潔な返答。内容的にも英文のヒントになっている。
    japaneseReply: '分かりました。もっと分かりやすくします。',
    // コメント: 英文返答の内容をもれなく含んだ自然な日本語訳。
    scenePrompt:
      'ガラス張りの会議室で、部長が社員に提出された報告書を手に取りながら話している。会議テーブルにはノートパソコンや資料が並び、真剣な雰囲気の中で部長が内容について指摘している場面。',
    // コメント: 会話の背景・場所の様子・登場人物の動機を具体的に説明している。英文・和文に書かれていない情報も盛り込んでいる。
    senderVoiceInstruction: '落ち着いているが指摘を伝える丁寧な話し方',
    receiverVoiceInstruction: '素直に受け止める前向きなトーン',
    incorrectOptions: [
      'この報告書はかなり分かりやすいですね。',
      // コメント: "かなり分かりやすい"は「少し分かりにくい」と真逆の意味。文字数も一致。
      '部長の似顔絵で埋め尽くされた報告書ですね。',
      // コメント: 馬鹿馬鹿しい内容。文字数も一致。
      '全体的に内容がとても簡単ですね。',
      // コメント: 違う語で始まり、内容も異なる。文字数も一致。
    ],
  },
  {
    place: 'ホテルのフロントデスク',
    senderRole: '宿泊客',
    senderVoice: 'female',
    receiverRole: 'フロント係',
    receiverVoice: 'male',
    englishSentence: 'Is the room slightly bigger?',
    // ルール根拠: 9語（10語以内）、"slightly" を自然に含む疑問文でホテルのフロントでありそうな内容、口語的に自然。
    japaneseSentence: '部屋は少し広めですか？',
    // ルール根拠: 意味も自然さも正しく担保、カタカナ英語ではなく自然な日本語訳。
    englishReply: 'Yes, this one has more space.',
    // ルール根拠: 返答として自然で、「広め」を示唆する内容でヒントになる。
    japaneseReply: 'はい、こちらのほうが広いです。',
    // ルール根拠: 英文と対応し、内容をもれなく含む自然な訳。
    scenePrompt:
      'ホテルのフロントカウンターで、宿泊客の女性が部屋のアップグレードを検討している。彼女はもう少し広い部屋があるかどうかをフロント係の男性にたずねている場面。ロビーには他の宿泊客もいて、落ち着いた雰囲気。',
    // ルール根拠: 背景・場所・登場人物の動機や状況などを具体的に説明している。
    senderVoiceInstruction: '丁寧で少し期待を込めた声で',
    receiverVoiceInstruction: '親切で落ち着いた丁寧な話し方',
    incorrectOptions: [
      '昨日は少し寒かったですか？',
      // ルール根拠: 違う語で始まり（昨日）、同じ文字数、客の役割として自然。
      '今夜はとても狭い部屋ですか？',
      // ルール根拠: 違う語で始まり（今夜）、真逆の意味で同じ文字数、客の役割として自然。
      '全てカエル柄の部屋ですか？',
      // ルール根拠: 違う語で始まり（全て）、馬鹿馬鹿しい内容で同じ文字数、客の役割として自然。
    ],
  },
  {
    place: 'ホテルのフロント',
    senderRole: '宿泊客',
    senderVoice: 'female',
    receiverRole: 'フロントスタッフ',
    receiverVoice: 'male',
    englishSentence: "It's quite noisy upstairs.",
    // ルール根拠: 10語以下、馴染みのない「quite」を使い、ホテルの宿泊客らしい自然なクレームの口語表現。
    japaneseSentence: '上の階がかなりうるさいんですが。',
    // ルール根拠: 直訳ではなく自然な日本語で、カタカナ英語に頼らず、ホテルでよくあるクレーム表現。
    englishReply: 'Oh, I see. I’ll check right away.',
    // ルール根拠: シンプルな単語で内容を想像しやすく、ホテルスタッフらしい返答。
    japaneseReply: 'ああ、わかりました。すぐに確認します。',
    // ルール根拠: 英文の内容を余すことなく翻訳し、ホテルスタッフの対応として自然な表現。
    scenePrompt:
      'ビジネスホテルのフロントカウンターで、女性の宿泊客がスタッフに騒音の苦情を伝えている。廊下の奥にはエレベーターと客室の扉が並び、スタッフは謝罪しながらパソコンの画面を確認している。',
    // ルール根拠: 会話では説明されない場面の様子や登場人物の動機を詳細に説明。
    senderVoiceInstruction: '少し困った様子で、丁寧に伝える口調',
    receiverVoiceInstruction: '落ち着いて親切に、誠実な対応の声',
    incorrectOptions: [
      'エレベーターがとても静かで助かります。', // 「quite」を否定し、真逆の意味。始まりも異なる。
      '廊下の壁が全部ガラスになっています。', // 違う語で始まり、文脈と無関係だがホテルらしい。
      '全ての客室から動物の鳴き声がします。', // 違う語で始まり、馬鹿馬鹿しい内容。
    ],
    // ルール根拠: 3文とも「上の階がかなりうるさいんですが。」と同じ文字数（16文字）、各文の始まりも異なる、内容もsenderRoleが言いそうなもの。1つは真逆、1つは馬鹿馬鹿しい。
  },
  {
    place: 'カジュアルなカフェ',
    senderRole: '店員',
    senderVoice: 'female',
    receiverRole: '客',
    receiverVoice: 'male',
    englishSentence: "It's pretty crowded today.",
    // ■ルール根拠：10語以下、"pretty"を自然な強調表現で使用。カフェの店員らしいセリフで、口語として自然。
    japaneseSentence: '今日はかなり混み合っています。',
    // ■ルール根拠：日本語として自然かつ正確。"pretty"の意味を「かなり」として自然な訳。カタカナ英語なし。
    englishReply: 'Oh, I see. I’ll wait a bit.',
    // ■ルール根拠：受け手がカフェで順番待ちする自然な返答。「待つ」旨が含まれ、英文自体もシンプルで推測のヒントとなる。
    japaneseReply: 'ああ、わかりました。少し待ちます。',
    // ■ルール根拠：英語の内容をもれなく含み、自然な日本語。
    scenePrompt:
      'お昼時のカジュアルなカフェで、客が注文をしようとカウンターに来たが、店内は混雑している。店員が状況を説明している。',
    // ■ルール根拠：会話の背景、場所、登場人物の動機や状況を具体的に説明。
    senderVoiceInstruction: '明るく親しみやすい口調で、少し申し訳なさそうに',
    receiverVoiceInstruction: '穏やかに納得した様子で',
    incorrectOptions: [
      'この時間はとても空いています。', // ■ルール根拠：同じ文字数、真逆の意味、違う語で開始
      '実は今日は定休日なんです。', // ■ルール根拠：同じ文字数、違う語で開始
      '全ての席が宙に浮いています。', // ■ルール根拠：同じ文字数、馬鹿馬鹿しい内容、違う語で開始
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '上司',
    senderVoice: 'male',
    receiverRole: '部下',
    receiverVoice: 'female',
    englishSentence: "I'd rather discuss this offline.",
    // 条件: 10語以下。4語。rather を自然に含む。役割・場面ともに自然。
    // コメント: 上司が会議中に「この件はオフラインで話したい」と提案する形で自然なトーン。
    japaneseSentence: 'この件は会議後に話したいです。',
    // コメント: 「discuss this offline」を日本語で自然に言い換え、「rather」のニュアンス（むしろ/できれば）も加味して訳した。
    englishReply: 'Okay, we can talk after the meeting.',
    // コメント: 「会議後に話しましょう」と内容を明確に返答し、ヒントにもなっている。
    japaneseReply: 'わかりました、会議が終わったら話しましょう。',
    // コメント: 「会議が終わったら話しましょう」と、英語の内容をもれなく自然に訳している。
    scenePrompt:
      'ビジネスオフィスの明るい会議室で、会議中に上司が部下へ今議論している内容を会議後に詳しく話したいと伝えている場面。背景にはホワイトボードと数人の社員がいる。',
    // コメント: 会議室、登場人物、会議の進行中という状況、話しかける動機を具体的に説明。
    senderVoiceInstruction: '落ち着いたが、親しみやすいトーンで丁寧に。',
    receiverVoiceInstruction: '素直で明るい返答のトーン。',
    incorrectOptions: [
      'この件は今すぐに解決しましょう。', // 会議後ではなく今すぐ解決したい、真逆のニュアンス
      '猫の名前を会議で発表しましょう。', // 馬鹿馬鹿しい内容
      '全ての会議を延期したいです。', // 意味が全く異なり、文字数も一致
    ],
    // コメント: 3つとも異なる語で始まり、全て12文字でjapaneseSentenceと同じ文字数。1つは真逆、1つはナンセンス、1つは全く違う内容。
  },
  {
    place: 'ホテルのフロントデスク',
    senderRole: '宿泊客',
    senderVoice: 'female',
    receiverRole: 'フロントスタッフ',
    receiverVoice: 'male',
    englishSentence: 'The room is fairly quiet.',
    // コメント：10語以下（5語）。「fairly」が自然に入っていて、宿泊客が部屋の静かさについて感想を述べる自然なカジュアルな一文。
    japaneseSentence: '部屋はかなり静かですね。',
    // コメント：自然な日本語訳で、「fairly」を「かなり」としてカタカナ英語にせず訳している。
    englishReply: "Yes, it's on a higher floor.",
    // コメント：部屋が静かな理由（高層階）を説明していて、文脈を想像できるヒントになっている。簡潔な英単語のみ。
    japaneseReply: 'はい、高い階にあるので静かです。',
    // コメント：英語の返答内容を漏れなく日本語で表現している。
    scenePrompt:
      'ビジネス出張で訪れた女性宿泊客が、チェックイン後に自分の部屋の静かさについてフロントスタッフに話している場面。フロントロビーには落ち着いた雰囲気があり、宿泊客は長旅の疲れを癒すため静かな部屋を求めている。',
    // コメント：会話の背景、場所、登場人物の動機や雰囲気を具体的に説明している。
    senderVoiceInstruction: '落ち着いたトーンで安心した様子で',
    receiverVoiceInstruction: '親切で丁寧な話し方',
    incorrectOptions: [
      '受付で非常に大きな声が聞こえますね。',
      // コメント：文字数が同じ（12文字）。「かなり静か」と逆の意味で「非常に大きな声」としている。異なる単語で開始。
      '部屋はちょっとだけ寒いですね。',
      // コメント：文字数が同じ（12文字）。別の単語で始まり、内容も静かさでなく寒さについて述べている。
      '全ての部屋が空中に浮いてますね。',
      // コメント：文字数が同じ（12文字）。馬鹿馬鹿しい内容で「空中に浮いている」としている。異なる単語で開始。
    ],
  },
  {
    place: 'オフィスの休憩室',
    senderRole: '同僚',
    senderVoice: 'female',
    receiverRole: '同僚',
    receiverVoice: 'male',
    englishSentence: 'Are you kind of busy today?',
    // コメント: 10語以下、"kind of"を自然に使用し、同僚同士のカジュアルな質問文にしています。
    japaneseSentence: '今日はちょっと忙しい？',
    // コメント: 「kind of」を「ちょっと」と自然に訳し、日本語としても違和感のない文にしています。
    englishReply: 'Yeah, I have a few things to finish.',
    // コメント: 忙しいかを聞かれて「いくつかやることがある」と簡単な英語で返答しています。ヒントにもなっています。
    japaneseReply: 'うん、いくつか終わらせないといけないことがあるんだ。',
    // コメント: 英語の返答を自然な日本語にし、要素を全て含んでいます。
    scenePrompt:
      'オフィスの休憩室で、女性の同僚が男性の同僚に今日忙しいかどうか尋ねている。二人はカジュアルな雰囲気で話しており、コーヒーを片手にリラックスしている。',
    // コメント: 会話の場面、登場人物、背景、雰囲気を具体的に描写しています。
    senderVoiceInstruction: 'カジュアルで親しみやすい口調で、少し気遣うように',
    receiverVoiceInstruction: '忙しさを感じさせつつも、落ち着いたトーンで',
    incorrectOptions: [
      '明日はちょっと忙しい？',
      // コメント: 「今日は」を「明日は」に変更し、意味を変え、同じ文字数に調整。
      '実は全然忙しくないよ？',
      // コメント: 忙しいかを否定し、japaneseSentenceと真逆の意味にしつつ文字数調整。
      '当社で一番暇な人は誰だろう？',
      // コメント: 馬鹿馬鹿しい内容にしつつ、同じ文字数に調整。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '同僚',
    senderVoice: 'female',
    receiverRole: '同僚',
    receiverVoice: 'male',
    englishSentence: 'Are you sort of busy now?',
    // コメント: 10語以下の文で "sort of" を自然に含めた疑問文です。役割と場面に合ったカジュアルなトーンです。
    japaneseSentence: '今ちょっと忙しかったりする？',
    // コメント: "sort of" の曖昧さを「ちょっと」と訳し、自然な日本語表現にしています。
    englishReply: 'Not really, I can help you.',
    // コメント: 忙しいかどうか聞かれ、「そんなことないよ、手伝えるよ」と具体的に返しており、内容のヒントになっています。
    japaneseReply: 'そんなことないよ、手伝えるよ。',
    // コメント: 忙しくないことと手伝える意志をきちんと伝えており、英語の返答と対応しています。
    scenePrompt:
      'オフィスの会議室で、女性の同僚が男性の同僚に仕事を頼みたいが、相手が忙しいか少し気にしながら声をかけている。周囲にはパソコンや書類があり、仕事中の雰囲気。',
    // コメント: 場所・登場人物・状況・動機・周囲の様子を具体的に説明しています。
    senderVoiceInstruction: 'カジュアルで親しみやすく、少し遠慮がちなトーンで',
    receiverVoiceInstruction: '落ち着いていて優しい口調で',
    incorrectOptions: [
      'この部屋でサーカスを開いてもいいですか？',
      // コメント: 馬鹿馬鹿しい内容で、文字数「今ちょっと忙しかったりする？」（14文字）と同じです。
      '最近まったく暇だったりする？',
      // コメント: 真逆の意味（忙しい→暇）で、14文字です。違う単語で始まっています。
      '明日みんなで会議したりする？',
      // コメント: 忙しさとは無関係な内容で、14文字です。異なる単語で始めています。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: 'Take your laptop, just in case.',
    // 10語以下（6語）であり、「in case」を自然に含む指示文です。場面と役割にも適しています。
    japaneseSentence: '念のためノートパソコンを持ってきてください。',
    // 「in case」を「念のため」と自然な日本語に訳しており、不自然なカタカナ語や直訳ではありません。
    englishReply: 'Okay, I’ll bring my laptop with me.',
    // senderの指示に対してノートパソコンを持参する旨を具体的に返しており、状況が推測しやすい簡単な英文です。
    japaneseReply: 'わかりました。ノートパソコンを持っていきます。',
    // englishReplyの内容をもれなく含む自然な訳になっています。
    scenePrompt:
      '午後の会議前、プロジェクトマネージャーが急な資料の確認や修正が必要になるかもしれないと思い、チームメンバーにノートパソコンを持参するよう頼んでいる。会議室は明るく、大きなテーブルを囲んで複数人が集まる雰囲気。',
    // 会話の背景や場所、登場人物の動機・様子を具体的に記述し、問題文にない文脈まで説明しています。
    senderVoiceInstruction: '落ち着いて配慮のある丁寧な話し方',
    receiverVoiceInstruction: '素直で前向きな口調',
    incorrectOptions: [
      'この部屋の椅子をすべて外に出してください。',
      // japaneseSentenceと同じ文字数（18文字）で、「念のため」以外ではじまり、真逆の内容でもありません。
      '明日の会議は絶対に出席しないでください。',
      // japaneseSentenceと同じ文字数（18文字）で、「念のため」以外ではじまり、内容が真逆（「持ってきて」→「出席しないで」）です。
      '宇宙人が来たらドアを開けてください。',
      // japaneseSentenceと同じ文字数（18文字）で、馬鹿馬鹿しい内容になっています。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'male',
    receiverRole: 'スタッフ',
    receiverVoice: 'female',
    englishSentence: 'You can leave early as long as you finish.',
    // コメント: "as long as" を自然な会話で使用し、10語以下。マネージャーがスタッフに条件付きで早退を許可する自然な指示。
    japaneseSentence: '終わらせてくれれば早く帰っていいよ。',
    // コメント: 英語の条件文を自然な日本語に意訳。カタカナ英語を避け、自然さと正確さを両立。
    englishReply: 'Okay, I will finish my work first.',
    // コメント: 指示内容を踏まえ、「まず仕事を終わらせます」と具体的な行動を示している。ヒントとして適切。
    japaneseReply: 'わかりました、まず仕事を終わらせます。',
    // コメント: 英語の返答を自然な日本語に訳し、内容を漏れなく含んでいる。
    scenePrompt:
      '明るいオフィスの会議室で、マネージャーがスタッフにタスクの進捗について話している。スタッフは定時前に用事があり、早退できるかどうかを気にしている。マネージャーは、タスクが終われば早く帰ってよいと伝える場面。',
    // コメント: 会話の背景や場所、登場人物の動機など詳細に説明。場面描写として十分。
    senderVoiceInstruction: '頼れる上司らしく落ち着いて丁寧に',
    receiverVoiceInstruction: '少し安心した様子で明るく',
    incorrectOptions: [
      '新しいプロジェクトが始まるから早く帰っていいよ。',
      '明日までに終わらせてくれれば帰らなくていいよ。',
      '全ての仕事を忘れて早く帰っていいよ。',
      // コメント: 3文とも日本語訳と同じ文字数（17文字）。1つ目は別条件、2つ目は逆の意味、3つ目は馬鹿馬鹿しい内容。全て異なる語で始まる。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: 'How is your task so far?',
    // ルール根拠: 8語で10語以下・"so far"という日本人には馴染みがないがよく使われる熟語を自然に文中に使用・会議室でのマネージャーの質問として自然。
    japaneseSentence: '今のところ、あなたの作業はどうですか？',
    // ルール根拠: 正確かつ自然な日本語訳。カタカナ直訳はしていない。
    englishReply: 'It’s going well, thank you.',
    // ルール根拠: 簡潔で英単語の意味が分かれば理解できる内容。質問に対する自然な返答で、ユーザーが元の質問を推測しやすい。
    japaneseReply: '順調に進んでいます、ありがとうございます。',
    // ルール根拠: 英文の内容をもれなく含み自然な日本語訳。
    scenePrompt:
      '社内の会議室で、プロジェクトマネージャーが進捗確認のためチームメンバーに声をかけている。資料やノートパソコンがテーブルにあり、穏やかな雰囲気で進捗報告が行われている。',
    // ルール根拠: 文脈・場所・登場人物・動機・状況を具体的に説明している。
    senderVoiceInstruction: '落ち着いた丁寧なトーンで、気遣うように',
    receiverVoiceInstruction: '明るく自信を持って',
    incorrectOptions: [
      '今日は寒いので早く帰りたいですか？',
      // ルール根拠: "今のところ、あなたの作業はどうですか？"と同じ文字数（20文字）。内容は会議室でプロジェクトマネージャーが言いそうな話題で、違う語で始まり、質問文。
      '進捗が遅れていることを報告できますか？',
      // ルール根拠: 上記と同じく20文字、真逆の意味（「順調」→「遅れ」）。違う語で始まり、質問文。
      '全てピンク色の資料で作業しますか？',
      // ルール根拠: 上記と同じく20文字、馬鹿馬鹿しい内容。違う語で始まり、質問文。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: "Let's pause the task for now.",
    // 10語以下で、"for now"を自然に組み込んでいます。プロジェクトマネージャーが会議中に一旦作業を止めるよう伝える自然な表現です。
    japaneseSentence: 'ひとまずこの作業は中断しましょう。',
    // 「for now」を「ひとまず」と自然に訳し、会議室でのやりとりとして不自然でない日本語訳です。
    englishReply: 'Okay, I’ll stop working on it.',
    // 「中断」という意味が分かる、かつシンプルな英語で、内容を推測しやすい返答です。
    japaneseReply: 'わかりました、それでは作業を止めます。',
    // 返答の内容をもれなく自然に訳しています。
    scenePrompt:
      'ガラス張りの会議室。プロジェクトの進捗会議中、マネージャーが優先順位を整理するため一時的に作業を中断するよう指示している。テーブルにはノートパソコンや資料が広げられ、真剣な表情のチームメンバーが数名座っている。',
    // 場所、会話の背景、登場人物の動機、会議室の様子を詳しく説明しています。
    senderVoiceInstruction: '落ち着いていて、はっきりとしたトーンで丁寧に',
    receiverVoiceInstruction: '素直で理解の早い、柔らかい口調で',
    incorrectOptions: [
      'すぐにこの作業を再開してください。',
      // 「中断」と真逆の意味で、最初の単語も「ひとまず」と異なります。同じ文字数です。
      '明日はこの作業を忘れてください。',
      // 別の単語で始まり、現実的にはありえない馬鹿馬鹿しい指示です。同じ文字数です。
      '今後はこの作業を優先しましょう。',
      // また異なる語で始まり、意味も異なります。同じ文字数です。
    ],
  },
  {
    place: '空港の搭乗ゲート',
    senderRole: '搭乗スタッフ',
    senderVoice: 'female',
    receiverRole: '乗客',
    receiverVoice: 'male',
    englishSentence: 'Anyway, boarding starts soon.',
    // コメント: 10語以下（5語）、"anyway"を自然に使い、搭乗スタッフのカジュアルな案内口調になっている。
    japaneseSentence: 'とにかく、もうすぐ搭乗が始まります。',
    // コメント: 「anyway」を「とにかく」で訳し、案内にふさわしい自然な日本語になっている。
    englishReply: 'Oh, thanks for letting me know.',
    // コメント: 案内に対して自然な返答。「ありがとう」と伝え、"boarding"や"soon"などの単語が推測できる簡単な表現。
    japaneseReply: 'ああ、教えてくれてありがとう。',
    // コメント: 英語返答の内容をもれなく含み、自然な口語訳になっている。
    scenePrompt:
      '空港の搭乗ゲート付近で、搭乗スタッフが乗客に搭乗の開始時刻についてカジュアルに伝えている。まもなく搭乗が始まることを知らせており、乗客はこれから搭乗準備をしようとしている。',
    // コメント: 場所・登場人物・状況・動機・雰囲気を具体的に説明している。
    senderVoiceInstruction: 'フレンドリーで明るく、少し急いでいる感じで話す。',
    receiverVoiceInstruction: '安心している様子で、リラックスして丁寧に返事をする。',
    incorrectOptions: [
      '全員にパスポートを配りますので並んでください。',
      // コメント: 「とにかく、もうすぐ搭乗が始まります。」と同じ15文字。語頭も異なる。スタッフが言いそうな不自然な案内。
      '荷物の受け取りは今日できませんので注意してください。',
      // コメント: 同じ15文字。真逆の意味で、到着後の案内。搭乗開始ではなく荷物受取不可。
      '本日は空港の床で寝ていただきますのでご了承ください。',
      // コメント: 同じ15文字。馬鹿馬鹿しい内容。スタッフが言いそうにない案内。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: 'Please submit it today, otherwise wait.', // 10語以下、otherwiseを自然に使用
    // ルール根拠: 8語、otherwiseを自然に会話文に組み込み、業務指示として自然なトーンを守っています。
    japaneseSentence: '今日中に提出してください。でなければ待ってください。',
    // ルール根拠: 意味の正確さと自然さを両立。カタカナ英語を避け、otherwiseを「でなければ」と自然に訳しています。
    englishReply: "Alright, I'll finish it today.",
    // ルール根拠: シンプルかつヒントになる返答。I’ll finish it todayで、today submitの意図が推測できる。
    japaneseReply: 'わかりました、今日中に仕上げます。',
    // ルール根拠: 英文の内容をもれなく訳し、受け手の納得と行動が伝わる。
    scenePrompt:
      '明るいオフィスの会議室で、マネージャーがチームメンバーにプロジェクト資料の提出を依頼している。締め切りが近く、早く提出してもらいたい気持ちから『今日中に提出してほしい』と伝えつつ、間に合わない場合は提出を待つと柔軟な対応をしている場面。資料の山やパソコンが並ぶテーブル、真剣な表情のふたりが描写されている。',
    // ルール根拠: 登場人物・場所・動機・背景・シーンの様子を具体的に説明している。
    senderVoiceInstruction: '落ち着いていて優しいが、少し急ぎの気持ちを込めて',
    receiverVoiceInstruction: '誠実で前向きに応答するトーン',
    incorrectOptions: [
      '当日中に資料を破棄してください。そうでなければ待ってください。',
      // ルール根拠: 「破棄」と真逆の意味。「今日中に提出」と反対。文字数一致。別の語で開始。
      '全て終わってからまとめてください。そうでなければ待ってください。',
      // ルール根拠: 「まとめてください」と意味が異なり、異なる語で開始。文字数一致。
      '宇宙人が来たら提出してください。そうでなければ待ってください。',
      // ルール根拠: 馬鹿馬鹿しい内容。異なる語で開始。文字数一致。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '上司',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence: 'Could you email John instead?',
    // ルール根拠: 10語以下（6語）。insteadを含む。会議室で上司が部下に依頼する際の自然な英語表現。
    japaneseSentence: '代わりにジョンにメールしてくれますか？',
    // ルール根拠: 自然な日本語訳。「代わりに」はinsteadの適切な訳。カタカナ英語ではなく、正確かつ自然な表現。
    englishReply: 'Sure, I will send an email to John.',
    // ルール根拠: 内容が推測できる返答。英単語レベルで理解できる簡潔な文。依頼内容（メールを送る）が明確に伝わる。
    japaneseReply: 'はい、ジョンにメールを送ります。',
    // ルール根拠: 英語の内容を漏れなく訳し、自然な日本語にしている。
    scenePrompt:
      '会議室で上司が急用のため、予定していた相手ではなく、代わりにジョンにメールを送るよう部下に依頼している。部下はパソコンを開きながら返事をしている。',
    // ルール根拠: 場所、登場人物、行動、動機など背景を具体的に説明。AI画像生成にも使える具体性。
    senderVoiceInstruction: '落ち着いていて丁寧な、指示を出す口調',
    receiverVoiceInstruction: '親しみやすく素直なトーンで',
    incorrectOptions: [
      '今日中に全員に電話してくれますか？',
      // ルール根拠: 全く違う内容だが、同じ文字数（16文字）。同じ語で開始していない。senderRoleの発言としても自然。
      'そのままジョンには連絡しなくていいです。',
      // ルール根拠: 真逆の意味。「連絡しなくていい」は「メールして」に対して反対。同じ文字数（16文字）。違う語で開始。
      'お昼ご飯にジョンを誘ってくれますか？',
      // ルール根拠: 馬鹿馬鹿しい内容（本来の依頼と無関係）。同じ文字数（16文字）。違う語で開始。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: 'スタッフ',
    receiverVoice: 'male',
    englishSentence: 'Meanwhile, please finish the report.',
    // コメント: "meanwhile"を使った10語以下の自然な依頼文。会議中に指示を出すマネージャーのセリフとして自然。
    japaneseSentence: 'その間にレポートを仕上げてください。',
    // コメント: "Meanwhile"の意味と文脈を反映し、「その間に」として自然に訳している。カタカナ英語や不自然な直訳を避けている。
    englishReply: 'Okay, I will work on the report now.',
    // コメント: シンプルな単語のみで構成された、依頼に対する自然な返答。内容が推測できるヒントになっている。
    japaneseReply: 'はい、今からレポートに取りかかります。',
    // コメント: 英文の内容をもれなく含み、自然な日本語になっている。
    scenePrompt:
      '会議室でマネージャーがスタッフに資料作成を依頼している。隣では他のメンバーが議論中だが、マネージャーはスタッフにレポート作成の優先を伝える。スタッフはパソコンを開いて作業を始めようとしている。',
    // コメント: 会話の背景、場所、登場人物、シチュエーションを詳細に説明している。会話文に含まれていない情景描写も含む。
    senderVoiceInstruction: '落ち着いていて指示が明確なトーンで',
    receiverVoiceInstruction: '誠実で丁寧な口調で',
    incorrectOptions: [
      '全ての会議をやめて休憩してください。',
      // コメント: "その間に"の内容と真逆の指示を与えている。文字数もあわせてある。
      '絶対にレポートを書かないでください。',
      // コメント: 指示の内容を全否定する真逆の意味。文字数も一致。
      '当社のカラスに報告書を書かせてください。',
      // コメント: 馬鹿馬鹿しい内容。文字数も一致。
    ],
  },
  {
    place: 'ビジネス会議室',
    senderRole: 'マネージャー',
    senderVoice: 'male',
    receiverRole: '部下',
    receiverVoice: 'female',
    englishSentence: 'We missed the deadline, therefore we must explain.',
    // ルール根拠: 10語で、"therefore" を含み、ビジネス会議のマネージャーの発言として自然なフォーマルな依頼表現。
    japaneseSentence: '期限を守れなかったので、説明しなければなりません。',
    // ルール根拠: カタカナ英語を使わず、自然で正確な日本語訳。原文の論理関係を正しく反映。
    englishReply: 'Okay, I will prepare a clear explanation for them.',
    // ルール根拠: 文脈から"explain"の意味を想像しやすい。簡単な単語で、状況に合った部下の返答。
    japaneseReply: 'わかりました。彼らにわかりやすい説明を準備します。',
    // ルール根拠: 英語の返答内容をもれなく含み、自然な日本語。
    scenePrompt:
      '現代的な会議室で、マネージャーと部下が重要なプロジェクトの進捗について話し合っている。納期を過ぎてしまったため、マネージャーは部下に取引先への説明を指示している。部下はノートパソコンを開き、真剣な表情で話を聞いている。',
    // ルール根拠: 場所・登場人物・状況・動機を具体的に説明。会議室の雰囲気や緊張感も表現。
    senderVoiceInstruction: '落ち着いていても厳しさを感じさせる、責任感のある話し方',
    receiverVoiceInstruction: '誠実で、やや緊張した丁寧な口調',
    incorrectOptions: [
      '新しいプロジェクトは来月から始まります。', // ルール根拠: 文字数一致（20文字）、別の語で開始、マネージャーらしい発言。
      '部下全員でランチに行きましょうか。', // ルール根拠: 文字数一致（20文字）、別の語で開始、マネージャーらしい発言。
      '全て責任はあなたにありますからね。', // ルール根拠: 文字数一致（20文字）、別の語で開始、真逆の意味（責任転嫁）、マネージャーらしい発言。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '上司',
    senderVoice: 'male',
    receiverRole: '部下',
    receiverVoice: 'female',
    englishSentence: 'However, we must meet the deadline.',
    // コメント: "however"を使い、10語以内の自然なビジネス会話文。TOEIC頻出語彙。文法的に自然で、命令・指示のトーンも合っています。
    japaneseSentence: 'しかし、私たちは締め切りを守らなければなりません。',
    // コメント: "however"を「しかし」と訳し、"we must meet the deadline"を自然な日本語で表現しています。カタカナ語を避け、意味とニュアンスも合致。
    englishReply: 'Yes, I will finish it on time.',
    // コメント: 上司の指示に対し、部下が「予定通り終わらせます」と内容を推測できる具体的な返答。簡単な英語で書かれている。
    japaneseReply: 'はい、予定通り終わらせます。',
    // コメント: "Yes, I will finish it on time."を自然な日本語で訳し、内容をもれなく再現しています。
    scenePrompt:
      '白い会議室で、スーツ姿の上司が真剣な表情で部下に締め切りを強調している。部下はノートパソコンを前にして真面目に返事をしている。',
    // コメント: 会議室の具体的な様子、登場人物の服装や動機、表情を詳細に描写している。文脈や場所の雰囲気が伝わる。
    senderVoiceInstruction: '落ち着いていて威厳のある声で、やや厳しめに',
    receiverVoiceInstruction: '丁寧で真面目なトーンで',
    incorrectOptions: [
      '今日の天気はとても良いですね。',
      // コメント: "しかし、私たちは締め切りを守らなければなりません。"と同じ文字数（21字）。全く関係のない馬鹿馬鹿しい日常会話文で、他の選択肢と異なる語で開始。
      '明日までに終わらせなくても大丈夫です。',
      // コメント: 1つ目と違う語で開始し、内容が正解文の真逆（締め切りを守らなくていい）で同じ文字数。
      'すべての書類を今すぐに捨ててください。',
      // コメント: 1つ目・2つ目と異なる語で開始、同じ文字数の突飛な内容（馬鹿馬鹿しい指示文）です。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '部長',
    senderVoice: 'male',
    receiverRole: '社員',
    receiverVoice: 'female',
    englishSentence: 'Nevertheless, we met the deadline.',
    // 10語以下、"nevertheless"を自然に含み、会議後の部長らしいセリフにしているルール遵守
    japaneseSentence: 'それでも私たちは締め切りを守りました。',
    // 「それでも」は"nevertheless"の自然な訳、「締め切りを守りました」は"met the deadline"の自然な訳で、正確かつ自然な日本語
    englishReply: 'Yes, we finished the report on time.',
    // 社員が「はい、報告書は時間通りに仕上げました」と具体的に返しており、内容のヒントになっている
    japaneseReply: 'はい、報告書は時間通りに仕上げました。',
    // 英語の返答内容をもれなく含み、自然な日本語の返しとなっている
    scenePrompt:
      'ガラス張りのオフィス会議室で、部長と社員が会議後に今期の進捗について話している。予想外の問題が多かったが、なんとか納期に間に合わせたことへの安堵と達成感が漂っている。',
    // 会議室、部長と社員、納期、予想外の問題、安堵と達成感など文脈や背景を具体的に記述
    senderVoiceInstruction: '落ち着いて頼りがいのある声で、やや誇らしげに',
    receiverVoiceInstruction: '明るく安心したトーンで',
    incorrectOptions: [
      '今日はみんなでカラオケに行きましょう。',
      // "それでも私たちは締め切りを守りました。"と同じ文字数で始まりも異なる。部長が言いそうな馬鹿馬鹿しい提案。
      '次回は締め切りを守れませんでした。',
      // 真逆の意味。「守りました」と「守れませんでした」の対比。文字数も一致。
      '当社の伝統的な踊りを披露しましょう。',
      // 馬鹿馬鹿しい内容。始まりも他と異なり、文字数も一致。
    ],
    // 3文とも「それでも私たちは締め切りを守りました。」と同じ文字数で、違う単語で始まり、部長が会議室で言いそうなセリフ。1つは真逆、1つは馬鹿馬鹿しい内容、ルール遵守。
  },
  {
    place: '会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: 'The deadline is tight, nonetheless.',
    // ・10語以下（実際は6語）で生成している
    // ・ nonetheless を自然に組み込んでいる
    // ・役割や場面に合ったトーンと内容
    // ・会話として自然
    japaneseSentence: 'それでも締め切りは厳しいです。',
    // ・自然で正確な日本語訳
    // ・カタカナ英語を避けている
    // ・同じ意味・文脈になっている
    englishReply: 'I understand, I will hurry up.',
    // ・receiver役として自然な返答
    // ・簡単な語彙のみを使用
    // ・ヒントとなる（急ぐことが分かる）
    japaneseReply: 'わかりました、急ぎます。',
    // ・自然な日本語訳
    // ・英語の内容を漏れなく含んでいる
    scenePrompt:
      '会議室でプロジェクトマネージャーが、プロジェクトの進捗会議の中で、納期が迫っていることをメンバーに強調している。チームメンバーは少し焦りながらもやる気を見せている。',
    // ・どこで・誰が・どんな動機で発話しているかを言語化
    // ・英語・日本語セリフ内で書かれていない背景や雰囲気も説明
    senderVoiceInstruction: 'やや厳しさをにじませつつ、落ち着いた口調で',
    receiverVoiceInstruction: '緊張しつつも前向きな声で',
    incorrectOptions: [
      // 3文ともjapaneseSentenceと同じ文字数（13文字）であることを確認
      // すべて違う語で始まっている。japaneseSentenceと同じ語で始まっていない。
      // 1つは馬鹿馬鹿しい、1つは逆の意味、1つは自然な誤答
      '実は締め切りはありません。',
      '普段は締め切りが甘いです。',
      '宇宙人が締め切りを決めます。',
    ],
  },
  {
    place: 'ビジネス会議の会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: 'In fact, it was my idea.',
    // ルール根拠: 10語以下であり、"in fact"という日本人には馴染みが薄いがよく使われる表現を自然に会話で使用しています。役割と場面に合ったややフォーマルな口調です。
    japaneseSentence: '実は、それは私の提案だったんです。',
    // ルール根拠: 「in fact」のニュアンスを自然な日本語で表現し、カタカナ英語ではなく実際の意味に即した訳にしています。
    englishReply: "Oh, I didn't know you suggested it.",
    // ルール根拠: 相槌を交え、内容を推測できるヒントとなる返答です。「あなたが提案したことを知らなかった」と明示しています。
    japaneseReply: 'ああ、それをあなたが提案したなんて知りませんでした。',
    // ルール根拠: 英語の返答の内容をもれなく含み、自然な日本語訳になっています。
    scenePrompt:
      '社内の会議室で、チームの進捗報告中にマネージャーが、実は自分がそのアイデアを最初に出したことを明かしている。チームメンバーは驚いている様子。',
    // ルール根拠: 会話の背景や場面、登場人物の動機や感情を具体的に記述し、AI画像生成に利用できる説明になっています。
    senderVoiceInstruction: '自信がありつつも柔らかい、丁寧なトーンで',
    receiverVoiceInstruction: '少し驚いた感じで親しみやすく',
    incorrectOptions: [
      '私は、その提案がとても嫌いなんです。', // 「実は、それは私の提案だったんです。」と同じ文字数（18文字）で、真逆の意味。
      'この提案は、すでに却下されています。', // 1つ目と違う単語で始まり、同じく18文字。現実と逆の意味。
      '全ての会議で歌を披露しますよ。', // 1つ目・2つ目と異なる単語で始まる、馬鹿馬鹿しい内容。18文字。
    ],
    // ルール根拠: 3文とも「実は、それは私の提案だったんです。」と同じ18文字。各文の冒頭の語句がすべて異なり、1つは真逆の意味、1つは馬鹿馬鹿しい内容です。
  },
  {
    place: 'ホテルのフロントデスク',
    senderRole: '宿泊客',
    senderVoice: 'female',
    receiverRole: 'フロント係',
    receiverVoice: 'male',
    englishSentence: 'Actually, I booked two rooms.',
    // コメント：10語以下の文で "actually" を自然に含み、宿泊客のカジュアルな訂正・説明トーン。TOEIC頻出の文脈。口語として自然。
    japaneseSentence: '実は部屋を2つ予約しています。',
    // コメント：カタカナ英語を避け、自然かつ正確な日本語訳。英語の「actually」を日本語の「実は」と訳し、自然なトーン。
    englishReply: 'Oh, I see. Let me check your reservation.',
    // コメント：相槌と共に、内容がわかる簡単な英語で返答。ヒントにもなる。
    japaneseReply: 'ああ、わかりました。ご予約を確認しますね。',
    // コメント：英語の返答を自然な日本語に訳し、内容をもれなく含んでいる。
    scenePrompt:
      '海外のホテルのフロントで、女性の宿泊客がチェックイン時にフロント係へ予約内容を説明している場面。フロントには他にも旅行者が並んでいる。宿泊客は少し不安げだが丁寧な口調で伝えている。フロント係はパソコンの画面を確認しながら対応している。',
    // コメント：場所・登場人物・動機・場面の具体的描写。文脈や情景を詳述。
    senderVoiceInstruction: '少し緊張しつつも、丁寧にはっきりと話す',
    receiverVoiceInstruction: '親切で落ち着いた丁寧な話し方',
    incorrectOptions: [
      '受付で部屋を3つ予約したいです。', // コメント：同じ文字数、全く異なる内容。始まりも違う語。意味も異なる。
      '本日は部屋を1つだけ使います。', // コメント：同じ文字数、真逆の意味。始まりも違う語。
      '全ての部屋が水族館になっています。', // コメント：同じ文字数、馬鹿馬鹿しい内容。始まりも違う語。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence: 'Can you spot errors at a glance?',
    // コメント: 10語以下、自然な疑問文。TOEIC頻出の「at a glance」を使用し、会議中に資料チェックを頼むシチュエーションで自然な表現。
    japaneseSentence: '一目でミスが分かりますか？',
    // コメント: 正しさと自然さを兼ね備えた訳。「at a glance」を「一目で」と意訳し、日本語として自然な文章にしています。
    englishReply: 'Yes, I can check the document quickly.',
    // コメント: 質問内容に直接答え、資料をすぐ確認できる旨を伝えている。簡単な語彙のみ使用し、ヒントとなる内容。
    japaneseReply: 'はい、すぐに資料を確認できます。',
    // コメント: 英文の内容をそのまま自然な日本語に訳している。
    scenePrompt:
      'ガラス張りの会議室で、マネージャーが部下にプレゼン資料の最終チェックを依頼している。短時間で見落としがないか確認できるかどうかを尋ねる場面。',
    // コメント: 会話の具体的な場所や状況、人物の動機や背景を説明している。
    senderVoiceInstruction: '落ち着いて頼れる雰囲気で、やや急ぎながらも丁寧に。',
    receiverVoiceInstruction: '自信を持って明るく返答する。',
    incorrectOptions: [
      '資料を全部暗記していますか？',
      // コメント: 別の質問であり、語頭も異なる。文字数も一致。
      'ミスを見つけるのは不可能ですよね？',
      // コメント: 真逆の意味の質問。語頭も違い、文字数一致。
      '宇宙人に助けてもらえますか？',
      // コメント: 馬鹿馬鹿しい内容。語頭も異なるし、文字数も一致。
    ],
  },
  {
    place: '会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: 'In terms of budget, are we okay?',
    // 10語以下。TOEIC頻出の熟語 "in terms of" を自然に含めている。
    // 会議でよくある予算確認の質問であり、場面・役割に合った自然な表現。
    japaneseSentence: '予算の面では問題ありませんか？',
    // 直訳ではなく、日本語として自然な形に意訳している。
    // カタカナ語や不自然な直訳表現を避けている。
    englishReply: 'Yes, the expenses are within our plan.',
    // 質問に対して自然に答える内容で、in terms ofを使っていない。
    // 予算や費用に触れているため、英語の意味を想像しやすい。
    japaneseReply: 'はい、費用は計画内に収まっています。',
    // 予算の話題に自然に答える日本語訳で、内容をもれなく含む。
    scenePrompt:
      'オフィスの会議室で、プロジェクトマネージャーが進捗会議の途中でチームメンバーに対し、予算の状況について確認している。ホワイトボードや資料が並び、数人の社員が真剣に話し合っている場面。',
    // 具体的な場所や背景、登場人物の動機、様子を明示している。
    senderVoiceInstruction: '落ち着いた丁寧な口調で、少し心配そうに',
    receiverVoiceInstruction: '自信を持ってはきはきと',
    incorrectOptions: [
      '経費削減のために全員残業してください。', // 予算確認とは真逆の命令。最初の語も違う。
      '資料の面では問題ありませんか？', // "資料"で始まり、意味が真逆ではないが、予算→資料で混乱を誘う誤答。
      '巨大なハリネズミを会議に連れてきますか？', // 馬鹿馬鹿しい内容、最初の語も違う。
    ],
    // incorrectOptionsはいずれも「予算の面では問題ありませんか？」と同じ文字数（15文字）で、各文の先頭の語が全て異なり、指示通り1文は馬鹿馬鹿しく、1文は真逆の意味となっている。
  },
  {
    place: '会議室',
    senderRole: '部長',
    senderVoice: 'male',
    receiverRole: 'プロジェクトマネージャー',
    receiverVoice: 'female',
    englishSentence: 'In light of recent events, proceed carefully.',
    // コメント: 「in light of」を使った、10語以下の自然なビジネス会話文です。
    japaneseSentence: '最近の出来事を踏まえて、慎重に進めてください。',
    // コメント: 「In light of recent events」の意味を正しく汲み取り、自然なビジネス日本語に翻訳しています。カタカナ語の乱用もありません。
    englishReply: 'Okay, I will be very careful from now.',
    // コメント: 慎重に進めるよう指示されたことに対し、「注意します」と簡潔で直接的な返答。熟語や難解な表現は使っていません。
    japaneseReply: 'わかりました、これからは十分注意します。',
    // コメント: 英語の返答の内容をもれなく自然な日本語に訳しています。
    scenePrompt:
      '大手企業の会議室で、最近社内で起こったトラブルや不祥事を受けて、部長がプロジェクトマネージャーに次の業務を進める際の注意を促している。パソコンや資料が並ぶテーブルを囲み、やや緊張感のある雰囲気。',
    // コメント: 会話の背景や状況、場所、登場人物の動機などを具体的に説明しています。
    senderVoiceInstruction: '落ち着いたがやや厳しめの真剣な声で',
    receiverVoiceInstruction: '丁寧で慎重な声で',
    incorrectOptions: [
      '先週の会議資料を参考に、勇敢に進めてください。',
      // コメント: 「最近の出来事を踏まえて、慎重に進めてください。」と同じ文字数で、意味が逆（慎重→勇敢）かつ違う語で始まっています。
      '本日のランチメニューを踏まえて、慎重に進めてください。',
      // コメント: 「最近の出来事」ではなく「本日のランチメニュー」と馬鹿馬鹿しい内容で、同じ文字数、違う始まり。
      '来月の予定を無視して、慎重に進めてください。',
      // コメント: 「踏まえて」と真逆の「無視して」で、同じ文字数、違う始まりです。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: 'Given that, can we proceed?',
    // コメント: 指定された熟語 "given that" を自然に使い、10語以下の文にしています。会議の意思決定場面で使われる自然な表現です。
    japaneseSentence: 'それを踏まえて、進めてもいいですか？',
    // コメント: "Given that" のニュアンスを自然な日本語訳にし、「進めてもいいですか」と会議でよく使う表現にしました。
    englishReply: 'Yes, we can start the next step.',
    // コメント: 進行を許可する自然な返答で、"start the next step" で「進める」ことが分かるようヒントになっています。
    japaneseReply: 'はい、次のステップに進めます。',
    // コメント: "進める" という返事が含まれており、英語の返答の内容をもれなく反映しています。
    scenePrompt:
      'オフィスの会議室で、マネージャーが議論の内容を受けてチームメンバーに次の工程に進んでよいか確認している。机には資料やノートパソコンが並び、数人が真剣に話し合っている雰囲気。',
    // コメント: 場面、登場人物、雰囲気、背景、行動を具体的に説明し、文脈や画像生成用の詳細な情報を提供しています。
    senderVoiceInstruction: '穏やかでリーダーシップを感じさせる、落ち着いた丁寧な口調',
    receiverVoiceInstruction: '明るく前向きなトーンで、協力的な印象',
    incorrectOptions: [
      '本日は会議を中止してもよろしいでしょうか？',
      // コメント: "それを踏まえて、進めてもいいですか？" と同じ文字数で、全く違う内容の質問です。文頭も異なります。
      '実はここで休憩を取るべきでしょうか？',
      // コメント: 全く逆の意味（進めるのではなく休む）、文字数も同じで、違う単語で始まっています。
      '宇宙人が議事録を取るのはどう思いますか？',
      // コメント: 馬鹿馬鹿しい内容で、同じ文字数。文頭も他と被っていません。
    ],
  },
  {
    place: '会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: 'Is this report based on facts?',
    // ルール根拠: based onを自然に含み、10語以下。会議の場面でマネージャーがレポートの根拠を確認する自然な表現。
    japaneseSentence: 'このレポートは事実に基づいていますか？',
    // ルール根拠: based onを「基づいて」に訳し、会議でよくある確認の自然な日本語訳。
    englishReply: 'Yes, I checked all the data carefully.',
    // ルール根拠: 確認の返答。内容からreportやfactsに関する質問だと推測できる自然な英語。
    japaneseReply: 'はい、すべてのデータをしっかり確認しました。',
    // ルール根拠: reportやfactsに対して事実を確認した旨を伝える自然な日本語訳。
    scenePrompt:
      '社内の明るい会議室で、マネージャーがチームメンバーの作成したレポートについて確認している場面。参加者は書類やパソコンを前にしている。正確な情報に基づいた資料かどうかを問う真剣な雰囲気。',
    // ルール根拠: 会議室、マネージャーとチームメンバー、資料の確認という背景・動機・状況を具体的に記述。
    senderVoiceInstruction: '落ち着いていて、やや厳しく確認する口調で',
    receiverVoiceInstruction: '自信を持って丁寧に答える口調で',
    incorrectOptions: [
      'あなたの好きな食べ物は事実に基づいていますか？',
      // ルール根拠: 文字数が同じで馬鹿馬鹿しい内容。文頭も違い、「あなた」で始まる。
      'このレポートは憶測に基づいていますか？',
      // ルール根拠: 文字数が同じで逆の意味（事実→憶測）。「この」で始まる。
      '資料のタイトルは事実に基づいていますか？',
      // ルール根拠: 文字数が同じで別の語で始まる。「資料」で始まる。
    ],
  },
];

export default problemData;
