import { SeedProblemData } from '../src/types/problem';

/**
 * 問題データ 6
 * Generated by create-problems.ts (30 problems)
 */
const problemData: SeedProblemData[] = [
{
  place: '会議室',
  senderRole: 'チームリーダー',
  senderVoice: 'female',
  receiverRole: 'プロジェクトメンバー',
  receiverVoice: 'male',
  englishSentence: 'Let’s take some time to strategize for the new project.',
  japaneseSentence: '新しいプロジェクトのために少し時間を取って作戦を立てましょう。',
  englishReply: 'Good idea, planning will help us succeed.',
  japaneseReply: 'いい考えですね。計画を立てればうまくいきますね。',
  scenePrompt: '対面での会話シーン。火曜の午前中、明るい会議室で女性のチームリーダーが会議テーブル越しに男性メンバーに向かって、真剣な表情で新規プロジェクトについて話し始める。1コマ目では女性が計画の必要性を説明している。2コマ目では男性が向かい側から前向きな表情でその提案に同意している。まだホワイトボードや資料は使われておらず、テーブルの上は整理されている。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "宇宙人が昨日近所の公園でダンスをしていたそうですよね。",
    "昔のプロジェクトについてもう一度考え直してみませんか。",
    "冷蔵庫の内部に現在入っている野菜の個数を数えてみましょうか。"
  ],
  difficultyLevel: null
},
{
  place: '会議室',
  senderRole: '上司',
  senderVoice: 'female',
  receiverRole: 'チームメンバー',
  receiverVoice: 'male',
  englishSentence: 'I\'d like to strengthen our team\'s communication this quarter.',
  japaneseSentence: '今期はチームのコミュニケーションを強化したいと思います。',
  englishReply: 'Great idea. More meetings could really help us.',
  japaneseReply: 'いい考えですね。打ち合わせを増やせば、きっと役立つと思います。',
  scenePrompt: '対面での会話。水曜の午前、明るい会議室で女性上司がテーブル越しに座っている男性チームメンバーに向かい、チームワーク強化について提案する。1コマ目では女性上司が真剣な表情で話し始めている。2コマ目では男性が前向きな表情で返答している。まだ具体的な議論や資料の提示は始まっていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "毎朝コーヒーを三杯も飲む理由を教えてください。",
    "宇宙人が会議室で踊っていたら面白いと思いませんか。",
    "今期につきましては新しいメンバーを増やすご予定はありますでしょうか。"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの休憩室',
  senderRole: '同僚',
  senderVoice: 'female',
  receiverRole: '同僚',
  receiverVoice: 'male',
  englishSentence: 'Recent studies show taking short walks after lunch improves health.',
  japaneseSentence: '最近の研究で、昼食後に少し歩くだけでも健康に良いことが分かったそうですよ。',
  englishReply: 'Yeah, I’ve read those studies too.',
  japaneseReply: 'うん、その研究、僕も読んだことがあるよ。',
  scenePrompt: '対面での会話。平日の昼休み、オフィスの休憩室で女性の同僚が明るい表情でテーブル越しに男性の同僚へ健康習慣について話しかける。1コマ目は女性が話し始めており、男性はまだ返答していない。2コマ目では男性が女性の話にうなずきながら返答している。まだ2人とも席を立っていないし、休憩室のテーブルには昼食の残りや飲み物があるが、歩き出す様子や他の同僚の介入はない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "新しいゲーム機が発売されて話題になっているそうですね。",
    "宇宙人は昼食後にジャンプすると元気になるって本当ですか？",
    "最近の研究によれば、朝食を食べた後にそのまま座っていることが健康に良いのでしょうか？"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの会議室',
  senderRole: '人事担当者',
  senderVoice: 'male',
  receiverRole: '社員',
  receiverVoice: 'female',
  englishSentence: 'Starting next month, the company will subsidize your commuting costs.',
  japaneseSentence: '来月から会社があなたの通勤費を補助します。',
  englishReply: 'Oh, that’s great! How do I apply?',
  japaneseReply: 'それは嬉しいです。どうやって申し込めばいいですか？',
  scenePrompt: '対面での会話。火曜の午前、オフィスの会議室で行われている。1コマ目では、男性の人事担当者が会議室のテーブル越しに女性社員へ新しい通勤手当制度について説明し始めている。2コマ目では、女性社員がテーブル席で嬉しそうに担当者へ質問している。まだ申込書や資料などはテーブルの上に出ていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "宇宙人が会社の屋上でダンスします。",
    "図書館の本は全部英語で書かれています。",
    "毎日会社において昼食が無料で提供されます。"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの会議室',
  senderRole: '営業マネージャー',
  senderVoice: 'female',
  receiverRole: 'プロジェクト担当者',
  receiverVoice: 'male',
  englishSentence: 'The supplier\'s shipment has been delayed until next week.',
  japaneseSentence: '仕入先からの荷物の到着が来週まで遅れることになりました。',
  englishReply: 'Okay, should we update the project schedule?',
  japaneseReply: 'わかりました。予定を更新しましょうか？',
  scenePrompt: '対面での会話シーンです。水曜の午前、オフィスの会議室で女性の営業マネージャーが資料を手に持ち、テーブル越しに男性のプロジェクト担当者に納期遅延の状況を説明しています。1コマ目は女性が真剣な表情で説明している場面。2コマ目は男性が向かい側で冷静に返答している場面です。まだ資料や書類の受け渡しやパソコン操作は行われていません。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "工場からの製品の発送が今日中に完了する予定です。",
    "宇宙人が昨日スーパーで買い物をしていたそうですよね。",
    "新しい映画の上映が始まる日は再来月だと私は聞きました。"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスのコピー機の横',
  senderRole: '同僚',
  senderVoice: 'female',
  receiverRole: 'オフィスの管理担当者',
  receiverVoice: 'male',
  englishSentence: 'We’re running low on office supplies by the copier.',
  japaneseSentence: 'コピー機のところの事務用品が少なくなってきています。',
  englishReply: 'Thanks, I’ll order more supplies today.',
  japaneseReply: 'ありがとう。今日中に事務用品を追加で注文します。',
  scenePrompt: '対面での会話。平日の午前中、明るいオフィス内のコピー機の横で、女性の同僚が管理担当の男性に事務用品の在庫が少ないことを伝えている。1コマ目では女性がコピー機の横でやや心配そうに男性に話しかけている。2コマ目では男性が女性の話を聞き、メモを取りながら前向きに対応を約束している。まだ事務用品の補充や注文作業は始まっていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "夏祭りの花火大会は今年も開催される予定です。",
    "宇宙人がコピー機でダンスを始めたらどうしますか？",
    "プリンターのインクがまもなく切れてしまいそうですね。"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの自席',
  senderRole: '同僚',
  senderVoice: 'male',
  receiverRole: '上司',
  receiverVoice: 'female',
  englishSentence: 'I need to take some days off for surgery next week.',
  japaneseSentence: '来週、手術のために何日かお休みをいただきたいです。',
  englishReply: 'Of course, just let me know the dates.',
  japaneseReply: 'もちろんです。日にちが決まったら教えてください。',
  scenePrompt: '対面での会話。火曜の午前、明るいオフィス内で、1コマ目は男性社員が自席でやや緊張した様子で立ち上がり、近くの女性上司のデスクに向かって休暇の相談をしている。2コマ目は女性上司が自席で優しく微笑みながら男性に返答している。まだ休暇申請書類や具体的な日程はやり取りされていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "新しいパソコンの調子はどうですか最近は？",
    "宇宙人が今夜公園でダンス大会を開くらしいですよ。",
    "最近はほぼ毎日のようにスポーツジムに通っていますか？"
  ],
  difficultyLevel: null
},
{
  place: '会議室のプレゼンテーションエリア',
  senderRole: 'マネージャー',
  senderVoice: 'male',
  receiverRole: 'チームメンバー',
  receiverVoice: 'female',
  englishSentence: 'I\'d like to discuss the results of our recent surveys.',
  japaneseSentence: '最近行ったアンケートの結果について話したいと思います。',
  englishReply: 'Sure, are the survey results positive overall?',
  japaneseReply: 'はい、アンケートの結果は全体的に良かったですか？',
  scenePrompt: '対面での会話。水曜の午前、明るい会議室のプレゼンテーションエリアで、スーツ姿の男性マネージャーが立ったまま、ホワイトボードやスクリーンを背にして調査結果の共有を始める。テーブル席には女性チームメンバーが座り、話を真剣に聞いている。1コマ目ではマネージャーが説明を始める場面で、女性はまだ発言していない。2コマ目では女性が関心を持って質問しているが、まだ資料やグラフはテーブルに出ていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "宇宙人が最近地球の温泉に入ったそうですよ、本当ですか。",
    "先週実施した調査の方法について説明します。",
    "猫のしっぽの長さについて考えたことありますか。"
  ],
  difficultyLevel: null
},
{
  place: '会議室',
  senderRole: 'プロジェクトマネージャー',
  senderVoice: 'female',
  receiverRole: 'チームメンバー',
  receiverVoice: 'male',
  englishSentence: 'I think we should prioritize sustainability in this new proposal.',
  japaneseSentence: 'この新しい提案では持続可能性を優先すべきだと思います。',
  englishReply: 'Absolutely, sustainability should be a key focus.',
  japaneseReply: 'その通りですね。持続可能性は重要なポイントだと思います。',
  scenePrompt: '対面での会話。金曜の午前、明るい会議室で、1コマ目は女性プロジェクトマネージャーが会議室のテーブル越しに真剣な表情で新しい事業提案に持続可能性を加える重要性を話している。2コマ目は男性チームメンバーがテーブルの向かい側で女性の話をしっかり聞き、同意を示す表情で返答している。まだ資料やパソコンはテーブルに置かれていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "宇宙人が地球でカレーを作る方法を知っていますか？",
    "この新しい提案ではコスト削減を重視すべきでしょうか。",
    "昨日発表されていた天気予報は、実際の天候と照らし合わせてみた場合において、果たして的中したとお考えになりますでしょうか。"
  ],
  difficultyLevel: null
},
{
  place: '自宅のダイニングテーブル',
  senderRole: '家族（母親）',
  senderVoice: 'male',
  receiverRole: '家族（子ども）',
  receiverVoice: 'female',
  englishSentence: 'I think we should try living in a more sustainable way.',
  japaneseSentence: 'もっと環境にやさしい暮らし方をしてみたほうがいいと思うんだ。',
  englishReply: 'Like using less plastic and saving energy?',
  japaneseReply: 'たとえば、プラスチックを減らしたり、電気を節約したりするってこと？',
  scenePrompt: '対面での会話。土曜の朝、自宅のダイニングテーブルで家族が向かい合って座っている。1コマ目では母親である男性が真剣な表情で家族に環境に配慮した生活を提案している。2コマ目では子どもである女性が少し考えながら具体例を挙げて返答している。まだ何も実際の行動は始まっておらず、テーブルの上には朝食の食器などはなく、話し合いだけが行われている。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "新しいテレビドラマの主題歌は誰が歌っているか知ってる？",
    "宇宙人が地球でピクニックをするとき何を食べると思いますか？",
    "最近になってペットボトルの外観デザインが変化したことをご存知ですか？"
  ],
  difficultyLevel: null
},
{
  place: '会議室',
  senderRole: 'マネージャー',
  senderVoice: 'male',
  receiverRole: 'チームメンバー',
  receiverVoice: 'female',
  englishSentence: 'Before our new project starts, let\'s plan a team-building activity.',
  japaneseSentence: '新しいプロジェクトが始まる前に、みんなで親睦を深める活動を計画しましょう。',
  englishReply: 'Great idea. Team-building will help us collaborate better.',
  japaneseReply: 'いい考えですね。親睦を深めることで、もっと協力しやすくなると思います。',
  scenePrompt: '対面での会話。金曜の午前、明るい会議室で男性マネージャーが会議テーブルの前に立ち、数名のチームメンバーに向けて新プロジェクト前の親睦活動を提案している。1コマ目ではマネージャーが前向きな表情で話し、まだ具体的な活動内容や準備物は出ていない。2コマ目ではテーブル周辺で女性チームメンバーが笑顔で同意を示し、他のメンバーも聞いている様子。まだ親睦活動自体は始まっていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "古いプロジェクトが終わった後に、発表会を開催しませんか。",
    "宇宙人が会社の会議に参加したら何を提案するのでしょうかね。",
    "冷蔵庫の中に現在入っている野菜のみを使って、夕食の料理を作ることは可能でしょうか。"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの会議室',
  senderRole: '同僚',
  senderVoice: 'male',
  receiverRole: '同僚',
  receiverVoice: 'female',
  englishSentence: 'I’d like to share the new report template with you.',
  japaneseSentence: '新しい報告書のひな形を共有したいと思います。',
  englishReply: 'Great, I’ve been waiting for that template.',
  japaneseReply: 'ちょうどそのひな形を待っていました。',
  scenePrompt: '対面での会話。火曜の午前、明るいオフィスの会議室で二人の同僚がテーブルを挟んで座っている。1コマ目では男性が資料を持ちながら女性に新しい報告書テンプレートの共有を提案している。2コマ目では女性が嬉しそうに男性の話に応じている。まだテンプレートの配布やパソコンの操作は行われていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "宇宙人が会議室でダンスをしているみたいですね。",
    "古い報告書の修正版を送付したいと思います。",
    "今夜の天気予報は雨になる予定ですよね。"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスのコピー機の横',
  senderRole: '同僚',
  senderVoice: 'female',
  receiverRole: '同僚',
  receiverVoice: 'male',
  englishSentence: 'Watch me make this three-pointer into the trash can.',
  japaneseSentence: 'この書類をゴミ箱に投げ入れるところ、見ててね。',
  englishReply: 'Nice shot! You should join our basketball team.',
  japaneseReply: 'すごいね。うちのバスケットボール部に入ったらどう？',
  scenePrompt: '対面での会話。平日の昼休み前、オフィスのコピー機の横で女性の同僚が、冗談めかした表情で手に持った書類をゴミ箱に向かって投げ入れようとポーズをとっている。2コマ目では、近くにいる男性の同僚がその様子を見て感心したように笑顔で返答している。まだ書類はゴミ箱に入っていない。周囲には他の社員や余計な小道具はなく、コピー機とゴミ箱が見えるだけ。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "宇宙人が毎朝パンケーキを焼く瞬間、見たことある？",
    "毎日このカバンを机の上に置くところ、見ててね。",
    "新しい靴下の色について相談したいんだけど、どう思う？"
  ],
  difficultyLevel: null
},
{
  place: '大学の学生課カウンター前',
  senderRole: '学生',
  senderVoice: 'male',
  receiverRole: '学生課の職員',
  receiverVoice: 'female',
  englishSentence: 'Hi, I need a transcript for my study abroad application.',
  japaneseSentence: 'こんにちは、留学の申請に使う成績証明書が必要です。',
  englishReply: 'Sure, I can help you with your transcript.',
  japaneseReply: 'はい、成績証明書の手続きをお手伝いします。',
  scenePrompt: '対面での会話。平日の午前中、大学の学生課カウンター前で男子学生がカウンター越しに職員へ成績証明書について相談している。1コマ目では学生がカウンター前で書類を手に立ち、職員に話しかけている。2コマ目ではカウンター内の女性職員が親切そうに学生に対応している。まだ書類の受け渡しや手続きは始まっていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "宇宙人が昨日うちに来てカレーを作ってくれましたよ。",
    "明日の授業の時間割について知っていますか。",
    "新しいペットの名前をもう決めましたかどうですか。"
  ],
  difficultyLevel: null
},
{
  place: '会議室',
  senderRole: 'プロジェクトマネージャー',
  senderVoice: 'female',
  receiverRole: 'チームメンバー',
  receiverVoice: 'male',
  englishSentence: 'We\'ll begin the transition to the new system next Monday.',
  japaneseSentence: '新しいシステムへの移行を来週の月曜日から始めます。',
  englishReply: 'Okay, so the transition starts next week.',
  japaneseReply: '分かりました。移行は来週からなんですね。',
  scenePrompt: '対面での会話。火曜の朝、オフィスの会議室で女性プロジェクトマネージャーが、会議テーブル越しに複数のチームメンバーへ新しいシステムへの移行時期を説明している。1コマ目では女性が資料を持ち、真剣な表情で説明している。2コマ目では男性チームメンバーがテーブル越しにうなずきながら返答している。まだ会議は始まったばかりで、テーブル上にパソコンや飲み物はなく、議論も始まっていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "宇宙人が明日から会社に来る予定だそうですよね。",
    "雪が降ると駅前のカフェが混雑しやすくなります。",
    "新しい部署の正式な発足を今月の金曜日に行う予定です。"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの会議室',
  senderRole: '同僚',
  senderVoice: 'female',
  receiverRole: '同僚',
  receiverVoice: 'male',
  englishSentence: 'Have you decided on transportation for our business trip yet?',
  japaneseSentence: '出張の移動手段はもう決めましたか？',
  englishReply: 'Not yet—I’m still comparing train and taxi.',
  japaneseReply: 'まだです。電車とタクシーを比べているところです。',
  scenePrompt: '対面での会話。金曜の午後、オフィスの明るい会議室で、1コマ目は女性の同僚がテーブル越しに男性同僚へ出張の交通手段について相談するため話しかけている。2コマ目では男性が考え込む様子で女性に返答している。どちらのコマでも書類やパソコンはテーブルに置かれていない。まだ交通手段は決定していない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "カバは空を飛ぶことができるのですか？",
    "会議の開始時間はもう決めましたか？",
    "パンダの好物は本当に肉ですか？"
  ],
  difficultyLevel: null
},
{
  place: '会議室',
  senderRole: '上司',
  senderVoice: 'female',
  receiverRole: '営業担当者',
  receiverVoice: 'male',
  englishSentence: 'Our recent sales figures show consistent underperformance this quarter.',
  japaneseSentence: '今期の売上実績がずっと目標を下回っています。',
  englishReply: 'I know, and I\'m working to improve them.',
  japaneseReply: '分かっています。改善に取り組んでいます。',
  scenePrompt: '対面での会話。金曜の午後、オフィスの会議室で女性上司と男性営業担当者がテーブル越しに向かい合って座っている。1コマ目では女性上司が真剣な表情で男性に売上実績について話しかけている。2コマ目では男性がやや緊張しつつも前向きな表情で返答している。まだ資料やパソコンなどはテーブルの上に出ていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "巨大なカブトムシが空を飛ぶ夢を見たことがあります。",
    "新商品の開発状況は順調に進んでいます。",
    "昨日の晩ご飯はカレーライスでしたが美味しかったです。"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの休憩室',
  senderRole: '同僚',
  senderVoice: 'male',
  receiverRole: '同僚',
  receiverVoice: 'female',
  englishSentence: 'Hey, did you hear? We get our new uniforms on Friday.',
  japaneseSentence: 'ねえ、聞いた？金曜日に新しい制服がもらえるんだって。',
  englishReply: 'Oh, great! I was wondering about the uniforms.',
  japaneseReply: '本当？ずっと制服のこと気になってたんだ。',
  scenePrompt: '対面での会話シーン。水曜の昼休み、明るいオフィスの休憩室で男性の同僚が立ったまま、近くの女性同僚に新しい制服の支給日について伝えようとしている。1コマ目では男性が少し前のめりで話しかけており、女性は驚きと関心の表情で聞いている。まだ制服は手元にないし、書類や制服などの物も二人の手やテーブルにはない。2コマ目では女性が嬉しそうに返答しているが、まだ制服の話以外の行動や物の受け渡しは発生していない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "今夜の天気予報は雨になる可能性が高いのかな？",
    "宇宙人が金曜日にラーメンを配るらしいけど知ってる？",
    "体育の授業で新しい靴を使うことになったということなのですか？"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスのプリンター前',
  senderRole: '同僚',
  senderVoice: 'female',
  receiverRole: '同僚',
  receiverVoice: 'male',
  englishSentence: 'I think we’re printing too many unnecessary documents again.',
  japaneseSentence: 'また不必要な書類をたくさん印刷している気がするよ。',
  englishReply: 'You\'re right, we should only print what\'s needed.',
  japaneseReply: 'そうだね、必要なものだけ印刷するようにしよう。',
  scenePrompt: '対面での会話。平日の午前中、オフィスのプリンター前で女性の同僚が真剣な表情で男性の同僚に無駄な書類の印刷について注意している。背景にはプリンターやコピー用紙、オフィスの机や椅子が見える。1コマ目では女性が話しかけ、男性はまだ返答していない。2コマ目では男性が女性に向き直り、納得した様子で返答している。まだプリンターの使用をやめたわけではなく、印刷中の書類も手に持っていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "宇宙人が昨日公園でサッカーしていたって本当なのかなあ。",
    "今日は雨が降るって予報だったけど本当に降るのかなあ。",
    "最近ペットボトルのキャップを集める人が多いのかな。"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスのキッチンエリア',
  senderRole: '同僚',
  senderVoice: 'male',
  receiverRole: '同僚',
  receiverVoice: 'female',
  englishSentence: 'Hey, do you know if we have any extra utensils here?',
  japaneseSentence: 'ねえ、ここに予備のお箸とかフォークってあるか知ってる？',
  englishReply: 'No, I just checked—there aren’t any left.',
  japaneseReply: 'ううん、さっき確認したけどもう残ってなかったよ。',
  scenePrompt: '対面での会話。平日の昼、明るいオフィスのキッチンエリアで男性の同僚が女性の同僚に話しかけている。1コマ目では男性がキッチンの棚や引き出しを指差しながら、備品の場所について女性に尋ねている。女性はまだ返答していない。2コマ目では女性が男性に向かって、備品がもう残っていないことを伝えている。まだ新しい箸やフォークは登場していないし、補充もされていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "宇宙人がここでダンスを踊ったことって本当にあると思う？",
    "冷蔵庫の中に飲み物のストックがあるか知ってる？",
    "最近の天気予報は信じていいものなのかなって思わない？"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの会議室',
  senderRole: '上司',
  senderVoice: 'male',
  receiverRole: '部下',
  receiverVoice: 'female',
  englishSentence: 'Your idea for the project is really valuable to us.',
  japaneseSentence: '君のプロジェクトのアイデアは私たちにとって本当に貴重だよ。',
  englishReply: 'Thank you, I\'m glad it was helpful.',
  japaneseReply: 'ありがとうございます。お役に立ててうれしいです。',
  scenePrompt: '対面での会話。金曜の午後、明るいオフィスの会議室で、1コマ目は男性上司が会議室のテーブル越しに座り、穏やかな表情で女性部下に話しかけている。背景には会議室らしいガラス窓やホワイトボードがある。2コマ目では女性部下が向かい側の席で、上司の言葉に微笑みながら丁寧に返答している。まだ書類やパソコンはテーブルに出ていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "昨日読んだ小説の結末を覚えていますか？",
    "ペンギンが空を飛びたがる理由を知っていますか？",
    "この資料のご提出の締め切りは一体いつまでとなっておりますでしょうか？"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの休憩スペース',
  senderRole: '同僚',
  senderVoice: 'female',
  receiverRole: '同僚',
  receiverVoice: 'male',
  englishSentence: 'Since I’m vegan, do you know any good lunch spots nearby?',
  japaneseSentence: '私、動物性のものを食べないんだけど、この近くでいいお昼ご飯のお店知ってる？',
  englishReply: 'Yeah, there’s a vegan café two blocks away.',
  japaneseReply: 'うん、二つ先の通りに動物性のものを使っていないカフェがあるよ。',
  scenePrompt: '対面での会話。平日の昼休み、オフィスの休憩スペースで女性の同僚が明るい表情で、向かいに座る男性同僚に自分がヴィーガンであることを伝え、近くで食事できる店について相談している。1コマ目では女性が話しかけており、テーブルの上にはまだ食べ物や飲み物は何もない。2コマ目では男性が女性の質問に親切に答えているが、まだ一緒に店を決めたり移動したりはしていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "あなたは普段からコーヒーを飲む習慣がありますか？",
    "ペンギンが空を飛べるって本当かどうか知っていますか？",
    "新しく登場する予定のスマートフォンの発売日についてご存知だったりしますか？"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスのエントランス',
  senderRole: 'オフィスの管理担当者',
  senderVoice: 'female',
  receiverRole: '社員',
  receiverVoice: 'male',
  englishSentence: 'Starting today, please park all vehicles in the new lot.',
  japaneseSentence: '今日からすべての車は新しい駐車場に停めてください。',
  englishReply: 'Okay, I\'ll use the new parking area.',
  japaneseReply: 'わかりました。新しい駐車場を使います。',
  scenePrompt: '対面での会話。平日の朝、オフィスのエントランスで女性の管理担当者が社員の男性に新しい駐車場の利用について説明している。1コマ目では女性がエントランス前で真剣な表情で男性に話しかけている。2コマ目では男性がエントランス付近で納得した様子で女性に返答している。まだ男性は駐車場に移動しておらず、車も描写されていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "宇宙の果てにはラーメン屋があるらしいですよ、本当ですか。",
    "昨日からすべての自転車は裏の倉庫に置いてください。",
    "新しい時計は図書館の隣に設置されたと聞きましたが。"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの会議室',
  senderRole: '同僚',
  senderVoice: 'male',
  receiverRole: '同僚',
  receiverVoice: 'female',
  englishSentence: 'I need your verification on this new client account.',
  japaneseSentence: 'この新しい顧客のアカウントについて確認をお願いしたいんだけど。',
  englishReply: 'Sure, I’ll review the client details now.',
  japaneseReply: 'わかりました。今すぐ内容を確認します。',
  scenePrompt: '対面での会話。平日の午前中、明るいオフィスの会議室で、1コマ目は男性の同僚がテーブル越しに女性の同僚へ新しい顧客アカウントの確認を依頼している。2コマ目では女性が真剣な表情でその依頼に応じる様子。まだ顧客情報の資料やパソコンは開かれていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "新しい商品の在庫状況について調べましたか？",
    "宇宙人の集会には参加するつもりだったんですか？",
    "明日のお天気の予報は晴れる予定になっているのでしょうか？"
  ],
  difficultyLevel: null
},
{
  place: 'オフィス会議室',
  senderRole: '同僚',
  senderVoice: 'female',
  receiverRole: '別の同僚',
  receiverVoice: 'male',
  englishSentence: 'This report verifies all the figures from last quarter.',
  japaneseSentence: 'この報告書は先四半期のすべての数値を確認しています。',
  englishReply: 'Great, thanks for double-checking those numbers.',
  japaneseReply: '分かりました、数字を再確認してくれてありがとう。',
  scenePrompt: '対面での会話。平日の午前中、明るいオフィス会議室で二人の同僚がテーブルを挟んで座っている。1コマ目では女性が正面の男性に向かって書類を持ちながら丁寧に説明している。2コマ目では男性が女性の説明を聞き、安心した表情で感謝の意を伝えている。まだ書類のやり取りや握手などは行われていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "駅前に新しいカフェがオープンしたそうですよ。",
    "宇宙人が来週の会議に参加する予定らしいですね。",
    "この書類につきましては、先月一ヶ月間だけの数値を確認しております。"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの会議室',
  senderRole: '同僚',
  senderVoice: 'female',
  receiverRole: 'プロジェクトメンバー',
  receiverVoice: 'male',
  englishSentence: 'We could arrange a virtual meeting with our overseas branch.',
  japaneseSentence: '海外支社とオンライン会議を設定することもできますよ。',
  englishReply: 'Good idea, a virtual meeting would save time.',
  japaneseReply: 'いいですね。オンライン会議なら時間の節約にもなりますね。',
  scenePrompt: '対面での会話。火曜の午前、明るいオフィスの会議室で、1コマ目は女性の同僚がテーブル越しに男性同僚へ新しい打ち合わせ方法を提案している。2コマ目は男性が女性の提案に前向きに返答している。どちらのコマもテーブルの上にパソコンや資料はなく、まだ実際のオンライン会議は始まっていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "宇宙人とカラオケ大会を開催することもできますよ。",
    "国内工場とオフライン会議を設定することもできますよ。",
    "新しい靴下を毎日交互に履くこともできますよ。"
  ],
  difficultyLevel: null
},
{
  place: 'カフェのテーブル席',
  senderRole: '友人',
  senderVoice: 'female',
  receiverRole: '友人',
  receiverVoice: 'male',
  englishSentence: 'I\'m volunteering at the animal shelter this weekend. Want to join?',
  japaneseSentence: '今週末、動物の保護施設でボランティアをするんだけど、一緒に行かない？',
  englishReply: 'That sounds fun. I\'d love to help volunteer.',
  japaneseReply: '楽しそうだね。ぜひ手伝いたい。',
  scenePrompt: '対面での会話。土曜の昼、明るいカフェのテーブル席で、女性が友人の男性に向かい合って座り、週末の動物保護施設でのボランティア活動に誘っている。1コマ目では女性が少し前のめりで話しかけている。2コマ目では男性が女性の話を聞き、前向きな表情で返答している。まだ2人とも飲み物や食べ物には手をつけておらず、テーブルの上にはコーヒーカップだけが置かれている。まだボランティア活動の具体的な内容や移動の話は始まっていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "来週末、美術館で特別展があるんだけど、一緒に行かない？",
    "宇宙人が今週末に公園でダンスをするらしいけど、見に行かない？",
    "新しいゲームの発売日が今週末だったかどうかって、あなたはご存知だったりしますか？"
  ],
  difficultyLevel: null
},
{
  place: 'クライアントの会社の会議室',
  senderRole: '営業担当者',
  senderVoice: 'female',
  receiverRole: 'クライアント担当者',
  receiverVoice: 'male',
  englishSentence: 'We\'re waiving all setup fees for your new contract.',
  japaneseSentence: '新しいご契約の初期費用はすべて無料にさせていただきます。',
  englishReply: 'That\'s great, waiving the fees really helps us.',
  japaneseReply: 'それは助かります。初期費用がかからないのは本当にありがたいです。',
  scenePrompt: '対面での会話シーン。平日の午前中、クライアント企業の明るい会議室で、営業担当の女性が資料を手に持ち、テーブル越しにクライアント担当の男性に新規契約の手数料免除を伝える。1コマ目は女性がやや前傾で説明している場面。2コマ目は男性が安心した表情で女性に感謝を伝えている場面。まだ契約書や書類へのサインなどは行われていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "昨日の天気予報は晴れだったと記憶しています。",
    "宇宙人が地球でラーメン屋を開いたという噂は本当ですか？",
    "新しくご契約いただいた場合の解約手数料については、すべて無料となっておりますでしょうか？"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの会議室',
  senderRole: 'オフィスのイベント担当者',
  senderVoice: 'male',
  receiverRole: '同僚たち',
  receiverVoice: 'female',
  englishSentence: 'I’m about to announce the winners of our office raffle.',
  japaneseSentence: 'これから社内のくじ引きの当選者を発表します。',
  englishReply: 'Great, I can’t wait to hear the winners!',
  japaneseReply: '楽しみです、早く当選者を知りたいです。',
  scenePrompt: '対面での会話。金曜の昼休み、オフィスの会議室で男性のイベント担当者が立って、数名の女性同僚たちに向かって注目を集めている。1コマ目では男性がイベントの抽選結果発表を始めるところで、まだ当選者名は発表されていない。2コマ目では女性たちがワクワクした様子で男性に注目し、当選者を知りたがっている。まだ誰が当選したかは発表されておらず、賞品も見えていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "宇宙人が地球でカラオケ大会を開催しています。",
    "今日の会議で新しい部署を紹介します。",
    "駅前のパン屋さんが閉店セールを始めました。"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの休憩スペース',
  senderRole: '同僚',
  senderVoice: 'female',
  receiverRole: '同僚',
  receiverVoice: 'male',
  englishSentence: 'Hey, check out my new wireless headphones I just bought.',
  japaneseSentence: '見て、新しい無線のヘッドホンを買ったんだ。',
  englishReply: 'Nice! Are they comfortable to wear?',
  japaneseReply: 'いいね、つけ心地はどう？',
  scenePrompt: '対面での会話。平日の昼休み、明るいオフィスの休憩スペースで、1コマ目は女性の同僚が新しいワイヤレスヘッドフォンを手に持ち、向かい側に座る男性同僚に見せている。2コマ目では男性がテーブル越しに興味深そうに女性に話しかけている。まだヘッドフォンは男性に渡されていないし、2人とも席を立っていない。テーブル上には飲み物だけがある。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "昨日は新しい有線のイヤホンを買ったんだよね。",
    "冷蔵庫の中にリンゴがひとつ残っていましたよ。",
    "カバが空を飛ぶって本当にあるのかな？"
  ],
  difficultyLevel: null
}
];

export default problemData;
