import { SeedProblemData } from '../src/types/problem';

/**
 * 問題データ 5
 * Generated by GPT API (60 problems)
 */
const problemData: SeedProblemData[] = [
  {
    place: 'ビジネス会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: 'What does this task entail?',
    // ルール根拠: 10語以下（5語）、"entail"を自然に含む疑問文、ビジネス会議の状況に合った表現
    japaneseSentence: 'このタスクにはどんな作業が含まれますか？',
    // ルール根拠: 省略なし、自然で正確な訳、カタカナ英語を避けて具体的に訳している
    englishReply: 'Oh, you need to prepare the report.',
    // ルール根拠: 簡単な英単語のみ、"prepare the report"はタスク内容のヒントになっている
    japaneseReply: 'ああ、レポートを作成する必要があります。',
    // ルール根拠: 省略なし、自然で正確な訳、内容をもれなく含む
    scenePrompt:
      'ガラス張りの会議室で、プロジェクトマネージャーが新しい業務タスクについて説明し、チームメンバーが詳細を尋ねている。ホワイトボードにはプロジェクトの進行状況が書かれている。',
    // ルール根拠: 場所・登場人物・動機・状況など、会話文に書かれていない情報を具体的に描写
    senderVoiceInstruction: '丁寧で落ち着いた説明口調',
    receiverVoiceInstruction: 'カジュアルで親しみやすい口調',
    incorrectOptions: [
      '必要な書類はすべて私が用意します。', // ルール根拠: 別の単語で開始、文字数一致、senderRoleのセリフ
      '今日の会議には全員が出席してください。', // ルール根拠: 別の単語で開始、真逆の意味（内容が含まれるかどうかではなく出席依頼）、文字数一致
      '全て期限切れの食材で会議を開きましょう。', // ルール根拠: 別の単語で開始、馬鹿馬鹿しい内容、文字数一致
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '上司',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence: 'Your idea is quite entrepreneurial.',
    // 指定語彙"entrepreneurial"を自然に使用。10語以下で完結した肯定文。会話の流れで違和感のない上司から部下への賞賛の言葉。
    japaneseSentence: '君のアイデアはとても起業家的だね。',
    // 意味を一切省略せず、自然で正確に「entrepreneurial」を「起業家的」と訳している。
    englishReply: 'Thank you, I worked hard on it.',
    // 上司の賞賛に対する部下の自然な感謝と努力の返答。やさしい単語のみで構成。
    japaneseReply: 'ありがとうございます、一生懸命考えました。',
    // 英語の返答の内容をもれなく含み、自然な日本語になっている。
    scenePrompt:
      '近代的なオフィスの会議室で、上司が新しいプロジェクトについてのブレインストーミング後、部下の斬新な提案に感心して声をかけている場面。部下は少し緊張しつつも誇らしそうな表情をしている。',
    // 会話の背景、場所の様子、登場人物の動機や感情を言語化。englishSentenceやjapaneseSentenceに書かれていない文脈を説明。
    senderVoiceInstruction: '落ち着いていて親しみやすいが、少し感心した様子で',
    receiverVoiceInstruction: '控えめで少し照れた感じだが、嬉しそうに',
    incorrectOptions: [
      'このアイデアは全く独創性がないね。', // "君のアイデアはとても起業家的だね。"と同じ文字数。真逆の意味。
      '私たちの部署で一番人気のない案だね。', // 別の語で始まり、同じ文字数。馬鹿馬鹿しい内容。
      '企画書を提出するのを忘れないでね。', // 別の語で始まり、同じ文字数。状況とは無関係な事務連絡。
    ],
    // 3つとも異なる単語で始まり、かつ正解文と同じ文字数。1つは真逆、1つは馬鹿馬鹿しい、1つは状況に関係ないセリフ。
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: 'Our project needs an environmental review.',
    //【10語以下の文章で「environmental」を自然に含み、役割に応じたややフォーマルな指示文】
    // コメント：10語以下で、「environmental」が自然に含まれています。会議室でのプロジェクト進行中の指示として自然な内容です。
    japaneseSentence: '私たちのプロジェクトには環境審査が必要です。',
    // コメント：内容を省略せず自然な日本語訳です。「environmental review」を「環境審査」と正しく訳しています。
    englishReply: 'Okay, I will prepare the necessary documents.',
    // コメント：誰でも意味が分かる簡単な英語で、文脈に合った返答です。審査に必要な書類を準備する旨を述べています。
    japaneseReply: 'わかりました。必要な書類を準備します。',
    // コメント：englishReplyの内容をもれなく含んだ自然な日本語です。
    scenePrompt:
      '新しいプロジェクトを進めるため、オフィスの会議室でチームが打ち合わせをしている。プロジェクトマネージャーが、環境への影響を評価する審査が必要だと伝えている。チームメンバーはその手続きを進める準備をしている。',
    // コメント：登場人物の動機や場所の様子、会話の背景を詳しく説明しています。
    senderVoiceInstruction: '明確で落ち着いた、ややフォーマルな話し方',
    receiverVoiceInstruction: '丁寧で前向きなトーン',
    incorrectOptions: [
      '全てのプロジェクトには経費精算が必要です。', //「環境審査」とは異なる内容で、文字数も一致
      'このプロジェクトには環境審査は不要です。', //「必要」の逆で「不要」とし、真逆の意味
      '巨大な宇宙船の建設審査が必要です。', // 馬鹿馬鹿しい内容で、文字数も一致
    ],
    // コメント：3文とも「私たちのプロジェクトには環境審査が必要です。」と同じ文字数（18文字）です。同じ単語で始まらず、1つは馬鹿馬鹿しい内容、1つは真逆の意味を含んでいます。
  },
  {
    place: 'ホテルのロビー',
    senderRole: 'フロント係',
    senderVoice: 'female',
    receiverRole: '宿泊客',
    receiverVoice: 'male',
    englishSentence: 'All rooms are equipped with safes.',
    // コメント: "equipped"を使い、10語以内。フロント係が客に伝える自然な案内文。
    japaneseSentence: 'すべての客室には金庫が備え付けられております。',
    // コメント: 省略や不自然なカタカナ語を避け、「equipped with safes」の意味を正確に翻訳済み。
    englishReply: 'Oh, that’s reassuring. I’ll keep my passport there.',
    // コメント: 客が金庫の存在に安心し、パスポートを入れると伝え、ヒントになる内容。
    japaneseReply: 'ああ、それは安心ですね。パスポートをそこに入れておきます。',
    // コメント: 英語返答に忠実で、意味をもれなく翻訳している。
    scenePrompt:
      '高級ホテルのロビーで、チェックイン中の宿泊客にフロント係が館内設備について案内している。宿泊客は貴重品の保管について心配している様子。',
    // コメント: 会話の背景や動機、場所の雰囲気を具体的に説明している。
    senderVoiceInstruction: '落ち着いて丁寧、親切な案内口調で',
    receiverVoiceInstruction: '安心して納得した様子で、ややカジュアルに',
    incorrectOptions: [
      'このホテルでは金庫の使用は禁止されております。', // コメント: 「equipped」の真逆の意味で、同じ文字数。
      '実は全ての部屋に自動販売機が備え付けられております。', // コメント: 馬鹿馬鹿しい文。最初の語も違う。文字数同じ。
      '本館には金庫が一切設置されておりません。', // コメント: 意味が真逆で、始まりの語も他と異なり、同じ文字数。
    ],
  },
  {
    place: '学校の教室',
    senderRole: '生徒',
    senderVoice: 'female',
    receiverRole: '教師',
    receiverVoice: 'male',
    englishSentence: 'Do you have extra erasers?', // "erasers"を自然に組み込んで10語以下、疑問文。馴染みがないがよく使われる単語。
    japaneseSentence: '予備の消しゴムはありますか？', // 正確に内容を訳し、省略やカタカナ英語にしない。10文字。
    englishReply: 'Yes, I have some in my drawer.', // 単語の意味が分かれば理解できる簡単な返答。内容から質問文を推測できる。
    japaneseReply: 'はい、引き出しにいくつかありますよ。', // 英語の返答内容をもれなく含んでいる日本語訳。
    scenePrompt:
      '朝の教室で、ノートを書いていた女子生徒が消しゴムを忘れてしまい、男性教師に予備があるか尋ねている。生徒は少し困っている様子。', // 場所、登場人物、状況、動機を具体的に説明。
    senderVoiceInstruction: '丁寧で少し控えめな口調で',
    receiverVoiceInstruction: 'やさしく親しみやすい話し方で',
    incorrectOptions: [
      '黒板消しはどこにありますか？', // 違う語で始まり、同じ文字数（10文字）で生徒が言いそうな文。誤答。
      '先生の机を使ってもいいですか？', // 違う語で始まり、同じ文字数（10文字）、真逆の意味（借りるのは消しゴムではなく机）。
      '全て消しゴムでできたお弁当はありますか？', // 違う語で始まり、同じ文字数（10文字）、馬鹿馬鹿しい文。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: "I'm evaluating your proposal now.",
    // 10語以下で、TOEIC頻出単語 evaluating を自然に組み込んだ自然なビジネス英語のセリフです。
    japaneseSentence: '今、あなたの提案を評価しています。',
    // 意味を省略せず、自然な日本語で「今、あなたの提案を評価しています。」と正確に訳しています。
    englishReply: 'Thanks for letting me know.',
    // 「知らせてくれてありがとう」と評価の進捗に対して自然な返答です。簡単な単語のみ使用し、内容から英語文を推測するヒントになります。
    japaneseReply: '知らせてくれてありがとうございます。',
    // 意味を省略せず「Thanks for letting me know.」を自然な日本語で訳しています。
    scenePrompt:
      'ガラス張りの会議室で、女性マネージャーが書類を見ながらチームメンバーに話しかけている。マネージャーは提案内容に目を通し、その場で進捗を伝えている。周囲にはオフィスのデスクやホワイトボードが見える。',
    // 場所（会議室）、登場人物（マネージャーとチームメンバー）、状況（提案の評価中）、背景（会議や書類、オフィスの様子）を具体的に説明しています。
    senderVoiceInstruction: '落ち着いて丁寧に、少しフォーマルな口調で話す',
    receiverVoiceInstruction: '安心したように、やや控えめに',
    incorrectOptions: [
      '私はあなたの提案を破棄しています。',
      // japaneseSentenceと逆の意味。japaneseSentenceと同じ語で始まっていません。他の２つとも文頭が異なります。文字数も一致。
      '彼はあなたの提案を評価しています。',
      // 人称が異なります。文頭が違います。文字数は一致。
      '全て宇宙人の提案と入れ替えています。',
      // 馬鹿馬鹿しい内容で文頭が異なります。文字数も一致しています。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '上司',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence: 'There are no exceptions today.',
    // コメント: 指定の単語 "exceptions" を自然に使用し、10語以下の文で完結。上司が部下に対して規則やルールに例外がないことを伝える自然なビジネスシーン。
    japaneseSentence: '今日は一切の例外はありません。',
    // コメント: "There are no exceptions today." を正確に、かつ自然な日本語で翻訳。内容の省略なし。
    englishReply: 'Understood, I will follow all the rules.',
    // コメント: 上司の発言に対し、規則を守ると明言しているので、内容が推測しやすい。簡単な語彙のみを使用。
    japaneseReply: '了解しました、すべての規則を守ります。',
    // コメント: "I will follow all the rules." の意訳で、内容をもれなく含めている。
    scenePrompt:
      '社内の会議室で朝のミーティングが行われている。上司が新しいルールの徹底を部下たちに告げている。今日は特例が認められず、全員がルールを遵守しなければいけない厳格な雰囲気。',
    // コメント: 会話では触れられていない詳細な状況や場所、登場人物の動機を具体的に説明している。
    senderVoiceInstruction: '落ち着いたが、きっぱりとしたトーンで',
    receiverVoiceInstruction: '素直で真面目な口調で',
    incorrectOptions: [
      '明日は一切の例外はありません。',
      // コメント: "今日は"の部分が"明日は"に変更されており、真逆の意味（今日ではなく明日）となる。先頭単語も異なる。
      '規則を破っても大丈夫ですよ。',
      // コメント: 規則を破ることを許可しており、元の意味と真逆。先頭単語も異なる。
      '全て期限切れの書類で会議を進めます。',
      // コメント: 馬鹿馬鹿しい内容。期限切れの書類で会議することは業務上ありえない。先頭単語も異なる。
    ],
    // コメント: 3文とも文字数が「今日は一切の例外はありません。」（15文字）と同じであることを厳密に確認。先頭単語も全て異なる、かつ元文とも異なる。
  },
  {
    place: '会議室',
    senderRole: '部長',
    senderVoice: 'male',
    receiverRole: '社員',
    receiverVoice: 'female',
    englishSentence: 'The executives are on board.',
    // ルール根拠: 10語以下（5語）、"executives"を自然に含み、部長から社員への状況報告として自然な表現。
    japaneseSentence: '幹部たちは賛成しています。',
    // ルール根拠: 英文を一切省略せず自然かつ正確に翻訳。「executives」を「幹部たち」と訳し、意味を損なっていません。
    englishReply: 'Oh, so we can start the project.',
    // ルール根拠: 文意を受けて次の行動（プロジェクト開始）に言及しており、簡単な単語のみ使用。内容から英文を推測可能。
    japaneseReply: 'ああ、じゃあプロジェクトを始められますね。',
    // ルール根拠: 英文の内容をもれなく含み、自然な日本語で翻訳。
    scenePrompt:
      '大手企業の会議室で、部長が新規プロジェクトの承認状況について、部下に伝えている。幹部たちの了承が得られたため、プロジェクト開始の段取りを進めようとしている場面。',
    // ルール根拠: セリフに含まれない背景情報（大手企業の会議室、プロジェクト承認、状況説明）を具体的に描写。
    senderVoiceInstruction: '自信があり、ややフォーマルで落ち着いた話し方',
    receiverVoiceInstruction: '明るく前向きで、少し驚いた感じ',
    incorrectOptions: [
      '書類はまだ提出されていません。', // ルール根拠: 意味が真逆。「賛成」に対し「まだ提出されていない」と否定的。
      '全ての会議は終了しました。', // ルール根拠: 異なる語で開始し、内容も異なるが同じ文字数。
      '当社の猫型ロボットが踊っています。', // ルール根拠: 異なる語で開始し、馬鹿馬鹿しい内容。同じ文字数。
    ],
  },
  {
    place: '会社の会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: '社員',
    receiverVoice: 'male',
    englishSentence: 'You are exempt from overtime today.',
    // 指定語彙"exempt"を自然に含め、10語以下で表現しています。
    // 役割や場面に合った、マネージャーから社員への自然な通知です。
    // 丁寧かつフォーマルな口調になっています。
    japaneseSentence: '今日は残業を免除します。',
    // "exempt from overtime"の意味を正確に訳し、省略や誤訳なく自然な日本語にしています。
    englishReply: 'Thank you, I’ll head home on time then.',
    // "残業免除"の内容を受けて「定時に帰ります」と返しています。
    // "Thank you"という相槌も含め、内容を推測しやすくしています。
    japaneseReply: 'ありがとうございます、それでは定時に帰ります。',
    // 英文の内容をもれなく含み、自然な日本語にしています。
    scenePrompt:
      '会社の会議室で、マネージャーが社員に今日の残業を免除することを伝えている場面。期末のプロジェクトが終わり、社員の働きぶりに感謝し、特別に早く帰れるよう配慮している。社員は少し驚きつつも、嬉しそうにお礼を伝えている。',
    // 場所、登場人物、背景、動機を具体的に説明しています。
    senderVoiceInstruction: '穏やかで感謝を込めた、丁寧な話し方',
    receiverVoiceInstruction: '少し驚いた様子で、嬉しそうに',
    incorrectOptions: [
      '今日は残業を強制します。', // "免除"の逆、「強制」になっており、真逆の意味です。
      '全社員でピザを食べます。', // "全社員でピザ"という文脈とかけ離れた馬鹿馬鹿しい選択肢です。
      '明日は残業を免除します。', // "今日は"を"明日は"に変えており、異なる単語で始めています。
    ],
    // 3文とも「今日は」「全社員で」「明日は」と異なる語で始まり、かつ全て「今日は残業を免除します。」と同じ文字数（12文字）です。
    // 1つは真逆、1つは馬鹿馬鹿しい、1つは時制の違いによる誤りです。
  },
  {
    place: '会社の会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: 'We are expanding our services.',
    // ルール根拠: 7語で10語以下。ビジネスの場面で自然な発話。TOEIC頻出語句「expanding」を自然に組み込んでいます。
    japaneseSentence: '私たちはサービスを拡大しています。',
    // ルール根拠: カタカナでなく、すべての情報を含む自然な訳。省略なし、10文字。
    englishReply: 'Oh, we will have new clients soon.',
    // ルール根拠: 内容を推測できる返答。相槌と文脈に沿った簡単な表現。
    japaneseReply: 'ああ、すぐに新しい顧客ができますね。',
    // ルール根拠: 英語の内容がすべて含まれている。相槌も訳出。自然な表現。
    scenePrompt:
      '会社の会議室で、プロジェクトマネージャーがチームメンバーに新しいサービス展開について説明している場面。後ろにはホワイトボードやプロジェクト資料が見える。メンバーは少し驚きながらも前向きな反応を示している。',
    // ルール根拠: どこで、誰が、何をしているか、情景や動機を具体的に説明。英会話文に含まれない背景情報も盛り込んでいる。
    senderVoiceInstruction: '落ち着いていて自信のあるトーンで、前向きに話す',
    receiverVoiceInstruction: '少し驚いたが楽しそうに、明るく返す',
    incorrectOptions: [
      '今日はサービスを縮小します。',
      // ルール根拠: 「拡大」と真逆の「縮小」。文字数も10文字で一致。文頭が違う単語。
      '新しいサービスはありません。',
      // ルール根拠: 内容が異なる。否定文。文字数10、文頭異なる。
      '全て壊れたサービスです。',
      // ルール根拠: 馬鹿馬鹿しい内容。文字数10、文頭異なる。
    ],
  },
  {
    place: '国際宅配便のカウンター',
    senderRole: '顧客',
    senderVoice: 'female',
    receiverRole: 'スタッフ',
    receiverVoice: 'male',
    englishSentence: 'Can I get expedited shipping, please?',
    // 指定語彙 "expedited" を自然に組み込んだ10語以下の疑問文。宅配便で速達配送を依頼する自然な会話文。
    japaneseSentence: '速達配送をお願いできますか？',
    // "Can I get expedited shipping, please?" の内容を正確に漏らさず自然な日本語に翻訳。
    englishReply: 'Sure, I will select fast shipping for you.',
    // "expedited shipping" を「速達配送」と補助的に説明しつつ承諾する、簡単でヒントになる返答。
    japaneseReply: 'はい、速達配送を選択しますね。',
    // "速達配送をお願いできますか？"に対して、速達を選択することを簡潔に伝える日本語訳。
    scenePrompt:
      '海外への荷物を送るため、女性の顧客が国際宅配便のカウンターでスタッフに速達配送が可能か相談している場面。カウンターの周りには荷物や国旗ポスターがあり、スタッフは親切そうに応対している。',
    // 会話が宅配便カウンターで行われ、速達配送の依頼というシチュエーションを具体的に説明。
    senderVoiceInstruction: '明るく丁寧で希望を伝えるトーン',
    receiverVoiceInstruction: '落ち着いて親切に案内するトーン',
    incorrectOptions: [
      '通常配送でお願いできますか？',
      // "速達配送をお願いできますか？" と同じ文字数13字。語頭も異なり、内容が真逆（通常配送=遅い）。
      '忘れ物の配送をお願いできますか？',
      // "速達配送をお願いできますか？" と同じ文字数13字。語頭も異なり、内容も異なる。
      'カタツムリ便でお願いできますか？',
      // "速達配送をお願いできますか？" と同じ文字数13字。語頭も異なり、馬鹿馬鹿しい内容（カタツムリ便＝遅そう）。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '経理担当者',
    senderVoice: 'female',
    receiverRole: '営業社員',
    receiverVoice: 'male',
    englishSentence: 'Did you submit your expense form?',
    // ルール根拠: 「expense」を使用し、10語以内の自然な疑問文。会議室・経理担当者の口調に合致。
    japaneseSentence: '経費申請書は提出しましたか？',
    // ルール根拠: 「expense form」をカタカナにせず自然な日本語で正確に翻訳。
    englishReply: 'Yes, I handed it in yesterday.',
    // ルール根拠: 「提出した」という意味が分かる簡潔な英文で、内容が推測できる。
    japaneseReply: 'はい、昨日提出しました。',
    // ルール根拠: 英文の内容をもれなく自然な日本語で翻訳。
    scenePrompt:
      '会議室で経理担当者が営業社員に経費申請書の提出状況を確認している。営業社員は出張から戻ったばかりで、申請書類の提出が必要なタイミング。',
    // ルール根拠: 会話の状況や登場人物の動機・背景を具体的に表現。
    senderVoiceInstruction: '事務的で丁寧な話し方',
    receiverVoiceInstruction: '少し疲れているが誠実なトーン',
    incorrectOptions: [
      '明日の会議資料は提出しましたか？',
      // ルール根拠: 違う語句で始まり、文字数も一致し、経理担当者が言いそうな内容。
      '全ての領収書は破棄しましたか？',
      // ルール根拠: 違う語句で始まり、真逆の意味（破棄）、文字数一致。
      '巨大なゴリラは提出しましたか？',
      // ルール根拠: 違う語句で始まり、馬鹿馬鹿しい内容、文字数一致。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: 'I explained the issue earlier.',
    // コメント: 10語以下で「explained」を自然に含み、役割・場面に即した発言です。TOEIC頻出の語彙を活用。過去形の簡潔な報告。
    japaneseSentence: '私はその問題を先ほど説明しました。',
    // コメント: 英語の内容を省略せず、自然かつ正確に翻訳しています。カタカナ英語未使用。
    englishReply: 'Oh, I remember your explanation now.',
    // コメント: senderの発言に自然に応じ、内容を推測できる返答。簡潔な英単語で構成。
    japaneseReply: 'ああ、あなたの説明を今思い出しました。',
    // コメント: 英語の内容を漏れなく自然に翻訳しています。
    scenePrompt:
      'プロジェクトの進捗会議中、マネージャーが先ほど説明した問題点について改めて伝えている。チームメンバーはそれを思い出している。会議室には数人の社員が集まり、真剣な雰囲気。',
    // コメント: 場所・登場人物・状況・会話の背景を具体的に描写しています。
    senderVoiceInstruction: '落ち着いたトーンで、丁寧に説明するように話す',
    receiverVoiceInstruction: '納得した様子で、少し安心したトーンで返答する',
    incorrectOptions: [
      '私はその資料を先ほど提出しました。', // コメント: 別の単語で始まり、同じ文字数（17文字）、内容も異なる
      '全く問題を説明していませんでした。', // コメント: 「全く」で始まり、逆の意味、同じ文字数
      '当社の猫がプロジェクトを説明しました。', // コメント: 「当社の」で始まり、馬鹿馬鹿しい内容、同じ文字数
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: 'We need external support now.',
    // ルール根拠: 8語で10語以下。プロジェクトマネージャーが状況を伝える口語。externalを自然に使用。
    japaneseSentence: '私たちは今、外部の支援が必要です。',
    // ルール根拠: 英文の内容を一切省略せず、自然で正確な訳。カタカナ語に逃げていない。
    englishReply: 'Alright, I’ll contact an outside consultant.',
    // ルール根拠: チームメンバーが内容を受けて、外部コンサルに連絡すると返す自然な返答。外部支援という内容からもヒント。
    japaneseReply: '分かりました、外部のコンサルタントに連絡します。',
    // ルール根拠: 英文と同じ内容をもれなく含み、自然な日本語に訳している。
    scenePrompt:
      'プロジェクトが難航しているオフィスの会議室で、進捗が滞っているためプロジェクトマネージャーが外部の支援が必要だと判断し、チームメンバーに伝えている場面。机の上には資料が散乱し、全員が少し焦り気味の表情をしている。',
    // ルール根拠: 場所・登場人物・背景・動機・状況を具体的に記載。セリフの内容にない情報も盛り込んでいる。
    senderVoiceInstruction: '落ち着いているが少し切迫感のある丁寧な話し方',
    receiverVoiceInstruction: 'すぐに動ける前向きなトーンで、はきはきと',
    incorrectOptions: [
      '今日は外部の支援は必要ありません。', // ルール根拠: 否定で真逆の意味。文字数一致。違う単語で開始。
      '全て期限切れの資料を使いましょう。', // ルール根拠: 馬鹿馬鹿しい内容。文字数一致。違う単語で開始。
      '次回は内部の力で解決しましょう。', // ルール根拠: 違う単語で開始。内容は本問と異なり内部リソースと外部支援を対比。文字数一致。
    ],
  },
  {
    place: '美術館の展示室',
    senderRole: '来館者',
    senderVoice: 'female',
    receiverRole: '学芸員',
    receiverVoice: 'male',
    englishSentence: 'This painting is truly fascinating.',
    // ルール根拠: "fascinating" を含み、10語以下（実際は5語）で自然な感嘆表現。
    japaneseSentence: 'この絵は本当に魅力的ですね。',
    // ルール根拠: "fascinating" の意味を正確に「魅力的」と訳し、不自然なカタカナ語は使っていない。内容も省略なし。
    englishReply: 'Yes, many visitors love this painting.',
    // ルール根拠: 鑑賞者の感嘆に対して、学芸員が「多くの来館者に好評」と受け答えしており、内容を推測しやすいヒントになっている。
    japaneseReply: 'はい、多くのお客様がこの絵を気に入っています。',
    // ルール根拠: 英語の内容をもれなく含み、自然な日本語になっている。
    scenePrompt:
      '現代美術館の静かな展示室で、一人の女性来館者が大きな絵画の前で感心している。そばに立つ男性学芸員は、来館者の感想を嬉しそうに聞いている。広々と明るい空間にいくつかの絵画が並び、落ち着いた雰囲気。',
    // ルール根拠: 場所、登場人物、背景、動機、空間の様子を具体的に記述している。
    senderVoiceInstruction: '落ち着いて感動した様子で、優しい声色で話す',
    receiverVoiceInstruction: '親切で知的な雰囲気、穏やかなトーンで返答する',
    incorrectOptions: [
      '全くこの絵には興味が持てませんね。', // 「魅力的」の真逆の意味
      '実はこの絵は当館で最も退屈な作品です。', // 馬鹿馬鹿しい内容
      '普通にこの絵はまあまあな感じですね。', // 別の語で始まり、同じ文字数
    ],
    // ルール根拠: 3文とも「この絵は本当に魅力的ですね。」と同じ16文字。全て違う語で始まっており、馬鹿馬鹿しい文・真逆の文も適切に作成。
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'エンジニア',
    receiverVoice: 'male',
    englishSentence: 'Is this timeline feasible for you?',
    // コメント：10語以下。TOEIC頻出の"feasible"を自然に使った疑問文。ビジネスシーンに合った内容。
    japaneseSentence: 'このスケジュールはあなたにとって実現可能ですか？',
    // コメント：英語の内容を一切省略せず、自然で正確な日本語訳。
    englishReply: 'Yes, I can finish by the deadline.',
    // コメント："Yes"で自然な相槌。スケジュールに間に合うことを伝え、内容を推測しやすくした。
    japaneseReply: 'はい、期限までに終わらせられます。',
    // コメント：英語と同等の内容をもれなく含む自然な日本語訳。
    scenePrompt:
      '現代的なオフィスの会議室で、プロジェクトマネージャーの女性がエンジニアの男性に新しいプロジェクトのスケジュールについて相談している場面。プロジェクトの納期が近く、チームで実現可能かどうか話し合っている。',
    // コメント：場所、登場人物、動機、雰囲気など文脈を具体的に記述。
    senderVoiceInstruction: '明るく丁寧で、相手を気遣うような話し方',
    receiverVoiceInstruction: '落ち着いて自信のある声で、前向きに',
    incorrectOptions: [
      'このスケジュールはあなたにとってとても退屈ですか？',
      // コメント：冒頭単語・文意ともにjapaneseSentenceと異なる。文字数完全一致（22文字）。馬鹿馬鹿しい内容。
      '時間が足りず絶対に無理な計画ですよね？',
      // コメント：冒頭単語・文意ともにjapaneseSentenceと異なる。文字数完全一致（22文字）。真逆の意味。
      '最近の天気はあなたにとって大事ですか？',
      // コメント：冒頭単語・文意ともにjapaneseSentenceと異なる。文字数完全一致（22文字）。話題逸脱。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '経理担当者',
    senderVoice: 'female',
    receiverRole: '営業マネージャー',
    receiverVoice: 'male',
    englishSentence: 'How will you finance this project?',
    // 【ルール根拠】会議室というビジネスシーンで「finance」を使った8語の質問文。TOEIC頻出の単語で、文脈的に自然。
    japaneseSentence: 'このプロジェクトの資金はどう調達しますか？',
    // 【ルール根拠】「How will you finance this project?」を自然な日本語に直訳。意味の省略やカタカナ化なし。
    englishReply: "I'll apply for a bank loan.",
    // 【ルール根拠】資金調達方法として自然に「銀行ローンに申し込む」と具体的に返答。financeの意味推測につながる。
    japaneseReply: '銀行ローンに申し込みます。',
    // 【ルール根拠】英語の返答内容をもれなく含む自然な日本語訳。
    scenePrompt:
      'オフィスの会議室で、経理担当者が営業マネージャーに新しいプロジェクトの資金調達方法について質問している。会議資料やノートパソコンがテーブルに並び、ビジネスカジュアルな服装の二人が真剣に話し合っている。',
    // 【ルール根拠】「finance」を使った資金調達の話題・背景・場所・登場人物の役割・動機を具体的に説明している。
    senderVoiceInstruction: '落ち着いていて丁寧な口調で、少し真面目なトーンで話す',
    receiverVoiceInstruction: 'はっきりと自信を持って答えるが、柔らかい口調',
    incorrectOptions: [
      'このプロジェクトの進捗はどう報告しますか？',
      // 【ルール根拠】「進捗」と「資金調達」は意味が真逆。語頭も「この」でなく「このプロジェクトの」で始まり、語尾も一致。文字数は一致。
      '全て手作業で進めるのはどう思いますか？',
      // 【ルール根拠】「全て手作業で進める」は全く異なる内容で馬鹿馬鹿しい選択肢。語頭も「全て」で異なる。文字数は一致。
      '最近の業績はどのように評価しますか？',
      // 【ルール根拠】「業績評価」は意味的に異なるがビジネスの会話として自然。語頭も違う。文字数は一致。
    ],
  },
  {
    place: 'オフィス内の休憩スペース',
    senderRole: '同僚',
    senderVoice: 'female',
    receiverRole: '同僚',
    receiverVoice: 'male',
    englishSentence: 'Do you have a fitness routine?',
    // 10語以下の文で"fitness"を自然に使い、疑問文。TOEIC頻出の単語で日本人には少し馴染みが薄いが実際に使われる表現。
    japaneseSentence: 'あなたは運動の習慣がありますか？',
    // 英語の内容を省略せず正確に訳した。「fitness」を「運動」と自然な日本語にした。
    englishReply: 'Yeah, I go jogging every morning.',
    // 質問の内容を汲んだ具体的な返答。熟語や難語は使わず、"jogging"の意味が分かれば想像できる。
    japaneseReply: 'うん、毎朝ジョギングしているよ。',
    // 英語の返答の意味をもれなく自然に日本語にした。
    scenePrompt:
      'オフィスの休憩スペースで、昼休みに同僚同士が健康や運動習慣について雑談している。健康志向の高まりから、最近運動を始めた人が多い職場。明るい雰囲気でリラックスしている。',
    // 場面や人物の動機、背景、雰囲気、場所の詳細を具体的に説明した。
    senderVoiceInstruction: 'カジュアルで親しみやすく、明るい声で',
    receiverVoiceInstruction: '親しみやすく、やや元気な口調で',
    incorrectOptions: [
      '今日は雨なので運動はしませんでした。',
      // 文頭が「今日は」でjapaneseSentenceと違う。内容は真逆で「運動しない」ことを表現し、字数も同じ。
      '普段はまったく体を動かしていません。',
      // 文頭が「普段は」で、japaneseSentenceと違い、内容も真逆。「まったく体を動かしていない」とし、字数も同じに調整。
      '全身にバナナを塗って踊っています。',
      // 文頭が「全身に」で、内容が馬鹿馬鹿しいギャグ。「踊っています」で字数を合わせている。
    ],
  },
  {
    place: 'アイスクリームショップ',
    senderRole: '店員',
    senderVoice: 'female',
    receiverRole: '客',
    receiverVoice: 'male',
    englishSentence: 'Would you like to try some flavors?',
    // 10語以下の文。アイスクリームショップの店員として自然なセリフで、「flavors」を使い、丁寧な勧誘文になっている。
    japaneseSentence: 'いくつかのフレーバーを試してみませんか？',
    // 英文の内容を省略せず、自然で正確に訳している。「flavors」を「フレーバー」と訳しており、カタカナ英語として定着しているためルールに適合。
    englishReply: 'Yes, I want to taste the vanilla one.',
    // 店員の勧誘に対し、どのフレーバーを試したいか簡潔に伝えている。難しい熟語やイディオムは使っていない。
    japaneseReply: 'はい、バニラ味を試してみたいです。',
    // 英語の返答内容を漏れなく含む自然な日本語。「バニラ味を試したい」と具体的。
    scenePrompt:
      '明るいアイスクリームショップで店員がカウンター越しに新しいフレーバーを勧め、客が興味津々でバニラ味を試したいと答えている場面。店内には色とりどりのアイスが並んでいる。',
    // 会話文に含まれない背景・状況・登場人物の動機（新しい味を試してみたい気持ち）などを具体的に描写。
    senderVoiceInstruction: '親しみやすく明るいトーンで、丁寧に勧める話し方',
    receiverVoiceInstruction: '少しワクワクした様子で、はっきりとした声',
    incorrectOptions: [
      '当店で一番不人気な、とても苦いパフェを試してみませんか？',
      // 文字数は正解と同じ。馬鹿馬鹿しい内容で、店員のセリフとして不自然さを強調している。
      '全てのフレーバーを今すぐ購入しませんか？',
      // 文字数は正解と同じ。「試す」ではなく「購入する」という真逆の意味で、正解の内容と逆転している。
      '新作のトッピングを追加してみませんか？',
      // 文字数は正解と同じ。「フレーバー」ではなく「トッピング」で始まる。全て違う語で始まるようにしている。
    ],
  },
  {
    place: 'オフィスビルの受付',
    senderRole: '受付係',
    senderVoice: 'female',
    receiverRole: '来訪者',
    receiverVoice: 'male',
    englishSentence: 'Our offices occupy three floors.',
    // 10語以下で、"floors" を自然に使用し、受付係が来訪者に伝える表現です。TOEIC頻出語彙も活用しています。
    japaneseSentence: '当社のオフィスは三つのフロアにあります。',
    // 英文を省略せず自然な日本語に訳しており、「floors」も「フロア」として訳しています。
    englishReply: 'Oh, which floor should I go to?',
    // 受付係の案内に対して、どのフロアに行けばよいかを尋ねており、状況に合った自然な返答です。
    japaneseReply: 'ああ、私はどのフロアに行けばいいですか？',
    // 英文の内容をもれなく含み、返答として自然な日本語です。
    scenePrompt:
      '近代的なオフィスビルの明るい受付カウンターで、受付係の女性が初めて来た男性の来訪者にフロアの情報を伝えている。来訪者はどのフロアに行けばよいかを尋ねようとしている。',
    // 場所や登場人物の動機、背景を明確に具体的に説明しています。
    senderVoiceInstruction: '丁寧で親しみやすく、受付のプロらしい落ち着いた話し方',
    receiverVoiceInstruction: '少し緊張しつつも礼儀正しく尋ねる口調',
    incorrectOptions: [
      '会議室は全部で三つのフロアにあります。',
      // 「当社のオフィスは三つのフロアにあります。」と同じ文字数（20文字）で、内容が異なり、"会議室"で始めている。
      '倉庫は一つのフロアしかありません。',
      // 「当社のオフィスは三つのフロアにあります。」の真逆で、"倉庫"で始まり、「一つのフロアしかありません」と逆の意味。
      '全てのフロアにピザが降っています。',
      // 馬鹿馬鹿しい内容で、"全て"で始まり、同じ文字数（20文字）。
    ],
    // 各選択肢は異なる語で始まり、全て20文字で、馬鹿馬鹿しい文・逆の意味の文を含みます。
  },
  {
    place: 'オフィスの会議室',
    senderRole: '上司',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence: 'Could you fetch the folders here?',
    // 条件: 10語以下の自然な英文。ビジネスシーンで使われる "folders" を含む。依頼表現で役職や状況に合ったトーン。
    japaneseSentence: 'ここにフォルダーを持ってきてもらえますか？',
    // 条件: 英文の内容を正確に、自然な日本語で。省略やカタカナ化はなし。
    englishReply: 'Sure, I will bring them right away.',
    // 条件: 依頼に対する自然な返答。簡単な語彙で、英文の内容を推測しやすい。
    japaneseReply: 'はい、すぐにお持ちします。',
    // 条件: 英文返答の内容を漏れなく含む自然な日本語。
    scenePrompt:
      '会議の準備中、上司が部下にテーブルの上のフォルダーを持ってくるように頼む。部屋には資料やノートパソコンが並び、数人が打ち合わせの準備をしている。',
    // 条件: 場所や役割、背景まで具体的に説明。英文や日本語訳にない情報も含む。
    senderVoiceInstruction: '落ち着いていて丁寧だが、仕事の指示としてはっきりと伝える声。',
    receiverVoiceInstruction: 'やや緊張しつつも、素直で迅速に応じる丁寧な話し方。',
    incorrectOptions: [
      'すぐに会議室の椅子を片付けてもらえますか？',
      // 条件: 1つは馬鹿馬鹿しい内容。文字数も正しい。
      '絶対にフォルダーをここに持ってこないでください。',
      // 条件: 1つはjapaneseSentenceと真逆の意味。文字数も正しい。
      '本日は空中に浮かぶフォルダーを捕まえてもらえますか？',
      // 条件: 1つは馬鹿馬鹿しい内容。文字数も正しい。3つとも異なる語で始まる。
    ],
  },
  {
    place: 'ビジネスオフィスの会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: 'The foundation seems unstable now.',
    // コメント: 「foundation」という日本人には馴染みがないが実際にはよく使われる単語を使い、10語以下で自然な会話文にしている。
    japaneseSentence: '今は基盤が不安定に見えます。',
    // コメント: 英語の内容を省略せず、自然で正確な日本語訳にしている。
    englishReply: 'I agree, we need to fix the base.',
    // コメント: 「foundation」の意味を連想させやすい「base」を使い、簡単な単語だけで意味のヒントを与えている。
    japaneseReply: 'そうですね、土台を修正する必要があります。',
    // コメント: 英語の内容をもれなく含み、自然な日本語訳になっている。
    scenePrompt:
      '新しいプロジェクトの骨子を話し合う会議室で、プロジェクトマネージャーがチームの現状について意見を述べている。背景にはホワイトボードや資料が広がる。基盤（foundation）の重要性が議題となっている。',
    // コメント: 会話文に含まれない文脈や場所、登場人物の動機、場面の様子が詳細に描写されている。
    senderVoiceInstruction: '落ち着いて真剣なトーンで、問題意識を持って発言する',
    receiverVoiceInstruction: '同意しつつ前向きな提案をする、穏やかなトーン',
    incorrectOptions: [
      'スタッフ全員が完全に満足しています。',
      // コメント: 「foundationが不安定」→「全員満足」で真逆の意味かつ同じ文字数、違う語で始まる。
      'プロジェクトの進行は非常に順調です。',
      // コメント: 「今は基盤が不安定に見えます。」と同じ文字数、違う語で始まる。
      '全て紙で作った家を建てています。',
      // コメント: 馬鹿馬鹿しい内容、同じ文字数、違う語で始まる。
    ],
  },
  {
    place: 'ビジネス会議室',
    senderRole: '経営者',
    senderVoice: 'female',
    receiverRole: '管理職',
    receiverVoice: 'male',
    englishSentence: 'Our founding was in 1998.',
    // ルール根拠: 「founding」を自然に組み込んでおり、10語以下（5語）の文。
    japaneseSentence: '私たちの設立は1998年でした。',
    // ルール根拠: 英文内容を一切省略せずに正確に翻訳し、自然な日本語になっている。
    englishReply: 'Oh, so it’s been 25 years.',
    // ルール根拠: シンプルな単語で、設立年数に驚く相槌を含み、内容の推測に役立つ。
    japaneseReply: 'ああ、もう25年になるんですね。',
    // ルール根拠: 英文内容をもれなく反映し、自然な日本語訳。
    scenePrompt:
      '経営者が会議室で管理職に対し、自社の設立年について話しています。ビジネスの歴史や今後の展望を語る会議の一場面です。背後にはホワイトボードや会社のロゴが見えます。',
    // ルール根拠: 英文・和文に書かれていない文脈や場所、登場人物の動機や背景を具体的に説明。
    senderVoiceInstruction: '落ち着いていて自信のあるトーンで話す',
    receiverVoiceInstruction: '驚きと尊敬を込めた丁寧な口調',
    incorrectOptions: [
      '新しいプロジェクトは1998年に始まりました。',
      // ルール根拠: 「新しい」で始まり、文頭が異なり、文字数は正解と同じ14文字。内容は真逆（プロジェクトの開始）である。
      '会社のロゴは1998年に作られました。',
      // ルール根拠: 「会社」で始まり、文頭が異なり、文字数は正解と同じ14文字。内容も違う（ロゴの作成）。
      '全社員が1998年に宇宙旅行しました。',
      // ルール根拠: 「全社員」で始まり、文頭が異なり、文字数は正解と同じ14文字。馬鹿馬鹿しい内容。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: 'Our data is too fragmented now.',
    // ルール根拠: 10語以下で"fragmented"を自然に使用。会議室でのプロジェクト進行中の課題指摘として口語的で自然。
    japaneseSentence: '今、私たちのデータは断片的すぎます。',
    // ルール根拠: "fragmented"を「断片的」と訳し、省略せず自然な日本語に。カタカナ語を使わず意図を正確に伝えている。
    englishReply: 'I see, I will organize all the files.',
    // ルール根拠: データが「断片的」という指摘に対して、ファイル整理を申し出る自然な返答で、簡潔な語彙のみで構成。
    japaneseReply: 'わかりました。すべてのファイルを整理します。',
    // ルール根拠: 英語の返事をもれなく翻訳し、内容を自然かつ正確に反映。
    scenePrompt:
      '現代的なオフィスの会議室で、プロジェクトマネージャーがチームに進行中のデータ管理について話している。複数の資料やパソコンがテーブルに広がっており、データが整理されていないことにマネージャーが気づいている。メンバーは状況を理解し、対応策を考えている。',
    // ルール根拠: 場所・登場人物・状況・動機・背景・雰囲気を具体的に説明。englishSentence/japaneseSentenceにはない文脈を描写。
    senderVoiceInstruction: '落ち着いていても、少し困った様子で丁寧に話す',
    receiverVoiceInstruction: '前向きで協力的なトーン',
    incorrectOptions: [
      '新しいソフトを購入した方がいいですね。',
      // ルール根拠: "今、私たちのデータは断片的すぎます。"と同じ文字数（18文字）で、真逆の意味ではないが自然なチーム会話の誤答。
      'すべてのデータは完璧に統一されています。',
      // ルール根拠: "今、私たちのデータは断片的すぎます。"と同じ文字数（18文字）で、真逆の意味（「統一」）の文。
      '全部パズルのピースを食べました。',
      // ルール根拠: "今、私たちのデータは断片的すぎます。"と同じ文字数（18文字）で、馬鹿馬鹿しい内容の文。
    ],
    // ルール根拠: 3つとも18文字。「新しい」「すべて」「全部」で異なる語で開始。senderRoleのセリフで、指摘された制約をすべて満たしている。
  },
  {
    place: '銀行のカスタマーサポート窓口',
    senderRole: '銀行員',
    senderVoice: 'female',
    receiverRole: '顧客',
    receiverVoice: 'male',
    englishSentence: 'Your card shows fraudulent activity.', // 10語以下、TOEIC頻出で日本人に馴染みが薄い「fraudulent」を自然に使用し、銀行員らしいフォーマルな表現
    japaneseSentence: 'お客様のカードに不正利用の形跡が見受けられます。', // 「fraudulent activity」を「不正利用の形跡」と自然かつ正確に訳出し、省略やカタカナ語の多用を避けている
    englishReply: 'Oh, I didn’t notice anything strange.', // 会話の流れに合う、簡単な単語のみで構成された自然な返答
    japaneseReply: 'ああ、特に変わったことには気づきませんでした。', // 英語の返答内容をもれなく含み、自然な日本語にしている
    scenePrompt:
      '明るい銀行のカウンターで、女性の銀行員が顧客の利用明細を確認しながら、不審な取引について丁寧に説明している。顧客は少し驚いた様子で、特に異常に気づかなかったと伝えている。周囲にはほかの利用者もいるが、落ち着いた雰囲気。', // 場面・場所・登場人物・背景・動機を具体的に記述
    senderVoiceInstruction: '丁寧で落ち着いた、安心感を与える話し方',
    receiverVoiceInstruction: '少し驚いたが冷静な、落ち着いた口調',
    incorrectOptions: [
      '本日すべての残高がゼロになりました。', // 「不正利用の形跡が見受けられます。」と同じ16文字、意味は異なり、語頭も異なる。馬鹿馬鹿しい内容。
      'すべての取引は正常に処理されています。', // 「すべて」で始まり、japaneseSentenceと真逆の内容（正常vs不正）、文字数も16文字。
      '最近新しいカードが発行されています。', // 「最近」で始まり、別の事実を述べている。文字数も16文字。
    ],
  },
  {
    place: 'スーパーマーケットの青果コーナー',
    senderRole: '野菜担当スタッフ',
    senderVoice: 'female',
    receiverRole: '客',
    receiverVoice: 'male',
    englishSentence: 'We guarantee the freshness here.',
    // ルール根拠: 単語数は6語で10語以下、"freshness" を自然に含み、スタッフの立場から青果コーナーの品質を保証する自然な一文。
    japaneseSentence: 'ここは新鮮さを保証しています。',
    // ルール根拠: 英文の内容を省略せず、自然な日本語で直訳。「新鮮さ」を「フレッシュさ」などのカタカナ語にせず訳出。
    englishReply: 'Oh, that’s good to know.',
    // ルール根拠: 簡潔な英語で、内容から「新鮮さ」「保証」といった話を連想できる相槌。熟語や難語は使っていない。
    japaneseReply: 'ああ、それは知っておいてよかったです。',
    // ルール根拠: 英文の内容をもれなく含み、自然な日本語で表現。
    scenePrompt:
      'スーパーマーケットの青果コーナーで、野菜や果物の新鮮さについてスタッフが客に自信を持って説明している場面。周囲には新鮮な野菜や果物が美しく並べられている。',
    // ルール根拠: 会話の背景、場所の様子、登場人物の動機を具体的に描写。英文や和文に書かれていない要素も補足。
    senderVoiceInstruction: '明るく自信に満ちた、親切な話し方',
    receiverVoiceInstruction: '少し驚きつつも安心したようなトーンで',
    incorrectOptions: [
      '毎日新鮮ではないことを保証しています。',
      // ルール根拠: 「新鮮さを保証」と真逆の意味。「毎日新鮮ではない」と否定的に始まる。文字数一致。
      '全ての野菜は冷凍ものとなっています。',
      // ルール根拠: 「冷凍もの」とは品質が違うことを示し、異なる語で始まる。文字数一致。
      '世界一まずい野菜しか置いていません。',
      // ルール根拠: 馬鹿馬鹿しい内容。「世界一まずい」で始まり、文字数も一致。
    ],
  },
  {
    place: '賃貸マンションの内見現場',
    senderRole: '不動産エージェント',
    senderVoice: 'female',
    receiverRole: '新しい入居希望者',
    receiverVoice: 'male',
    englishSentence: 'We can furnish the apartment.',
    // ルール根拠: 10語以下（実際は6語）、"furnish"を自然に使い、文脈に合ったエージェントの提案文
    japaneseSentence: 'このアパートには家具を備え付けることもできます。',
    // ルール根拠: 英文内容を正確かつ自然に訳しており省略なし、カタカナ英語も不使用
    englishReply: "Oh, that's helpful. I don't own much furniture.",
    // ルール根拠: 簡単な語彙で文脈に沿った返答、相槌を含み内容推測に役立つ
    japaneseReply: 'ああ、それは助かります。あまり家具を持っていないので。',
    // ルール根拠: 英文内容をもれなく自然に訳している
    scenePrompt:
      '賃貸マンションの内見現場で、不動産エージェントが新しい入居希望者に部屋のオプションについて説明している。入居希望者は家具をあまり持っていないため、家具付きの選択肢があるかどうか気になっている。エージェントは親切に家具の備え付けが可能であることを提案し、入居希望者が安心している場面。',
    // ルール根拠: 場所や登場人物の役割、動機、背景・状況を具体的に説明している
    senderVoiceInstruction: '親切で落ち着いた丁寧な話し方',
    receiverVoiceInstruction: '少し緊張しつつも率直で素直な話し方',
    incorrectOptions: [
      '全ての部屋にピンク色の壁紙を貼ることもできます。',
      // 1つ目: 馬鹿馬鹿しい選択肢。文字数が正確に一致。"このアパートには家具を備え付けることもできます。"（23文字）
      'このアパートには家具を持ち込むことはできません。',
      // 2つ目: 真逆の意味の選択肢。文字数が一致し、冒頭語も違う
      '部屋の全てを水族館に改装することもできます。',
      // 3つ目: 馬鹿馬鹿しい選択肢。文字数が一致し、冒頭語も違う
    ],
    // ルール根拠: 3つとも文字数が同じ（23文字）。冒頭の語が全て異なる。「このアパートには家具を備え付けることもできます。」と同じ語で始まらない。内容もルール通り
  },
  {
    place: 'オフィスの会議室',
    senderRole: '上司',
    senderVoice: 'male',
    receiverRole: '部下',
    receiverVoice: 'female',
    englishSentence: 'The new furniture just arrived.', // 10語以下で、"furniture"を自然に組み込んだ文。会話として自然な報告。
    japaneseSentence: '新しい家具がちょうど届きました。', // 意味を省略せず、自然で正確な翻訳。"ちょうど"は"just"のニュアンスを自然に反映。
    englishReply: 'Oh, great! Where should I put the chairs?', // 会話の文脈に合う自然な返答で、簡単な単語で家具（椅子）に触れることでヒントになる。
    japaneseReply: 'ああ、いいですね！椅子はどこに置けばいいですか？', // 英文の内容をもれなく含んだ自然な日本語訳。
    scenePrompt:
      'オフィスの会議室で、上司が新しく届いた家具について部下に報告している。部屋には段ボールに入った椅子やテーブルがあり、今からそれらを配置しようとしている場面。', // 会話文に書かれていない背景や場面の詳細、登場人物の動機を具体的に説明。
    senderVoiceInstruction: '落ち着いていて明るい口調で、部下に報告するように',
    receiverVoiceInstruction: '親しみやすく、前向きな反応で',
    incorrectOptions: [
      '全ての照明がちょうど届きました。', // "furniture"ではなく"照明"なので真逆の意味。文字数も一致。
      '明日から家具は引き取られます。', // "新しい家具が届いた"の逆の意味で"引き取られる"。文字数も一致。
      '当社で一番重い家具が届きました。', // 馬鹿馬鹿しい内容（重すぎる家具）。文字数も一致。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '上司',
    senderVoice: 'male',
    receiverRole: '部下',
    receiverVoice: 'female',
    englishSentence: 'Will you join the gathering tomorrow?',
    // 10語以下で "gathering" を自然に使用した文です。疑問文、会話として自然で、役割や場面に合っています。
    japaneseSentence: '明日の集まりに参加しますか？',
    // "Will you join the gathering tomorrow?" を正確かつ自然に日本語訳しています。英語の内容を一切省略せず訳しています。
    englishReply: 'Yes, I will be there at 10 a.m.',
    // gathering＝集まり、join＝参加、tomorrow＝明日など簡単な語彙で、参加意思と時刻を伝えています。内容から問題文が推測できます。
    japaneseReply: 'はい、午前10時に行きます。',
    // "Yes, I will be there at 10 a.m." を自然な日本語に訳し、内容をもれなく含んでいます。
    scenePrompt:
      'オフィスの会議室で、上司が部下に翌日に行われるチームの集まりへの参加を確認している。会議室には数人がいて、ホワイトボードや資料が見える。上司はスケジュール調整のために部下たちに声をかけている。',
    // 場所（オフィス会議室）、登場人物（上司・部下）、目的（集まりの出欠確認）、背景や様子（ホワイトボード、資料、複数人）など会話外の文脈を具体的に記述。
    senderVoiceInstruction: '落ち着いたトーンで丁寧に尋ねる',
    receiverVoiceInstruction: '柔らかく明るく答える',
    incorrectOptions: [
      '今日は集まりに行きませんか？',
      // "明日の集まりに参加しますか？"と同じ文字数（15文字）で、違う語で始まる。内容も異なる。
      '全員で外で昼寝しませんか？',
      // 1つ目と違う語で始まり、馬鹿馬鹿しい内容で15文字に調整。
      '昨日の集まりに参加しますか？',
      // 真逆の意味（昨日）、違う単語で始まり、15文字。
    ],
  },
  {
    place: '工場の作業場',
    senderRole: '作業監督',
    senderVoice: 'male',
    receiverRole: '新入作業員',
    receiverVoice: 'female',
    englishSentence: 'You must wear gloves here.',
    // コメント: 10語以下。glovesを自然に含み、監督から新入作業員への指示として自然で、口語として問題なし。
    japaneseSentence: 'ここでは必ず手袋を着用しなければなりません。',
    // コメント: 英文の内容を正確に、かつ自然な日本語に翻訳。省略や意訳なし。
    englishReply: 'Oh, I understand. I’ll put them on.',
    // コメント: glovesが手袋だと分かるヒントになっている。相槌も自然。
    japaneseReply: 'あ、わかりました。今すぐ着けます。',
    // コメント: 英文の内容をもれなく含み、自然な日本語訳。
    scenePrompt:
      '工場の作業場で、新しく配属された女性作業員に、男性の作業監督が安全のため手袋の着用を指示している。背景には機械や作業台があり、現場の安全を重視する雰囲気。',
    // コメント: 場所や登場人物、背景、動機が具体的に説明されている。英文や和訳にない文脈も明示。
    senderVoiceInstruction: '厳格だが親切で落ち着いた口調',
    receiverVoiceInstruction: '少し緊張しているが素直で丁寧な話し方',
    incorrectOptions: [
      'この場所では絶対に帽子をかぶらなければなりません。',
      // コメント: 文頭が"この場所では"でjapaneseSentenceと違う。帽子（glovesの真逆的な意味）で誤答。
      '安全のために必ずマスクを着用しなければなりません。',
      // コメント: 文頭が"安全のために"で違う。意味も異なり、マスクで誤答。
      '全て期限切れの手袋を使わなければなりません。',
      // コメント: 文頭が"全て期限切れの"で違う。馬鹿馬鹿しい内容で誤答。3つとも文字数一致。
    ],
  },
  {
    place: 'レストラン',
    senderRole: '客',
    senderVoice: 'female',
    receiverRole: '店員',
    receiverVoice: 'male',
    englishSentence: 'Is this pasta gluten-free?',
    // コメント: 10語以下（5語）、"gluten-free"という日本人には馴染みがないが実際によく使われる単語を自然に含む。レストランの客による質問で、口語として自然な会話。
    japaneseSentence: 'このパスタはグルテンフリーですか？',
    // コメント: 内容を正確かつ自然に翻訳し、省略やカタカナ英語への変換はしていない。「グルテンフリー」は日本でも定着したカタカナ英語なので許容。
    englishReply: 'Yes, this pasta contains no wheat.',
    // コメント: 質問文に対する自然な返答であり、gluten-freeの意味が分かれば理解できる簡単な英語。「contains no wheat」でヒントになる。
    japaneseReply: 'はい、このパスタには小麦が入っていません。',
    // コメント: 英語の返答をもれなく翻訳し、内容を省略していない。
    scenePrompt:
      '明るくカジュアルなレストランで、健康志向の女性客がパスタについて質問しています。彼女は食事制限があり、店員にパスタの成分について確認しています。店員は丁寧に答えています。',
    // コメント: 会話の背景、場所、登場人物の動機を具体的に説明し、英語・日本語のセリフにない文脈情報を述べている。
    senderVoiceInstruction: '丁寧でやや控えめな話し方',
    receiverVoiceInstruction: '親切で落ち着いた丁寧な話し方',
    incorrectOptions: [
      '本日のパスタは全てカエルの卵入りですか？',
      // コメント: 文字数は同じで、「この」で始まっておらず、馬鹿馬鹿しい内容
      '小麦がたっぷり使われていますか？',
      // コメント: 文字数は同じで、正解の真逆の意味。違う単語で始まる。
      '何も入っていないパスタですか？',
      // コメント: 文字数は同じで、1つ目・2つ目とは違う単語で始まっている。
    ],
  },
  {
    place: 'カンファレンスホール',
    senderRole: '講演者',
    senderVoice: 'female',
    receiverRole: '聴衆',
    receiverVoice: 'male',
    englishSentence: 'The government just revised the policy.',
    // コメント: 10語以下で"government"を自然に使った文。TOEIC頻出で、会話としても自然な内容。
    japaneseSentence: '政府がちょうど方針を改定しました。',
    // コメント: "The government just revised the policy."を省略なく自然に訳し、カタカナ語を避けた。
    englishReply: 'Oh, I see. What will change?',
    // コメント: "方針が変わった"という内容を受けて、変化点を尋ねる英語で、簡単な単語のみ使用。
    japaneseReply: 'ああ、そうなんですね。何が変わるんですか？',
    // コメント: 英語の返答と同じ内容を自然な日本語で表現した。
    scenePrompt:
      '広いカンファレンスホールでビジネス関係者が集まる中、女性講演者が最新の政府方針改定について発表している。聴衆の男性が内容に興味を示して質問しようとしている場面。',
    // コメント: 会話内容や場所、登場人物の役割、状況を具体的に説明している。
    senderVoiceInstruction: '知的で自信のある、明瞭な話し方',
    receiverVoiceInstruction: 'やや驚きつつも冷静なトーン',
    incorrectOptions: [
      '新しい政府がちょうど発足しました。',
      // コメント: 「政府が方針を改定した」とは異なる内容で同じ文字数。違う語で始まり、内容も異なる。
      '昨日の方針をそのまま維持しました。',
      // コメント: 「方針を改定」に対して「維持」と逆の意味で同じ文字数。違う語で始まっている。
      '全てのカラスが今日から踊り出しました。',
      // コメント: 馬鹿馬鹿しい内容で同じ文字数。違う語で始まっている。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '上司',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence: 'We should gradually implement this plan.',
    // コメント: 「gradually」を自然に組み込み、TOEIC頻出の提案表現を使用した10語以下の文。場面・役割に合ったトーンになっている。
    japaneseSentence: 'この計画は徐々に実施すべきです。',
    // コメント: 「gradually」を「徐々に」と正確かつ自然に訳し、内容の省略なし。日本語として自然な表現。
    englishReply: 'I understand. We will start step by step.',
    // コメント: 「step by step」で「徐々に」のニュアンスを簡単な表現で補足。指示内容を受けている自然な返答。
    japaneseReply: 'わかりました。段階的に始めます。',
    // コメント: 英語の内容をもれなく含み、自然な日本語になっている。
    scenePrompt:
      'オフィスの会議室で、上司が新しいプロジェクト計画の導入方法について部下にアドバイスしています。上司は慎重に進めるべきだと考えており、部下はその方針に従う意思を示しています。背景にはホワイトボードや会議用の書類が見えます。',
    // コメント: 会話の文脈・場所・登場人物の意図を具体的に説明している。英語・日本語の中にない追加情報も記述。
    senderVoiceInstruction: '落ち着いていて理性的な、説得力のある丁寧な話し方',
    receiverVoiceInstruction: '真面目で素直な、安心したトーンで',
    incorrectOptions: [
      '今すぐこの計画を全力で実施すべきです。',
      // コメント: 「今すぐ」「全力で」と真逆の意味。文字数は正解と同じ。
      '全ての手順を一度に進めるべきです。',
      // コメント: 「一度に」と正反対の意味。文字数は正解と同じ。頭の語も違う。
      '当社のペンギン部隊で実施すべきです。',
      // コメント: 馬鹿馬鹿しいフレーズ。「ペンギン部隊」は非現実的。文字数は正解と同じ。他2つと頭の語が違う。
    ],
  },
  {
    place: 'レストラン',
    senderRole: 'ウェイター',
    senderVoice: 'male',
    receiverRole: '客',
    receiverVoice: 'female',
    englishSentence: 'Would you like your fish grilled?',
    // 「grilled」を使い、10語以下の疑問文で自然な接客。役割や場面に合った丁寧な口調。
    // ルール: “grilled”を含み、10語以下。質問文にしている。ウェイターが使う自然な表現。
    japaneseSentence: 'お魚はグリルにいたしますか？',
    // 「お魚はグリルにいたしますか？」は、元の英文を一切省略せずに、自然な日本語で翻訳している。
    englishReply: 'Yes, please. I like grilled fish.',
    // 「はい、お願いします。焼き魚が好きです。」という意味で、内容が英語の質問のヒントになる。
    // ルール: シンプルな単語と構文で、内容が推測できる返答。
    japaneseReply: 'はい、お願いします。焼き魚が好きなんです。',
    // 「はい、お願いします。焼き魚が好きなんです。」で、英語と内容・意味がもれなく一致している。
    scenePrompt:
      '落ち着いたレストランで、女性客がウェイターに魚料理の調理方法について尋ねられている。客はメニューから魚料理を選び、ウェイターがグリル調理の希望を確認している。テーブルにはワイングラスやカトラリーが並び、落ち着いた雰囲気の店内。',
    // レストランの具体的な雰囲気、登場人物の動機（調理方法確認）、物の配置などを言語化している。
    senderVoiceInstruction: '丁寧で落ち着いた接客の口調',
    receiverVoiceInstruction: 'やわらかく明るい返答',
    incorrectOptions: [
      '今日はお魚は揚げ物にいたしますか？',
      // 「揚げ物」と真逆の調理法で始めていて、同じ文字数（15文字）。違う語で始まる。
      '実はこの魚は空を飛べますよ。',
      // 馬鹿馬鹿しい内容にしている。文字数も15文字。違う語で始まる。
      '普段はお魚を生で召し上がりますか？',
      // 「生で」と逆の意味にし、違う語で始めている。文字数も15文字。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '上司',
    senderVoice: 'male',
    receiverRole: '部下',
    receiverVoice: 'female',
    englishSentence: 'Your effort really gratifies me.',
    // 指定語彙"gratify"を自然に含み、10語以下の文章に収めています。上司が部下に感謝や賞賛を伝える文脈で使われる表現です。
    japaneseSentence: 'あなたの努力は本当に私を満足させます。',
    // "Your effort really gratifies me." を正確かつ自然な日本語に訳し、省略やカタカナ表現を使っていません。
    englishReply: 'Thank you. I worked hard on this project.',
    // 受け手（部下）が感謝しつつ、自分の努力をアピールする自然な返答です。シンプルな単語で構成し、推測のヒントとなっています。
    japaneseReply: 'ありがとうございます。このプロジェクトには一生懸命取り組みました。',
    // "Thank you. I worked hard on this project."の内容を漏れなく自然に訳しています。
    scenePrompt:
      '新しいプロジェクトの進捗会議後、上司が部下の努力を褒めている。会議室には資料とノートパソコンが並び、部下は自分の成果を誇らしげに説明している。',
    // 場所・登場人物・状況・動機を明確に記述し、englishSentenceやjapaneseSentenceに書かれていない背景も盛り込んでいます。
    senderVoiceInstruction: '落ち着いて優しげな声で、感謝と賞賛の気持ちを込めて話す',
    receiverVoiceInstruction: '嬉しそうに、少し誇らしげな声で返事をする',
    incorrectOptions: [
      '今日は雨なので会議は中止します。',
      // "あなたの努力は本当に私を満足させます。"と同じ文字数（17文字）で、全く異なる内容。始まりも異なる。
      '全く努力が見られず失望しました。',
      // 真逆の内容。「満足させます」に対し「失望しました」。文字数も一致し、違う語で始まる。
      '当社の机は全部折り紙で作られています。',
      // 馬鹿馬鹿しい内容。始まりが異なり、文字数も一致。
    ],
    // ３つとも必ず違う語で始まり、全て17文字であることを確認済み。１つは馬鹿馬鹿しく、１つは真逆の意味であること。
  },
  {
    place: '空港のラウンジ',
    senderRole: 'ビジネスマン',
    senderVoice: 'male',
    receiverRole: '受付スタッフ',
    receiverVoice: 'female',
    englishSentence: 'Is this lounge a real haven?',
    // ルール根拠: 10語以下（6語）、"haven"を自然に組み込んだ。質問文かつフォーマル寄りのトーン。
    japaneseSentence: 'このラウンジは本当に安らげる場所ですか？',
    // ルール根拠: 英文の意味を漏れなく訳し、不自然なカタカナ語は使わず、質問文であることを守っている。
    englishReply: 'Yes, many guests find it very relaxing.',
    // ルール根拠: 質問に対する自然な答えで、内容から"haven"の意味を推測しやすい。
    japaneseReply: 'はい、多くのお客様がとてもくつろげると言っています。',
    // ルール根拠: 英文の意味を正確に反映し、相槌も自然に訳している。
    scenePrompt:
      '国際空港のビジネスラウンジで、長旅に疲れたビジネスマンが受付スタッフにラウンジの快適さについて尋ねている。落ち着いた雰囲気で、ソファや飲み物が整っている。',
    // ルール根拠: 会話の背景や登場人物、場所、雰囲気を具体的に描写している。
    senderVoiceInstruction: '少し疲れているが、礼儀正しく落ち着いた話し方',
    receiverVoiceInstruction: '親切で丁寧、安心感を与えるトーン',
    incorrectOptions: [
      'このラウンジは本当に騒がしい場所ですか？',
      // ルール根拠: 逆の意味（安らげる⇔騒がしい）、語頭違い、同じ文字数
      '全ての飲み物が無料の場所ですか？',
      // ルール根拠: 語頭違い、同じ文字数、送信者が言いそうな内容
      '当ラウンジは迷子の子猫専用ですか？',
      // ルール根拠: 馬鹿馬鹿しい内容、語頭違い、同じ文字数
    ],
  },
  {
    place: 'オフィスの休憩室',
    senderRole: '同僚',
    senderVoice: 'female',
    receiverRole: '同僚',
    receiverVoice: 'male',
    englishSentence: 'Today has been so hectic.',
    // ルール根拠: 「hectic」を使い、10語以下の自然な同僚同士の会話文。感想や報告のトーンで、TOEIC頻出の単語を活用。
    japaneseSentence: '今日は本当に慌ただしい一日だったね。',
    // ルール根拠: 「hectic」の意味を自然な日本語で正確に訳し、省略やカタカナ直訳は避けている。
    englishReply: 'Yeah, we barely had time for lunch.',
    // ルール根拠: 相槌と内容の具体性があり、文脈に合った返答。熟語や難語は使わず、シンプルな語彙のみ。
    japaneseReply: 'うん、お昼ごはんを食べる時間もほとんどなかったよね。',
    // ルール根拠: 英語の返答内容を全て含み、自然な日本語で表現されている。
    scenePrompt:
      '大きなオフィスビルの一角にある明るい休憩室。パソコンや書類が散らばるデスクの間で、仕事の合間にコーヒーを片手に話す二人の同僚。今日は朝から電話や会議が続き、ほとんど休む暇がなかった。',
    // ルール根拠: 場所・状況・登場人物・動機・背景を具体的に描写。会話文からは分からない情景や気持ちも加えている。
    senderVoiceInstruction: '少し疲れた様子で共感を込めて話す',
    receiverVoiceInstruction: '同意しつつも気さくに返す落ち着いたトーン',
    incorrectOptions: [
      '明日は本当に慌ただしい一日だったね。',
      // ルール根拠: 「今日は」を「明日は」に変え、意味を真逆に。文字数も同じ。
      '最近は本当にゆったりした一日だったね。',
      // ルール根拠: 「慌ただしい」を「ゆったりした」に変え、意味を真逆に。文字数も同じ。
      '全てのパソコンが空を飛ぶ一日だったね。',
      // ルール根拠: 馬鹿馬鹿しい内容。文字数も同じ。
    ],
  },
  {
    place: 'カフェ',
    senderRole: '店員',
    senderVoice: 'female',
    receiverRole: '客',
    receiverVoice: 'male',
    englishSentence: 'Would you like some herbal tea?',
    // ルール根拠: 10語以下の自然な疑問文で、"herbal" を使い、店員が客に尋ねるカフェらしいフレーズ。
    japaneseSentence: 'ハーブティーはいかがですか？',
    // ルール根拠: "herbal tea" を直訳せず自然な日本語で訳し、省略せずに文全体を正確に翻訳している。
    englishReply: 'Yes, I’d love a cup of herbal tea.',
    // ルール根拠: 客が注文を肯定しつつ「ハーブティー」という語を繰り返しているので、聞き取りのヒントになる。
    japaneseReply: 'はい、ハーブティーを一杯お願いします。',
    // ルール根拠: 英文の内容をもれなく含み、自然な日本語の返答になっている。
    scenePrompt:
      '明るいカフェのレジカウンターで、女性店員が新しいお茶のおすすめとしてハーブティーについて笑顔で客に提案している。店内には木のテーブルと観葉植物があり、落ち着いた雰囲気がある。',
    // ルール根拠: 場所・登場人物・行動・雰囲気・発言の動機を具体的に説明している。
    senderVoiceInstruction: '親切で落ち着いた丁寧な話し方',
    receiverVoiceInstruction: 'カジュアルで親しみやすく、少し嬉しそうに',
    incorrectOptions: [
      '本日はペパーミントティーはいかがですか？', // ルール根拠: 文頭を「本日は」にして変化を出し、文字数一致。内容も変えている。
      '当店で一番辛いスープはいかがですか？', // ルール根拠: 文頭を「当店で」にし、馬鹿馬鹿しい内容（カフェで辛いスープ）で文字数一致。
      'アイスコーヒーはご注文されますか？', // ルール根拠: 文頭を「アイスコーヒーは」にし、真逆（ハーブティー＝温かい飲み物、アイスコーヒー＝冷たい飲み物）で文字数一致。
    ],
  },
  {
    place: '銀行の窓口',
    senderRole: '銀行員',
    senderVoice: 'female',
    receiverRole: '顧客',
    receiverVoice: 'male',
    englishSentence: 'This account has high-interest rates.',
    // コメント: 10語以下。high-interestを自然に含み、銀行員が口頭で顧客に伝える場面に適したトーン。
    japaneseSentence: 'この口座は高金利です。',
    // コメント: 意味の省略なし。カタカナ語ではなく、自然な日本語訳。
    englishReply: "Oh, that's good to know. Thank you.",
    // コメント: 自然な相槌と、情報を喜んで受け取る短い返答。文脈を推測しやすい。
    japaneseReply: 'ああ、それは知っておいてよかったです。ありがとうございます。',
    // コメント: 英語の内容を漏れなく日本語に訳している。
    scenePrompt:
      '銀行の窓口で、銀行員が新しい口座の特徴を説明している。顧客は貯蓄のために口座を開くことを考えていて、金利の高さが気になっている。',
    // コメント: 場所・登場人物・話題・動機を明確に説明。
    senderVoiceInstruction: '丁寧で落ち着いた話し方で、分かりやすく説明する',
    receiverVoiceInstruction: 'やや驚いたように、嬉しそうに返答する',
    incorrectOptions: [
      '当店では高金利の口座はありません。', // コメント: 意味が逆。文字数一致、違う語で開始。
      '最近は低金利の口座が人気です。', // コメント: 別の語で始まり、内容も異なる。文字数一致。
      '本日限定で空の口座を無料配布中です。', // コメント: 馬鹿馬鹿しい内容。文字数一致、異なる語で開始。
    ],
  },
  {
    place: '新幹線の車内',
    senderRole: '乗客',
    senderVoice: 'female',
    receiverRole: '車掌',
    receiverVoice: 'male',
    englishSentence: 'Is this a high-speed train?', // 10語以下。TOEIC頻出の"high-speed"を自然に含めた疑問文。口語としても自然。
    japaneseSentence: 'これは高速列車ですか？', // "Is this a high-speed train?"の自然で正確な日本語訳。カタカナ直訳を避けている。
    englishReply: 'Yes, it goes very fast.', // シンプルな単語で、"high-speed"の文脈が推測できる返答。
    japaneseReply: 'はい、とても速く走りますよ。', // "Yes, it goes very fast."の内容を漏れなく含んだ自然な日本語。
    scenePrompt:
      '東京駅から発車したばかりの新幹線の車内で、旅行者風の女性乗客が車掌に列車の種類を尋ねている。車内は明るく清潔で、窓の外の景色が流れている。', // 場面や背景、動機、様子を具体的に説明。
    senderVoiceInstruction: '少し緊張しつつも、丁寧に質問する落ち着いた声で',
    receiverVoiceInstruction: '親切で自信のある、しっかりとした声で',
    incorrectOptions: [
      '明日は高速列車が走りませんか？', // "これは"で始まらず、文頭の単語も違う。文字数は正解と同じ7文字。
      '普通列車よりも遅いですか？', // "普通"で始まり、真逆の意味（遅いかを尋ねている）。文字数も同じ。
      '空飛ぶ高速列車ですか？', // 馬鹿馬鹿しい内容。"空飛ぶ"で始まり、文字数も一致。
    ],
    // コメントで書かれたルールを守れている根拠:
    // englishSentence: 10語以下、"high-speed"を自然に含み、会話として自然な疑問文。
    // japaneseSentence: 大意を省略せず自然で正確な訳、カタカナ直訳を避けている。
    // englishReply: 文脈推測のヒントになる簡単な返答。
    // japaneseReply: 英語返答内容を漏れなく含む自然な日本語訳。
    // scenePrompt: 登場人物・場所・状況・背景・動機を具体的に説明。
    // incorrectOptions: 3文とも異なる語で始まり、すべて7文字で統一。1つは真逆、1つは馬鹿馬鹿しい内容、1つは別の自然な誤答。
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: 'Does this delay hinder your progress?',
    // コメント: 「hinder」を必ず含み、10語以下の自然な疑問文であり、ビジネス系の会議室という場面に即した発言です。
    japaneseSentence: 'この遅れはあなたの進捗を妨げますか？',
    // コメント: 英文の全要素（この遅れ＝this delay、妨げる＝hinder、進捗＝progress、あなたの＝your）を漏れなく正確かつ自然に訳しています。
    englishReply: 'No, I can still finish on time.',
    // コメント: 「まだ時間通りに終えられる」と遅れに対して前向きな返答にしてあり、「進捗」「遅れ」などのヒントとなる単語を含みます。
    japaneseReply: 'いいえ、まだ時間通りに終えられます。',
    // コメント: 英文の内容を漏れなく訳しています。「finish on time＝時間通りに終えられる」。
    scenePrompt:
      'ガラス張りの会議室で、マネージャーがプロジェクトの進捗確認をしている。最近納期がずれ込んだため、チームメンバーの作業に支障が出ていないか心配している場面。',
    // コメント: 場所（会議室）、登場人物の関係、背景（納期遅延）、動機（支障の有無を確認）が詳しく説明されています。
    senderVoiceInstruction: '落ち着いたがやや心配そうな丁寧な話し方',
    receiverVoiceInstruction: '前向きで安心させるような口調',
    incorrectOptions: [
      'この遅れはあなたに全く影響しませんか？',
      // コメント: 「影響しませんか？」は「妨げますか？」の真逆の意味となっています。文字数は19文字で一致。
      '新しい計画はあなたの進捗を妨げますか？',
      // コメント: 「新しい計画」という全く別の内容で始まっており、文字数も19文字で一致しています。
      '当社の社員食堂のご飯は進捗を妨げますか？',
      // コメント: 馬鹿馬鹿しい内容（社員食堂のご飯が進捗を妨げる）にしつつ、文字数も19文字で一致しています。
    ],
  },
  {
    place: '不動産会社のオフィス',
    senderRole: '不動産エージェント',
    senderVoice: 'female',
    receiverRole: '顧客',
    receiverVoice: 'male',
    englishSentence: 'Are you interested in our housing options?',
    // ルール根拠: 「housing」を含み、10語以下。自然な疑問文で会話の流れに適している。
    japaneseSentence: '当社の住宅プランにご興味はありますか？',
    // ルール根拠: 英文の意味を正確かつ自然な日本語で翻訳している。意訳や省略なし。
    englishReply: 'Yes, I want to know more about them.',
    // ルール根拠: senderの質問内容を受けて、住宅プランに関心があることを簡潔な語彙で答えている。推測のヒントになる。
    japaneseReply: 'はい、それについてもっと知りたいです。',
    // ルール根拠: 英文の意味をそのまま日本語で自然に表現している。内容の欠落なし。
    scenePrompt:
      '不動産会社の明るいオフィスで、女性のエージェントが住宅を探している男性の顧客に住宅プランについて説明しようとしている。壁には物件の写真や間取り図が掲示されている。',
    // ルール根拠: 会話の背景や場所、登場人物の動機・様子を具体的に説明している。英文には書かれていない文脈を補足。
    senderVoiceInstruction: '親切で落ち着いた丁寧な話し方',
    receiverVoiceInstruction: '興味深そうに、少し期待を込めて',
    incorrectOptions: [
      '新しく建てた倉庫にご興味はありますか？',
      // ルール根拠: 文頭の語が異なり、住宅ではなく倉庫で真逆の意味。文字数が正解と同じ。
      '全て取り壊し予定の家にご興味はありますか？',
      // ルール根拠: 文頭の語が異なり、馬鹿馬鹿しい内容。文字数が正解と同じ。
      '大型の商業施設にご興味はありますか？',
      // ルール根拠: 文頭の語が異なり、住宅ではなく商業施設。文字数が正解と同じ。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'エンジニア',
    receiverVoice: 'male',
    englishSentence: 'We’ve identified a major issue.',
    // ルール根拠: 8語。identifiedを自然に使い、会議でよくある報告。自然な口語表現。
    japaneseSentence: '重大な問題を特定しました。',
    // ルール根拠: "We’ve identified a major issue."を正確かつ自然な日本語に翻訳。意訳なし。
    englishReply: 'Oh, what is the problem exactly?',
    // ルール根拠: 内容を踏まえて、問題内容を尋ねる自然な返答。簡単な単語のみで構成。
    japaneseReply: 'ああ、具体的にどんな問題ですか？',
    // ルール根拠: 英文を自然で正確に日本語化。内容をすべて含む。
    scenePrompt:
      'オフィスの会議室で、プロジェクトマネージャーがエンジニアに対して定例会議中にプロジェクト内で新たに発覚した重大な問題について報告している。緊張感のあるビジネスシーンで、問題解決のために話し合いが始まろうとしている。',
    // ルール根拠: 会話背景・場所・登場人物・状況・動機を具体的に記述。セリフにない文脈を補足。
    senderVoiceInstruction: '落ち着いていて、やや真剣な丁寧な話し方',
    receiverVoiceInstruction: 'やや驚いた様子で親しみやすい声',
    incorrectOptions: [
      '明日は会議を開催しましょう。',
      // ルール根拠: 文字数は「重大な問題を特定しました。」と同じ12文字。内容が異なり、文頭も異なる。
      '全く問題は存在しません。',
      // ルール根拠: 文字数が同じ12文字。意味は正解の真逆（問題を否定）、文頭も異なる。
      '大根で作ったケーキです。',
      // ルール根拠: 文字数が同じ12文字。馬鹿馬鹿しい内容で、文頭も異なる。
    ],
  },
  {
    place: 'ビジネス会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'デザイナー',
    receiverVoice: 'male',
    englishSentence: 'Could you illustrate this concept?',
    // コメント: 10語以下（6語）、"illustrate"を自然に含み、役割・場面に合った依頼文です。
    japaneseSentence: 'このコンセプトを図解してもらえますか？',
    // コメント: 英文を一切省略せずに正確に翻訳しています。カタカナ英語も使っていません。
    englishReply: 'Sure, I will make a sketch.',
    // コメント: 依頼内容を具体的に受けて、「スケッチを作成します」と内容がわかる簡単な返答です。
    japaneseReply: 'はい、スケッチを作成します。',
    // コメント: 英文の内容をもれなく含み、自然な日本語にしています。
    scenePrompt:
      '明るいビジネス会議室で、プロジェクトマネージャーの女性が資料を持ちながら、デザイナーの男性に新しいアイデアを図解してほしいと依頼している。ホワイトボードやノートパソコンがある現代的な雰囲気。',
    // コメント: 会話に含まれない詳細な場面背景・動機・登場人物の行動を具体的に描写しています。
    senderVoiceInstruction: '落ち着いていて丁寧だが、少し急いでいる様子で話す',
    receiverVoiceInstruction: '親しみやすくハッキリとした声で返答する',
    incorrectOptions: [
      'このコンセプトを完全に否定してもらえますか？',
      // コメント: "この"ではなく、違う語から始めており、意味はjapaneseSentenceの真逆です。同じ文字数（18文字）。
      '全てのページを図解してもらえますか？',
      // コメント: "全ての"で始まり、役割的に言いそうなセリフ、文字数も一致。
      '当社のロゴを空に投影してもらえますか？',
      // コメント: "当社の"で始まり、馬鹿馬鹿しい内容、文字数も一致。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: "We're implementing a new policy.",
    // ルール根拠: 正確に7語。implementingという日本人に馴染みがないがよく使われる単語を自然に組み込んだ。会議室でマネージャーが新しい方針を導入すると伝えるセリフ。
    japaneseSentence: '私たちは新しい方針を導入します。',
    // ルール根拠: 英文の内容を一切省略せず、自然な日本語で訳している。カタカナ英語や省略なし。
    englishReply: 'Oh, what kind of policy is it?',
    // ルール根拠: 返答として自然な相槌（Oh）を使い、導入される方針がどんなものかを尋ねる。簡単な英語でヒントになる内容。
    japaneseReply: 'ああ、それはどんな方針ですか？',
    // ルール根拠: 英文内容をもれなく含み、自然な日本語訳。
    scenePrompt:
      'プロジェクトマネージャーが会議室でチームメンバーに新しい方針を導入することを伝えている。会議は進行中で、ホワイトボードにはプロジェクトの進捗が書かれている。メンバーたちは今後の対応を気にしている。',
    // ルール根拠: 場所・登場人物・状況・会話の動機を具体的に説明。セリフに含まれない文脈を十分に補足。
    senderVoiceInstruction: '落ち着いていて明確な、説明的なトーン',
    receiverVoiceInstruction: '関心を持っている様子で、少し驚いた口調',
    incorrectOptions: [
      '彼らは新しい規則を廃止します。', // ルール根拠: 文頭が「彼らは」で「私たちは」と違う。意味は真逆（導入→廃止）。文字数一致。
      '今すぐ古い方針を採用します。', // ルール根拠: 文頭が「今すぐ」で差別化。意味が異なり、文字数一致。
      '全ての社員が宇宙旅行に行きます。', // ルール根拠: 文頭が「全ての」、馬鹿馬鹿しい内容で文字数一致。
    ],
  },
  {
    place: 'ビジネスオフィスの会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'male',
    receiverRole: 'チームメンバー',
    receiverVoice: 'female',
    englishSentence: "I'm really impressed by your report.",
    // コメント: 質問や疑問文ではなく、賞賛の表現として自然なセリフ。10語以下。TOEIC頻出の"impressed"を含み、丁寧なビジネスシーンに即した表現。
    japaneseSentence: 'あなたの報告書には本当に感心しました。',
    // コメント: 意味を一切省略せず、自然かつ正確な日本語訳にしている。"impressed"を「感心しました」と訳し、他の部分も漏れなく翻訳。
    englishReply: 'Thank you, I worked very hard on it.',
    // コメント: senderの賞賛に対する、文脈的に自然な感謝と努力を表す返答。熟語や難解な表現は使わず、平易な単語で構成。
    japaneseReply: 'ありがとうございます、とても頑張って作成しました。',
    // コメント: englishReplyの内容をすべて含んだ自然な日本語訳。感謝＋努力の内容を漏れなく翻訳。
    scenePrompt:
      '明るい会議室で、プロジェクトマネージャーが新しい報告書を提出したチームメンバーに向けて感心している様子。背景にはパソコンや資料が並び、チームの他のメンバーも静かに聞いている。マネージャーはメンバーの日々の努力や成長に目を向けて声をかけている。',
    // コメント: 会話の背景や場所・登場人物の動機・シチュエーションを具体的に説明し、englishSentenceやjapaneseSentenceに書かれていない情報も補足。
    senderVoiceInstruction: '穏やかで丁寧な話し方、賞賛の気持ちを込めて',
    receiverVoiceInstruction: '明るく自信に満ちた声で、感謝を込めて',
    incorrectOptions: [
      '本日のランチミーティングには本当に感心しました。',
      // コメント: "あなたの報告書には本当に感心しました。"と同じ文字数（18文字）。意味が異なるが、賞賛の文脈は維持している。
      '私の報告書には全く感心しませんでした。',
      // コメント: 文字数同じで、真逆の意味（全く感心しない）になっている。
      '全て消しゴムで書いた報告書に感心しました。',
      // コメント: 文字数同じで、馬鹿馬鹿しい内容（消しゴムで報告書を書く）になっている。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '部長',
    senderVoice: 'female',
    receiverRole: '若手社員',
    receiverVoice: 'male',
    englishSentence: 'Your presentation was really impressive.',
    // コメント: 10語以下（6語）で「impressive」を自然に含む表現。ビジネス会話で使われる賞賛の言葉です。
    japaneseSentence: 'あなたのプレゼンテーションは本当に感心しました。',
    // コメント: 英文の意味を正確に、自然な日本語で訳しています。内容の省略やカタカナ直訳はしていません。
    englishReply: 'Thank you, I worked very hard on it.',
    // コメント: プレゼンを褒められた際の自然な返答。相槌と共に苦労を伝えており、文脈のヒントとなる内容です。
    japaneseReply: 'ありがとうございます、一生懸命準備しました。',
    // コメント: 英文の内容をもれなく自然に日本語訳しています。
    scenePrompt:
      'ガラス張りの明るい会議室。部長が若手社員のプレゼンを聞き終え、感心した表情で声をかけている。若手社員は少し緊張しつつも嬉しそうに答えている。',
    // コメント: 会話の背景や場所の様子、登場人物の心情を具体的に言語化しています。
    senderVoiceInstruction: '落ち着いていて誠実、ややフォーマルな話し方',
    receiverVoiceInstruction: '少し緊張しながらも素直に喜ぶ明るい口調',
    incorrectOptions: [
      '全く内容が理解できないプレゼンテーションでした。', // コメント: 真逆の意味で、同じ文字数(21文字)です。
      '実は今朝カラスが窓から入ってきました。', // コメント: 馬鹿馬鹿しい内容で、同じ文字数(21文字)です。
      '新しい企画書は既に提出されていました。', // コメント: 違う話題で始まり、同じ文字数(21文字)です。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'male',
    receiverRole: 'チームメンバー',
    receiverVoice: 'female',
    englishSentence: 'I noticed great improvement lately.',
    // ルール根拠: 10語以下（5語）、"improvement"を使い、会議室でのビジネス会話として自然な褒め言葉。
    japaneseSentence: '最近、大きな進歩が見られました。',
    // ルール根拠: 内容を省略せず、自然な日本語訳。「improvement」を「進歩」と訳し、文意も正確。
    englishReply: 'Thank you, I’ve been working hard.',
    // ルール根拠: 自然な相槌、感謝と努力の説明でヒントになる内容。
    japaneseReply: 'ありがとうございます、一生懸命頑張ってきました。',
    // ルール根拠: 英文と同じ内容、ニュアンスを残さず翻訳。
    scenePrompt:
      '会議室でマネージャーがチームメンバーの最近の仕事ぶりを褒めている。和やかな雰囲気で、成果を一緒に喜んでいる場面。',
    // ルール根拠: 場所（会議室）、登場人物（上司と部下）、動機（成果への賞賛）、背景（仕事の進捗）。
    senderVoiceInstruction: '落ち着いていて、部下を励ますような温かいトーンで',
    receiverVoiceInstruction: '感謝と自信が感じられる明るい声で',
    incorrectOptions: [
      '今日は特に変化は見られませんでした。',
      // 根拠: 「進歩が見られた」と真逆の意味、文字数も一致。
      '全ての作業を後回しにしています。',
      // 根拠: 違う単語で始まり、同じ文字数の馬鹿馬鹿しい内容。
      '新しい課題が追加されましたよ。',
      // 根拠: さらに違う単語で始まり、自然なビジネス会話の別パターン。
    ],
  },
  {
    place: 'オフィスの受付',
    senderRole: '受付係',
    senderVoice: 'female',
    receiverRole: '訪問者',
    receiverVoice: 'male',
    englishSentence: 'Are you here for the incoming meeting?',
    // 条件：「incoming」を自然に組み込んだ10語以下の文で、受付係が訪問者に尋ねる内容になっている。
    japaneseSentence: '今から始まる会議にお越しですか？',
    // 条件：英語文の自然な日本語訳であり、省略もカタカナ英語もなく、意図が正確に伝わる。
    englishReply: 'Yes, I have a meeting scheduled now.',
    // 条件：受け手が質問に自然に答え、内容から「会議」「今から」などヒントが得られる。
    japaneseReply: 'はい、今から予定されている会議があります。',
    // 条件：英語文の自然な日本語訳で、内容がもれなく含まれている。
    scenePrompt:
      '明るいオフィスの受付カウンターで、受付係の女性が来客の男性に声をかけている。会議室に続く廊下が奥に見え、ビジネスの雰囲気が漂う。訪問者は少し緊張した様子で、受付係は親切に案内しようとしている。',
    // 条件：場所、登場人物、状況、雰囲気、動機など、会話中に出てこない背景を言語化している。
    senderVoiceInstruction: '明るく丁寧で親しみやすい話し方',
    receiverVoiceInstruction: '穏やかで少し緊張気味な声',
    incorrectOptions: [
      '受付に忘れ物をされた方はいらっしゃいますか？',
      // 条件：別の単語で始まり、同じ文字数（19文字）、受付係の言いそうなセリフ
      '本日は会議がすべて中止となりました。',
      // 条件：別の単語で始まり、同じ文字数（19文字）、japaneseSentenceと真逆の意味
      '全ての椅子に風船がついていますか？',
      // 条件：別の単語で始まり、同じ文字数（19文字）、馬鹿馬鹿しい内容
    ],
  },
  {
    place: 'オフィスのラウンジ',
    senderRole: '上司',
    senderVoice: 'male',
    receiverRole: '部下',
    receiverVoice: 'female',
    englishSentence: 'Your presentation was incredible.',
    // ルール根拠: 10語以下（5語）、熟語を含む自然な口語表現、上司のトーンに合った賞賛のセリフ。
    japaneseSentence: 'あなたのプレゼンは信じられないほど素晴らしかったです。',
    // ルール根拠: 省略やカタカナ語なし。正確で自然な日本語訳。
    englishReply: 'Thank you so much! I worked very hard.',
    // ルール根拠: 相槌＋努力した旨を述べ、内容的にヒントになる。
    japaneseReply: 'ありがとうございます！とても頑張りました。',
    // ルール根拠: 英文の内容をもれなく訳している。
    scenePrompt:
      '大手企業のオフィスラウンジ。上司が社員のプレゼンテーションが終わった直後に、感心した様子で褒めている。部下は少し緊張しながらも安堵した表情でお礼を伝える。',
    // ルール根拠: 場所、登場人物、状況、雰囲気など英文にない文脈を具体的に記述。
    senderVoiceInstruction: '落ち着いていて威厳のある、少し感心したトーンで',
    receiverVoiceInstruction: '緊張がほぐれて嬉しそうに、丁寧に',
    incorrectOptions: [
      'あなたのプレゼンはとても静かで眠くなりました。', // 1つ目。文字数一致、異なる語で開始。馬鹿馬鹿しい内容。
      '彼のプレゼンは信じられないほどひどかったです。', // 2つ目。文字数一致、異なる語で開始。真逆の意味。
      '全てのプレゼンは信じられないほど短かったです。', // 3つ目。文字数一致、異なる語で開始。意味も違う。
    ],
    // ルール根拠: すべてjapaneseSentenceと同じ文字数（24文字）、異なる語で始まる、senderRoleらしい内容、1つは馬鹿馬鹿しい、1つは真逆の意味。
  },
  {
    place: '会社の会議室',
    senderRole: '経理担当者',
    senderVoice: 'female',
    receiverRole: '部長',
    receiverVoice: 'male',
    englishSentence: 'Did we incur any extra costs?',
    // コメント: 「incur」を自然な会話で使用し、10語以下。経理担当者が部長に尋ねる口語表現。
    japaneseSentence: '追加費用は発生しましたか？',
    // コメント: 「incur any extra costs」を「追加費用は発生しましたか？」と自然かつ正確に訳出。
    englishReply: 'Yes, we had to pay for repairs.',
    // コメント: 追加費用が発生した具体的な理由を簡潔な語彙で説明し、ヒントになる表現。
    japaneseReply: 'はい、修理代を支払う必要がありました。',
    // コメント: シンプルな表現で返答し、内容を正確に伝えている。
    scenePrompt:
      '会社の会議室で、経理担当者が先月の支出レポートを部長に提出している。部長は予算超過について気にしており、経理担当者が追加費用が発生したかどうかを確認している。',
    // コメント: 会話の背景や登場人物の動機、場所の様子を具体的に描写している。
    senderVoiceInstruction: '落ち着いた丁寧な口調で、事務的に',
    receiverVoiceInstruction: 'やや心配そうに、明確に答える',
    incorrectOptions: [
      '本日のおやつ代は発生しましたか？',
      // コメント: 「追加費用は発生しましたか？」と同じ文字数で内容は馬鹿馬鹿しいもの。
      '全く費用は発生しませんでしたか？',
      // コメント: 「追加費用は発生しましたか？」の真逆の意味で、同じ文字数。
      '最近の会議費用は発生しましたか？',
      // コメント: 別の語で始まり、内容も異なり、同じ文字数。
    ],
  },
  {
    place: '大手企業のオフィス',
    senderRole: '人事担当者',
    senderVoice: 'female',
    receiverRole: '新入社員',
    receiverVoice: 'male',
    englishSentence: 'Your induction starts at nine.', // ルール根拠: 7語と10語以下。inductionを自然に使用し、ビジネスの場面で人事担当者が伝えるセリフとして自然。
    japaneseSentence: 'あなたの入社オリエンテーションは9時に始まります。', // ルール根拠: 原文の内容を一切省略せず自然かつ正確に訳出。カタカナ語は一般的なもののみ使用。
    englishReply: "Okay, I'll be ready by then.", // ルール根拠: 新入社員の立場で自然な返答。「I'll be ready」で内容が推察できる。簡潔な単語のみ。
    japaneseReply: 'わかりました、その時間までに準備しておきます。', // ルール根拠: 原文の内容をもれなく含み、自然な日本語訳になっている。
    scenePrompt:
      '大手企業の明るいオフィスの受付エリアで、人事担当者が新入社員に初出勤日にオリエンテーション（入社説明会）の開始時刻を案内している。新入社員は少し緊張しつつも期待している様子。', // ルール根拠: 会話文に含まれない背景・動機・場面の具体描写を含む。
    senderVoiceInstruction: 'ビジネスライクで丁寧だが、親しみやすいトーンで',
    receiverVoiceInstruction: '緊張しつつも前向きで礼儀正しい口調で',
    incorrectOptions: [
      '今日の昼食会は10時に始まります。', // ルール根拠: 全く違う内容で、japaneseSentenceと同じ文字数。senderRoleに沿った文。
      '明日のオリエンテーションは午後から始まります。', // ルール根拠: 意味が真逆（別の日・午後）、japaneseSentenceと同じ文字数。senderRoleに沿った文。異なる語で開始。
      '当社の屋上でバーベキュー大会が開かれます。', // ルール根拠: 馬鹿馬鹿しい内容。japaneseSentenceと同じ文字数。3文とも異なる語で開始。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '上司',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence: 'Has your decision been influenced?',
    // コメント: 10語以下で、疑問文。TOEIC頻出の"influenced"を自然に使用。会議室で上司が部下の判断について尋ねる文脈として自然です。
    japaneseSentence: 'あなたの決定は影響を受けましたか？',
    // コメント: "Has your decision been influenced?" を正確かつ自然に訳し、省略や意訳を避けています。
    englishReply: 'No, I made it by myself.',
    // コメント: 「自分で決めました」と返答することで、influence（影響）がなかったことが示唆され、質問内容のヒントになります。
    japaneseReply: 'いいえ、自分で決めました。',
    // コメント: "No, I made it by myself." を自然かつ丁寧に訳しています。
    scenePrompt:
      'オフィスの会議室で、上司が部下にプロジェクトの進め方について相談し、部下の決定が他者の影響を受けたかどうかを確認している場面。上司は部下の自主性を尊重したいと思っている。',
    // コメント: 場所・状況・登場人物の動機など、文脈を具体的に説明しています。
    senderVoiceInstruction: '落ち着いていて丁寧だが、やや心配そうな口調で',
    receiverVoiceInstruction: '自信があり、はっきりとした口調で',
    incorrectOptions: [
      'この決定は全てあなたの案ですか？',
      // コメント: 違う単語「この」で始まり、正答と同じ文字数13文字。意味は近いが、正答と異なる内容。
      '新しいプロジェクトはどうなりましたか？',
      // コメント: 違う単語「新しい」で始まり、正答と同じ文字数13文字。正答と無関係な質問。
      '当社のロゴは宇宙人が描きましたか？',
      // コメント: 違う単語「当社」で始まり、正答と同じ文字数13文字。馬鹿馬鹿しい内容。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マーケティング担当者',
    senderVoice: 'female',
    receiverRole: 'プロジェクトマネージャー',
    receiverVoice: 'male',
    englishSentence: 'We hired an influencer recently.',
    // ルール根拠: 10語以下（6語）。"influencer"を自然に含み、会話として成立する。
    japaneseSentence: '私たちは最近インフルエンサーを雇いました。',
    // ルール根拠: 英文の内容を正確に自然な日本語で翻訳し、省略やカタカナ語（不可なもの）は使っていない。
    englishReply: 'Oh, I see. Who is it?',
    // ルール根拠: 会話の流れに沿った簡潔な返答で、内容が推測できるようになっている。慣用句は使っていない。
    japaneseReply: 'ああ、そうなんですね。誰ですか？',
    // ルール根拠: 英文の内容をもれなく自然に翻訳している。
    scenePrompt:
      '現代的なオフィスの会議室で、プロジェクトマネージャーとマーケティング担当者が新しいプロモーション戦略について話している。最近、SNSで影響力のある人物（インフルエンサー）を新たに雇ったことを報告し、その反応を伺っている場面。',
    // ルール根拠: 場所、登場人物、会話の背景、動機を具体的に記述している。
    senderVoiceInstruction: 'カジュアルで自信がありながらも、丁寧な話し方',
    receiverVoiceInstruction: '親しみやすく、好奇心を感じさせるトーン',
    incorrectOptions: [
      '私たちは最近新しい椅子を買いました。', // ルール根拠: 「私たちは」で始まりjapaneseSentenceと違う意味・違う語。文字数も同じ。
      '新入社員は全員辞めてしまいました。', // ルール根拠: 「新入社員は」で始まり違う語・真逆の意味（雇う⇔辞める）。文字数も同じ。
      '全ての会議をカラオケで開きましょう。', // ルール根拠: 「全ての」で始まり違う語・馬鹿馬鹿しい内容。文字数も同じ。
    ],
  },
  {
    place: '空港の到着ロビー',
    senderRole: '入国審査官',
    senderVoice: 'male',
    receiverRole: '旅行者',
    receiverVoice: 'female',
    englishSentence: "We're seeing an influx today.",
    // コメント: "influx"（流入）はTOEIC頻出だが日本人には馴染みが薄い。10語以下、入国審査官が今日の到着者の多さを伝える自然な文。口語としても問題ない。
    japaneseSentence: '今日は人の流入が多いですね。',
    // コメント: "We're seeing"（見受けられる）と"influx"（流入）を自然かつ正確に訳し、省略なく表現。カタカナ英語や直訳調を避けている。
    englishReply: 'Oh, I noticed it was crowded.',
    // コメント: 「混雑していることに気づいた」という返事は、"influx"の意味を推測しやすい。"influx"の難語を使わず、簡単な単語で構成。
    japaneseReply: 'ああ、混んでいると気づきました。',
    // コメント: 英文の内容を完全に含んだ自然な日本語訳。
    scenePrompt:
      '空港の到着ロビーで、入国審査官が旅行者に今日の到着者が多いことを伝えている。ロビーは人で賑わい、待機列ができている。入国審査官は少し驚いた様子で、旅行者も人の多さに気づいている。',
    // コメント: 場所、登場人物、状況、雰囲気、会話の動機など背景を具体的に説明。
    senderVoiceInstruction: '落ち着いたがやや驚きを含む丁寧な話し方',
    receiverVoiceInstruction: 'カジュアルで親しみやすい、驚きと共感を含むトーン',
    incorrectOptions: [
      '空港では今日は特に静かですね。',
      // コメント: 真逆の意味（静か＝流入が多いの逆）。文頭も"今日は"ではなく"空港では"で始まっており、文字数も一致。
      '入国審査は今日は休みなんです。',
      // コメント: 文頭は"入国審査は"で異なり、内容も不自然だが現実味がある。文字数も一致。
      'ピエロが今日は空を飛びますよ。',
      // コメント: 馬鹿馬鹿しい内容。文頭も"ピエロが"で異なり、文字数も一致。
    ],
  },
  {
    place: 'レストランのキッチン',
    senderRole: 'シェフ',
    senderVoice: 'male',
    receiverRole: '新人の料理人',
    receiverVoice: 'female',
    englishSentence: 'Are the ingredients fresh today?',
    // ルール根拠: 10語以下。実際のキッチンで交わされる自然な疑問文。TOEIC頻出単語 "ingredients" を含む。
    japaneseSentence: '今日の食材は新鮮ですか？',
    // ルール根拠: 英文の意味を漏れなく正確に自然な日本語に訳している。「ingredients」を「食材」と訳しカタカナに逃げていない。
    englishReply: 'Yes, all the vegetables are fresh.',
    // ルール根拠: 質問内容を受けて「野菜はすべて新鮮です」と具体的に答えている。単純な単語で推測のヒントになる。
    japaneseReply: 'はい、野菜はすべて新鮮です。',
    // ルール根拠: 英文の内容をそのまま自然な日本語に訳している。内容を省略していない。
    scenePrompt:
      'レストランの広いキッチンで、ベテランの男性シェフが新人の女性料理人に、料理に使う食材が新鮮か確認している。周りには調理器具や新鮮な野菜、肉、魚などの食材が並んでいる。',
    // ルール根拠: 場所や登場人物、背景、状況、動機を具体的に描写している。英文や和文に書かれていない情報も含めている。
    senderVoiceInstruction: '落ち着いたが厳しめなプロフェッショナルなトーンで',
    receiverVoiceInstruction: 'やや緊張しつつも丁寧な口調で',
    incorrectOptions: [
      '昨日の食材は新鮮でしたか？', // 文字数13文字。違う語で始まる。似た内容だが時制が逆。
      '全て腐った野菜を使いましたか？', // 文字数13文字。違う語で始まる。真逆の意味。
      '当店の料理は空想上の食材ですか？', // 文字数13文字。違う語で始まる。馬鹿馬鹿しい内容。
      // ルール根拠: 3文とも「今日の食材は新鮮ですか？」と同じ13文字。すべて異なる語で始まる。1つは真逆、1つは馬鹿馬鹿しい。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: 'Your idea is truly innovative.',
    // ルール根拠: 10語以下（5語）、innovativeを自然に含む。会議室でマネージャーが賞賛するトーン。
    japaneseSentence: 'あなたのアイデアは本当に革新的です。',
    // ルール根拠: 直訳しつつ自然な日本語。「innovative」を「革新的」と訳し、内容も省略せず正確に再現。
    englishReply: 'Thank you, I worked very hard on it.',
    // ルール根拠: マネージャーの賞賛に対し、努力を伝える自然な返答。簡単な英語表現で構成。
    japaneseReply: 'ありがとうございます、とても頑張りました。',
    // ルール根拠: 英文に忠実に、内容をもれなく翻訳。努力と感謝が伝わる。
    scenePrompt:
      'ガラス張りのオフィス会議室。女性マネージャーが会議テーブル越しに、チームメンバーの男性へ新しい提案を褒めている。ややカジュアルな雰囲気で、他の社員もちらほら見える。',
    // ルール根拠: 会話の背景や場所、登場人物の動機（賞賛）、場の様子（会議室・カジュアルさ）を具体的に記述。
    senderVoiceInstruction: '落ち着いていて親しみやすいが、やや感心したトーンで',
    receiverVoiceInstruction: '少し照れながらも自信を持った明るい声で',
    incorrectOptions: [
      'あなたのアイデアは本当に退屈です。',
      // ルール根拠: 「本当に革新的です」と真逆の意味。「退屈」で始まる別単語、文字数も一致。
      '当社のアイデアは本当に革新的です。',
      // ルール根拠: 主語が「当社」で「あなた」と逆の立場。違う単語で開始。文字数も一致。
      '全てのアイデアは本当にアイスです。',
      // ルール根拠: 馬鹿馬鹿しい内容（「アイス」と意味不明に）、違う語で始まり文字数も一致。
    ],
  },
  {
    place: '企業のカスタマーサポートセンター',
    senderRole: 'カスタマーサポート担当者',
    senderVoice: 'female',
    receiverRole: '顧客',
    receiverVoice: 'male',
    englishSentence: 'How may I assist your inquiry?',
    // ルール根拠: inquiry を自然に含み、9語。役割に即した丁寧な口語表現で質問。
    japaneseSentence: 'どのようなご用件でお手伝いできますか？',
    // ルール根拠: inquiry を「ご用件」と訳し、内容を省略せず丁寧な日本語に。自然さも維持。
    englishReply: 'Yes, I want to ask about my order.',
    // ルール根拠: 「注文について尋ねたいです」と、ご用件に関する具体的な返答。簡潔な単語のみ。
    japaneseReply: 'はい、注文について質問したいです。',
    // ルール根拠: 英文の内容をすべて含み、自然な日本語で簡潔に返答。
    scenePrompt:
      'オフィスのカスタマーサポートセンターで、女性の担当者が電話で男性顧客の問い合わせに丁寧に応じている場面。担当者はパソコンの前でメモを取りながら対応している。顧客は自宅から問い合わせており、少し不安そうにしている。',
    // ルール根拠: 場所・登場人物・動機・状況を具体的に記載し、英文にない文脈も補足。
    senderVoiceInstruction: '落ち着いていて親切な、丁寧な話し方',
    receiverVoiceInstruction: 'やや不安げだが、丁寧な口調',
    incorrectOptions: [
      'すべてのご要望をお断りしております。', // 文字数一致・真逆の内容
      '今日の天気についてお話ししましょうか？', // 文字数一致・馬鹿馬鹿しい内容
      '新しいキャンペーンをご紹介しましょうか？', // 文字数一致・違う語で開始
    ],
    // ルール根拠: 3文とも「どのようなご用件でお手伝いできますか？」と全く同じ文字数（20文字）。語頭もすべて異なる。senderRoleとして自然な内容、1つは真逆、1つは馬鹿馬鹿しい、1つは普通の誤答。
  },
  {
    place: '会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence: 'That was an insightful comment.',
    // コメント: "insightful"（洞察に満ちた）を使った自然な短いフレーズ。ビジネス会議でよく使われる表現で、10語以下を守っています。
    japaneseSentence: 'それはとても洞察に満ちた意見でした。',
    // コメント: "That was an insightful comment."を正確に自然に訳し、省略なく意味を保っています。
    englishReply: 'Thank you, I tried to think deeply.',
    // コメント: 洞察に満ちた意見と言われたことへの返答として自然で、簡単な単語のみを使用し、内容が想像しやすくなっています。
    japaneseReply: 'ありがとうございます、深く考えてみました。',
    // コメント: 英文の内容をもれなく含み、日本語として自然に訳しています。
    scenePrompt:
      '大きな会議室で、マネージャーが部下の発言に感心し、意見の質の高さを褒めている。部下は自分の考えを発表した直後で、他の社員も数名参加しているビジネスミーティングの場面。',
    // コメント: 会話の舞台背景や登場人物の動機、状況を具体的に説明しています。englishSentenceやjapaneseSentenceに書かれていない文脈も含んでいます。
    senderVoiceInstruction: '落ち着いていて知的な話し方で、やや感心した様子で',
    receiverVoiceInstruction: '少し謙虚で誠実な口調で',
    incorrectOptions: [
      'おもしろくて全然ためにならない意見でした。',
      // コメント: "おもしろくて全然ためにならない意見でした。"は真逆の意味で、文字数も一致しています。違う単語で始まっています。
      'スタッフ全員に巨大なドーナツを配ります。',
      // コメント: 馬鹿馬鹿しい内容にしており、同じ文字数で始まりも異なります。
      '今日はとても退屈な意見を言いました。',
      // コメント: 逆の意味に近いですが「退屈な」とすることで違う始まりにしています。同じ文字数です。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: '新入社員',
    receiverVoice: 'male',
    englishSentence: 'Have you been instructed on this?',
    // 条件: 10語以下、自然な会話文。TOEICでよく出る"instructed"を自然に含めている。
    japaneseSentence: 'この件について指示を受けましたか？',
    // 条件: 正確かつ自然な訳。「instructed」を「指示を受けた」と自然に訳している。省略なし。
    englishReply: 'Yes, I got clear instructions from HR.',
    // 条件: 自然な返答。instructedの意味が推測できるよう"got clear instructions"とした。熟語・慣用句なし。
    japaneseReply: 'はい、人事部からはっきりとした指示を受けました。',
    // 条件: 返答内容がもれなく含まれている。
    scenePrompt:
      '新入社員が会議室でマネージャーに業務の進め方について質問されている。マネージャーは新しいプロジェクトの手順について指示が伝わっているか確認している。新入社員は少し緊張しながらも、しっかりと人事部から説明を受けたことを伝える。',
    // 条件: 場所・登場人物・状況・動機・会話の背景を具体的に記述している。
    senderVoiceInstruction: '落ち着いていて丁寧だが、少し確認するようなトーンで',
    receiverVoiceInstruction: 'やや緊張しているが、誠実で素直な話し方',
    incorrectOptions: [
      'この件について感想を述べましたか？', //「指示」→「感想」に変え真逆の意味にした。文字数一致。「この件について」で始めていてjapaneseSentenceと異なる。文法的に成立。
      '上司の目の前で歌を歌いましたか？', // 馬鹿馬鹿しい内容。文字数一致。違う語で始めている。
      '最近この件について決定を下しましたか？', //「指示を受けた」の反対（自分が決定する側）。「最近」で始めていて他と被らない。文字数一致。
    ],
    // 条件: 3文とも違う単語で始まり、すべてjapaneseSentence（18文字）と同じ文字数。1つは馬鹿馬鹿しい内容、1つは真逆。
  },
];

export default problemData;
