import { SeedProblemData } from '../src/types/problem';

const problems: SeedProblemData[] = [
  {
    place: 'レストランのテーブル',
    senderRole: '客',
    senderVoice: 'female',
    receiverRole: 'ウェイター',
    receiverVoice: 'male',
    englishSentence: 'Could we split the bill?',
    japaneseSentence: 'お会計を分けてもらえますか？',
    englishReply: 'Sure, I’ll prepare separate checks.',
    japaneseReply: 'はい、別々にしますね。',
    incorrectOptions: [
      '辛さは調整できますか？',
      'デザートはまだですか？',
      '席を変えてもいいですか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: 'コンビニのレジ',
    senderRole: '店員',
    senderVoice: 'male',
    receiverRole: '客',
    receiverVoice: 'female',
    englishSentence: 'Would you like a bag for this?',
    japaneseSentence: '袋はご利用になりますか？',
    englishReply: 'No, I can carry it as is.',
    japaneseReply: 'いえ、そのままで大丈夫です。',
    incorrectOptions: ['温めますか？', 'ポイントカードはありますか？', 'トイレは使えますか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: 'ホテルのロビー',
    senderRole: '宿泊客',
    senderVoice: 'male',
    receiverRole: 'フロントスタッフ',
    receiverVoice: 'female',
    englishSentence: 'Can you hold my luggage till noon?',
    japaneseSentence: 'お昼まで荷物を預かってもらえますか？',
    englishReply: 'Yes, we’ll store it safely here.',
    japaneseReply: 'はい、こちらでお預かりします。',
    incorrectOptions: [
      'チェックインは何時からですか？',
      '朝食はどこで食べられますか？',
      'ランドリーは使えますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '空港のチェックインカウンター',
    senderRole: '乗客',
    senderVoice: 'female',
    receiverRole: '係員',
    receiverVoice: 'male',
    englishSentence: 'Could you upgrade me if seats are available?',
    japaneseSentence: '空席があれば席をアップグレードできますか？',
    englishReply: 'I’ll check, please wait a moment.',
    japaneseReply: '確認しますので少々お待ちください。',
    incorrectOptions: ['荷物は追加できますか？', '次の便は何時ですか？', '搭乗口はどこですか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '図書館の受付',
    senderRole: '利用者',
    senderVoice: 'male',
    receiverRole: '司書',
    receiverVoice: 'female',
    englishSentence: 'Do you have any books on astronomy?',
    japaneseSentence: '天文学の本はありますか？',
    englishReply: 'Yes, they’re on the second floor.',
    japaneseReply: 'はい、二階にございます。',
    incorrectOptions: ['延長できますか？', 'Wi-Fiはありますか？', 'コピー機は使えますか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: 'バス停のベンチ',
    senderRole: '観光客',
    senderVoice: 'female',
    receiverRole: '通行人',
    receiverVoice: 'male',
    englishSentence: 'Does this bus go downtown?',
    japaneseSentence: 'このバスは中心街に行きますか？',
    englishReply: 'Yes, just stay on until the last stop.',
    japaneseReply: 'はい、終点まで行けば着きますよ。',
    incorrectOptions: ['タクシーはありますか？', '地図を持っていますか？', 'ここはどこですか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: 'カフェのカウンター',
    senderRole: '客',
    senderVoice: 'female',
    receiverRole: '店員',
    receiverVoice: 'male',
    englishSentence: 'Could you go easy on the sugar?',
    japaneseSentence: '砂糖を少なめにしてもらえますか？',
    englishReply: 'Sure, I’ll make it less sweet.',
    japaneseReply: 'はい、甘さ控えめにしますね。',
    incorrectOptions: [
      'サイズを変えられますか？',
      'アイスにできますか？',
      'カップは持参できますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: 'スーパーのレジ',
    senderRole: '客',
    senderVoice: 'male',
    receiverRole: 'レジ係',
    receiverVoice: 'female',
    englishSentence: 'Can I pay by credit card?',
    japaneseSentence: 'クレジットカードで支払えますか？',
    englishReply: 'Yes, insert it into the machine.',
    japaneseReply: 'はい、機械にお入れください。',
    incorrectOptions: ['袋は必要ですか？', '温めますか？', '値引きできますか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '郵便局の窓口',
    senderRole: '客',
    senderVoice: 'female',
    receiverRole: '局員',
    receiverVoice: 'male',
    englishSentence: 'Could I get five-hundred-yen stamps?',
    japaneseSentence: '五百円切手をいただけますか？',
    englishReply: 'Yes, here are the stamps.',
    japaneseReply: 'はい、こちらになります。',
    incorrectOptions: ['航空便にしますか？', '速達にしますか？', '宛名を書きますか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '映画館のホール',
    senderRole: '友人',
    senderVoice: 'male',
    receiverRole: '友人',
    receiverVoice: 'female',
    englishSentence: 'Want to grab popcorn before it starts?',
    japaneseSentence: '始まる前にポップコーン買わない？',
    englishReply: 'Yeah, let’s get a large one.',
    japaneseReply: 'うん、大きいのを買おう。',
    incorrectOptions: ['今日は誰と来たの？', '次は何を見る？', '席はどこだっけ？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: 'ホテルのフロント',
    senderRole: '宿泊客',
    senderVoice: 'female',
    receiverRole: 'フロントスタッフ',
    receiverVoice: 'male',
    englishSentence: 'Could I get an extra blanket?',
    japaneseSentence: '毛布をもう一枚いただけますか？',
    englishReply: 'Yes, I’ll send one to your room.',
    japaneseReply: 'はい、お部屋にお持ちします。',
    incorrectOptions: ['チェックインできますか？', '朝食はどこですか？', 'ジムは使えますか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '空港の荷物受取所',
    senderRole: '旅行者',
    senderVoice: 'male',
    receiverRole: '係員',
    receiverVoice: 'female',
    englishSentence: 'My suitcase hasn’t shown up yet.',
    japaneseSentence: 'スーツケースがまだ出てこないんです。',
    englishReply: 'I’ll check the system for you.',
    japaneseReply: 'システムで確認いたしますね。',
    incorrectOptions: ['搭乗口はどこですか？', 'パスポートは必要ですか？', '免税品はどこですか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '駅の改札前',
    senderRole: '通勤客',
    senderVoice: 'female',
    receiverRole: '駅員',
    receiverVoice: 'male',
    englishSentence: 'This ticket isn’t working at the gate.',
    japaneseSentence: 'この切符が改札を通らないんです。',
    englishReply: 'I see, let me reissue it for you.',
    japaneseReply: 'わかりました、再発行しますね。',
    incorrectOptions: ['トイレはどこですか？', '窓口は開いていますか？', '電車は遅れていますか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '会社の会議室',
    senderRole: '部下',
    senderVoice: 'male',
    receiverRole: '上司',
    receiverVoice: 'female',
    englishSentence: 'Could I run an idea by you?',
    japaneseSentence: 'ちょっとアイデアを相談してもいいですか？',
    englishReply: 'Sure, go ahead and share it.',
    japaneseReply: 'いいですよ、話してみてください。',
    incorrectOptions: [
      '今会議を始めますか？',
      '資料を印刷しましょうか？',
      '次回はいつにしますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '病院の受付',
    senderRole: '患者',
    senderVoice: 'female',
    receiverRole: '受付スタッフ',
    receiverVoice: 'male',
    englishSentence: 'Do I need an appointment for today?',
    japaneseSentence: '今日は予約が必要ですか？',
    englishReply: 'Yes, but we have walk-in slots left.',
    japaneseReply: 'はい、ただし当日受付もございます。',
    incorrectOptions: ['診察券は必要ですか？', '支払いは先ですか？', '薬はここでもらえますか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: 'スーパーのレジ',
    senderRole: 'レジ係',
    senderVoice: 'male',
    receiverRole: '客',
    receiverVoice: 'female',
    englishSentence: 'Do you have a point card?',
    japaneseSentence: 'ポイントカードはお持ちですか？',
    englishReply: 'No, I don’t have one.',
    japaneseReply: 'いえ、持っていません。',
    incorrectOptions: ['温めますか？', 'お釣りはありますか？', '領収書は必要ですか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '郵便局の窓口',
    senderRole: '局員',
    senderVoice: 'female',
    receiverRole: '客',
    receiverVoice: 'male',
    englishSentence: 'Would you like insurance for this parcel?',
    japaneseSentence: 'この荷物に補償をつけますか？',
    englishReply: 'No, that won’t be necessary.',
    japaneseReply: 'いえ、必要ありません。',
    incorrectOptions: ['宛名は書きましたか？', '封筒は必要ですか？', '料金はご存じですか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '映画館のロビー',
    senderRole: '友人',
    senderVoice: 'male',
    receiverRole: '友人',
    receiverVoice: 'female',
    englishSentence: 'Want to grab seats near the front?',
    japaneseSentence: '前の方の席に座ろうか？',
    englishReply: 'Nah, I’d rather sit in the middle.',
    japaneseReply: 'いや、真ん中あたりがいいな。',
    incorrectOptions: ['ポップコーン買う？', '何時に始まる？', 'トイレ行く？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: 'カフェのカウンター',
    senderRole: '客',
    senderVoice: 'female',
    receiverRole: '店員',
    receiverVoice: 'male',
    englishSentence: 'Can I get this with soy milk?',
    japaneseSentence: 'これを豆乳で作ってもらえますか？',
    englishReply: 'Yes, we can switch it to soy milk.',
    japaneseReply: 'はい、豆乳に変更できます。',
    incorrectOptions: ['氷は入れますか？', 'サイズはどうしますか？', '甘さは普通でいいですか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '公園のベンチ',
    senderRole: '友人',
    senderVoice: 'female',
    receiverRole: '友人',
    receiverVoice: 'male',
    englishSentence: 'Fancy taking a walk around?',
    japaneseSentence: '散歩でもしない？',
    englishReply: 'Yeah, the weather’s perfect for it.',
    japaneseReply: 'うん、天気もちょうどいいね。',
    incorrectOptions: ['今日は仕事あるの？', '音楽聴く？', '宿題は終わった？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: 'ショッピングモールのフードコート',
    senderRole: '店員',
    senderVoice: 'female',
    receiverRole: '客',
    receiverVoice: 'male',
    englishSentence: 'Would you like fries with that?',
    japaneseSentence: 'フライドポテトを一緒にいかがですか？',
    englishReply: 'Yes, make it a small one.',
    japaneseReply: 'はい、小さいサイズでお願いします。',
    incorrectOptions: ['支払いはカードですか？', 'ソースをかけますか？', '温め直しますか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: 'ホテルのロビー',
    senderRole: 'フロントスタッフ',
    senderVoice: 'male',
    receiverRole: '宿泊客',
    receiverVoice: 'female',
    englishSentence: 'Could you sign here for check-in?',
    japaneseSentence: 'チェックインのため、こちらにご署名いただけますか？',
    englishReply: 'Yes, here’s my signature.',
    japaneseReply: 'はい、署名しました。',
    incorrectOptions: [
      '荷物を預けられますか？',
      '朝食はついていますか？',
      'エレベーターはどこですか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '図書館の学習スペース',
    senderRole: '司書',
    senderVoice: 'female',
    receiverRole: '利用者',
    receiverVoice: 'male',
    englishSentence: 'Please keep your phone on silent.',
    japaneseSentence: '携帯電話はマナーモードにしてください。',
    englishReply: 'Sure, I’ll turn it to silent.',
    japaneseReply: 'わかりました、マナーモードにします。',
    incorrectOptions: ['本は借りられますか？', 'コピーできますか？', 'パソコンは使えますか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '駅のホーム',
    senderRole: '観光客',
    senderVoice: 'male',
    receiverRole: '駅員',
    receiverVoice: 'female',
    englishSentence: 'Does this train stop at Kyoto?',
    japaneseSentence: 'この電車は京都に止まりますか？',
    englishReply: 'Yes, it stops there after Osaka.',
    japaneseReply: 'はい、大阪の次に止まりますよ。',
    incorrectOptions: ['切符はここで買えますか？', '改札はどこですか？', 'バスはありますか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: 'カフェのテーブル',
    senderRole: '友人',
    senderVoice: 'female',
    receiverRole: '友人',
    receiverVoice: 'male',
    englishSentence: 'Mind if I borrow your pen?',
    japaneseSentence: 'ペンをちょっと借りてもいい？',
    englishReply: 'Yeah, here you go.',
    japaneseReply: 'うん、どうぞ。',
    incorrectOptions: ['宿題は終わった？', '飲み物は頼む？', '今日は何時に帰る？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '郵便局の窓口',
    senderRole: '客',
    senderVoice: 'male',
    receiverRole: '局員',
    receiverVoice: 'female',
    englishSentence: 'Can I send this by airmail?',
    japaneseSentence: 'これを航空便で送れますか？',
    englishReply: 'Yes, please fill out this form.',
    japaneseReply: 'はい、この用紙にご記入ください。',
    incorrectOptions: ['切手はどこで買えますか？', '封筒はありますか？', '窓口は何時までですか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: 'スーパーの野菜売り場',
    senderRole: '客',
    senderVoice: 'female',
    receiverRole: '店員',
    receiverVoice: 'male',
    englishSentence: 'Is this lettuce fresh today?',
    japaneseSentence: 'このレタスは今日のものですか？',
    englishReply: 'Yes, it was delivered this morning.',
    japaneseReply: 'はい、今朝入荷しました。',
    incorrectOptions: ['値引きはありますか？', '洗ってありますか？', '保存方法はどうですか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '会社の会議室',
    senderRole: '同僚',
    senderVoice: 'male',
    receiverRole: '同僚',
    receiverVoice: 'female',
    englishSentence: 'Could you take the minutes today?',
    japaneseSentence: '今日の議事録をお願いできますか？',
    englishReply: 'Sure, I’ll write them down.',
    japaneseReply: 'わかりました、記録します。',
    incorrectOptions: ['会議を始めますか？', '次回はいつにしますか？', '休憩を入れますか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '病院の薬局カウンター',
    senderRole: '薬剤師',
    senderVoice: 'female',
    receiverRole: '患者',
    receiverVoice: 'male',
    englishSentence: 'Please take this after each meal.',
    japaneseSentence: 'こちらは食後に服用してください。',
    englishReply: 'Okay, after breakfast, lunch, and dinner.',
    japaneseReply: 'わかりました、朝昼晩ですね。',
    incorrectOptions: ['痛みはありますか？', '予約はしていますか？', '診察券はお持ちですか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '公園のベンチ',
    senderRole: '友人',
    senderVoice: 'male',
    receiverRole: '友人',
    receiverVoice: 'female',
    englishSentence: 'How about grabbing coffee later?',
    japaneseSentence: 'あとでコーヒーでも飲まない？',
    englishReply: 'Yeah, I’d love that.',
    japaneseReply: 'うん、ぜひ行こう。',
    incorrectOptions: ['宿題は終わった？', '散歩に行く？', '本を読んだ？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
];

export default problems;
