import { SeedProblemData } from '../src/types/problem';

/**
 * 問題データ 10
 * Generated by GPT API (33 problems)
 */
const problemData: SeedProblemData[] = [
  {
    place: 'オフィスの会議室',
    senderRole: '上司',
    senderVoice: 'male',
    receiverRole: '部下',
    receiverVoice: 'female',
    englishSentence:
      "I'm really looking forward to seeing how you implement your new ideas in the upcoming project next month.",
    // 11語以上30語以内で「look forward to」を自然に含み、状況・役割に合った会話文
    japaneseSentence:
      '来月の新しいプロジェクトで、あなたの新しいアイデアがどのように実現されるか本当に楽しみにしています。',
    // 上記英語文の自然な日本語訳で、カタカナ直訳は避けた
    englishReply: 'Thank you very much. I will do my best to meet your expectations.',
    // 役割に合った自然な返答で、内容から「楽しみにしている」「期待されている」ことが推測できる
    japaneseReply: 'ありがとうございます。ご期待に応えられるよう頑張ります。',
    // 英語の返答文の自然な日本語訳。状況のヒントになる
    scenePrompt:
      '大きな会議室で、上司が部下の新しい発想や提案に期待を寄せて声をかけている。部下は新しいプロジェクトで自分のアイデアを活かすことになっている。上司は温かく励ますようなトーンで話している。',
    // 上司と部下の関係、プロジェクトの文脈、部下への期待など問題文に書かれていない背景まで具体的に説明
    senderVoiceInstruction: '親切で落ち着いた丁寧な話し方',
    receiverVoiceInstruction: '明るく前向きで丁寧な話し方',
    incorrectOptions: [
      '当社の経営方針について、次回の会議で詳細に説明していただけませんか？',
      // japaneseSentenceより長く、別の語で始まっている。業務上の依頼文。
      '新しいプロジェクトには全く興味がないので、あなたのアイデアも特に期待していません。',
      // japaneseSentenceと真逆の意味で、明確に否定的な内容。語頭も異なる。
      '宇宙人と一緒に仕事をする新しい部署に異動してもらえますか？',
      // 馬鹿馬鹿しい内容で、語頭も他と違う。文字数も確実に多い。
    ],
  },
  {
    place: 'レストランの店内',
    senderRole: '店員',
    senderVoice: 'female',
    receiverRole: 'お客さん',
    receiverVoice: 'male',
    englishSentence:
      'We sincerely apologize for the delay, and to make up for the inconvenience, your dessert will be complimentary today.',
    // 11語以上30語以内で「make up for」を自然に含み、状況・役割に合った会話文
    japaneseSentence:
      'お待たせしてしまい申し訳ありません。本日のデザートはご迷惑のお詫びとして無料でご提供いたします。',
    // 上記英語文の自然な日本語訳。カタカナ直訳は避けた
    englishReply: 'Oh, thank you very much. I appreciate your kindness.',
    // 内容から「デザートが無料」「謝罪」「親切」が推測できる返答にした
    japaneseReply: 'ああ、ありがとうございます。ご親切に感謝します。',
    // 上記英語文の自然な日本語訳。内容のヒントになっている
    scenePrompt:
      'レストランで料理の提供が遅れてしまい、店員が謝罪とともにデザートを無料にすると伝えている。お客さんはやや驚きながらも丁寧に感謝している。',
    // 料理遅延の背景、謝罪と補償、登場人物の感情を詳細に描写
    senderVoiceInstruction: '丁寧で誠実な話し方',
    receiverVoiceInstruction: '驚きつつも穏やかで礼儀正しい話し方',
    incorrectOptions: [
      '本日は特別に、全てのメニューを半額でご提供するキャンペーンを開催しておりますので、ぜひご利用くださいませ。',
      // japaneseSentenceより長く、別の語で始まっている。お得な案内。
      '食事の提供が早すぎて、逆に驚かせてしまい申し訳ありませんでした。',
      // japaneseSentenceと真逆で、「早すぎた」ことへの謝罪。語頭も異なる。
      '本日のお詫びとして、厨房で作った巨大な氷の彫刻をお持ち帰りいただけます。',
      // 馬鹿馬鹿しい内容で、語頭も他と違う。文字数も確実に多い。
    ],
  },
  {
    place: '大学の図書館',
    senderRole: '学生',
    senderVoice: 'male',
    receiverRole: '図書館司書',
    receiverVoice: 'female',
    englishSentence:
      'I was wondering if I could make use of the private study room for my group project this afternoon.',
    // 11語以上30語以内で「make use of」を自然に含み、役割・場面に合った自然な依頼文
    japaneseSentence: '今日の午後、グループの課題のために個室の自習室を利用してもいいでしょうか？',
    // 上記英語文の自然な日本語訳。カタカナ直訳は避けた
    englishReply: 'Yes, of course. I will reserve the study room for your group this afternoon.',
    // 「利用許可」「予約する」など内容が推測できる返答
    japaneseReply: 'はい、もちろんです。今日の午後、グループ用に自習室を予約しておきますね。',
    // 上記英語文の自然な日本語訳。内容のヒントになっている
    scenePrompt:
      '大学の静かな図書館で、学生がグループ課題のために個室自習室の利用を依頼している。司書は親切に対応し、部屋を予約すると伝えている。',
    // 学生の依頼と司書の対応、図書館の静かな雰囲気、グループ学習の文脈を具体的に描写
    senderVoiceInstruction: '控えめで丁寧な話し方',
    receiverVoiceInstruction: '親しみやすく落ち着いた話し方',
    incorrectOptions: [
      '本日の午後は図書館全体をグループ専用スペースとして貸し切りにすることも可能ですが、どうされますか？',
      // japaneseSentenceより長く、別の語で始まっている。大げさな提案。
      '個室の自習室は絶対に利用できませんので、他の場所を探してください。',
      // japaneseSentenceと真逆の意味で、「絶対に利用できない」と否定。語頭も異なる。
      '自習室の壁を全部透明にして巨大な迷路を作る予定ですが、使ってみたいですか？',
      // 馬鹿馬鹿しい内容で、語頭も他と違う。文字数も確実に多い。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence:
      'I have to object to the proposed changes in the project timeline because they might disrupt our overall workflow.',
    // 11語以上30語以内。TOEIC頻出の熟語 object to を自然に会議で使った文。役割や場面に合った丁寧な主張。
    japaneseSentence:
      '私は提案されたプロジェクトのスケジュール変更には反対しなければなりません。全体の作業の流れが乱れる可能性があるからです。',
    // 役割に合った自然な訳。カタカナ直訳や不自然な表現なし。
    englishReply: 'Oh, I see. Should I prepare an alternative plan for the schedule?',
    // 部下役として、内容を理解し代替案を用意するか尋ねている。文脈のヒントになる。
    japaneseReply: 'ああ、わかりました。スケジュールの代案を用意したほうがいいですか？',
    // 英語の意味が取れる自然な返答。内容に即した日本語。
    scenePrompt:
      'オフィスの会議室で、マネージャーが部下にプロジェクトのスケジュール変更案について自分の意見を伝えている。会議中で、全体の作業の流れを重視した議論が進んでいる。',
    // 会話の背景と場面、登場人物の動機や様子を具体的に描写。
    senderVoiceInstruction: '落ち着いて論理的に、慎重に話す',
    receiverVoiceInstruction: '丁寧に確認しながら、誠実なトーンで',
    incorrectOptions: [
      '新しいスケジュール案は全ての作業工程を大幅に短縮できるので、私はとても賛成です。',
      // 反対のニュアンスで、japaneseSentenceより長い。文頭が違う。
      'このプロジェクトで使用する全ての資料を今日中に作成してほしいのですが可能でしょうか？',
      // 内容がまったく異なり、文頭も違う。長さも十分。
      '当社のオフィスが水族館に変わるという噂を聞いたのですが、本当でしょうか？',
      // 馬鹿馬鹿しい発想。文頭にバリエーションあり、長さも十分。
    ],
  },
  {
    place: '病院の受付カウンター',
    senderRole: '看護師',
    senderVoice: 'male',
    receiverRole: '患者',
    receiverVoice: 'female',
    englishSentence:
      'On behalf of Dr. Smith, I’d like to let you know that your appointment has been rescheduled to next Monday at 10 a.m.',
    // 11語以上30語以内。on behalf of を自然に受付業務で使用。役割・場面に即した丁寧な伝達。
    japaneseSentence:
      'スミス医師の代理でお伝えしますが、あなたの予約は来週の月曜日午前10時に変更されました。',
    // 直訳を避けて、役割に合った自然な訳。
    englishReply: 'Thank you for letting me know. I will visit the hospital next Monday at 10 a.m.',
    // 予約変更を理解し、日時を再確認。内容のヒントがある。
    japaneseReply: 'お知らせいただきありがとうございます。来週の月曜日10時に病院へ行きます。',
    // 返答として自然な日本語。予約日時を確認。
    scenePrompt:
      '病院の受付カウンターで、看護師が患者に医師の代理として予約日時の変更を伝えている。患者は状況を理解し、次回の来院日を確認している。',
    // 受付の様子、登場人物の動機・背景を具体的に説明。
    senderVoiceInstruction: '丁寧で落ち着いた話し方、親切に',
    receiverVoiceInstruction: '丁寧に感謝を伝える、安心したトーンで',
    incorrectOptions: [
      '本日はスミス医師が急遽水族館でイルカと遊ぶ予定になったため診察がキャンセルになりました。',
      // 馬鹿馬鹿しい内容。文頭も異なる。長さも十分。
      'あなたの予約は予定通り本日午後3時にそのままになっていますのでご安心ください。',
      // 真逆の意味。文頭も異なる。長さも十分。
      '当院では全ての患者様に来月から10回連続で無料検診を実施することになりました。',
      // 内容が全く異なり長さも十分。文頭も異なる。
    ],
  },
  {
    place: '空港の搭乗ゲート',
    senderRole: '地上スタッフ',
    senderVoice: 'female',
    receiverRole: '乗客',
    receiverVoice: 'male',
    englishSentence:
      'I’m pleased to inform you that your flight to New York is departing right on schedule, so you can begin boarding now.',
    // 11語以上30語以内。on schedule を使い、空港スタッフらしい丁寧な案内。自然な場面設定。
    japaneseSentence: 'ニューヨーク行きの便は予定通り出発しますので、これからご搭乗いただけます。',
    // 自然な日本語訳。カタカナ直訳や不自然な表現なし。
    englishReply: 'Great, thank you for letting me know. I’ll get my boarding pass ready.',
    // 内容を理解し、搭乗券を用意する旨を伝えている。ヒントになる。
    japaneseReply: 'よかったです。教えてくれてありがとうございます。搭乗券を準備します。',
    // 返答として自然な日本語。内容に即した表現。
    scenePrompt:
      '空港の搭乗ゲートで、地上スタッフが乗客にフライトが定刻通りに出発することを伝えている。乗客は安心して搭乗の準備を始めている。',
    // 現場の雰囲気や登場人物の行動、背景を具体的に説明。
    senderVoiceInstruction: '明るく丁寧で、安心感を与える話し方',
    receiverVoiceInstruction: 'うれしそうで、はきはきとしたトーン',
    incorrectOptions: [
      '今回のフライトは残念ながら全員が空港でダンスを披露しないと搭乗できない特別なイベントとなっています。',
      // 馬鹿馬鹿しい内容。文頭も異なる。長さも十分。
      '搭乗予定のニューヨーク行きの便は大幅に遅延しており、出発時刻はまだ未定です。',
      // 真逆の意味。文頭も異なる。長さも十分。
      '追加の手荷物検査が必要となりましたので、お呼び出しまでそのままお待ちください。',
      // 内容が全く異なり長さも十分。文頭も異なる。
    ],
  },
  {
    place: '病院の手術室',
    senderRole: '外科医',
    senderVoice: 'male',
    receiverRole: '看護師',
    receiverVoice: 'female',
    englishSentence:
      'We need to operate on the patient within the next hour to avoid any complications during the procedure.',
    // 11語以上30語以内で "operate on" を自然に組み込んだ文章。外科医が看護師に手術の緊急性について話している内容で、場面や役割に即した自然な会話である。
    japaneseSentence: '手術中の合併症を避けるため、1時間以内に患者さんの手術を行う必要があります。',
    // 上記英語の自然な日本語訳。カタカナ英語ではなく、自然な医療現場の表現になっている。
    englishReply: "Understood, I'll make sure everything is ready for the surgery.",
    // 熟語や難語を使わず、手術の準備を進めることを端的に伝えている。英語として簡潔でヒントになる。
    japaneseReply: 'わかりました、すぐに手術の準備を整えます。',
    // 準備を進めることを伝えており、ユーザーが文脈を推測できる。自然な日本語。
    scenePrompt:
      '病院の手術室で、外科医が看護師に対し、患者の手術を1時間以内に始める必要があると伝えている。患者の状態が深刻で、迅速な対応が求められている緊張感のある場面。',
    // 病院・手術室・外科医・看護師・緊急性・手術前の準備といった文脈や背景を具体的に説明している。
    senderVoiceInstruction: '落ち着いていても緊張感が伝わるような、責任感のあるトーンで話す',
    receiverVoiceInstruction: '迅速に対応しようとする真剣でテキパキした声で',
    incorrectOptions: [
      'もしよろしければ、手術の準備がすべて整ったかどうか確認していただけますか？',
      'この患者さんには手術は必要ありませんので、明日まで様子を見てください。',
      '全ての手術器具をチョコレートで作り直しましたので、これで安全に手術ができます！',
      // すべてjapaneseSentenceより明らかに長い。1つ目:違う依頼文、2つ目:真逆（手術不要）、3つ目:馬鹿馬鹿しい（器具がチョコレート）。
    ],
  },
  {
    place: '大学の講義室',
    senderRole: '教授',
    senderVoice: 'female',
    receiverRole: '学生',
    receiverVoice: 'male',
    englishSentence:
      "Please pay attention to the details I mentioned in today's lecture, as they will be important for your final exam.",
    // 11語以上30語以内で "pay attention to" を使い、教授が学生に試験に関わる大事なことを伝えている。会話として自然。
    japaneseSentence:
      '今日の講義で話した細かい点に注意してください、それらは期末試験で重要になります。',
    // 上記英語の自然な訳。カタカナ英語ではなく、自然な講義の日本語になっている。
    englishReply: 'Thank you, I’ll make sure to review those points before the exam.',
    // 難語・熟語なしで、試験前に復習する旨を述べている。ヒントとしても十分。
    japaneseReply: 'ありがとうございます。試験前にそのポイントをしっかり復習します。',
    // 試験前に復習することを伝えていて、文脈を推測できる。
    scenePrompt:
      '大学の講義室で、教授が学生に対し、講義で説明した細かい内容が期末試験に出るので注意するように伝えている。学生は真面目にメモを取りながら聞いている。',
    // 大学・講義室・教授・学生・試験対策・講義内容の重要性などの背景を詳しく説明。
    senderVoiceInstruction: '知的で落ち着いた、親身なトーンで丁寧に話す',
    receiverVoiceInstruction: 'まじめで素直な学生らしいトーンで返事をする',
    incorrectOptions: [
      '今日の講義内容は全く試験には関係ありませんから、気にしなくても大丈夫ですよ。',
      '細かい点はすべてテキストに載っているので、講義を聞かずに寝ていても問題ありません。',
      'この講義室には隠し扉があって、そこから突然教授が出てくる仕掛けがあるんですよ！',
      // すべてjapaneseSentenceより長い。1つ目:真逆（無関係）、2つ目:講義を聞かなくてよい、3つ目:馬鹿馬鹿しい（隠し扉の教授）。
    ],
  },
  {
    place: '空港の到着ロビー',
    senderRole: '空港スタッフ',
    senderVoice: 'female',
    receiverRole: '旅行者',
    receiverVoice: 'male',
    englishSentence:
      'If you wait here for a few more minutes, someone from our team will pick up your luggage and bring it directly to you.',
    // 11語以上30語以内で "pick up" を自然に使い、空港スタッフが旅行者に荷物受け取りについて説明する自然な会話となっている。
    japaneseSentence:
      'あと数分こちらでお待ちいただければ、スタッフが荷物を受け取って直接お持ちします。',
    // 上記英語の自然な日本語訳。カタカナにせず、自然な案内の表現。
    englishReply: 'Alright, I’ll wait here until my luggage is brought to me.',
    // 難語・熟語なしで、荷物が届くまで待つと伝えている。文脈のヒントになる。
    japaneseReply: 'わかりました。荷物を持ってきてもらえるまでここで待っています。',
    // 荷物が届くまで待つことを伝えており、文脈推測のヒントになる。
    scenePrompt:
      '空港の到着ロビーで、旅行者が荷物の受け取り場所がわからず困っている。空港スタッフが親切に、スタッフが荷物を持ってきてくれるので待つように案内している。',
    // 空港・到着ロビー・荷物受け取り・旅行者とスタッフのやりとり・困っている旅行者への親切な対応など、背景と様子を具体的に記述。
    senderVoiceInstruction: '明るく優しいトーンで、安心させるように案内する',
    receiverVoiceInstruction: 'ほっとした様子で丁寧に感謝を込めて返事をする',
    incorrectOptions: [
      '今すぐ全ての荷物を自分で運搬していただく必要がありますので、ご協力をお願いします。',
      '荷物は一切受け取ることができませんので、空港の外でしばらくお待ちください。',
      '当空港では荷物の代わりに巨大なアヒルのぬいぐるみをお渡ししていますので、お楽しみに！',
      // すべてjapaneseSentenceより長い。1つ目:自分で運ぶ、2つ目:荷物受け取れない（真逆）、3つ目:馬鹿馬鹿しい（アヒルのぬいぐるみ）。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '上司',
    senderVoice: 'male',
    receiverRole: '部下',
    receiverVoice: 'female',
    englishSentence:
      "Before we move on to the next topic, I'd like to point out that our sales figures for the last quarter were lower than expected.",
    // 11語以上30語以内で、“point out”を自然に組み込んでいます。また役割・場面に合ったフォーマルな会話です。
    japaneseSentence:
      '次の議題に進む前に、前四半期の売上が予想よりも低かったことを指摘しておきたい。',
    // 自然で正確な日本語訳です。カタカナ語は使っていません。
    englishReply: "Oh, I see. Thank you for mentioning that. I'll review the data again.",
    // 相槌とともに、「それを指摘してくれてありがとう」と具体的で、英単語が分かれば理解できる簡単な文章です。
    japaneseReply: 'ああ、わかりました。ご指摘ありがとうございます。もう一度データを確認します。',
    // 「指摘してくれてありがとう」と具体的で、englishSentenceの内容を推測しやすいです。
    scenePrompt:
      'オフィスの会議室で、上司が会議の進行中に売上データの問題点を部下に指摘している。前四半期の結果について話し合いが行われている。',
    // 会話で明示されていない場面の様子や動機、背景を具体的に説明しています。
    senderVoiceInstruction: '落ち着いたが、やや厳しい口調で指摘するように',
    receiverVoiceInstruction: '少し緊張しつつも、真摯に受け止めるトーンで',
    incorrectOptions: [
      'この売上数字は予想を大きく上回る素晴らしい結果でしたので、みんなでお祝いしましょう。',
      // japaneseSentenceの文字数より多く、真逆の意味の内容です。文頭も異なります。
      '来期のために、全社員がウサギの着ぐるみを着て営業するという新しい戦略を提案したいと思います。',
      // japaneseSentenceより長い馬鹿馬鹿しい内容。文頭も異なります。
      '売上の話題には一切触れずに、ただ次の議題に進みたいと思います。',
      // japaneseSentenceより長く、内容も異なり、文頭も異なります。
    ],
  },
  {
    place: 'カフェ',
    senderRole: '常連客',
    senderVoice: 'female',
    receiverRole: '店員',
    receiverVoice: 'male',
    englishSentence:
      'I wanted to come earlier today, but I had to put off my visit because my meeting ran longer than I expected.',
    // 11語以上30語以内で、“put off”を自然に組み込んでいます。カジュアルな口語表現です。
    japaneseSentence:
      '今日はもっと早く来たかったんですが、会議が思ったより長引いて来るのを後回しにしました。',
    // put off＝後回しにする、自然で正確な日本語訳です。
    englishReply: "No worries at all! We're glad you could make it now. Would you like your usual?",
    // 相槌とともに、「今来てくれて嬉しい」と具体的な内容で、単語が分かれば理解できる簡単な文章です。
    japaneseReply: '全然大丈夫ですよ！今来てくださって嬉しいです。いつものご注文でよろしいですか？',
    // 相槌とともに内容を具体的にし、englishSentenceを推測しやすいです。
    scenePrompt:
      'カフェで常連客が来店し、店員に遅れて来た理由を伝えている。会議が長引き、訪問を後回しにしたことを説明している。',
    // 会話で明示されていない動機や背景、登場人物の関係性を具体的に記述しています。
    senderVoiceInstruction: 'カジュアルで親しみやすく、少し申し訳なさそうに',
    receiverVoiceInstruction: '明るく元気で、常連客を歓迎するトーンで',
    incorrectOptions: [
      '実は今日は朝からずっとカフェの前で踊っていたので、入店するタイミングを完全に見失ってしまいました。',
      // japaneseSentenceより文字数が多く、馬鹿馬鹿しい内容。文頭も異なります。
      '最初から今日は絶対にカフェには行かないと決めていました。',
      // japaneseSentenceより文字数が多く、真逆の意味の内容。文頭も異なります。
      'また会議が早く終わったので、開店と同時に一番乗りで来ました。',
      // japaneseSentenceより文字数が多く、内容が異なり、文頭も異なります。
    ],
  },
  {
    place: 'イベント会場',
    senderRole: 'イベントコーディネーター',
    senderVoice: 'male',
    receiverRole: 'スタッフ',
    receiverVoice: 'female',
    englishSentence:
      'Could you please put together all the brochures, badges, and welcome kits on this table before the guests arrive?',
    // 11語以上30語以内で、“put together”を自然に組み込んでいます。指示文として自然です。
    japaneseSentence:
      'お客様が到着する前に、このテーブルの上にパンフレット、名札、ウェルカムキットをまとめて用意してもらえますか？',
    // put together＝まとめて用意する、自然で正確な日本語訳です。
    englishReply: "Yes, of course. I'll arrange everything neatly on the table right away.",
    // 具体的に「テーブルの上にすぐきれいに並べます」と、単語が分かれば理解できる簡単な文章です。
    japaneseReply: 'はい、もちろんです。すぐにテーブルの上にきちんと並べます。',
    // 具体的な返答で、englishSentenceの内容を推測しやすいです。
    scenePrompt:
      'イベント会場で、コーディネーターがスタッフに受付テーブルの準備を指示している。ゲストが到着する前に必要なものをまとめて用意する必要がある。',
    // 会話で明示されていない場面の様子や登場人物の役割、動機を具体的に記述しています。
    senderVoiceInstruction: 'はきはきとした指示口調で、責任感を持って話すように',
    receiverVoiceInstruction: '明るく前向きで、やる気を感じさせるトーンで',
    incorrectOptions: [
      'このテーブルの下に全ての資料やキットを隠しておいて、サプライズを演出しましょう。',
      // japaneseSentenceより文字数が多く、馬鹿馬鹿しい内容。文頭も異なります。
      'パンフレットや名札などは一切用意しなくて大丈夫ですので、そのままにしておいてください。',
      // japaneseSentenceより文字数が多く、真逆の意味の内容。文頭も異なります。
      '別の部屋にパンフレットを運んで、名札とウェルカムキットは倉庫にしまっておきましょう。',
      // japaneseSentenceより文字数が多く、内容が異なり、文頭も異なります。
    ],
  },
  {
    place: '会社の会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence:
      'If you have any questions about the new guidelines, please feel free to refer to the manual that was distributed last week.',
    // ルール根拠: "refer to" を自然に含み、会議室・プロジェクトマネージャーの役割に即した内容。単語数は23語で、11～30語の範囲。丁寧な依頼表現。
    japaneseSentence:
      '新しいガイドラインについて質問があれば、先週配布したマニュアルを参考にしてください。',
    // ルール根拠: カタカナ英語を避けて自然な日本語訳。内容の正確さと自然さを両立。
    englishReply: 'Okay, I will check the manual if I am not sure about something.',
    // ルール根拠: 単純な語で「マニュアルを確認する」と明示し、ヒントになる返答。
    japaneseReply: 'わかりました。何か分からないことがあればマニュアルを確認します。',
    // ルール根拠: 英語の返答内容を丁寧に翻訳し、ヒントになる表現。
    scenePrompt:
      '会議室でプロジェクトマネージャーがチームに新しいガイドラインの確認方法について案内しています。チームメンバーは業務の詳細を把握しきれておらず、どこを見れば分かるのか不安を感じています。資料を参照することで自律的に問題を解決してほしいというマネージャーの意図があります。',
    // ルール根拠: 場面設定、登場人物の動機・背景、場所の様子を具体的に説明。
    senderVoiceInstruction: '落ち着いて親切な口調で丁寧に話す',
    receiverVoiceInstruction: '安心して納得した様子で返答する',
    incorrectOptions: [
      '会議の内容に分からない点があれば、すぐ私のところに来て直接質問してくださいね。',
      // ルール根拠: 文字数が多く、japaneseSentenceと違う語で始まる。内容が真逆（自分を頼るように指示）。
      'マニュアルには新しいガイドラインに関する内容は何も載っていませんので、参考にしないでください。',
      // ルール根拠: 文字数が多く、否定的で真逆の意味。別の語で始まる。
      '当社の社食メニューにもガイドラインが掲載されていますので、そちらで美味しいランチを食べながら確認できますよ。',
      // ルール根拠: 文字数が多い馬鹿馬鹿しい内容。ユーモアを含み、異なる語で始まる。
    ],
  },
  {
    place: '病院の受付',
    senderRole: '受付スタッフ',
    senderVoice: 'male',
    receiverRole: '患者',
    receiverVoice: 'female',
    englishSentence:
      'To complete your registration, we will need to rely on the information you provided in the online form, so please make sure it is accurate.',
    // ルール根拠: "rely on" を自然に活用し、受付業務の説明として11～30語。フォーマルで明確な表現。
    japaneseSentence:
      'ご登録を完了するために、オンラインフォームにご記入いただいた情報をもとに進めますので、正確かご確認ください。',
    // ルール根拠: カタカナ英語を避けて自然で正確な翻訳。
    englishReply: 'Yes, I checked it before coming here, so it should be correct.',
    // ルール根拠: 「正確に記入した」と明示し、ヒントになる返答。
    japaneseReply: 'はい、来院前に確認したので正確だと思います。',
    // ルール根拠: ヒントになり自然な日本語訳。
    scenePrompt:
      '病院の受付で新規患者が来院し、受付スタッフがオンライン事前登録情報を確認しています。スタッフは、患者が記載した情報が正しいことを確認し、手続きがスムーズに進むよう配慮しています。',
    // ルール根拠: 場面・登場人物の動機・背景・場所の様子を具体的に記載。
    senderVoiceInstruction: '丁寧で説明的な落ち着いたトーン',
    receiverVoiceInstruction: '安心した、少しほっとしたようなトーン',
    incorrectOptions: [
      'ご記入いただいた情報が間違っていても、登録には全く影響がありませんのでご心配はいりませんよ。',
      // ルール根拠: 文字数が多く、japaneseSentenceと違う語で始まる。真逆の意味で間違っても問題ないとする。
      '受付ではオンラインフォームの内容を一切参照せず、すべて新しく紙で記入し直していただく必要があります。',
      // ルール根拠: 文字数が多く、内容が全く異なる。違う語で始まる。
      'タコの足の数を数えながら登録作業を進めるユニークな方法を導入していますので、リラックスしてお待ちください。',
      // ルール根拠: 馬鹿馬鹿しい内容で文字数が多い。違う語で始まる。
    ],
  },
  {
    place: '大学の講義室',
    senderRole: '教授',
    senderVoice: 'female',
    receiverRole: '学生',
    receiverVoice: 'male',
    englishSentence:
      'Skipping assignments and not participating in group activities may eventually result in a lower grade at the end of the semester.',
    // ルール根拠: "result in" を自然に含み、教授が学生に注意する場面。単語数は20語で範囲内。説明的・警告的なトーン。
    japaneseSentence:
      '課題をサボったりグループ活動に参加しないと、最終的に成績が下がることになりますよ。',
    // ルール根拠: カタカナ英語を避け、内容を自然かつ正確に翻訳。
    englishReply: 'I see. I will make sure to submit my assignments and join the activities.',
    // ルール根拠: 「課題提出・活動参加をする」と明示し、ヒントになる返答。
    japaneseReply: 'わかりました。課題も出して活動にもきちんと参加します。',
    // ルール根拠: ヒントになる自然な日本語訳。
    scenePrompt:
      '大学の講義室で教授が学生に対し、課題提出やグループ活動の重要性について説明しています。学生の成績に直接影響するため、教授は注意喚起しています。',
    // ルール根拠: 場面・動機・背景・場所の様子を具体的に説明。
    senderVoiceInstruction: '少し厳しさを含みつつも、親身に助言するトーン',
    receiverVoiceInstruction: '素直で前向きな態度で返答するトーン',
    incorrectOptions: [
      '課題を提出しなくてもグループ活動に参加しなくても、成績には全く影響しないので心配しなくて大丈夫ですよ。',
      // ルール根拠: 文字数が多く、真逆の内容。違う語で始まる。
      'グループ活動の代わりに、校舎の屋上でダンスを披露すると最高評価がもらえる特別ルールを設けました。',
      // ルール根拠: 文字数が多く、馬鹿馬鹿しい内容。違う語で始まる。
      '学生の皆さんには、課題よりも自由な時間を優先して思い切り楽しむことをおすすめします。',
      // ルール根拠: 文字数が多く、違う語で始まる。真逆の意味のアドバイス。
    ],
  },
  {
    place: 'オフィスのロビー',
    senderRole: '営業担当者',
    senderVoice: 'female',
    receiverRole: '受付スタッフ',
    receiverVoice: 'male',
    englishSentence:
      'Earlier today, I happened to run into Mr. Johnson from the finance department, and he mentioned there was an issue with the meeting room booking.',
    // コメント: 「run into」を自然な形で使用し、TOEIC頻出のビジネスシーンの口語表現で、11語以上30語以内です。
    japaneseSentence:
      '今日の早い時間に経理部のジョンソンさんに偶然会ったんですが、会議室の予約に問題があると言っていました。',
    // コメント: カタカナ英語を避け、run intoを「偶然会う」と自然な日本語に訳しています。
    englishReply: "Oh, I see. I'll double-check the reservation for you right now.",
    // コメント: 会議室予約について再確認する旨の返答で、内容が推測しやすく簡潔です。
    japaneseReply: 'ああ、わかりました。今すぐ予約を確認しますね。',
    // コメント: 英語の返答に合わせて、会議室の予約確認を伝えています。
    scenePrompt:
      'オフィスのロビーで営業担当者が受付スタッフに、経理部のジョンソンさんと偶然会ったこと、会議室の予約に問題があると聞いたことを伝えている。受付スタッフは予約状況の再確認をしようとしている。',
    // コメント: 会話の文脈・背景・登場人物の動機、場所の様子を詳細に説明しています。
    senderVoiceInstruction: '丁寧でやや急いだトーンで、少し心配そうに',
    receiverVoiceInstruction: '落ち着いて親切に応じるトーンで',
    incorrectOptions: [
      '会議室の予約をキャンセルしたいのですが、手続きを教えていただけますか？',
      // コメント: japaneseSentenceより長い。予約に関する内容で、会話の流れに合うが、意味は異なる。
      '経理部のジョンソンさんが会議室の予約に全く問題がないと言っていましたよ。',
      // コメント: japaneseSentenceより長く、真逆の意味（問題がない）になっています。
      '巨大な会議室の中で突然カンガルーと出会ったので、予約が必要かどうかよくわからなくなりました。',
      // コメント: japaneseSentenceより長い馬鹿馬鹿しい文。カンガルーに出会うという非現実的な内容。
    ],
  },
  {
    place: 'カフェ',
    senderRole: 'イベントオーガナイザー',
    senderVoice: 'male',
    receiverRole: 'カフェ店員',
    receiverVoice: 'female',
    englishSentence:
      'Could you help me set up the tables and chairs at the back of the café for our seminar that starts in thirty minutes?',
    // コメント: 「set up」を自然に用いた依頼文で、カフェのシーンに合った内容。TOEIC頻出表現かつ11語以上。
    japaneseSentence:
      '30分後に始まるセミナーのために、カフェの奥でテーブルと椅子の準備を手伝ってもらえますか？',
    // コメント: set upを「準備」とし自然な日本語に。カタカナ英語を避けています。
    englishReply: "Sure, I'll bring some extra chairs and start arranging them now.",
    // コメント: 椅子を持って準備することを具体的に返答しており、内容のヒントになる。
    japaneseReply: 'はい、予備の椅子を持ってきて、今から並べ始めますね。',
    // コメント: 上記英語の返答と同じく、準備を始める旨を自然に訳しています。
    scenePrompt:
      'カフェでイベントオーガナイザーが店員にセミナー用のテーブルと椅子の準備を手伝ってほしいと頼んでいる。店員は快く引き受け、準備を始めている。',
    // コメント: 会話内容にはない細部（手伝いの経緯や場の状況）まで説明。
    senderVoiceInstruction: 'てきぱきとした丁寧な頼み方で、少し焦った様子で',
    receiverVoiceInstruction: '明るく親切なトーンで快く応じる',
    incorrectOptions: [
      'このカフェで一番大きなピザを30分以内に焼いてもらえますか？セミナーで使うので必要なんです。',
      // コメント: japaneseSentenceより明らかに長いセリフで、ピザの注文という馬鹿馬鹿しい内容。
      '椅子やテーブルの準備は一切必要ありませんので、そのままにしておいてください。',
      // コメント: japaneseSentenceより長い、準備不要という真逆の内容。
      '新しいテーブルと椅子をカフェの奥にすでに並べ終わったので、ほかに必要なことがあれば教えてください。',
      // コメント: japaneseSentenceより長い。準備がすでに完了していると伝える別内容。
    ],
  },
  {
    place: '大学の教室',
    senderRole: '教授',
    senderVoice: 'female',
    receiverRole: '学生',
    receiverVoice: 'male',
    englishSentence:
      'I was surprised that only a few students showed up for the guest lecture, even though we had promoted it for weeks.',
    // コメント: 「show up」を自然な形で使い、大学の講義に合った内容。語数も条件内。
    japaneseSentence:
      '何週間も宣伝していたのに、ゲスト講義に来た学生がほんの数人だけだったのは驚きでした。',
    // コメント: show upを「来た」と自然な日本語にし、カタカナ英語を避けています。
    englishReply: 'Yeah, I noticed the classroom was almost empty during the lecture.',
    // コメント: 教室がほとんど空だったことを具体的に返答し、内容理解のヒントになる。
    japaneseReply: 'そうですね、講義中は教室がほとんど空っぽだと気づきました。',
    // コメント: 教室の様子を具体的に伝え、日本語として自然です。
    scenePrompt:
      '大学の教室で教授が学生に、ゲスト講義のために何週間も宣伝したのに参加者が少なかったことを伝えている。学生も教室がほとんど空だったことに同意している。',
    // コメント: 会話の背景、教授と学生の動機、教室の状況など詳細を記述。
    senderVoiceInstruction: '落ち着いているが少し落胆したトーンで',
    receiverVoiceInstruction: '共感するようにやや驚いたトーンで',
    incorrectOptions: [
      'ゲスト講義に参加した学生が多すぎて、教室に座る場所が全く足りませんでした。',
      // コメント: japaneseSentenceより長く、真逆の内容（参加者が多すぎる）です。
      '昨日、教室に宇宙人がたくさん現れてゲスト講義を始めてしまったので、学生は誰も入れませんでした。',
      // コメント: japaneseSentenceより長い馬鹿馬鹿しい内容になっています。
      '今後は、ゲスト講義の宣伝を一切しないように全員に伝えておきますね。',
      // コメント: japaneseSentenceより長く、宣伝をしないという異なる意味になっています。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'チームリーダー',
    senderVoice: 'female',
    receiverRole: '新入社員',
    receiverVoice: 'male',
    englishSentence:
      'Could you help me sort out these documents before the meeting starts so that everything is in order when the clients arrive?',
    // ルール根拠: 19語で「sort out」を自然に含み、会議前に資料整理を依頼する自然なオフィス会話。
    japaneseSentence: '会議が始まる前にこれらの書類を整理するのを手伝ってくれる？',
    // ルール根拠: 意味を正しく自然な日本語で訳している。カタカナ直訳ではない。
    englishReply: 'Sure, I’ll organize them by date right away.',
    // ルール根拠: 「書類を整理して」との依頼に対して、日付順にまとめると返しているので推測のヒントになる。
    japaneseReply: 'はい、すぐに日付ごとにまとめます。',
    // ルール根拠: 「整理する」内容が日付ごとであることを日本語で示し、依頼を受けている。
    scenePrompt:
      'オフィスの会議室で、チームリーダーが新入社員にクライアントが来る前に資料整理を頼んでいる。テーブルの上にはたくさんの書類が積まれている。',
    // ルール根拠: 会話の場面・背景・登場人物の動機や状況を具体的に記述。
    senderVoiceInstruction: '落ち着いて親切に、丁寧で頼りがいのある口調で',
    receiverVoiceInstruction: '少し緊張しつつも前向きな、素直な話し方で',
    incorrectOptions: [
      'もし時間があれば、これらの書類を全部英語に翻訳してくれると助かるんだけど。',
      // ルール根拠: 文字数が多く、役割に合った内容だが内容が異なる自然な依頼。
      'この書類は絶対に整理しないで、そのままにしておいてもらえますか？',
      // ルール根拠: japaneseSentenceと真逆の意味。「整理しないで」と依頼し、文字数も多い。
      '宇宙人が来た時のためにこれらの書類を全部アルミホイルで包んでおいてくれる？',
      // ルール根拠: 馬鹿馬鹿しい内容。宇宙人やアルミホイルなど非現実的。文字数が多い。
    ],
  },
  {
    place: '大学のキャンパスカフェ',
    senderRole: '学生',
    senderVoice: 'male',
    receiverRole: '友人',
    receiverVoice: 'female',
    englishSentence:
      'Your presentation really stood out among all the others because you explained the complex topic in such a clear and engaging way.',
    // ルール根拠: 22語で「stood out」を活用し、発表の際の賞賛として自然な会話。
    japaneseSentence: '君の発表は他のみんなの中でもとても目立っていたよ。',
    // ルール根拠: 「stood out」の自然な日本語訳で、カタカナ直訳ではない。
    englishReply: 'Oh, thank you! I was really nervous but tried my best.',
    // ルール根拠: 褒められて「ありがとう、不安だったけど頑張った」と自然な返答で内容が推測できる。
    japaneseReply: 'わあ、ありがとう！すごく緊張してたけど、頑張ったんだ。',
    // ルール根拠: 内容を正確に自然な日本語にし、賞賛の会話として成立。
    scenePrompt:
      '大学のカフェで友人同士が発表会後に話している。学生が友人の発表を褒め、友人は少し照れながら返している。',
    // ルール根拠: 場面・登場人物・状況・動機を具体的に説明。
    senderVoiceInstruction: '明るく親しみやすく、率直な褒め言葉で',
    receiverVoiceInstruction: '照れながらも嬉しそうに、素直な感じで',
    incorrectOptions: [
      'もしよかったら、今度の発表で使った資料を全部貸してくれないかな？',
      // ルール根拠: 文字数が多く、内容が異なるが学生らしい依頼。
      '君の発表は他のみんなの中では全然目立たなかったと思うよ。',
      // ルール根拠: japaneseSentenceと真逆の意味。目立たなかったと否定し、文字数も多い。
      'カフェのテーブルの上でダンスを披露してくれたら、きっとみんな驚くと思うよ！',
      // ルール根拠: 馬鹿馬鹿しい内容。カフェのテーブルでダンスという非現実的な依頼。文字数も多い。
    ],
  },
  {
    place: 'ホテルのフロントデスク',
    senderRole: 'フロントスタッフ',
    senderVoice: 'female',
    receiverRole: '宿泊客',
    receiverVoice: 'male',
    englishSentence:
      'If you’d like to take advantage of our complimentary late checkout option, just let us know before noon tomorrow.',
    // ルール根拠: 20語で「take advantage of」を自然に含み、ホテルのサービス案内として自然。
    japaneseSentence:
      '無料のレイトチェックアウトをご利用になりたい場合は、明日の正午までにお知らせください。',
    // ルール根拠: 「take advantage of」の自然な日本語訳で、カタカナ直訳ではない。
    englishReply: 'Thank you for letting me know. I will think about it.',
    // ルール根拠: サービス案内に対し「知らせてくれてありがとう、考えておきます」と自然な返答。
    japaneseReply: '教えてくれてありがとうございます。検討してみます。',
    // ルール根拠: 内容を正確に自然な日本語に訳している。
    scenePrompt:
      'ホテルのフロントで、スタッフが宿泊客に無料のレイトチェックアウトサービスについて案内している。ロビーは落ち着いた雰囲気。',
    // ルール根拠: 場面・登場人物・背景・動機を具体的に説明。
    senderVoiceInstruction: '丁寧で落ち着いた、親切な案内の口調で',
    receiverVoiceInstruction: '少し考えながらも丁寧に、礼儀正しい話し方で',
    incorrectOptions: [
      '朝食ビュッフェをご利用の場合は、毎朝必ず6時に起きていただく必要がございます。',
      // ルール根拠: 文字数が多く、ホテルスタッフの案内として自然だが内容が異なる。
      'レイトチェックアウトは有料サービスですので、明日の朝10時までに追加料金をお支払いください。',
      // ルール根拠: japaneseSentenceと真逆の意味。無料ではなく有料と案内し、文字数も多い。
      '本日限定で、チェックアウト時に逆立ちしながらフロントに来ていただくと景品が当たります！',
      // ルール根拠: 馬鹿馬鹿しい内容。逆立ちでチェックアウトという非現実的な案内。文字数も多い。
    ],
  },
  {
    place: '大学の講堂',
    senderRole: '教授',
    senderVoice: 'male',
    receiverRole: '学生',
    receiverVoice: 'female',
    englishSentence:
      'If you want to take part in the international seminar next month, please submit your application form by this Friday.',
    // 11語以上30語以内で "take part in" を自然に含み、教授が学生に指示する場面に合った文章です。
    japaneseSentence:
      '来月の国際セミナーに参加したい場合は、今週金曜日までに申込書を提出してください。',
    // 英語の内容を自然な日本語で表現し、カタカナ英語ではありません。
    englishReply: 'Alright, I will fill out the application and hand it in this week.',
    // 申込書を提出する意向を示し、内容のヒントになっています。
    japaneseReply: 'わかりました。申込書を記入して今週中に提出します。',
    // 英語の返答を自然な日本語で表現しています。
    scenePrompt:
      '大学の講堂で、教授が来月開催される国際セミナーへの参加について案内している。学生はセミナーに興味があり、申し込み方法について聞いていた。',
    // 会話に書かれていない背景や動機、場所の様子を詳細に説明しています。
    senderVoiceInstruction: '丁寧で落ち着いた口調で、案内するように話す',
    receiverVoiceInstruction: '明るく前向きな声で返事する',
    incorrectOptions: [
      'このセミナーに参加するには英語のプレゼンテーションを準備しなければなりませんので、事前に練習しておいてください。',
      // 文頭が「この」であり、japaneseSentenceと異なり、より長文で内容も異なります。
      '特別な理由がない限り、申し込みをしなくても当日に直接来ていただいても大丈夫です。',
      // 文頭が「特別な理由」で、内容が真逆（申し込み不要）です。japaneseSentenceより長いです。
      '宇宙人のみが参加できる特別なセミナーなので、学生の皆さんは申し込むことができません。',
      // 文頭が「宇宙人」で馬鹿馬鹿しい内容。japaneseSentenceより文字数が多いです。
    ],
  },
  {
    place: 'カンファレンス会場の受付',
    senderRole: 'スタッフ',
    senderVoice: 'female',
    receiverRole: '参加者',
    receiverVoice: 'male',
    englishSentence:
      'The keynote speech will take place in the main hall at 10 a.m., so please make sure to arrive a bit earlier.',
    // 11語以上30語以内で "take place" を自然に含み、案内として自然な表現です。
    japaneseSentence:
      '基調講演は午前10時にメインホールで行われますので、少し早めにお越しください。',
    // 英語の内容を自然な日本語で表現しています。
    englishReply: 'Thank you for letting me know. I will be there before it starts.',
    // 時間前に到着することを伝え、内容を推測するヒントになります。
    japaneseReply: '教えてくれてありがとうございます。始まる前に到着しておきます。',
    // 英語の返答を自然な日本語で表現しています。
    scenePrompt:
      'カンファレンス会場の受付で、スタッフが参加者に基調講演の開催場所と時間について丁寧に案内している。参加者は初めての参加で、少し緊張している様子だ。',
    // 会話文に明記されていない受付や参加者の背景・雰囲気を説明しています。
    senderVoiceInstruction: '親切で明るいトーンで、わかりやすく丁寧に案内する',
    receiverVoiceInstruction: '少し緊張しつつも礼儀正しく返事する',
    incorrectOptions: [
      'メインホールではなく、屋上で基調講演が行われる予定ですので、エレベーターで最上階までお越しください。',
      // 文頭が「メインホール」であり、内容が異なり長い文です。
      '午後3時に基調講演が始まりますので、午前中は自由にお過ごしください。',
      // 文頭が「午後3時」で、japaneseSentenceと真逆（時間が異なる）内容です。
      'ペンギンの着ぐるみを着ていないとメインホールに入れませんので、必ずご用意ください。',
      // 文頭が「ペンギン」で馬鹿馬鹿しい内容。japaneseSentenceより長文です。
    ],
  },
  {
    place: '企業の会議室',
    senderRole: '部長',
    senderVoice: 'male',
    receiverRole: '社員',
    receiverVoice: 'female',
    englishSentence:
      "Unfortunately, we had to turn down the supplier's latest offer because it didn’t meet our requirements.",
    // 11語以上30語以内で "turn down" を自然に含み、ビジネスの断り表現として自然です。
    japaneseSentence:
      '残念ながら、その仕入先の最新の提案は当社の要件を満たさなかったため、お断りしました。',
    // 英語の内容を自然な日本語で表現しています。カタカナは使用していません。
    englishReply: 'I see. Thank you for explaining the reason for your decision.',
    // 理由を聞いて納得する内容で、英語の内容を推測できるヒントです。
    japaneseReply: 'なるほど。ご決定の理由を説明してくださりありがとうございます。',
    // 英語の返答を自然な日本語で表現しています。
    scenePrompt:
      '企業の会議室で、部長が社員に仕入先からの提案を断った理由を説明している。社員はその経緯を知りたがっていた。',
    // 会話文にない背景や動機、場面を詳しく描写しています。
    senderVoiceInstruction: '落ち着いた口調で、事実を淡々と伝える',
    receiverVoiceInstruction: '丁寧で納得した様子で返事する',
    incorrectOptions: [
      '先方の提案を受け入れることで、私たちの会社には多大な利益がもたらされると考えていますので、すぐに契約を進めます。',
      // 文頭が「先方」で、内容もjapaneseSentenceと異なり長文です。
      '今回の提案はすぐに承認され、既に新しい取引が始まっていますので、今後の流れにご注意ください。',
      // 文頭が「今回」で、内容が真逆（提案を承認）です。長文です。
      'お断りの返事を送る代わりに、部長自ら宇宙に飛び立って交渉することに決めました。',
      // 文頭が「お断り」で馬鹿馬鹿しい内容。japaneseSentenceより長いです。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '上司',
    senderVoice: 'male',
    receiverRole: '部下',
    receiverVoice: 'female',
    englishSentence:
      'If you could turn in your expense report by the end of today, it would really help us meet our accounting deadline.',
    // コメント: "turn in" を自然に含み、11語以上30語以内の文。会議室での上司としての依頼文。
    japaneseSentence: '今日中に経費報告書を提出してもらえると、経理の締切に間に合って助かります。',
    // コメント: 英文の自然な日本語訳。カタカナ英語は使っていません。
    englishReply: 'Sure, I will finish it and submit it before I leave today.',
    // コメント: 提出を約束する内容であり、ユーザーが英語の内容を推測できるヒント。
    japaneseReply: 'はい、今日退社前に仕上げて提出します。',
    // コメント: 英語の返答の自然な訳で、提出を約束している内容。
    scenePrompt:
      'オフィスの会議室で、上司が部下に経費報告書の提出を依頼している。会社の経理部門の締切が迫っているため、早めの対応を求めている場面。',
    // コメント: 会話の文脈や背景を具体的に説明している。
    senderVoiceInstruction: '穏やかで丁寧な話し方、ややフォーマルに',
    receiverVoiceInstruction: '明るくはきはきとした返答で、前向きなトーン',
    incorrectOptions: [
      '今週中にあなたの新しい名刺デザイン案を全ての社員に配布してください。',
      // コメント: "japaneseSentence"より文字数が多く、内容が異なる部下への指示。文頭も異なる。
      '先週提出した経費報告書は書式が完全に間違っていましたので、もう一度やり直してください。',
      // コメント: "japaneseSentence"の逆の意味（やり直しを求める）。文字数も多い。文頭も異なる。
      '当社の社長の似顔絵を描いて会議室の壁に飾ってもらえますか？',
      // コメント: 馬鹿馬鹿しい依頼で、文字数も多く、文頭も異なる。
    ],
  },
  {
    place: '大学の図書館',
    senderRole: '友人A',
    senderVoice: 'female',
    receiverRole: '友人B',
    receiverVoice: 'male',
    englishSentence:
      'I didn’t realize we had used up all the printer paper, so now I have to find some before I can print my assignment.',
    // コメント: "use up" を自然に含み、11語以上30語以内の文。学生同士の自然な会話。
    japaneseSentence:
      'プリンター用紙を全部使い切っていたなんて気づかなかったから、レポートを印刷する前に探さなきゃ。',
    // コメント: 英文の自然な日本語訳。「使い切る」を自然に訳している。
    englishReply: 'Oh, I have some extra paper in my backpack. Do you want to use it?',
    // コメント: 追加の用紙を提案しており、ユーザーが内容を推測できるヒント。
    japaneseReply: 'あ、僕のリュックに予備の用紙があるよ。使う？',
    // コメント: 英語の返答の自然な訳で、追加の用紙を提案している。
    scenePrompt:
      '大学の図書館で、友人Aがプリンターの用紙がなくなったことに気づき、課題の印刷ができずに困っている。友人Bが助けを申し出る場面。',
    // コメント: 会話の文脈や背景を具体的に説明している。
    senderVoiceInstruction: '少し困ったようなトーンで、親しみやすく話す',
    receiverVoiceInstruction: '優しく親切なトーンで、親しみやすく',
    incorrectOptions: [
      '今から一緒に図書館の全ての本を一冊ずつ読んでいこうと思うんだけど、付き合ってくれる？',
      // コメント: 馬鹿馬鹿しい提案で、文字数が多く、文頭も異なる。
      'プリンター用紙は全く減っていないから、好きなだけ使って大丈夫だよ。',
      // コメント: 真逆の意味（用紙が減っていない）。文字数も多い。文頭も異なる。
      '明日の朝までに友達全員の分のレポートを代わりに印刷しておいてほしいな。',
      // コメント: 文字数が多く、内容も異なる。文頭も異なる。
    ],
  },
  {
    place: 'フィットネスジム',
    senderRole: 'トレーナー',
    senderVoice: 'male',
    receiverRole: '会員',
    receiverVoice: 'female',
    englishSentence:
      'If you stick to this routine and eat a balanced diet, I’m confident things will work out well for your fitness goals.',
    // コメント: "work out" を自然に含み、11語以上30語以内の文。トレーナーの励ましとして自然。
    japaneseSentence:
      'このトレーニングを続けてバランスのいい食事を心がければ、きっと良い結果が出ますよ。',
    // コメント: 英文の自然な日本語訳。「work out」を「良い結果が出る」と自然に訳している。
    englishReply: 'Thank you! I’ll do my best to follow your advice and stay motivated.',
    // コメント: トレーナーの励ましに素直に感謝し、やる気を伝えており内容を推測できるヒント。
    japaneseReply: 'ありがとうございます！アドバイス通りに頑張って続けます。',
    // コメント: 英語の返答の自然な訳で、努力を約束している内容。
    scenePrompt:
      'フィットネスジムで、トレーナーが会員にトレーニングの継続と食事のアドバイスをし、運動目標の達成を励ましている場面。',
    // コメント: 会話の文脈や背景を具体的に説明している。
    senderVoiceInstruction: '明るく前向きで、応援するようなトーンで',
    receiverVoiceInstruction: '元気で感謝を込めたトーンで',
    incorrectOptions: [
      'もし毎日ジムに来て野菜だけ食べ続ければ、筋肉がみるみる消えていくと思いますよ。',
      // コメント: 真逆の意味（悪い結果になる）。文字数も多い。文頭も異なる。
      '今日からジムのマシンで逆立ちしながらトレーニングする新しいルールを導入しますので、よろしくお願いします！',
      // コメント: 馬鹿馬鹿しい内容で、文字数が多い。文頭も異なる。
      '運動も食事も特に変えなくていいので、今まで通りリラックスして過ごしてください。',
      // コメント: 内容が異なり、文字数も多い。文頭も異なる。
    ],
  },
  {
    place: '会議室',
    senderRole: '部長',
    senderVoice: 'male',
    receiverRole: '新入社員',
    receiverVoice: 'female',
    englishSentence:
      'Before you leave today, please write down any important points from the meeting so we can review them later if needed.',
    // ルール根拠: 13語で「write down」を自然に使用。役割・場面に合ったフォーマルで丁寧な指示文。
    japaneseSentence:
      '今日帰る前に、会議で大事だった点をメモしておいてください。後で見返せるようにしておきたいので。',
    // ルール根拠: カタカナ直訳を避けた自然な訳。文字数も充分。
    englishReply: 'Sure, I’ll write down the main points right after the meeting ends.',
    // ルール根拠: 「write down」を含み、依頼された内容を繰り返しているため推測可能。
    japaneseReply: 'わかりました、会議が終わったらすぐに要点を書き留めます。',
    // ルール根拠: 丁寧な返事で、内容が推測しやすい。
    scenePrompt:
      '新入社員が部長に会議の内容をまとめておくよう頼まれる場面。広い会議室で複数名が会議を終えた直後、部長は重要事項の記録を忘れずにと新入社員に伝えている。',
    // ルール根拠: 登場人物・背景・場所の様子や動機を具体的に説明。
    senderVoiceInstruction: '落ち着いていて頼もしいが、丁寧な話し方',
    receiverVoiceInstruction: '初々しく、明るく元気な口調',
    incorrectOptions: [
      'この会議が終わったら、明日の天気について全員で議論しましょう。',
      // ルール根拠: 長文。内容がズレているが会議室の会話として自然。
      'みなさん、今日は何もメモを取らずにそのまま帰っても大丈夫です。',
      // ルール根拠: 真逆の意味。長文。
      '宇宙人が会議に乱入してきたらどう対応すればいいか、全員で考えてください。',
      // ルール根拠: 馬鹿馬鹿しい内容かつ長文。
    ],
  },
  {
    place: '道路の横断歩道',
    senderRole: '交通指導員',
    senderVoice: 'female',
    receiverRole: '小学生',
    receiverVoice: 'male',
    englishSentence:
      'Remember, even if you are in a hurry, always yield to vehicles when you cross the street at this intersection.',
    // ルール根拠: 20語。「yield to」を自然に使い、指導員の立場・状況に合った注意喚起。
    japaneseSentence:
      'たとえ急いでいる時でも、この交差点を渡るときは必ず車に道を譲るようにしましょう。',
    // ルール根拠: 直訳ではなく、自然な日本語。十分な長さ。
    englishReply: 'Okay, I’ll make sure to wait for the cars to pass before crossing.',
    // ルール根拠: 指示を理解し、内容を繰り返しているので推測しやすい。
    japaneseReply: 'はい、車が通り過ぎるまでちゃんと待つようにします。',
    // ルール根拠: 推測しやすく、自然な相槌。
    scenePrompt:
      '交通指導員が朝の横断歩道で小学生に安全な渡り方を教えている。車が行き交う中、指導員は急いでいる子どもにも安全を最優先するよう優しく声をかけている。',
    // ルール根拠: 登場人物・背景・場所の様子や動機を具体的に記述。
    senderVoiceInstruction: '優しく、子どもに安心感を与える話し方',
    receiverVoiceInstruction: '元気で素直な口調',
    incorrectOptions: [
      '信号が青になったら、走って一気に道路を渡ってもいいですよ。',
      // ルール根拠: 長文かつ状況に合った誤った指示。
      '道路を渡るときは、車が来ていても気にせず進んでください。',
      // ルール根拠: 真逆の意味で長文。
      'もし横断歩道の真ん中でダンスしたくなったら、車が来ても踊って大丈夫です。',
      // ルール根拠: 馬鹿馬鹿しい発想かつ長文。
    ],
  },
  {
    place: 'オフィスの自席',
    senderRole: '経理担当者',
    senderVoice: 'male',
    receiverRole: '営業担当者',
    receiverVoice: 'female',
    englishSentence:
      'Could you please account for the difference between the total sales reported last month and the amount shown in our records?',
    // ルール根拠: 21語。「account for」を自然な形で使用。経理担当者が営業担当者に説明を求めるフォーマルな依頼文。
    japaneseSentence:
      '先月報告された売上合計と、こちらの記録にある金額の差について説明していただけますか？',
    // ルール根拠: account for の自然な訳。フォーマルで必要な情報を含む長文。
    englishReply: 'Yes, I’ll double-check the numbers and let you know why there is a difference.',
    // ルール根拠: 要点を繰り返し、内容推測のヒントになっている。
    japaneseReply: 'はい、数字をもう一度確認して、その差の理由をお伝えします。',
    // ルール根拠: 推測しやすい自然な返事。
    scenePrompt:
      '経理担当者が営業担当者に、売上報告と記録の金額が一致しない理由を尋ねている。オフィスの自席でパソコンを操作しながら、具体的な差異の説明を丁寧に求めている場面。',
    // ルール根拠: 人物・背景・動機を具体的に記述。
    senderVoiceInstruction: '真面目で丁寧なトーン、少し心配そうな話し方',
    receiverVoiceInstruction: '落ち着いていて誠実な話し方',
    incorrectOptions: [
      'もし金額が合わなくても、気にせずにそのまま進めてください。',
      // ルール根拠: 長文かつ状況に合った誤った指示。
      'こちらの記録と報告された売上合計が完全に一致していることを確認しました。',
      // ルール根拠: 真逆の意味で長文。
      '売上の差額が魔法で消えた場合、どのように報告すればいいでしょうか？',
      // ルール根拠: 馬鹿馬鹿しい発想で長文。
    ],
  },
  {
    place: '会社の会議室',
    senderRole: 'マネージャー',
    senderVoice: 'male',
    receiverRole: 'プロジェクトメンバー',
    receiverVoice: 'female',
    englishSentence:
      'In order to avoid any confusion, please make sure to adhere to the updated project guidelines throughout this quarter.',
    // ルール根拠: adhere toを自然に使用し、会議室でのマネージャーの指示として自然な文章。11語以上30語以内。
    japaneseSentence:
      '混乱を避けるために、今期は必ず新しいプロジェクトのガイドラインを守ってください。',
    // ルール根拠: adhere toを「守る」と自然な日本語で翻訳。カタカナ英語は使用していません。
    englishReply: 'Okay, I will review the updated guidelines and follow them closely.',
    // ルール根拠: 指示に対して、内容を理解し実行する意思を表明し、ヒントとなる自然な返答。
    japaneseReply: 'わかりました。新しいガイドラインを確認して、しっかり守ります。',
    // ルール根拠: 指示への理解と実践を表明する返答。内容からoriginal sentenceを推測しやすい。
    scenePrompt:
      '社内の会議室で、マネージャーが新しくなったプロジェクトのガイドラインについて説明し、混乱を避けるためにそのガイドラインを守るようにメンバーへ強調している。プロジェクトの進行に関わる大切な場面。',
    // ルール根拠: 場面・動機・場所の様子・会話の背景を具体的に説明。
    senderVoiceInstruction: '落ち着いていて丁寧な、しっかりとした声で',
    receiverVoiceInstruction: '明るく前向きで協力的なトーンで',
    incorrectOptions: [
      '新しいガイドラインができましたが、好きな部分だけ従ってもらえれば大丈夫ですので、特に気にしないでください。',
      'ガイドラインには従わず、自分たちのやり方を自由に進めてください。',
      '当社のガイドラインに従えば、会議中に空を飛ぶことが許可されますのでご注意ください。',
      // ルール根拠:
      // 1文目: 必ず守る→好きな部分だけ、で真逆の意味。文頭・内容が異なる。japaneseSentenceより文字数が多い。
      // 2文目: 「守る」→「従わず」で真逆。文頭が異なり、文字数が多い。
      // 3文目: 馬鹿馬鹿しい発想。ガイドラインで空を飛ぶ許可、現実離れ。文頭・内容が異なる。文字数も多い。
    ],
  },
  {
    place: '空港の搭乗ゲート前',
    senderRole: '空港スタッフ',
    senderVoice: 'female',
    receiverRole: '旅行者',
    receiverVoice: 'male',
    englishSentence:
      'Despite the brief delay, we ask all passengers to remain near the gate and carry on with their preparations for boarding.',
    // ルール根拠: carry onを自然に使い、空港スタッフの指示にふさわしい。11語以上30語以内。
    japaneseSentence: '少し遅れていますが、搭乗の準備を続けながらゲート付近でお待ちください。',
    // ルール根拠: carry onを「続ける」と自然な日本語に訳している。
    englishReply: 'Sure, I’ll stay here and keep getting ready for boarding.',
    // ルール根拠: 指示内容を理解し、待機しながら準備を続けると伝えている。内容の推測がしやすい。
    japaneseReply: 'はい、ここで待ちながら搭乗の準備を続けます。',
    // ルール根拠: 指示に素直に従い、行動内容を明示している。
    scenePrompt:
      '空港の搭乗ゲート前で、スタッフがフライトの一時的な遅延をアナウンスし、乗客に近くで準備を続けて待つよう説明している。旅行者たちは荷物の整理や搭乗券の確認などをしている。',
    // ルール根拠: 場所・状況・会話の背景・登場人物の動機を具体的に記述。
    senderVoiceInstruction: '丁寧で安心感のある落ち着いたトーンで',
    receiverVoiceInstruction: '素直で協力的なトーンで',
    incorrectOptions: [
      'フライトはキャンセルとなりましたので、すぐに空港を出てご自宅にお帰りください。',
      '搭乗の準備はせず、今はゲートから離れて好きな場所で自由に過ごしてください。',
      'ゲート付近でダンスパーティーを始めていただけると幸いです。スタッフも参加します！',
      // ルール根拠:
      // 1文目: 逆の内容（続けて待つ→帰宅）。文頭が異なる。文字数が多い。
      // 2文目: 準備を続ける→準備せず・離れるで真逆。文頭が異なり、文字数が多い。
      // 3文目: 馬鹿馬鹿しい（ダンスパーティー開催）。文頭が異なり文字数も多い。
    ],
  },
  {
    place: '会社の社員食堂',
    senderRole: '同僚',
    senderVoice: 'male',
    receiverRole: '別の同僚',
    receiverVoice: 'female',
    englishSentence:
      "I've decided to cut back on sugary snacks during work hours because I want to feel more energetic throughout the day.",
    // ルール根拠: cut back onを自然に使い、社員食堂での会話として自然。11語以上30語以内。
    japaneseSentence: '一日中元気でいたいから、勤務中の甘いお菓子を控えることにしたんだ。',
    // ルール根拠: cut back onを「控える」に自然な日本語訳。カタカナ英語なし。
    englishReply: 'Oh, I see. If you need healthy snack ideas, just let me know.',
    // ルール根拠: 内容を理解し、健康的な提案も含めた返答。推測のヒントとなる。
    japaneseReply: 'へえ、なるほど。もし健康的なおやつのアイデアが欲しかったら言ってね。',
    // ルール根拠: 内容を理解し、同僚らしい提案をしている。
    scenePrompt:
      '会社の社員食堂で、同僚同士が食事をしながら健康について話している。片方が最近、仕事中の甘いお菓子を控えることにした理由を話している。',
    // ルール根拠: 場所・登場人物・背景・動機を具体的に記述。
    senderVoiceInstruction: 'カジュアルで親しみやすいトーンで',
    receiverVoiceInstruction: '優しくて気遣いのあるトーンで',
    incorrectOptions: [
      '毎日仕事中に甘いお菓子をどんどん食べることに決めたんだ。エネルギーがなくても気にしないよ！',
      '甘いお菓子を控えるのはやめて、もっとたくさん食べるようにしようと思っているんだ。',
      '仕事中はお菓子の代わりに机の下でこっそりバナナを育てることにしたよ。',
      // ルール根拠:
      // 1文目: 控える→どんどん食べる、で真逆。文頭が異なる。文字数が多い。
      // 2文目: 控えるのをやめてたくさん食べる、で真逆。文頭が異なり、文字数も多い。
      // 3文目: 馬鹿馬鹿しい（机の下でバナナを育てる）。文頭が異なり文字数も多い。
    ],
  },
];

export default problemData;
