import { SeedProblemData } from '../src/types/problem';

/**
 * 問題データ 3
 * Generated by GPT API (3 problems)
 */
const problemData: SeedProblemData[] = [
  {
    place: 'オフィスの会議室',
    senderRole: '人事担当者',
    senderVoice: 'female',
    receiverRole: '部門マネージャー',
    receiverVoice: 'male',
    englishSentence:
      'There were growing concerns about whether the applicant could manage cross-functional coordination.',
    // 【ルール遵守根拠】10語以内。業務的な雰囲気で、会議室・人事担当者として自然。TOEIC的な語彙を含み、カジュアル・フォーマルの中間的な口調。
    japaneseSentence: '応募者が部門横断的な調整をうまくできるかどうか、懸念が高まっていました。',
    // 【ルール遵守根拠】内容を省略せず、正確かつ自然に訳している。カタカナ語を避けて自然な日本語訳。
    englishReply: 'Oh, really? I thought their background was strong enough for that.',
    // 【ルール遵守根拠】内容を受けて驚き+評価を返し、推測のヒントになる。単純な単語・構文で、慣用句なし。
    japaneseReply: '本当ですか？私はその方の経歴なら十分だと思っていました。',
    // 【ルール遵守根拠】englishReplyの内容を漏らさず自然に訳している。
    scenePrompt:
      'ガラス張りの近代的なオフィス会議室で、人事担当者が最近の採用面接について部門マネージャーと真剣に話し合っている場面。書類やノートパソコンが机の上に並び、両者は採用候補者の適性について意見交換している。',
    // 【ルール遵守根拠】場所・登場人物・状況・背景・動機を具体的に記述。englishSentenceに書かれていない文脈が含まれている。
    senderVoiceInstruction: 'ややフォーマルで落ち着いた、慎重なトーンで',
    receiverVoiceInstruction: '少し驚いた様子で率直に',
    incorrectOptions: [
      '弊社の新しい評価制度についてご説明させていただきますので、資料をご覧ください。',
      // 【ルール遵守根拠】japaneseSentenceより長く、別の話題。人事担当者らしい。最初の語も異なる。
      '応募者が部門横断的な調整を非常に得意としているという評価が多く寄せられていました。',
      // 【ルール遵守根拠】japaneseSentenceより長く、真逆の意味。最初の語も異なる。
      '全ての応募者にダンスと歌の実技試験を受けてもらっていますので、結果が出たらご連絡します。',
      // 【ルール遵守根拠】japaneseSentenceより長く、馬鹿馬鹿しい内容。最初の語も異なる。
    ],
  },
  {
    place: '会社のエントランスホール',
    senderRole: '人事部長',
    senderVoice: 'female',
    receiverRole: '新任マネージャー',
    receiverVoice: 'male',
    englishSentence:
      'HR acknowledged concerns about employee retention after the organizational restructuring.',
    // コメント: 10語で収まっており、職場の会話として自然な内容。TOEICでも頻出の表現「acknowledged concerns」「employee retention」「organizational restructuring」を盛り込んでいます。
    japaneseSentence: '人事部は組織再編後の従業員定着に関する懸念を認めました。',
    // コメント: 英文の内容を一切省略せず、自然なビジネス日本語に直訳しています。カタカナ英語も不使用。
    englishReply: 'Oh, I see. That’s been on everyone’s mind lately.',
    // コメント: 送信者の発言を受けて、懸念が現場でも共有されていることを示し、内容のヒントになっています。英単語も簡潔。
    japaneseReply: 'ああ、そうだったんですね。最近はみんな気にしていますしね。',
    // コメント: 英文の内容をもれなく含み、自然な返答になっています。
    scenePrompt:
      '会社のエントランスホールで、人事部長が新任マネージャーに組織再編後の社員定着について話している。明るいオフィスビルのロビー、スーツ姿のビジネスパーソンたちが行き交う中、二人は立ち話をしている。人事部長は、従業員の不安や懸念を丁寧に伝え、組織の安定を図ろうとしている。',
    // コメント: 会話の背景、場所、人間関係、動機、雰囲気を具体的に説明し、英文にはない文脈を付加しています。
    senderVoiceInstruction: '落ち着いていて信頼感のある丁寧な話し方',
    receiverVoiceInstruction: 'やや緊張しつつも誠実なトーン',
    incorrectOptions: [
      '今後は従業員の離職率が大幅に下がると予想されていますので、ご安心ください。',
      // コメント: 「japaneseSentence」より明らかに長く、内容も真逆（懸念を否定）。「今後は」で始まり同じ語頭ではない。
      '組織再編の影響で従業員数が半分以下になる可能性がありますが、特別な対応は考えていません。',
      // コメント: 1文目と違う語で始まり、内容は人事部長の立場としてありえるが、やや極端な内容で長い。
      '当社で一番人気のない部署に全社員を異動させる計画がありますので、お楽しみにしてください！',
      // コメント: 1文目・2文目と違う語で始まり、馬鹿馬鹿しい内容。文字数も十分に長い。
    ],
  },
  {
    place: '会社の会議室',
    senderRole: '人事部長',
    senderVoice: 'female',
    receiverRole: '課長',
    receiverVoice: 'male',
    englishSentence:
      'The committee discussed concerns about transparency in the promotion process.',
    // 10語ちょうどで、ルールに従い語彙を自然に使用し、場面と役割に即した内容。
    japaneseSentence: '委員会は昇進プロセスの透明性についての懸念を話し合いました。',
    // 内容の省略をせず、自然で正確に訳している。
    englishReply: 'Oh, I see. Was there any suggestion for improvement?',
    // 相槌から始まり、内容を推測できる質問で、熟語・難語なし。状況に合った返答。
    japaneseReply: 'ああ、そうなんですね。改善のための提案は何かありましたか？',
    // 英文の内容をもれなく含み、自然な日本語になっている。
    scenePrompt:
      '大きな会社の明るい会議室で、人事部長が課長に昇進プロセスの透明性について委員会で話し合われた内容を伝えている。背景にはホワイトボードがあり、会議資料がテーブルに広がっている。人事部長は誠実な雰囲気で、課長は少し心配そうに話を聞いている。',
    // 場所の様子や登場人物の動機、背景を具体的に描写している。
    senderVoiceInstruction: '落ち着いていて誠実な、丁寧な話し方',
    receiverVoiceInstruction: 'やや心配そうで、丁寧に聞き返す話し方',
    incorrectOptions: [
      '今回の昇進プロセスは完全に公正で問題ありませんでしたので、ご安心ください。',
      // japaneseSentenceより確実に長く、語頭も異なり、senderRoleの言いそうな内容。真逆の意味。
      '新しい昇進手続きに関する詳細なガイドラインを全社員に配布する予定ですので、ご確認ください。',
      // japaneseSentenceより長く、語頭も異なり、senderRoleが言いそうな内容。
      'この会社で一番人気のない、謎の昇進ゲームに参加してみませんか？勝者には秘密の賞品があります。',
      // japaneseSentenceより長く、語頭も異なり、馬鹿馬鹿しい内容。
    ],
    // 3文ともjapaneseSentenceから始まりが異なり、すべてjapaneseSentenceより長くなっている。馬鹿馬鹿しい文と真逆の文もルール通り。
  },
];

export default problemData;
