import { SeedProblemData } from '../src/types/problem';

/**
 * 問題データ 1
 * Generated by create-problems.ts (1 problems)
 */
const problemData: SeedProblemData[] = [
  {
    place: '学校の廊下',
    senderRole: '友人',
    senderVoice: 'female',
    receiverRole: '友人',
    receiverVoice: 'male',
    englishSentence: 'We are the winners this time!',
    japaneseSentence: '今回は私たちが勝者だよ！',
    englishReply: 'Wow, you won the relay race?',
    japaneseReply: 'えっ、リレーで勝ったの？',
    scenePrompt:
      '対面での会話。平日の昼休み、明るい学校の廊下で、1コマ目では女子生徒が友人の男子生徒にクラス対抗リレーで勝ったことを嬉しそうに伝えている。背景にはロッカーや掲示板があり、周囲には他の生徒もちらほら歩いている。2コマ目では男子生徒が驚いた表情で女子生徒の話を聞き返している。まだ表彰状やトロフィーは登場せず、廊下には特別な装飾もない。',
    senderVoiceInstruction: null,
    receiverVoiceInstruction: null,
    incorrectOptions: [
      '夕焼け空がとても綺麗だったね。',
      '今回は彼らが先に帰ったよ！',
      '宇宙人が寿司握った。',
    ],
    difficultyLevel: null,
  },
];

export default problemData;
