import { SeedProblemData } from '../src/types/problem';

/**
 * 問題データ 23
 * Generated by GPT API (6 problems)
 */
const problemData: SeedProblemData[] = [
  {
    place: '動物園の園内',
    senderRole: '飼育員',
    senderVoice: 'female',
    receiverRole: '来園者',
    receiverVoice: 'male',
    englishSentence: 'Please refrain from feeding animals.',
    japaneseSentence: '動物へのエサやりはご遠慮ください。',
    englishReply: "Oh, sorry. I won't do it.",
    japaneseReply: 'すみません。もうしません。',
    scenePrompt:
      '動物園の園路で、親子連れの来園者が動物にエサをあげようとしているのを見て、女性飼育員が穏やかに注意している場面。',
    senderVoiceInstruction: '優しく落ち着いた口調で、注意を促す話し方。',
    receiverVoiceInstruction: '少し驚いたが素直に謝る、カジュアルなトーンで。',
    incorrectOptions: [
      '動物に触れていただいても大丈夫です。',
      '展示エリアには立ち入らないでください。',
      '今からカバと一緒にダンスを踊りましょう。',
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '上司',
    senderVoice: 'male',
    receiverRole: '部下',
    receiverVoice: 'female',
    englishSentence: "Let's move forward with negotiations.",
    japaneseSentence: 'この交渉を進めていきましょう。',
    englishReply: "Understood. I'll contact them today.",
    japaneseReply: '承知しました。本日先方に連絡します。',
    scenePrompt:
      '会議室で、新規取引先との交渉案件について、上司が部下に今後の方針を伝えている。部下はメモを取りながら指示を受けている。',
    senderVoiceInstruction: '前向きで力強い、リーダーらしいトーンで。',
    receiverVoiceInstruction: 'やや緊張しつつも前向きな返答、ビジネスライクな話し方。',
    incorrectOptions: [
      'この交渉はすぐに中止しましょう。',
      '会議室の照明をもう少し暗くしてください。',
      '机の上でみんなで折り紙を作りましょう。',
    ],
  },
  {
    place: '劇場のロビー',
    senderRole: 'スタッフ',
    senderVoice: 'female',
    receiverRole: '観客',
    receiverVoice: 'male',
    englishSentence: 'Complimentary programs are available.',
    japaneseSentence: '無料のプログラムをご用意しております。',
    englishReply: "Thank you. I'll take one.",
    japaneseReply: 'ありがとうございます。いただきます。',
    scenePrompt:
      '劇場ロビーで、観客がプログラムの有無を尋ねたところ、女性スタッフが笑顔で案内している。',
    senderVoiceInstruction: '明るく親しみやすく、丁寧な案内のトーンで。',
    receiverVoiceInstruction: 'うれしそうに、柔らかい声で。',
    incorrectOptions: [
      '無料のプログラムは終了しました。',
      'ロビーで飲食はご遠慮ください。',
      '本日の演目は宇宙人が主演です。',
    ],
  },
  {
    place: '図書館の貸出カウンター',
    senderRole: '司書',
    senderVoice: 'male',
    receiverRole: '利用者',
    receiverVoice: 'female',
    englishSentence: 'Please hand over overdue books.',
    japaneseSentence: '延滞中の本をご返却ください。',
    englishReply: 'Yes, I have them here.',
    japaneseReply: 'はい、こちらに持ってきました。',
    scenePrompt:
      '図書館カウンターで、利用者が延滞していた本を返しに来た際、男性司書が返却を丁寧にお願いしている。',
    senderVoiceInstruction: '丁寧で落ち着いた声、穏やかに案内する口調。',
    receiverVoiceInstruction: '安心して返却する感じで、礼儀正しい声。',
    incorrectOptions: [
      '延滞中の本はご自由にお持ち帰りください。',
      '貸出カウンターで大声で歌ってください。',
      '本の返却は必要ございません。',
    ],
  },
  {
    place: 'カフェのレジ前',
    senderRole: '店員',
    senderVoice: 'female',
    receiverRole: '客',
    receiverVoice: 'male',
    englishSentence: 'We’ve run out of cheesecake.',
    japaneseSentence: 'チーズケーキは売り切れてしまいました。',
    englishReply: 'Oh, then I’ll choose pie.',
    japaneseReply: 'そうですか、ではパイにします。',
    scenePrompt:
      '夕方のカフェで、男性客がチーズケーキを注文しようとしたところ、女性店員が売り切れを伝える。',
    senderVoiceInstruction: '申し訳なさを含めつつも明るく親切な声で。',
    receiverVoiceInstruction: '少し残念そうだが切り替えて前向きな声。',
    incorrectOptions: [
      'チーズケーキは本日無料で配布中です。',
      'アップルパイはご注文いただけません。',
      'レジでケーキと腕相撲をしてください。',
    ],
  },
  {
    place: '企業の受付ロビー',
    senderRole: '受付係',
    senderVoice: 'male',
    receiverRole: '来訪者',
    receiverVoice: 'female',
    englishSentence: 'Please be advised that photos are prohibited.',
    japaneseSentence: '写真撮影は禁止となっておりますのでご注意ください。',
    englishReply: 'I see. I won’t take any.',
    japaneseReply: 'わかりました。撮影はしません。',
    scenePrompt:
      '企業ビルの受付ロビーで、女性来訪者がスマートフォンを手にしているところに、受付係が写真撮影禁止を丁寧に伝えている。',
    senderVoiceInstruction: 'フォーマルで冷静、案内を丁寧に伝える口調。',
    receiverVoiceInstruction: 'すぐに理解して素直に受け止める、落ち着いた声。',
    incorrectOptions: [
      '写真撮影はご自由にどうぞ。',
      '禁止事項は特にございません。',
      'ロビーで自撮りダンス大会を開催中です。',
    ],
  },
];

export default problemData;
