import { SeedProblemData } from '../src/types/problem';

/**
 * 問題データ 3
 * Generated by GPT API (33 problems)
 */
const problemData: SeedProblemData[] = [
{
  place: "オフィスの会議室",
  senderRole: "上司",
  senderVoice: "male",
  receiverRole: "部下",
  receiverVoice: "female",
  englishSentence: "Although it's late, let's finish this today.",
  // ルール根拠: 10語以内。althoughを自然に含み、会議室の上司らしい、提案のセリフ。
  japaneseSentence: "遅いけれど、今日中に終わらせましょう。",
  // ルール根拠: 日本語として自然かつ正確な訳。カタカナ英語を避ける。
  englishReply: "Okay, I'll do my best to complete it.",
  // ルール根拠: senderの発言を受けて、やる気を示しつつ内容を具体的に返答している。
  japaneseReply: "はい、頑張って終わらせます。",
  // ルール根拠: 上司の提案を受けて、やる気を見せる自然な返答。
  scenePrompt: "夜遅くのオフィス会議室で、上司が部下に残業をお願いし、今日中に仕事を終わらせたいと考えている場面。部下は疲れているが、やる気を見せている。",
  // ルール根拠: 場所、状況、登場人物の動機などを具体的に説明。
  senderVoiceInstruction: "落ち着いていて少し申し訳なさそうに、でも決意を持って話す。",
  receiverVoiceInstruction: "前向きでやる気のある明るい声。",
  incorrectOptions: [
    "他の会議室に移動しましょうか。",
    // ルール根拠: 違う単語で始まる。内容は提案だが本問の内容とは異なる。
    "今日はもう帰りましょう。",
    // ルール根拠: 違う単語で始まる。本問の内容と真逆の意味。
    "巨大なパンダが会議室に入ってきたらどうしますか？",
    // ルール根拠: 違う単語で始まる。馬鹿馬鹿しい発想。
  ]
},
{
  place: "カフェ",
  senderRole: "店員",
  senderVoice: "female",
  receiverRole: "客",
  receiverVoice: "male",
  englishSentence: "We’re out of scones, though we have muffins.",
  // ルール根拠: 10語以内。thoughを自然に含み、カフェの店員らしい説明のセリフ。
  japaneseSentence: "スコーンは売り切れですが、マフィンはございます。",
  // ルール根拠: 日本語として自然かつ正確な訳。カタカナ英語も使わず。
  englishReply: "Oh, then I’ll have a muffin, please.",
  // ルール根拠: 店員の説明に反応し、具体的な注文をしている。
  japaneseReply: "じゃあ、マフィンをお願いします。",
  // ルール根拠: 内容を具体的に受けて、自然な返答。
  scenePrompt: "お客さんがスコーンを注文しようとしたが、店員が売り切れを伝え、代わりにマフィンがあることを案内しているカフェでのやりとり。",
  // ルール根拠: 場所、状況、登場人物の動機などを具体的に説明。
  senderVoiceInstruction: "申し訳なさそうに、でも優しく明るい声で。",
  receiverVoiceInstruction: "少しがっかりしつつも前向きに。",
  incorrectOptions: [
    "本日はマフィンもケーキもありません。",
    // ルール根拠: 違う単語で始まる。内容は真逆（両方なし）。
    "ちなみに窓の外のリスが全部食べました。",
    // ルール根拠: 違う単語で始まる。馬鹿馬鹿しい発想。
    "代わりに新しい種類のスコーンが入荷しました。",
    // ルール根拠: 違う単語で始まる。内容が異なるが店員らしいセリフ。
  ]
},
{
  place: "空港の搭乗ゲート",
  senderRole: "スタッフ",
  senderVoice: "male",
  receiverRole: "乗客",
  receiverVoice: "female",
  englishSentence: "Even though it’s raining, flights are on schedule.",
  // ルール根拠: 10語以内。even thoughを使い、スタッフとして状況説明。
  japaneseSentence: "雨ですが、フライトは予定通りです。",
  // ルール根拠: 日本語として自然かつ正確な訳。カタカナ英語も使わず。
  englishReply: "That’s good to know, thank you.",
  // ルール根拠: 安心した様子で、情報に対して素直に感謝を伝える。
  japaneseReply: "それはよかったです、ありがとうございます。",
  // ルール根拠: 安心しつつ感謝を伝える自然な返答。
  scenePrompt: "空港の搭乗ゲートで外は雨が降っているが、スタッフが心配している乗客にフライトの遅れがないことを伝えている。",
  // ルール根拠: 場所、状況、登場人物の動機などを具体的に説明。
  senderVoiceInstruction: "落ち着いていて丁寧、安心させるように。",
  receiverVoiceInstruction: "ほっとした感じで、親しみやすい声。",
  incorrectOptions: [
    "雪なので、全ての便がキャンセルです。",
    // ルール根拠: 違う単語で始まる。内容は真逆（全部キャンセル）。
    "カバが滑走路を走っているため、少々お待ちください。",
    // ルール根拠: 違う単語で始まる。馬鹿馬鹿しい発想。
    "到着ゲートが変更になりましたのでご注意ください。",
    // ルール根拠: 違う単語で始まる。状況説明だが内容が異なるスタッフのセリフ。
  ]
},
{
  place: "オフィスの会議室",
  senderRole: "上司",
  senderVoice: "female",
  receiverRole: "部下",
  receiverVoice: "male",
  englishSentence: "We can't proceed unless you approve this.",
  // 10語以内で"unless"を自然に使い、会議室での上司としての指示として自然な一文
  japaneseSentence: "あなたが承認しないと先に進めません。",
  // "unless"の意味も伝わるような、自然な日本語訳
  englishReply: "Okay, I will check the document now.",
  // 上司の「あなたが承認しないと進めない」に対し、「では今資料を確認します」と返しており、内容を推測できる
  japaneseReply: "わかりました、今書類を確認します。",
  // 英語の返答内容に沿った自然な日本語訳で、やりとりの内容が推測できる
  scenePrompt: "オフィスの会議室で、上司が部下に新しいプロジェクトの承認を依頼している。部下がまだ承認していないため、上司は次のステップに進めず困っている。",
  // 会議室、上司と部下、プロジェクト承認依頼のビジネスシーンを具体的に記述
  senderVoiceInstruction: "落ち着いたが少し急ぎのトーンで",
  receiverVoiceInstruction: "丁寧で前向きな口調で",
  incorrectOptions: [
    // 全てjapaneseSentenceと同じくらいの長さで、1文目と違う単語で始めている
    "今すぐ会議を始めても大丈夫ですか？",
    // 真逆の意味：「あなたが承認しなくても先に進めます」
    "私の承認がなくても進めてください。",
    // 馬鹿馬鹿しい文：「全ての書類を紙飛行機にして飛ばしてもいいですか？」
    "全部の書類を紙飛行機にして飛ばしますか？"
  ]
},
{
  place: "鉄道駅のホーム",
  senderRole: "駅員",
  senderVoice: "male",
  receiverRole: "乗客",
  receiverVoice: "female",
  englishSentence: "Once the train departs, you can't board anymore.",
  // 10語以内で"once"を自然に使い、駅員が注意する自然な一文
  japaneseSentence: "電車が発車したらもう乗れません。",
  // "once"を「～したら」と訳し、日本語として自然に
  englishReply: "Oh, I see. I'll hurry to get on.",
  // 乗客が「あ、わかりました。急いで乗ります」と返しており、内容が推測できる
  japaneseReply: "あ、わかりました。急いで乗ります。",
  // 英語の返答内容に沿った自然な日本語訳
  scenePrompt: "鉄道駅のホームで、乗客が発車間際の電車に乗ろうとしている。駅員が発車後は乗れないことを丁寧に説明している。",
  // 駅のホーム、駅員が乗客に注意を促す状況を具体的に記述
  senderVoiceInstruction: "丁寧で注意喚起する話し方で",
  receiverVoiceInstruction: "少し慌てたが礼儀正しい口調で",
  incorrectOptions: [
    // 全て違う語で始め、同程度の長さ
    "この電車は空を飛ぶことができます。",
    // 真逆の意味：「電車が発車してもまだ乗れます」
    "電車が発車してもまだ乗れますよ。",
    // 馬鹿馬鹿しい文：「電車が消えたらジャンプして追いかけてください」
    "電車が消えたらジャンプして追いかけてください。"
  ]
},
{
  place: "病院の受付",
  senderRole: "受付スタッフ",
  senderVoice: "female",
  receiverRole: "患者",
  receiverVoice: "male",
  englishSentence: "Let us know whether you have an appointment.",
  // 10語以内で"whether"を自然に使い、受付スタッフの質問として自然な一文
  japaneseSentence: "予約があるかどうか教えてください。",
  // "whether"を「～かどうか」と訳し、実用的な日本語に
  englishReply: "Yes, I have an appointment at three.",
  // 患者が「はい、3時に予約しています」と返しているため内容が推測できる
  japaneseReply: "はい、3時に予約しています。",
  // 英語の返答内容に沿った自然な日本語訳
  scenePrompt: "病院の受付で、患者が受付スタッフに声をかけられ、予約の有無を確認されている。",
  // 病院受付、スタッフと患者のやりとりを具体的に記述
  senderVoiceInstruction: "穏やかで丁寧な声で",
  receiverVoiceInstruction: "落ち着いた普通の口調で",
  incorrectOptions: [
    // 全て違う語で始め、同程度の長さ
    "今日の天気は晴れかどうか教えてください。",
    // 真逆の意味：「予約があっても伝えなくて大丈夫です」
    "予約があっても教えなくて大丈夫です。",
    // 馬鹿馬鹿しい文：「宇宙人が来ているかどうか教えてください」
    "宇宙人が来ているかどうか教えてください。"
  ]
},
{
  place: "会社の会議室",
  senderRole: "マネージャー",
  senderVoice: "male",
  receiverRole: "チームメンバー",
  receiverVoice: "female",
  englishSentence: "You can leave early provided that your work is done.",
  // 指定語彙「provided that」を自然に使い、10語以内。許可・条件提示の文。
  // 10語以内で自然な会話文となっている。
  japaneseSentence: "仕事が終わっていれば早く帰っていいよ。",
  // 「provided that」の意味を自然に日本語訳に反映し、直訳を避けている。
  englishReply: "Oh, thank you! I’ll finish up soon.",
  // 早く帰れることへの感謝とやる気が伝わる返答。内容から条件を推測できる。
  japaneseReply: "ありがとうございます！すぐに終わらせますね。",
  // 早く帰れる条件に対して感謝し、やる気を示す日本語訳。
  scenePrompt: "会社の会議室で、マネージャーがチームメンバーに、もし仕事が終わっていれば早めに退社してもよいと伝えている。チームメンバーは感謝しつつ、やるべきことを急いで終わらせようとしている。",
  // 場所、登場人物、動機、状況などを詳細に説明。
  senderVoiceInstruction: "落ち着いて親切なトーンで、やや柔らかく伝える",
  receiverVoiceInstruction: "明るく前向きな声で感謝を表現する",
  incorrectOptions: [
    "今夜は絶対に残業しないでくださいね。", // 「provided that」の条件とは異なり、一方的な指示。
    "明日までに仕事が終わらなかったら帰れません。", // 真逆の意味。終わらないと帰れない。
    "全員でカンガルーの着ぐるみを着て会議に出てください。", // 馬鹿馬鹿しい内容。
  ]
},
{
  place: "小さなカフェ",
  senderRole: "店員",
  senderVoice: "female",
  receiverRole: "常連客",
  receiverVoice: "male",
  englishSentence: "Let me know in case you need a refill.",
  // 指定語彙「in case」を自然に使い、10語以内。提案・依頼の文。
  // 10語以内で自然な会話文となっている。
  japaneseSentence: "おかわりが必要なら教えてくださいね。",
  // 「in case」の意味を自然な日本語に訳し、直訳を避けている。
  englishReply: "Okay, I’ll tell you if I want more coffee.",
  // 「必要なら伝える」と内容から英語文を推測できる返答。
  japaneseReply: "わかりました。もっと欲しくなったら伝えます。",
  // おかわりが要る場合は伝える、という自然な日本語。
  scenePrompt: "カフェで常連客がコーヒーを飲んでいると、店員が気配りしながら、もしおかわりが必要になったら声をかけてほしいと伝えている。店員は親しみやすく対応している。",
  // 場所、登場人物、動機、状況などを詳細に説明。
  senderVoiceInstruction: "やさしく親しみやすいトーンで、気遣いを込めて",
  receiverVoiceInstruction: "リラックスした声で感謝をこめて返答",
  incorrectOptions: [
    "追加料金はいただきませんのでご安心ください。", // 「in case」や依頼と異なる内容。
    "おかわりは絶対にできませんのでご遠慮ください。", // 真逆の意味。
    "コーヒーのかわりにカレーを頭にかけましょうか？", // 馬鹿馬鹿しい内容。
  ]
},
{
  place: "オフィスの受付",
  senderRole: "受付担当者",
  senderVoice: "male",
  receiverRole: "来訪者",
  receiverVoice: "female",
  englishSentence: "Your name is listed above the others.",
  // 指定語彙「above」を自然に使い、10語以内。報告、説明の文。
  // 10語以内で自然な会話文となっている。
  japaneseSentence: "あなたのお名前が一番上に載っています。",
  // 「above」の意味を自然な日本語訳に反映し、直訳を避けている。
  englishReply: "Oh, I see. That’s easy to find then.",
  // 名前が一番上にあるため見つけやすいと推測できる返答。
  japaneseReply: "ああ、なるほど。それならすぐ見つかりますね。",
  // 一番上に載っていることを受けての自然な日本語訳。
  scenePrompt: "オフィスの受付で、来訪者が自分の名前を探していると、受付担当者が名簿の一番上にその名前があることをわかりやすく説明している。来訪者は安心している。",
  // 場所、登場人物、動機、状況などを詳細に説明。
  senderVoiceInstruction: "明るく丁寧なトーンで、はっきりと伝える",
  receiverVoiceInstruction: "安心し少しホッとした声で返答する",
  incorrectOptions: [
    "ご用件が書かれていないので入館できません。", // 「above」や説明と異なる内容。
    "お名前は一番下に記載されています。", // 真逆の意味。
    "空飛ぶペンギンの名前もリストに載っていますよ。", // 馬鹿馬鹿しい内容。
  ]
},
{
  place: "会社のオフィス",
  senderRole: "上司",
  senderVoice: "female",
  receiverRole: "部下",
  receiverVoice: "male",
  englishSentence: "Please review the report below by noon.",
  // 「below」を使い、10語以内、自然な業務指示のセリフです。
  japaneseSentence: "下記の報告書を正午までに確認してください。",
  // 「下記の報告書を正午までに確認してください。」は、"Please review the report below by noon." の自然な訳です。
  englishReply: "Sure, I will check the report under this email.",
  // 「下にある報告書を確認します」と推測できるヒントになる返答です。
  japaneseReply: "はい、このメールの下の報告書を確認します。",
  // 「はい、このメールの下の報告書を確認します」は、英文の内容を推測できる日本語訳です。
  scenePrompt: "朝のオフィス。上司がメールで部下に報告書の確認を依頼しています。部下はパソコンの画面を見ながら返事をしています。",
  // オフィス内でメールを通じて業務連絡をしている具体的な場面説明です。
  senderVoiceInstruction: "落ち着いたが明確な口調で、業務的に指示する",
  receiverVoiceInstruction: "丁寧で少し緊張した感じ",
  incorrectOptions: [
    "今日のランチ会の参加者名簿を提出してください。",
    // 「下記の報告書を正午までに確認してください。」とは逆の「提出」や内容違い。文頭も違う。
    "ごみ箱の中身をすべてパソコンに送ってください。",
    // 馬鹿馬鹿しい内容。「下記の報告書を正午までに確認してください。」と全く異なる意味。
    "この報告書は明日までに確認しなくていいです。",
    // 真逆の意味。確認しなくていいという指示。
  ]
},
{
  place: "美術館の展示室",
  senderRole: "ガイド",
  senderVoice: "male",
  receiverRole: "観光客",
  receiverVoice: "female",
  englishSentence: "Photography is not allowed throughout this gallery.",
  // 「throughout」を使い、10語以内、自然な美術館での注意事項のセリフです。
  japaneseSentence: "この展示室では写真撮影は禁止されています。",
  // 「この展示室では写真撮影は禁止されています。」は "Photography is not allowed throughout this gallery." の自然な訳です。
  englishReply: "Oh, so I can't take pictures here?",
  // 写真を撮ってはいけないことが推測できるヒントの返答。
  japaneseReply: "ああ、ここで写真を撮れないんですね？",
  // 「ここで写真を撮れないんですね？」は英文の内容を推測できる返答です。
  scenePrompt: "美術館の展示室でガイドが観光客に展示室全体での写真撮影禁止を説明しています。観光客はカメラを持っています。",
  // 美術館の展示室でのシチュエーション説明です。
  senderVoiceInstruction: "丁寧で礼儀正しい口調",
  receiverVoiceInstruction: "少し驚いた感じで丁寧に",
  incorrectOptions: [
    "この美術館では飲食は自由です。",
    // 文頭が違い、内容も違う。
    "全ての展示品を触っていただけますのでご安心ください。",
    // 馬鹿馬鹿しい内容。美術館で展示品に触れることを許可することは通常ありえない。
    "この展示室では写真撮影が特別に許可されています。",
    // 真逆の意味。「写真撮影が禁止」ではなく「許可」。
  ]
},
{
  place: "大学の講義室",
  senderRole: "教授",
  senderVoice: "female",
  receiverRole: "学生",
  receiverVoice: "male",
  englishSentence: "Despite the rain, class will proceed as scheduled.",
  // 「despite」を使い、10語以内、自然な大学の講義開始前の案内セリフです。
  japaneseSentence: "雨ですが、授業は予定通り行います。",
  // 「雨ですが、授業は予定通り行います。」は "Despite the rain, class will proceed as scheduled." の自然な訳です。
  englishReply: "Okay, I’ll be in class on time.",
  // 雨でも授業があることを受けて、授業に出席する旨の返答。
  japaneseReply: "わかりました、時間通りに教室に行きます。",
  // 「わかりました、時間通りに教室に行きます」は英文の内容を推測できる返答です。
  scenePrompt: "大学の講義室。外は雨が降っているが、教授が学生に授業が通常通りあることを伝えています。学生は傘を持っています。",
  // 雨天時の大学講義のシチュエーション説明です。
  senderVoiceInstruction: "はきはきとして明るい口調",
  receiverVoiceInstruction: "誠実で元気そうに",
  incorrectOptions: [
    "本日は全ての授業が中止となります。",
    // 文頭が違い、内容も逆。
    "傘の忘れ物がたくさんあるのでご注意ください。",
    // 馬鹿馬鹿しい内容。雨と授業の継続に関係なく、傘の忘れ物について言及。
    "雨のため、授業は全て延期となります。",
    // 真逆の意味。「授業は予定通り」→「授業は延期」。
  ]
},
{
  place: "会社の会議室",
  senderRole: "チームリーダー",
  senderVoice: "female",
  receiverRole: "部下",
  receiverVoice: "male",
  englishSentence: "In spite of delays, we finished early.",
  // 10語以内で"in spite of"を自然に含み、句読点込みで9単語。会議でよくある進捗報告の一言。
  // ルール根拠: 指定語彙を自然に使用し、条件内の語数で、役割に合ったセリフ。
  japaneseSentence: "遅れがあったのに、早く終わりました。",
  // "in spite of" を「〜があったのに」と訳し、自然な日本語にしている。
  englishReply: "Great, that’s impressive. We can relax now.",
  // 進捗報告を受けて「すごいですね。これでひと息つけますね」と内容を想像できる返答。
  japaneseReply: "すごいですね。これでひと息つけますね。",
  // 報告に対する自然な返事で、英語・日本語ともに内容が推測できる。
  scenePrompt: "会社の会議室でチームリーダーが部下に、プロジェクトの進捗について報告している。予想外の遅れはあったが、皆の協力で予定より早く作業が終わった状況。",
  // 場所や登場人物の動機、会話の背景を具体的に説明している。
  senderVoiceInstruction: "落ち着いて自信のある声で、穏やかに",
  receiverVoiceInstruction: "明るくねぎらうように",
  incorrectOptions: [
    "今日は全く仕事が進みませんでした。", // 真逆の意味
    "パーティー用のケーキを天井に投げてみましょうか？", // 馬鹿馬鹿しい文章
    "新しい問題がいくつか出てきました。", // 別の一般的な内容
    // ルール根拠: すべて異なる語で始まり、正解文と重複もなく、1つは真逆、1つは馬鹿馬鹿しい内容、1つは一般的な誤答
  ],
},
{
  place: "駅の改札",
  senderRole: "駅員",
  senderVoice: "male",
  receiverRole: "通勤客",
  receiverVoice: "female",
  englishSentence: "According to the board, the train is late.",
  // 10語以内で"according to"を自然に含み、案内板を根拠に遅延を伝えている。
  // ルール根拠: 指定語彙・語数・役割・場面に合致。
  japaneseSentence: "掲示板によると電車は遅れているそうです。",
  // "according to"を「〜によると」と自然に訳している。
  englishReply: "Oh, I see. I’ll wait here then.",
  // 「そうなんですね。じゃあここで待ちます」と内容を想像できる返答。
  japaneseReply: "そうなんですね。じゃあここで待ちます。",
  // 電車遅延に対する自然な返事。
  scenePrompt: "朝の駅の改札で、通勤客が電車の運行状況を駅員に尋ねた。駅員が掲示板を確認し、電車が遅れていることを伝えている。",
  // 会話の背景、場所、やり取りの詳細が具体的に説明されている。
  senderVoiceInstruction: "丁寧で説明的な口調で",
  receiverVoiceInstruction: "ややがっかりした様子で自然に",
  incorrectOptions: [
    "全ての電車がすでに出発しています。", // 真逆の意味
    "今からカラフルな風船を配ります。", // 馬鹿馬鹿しい文章
    "次の電車は15分後に来ます。", // 別の一般的な案内
    // ルール根拠: 異なる語で始まり、正解文と重複なし、真逆・馬鹿馬鹿しい・普通の誤答を網羅
  ],
},
{
  place: "病院の受付",
  senderRole: "受付スタッフ",
  senderVoice: "female",
  receiverRole: "患者",
  receiverVoice: "male",
  englishSentence: "Owing to weather, your appointment is postponed.",
  // 10語以内で"owing to"を自然に含み、天候が理由の延期を伝えている。
  // ルール根拠: 指定語彙、語数制限、役割・場面に合った内容。
  japaneseSentence: "天候のため、ご予約は延期になりました。",
  // "owing to"を自然な日本語「〜のため」と訳し、受付の口調にしている。
  englishReply: "Oh, I understand. When is the new date?",
  // 延期を受け入れ、次の予定を尋ねる返答。内容が推測できる。
  japaneseReply: "分かりました。次はいつになりますか？",
  // 延期を受けて次回日程を尋ねる自然な返事。
  scenePrompt: "病院の受付で、患者が予約時間に来院したところ、受付スタッフが天候不良のため診察日が延期になったことを伝えている。",
  // 病院、登場人物、延期理由、やり取りの背景を明確に説明。
  senderVoiceInstruction: "申し訳なさそうに、丁寧な口調で",
  receiverVoiceInstruction: "落ち着いて、状況を受け入れるように",
  incorrectOptions: [
    "今日は予定通り診察を行います。", // 真逆の意味
    "診察の代わりにカエルの合唱会があります。", // 馬鹿馬鹿しい文章
    "ご予約はキャンセルとなりました。", // 一般的な誤答
    // ルール根拠: すべて異なる語で始まり、意味・内容がばらけている。真逆、馬鹿馬鹿しい、一般的な誤答を網羅。
  ],
},
{
  place: "オフィスの会議室",
  senderRole: "プロジェクトマネージャー",
  senderVoice: "female",
  receiverRole: "チームメンバー",
  receiverVoice: "male",
  englishSentence: "Everyone is here except for John.",
  // 指定通り10語以内。except forを自然に会話に組み込んでいる。
  japaneseSentence: "ジョン以外は全員そろっています。",
  // except forの部分を自然な日本語訳で「〜以外は」としている。
  englishReply: "Oh, is John running late today?",
  // 返答として、ジョンが遅れているのか尋ねる内容。except for Johnを推測できる。
  japaneseReply: "ああ、今日はジョンが遅れているんですか？",
  // 上記返答の自然な日本語訳。except for Johnの内容を推測できる。
  scenePrompt: "オフィスの会議室で、プロジェクトマネージャーが会議の出席者を確認している。全員が席についているが、ジョンだけがまだ来ていない状況。",
  // どのような場面か、場所や登場人物、ジョンがいない理由まで具体的に説明。
  senderVoiceInstruction: "落ち着いた丁寧な話し方で、状況を確認するように。",
  receiverVoiceInstruction: "少し心配そうに、親しみやすいトーンで。",
  incorrectOptions: [
    "全員が揃うまで会議は始まりません。",
    // ジョン以外が揃っているという意味と逆の「全員が揃うまで」とした。真逆の意味。
    "私は今日、ジョンとランチに行く予定です。",
    // 内容が会話の流れとは異なる自然な誤答。先頭語も被っていない。
    "当社の会議室には巨大なピザが配られています。",
    // 馬鹿馬鹿しい内容で会議室の通常の状況から逸脱している。
  ]
  // incorrectOptionsはjapaneseSentenceと長さがばらけており、文頭も全て異なる語を使用し、1つは逆、1つは馬鹿馬鹿しい内容。
},
{
  place: "ホテルのフロント",
  senderRole: "フロントスタッフ",
  senderVoice: "male",
  receiverRole: "宿泊客",
  receiverVoice: "female",
  englishSentence: "Breakfast is not included beyond 10 AM.",
  // beyondを時間の制約として自然に使い、10語以内に収めている。
  japaneseSentence: "朝食は10時以降は含まれません。",
  // beyond 10 AMを「10時以降」と自然な日本語に訳している。
  englishReply: "Oh, then I should come down earlier.",
  // 朝食の時間制限を受けて、早めに来るべきだと返答。beyondの内容が推測できる。
  japaneseReply: "ああ、それならもっと早く降りてきますね。",
  // 上記返答を自然な日本語訳。制限時間を受けていることが伝わる。
  scenePrompt: "ホテルのフロントで、スタッフが朝食の提供時間について案内している。宿泊客が朝食の時間について尋ねた直後の場面。",
  // ホテルのフロント、スタッフと宿泊客、朝食時間の案内の文脈を具体的に説明。
  senderVoiceInstruction: "丁寧でややフォーマルな口調で案内する。",
  receiverVoiceInstruction: "納得した様子で、親しみやすく。",
  incorrectOptions: [
    "朝食はお部屋までお持ちしますね。",
    // 「含まれません」と逆で「サービスを提供する」内容にした。真逆。
    "私のカバンが朝食でいっぱいになっています。",
    // 馬鹿馬鹿しい内容。現実的ではない状況。
    "明日は朝食が無料になる予定です。",
    // 会話の流れとは異なるが、フロントスタッフが言いそうな内容。先頭語も被らない。
  ]
  // incorrectOptionsは文頭に違いがあり、意味も多様で、1つは馬鹿馬鹿しい内容、1つは逆の意味。
},
{
  place: "銀行の窓口",
  senderRole: "窓口担当者",
  senderVoice: "female",
  receiverRole: "顧客",
  receiverVoice: "male",
  englishSentence: "You must submit the form within five days.",
  // withinを明確に使い、10語未満の指示文で自然な会話。
  japaneseSentence: "この書類は5日以内に提出してください。",
  // within five daysを「5日以内に」と自然な日本語訳。
  englishReply: "Okay, I will bring it before the deadline.",
  // 期限前に提出する旨を述べており、withinを推測できる内容。
  japaneseReply: "はい、期限前に持ってきます。",
  // 上記返答の自然な日本語訳。期限を意識している。
  scenePrompt: "銀行の窓口で、新しいサービスの申込書を受け取った顧客に対し、窓口担当者が提出期限について説明している。",
  // 銀行窓口、担当者と顧客、申込書と提出期限の文脈を具体的に説明。
  senderVoiceInstruction: "事務的で丁寧な口調で、はっきりと説明する。",
  receiverVoiceInstruction: "理解した様子で、落ち着いて返答する。",
  incorrectOptions: [
    "この書類は明日までに破いてください。",
    // 馬鹿馬鹿しい内容。書類を破いてくださいという非現実的な指示。
    "翌週に提出しても大丈夫ですよ。",
    // 5日以内と逆で、もっと遅くてもいいという真逆の意味。
    "必要な場合は別の窓口をご案内します。",
    // 会話の流れとは異なるが、窓口担当者が言いそうな内容で先頭語も被らない。
  ]
  // incorrectOptionsは文頭が全て異なり、1つは馬鹿馬鹿しい内容、1つは真逆の内容。
},
{
  place: "会議室",
  senderRole: "部長",
  senderVoice: "female",
  receiverRole: "社員",
  receiverVoice: "male",
  englishSentence: "We have reached our quota, therefore let's celebrate.",
  // 10語以内で "therefore" を自然に使用。TOEIC頻出、口語にもあり得る。
  japaneseSentence: "目標を達成したので、お祝いしましょう。",
  // 自然な日本語訳。「therefore」の因果関係を明確に訳出。
  englishReply: "Great! I'll order a cake for everyone.",
  // 目標達成を受けてお祝いのケーキを頼む、内容から因果関係が推測できる。
  japaneseReply: "いいですね！みんなのためにケーキを注文します。",
  // お祝い案への自然な返答。状況を想像できる訳。
  scenePrompt: "会議室で、部長がチームに向かって今月のノルマ達成を報告し、皆でお祝いしようと提案している。社員たちは達成感にあふれ、部長の提案に喜んでいる雰囲気。",
  // 場所・背景・登場人物・動機を具体的に説明。文脈を明確に記述。
  senderVoiceInstruction: "自信にあふれて明るく、みんなを鼓舞するように",
  receiverVoiceInstruction: "うれしそうで元気なトーン",
  incorrectOptions: [
    "この後、全員で大掃除を始めましょう。",
    // "celebrate" の逆である「掃除」。「お祝い」とは真逆の意味。
    "明日は部長の誕生日なのでパーティーです。",
    // 目標達成とは関連しない誤った情報。始まりの語句も異なる。
    "巨大なプリンを作ってオフィスに飾りましょう。",
    // 馬鹿馬鹿しい発想。「巨大なプリン」をオフィスに飾る。
  ]
},
{
  place: "空港のチェックインカウンター",
  senderRole: "空港スタッフ",
  senderVoice: "male",
  receiverRole: "旅行客",
  receiverVoice: "female",
  englishSentence: "You must check in now, otherwise you’ll miss your flight.",
  // 10語以内で "otherwise" を自然に組み込み、警告文として自然。
  japaneseSentence: "今すぐチェックインしないと、飛行機に乗り遅れますよ。",
  // 「otherwise」を「〜しないと〜」と自然に訳出。
  englishReply: "Oh, thank you! I’ll check in right away.",
  // すぐにチェックインする意思を伝えているため内容が推測できる。
  japaneseReply: "ありがとうございます！すぐにチェックインします。",
  // 受付スタッフへの自然な返答。状況が想像できる。
  scenePrompt: "空港のカウンターで、出発間際の旅行客に対し、スタッフが急いでチェックインするよう優しく注意している。旅行客は少し焦りながらも感謝している。",
  // 場所・背景・登場人物・動機を具体的に記述し、情景が浮かぶ説明。
  senderVoiceInstruction: "丁寧で親切、少し急がせるような口調",
  receiverVoiceInstruction: "焦りつつも丁寧で感謝の気持ちを込めて",
  incorrectOptions: [
    "新しい航空券を今すぐ購入してください。",
    // 「チェックイン」とは逆、「今すぐ購入」→「乗り遅れる」と真逆の意味。
    "荷物にパイナップルを入れても大丈夫ですか？",
    // 内容が無関係な質問。始まりの語句も異なる。
    "巨大なカバンを持ってダンスしませんか？",
    // 馬鹿馬鹿しい発想。「巨大なカバンでダンス」。
  ]
},
{
  place: "カフェ",
  senderRole: "バリスタ",
  senderVoice: "female",
  receiverRole: "常連客",
  receiverVoice: "male",
  englishSentence: "Your coffee is being prepared, meanwhile please have a seat.",
  // 10語以内で "meanwhile" を自然に使用。TOEIC頻出、カフェで使われる口語。
  japaneseSentence: "コーヒーを準備している間、どうぞおかけください。",
  // 「meanwhile」を「〜している間に」と自然に訳出。
  englishReply: "Thank you. I’ll wait here until it’s ready.",
  // コーヒーができるまで席で待つ旨を伝え、内容が推測できる。
  japaneseReply: "ありがとうございます。できるまでここで待っています。",
  // 「準備中」→「待つ」の因果がわかる自然な訳。
  scenePrompt: "カフェのカウンターで、バリスタが常連客にコーヒーの準備を伝え、席で待つように案内している。店内は落ち着いた雰囲気で、他のお客さんもリラックスしている。",
  // カフェの状況・登場人物・動機を具体的に記述。情景が明確。
  senderVoiceInstruction: "親しみやすく穏やかなトーンで丁寧に",
  receiverVoiceInstruction: "礼儀正しくリラックスした様子で",
  incorrectOptions: [
    "次の注文が終わるまで立っていてください。",
    // 「座ってください」とは真逆の意味。「立っていて」と指示。
    "入り口でパンダの着ぐるみを着てお待ちください。",
    // 馬鹿馬鹿しい発想。「パンダの着ぐるみ」で待つ。
    "本日はコーヒーの提供を終了しております。",
    // 内容が異なる誤情報。始まりの語句も異なる。
  ]
},
{
  place: "会社の会議室",
  senderRole: "マネージャー",
  senderVoice: "male",
  receiverRole: "部下",
  receiverVoice: "female",
  englishSentence: "We missed the deadline; consequently, the client left.",
  // 10語以内。TOEIC頻出の"consequently"を自然に使用し、会議室のマネージャー発言として適切。
  japaneseSentence: "締切に間に合わなかったので、結果的に顧客が離れました。",
  // 丁寧で自然な日本語訳。カタカナ英語を使わず内容も正確。
  englishReply: "Oh, so we lost the project because of that.",
  // 原因と結果が読み取れ、内容推測のヒントになる返答。
  japaneseReply: "ああ、それで私たちはその案件を失ったんですね。",
  // 英文内容が推測できる適切な返答訳。
  scenePrompt: "会社の会議室でマネージャーが部下に、納期遅れのために顧客を失ったことを説明している。部下はその理由を理解しようとしている。",
  // 場所、登場人物、状況、動機の説明を含む。
  senderVoiceInstruction: "落ち着いたが少し残念そうな真剣な話し方",
  receiverVoiceInstruction: "驚きと納得が混ざった落ち着いた声",
  incorrectOptions: [
    "新しいプロジェクトが始まるので、気を引き締めてください。",
    // 文頭・文意が異なり、japaneseSentenceと同じ語で始まらない。長さも許容範囲。
    "私たちは締切に間に合ったので、顧客はとても喜びました。",
    // 真逆の内容。文頭が異なる。
    "実は全員で会議室でダンスバトルをしました。",
    // 馬鹿馬鹿しい発想で文頭も異なる。
  ],
},
{
  place: "大学の図書館",
  senderRole: "学生",
  senderVoice: "female",
  receiverRole: "友人",
  receiverVoice: "male",
  englishSentence: "It started raining; nevertheless, I walked here.",
  // 10語以内。自然な会話文で"nevertheless"を活用。
  japaneseSentence: "雨が降り始めたけど、それでも私はここまで歩いてきたよ。",
  // 内容・語感とも自然な日本語訳。
  englishReply: "Wow, you must really like studying here.",
  // 雨でも来たことから内容が連想できる返答。
  japaneseReply: "へえ、ここで勉強するのが本当に好きなんだね。",
  // 内容推測に役立つ返答訳。
  scenePrompt: "大学の静かな図書館。学生が友人に、雨の中でも歩いて来た熱意を伝えている。友人は驚きながらその努力を認めている。",
  // 場所・状況・動機・登場人物の様子を説明。
  senderVoiceInstruction: "カジュアルで少し誇らしげな明るい話し方",
  receiverVoiceInstruction: "感心している、やや驚いた声",
  incorrectOptions: [
    "昨日は一晩中ここでパーティーをしていました。",
    // 馬鹿馬鹿しい内容。文頭も違う。
    "私は雨が降ったから、家にずっといました。",
    // 真逆の内容。文頭が異なる。
    "普通はバスで来るけど、今日は混んでいたよ。",
    // 文頭も内容も異なり、長さも許容範囲。
  ],
},
{
  place: "ホテルのフロント",
  senderRole: "フロントスタッフ",
  senderVoice: "male",
  receiverRole: "宿泊客",
  receiverVoice: "female",
  englishSentence: "Breakfast is included; furthermore, parking is free.",
  // 10語以内。TOEIC頻出"furthermore"を自然に使い、フロントでの案内に適切。
  japaneseSentence: "朝食が付いていますし、さらに駐車場も無料です。",
  // 丁寧で自然な日本語訳。
  englishReply: "Oh, that's great. Thank you for letting me know.",
  // 朝食と駐車場の案内に対して納得の返答で内容推測に役立つ。
  japaneseReply: "ああ、それは嬉しいです。教えてくれてありがとう。",
  // 朝食・駐車場無料に対する自然な返答訳。
  scenePrompt: "ホテルのフロントでスタッフが宿泊客に、朝食が付いており駐車場も無料で利用できることを案内している。宿泊客はそのサービスに満足している様子。",
  // 登場人物、場所、状況、動機を具体的に説明。
  senderVoiceInstruction: "親切で丁寧、明るい案内の口調",
  receiverVoiceInstruction: "感謝と喜びが感じられるやわらかい声",
  incorrectOptions: [
    "お部屋にサプライズでピザを100枚ご用意しました。",
    // 馬鹿馬鹿しい内容。文頭も異なる。
    "朝食も駐車場もご利用いただけませんのでご了承ください。",
    // 真逆の内容。文頭が異なる。
    "ご質問があれば、いつでもフロントにお声かけください。",
    // 文頭も内容も異なり、適切な長さ。
  ],
},
{
  place: "オフィスの会議室",
  senderRole: "プロジェクトマネージャー",
  senderVoice: "female",
  receiverRole: "チームリーダー",
  receiverVoice: "male",
  englishSentence: "Moreover, we must meet the deadline.",
  // コメント: 10語以内で "moreover" を自然に使い、会議室のやりとりとして自然な文です。
  japaneseSentence: "さらに、私たちは締め切りを守らなければなりません。",
  // コメント: "moreover"を「さらに」と訳し、全体が自然な日本語になっている。
  englishReply: "Yes, I'll remind the team about the deadline.",
  // コメント: 締め切りについて再確認する内容で、英文から内容を推測可能です。
  japaneseReply: "はい、チームに締め切りを再度伝えます。",
  // コメント: 締め切りを守る話題に合った返答で、内容のヒントになっています。
  scenePrompt: "ガラス張りの明るい会議室で、プロジェクトマネージャーが重要な進捗を話しながら、今後のタスク管理について強調している。チームリーダーはメモを取りながら真剣に聞いている。",
  // コメント: 場所、登場人物、状況、動機を具体的に説明。
  senderVoiceInstruction: "落ち着いていて説得力のある丁寧な話し方",
  receiverVoiceInstruction: "慎重で協力的なトーン",
  incorrectOptions: [
    // コメント: 各文頭が異なり、japaneseSentenceと同じ語で始まらない。1つ目は真逆、2つ目は馬鹿馬鹿しい。
    "今日はもう何もやらなくていいですよ。",
    "当社のマスコットキャラクターが締め切りを延長してくれるそうです。",
    "とりあえず、会議を中止しましょう。"
  ]
},
{
  place: "ホテルのフロントデスク",
  senderRole: "フロントスタッフ",
  senderVoice: "male",
  receiverRole: "宿泊客",
  receiverVoice: "female",
  englishSentence: "There has been a considerable delay in service.",
  // コメント: 10語以内、"considerable"を自然に利用し、ホテルの案内として適切。
  japaneseSentence: "サービスにかなりの遅れが出ております。",
  // コメント: "considerable"を「かなりの」と自然に訳している。
  englishReply: "Oh, I see. How long will it take?",
  // コメント: 遅れに関する質問で、内容を推測しやすい。
  japaneseReply: "ああ、そうなんですね。あとどのくらいかかりますか？",
  // コメント: サービスの遅れについての話題に沿った自然な返答。
  scenePrompt: "シックなホテルのフロントで、スタッフが客に丁寧に説明している。ロビーには他の宿泊客もいて、少し待たされている様子。",
  // コメント: 場所、背景、登場人物の状況を具体的に描写。
  senderVoiceInstruction: "申し訳なさそうで丁寧な話し方",
  receiverVoiceInstruction: "穏やかで少し心配そうな口調",
  incorrectOptions: [
    // コメント: 各文頭が異なり、japaneseSentenceと同じ語で始まらず、1つは馬鹿馬鹿しい。
    "本日は全てのサービスが非常に早く提供されています。",
    "ロビーでダンス大会が始まるのでしばらくお待ちください。",
    "もしよろしければ、別のホテルをご案内しましょう。"
  ]
},
{
  place: "カフェのカウンター",
  senderRole: "店員",
  senderVoice: "female",
  receiverRole: "常連客",
  receiverVoice: "male",
  englishSentence: "Our menu has changed considerably this month.",
  // コメント: 10語以内で"considerably"を自然に使い、カフェの案内として適切。
  japaneseSentence: "今月はメニューが大幅に変わりました。",
  // コメント: "considerably"を「大幅に」と自然な日本語で表現。
  englishReply: "Oh, really? I’m looking forward to trying something new.",
  // コメント: 変化に驚き、楽しみにしている返答。ヒントになる。
  japaneseReply: "へえ、そうなんですね。新しいものを食べるのが楽しみです。",
  // コメント: メニューの大幅な変更に関連した自然な返答。
  scenePrompt: "明るいカフェで、店員が新しいメニューについて常連客に笑顔で説明している。カウンターには新メニューのポップが飾られている。",
  // コメント: 場所、状況、登場人物の関係を具体的に説明。
  senderVoiceInstruction: "明るく親しみやすい口調",
  receiverVoiceInstruction: "好奇心旺盛で嬉しそうな声",
  incorrectOptions: [
    // コメント: 各文頭が異なり、japaneseSentenceと同じ語で始まらず、1つは馬鹿馬鹿しい。
    "昨日のメニューが全部消えてしまいました。",
    "宇宙人向けのメニューだけを用意しています。",
    "毎日同じメニューしかありません。"
  ]
},
{
  place: "ホテルのフロント",
  senderRole: "フロントスタッフ",
  senderVoice: "female",
  receiverRole: "宿泊客",
  receiverVoice: "male",
  englishSentence: "Could you pay the full amount in advance?",
  // 指定語彙 "in advance" を自然に会話文に組み込んでいる。10語以内。
  japaneseSentence: "事前に全額お支払いいただけますか？",
  // "in advance"を「事前に」と自然に訳している。
  englishReply: "Sure, I will pay everything now.",
  // 支払いに同意し、今すぐ払うと返答している。内容が推測できる。
  japaneseReply: "はい、今すべて支払います。",
  // 支払いに応じている返事で、「事前に」のニュアンスも含まれている。
  scenePrompt: "ホテルのフロントで、チェックイン時にフロントスタッフが宿泊客に対して事前精算をお願いしている場面。宿泊客はスーツケースを手にしており、フロントには他のお客も並んでいる。",
  // 場所・役割・状況・動機・周囲の様子を具体的に説明している。
  senderVoiceInstruction: "丁寧で落ち着いた話し方。丁重な接客を意識して",
  receiverVoiceInstruction: "やや緊張しつつも丁寧で協力的な口調",
  incorrectOptions: [
    "今すぐクレジットカードを作っていただけますか？",
    // 文頭は「今すぐ」。japaneseSentenceと違う語で始まっている。内容も異なる。
    "全額の支払いは後日でも構いません。",
    // 文頭は「全額の」。真逆の意味（支払いを後にしてもいい）。
    "当ホテル自慢のカエル料理はいかがですか？",
    // 文頭「当ホテル自慢の」。馬鹿馬鹿しい内容で現実的でない。
  ]
},
{
  place: "オフィスの会議室",
  senderRole: "マネージャー",
  senderVoice: "male",
  receiverRole: "チームメンバー",
  receiverVoice: "female",
  englishSentence: "As a result, the project was delayed.",
  // 指定語彙 "as a result" を自然に文頭に使用。10語以内。
  japaneseSentence: "その結果、プロジェクトは遅れました。",
  // "as a result"を「その結果」と訳し、自然な日本語にしている。
  englishReply: "I understand, we will try to catch up.",
  // 遅れたプロジェクトへの理解と巻き返しの意志を示している。内容が推測できる。
  japaneseReply: "わかりました、遅れを取り戻すようにします。",
  // 「その結果」に対応し、状況を理解して対応すると言っている。
  scenePrompt: "オフィスの会議室で、マネージャーがチームの進捗状況について説明している。何らかのトラブルがあり、プロジェクトが予定より遅れていることを報告する場面。",
  // 会議室、役割、状況、動機が具体的に描写されている。
  senderVoiceInstruction: "落ち着いていて理知的、説明的なトーン",
  receiverVoiceInstruction: "前向きで協力的な口調",
  incorrectOptions: [
    "最終的にプロジェクトは大成功しました。",
    // 文頭は「最終的に」。japaneseSentenceと異なる語で始まる。
    "今度は予定より早く終わりました。",
    // 文頭は「今度は」。真逆の意味（早く終わった）。
    "巨大なカタツムリにプロジェクトを盗まれました。",
    // 文頭「巨大な」。馬鹿馬鹿しい内容で現実的でない。
  ]
},
{
  place: "病院の受付",
  senderRole: "看護師",
  senderVoice: "female",
  receiverRole: "患者",
  receiverVoice: "male",
  englishSentence: "You will be responsible for the paperwork.",
  // 指定語彙 "be responsible for" を自然な会話で使用。10語以内。
  japaneseSentence: "書類の手続きはご自身でお願いします。",
  // "be responsible for"を「ご自身でお願いします」と自然な日本語に訳している。
  englishReply: "Okay, I will fill out the forms myself.",
  // 書類記入を自分ですると返答している。内容が推測できる。
  japaneseReply: "わかりました、自分で書類を書きます。",
  // 手続きを自分ですると明言している。
  scenePrompt: "病院の受付で、看護師が患者に診察前の書類手続きを案内している。患者は初診で、受付カウンターで説明を受けている。",
  // 病院の受付、役割、状況、動機を具体的に説明している。
  senderVoiceInstruction: "親切で説明的な丁寧な口調",
  receiverVoiceInstruction: "やや不安だが理解しようとする静かな声",
  incorrectOptions: [
    "受付のスタッフがあなたの代わりにすべて記入します。",
    // 文頭は「受付のスタッフが」。japaneseSentenceと異なる語で始まる。
    "手続きは何もしなくて大丈夫です。",
    // 文頭は「手続きは」。真逆の意味（何もしなくていい）。
    "書類の代わりに折り紙を折ってください。",
    // 文頭「書類の代わりに」。馬鹿馬鹿しい内容で現実的でない。
  ]
},
{
  place: "会議室",
  senderRole: "マネージャー",
  senderVoice: "male",
  receiverRole: "チームメンバー",
  receiverVoice: "female",
  englishSentence: "This project is likely to finish early.",
  // 10語以内で"be likely to"を自然に含め、プロジェクトが早く終わりそうだという意味になっているためルールに沿っています。
  japaneseSentence: "このプロジェクトは早く終わりそうです。",
  // 不自然なカタカナ語は避け、自然な日本語訳にしています。
  englishReply: "Oh, that means we may have extra time.",
  // "may have extra time"で早く終わりそう＝余裕ができそう、と推測できるヒントになっています。
  japaneseReply: "ああ、それなら時間に余裕ができそうですね。",
  // 英語の返答の内容を反映し、推測できる日本語訳にしています。
  scenePrompt: "企業の会議室で、マネージャーがチームメンバーに進行中のプロジェクトの進捗について話している。メンバーたちは計画よりも順調に進んでいることに驚いている。",
  // 会議室、登場人物、進捗の話題、周囲の雰囲気を具体的に説明しています。
  senderVoiceInstruction: "落ち着いたが少し嬉しそうなトーンで",
  receiverVoiceInstruction: "前向きで安心した様子で",
  incorrectOptions: [
    "このプロジェクトは予定より大幅に遅れそうです。",
    // 「早く終わりそう」と反対の「遅れそう」を使い、真逆の意味にしています。
    "今夜は会議室でピザパーティーを開きましょう！",
    // ばかばかしい内容として唐突なピザパーティーの提案にしています。
    "資料はすべて明日までに提出してください。",
    // 「このプロジェクトは早く終わりそう」とは異なる単なる指示文で、文頭も異なります。
  ]
},
{
  place: "会社の受付",
  senderRole: "受付スタッフ",
  senderVoice: "female",
  receiverRole: "ビジター",
  receiverVoice: "male",
  englishSentence: "Please sign in accordance with the policy.",
  // 10語以内で"in accordance with"を自然に含み、方針に従ってサインしてくださいという依頼文になっています。
  japaneseSentence: "方針に従ってご署名をお願いします。",
  // 方針＝policyで自然な訳です。カタカナ語を避けています。
  englishReply: "Sure, I will follow the company rules.",
  // 方針＝ルールと考えれば、"follow the company rules"で推測しやすいヒントになっています。
  japaneseReply: "はい、会社のルールに従います。",
  // 英語の返答内容を反映した自然な日本語です。
  scenePrompt: "大手企業の受付カウンター。来客が訪問者名簿への記入を求められ、受付スタッフが会社の規則に従うよう丁寧に説明している。",
  // 場所、登場人物、背景、雰囲気を具体的に説明しています。
  senderVoiceInstruction: "丁寧で事務的な話し方",
  receiverVoiceInstruction: "礼儀正しく少し緊張した声で",
  incorrectOptions: [
    "安全のために検温をお願いします。",
    // 文頭・内容ともに異なり、受付スタッフが言いそうな別の指示文です。
    "今日は会社の屋上で動物園を開いています！",
    // ばかばかしい内容として、会社で動物園を開いているという非現実的な発言です。
    "方針を完全に無視しても大丈夫です。",
    // 正解文と真逆の意味の「無視しても大丈夫」を使っています。
  ]
},
{
  place: "クライアントのオフィス",
  senderRole: "営業担当",
  senderVoice: "male",
  receiverRole: "クライアント",
  receiverVoice: "female",
  englishSentence: "I'm speaking on behalf of my team.",
  // 10語以内で"on behalf of"を自然に含み、「チームを代表して話しています」という意味を表現しています。
  japaneseSentence: "私はチームを代表して発言しています。",
  // カタカナ語を使わず、「代表して」と自然な日本語訳になっています。
  englishReply: "Thank you for conveying your team's opinion.",
  // チームの意見を伝えてくれてありがとう、という返答で内容が推測できます。
  japaneseReply: "チームの意見を伝えてくださりありがとうございます。",
  // 英語の返答の内容を反映し、推測しやすい日本語です。
  scenePrompt: "クライアント企業の会議室で、営業担当者が自社チームを代表して先方と交渉している場面。真剣な話し合いが行われている。",
  // 場所、登場人物、交渉の場面を具体的に説明しています。
  senderVoiceInstruction: "自信があり丁寧なトーンで",
  receiverVoiceInstruction: "感謝を込めて落ち着いた声で",
  incorrectOptions: [
    "私は今日の会議に全く興味がありません。",
    // 文頭・内容ともに異なり、営業担当として不適切な馬鹿馬鹿しい発言です。
    "あなたのチームの代わりに私が話しています。",
    // 「私はチームを代表して」と真逆の意味になる内容です。
    "この件については後ほどメールします。",
    // 文頭も内容も異なり、別の発言になっています。
  ]
}
];

export default problemData;
