import { SeedProblemData } from '../src/types/problem';

const problems: SeedProblemData[] = [
  {
    place: 'ホテルのフロント',
    senderRole: '宿泊客',
    senderVoice: 'male',
    receiverRole: 'フロントスタッフ',
    receiverVoice: 'female',
    englishSentence: 'Could I extend my stay here for another two nights?',
    japaneseSentence: 'こちらでもう二泊延長できますか？',
    englishReply: 'Yes, we still have rooms available for those nights.',
    japaneseReply: 'はい、その日程でしたらまだ空室がございます。',
    incorrectOptions: [
      '部屋に金庫はありますか？',
      '朝食が付いているかどうか教えていただけますか？',
      'チェックアウトの時間を少し延ばせますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '空港のチェックインカウンター',
    senderRole: '乗客',
    senderVoice: 'female',
    receiverRole: '係員',
    receiverVoice: 'male',
    englishSentence:
      'Could you confirm if my luggage will be checked through to my final destination?',
    japaneseSentence: '荷物が最終目的地まで運ばれるか確認していただけますか？',
    englishReply: 'Yes, your bag will go directly to your last stop.',
    japaneseReply: 'はい、お荷物は最終目的地まで直行します。',
    incorrectOptions: [
      '手荷物を機内に持ち込めますか？',
      '搭乗ゲートはどこですか？',
      '荷物に追加料金が必要ですか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: 'レストランのテーブル',
    senderRole: '客',
    senderVoice: 'male',
    receiverRole: 'ウェイター',
    receiverVoice: 'female',
    englishSentence:
      'Can you make sure my dish is prepared without any nuts? I have a strong allergy.',
    japaneseSentence: '強いアレルギーがあるので、料理にナッツを入れないでいただけますか？',
    englishReply: 'Of course, I’ll tell the chef to avoid nuts completely.',
    japaneseReply: 'もちろんです、ナッツは一切使わないよう伝えます。',
    incorrectOptions: [
      '料理に乳製品を入れないようお願いできますか？',
      'ソースを別にしてもらえますか？',
      '辛さを控えめにしていただけますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '会社の会議室',
    senderRole: '上司',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence:
      'I’d like you to prepare a report on recent sales trends and customer feedback.',
    japaneseSentence: '最近の売上動向と顧客の声をまとめた報告書を用意してください。',
    englishReply: 'Understood, I’ll prepare a detailed report by tomorrow.',
    japaneseReply: '承知しました、明日までに詳しい報告書を作成します。',
    incorrectOptions: [
      '競合他社の動向をまとめた資料を準備してもらえますか？',
      '新しい企画案を来週までに提出してください。',
      '経費の明細を整理した表を作成してください。',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '学校の教室',
    senderRole: '教師',
    senderVoice: 'male',
    receiverRole: '生徒',
    receiverVoice: 'female',
    englishSentence: 'Could you explain in your own words what the main idea of this paragraph is?',
    japaneseSentence: 'この段落の主な内容を自分の言葉で説明してください。',
    englishReply: 'Alright, it’s mainly about the causes of pollution.',
    japaneseReply: 'はい、主に公害の原因について書かれています。',
    incorrectOptions: [
      'この段落のキーワードを三つ答えてください。',
      '次の段落の内容を予想して説明してください。',
      'この文章の要約を二行で書いてください。',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '病院の診察室',
    senderRole: '医者',
    senderVoice: 'female',
    receiverRole: '患者',
    receiverVoice: 'male',
    englishSentence: 'When did the pain start, and how has it changed over the last few days?',
    japaneseSentence: '痛みがいつ始まって、この数日でどう変化したのか教えていただけますか？',
    englishReply: 'It started on Monday and has been getting worse.',
    japaneseReply: '月曜日から始まって、どんどん悪化しています。',
    incorrectOptions: [
      '薬を飲んでから痛みが減ったか教えてください。',
      '頭痛がどの時間帯に出るのか話してください。',
      '今までに同じ症状があったか教えてください。',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '映画館のチケットカウンター',
    senderRole: '客',
    senderVoice: 'male',
    receiverRole: 'スタッフ',
    receiverVoice: 'female',
    englishSentence: 'Are there still any seats available in the middle rows for tonight’s show?',
    japaneseSentence: '今日の夜の上映で真ん中の列に空席はありますか？',
    englishReply: 'Yes, there are still a few seats left in the middle.',
    japaneseReply: 'はい、真ん中の席が少し残っています。',
    incorrectOptions: [
      '一番前の席が空いているか確認してもらえますか？',
      '次の上映時間が何時か教えていただけますか？',
      '字幕付きかどうか確認していただけますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '銀行の窓口',
    senderRole: '客',
    senderVoice: 'female',
    receiverRole: '銀行員',
    receiverVoice: 'male',
    englishSentence:
      'Could you explain how to transfer money internationally and what the fees are?',
    japaneseSentence: '海外送金の方法と手数料について教えていただけますか？',
    englishReply: 'Yes, I’ll explain the steps and costs to you now.',
    japaneseReply: 'はい、手順と費用を今ご説明します。',
    incorrectOptions: [
      '口座を開設する方法を教えていただけますか？',
      '残高証明書の発行方法を説明してください。',
      '定期預金の利率を教えていただけますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '図書館の受付',
    senderRole: '利用者',
    senderVoice: 'male',
    receiverRole: '司書',
    receiverVoice: 'female',
    englishSentence: 'Can this book be renewed again, or do I have to return it by tomorrow?',
    japaneseSentence:
      'この本をもう一度延長できるのか、それとも明日までに返さないといけないのか教えてください。',
    englishReply: 'You need to return it tomorrow, renewals aren’t allowed.',
    japaneseReply: '明日までに返却が必要で、延長はできません。',
    incorrectOptions: [
      'この本を予約することは可能ですか？',
      '電子書籍の貸出はありますか？',
      'この本は他館から取り寄せできますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: 'カフェのカウンター',
    senderRole: '客',
    senderVoice: 'female',
    receiverRole: '店員',
    receiverVoice: 'male',
    englishSentence:
      'Could you make this coffee extra hot? It usually gets cold very quickly for me.',
    japaneseSentence: 'このコーヒーを特に熱くしてもらえますか？いつもすぐ冷めてしまうので。',
    englishReply: 'Of course, I’ll make sure it’s very hot this time.',
    japaneseReply: 'もちろんです、今回は熱めにお作りします。',
    incorrectOptions: [
      'ミルクを多めにしていただけますか？',
      '砂糖を控えめにしていただけますか？',
      '氷なしで作っていただけますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: 'ホテルのフロント',
    senderRole: '宿泊客',
    senderVoice: 'female',
    receiverRole: 'フロントスタッフ',
    receiverVoice: 'male',
    englishSentence: 'Is breakfast included in the room rate, or do I need to pay separately?',
    japaneseSentence: '宿泊料金に朝食が含まれているのか、別料金なのか教えていただけますか？',
    englishReply: 'Breakfast is included, you don’t need to pay extra.',
    japaneseReply: '朝食は含まれておりますので追加料金は不要です。',
    incorrectOptions: [
      'チェックインは何時からできますか？',
      '部屋に冷蔵庫がありますか？',
      'ランドリーサービスはありますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '空港の搭乗ゲート',
    senderRole: '乗客',
    senderVoice: 'male',
    receiverRole: '係員',
    receiverVoice: 'female',
    englishSentence:
      'Does this boarding pass allow me to bring both a carry-on and a personal bag?',
    japaneseSentence: 'この搭乗券で機内持ち込み荷物と手荷物を両方持って入れますか？',
    englishReply: 'Yes, one carry-on and one personal item are allowed.',
    japaneseReply: 'はい、手荷物と小物の二点は持ち込み可能です。',
    incorrectOptions: [
      '搭乗開始は何時からですか？',
      '預け荷物の料金はいくらですか？',
      '座席を変更できますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: 'レストランの入り口',
    senderRole: '客',
    senderVoice: 'female',
    receiverRole: 'ホスト',
    receiverVoice: 'male',
    englishSentence: 'How long is the wait for a table for four without a reservation tonight?',
    japaneseSentence: '今夜予約なしで四人席を待つ場合、どのくらいかかりますか？',
    englishReply: 'It’ll be about thirty minutes for a table.',
    japaneseReply: 'お席まで三十分ほどお待ちいただきます。',
    incorrectOptions: [
      '二人席ならどれくらいで案内できますか？',
      '窓際の席は空いていますか？',
      'テラス席は使えますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '学校の教室',
    senderRole: '教師',
    senderVoice: 'male',
    receiverRole: '生徒',
    receiverVoice: 'female',
    englishSentence: 'Could you explain step by step how you solved this math problem?',
    japaneseSentence: 'その数学の問題を解いた手順を順番に説明してください。',
    englishReply: 'Okay, I started by dividing both sides by two.',
    japaneseReply: 'はい、まず両辺を二で割りました。',
    incorrectOptions: [
      '答えだけを簡単に言ってください。',
      '似た問題を黒板に書いて解いてみてください。',
      '次の問題を一緒に考えてみましょう。',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '病院の待合室',
    senderRole: '患者',
    senderVoice: 'female',
    receiverRole: '看護師',
    receiverVoice: 'male',
    englishSentence: 'How long will I need to wait before the doctor can see me this afternoon?',
    japaneseSentence: '今日の午後、先生に診てもらうまでどのくらい待ちますか？',
    englishReply: 'It should be about twenty minutes from now.',
    japaneseReply: 'あと二十分ほどで診察に呼ばれると思います。',
    incorrectOptions: [
      '受付で支払いを先にしますか？',
      '診察券を持ってきた方がいいですか？',
      '薬はここでもらえますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '図書館の受付',
    senderRole: '利用者',
    senderVoice: 'male',
    receiverRole: '司書',
    receiverVoice: 'female',
    englishSentence: 'Can I borrow this magazine, or is it only for reading inside?',
    japaneseSentence:
      'この雑誌は借りられるのか、それとも館内だけで読むものなのか教えていただけますか？',
    englishReply: 'Magazines are only for in-library use, not for borrowing.',
    japaneseReply: '雑誌は館内閲覧専用で貸出はできません。',
    incorrectOptions: [
      '新聞は借りられますか？',
      '延長はどのくらい可能ですか？',
      'コピーはできますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: 'スーパーのレジ',
    senderRole: '客',
    senderVoice: 'female',
    receiverRole: 'レジ係',
    receiverVoice: 'male',
    englishSentence: 'Can I use both a coupon and a point card for this purchase?',
    japaneseSentence: 'この買い物でクーポンとポイントカードを両方使えますか？',
    englishReply: 'Yes, you can use both together for this purchase.',
    japaneseReply: 'はい、今回は両方一緒にご利用いただけます。',
    incorrectOptions: [
      'クレジットカードは使えますか？',
      '電子マネーは使えますか？',
      '領収書を発行していただけますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '銀行のATM前',
    senderRole: '利用客',
    senderVoice: 'male',
    receiverRole: '銀行員',
    receiverVoice: 'female',
    englishSentence: 'I forgot my PIN. How can I reset it on this machine?',
    japaneseSentence:
      '暗証番号を忘れてしまったので、この機械でリセットする方法を教えていただけますか？',
    englishReply: 'You can’t reset it here, please apply at the counter.',
    japaneseReply: 'こちらではできませんので窓口でお手続きください。',
    incorrectOptions: [
      '通帳を再発行できますか？',
      'キャッシュカードの有効期限を確認したいです。',
      '振込手数料を教えていただけますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: 'カフェのカウンター',
    senderRole: '店員',
    senderVoice: 'female',
    receiverRole: '客',
    receiverVoice: 'male',
    englishSentence: 'Would you like your latte with regular milk, or almond or soy milk?',
    japaneseSentence: 'ラテは普通の牛乳にしますか、それともアーモンドか豆乳にしますか？',
    englishReply: 'Soy milk would be great, thank you.',
    japaneseReply: '豆乳でお願いします、ありがとうございます。',
    incorrectOptions: ['サイズを大きくしますか？', '氷を入れますか？', '砂糖を加えますか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
  {
    place: '公園のベンチ',
    senderRole: '友人',
    senderVoice: 'female',
    receiverRole: '友人',
    receiverVoice: 'male',
    englishSentence:
      'Do you remember the last trip we took together and how much fun we had at the beach?',
    japaneseSentence: '一緒に旅行に行ったとき、海でとても楽しかったのを覚えてる？',
    englishReply: 'Yeah, that was one of the best trips ever.',
    japaneseReply: 'うん、本当に最高の旅行だったよ。',
    incorrectOptions: [
      '今度の週末にどこか行かない？',
      '新しい本を読んだことを覚えてる？',
      '先週の映画のことは覚えてる？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
  },
];

export default problems;
