import { SeedProblemData } from '../src/types/problem';

/**
 * 問題データ 9
 * Generated by GPT API (6 problems)
 */
const problemData: SeedProblemData[] = [
  {
    place: '法律事務所の会議室',
    senderRole: '弁護士',
    senderVoice: 'female',
    receiverRole: '依頼人',
    receiverVoice: 'male',
    englishSentence: 'This is a breach of contract.',
    // 8語以内、直訳で意味が取れる構文。TOEICで頻出の法務単語を自然に会話で使用。
    // "breach of contract" の意味が分かれば直訳で理解できる。
    japaneseSentence: 'これは契約違反です。',
    // "This is a breach of contract." の自然な訳。短く明確。
    englishReply: 'Oh, I understand. Thank you.',
    // 依頼人が納得して感謝を伝える自然な返答。簡単な語彙だけ。
    japaneseReply: 'ああ、分かりました。ありがとうございます。',
    // "I understand"の直訳＋感謝表現。中学レベル。
    scenePrompt:
      '依頼人が自分の契約書について弁護士に相談している。会議室には書類が広げられ、弁護士は冷静に説明している。依頼人は契約内容に不安があり、専門用語について理解を求めている。',
    // 会話では説明されない職場の雰囲気や、相談の動機、書類の状況を具体的に描写。
    senderVoiceInstruction: '落ち着いた、プロフェッショナルで明瞭な話し方',
    receiverVoiceInstruction: 'やや緊張しつつも納得した様子で',
    incorrectOptions: [
      // すべて8～12文字程度でバラつきを持たせている。
      // 1つめ: 馬鹿馬鹿しい選択肢
      '当事務所の弁護士は全員宇宙人です。',
      // 2つめ: 真逆の内容の選択肢（契約違反→契約順守）
      'これは契約は守られています。',
      // 3つめ: ランダムな自然な誤答
      'この内容は再度ご確認が必要です。',
    ],
  },
  {
    place: 'IT企業の会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'male',
    receiverRole: 'チームメンバー',
    receiverVoice: 'female',
    englishSentence: 'We may consider a full buyout.',
    // 8語以内、熟語「buyout」を自然に使用。TOEICに頻出しつつ日本人に馴染みが薄い。
    japaneseSentence: '完全買収も検討するかもしれません。',
    // 「buyout」を「完全買収」と自然に訳している。直訳ではなく自然な日本語。
    englishReply: 'Okay, I will keep that in mind.',
    // 日常的な返答。熟語ではなく簡単な表現。
    japaneseReply: '分かりました、覚えておきます。',
    // "keep that in mind"の自然な訳。短め。
    scenePrompt:
      '企業買収を議題とした重要なミーティング中。複数の選択肢を議論し、プロジェクトマネージャーが今後の方針について発言している。チームメンバーは新しい提案に注意を払っている。',
    // 会議の緊張感や議題の背景、メンバーの反応を描写。
    senderVoiceInstruction: '冷静で論理的、ややフォーマルな口調',
    receiverVoiceInstruction: '真剣で前向きな姿勢、適度に丁寧',
    incorrectOptions: [
      // 全て10～14文字程度でバラバラにしている。
      // 1つめ: 馬鹿馬鹿しい選択肢
      '社内全員でカレー大会を始めましょう。',
      // 2つめ: 真逆の内容（買収しない）
      '完全買収は全く考えていません。',
      // 3つめ: ランダムな自然な誤答
      'この提案について本社に確認します。',
    ],
  },
  {
    place: '銀行のカウンター前',
    senderRole: '銀行員',
    senderVoice: 'female',
    receiverRole: '顧客',
    receiverVoice: 'male',
    englishSentence: 'Do you have any collateral with you?',
    // 8語以内、熟語「collateral」を使った疑問文。日本人が苦手な表現。
    japaneseSentence: '担保はお持ちですか？',
    // "collateral"を「担保」と自然に訳し、短く分かりやすい疑問文。
    englishReply: 'No, I don’t have anything now.',
    // シンプルな否定。熟語なし。
    japaneseReply: 'いいえ、今は何も持っていません。',
    // "I don't have anything now." の直訳。
    scenePrompt:
      '顧客がローンの申し込みに来ている銀行のカウンター。銀行員が手続きに必要な書類や担保の有無を丁寧に確認している。顧客は少し戸惑いながらも対応している。',
    // 銀行の雰囲気とローン申請時のやりとりを具体的に描写。
    senderVoiceInstruction: '丁寧で親切、落ち着いたトーン',
    receiverVoiceInstruction: 'やや困惑しつつも誠実な話し方',
    incorrectOptions: [
      // 9～13文字程度、文頭を全て変えている。
      // 1つめ: 馬鹿馬鹿しい選択肢
      '今朝、空飛ぶ豚を見ましたか？',
      // 2つめ: 真逆の内容（担保がある→担保がない）
      '担保は必要ありません。',
      // 3つめ: ランダムな誤答
      '申請書はすでに提出しています。',
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '部長',
    senderVoice: 'male',
    receiverRole: '社員',
    receiverVoice: 'female',
    englishSentence: 'We must comply with regulations.',
    // 8語以内で "comply with regulations" を自然に含んだ、直訳系ではなく慣用句系のセリフです。会議の場面として自然です。
    japaneseSentence: '規則を順守しなければなりません。',
    // "We must comply with regulations." の自然な日本語訳。直訳ではなく、日本語として自然な表現を採用しています。
    englishReply: 'Yes, I understand. Thank you.',
    // 簡単な単語のみで、意味が分かれば日本人にも理解できる返答です。
    japaneseReply: 'はい、分かりました。ありがとうございます。',
    // "Yes, I understand. Thank you." を自然な日本語訳にしています。
    scenePrompt:
      '大手企業の会議室で、部長が新しい業務手順について説明し、規則を守る必要性を強調しています。部屋にはホワイトボードや資料があり、社員たちは真剣な表情で話を聞いています。',
    // 英語・日本語訳に含まれていない、場所や状況、登場人物の立場などを具体的に記述しています。
    senderVoiceInstruction: '落ち着いていて威厳のある、誠実なトーンで話す',
    receiverVoiceInstruction: '丁寧で真面目なトーン、やや緊張気味',
    incorrectOptions: [
      '今後は法律を無視して行動します。',
      // "規則を順守しなければなりません。"の真逆の意味になっています。
      'ピザを食べながらダンスする規則が追加されました。',
      // 馬鹿馬鹿しい内容で、現実にありえない提案になっています。
      '新しいルールは一切存在しません。',
      // "規則を順守しなければなりません。"とは異なる内容、かつ文頭が異なります。
    ],
  },
  {
    place: 'プロジェクトの作業場',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'エンジニア',
    receiverVoice: 'male',
    englishSentence: 'Do we have a contingency plan ready?',
    // 8語以内で "contingency plan" を使った疑問文。プロジェクト現場で自然な表現。
    japaneseSentence: '万が一の対応策は用意できていますか？',
    // "Do we have a contingency plan ready?" の自然な日本語訳。日本語で使われる自然な言い回しです。
    englishReply: 'Yes, we finished it yesterday.',
    // 簡単な単語かつ直訳で理解できる内容です。
    japaneseReply: 'はい、昨日仕上げました。',
    // "Yes, we finished it yesterday." の自然な日本語訳です。
    scenePrompt:
      'IT企業の作業現場で、プロジェクトマネージャーが進行中のシステム開発においてリスク管理を確認しています。エンジニアたちはパソコンの前で作業しています。',
    // 会話の内容に登場しない場面設定や状況、雰囲気を具体的に説明。
    senderVoiceInstruction: '頼もしく、自信に満ちた明るい声で',
    receiverVoiceInstruction: 'カジュアルで親しみやすいが、少し誇らしげに',
    incorrectOptions: [
      'この計画は何も準備していません。',
      // "万が一の対応策は用意できていますか？"とは真逆の意味を持つ内容。
      '象が空を飛ぶための計画もあります。',
      // 馬鹿馬鹿しい内容で、現実的ではありません。
      'メンバー全員が既に出発しています。',
      // 本文と異なる内容で、なおかつ文頭も異なります。
    ],
  },
  {
    place: 'ビジネスセミナー会場',
    senderRole: '講師',
    senderVoice: 'male',
    receiverRole: '参加者',
    receiverVoice: 'female',
    englishSentence: 'Let’s discuss corporate governance today.',
    // 8語以内で "corporate governance" を使い、講師の提案口調として自然な文です。
    japaneseSentence: '今日は企業統治について話しましょう。',
    // "Let’s discuss corporate governance today." の自然な日本語訳で、日本語として自然な流れです。
    englishReply: "That sounds interesting. I'm looking forward.",
    // 簡単な単語と構文のみで、理解しやすい返答です。
    japaneseReply: '面白そうですね。楽しみにしています。',
    // "That sounds interesting. I'm looking forward." の自然な日本語訳です。
    scenePrompt:
      '大きな会議室で多くのビジネスパーソンが集まる中、講師がセミナーの冒頭で今日のテーマについて話し始めています。参加者たちはメモを取りながら熱心に耳を傾けています。',
    // 会話に含まれない、場所・雰囲気・登場人物の行動を具体的に説明。
    senderVoiceInstruction: 'はっきりと自信のある、情熱的な話し方',
    receiverVoiceInstruction: '柔らかく明るい、前向きなトーン',
    incorrectOptions: [
      '明日は動物園について語りましょう。',
      // "今日は企業統治について話しましょう。"と真逆の内容。
      '巨大ロボットの操縦方法を教えます。',
      // 馬鹿馬鹿しく現実離れした内容。
      '参加者全員に新しい規則を配布します。',
      // 本文と違うが、自然な文頭・内容となっています。
    ],
  },
];

export default problemData;
