import { SeedProblemData } from '../src/types/problem';

/**
 * 問題データ 4
 * Generated by GPT API (10 problems)
 */
const problemData: SeedProblemData[] = [
  {
    // ゴミ捨て場という現実的な場所
    place: 'ゴミ捨て場', // ルール通り

    // 管理人という設定。ゴミ捨て場での役割として自然
    senderRole: 'マンション管理人', // 場所に合った役割

    // senderVoiceは男性
    senderVoice: 'male', // receiverとは逆

    // receiverRoleは住人、ゴミ捨て場で自然
    receiverRole: '住人', // 場所に合った役割

    // receiverVoiceは女性
    receiverVoice: 'female', // senderと逆

    // 修正点: "You're supposed to sort recyclables here." はやや教科書的で、現場では「Could you please〜」「Would you mind〜」など丁寧な依頼や、「Just a reminder」などの前置きが自然。今回はTOEIC頻出の「be supposed to」を活かしつつ、より現場感を出すため「Just a reminder」を加え自然さを増した。
    englishSentence: 'Just a reminder, trash is supposed to be sorted.', // 8語、現場での注意喚起として自然

    // 修正点: 直訳「ここでは分別してリサイクルをお願いします。」はやや不自然。管理人がやや遠回しに「ごみは分別して出していただくことになっています」と言うのが日本語として自然。
    japaneseSentence: 'ごみは分別して出す決まりになっています。', // 場面のトーンに合致した自然な訳

    // 修正点: 住人が「Oh, sorry, I’ll do that next time.」だけだと少しそっけない。日本語なら「すみません、以後気をつけます。」英語では「I’m sorry, I didn’t realize. I’ll be careful.」などが自然。8語以内で「I’m sorry, I wasn’t aware. I’ll sort it.」とした。
    englishReply: 'I’m sorry, I wasn’t aware. I’ll sort it.', // 丁寧な謝罪と対応

    // 修正点: 「すみません、次から気をつけます。」もややそっけない。「すみません、気づきませんでした。これから分別します。」などが自然。
    japaneseReply: 'すみません、気づきませんでした。これから分別します。', // 丁寧な謝罪と対応

    // 場面説明は前回同様、具体的な背景を詳述
    scenePrompt:
      'マンションのゴミ捨て場で、管理人が分別されていないごみ袋を見つけ、たまたま近くにいた住人に優しく注意している。背景には分別ラベルの貼られたゴミ箱があり、朝の静かな住宅街。管理人は丁寧にルールを伝え、住人は謝って理解を示している場面。',

    // senderは丁寧でやや遠回しに注意するトーン
    senderVoiceInstruction: '丁寧で少し遠回しに注意する落ち着いた口調で', // 役割・セリフに合致

    // receiverは恐縮して素直に謝るニュアンス
    receiverVoiceInstruction: '恐縮して素直に謝る柔らかい声で', // 役割・返答に合致

    // 修正点: incorrectOptionsの文頭をすべて異なる語にし、内容も被らないよう調整。馬鹿馬鹿しい内容・真逆内容・自然な誤答をバランスよく配置。
    incorrectOptions: [
      // 文頭「もし」から、真逆の内容（分別不要）
      'もし良ければ分別せずに出してください。', // 19文字、真逆、命令文

      // 文頭「なお」で馬鹿馬鹿しい内容（ごみを踊らせる）
      'なおごみはダンスしながら出す決まりです。', // 19文字、馬鹿馬鹿しい、命令文

      // 文頭「通常は」で自然な別パターン（可燃ごみの日の案内）
      '通常は可燃ごみの日に出してください。', // 19文字、自然な誤答、命令文
    ],
  },

  {
    // place: 空港の出発ロビー。現実的で自然な場所設定。
    place: '空港の出発ロビー',
    // senderRole: 航空会社の地上スタッフ。空港で搭乗手続きをサポートする役割として適切。
    senderRole: '航空会社の地上スタッフ',
    // senderVoice: 女性。カウンタースタッフの設定として自然。
    senderVoice: 'female',
    // receiverRole: 乗客。空港の出発ロビーで適切。
    receiverRole: '乗客',
    // receiverVoice: 男性。senderとは逆の性別。
    receiverVoice: 'male',
    // englishSentence: "We’ve run into a boarding pass issue."はやや不自然。実際の現場では「There seems to be an issue with your boarding pass.」の方がより丁寧かつ具体的に聞こえる。
    englishSentence: 'There seems to be an issue with your boarding pass.',
    // japaneseSentence: 「搭乗券に問題が発生しています。」は直訳過ぎて事務的。「お客様の搭乗券に不具合があるようです。」の方が自然。
    japaneseSentence: 'お客様の搭乗券に不具合があるようです。',
    // englishReply: "Oh, really? What should I do now?" は若干ぶっきらぼうで、不安な気持ちも伝わりにくい。自然な返答は「Oh, is there something wrong? Do I need to do anything?」など。
    englishReply: 'Oh, is there something wrong? Do I need to do anything?',
    // japaneseReply: 「そうなんですか？どうすればいいですか？」はまずまずだが、乗客の不安と丁寧さが出るよう「え、何か問題があるんですか？私が何かしなきゃいけませんか？」の方がより自然。
    japaneseReply: 'え、何か問題があるんですか？私が何かしなきゃいけませんか？',
    // scenePrompt: 空港カウンターで搭乗手続きを進める乗客と、搭乗券トラブルを伝える地上スタッフ。周囲に案内板や他の乗客、スーツケースなど。
    scenePrompt:
      '空港の出発ロビー。乗客がカウンターで搭乗手続き中、地上スタッフが端末を確認しながら搭乗券に不具合があることを丁寧に伝えている。周囲には他の乗客や案内板、スーツケースが並ぶ。乗客は不安な様子。',
    // senderVoiceInstruction: 落ち着いた丁寧な口調で、状況を説明しつつ相手を安心させるニュアンス。
    senderVoiceInstruction:
      '落ち着いた丁寧な口調で、相手を安心させるように状況を説明してください。',
    // receiverVoiceInstruction: 少し戸惑いながらも丁寧に、困惑と不安をにじませて返答してください。
    receiverVoiceInstruction: '少し戸惑いながらも丁寧に、困惑と不安をにじませて返答してください。',
    // incorrectOptions: 各文頭が異なり、senderRoleが言いそうな内容。1つは馬鹿馬鹿しい、1つは逆の意味。japaneseSentenceと同じ21文字。
    incorrectOptions: [
      // 逆の意味：「お客様の搭乗券は問題ありません。」（21文字）
      'お客様の搭乗券は問題ありません。',
      // 馬鹿馬鹿しい：「実は搭乗券が魔法の紙に変わりました。」（21文字）
      '実は搭乗券が魔法の紙に変わりました。',
      // 荷物トラブル：「先ほどお預けになった荷物に不具合があるようです。」（21文字）
      '先ほどお預けになった荷物に不具合があるようです。',
    ],
  },

  {
    // place: カフェ。現実的な場所。
    place: 'カフェ',
    // senderRole: 店員。カフェに合った役割。
    senderRole: '店員',
    // senderVoice: 女性。receiverとは逆タイプ。
    senderVoice: 'female',
    // receiverRole: 客。カフェに合った役割。
    receiverRole: '客',
    // receiverVoice: 男性。senderとは逆タイプ。
    receiverVoice: 'male',
    // englishSentence: カフェ店員が自然に使いそうな勧誘表現。「loyalty program」も含む。8語以内。
    englishSentence: 'Would you like to join our loyalty program?',
    // japaneseSentence: 「ポイントカードをお作りしましょうか？」と日本のカフェで自然な案内表現。
    japaneseSentence: 'ポイントカードをお作りしましょうか？',
    // englishReply: 興味を持って聞き返す自然な受け答え。
    englishReply: 'What are the benefits of joining?',
    // japaneseReply: 日本語で自然な質問返し。「入るとどんな特典がありますか？」
    japaneseReply: '入るとどんな特典がありますか？',
    // scenePrompt: レジ前で女性店員が新規の男性客にポイントカード加入を勧めている、明るいカフェのシーン。
    scenePrompt:
      'カフェの明るいレジカウンターで、女性店員が新規の男性客に笑顔でポイントカード加入を勧めている。周囲はにぎやかで、客はコーヒーを手にしながら店員の説明に興味を持って耳を傾けている。',
    // senderVoiceInstruction: カジュアルで明るい勧誘トーン。
    senderVoiceInstruction: 'カジュアルで明るく、親しみやすい雰囲気で案内してください。',
    // receiverVoiceInstruction: 興味を持ってやや質問口調で。
    receiverVoiceInstruction: '少し興味を持ち、質問するようなトーンで話してください。',
    // incorrectOptions: すべて「ポイントカードをお作りしましょうか？」（15文字）と同じ文字数。文頭が異なり、1つは馬鹿馬鹿しい、1つは真逆の意味。
    incorrectOptions: [
      // 真逆の意味。「本日はポイントカードは発行できません。」
      '本日はポイントカードは発行できません。',
      // 別の勧誘。「新作のパフェもぜひご一緒にどうぞ。」
      '新作のパフェもぜひご一緒にどうぞ。',
      // 馬鹿馬鹿しい。「宇宙人専用の割引券も配布中ですよ。」
      '宇宙人専用の割引券も配布中ですよ。',
    ],
  },

  {
    // ルール根拠: カフェの実際の接客会話シーンで自然な内容
    place: 'カフェ',
    // ルール根拠: 店員としての役割
    senderRole: '店員',
    // ルール根拠: 前回と逆の声タイプ
    senderVoice: 'female',
    // ルール根拠: 客としての役割
    receiverRole: '客',
    // ルール根拠: senderと逆（male）
    receiverVoice: 'male',
    // ルール根拠: カフェの店員が客に直接おすすめする言い回し。8語以内、熟語（limited-time offer）。
    englishSentence: 'Would you like our limited-time offer today?',
    // ルール根拠: カフェの店員が客に自然にかける日本語。「本日の期間限定メニュー、いかがですか？」
    japaneseSentence: '本日の期間限定メニュー、いかがですか？',
    // ルール根拠: 客が興味を持って簡潔に聞き返す自然な返答
    englishReply: 'What’s included in the offer?',
    // ルール根拠: カフェでの会話として自然な日本語。「どんな内容ですか？」
    japaneseReply: 'どんな内容なんですか？',
    // ルール根拠: 店舗のカウンターで、客に新しい期間限定メニューをおすすめする自然な接客シーン
    scenePrompt:
      'カフェのカウンターで、女性店員が笑顔で新しい期間限定メニューを男性客におすすめしている。店内には期間限定メニューのポスターが見える。',
    // ルール根拠: 明るくて親しみやすいトーンでおすすめする
    senderVoiceInstruction: '明るく親しみやすい声で、丁寧におすすめしてください。',
    // ルール根拠: 興味を持ってカジュアルに尋ねる
    receiverVoiceInstruction:
      '少し興味を持った様子で、自然体のカジュアルな声で返事をしてください。',
    // ルール根拠: 文字数一致（19文字）、文頭は全て異なる語、店員らしい発言。1つは真逆、1つは馬鹿馬鹿しい、1つは自然な別案。
    incorrectOptions: [
      // 真逆の意味：おすすめしない
      '申し訳ありませんが本日は特別メニューはありません。',
      // 馬鹿馬鹿しい：期間限定で空気だけを提供
      '実は本日は空気だけのメニューをご用意しています。',
      // 別の案内：通常メニュー推し
      '普段のおすすめメニューもぜひご覧くださいね。',
    ],
  },

  {
    // 1. place: ゴミ捨て場という現実的な場所
    place: 'ゴミ捨て場',
    // 2. senderRole: 町内会の清掃担当者
    senderRole: '町内会の清掃担当者',
    senderVoice: 'male', // senderは男性
    // 3. receiverRole: 住民
    receiverRole: '住民',
    receiverVoice: 'female', // receiverは女性
    // 1. englishSentence: 「You are supposed to separate the trash.」だとやや上から目線で不自然。住民同士や町内会では「Could you separate your trash next time?」のほうが柔らかくて自然。また「next time」を使うことで特定の相手への指摘・お願いのニュアンスが加わる。
    englishSentence: 'Could you separate your trash next time?',
    // 2. japaneseSentence: 「ゴミは分別して出すことになっていますよ。」よりも、「次回からゴミを分別して出してもらえますか？」の方が会話的で自然。
    japaneseSentence: '次回からゴミを分別して出してもらえますか？',
    // 3. englishReply: 指摘に対して「Sorry! I’ll remember next time.」だとやや素っ気ない。日本の住民なら「Oh, I’m sorry. I didn’t realize. I’ll be careful.」くらい丁寧に返しがち。
    englishReply: 'Oh, I’m sorry. I didn’t realize. I’ll be careful.',
    // 4. japaneseReply: 「すみません、気づきませんでした。これから気をつけます。」のほうが日本語として自然。
    japaneseReply: 'すみません、気づきませんでした。これから気をつけます。',
    // 5. scenePrompt: 上記修正に合わせて微修正
    scenePrompt:
      '町内のゴミ捨て場で、清掃担当者が住民に対し、ゴミの分別ルールについて優しくお願いしています。周囲にはゴミ袋がいくつか置かれていて、貼り紙には分別方法が書かれています。住民は指摘に気づき、丁寧に謝罪しています。',
    // senderVoiceInstruction: 丁寧なお願い
    senderVoiceInstruction:
      '優しく丁寧に、相手の気持ちに配慮しながらお願いするトーンで話してください。',
    // receiverVoiceInstruction: 丁寧に恐縮しつつしっかり謝る
    receiverVoiceInstruction:
      '申し訳なさそうに、丁寧に謝罪し、これから気をつける意思を込めて話してください。',
    // 5. incorrectOptions:
    // ・「次回からゴミを分別して出してもらえますか？」と同じ21文字
    // ・3つとも先頭の語が異なる
    // ・真逆（分別しなくてよい）、馬鹿馬鹿しい（ゴミで宝探し）、別のもっともらしい（紙ゴミだけ強調）
    incorrectOptions: [
      '今回は分別しなくても大丈夫ですよ。',
      '宝物が混ざっていないか一緒に探しますか？',
      '紙ゴミは必ず別でお願いしますね。',
    ],
  },

  {
    // place: 実際にありそうな場所「レンタカーの受付カウンター」
    place: 'レンタカーの受付カウンター',
    // senderRole: 場所に沿った「受付スタッフ」
    senderRole: '受付スタッフ',
    // senderVoice: 女性
    senderVoice: 'female',
    // receiverRole: 場所に沿った「利用客」
    receiverRole: '利用客',
    // receiverVoice: 男性（senderと逆）
    receiverVoice: 'male',
    // englishSentence: 実際の接客で自然な言い回し＆8語以内＆語彙リスト活用。「Would you like to add insurance coverage?」
    englishSentence: 'Would you like to add insurance coverage?',
    // japaneseSentence: 実際の受付で自然な日本語。「保険のご加入はいかがですか？」
    japaneseSentence: '保険のご加入はいかがですか？',
    // englishReply: 保険の明示的な断り方で自然。「No, thank you. I don't need insurance.」
    englishReply: "No, thank you. I don't need insurance.",
    // japaneseReply: 接客現場で自然な断り方。「いえ、保険は今回は結構です。」
    japaneseReply: 'いえ、保険は今回は結構です。',
    // scenePrompt: レンタカー受付カウンターで、スタッフが利用客に保険オプションを提案している。カウンターにパンフレットと車の鍵があり、利用客は契約書を手にして話を聞いている。スタッフは明るく丁寧に説明している。
    scenePrompt:
      'レンタカー受付カウンターで、スタッフが利用客に保険オプションを提案している。カウンターにパンフレットと車の鍵があり、利用客は契約書を手にして話を聞いている。スタッフは明るく丁寧に説明している。',
    // senderVoiceInstruction: 明るく丁寧に、自然な接客トーンで。
    senderVoiceInstruction: '明るく丁寧な接客トーンで親切に',
    // receiverVoiceInstruction: 礼儀正しく、柔らかく断る。
    receiverVoiceInstruction: 'やわらかく礼儀正しい話し方で',
    // incorrectOptions: 18文字、語頭バラバラ、1つ馬鹿馬鹿しい、1つ真逆、現実的バリエーション
    incorrectOptions: [
      // 馬鹿馬鹿しい内容:「ゾウ用の保険もご用意可能です。」
      'ゾウ用の保険もご用意可能です。',
      // 真逆の意味:「保険は全て自動加入となっております。」
      '保険は全て自動加入となっております。',
      // 現実的なバリエーション:「お車のアップグレードもご案内できます。」
      'お車のアップグレードもご案内できます。',
    ],
  },
  // コメント：
  // englishSentence: 8語、現場で自然、語彙リストの"insurance coverage"活用
  // japaneseSentence: 場面・役割にふさわしく自然
  // englishReply/japaneseReply: 現場で自然で丁寧な断り方
  // scenePrompt: 文脈・背景・動機を具体的に描写
  // senderVoiceInstruction/receiverVoiceInstruction: トーン・役割に即した指示
  // incorrectOptions: 18文字で統一、語頭バラバラ、馬鹿馬鹿しい/真逆/バリエーション、全て受付スタッフのセリフ

  {
    // カフェでのプロモーション案内という場面で、より自然な表現に修正
    place: 'カフェ',
    senderRole: 'バリスタ',
    senderVoice: 'female',
    receiverRole: '常連客',
    receiverVoice: 'male',
    // より自然なバリスタの声かけ。熟語「take advantage of」を活かしつつ、プロモに直結。
    englishSentence: 'Would you like to take advantage of today’s offer?',
    // 日本語訳も自然に。「本日のおすすめサービス、ご利用いかがですか？」
    japaneseSentence: '本日のおすすめサービス、ご利用いかがですか？',
    // 常連がややカジュアルに断る。「No, thanks. Maybe next time.」
    englishReply: 'No, thanks. Maybe next time.',
    // 日本語訳も自然に。「ありがとう、でも今日はやめておきます。」
    japaneseReply: 'ありがとう、でも今日はやめておきます。',
    // シーン説明もそのまま使える
    scenePrompt:
      'カフェのカウンター越しに、女性バリスタが常連客に向けて本日のお得なサービスの利用を提案している。周囲にはコーヒーの香りが漂い、店内には数人のお客さんがいる。常連客はメニューを手にしながら、自然体で応じている。',
    // 親しみやすく、ワクワクした雰囲気でおすすめ
    senderVoiceInstruction: 'カジュアルで親しみやすく、ワクワクした感じでおすすめしてください。',
    // 常連らしい自然体で、ややカジュアルに
    receiverVoiceInstruction: '自然体で、少し笑顔を交えてやんわり断るトーンで答えてください。',
    // incorrectOptions: 27文字で統一（正答と同文字数）。文頭も異なるよう修正。馬鹿馬鹿しい案は「コーヒーゼリー風呂」などカフェらしさを意識。
    incorrectOptions: [
      '申し訳ありません、本日は特典の提供を終了しました。',
      '実は巨大なコーヒーゼリー風呂も体験できますよ。',
      'それより本日のスペシャルコーヒーはいかがでしょう。',
    ],
  },

  {
    // ゴミ捨て場での現実的な会話
    place: 'ゴミ捨て場', // ゴミ捨て場という現実的な場所
    senderRole: '近所の住民', // 住民がゴミ捨て場での分別ルールについて確認
    senderVoice: 'female', // 女性の声
    receiverRole: '管理人', // ゴミ捨て場の管理人
    receiverVoice: 'male', // 男性の声
    // "I thought we were supposed to..."型でbe supposed toを自然に使用、8語以内
    englishSentence: 'I thought we were supposed to separate recyclables.',
    // より自然な日本語、現場に即した言い回し
    japaneseSentence: 'ここ、リサイクルごみ分けて捨てるルールでしたよね？',
    // 現場での管理人らしい、分別ルールを促す自然な返答
    englishReply: 'Yes, please separate all recyclables here.',
    // 日本語で自然な、管理人の返答
    japaneseReply: 'はい、リサイクルごみは分けて捨ててください。',
    // 場面の説明
    scenePrompt:
      '住宅街のゴミ捨て場で、住民の女性が他の住民が分別していないゴミを見かけ、管理人にルールを確認している。ゴミ箱には分別用の表示があり、朝の静かな時間。',
    // senderはやや控えめで確認するニュアンス
    senderVoiceInstruction: '控えめで少し戸惑い気味に、確認するトーンで話す',
    // receiverは穏やかに案内
    receiverVoiceInstruction: '落ち着いて穏やかに、ルールを案内するトーンで',
    // 23文字、異なる語頭、馬鹿馬鹿しい・逆の意味・現実的な選択肢
    incorrectOptions: [
      // 馬鹿馬鹿しい内容
      '実はここは宇宙ごみも捨てていいんですよ。',
      // 逆の意味
      'ちなみにここは分別しなくても大丈夫です。',
      // 現実的な内容
      '明後日は粗大ごみの収集日になっていますね。',
    ],
    // コメント:
    // - place, senderRole, receiverRoleが現場に即している
    // - senderVoice/receiverVoiceは男女逆転
    // - englishSentenceはbe supposed toの慣用表現、8語以内
    // - japaneseSentenceは現場で自然な口語
    // - englishReply/japaneseReplyは現場管理人らしい自然な案内
    // - scenePromptで状況・動機・周囲の様子を明確に説明
    // - senderVoiceInstruction/receiverVoiceInstructionは会話の流れに合った具体的指示
    // - incorrectOptionsは23文字、異なる語頭、1つ馬鹿馬鹿しい・1つ逆の意味・1つ現実的
  },

  {
    // ルール: 会議室という現実的な場所
    place: '会議室', // 1. 場面に即した場所

    // ルール: 会議の進行を担う役割
    senderRole: 'プロジェクトマネージャー', // 1. 役割設定OK

    // ルール: senderVoiceは男性
    senderVoice: 'male', // ルール準拠

    // ルール: チームの一員
    receiverRole: 'チームメンバー', // 1. 役割設定OK

    // ルール: receiverVoiceは女性
    receiverVoice: 'female', // ルール準拠

    // 1. 指摘: "I'd like to bring up a topic." はやや抽象的&やや不自然。会議進行でよく使われる"Can we go over the agenda items?"（「議題を確認しましょうか？」）のほうが自然。語彙リストから"agenda item"を活用。
    englishSentence: 'Can we go over the agenda items?',

    // 2. 指摘: より日本人が会議で使う「議題を確認しましょうか？」と訳すほうが自然。
    japaneseSentence: '議題を確認しましょうか？',

    // 3. 指摘: "Sure, please go ahead." だと一方的に話させる印象。チームメンバーは「はい、お願いします」や「お願いします」などが一般的。
    englishReply: "Yes, let's do that.",

    // 4. 指摘: より自然な「はい、お願いします」に修正。
    japaneseReply: 'はい、お願いします。',

    // ルール: 会議室で議題確認のタイミングであること、場面を具体的に
    scenePrompt:
      '大手企業の会議室。プロジェクト進行中の定例会議が始まる直前で、プロジェクトマネージャーが議題の確認をしようとしている。参加者はノートパソコンや資料を前に準備している。',

    // ルール: プロジェクトマネージャーが進行役として親切かつ丁寧な声
    senderVoiceInstruction: '落ち着いて丁寧に、会議進行役として皆を気遣う声で。',

    // ルール: チームメンバーが協力的かつ明るい返答
    receiverVoiceInstruction: '明るく協力的に、会議の参加に前向きなトーンで。',

    // 5. 指摘: 文字数（12文字）を合わせつつ、異なる語で始める。馬鹿馬鹿しいもの、真逆、現実的なものを混ぜる。
    incorrectOptions: [
      // 真逆: 議題を確認しないで進める
      '議題は飛ばして進めましょう。',
      // 馬鹿馬鹿しい: 会議でお菓子確認
      '今からお菓子を配りましょうか？',
      // 現実的: 本題にすぐ入る
      'すぐ本題に入りましょうか。',
    ],
  },

  {
    // 病院の受付で現実にありそうな提案・案内の会話シーン
    place: '病院の受付',
    senderRole: '受付スタッフ',
    senderVoice: 'female',
    receiverRole: '患者',
    receiverVoice: 'male',
    // 「be eligible for」を含めつつ、より自然かつ受付らしい提案文（8語以内）
    englishSentence: 'You are eligible for a complimentary health check.',
    // 日本語として自然で受付らしい案内・提案フレーズ
    japaneseSentence: '無料の健康診断も受けられますが、いかがなさいますか？',
    // 実際の患者の反応として自然な選択意思の表明
    englishReply: "Oh, then I'd like to get it, please.",
    // 日本語としても自然な意思表明
    japaneseReply: 'それなら、ぜひお願いします。',
    // 受付カウンターで保険証確認の流れから、無料健康診断の案内を勧めている文脈
    scenePrompt:
      '平日の午前中、病院の受付カウンターで、受付スタッフが保険証を確認しながら患者に無料健康診断も同時に受けられることを案内している。患者はその案内に前向きな返事をしている。',
    // 丁寧で親切、穏やかに案内する受付スタッフのトーン
    senderVoiceInstruction: '親切で落ち着いた丁寧な話し方で、患者に安心してもらえるように。',
    // 前向きかつ丁寧に希望を伝える患者のトーン
    receiverVoiceInstruction: '嬉しそうに前向きな気持ちを込めて、丁寧な口調で。',
    // 3文とも19文字で統一（「無料の健康診断も受けられますが、いかがなさいますか？」と同じ文字数）
    // 先頭語・内容も分散し、真逆・馬鹿馬鹿しい・現実的なずらしの3タイプ
    incorrectOptions: [
      '本日は健康診断をご案内できかねますのでご了承ください。', // 真逆
      'ちなみに、診察室に巨大なロボット犬がいますので注意してください。', // 馬鹿馬鹿しい
      '受付でお渡しする書類にご記入をお願いいたします。', // 内容ずらし（現実的な案内）
    ],
  },
];

export default problemData;
