import { SeedProblemData } from '../src/types/problem';

const problems: SeedProblemData[] = [
  {
    place: 'カフェのカウンター',
    senderRole: 'カフェの客',
    senderVoice: 'female',
    receiverRole: 'カフェの店員',
    receiverVoice: 'male',
    englishSentence: 'Could you keep the change for yourself?',
    japaneseSentence: 'お釣りは取っておいてください。',
    englishReply: 'Sure, thank you very much for that.',
    japaneseReply: 'はい、ありがとうございます。',
    incorrectOptions: [
      'ポイントカードは使えますか？',
      'この席は空いていますか？',
      'テイクアウトもできますか？',
    ],
  },
  {
    place: 'レストランの入り口',
    senderRole: 'レストランの客',
    senderVoice: 'male',
    receiverRole: 'レストランの店員',
    receiverVoice: 'female',
    englishSentence: 'We’re a bit pressed for time, any quick dishes?',
    japaneseSentence: 'ちょっと時間がなくて、早く出せる料理ありますか？',
    englishReply: 'Yes, salads and pasta come out quickly.',
    japaneseReply: 'はい、サラダとパスタならすぐ出せますよ。',
    incorrectOptions: [
      '窓側の席は空いてますか？',
      '今日のおすすめは何ですか？',
      '予約なしでも大丈夫ですか？',
    ],
  },
  {
    place: '図書館の受付',
    senderRole: '学生',
    senderVoice: 'female',
    receiverRole: '司書',
    receiverVoice: 'female',
    englishSentence: 'Could you point me in the right direction for history books?',
    japaneseSentence: '歴史の本はどのあたりにありますか？',
    englishReply: 'Yes, they’re on the second floor to your left.',
    japaneseReply: 'はい、二階の左側にありますよ。',
    incorrectOptions: [
      '貸出は何冊まで可能ですか？',
      '雑誌はここで借りられますか？',
      'コピー機はどこにありますか？',
    ],
  },
  {
    place: '駅の改札前',
    senderRole: '旅行者',
    senderVoice: 'male',
    receiverRole: '駅員',
    receiverVoice: 'male',
    englishSentence: 'I’m totally lost, which line goes to Namba?',
    japaneseSentence: 'すっかり迷ってしまって、難波へはどの路線ですか？',
    englishReply: 'No worries, you can take the red line from here.',
    japaneseReply: '大丈夫ですよ、ここから赤い路線に乗れば行けます。',
    incorrectOptions: [
      '切符はここで買えますか？',
      'トイレは近くにありますか？',
      '次の急行は何時ですか？',
    ],
  },
  {
    place: '病院の待合室',
    senderRole: '患者',
    senderVoice: 'female',
    receiverRole: '受付スタッフ',
    receiverVoice: 'female',
    englishSentence: 'I’m feeling under the weather, do I need to wait long?',
    japaneseSentence: 'ちょっと体調が悪いんですが、待ち時間は長いですか？',
    englishReply: 'Not too long, about fifteen minutes.',
    japaneseReply: 'そんなに長くありませんよ、十五分ほどです。',
    incorrectOptions: [
      '診察券を忘れてしまいました。',
      '薬だけ先にもらえますか？',
      '会計はここでいいですか？',
    ],
  },
  {
    place: '銀行のATM前',
    senderRole: '利用客',
    senderVoice: 'male',
    receiverRole: '銀行員',
    receiverVoice: 'female',
    englishSentence: 'This machine seems out of order, what should I do?',
    japaneseSentence: 'この機械が壊れているみたいですが、どうすればいいですか？',
    englishReply: 'Please use the next one on the right side.',
    japaneseReply: '右側の機械をご利用ください。',
    incorrectOptions: [
      '振込手数料はいくらですか？',
      '両替はここでできますか？',
      '通帳記入はできますか？',
    ],
  },
  {
    place: '映画館のチケットカウンター',
    senderRole: '映画館の客',
    senderVoice: 'female',
    receiverRole: '映画館スタッフ',
    receiverVoice: 'male',
    englishSentence: 'Is there any chance to get seats together?',
    japaneseSentence: '一緒に座れる席はまだありますか？',
    englishReply: 'Yes, two seats are available in the back row.',
    japaneseReply: 'はい、後ろの列に二席空いています。',
    incorrectOptions: [
      'ポップコーンはここで買えますか？',
      '学生割引はありますか？',
      '吹き替え版はありますか？',
    ],
  },
  {
    place: 'ホテルのフロント',
    senderRole: '宿泊客',
    senderVoice: 'male',
    receiverRole: 'ホテルスタッフ',
    receiverVoice: 'female',
    englishSentence: 'Could you give me a hand with my luggage?',
    japaneseSentence: '荷物を運ぶのを手伝ってもらえますか？',
    englishReply: 'Of course, I’ll call the bell staff right away.',
    japaneseReply: 'もちろんです。すぐにベルスタッフを呼びますね。',
    incorrectOptions: [
      'チェックアウトは何時までですか？',
      '朝食はどこで食べられますか？',
      '延泊は可能ですか？',
    ],
  },
  {
    place: '郵便局の窓口',
    senderRole: '郵便局の客',
    senderVoice: 'female',
    receiverRole: '郵便局員',
    receiverVoice: 'male',
    englishSentence: 'I need to send this letter overseas, how much is it?',
    japaneseSentence: 'この手紙を海外に送りたいのですが、いくらですか？',
    englishReply: 'It will cost 五百円 to send this one.',
    japaneseReply: 'こちらは五百円になります。',
    incorrectOptions: ['速達にできますか？', '切手はここで買えますか？', '小包も出せますか？'],
  },
  {
    place: 'スーパーの試食コーナー',
    senderRole: 'お客さん',
    senderVoice: 'male',
    receiverRole: '試食スタッフ',
    receiverVoice: 'female',
    englishSentence: 'This cheese really hits the spot, can I buy some?',
    japaneseSentence: 'このチーズすごくおいしいですね、買えますか？',
    englishReply: 'Yes, the packaged ones are right behind you.',
    japaneseReply: 'はい、後ろにパック詰めのものがありますよ。',
    incorrectOptions: [
      'ワインの試飲はできますか？',
      '賞味期限はいつまでですか？',
      '他の種類もありますか？',
    ],
  },
  {
    place: '空港の搭乗ゲート',
    senderRole: '旅行客',
    senderVoice: 'female',
    receiverRole: 'ゲートスタッフ',
    receiverVoice: 'male',
    englishSentence: 'Is boarding already in full swing now?',
    japaneseSentence: 'もう搭乗は始まっていますか？',
    englishReply: 'Yes, they just started letting people in.',
    japaneseReply: 'はい、ちょうど今搭乗が始まりました。',
    incorrectOptions: [
      '荷物検査はどこで受けますか？',
      '出発時刻は何時ですか？',
      '搭乗券はここで見せますか？',
    ],
  },
  {
    place: '会社の会議室',
    senderRole: '上司',
    senderVoice: 'male',
    receiverRole: '部下',
    receiverVoice: 'female',
    englishSentence: 'Let’s cut corners on details and focus on results.',
    japaneseSentence: '細かいことは省いて結果に集中しましょう。',
    englishReply: 'Got it, I’ll prepare only the key points.',
    japaneseReply: '分かりました、要点だけまとめます。',
    incorrectOptions: [
      '会議は何時に始まりますか？',
      '昼食はどうしますか？',
      '議事録は誰が取りますか？',
    ],
  },
  {
    place: 'バス停のベンチ',
    senderRole: '通勤客',
    senderVoice: 'female',
    receiverRole: '通勤客',
    receiverVoice: 'male',
    englishSentence: 'This bus always runs behind schedule, doesn’t it?',
    japaneseSentence: 'このバスっていつも遅れますよね？',
    englishReply: 'Yeah, it’s usually ten minutes late.',
    japaneseReply: 'ええ、たいてい十分は遅れますね。',
    incorrectOptions: [
      'このバスは市役所に行きますか？',
      '次の便は何分後ですか？',
      '定期券はここで買えますか？',
    ],
  },
  {
    place: '観光地のチケット売り場',
    senderRole: '観光客',
    senderVoice: 'male',
    receiverRole: 'スタッフ',
    receiverVoice: 'female',
    englishSentence: 'Do you have any bundle tickets for families?',
    japaneseSentence: '家族用のセットチケットはありますか？',
    englishReply: 'Yes, we offer a discount for four people.',
    japaneseReply: 'はい、四人用の割引チケットがあります。',
    incorrectOptions: [
      '団体割引はありますか？',
      '今日の最終入場は何時ですか？',
      '子供料金はいくらですか？',
    ],
  },
  {
    place: '学校の教室',
    senderRole: '教師',
    senderVoice: 'female',
    receiverRole: '生徒',
    receiverVoice: 'male',
    englishSentence: 'Don’t beat around the bush, tell me your answer.',
    japaneseSentence: '回りくどく言わずに答えを言ってください。',
    englishReply: 'Alright, the answer is option B.',
    japaneseReply: '分かりました、答えはBです。',
    incorrectOptions: [
      '黒板をきれいにしてください。',
      '宿題は終わりましたか？',
      '教科書を開いてください。',
    ],
  },
  {
    place: '公園のベンチ',
    senderRole: '友人',
    senderVoice: 'male',
    receiverRole: '友人',
    receiverVoice: 'female',
    englishSentence: 'Wanna shoot the breeze while we wait?',
    japaneseSentence: '待ってる間にちょっと雑談しない？',
    englishReply: 'Sure, what’s new with you these days?',
    japaneseReply: 'いいよ、この頃どうしてる？',
    incorrectOptions: [
      '飲み物を買いに行かない？',
      '犬を少し散歩させてもいい？',
      '今日はどこに行く予定？',
    ],
  },
  {
    place: 'ショッピングモールのフードコート',
    senderRole: '客',
    senderVoice: 'female',
    receiverRole: '清掃員',
    receiverVoice: 'male',
    englishSentence: 'This table seems taken, or is it free?',
    japaneseSentence: 'このテーブル、使われていますか？それとも空いてますか？',
    englishReply: 'It’s free, you can sit down here.',
    japaneseReply: '空いてますよ、どうぞお座りください。',
    incorrectOptions: [
      'ゴミ箱はどこにありますか？',
      '近くにトイレはありますか？',
      'ここで充電できますか？',
    ],
  },
  {
    place: '郵便局の窓口',
    senderRole: '客',
    senderVoice: 'male',
    receiverRole: '郵便局員',
    receiverVoice: 'female',
    englishSentence: 'Can you send this package on the double?',
    japaneseSentence: 'この荷物、すぐに送ってもらえますか？',
    englishReply: 'Yes, express delivery is available for it.',
    japaneseReply: 'はい、速達で送れますよ。',
    incorrectOptions: ['代引きはできますか？', '封筒を買えますか？', '土日も営業していますか？'],
  },
  {
    place: '会社のエレベーターホール',
    senderRole: '同僚',
    senderVoice: 'female',
    receiverRole: '同僚',
    receiverVoice: 'male',
    englishSentence: 'Looks like we’re in the same boat with deadlines.',
    japaneseSentence: '締め切りに追われて、同じ状況ですね。',
    englishReply: 'Yeah, I’ll be working late again tonight.',
    japaneseReply: 'ええ、今夜も残業になりそうです。',
    incorrectOptions: [
      '昼ご飯はもう食べましたか？',
      '今朝は何階で会議ですか？',
      'コピー機は空いてますか？',
    ],
  },
  {
    place: '図書館の静かな一角',
    senderRole: '学生',
    senderVoice: 'male',
    receiverRole: '学生',
    receiverVoice: 'female',
    englishSentence: 'Could you keep it down a notch, please?',
    japaneseSentence: 'もう少し静かにしてもらえますか？',
    englishReply: 'Yes, sorry, I’ll lower my voice.',
    japaneseReply: 'はい、すみません。声を小さくします。',
    incorrectOptions: [
      'この席は使えますか？',
      '充電できる場所はありますか？',
      'プリンターはどこにありますか？',
    ],
  },
  {
    place: 'コンビニのレジ',
    senderRole: '客',
    senderVoice: 'female',
    receiverRole: '店員',
    receiverVoice: 'male',
    englishSentence: 'Could you break this bill into smaller change?',
    japaneseSentence: 'このお札を小銭に両替してもらえますか？',
    englishReply: 'Yes, I can give you smaller coins here.',
    japaneseReply: 'はい、小銭に両替できますよ。',
    incorrectOptions: [
      'レシートをくださいませんか？',
      '温めてもらえますか？',
      'トイレは使えますか？',
    ],
  },
  {
    place: 'ホテルのロビー',
    senderRole: '宿泊客',
    senderVoice: 'male',
    receiverRole: 'フロントスタッフ',
    receiverVoice: 'female',
    englishSentence: 'I’m running late, could you hail me a cab?',
    japaneseSentence: '時間がなくて、タクシーを呼んでもらえますか？',
    englishReply: 'Of course, I’ll call one right away.',
    japaneseReply: 'かしこまりました、すぐに手配します。',
    incorrectOptions: [
      '荷物を預けられますか？',
      '朝食は何時からですか？',
      'チェックインはできますか？',
    ],
  },
  {
    place: '駅のホーム',
    senderRole: '旅行者',
    senderVoice: 'female',
    receiverRole: '駅員',
    receiverVoice: 'male',
    englishSentence: 'Is this train on track for Osaka?',
    japaneseSentence: 'この電車は大阪に行きますか？',
    englishReply: 'Yes, this one goes directly there.',
    japaneseReply: 'はい、この電車は直通で行きます。',
    incorrectOptions: [
      '特急料金はいくらですか？',
      '自由席はどこですか？',
      'トイレはついていますか？',
    ],
  },
  {
    place: '病院の診察室前',
    senderRole: '患者',
    senderVoice: 'male',
    receiverRole: '看護師',
    receiverVoice: 'female',
    englishSentence: 'I’ve been waiting ages, is my turn soon?',
    japaneseSentence: 'ずっと待っているんですが、もうすぐ順番ですか？',
    englishReply: 'Yes, you’re next after this patient.',
    japaneseReply: 'はい、この方の次になります。',
    incorrectOptions: [
      '予約は必要ですか？',
      '検査はここで受けますか？',
      '薬局はどこにありますか？',
    ],
  },
  {
    place: 'レストランのテーブル',
    senderRole: '客',
    senderVoice: 'female',
    receiverRole: 'ウェイター',
    receiverVoice: 'male',
    englishSentence: 'Could you go easy on the salt this time?',
    japaneseSentence: '今回は塩を控えめにしてもらえますか？',
    englishReply: 'Sure, I’ll make a note for the kitchen.',
    japaneseReply: 'はい、厨房に伝えておきますね。',
    incorrectOptions: [
      '飲み物はまだ頼めますか？',
      '会計は別々にできますか？',
      'パンはおかわりできますか？',
    ],
  },
  {
    place: 'ショッピングモールのエスカレーター前',
    senderRole: '買い物客',
    senderVoice: 'male',
    receiverRole: '案内スタッフ',
    receiverVoice: 'female',
    englishSentence: 'Which way should I head for the food court?',
    japaneseSentence: 'フードコートへはどちらに行けばいいですか？',
    englishReply: 'Go straight and take the escalator up.',
    japaneseReply: 'まっすぐ進んでエスカレーターで上に行ってください。',
    incorrectOptions: [
      '両替所はどこにありますか？',
      '駐車場はどちらですか？',
      'トイレは近くにありますか？',
    ],
  },
  {
    place: '映画館のロビー',
    senderRole: '観客',
    senderVoice: 'female',
    receiverRole: '友人',
    receiverVoice: 'male',
    englishSentence: 'Shall we grab seats before the crowd pours in?',
    japaneseSentence: '人が増える前に席を取らない？',
    englishReply: 'Good idea, let’s head in now.',
    japaneseReply: 'いいね、今行こう。',
    incorrectOptions: [
      '先に飲み物を買わない？',
      '上映時間を確認しようか？',
      'パンフレットを見てみない？',
    ],
  },
  {
    place: '銀行の窓口',
    senderRole: '利用客',
    senderVoice: 'male',
    receiverRole: '銀行員',
    receiverVoice: 'female',
    englishSentence: 'Could I withdraw a large sum at once?',
    japaneseSentence: '一度に大きな金額を引き出せますか？',
    englishReply: 'Yes, but I’ll need to check your ID first.',
    japaneseReply: 'はい、ただ身分証の確認が必要です。',
    incorrectOptions: [
      '両替はここでできますか？',
      '新しい口座を作れますか？',
      '暗証番号を変えられますか？',
    ],
  },
  {
    place: 'カフェのテーブル',
    senderRole: '客',
    senderVoice: 'female',
    receiverRole: '友人',
    receiverVoice: 'female',
    englishSentence: 'Mind if I pick your brain about my project?',
    japaneseSentence: 'ちょっとプロジェクトのこと相談してもいい？',
    englishReply: 'Of course, tell me what’s going on.',
    japaneseReply: 'もちろん、どういう内容？',
    incorrectOptions: ['宿題を手伝ってくれる？', '今週末は空いてる？', '新しいカフェに行かない？'],
  },
  {
    place: '図書館の入口',
    senderRole: '学生',
    senderVoice: 'male',
    receiverRole: '司書',
    receiverVoice: 'male',
    englishSentence: 'Do I need to flash my card to get in?',
    japaneseSentence: '入るときにカードを見せる必要がありますか？',
    englishReply: 'Yes, please show it at the gate.',
    japaneseReply: 'はい、ゲートで提示してください。',
    incorrectOptions: [
      '延長はどこで手続きしますか？',
      '雑誌は借りられますか？',
      '閉館時間は何時ですか？',
    ],
  },
  {
    place: 'キッチン',
    senderRole: '大学生の息子',
    senderVoice: 'male',
    receiverRole: '母親',
    receiverVoice: 'female',
    englishSentence: '',
    japaneseSentence: 'はい、オリゴ糖買ってきたよ！',
    englishReply: '',
    japaneseReply: 'わぁ、ありがとう！オリゴ糖！',
    incorrectOptions: [
      '延長はどこで手続きしますか？',
      '雑誌は借りられますか？',
      '閉館時間は何時ですか？',
    ],
  },
];

export default problems;
