import { SeedProblemData } from '../src/types/problem';

// - incorrectOptions の要素たちは japaneseSentence とほぼ同じ文字数で生成すること
// - incorrectOptionsの内容は、依頼や質問や提案や意見や情報共有のような、話しかける形式のセリフであること。japaneseSentenceとは無関係なセリフであること。
// - 日本語の文について。「500円」などの数値は「五百円」と表記すること

const problems: SeedProblemData[] = [
  {
    englishSentence: 'May I ask who is calling, please?',
    japaneseSentence: 'どちら様でしょうか？',
    japaneseReply: '山田と申します。',
    englishReply: 'This is Yamada speaking.',
    incorrectOptions: ['昨日は眠れましたか？', '週末に出かけませんか？', '最近映画を見ましたか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '受付',
    receiverVoice: 'male',
    receiverRole: '電話の相手',
    place: '会社（電話中）',
  },
  {
    englishSentence: 'Could you bring me some water, please?',
    japaneseSentence: 'お水をいただけますか？',
    japaneseReply: 'はい、すぐにお持ちします。',
    englishReply: 'Yes, I’ll bring it right away.',
    incorrectOptions: ['明日は会えますか？', '最近どうしていますか？', '週末に集まりますか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '客',
    receiverVoice: 'female',
    receiverRole: '店員',
    place: 'レストラン',
  },
  {
    englishSentence: 'I’d like to send this package to Tokyo by express mail, please.',
    japaneseSentence: 'この荷物を速達で東京に送りたいのですが。',
    japaneseReply: 'はい、承知しました。伝票をご記入ください。',
    englishReply: 'Yes, understood. Please fill out this form.',
    incorrectOptions: [
      '昨日はどこに行きましたか？',
      '週末に集まりますか？',
      '最近どうしていますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '客',
    receiverVoice: 'female',
    receiverRole: '郵便局員',
    place: '郵便局',
  },
  {
    englishSentence: 'Please turn off your mobile phone before the performance begins.',
    japaneseSentence: '開演前に携帯電話の電源をお切りください。',
    japaneseReply: 'はい、電源を切ります。',
    englishReply: 'Yes, I’ll turn it off.',
    incorrectOptions: ['昨日は眠れましたか？', '週末に出かけませんか？', '最近映画を見ましたか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '係員',
    receiverVoice: 'male',
    receiverRole: '観客',
    place: '劇場',
  },
  {
    englishSentence: 'I’m afraid your flight has been delayed by two hours due to bad weather.',
    japaneseSentence: '悪天候のため、便は二時間遅れています。',
    japaneseReply: 'わかりました、ありがとうございます。',
    englishReply: 'I understand, thank you.',
    incorrectOptions: [
      '昨日は楽しかったですか？',
      '週末に集まりますか？',
      '最近体調はどうですか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '係員',
    receiverVoice: 'female',
    receiverRole: '乗客',
    place: '空港',
  },
  {
    englishSentence: 'Could you tell me if there is Wi-Fi available in this cafe?',
    japaneseSentence: 'このカフェにWi-Fiはありますか？',
    japaneseReply: 'はい、無料でご利用いただけます。',
    englishReply: 'Yes, it’s free to use.',
    incorrectOptions: ['昨日は眠れましたか？', '週末に出かけますか？', '最近映画を見ましたか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '客',
    receiverVoice: 'male',
    receiverRole: '店員',
    place: 'カフェ',
  },
  {
    englishSentence: 'Can you show me where the pain is?',
    japaneseSentence: '痛い場所を教えていただけますか？',
    japaneseReply: 'ここが痛いです。',
    englishReply: 'It hurts here.',
    incorrectOptions: ['昨日は雨でしたか？', '週末に集まりますか？', '最近本を読みましたか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '医者',
    receiverVoice: 'female',
    receiverRole: '患者',
    place: '病院',
  },
  {
    englishSentence: 'Excuse me, is there a bus to the airport from here?',
    japaneseSentence: 'すみません、ここから空港行きのバスはありますか？',
    japaneseReply: 'はい、あちらから出ています。',
    englishReply: 'Yes, it leaves from over there.',
    incorrectOptions: ['昨日は映画を見ましたか？', '週末に買い物しますか？', '最近元気ですか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '旅行者',
    receiverVoice: 'male',
    receiverRole: '駅員',
    place: 'バスターミナル',
  },
  {
    englishSentence: 'Good morning, I have a reservation under the name Tanaka.',
    japaneseSentence: 'おはようございます。田中で予約しています。',
    japaneseReply: 'はい、田中様ですね。こちらへどうぞ。',
    englishReply: 'Yes, Mr. Tanaka, this way please.',
    incorrectOptions: [
      '昨日は忙しかったですか？',
      '週末に出かけますか？',
      '最近何をしていますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '宿泊客',
    receiverVoice: 'female',
    receiverRole: 'ホテル受付',
    place: 'ホテル',
  },
  {
    englishSentence: 'Could you please lower your voice a little?',
    japaneseSentence: '声を少し小さくしていただけますか？',
    japaneseReply: 'すみません、気をつけます。',
    englishReply: 'Sorry, I’ll be careful.',
    incorrectOptions: ['昨日は楽しかったですか？', '週末に集まりますか？', '最近どうですか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '図書館員',
    receiverVoice: 'male',
    receiverRole: '利用者',
    place: '図書館',
  },
  {
    englishSentence: 'Can I try on this jacket in a larger size?',
    japaneseSentence: 'このジャケットをもう少し大きいサイズで試着できますか？',
    japaneseReply: 'はい、大きいサイズをお持ちします。',
    englishReply: 'Yes, I’ll bring you a larger one.',
    incorrectOptions: ['昨日は雨でしたか？', '週末に映画を見ますか？', '最近元気ですか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '客',
    receiverVoice: 'female',
    receiverRole: '店員',
    place: '服屋',
  },
  {
    englishSentence: 'Excuse me, how much is the entrance fee for adults?',
    japaneseSentence: 'すみません、大人の入場料はいくらですか？',
    japaneseReply: '五百円です。',
    englishReply: 'It’s five hundred yen.',
    incorrectOptions: [
      '昨日は楽しかったですか？',
      '週末は何をしましたか？',
      '最近本を読みましたか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '旅行者',
    receiverVoice: 'male',
    receiverRole: '係員',
    place: '博物館',
  },
  {
    englishSentence: 'Excuse me, could you tell me how to get to the station from here?',
    japaneseSentence: 'すみません、ここから駅までの行き方を教えていただけますか？',
    japaneseReply: 'はい、まっすぐ進んで右に曲がってください。',
    englishReply: 'Yes, go straight and then turn right.',
    incorrectOptions: ['昨日は眠れましたか？', '週末に遊びますか？', '最近どうしていますか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '旅行者',
    receiverVoice: 'female',
    receiverRole: '通行人',
    place: '道',
  },
  {
    englishSentence: 'Could you help me lift this heavy box?',
    japaneseSentence: 'この重い箱を持ち上げるのを手伝っていただけますか？',
    japaneseReply: 'はい、一緒に持ちましょう。',
    englishReply: 'Yes, let’s lift it together.',
    incorrectOptions: ['昨日は楽しかったですか？', '週末は忙しいですか？', '最近どうですか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '通行人',
    receiverVoice: 'male',
    receiverRole: '通行人',
    place: '道',
  },
  {
    englishSentence: 'Excuse me, could you tell me where the nearest ATM is?',
    japaneseSentence: 'すみません、一番近いATMはどこですか？',
    japaneseReply: '角を曲がるとすぐあります。',
    englishReply: 'It’s right around the corner.',
    incorrectOptions: [
      '昨日は映画を見ましたか？',
      '週末は買い物しますか？',
      '最近どうしていますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '旅行者',
    receiverVoice: 'female',
    receiverRole: '通行人',
    place: '街',
  },
  {
    englishSentence: 'I’d like to order two coffees and one sandwich, please.',
    japaneseSentence: 'コーヒーを二つとサンドイッチを一つお願いします。',
    japaneseReply: 'はい、少々お待ちください。',
    englishReply: 'Sure, just a moment.',
    incorrectOptions: ['昨日は雨でしたか？', '週末に遊びますか？', '最近どうしていますか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '客',
    receiverVoice: 'male',
    receiverRole: '店員',
    place: 'カフェ',
  },
  {
    englishSentence: 'Excuse me, where can I buy a ticket for the subway?',
    japaneseSentence: 'すみません、地下鉄の切符はどこで買えますか？',
    japaneseReply: '券売機で買えます。',
    englishReply: 'You can buy it at the ticket machine.',
    incorrectOptions: ['昨日は楽しかったですか？', '週末は何をしましたか？', '最近どうですか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '旅行者',
    receiverVoice: 'female',
    receiverRole: '駅員',
    place: '地下鉄駅',
  },
  {
    englishSentence: 'Excuse me, what time does the last train leave tonight?',
    japaneseSentence: 'すみません、今夜の最終電車は何時に出ますか？',
    japaneseReply: '十一時四十五分です。',
    englishReply: 'At 11:45.',
    incorrectOptions: ['昨日は忙しかったですか？', '週末に集まりますか？', '最近元気ですか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '旅行者',
    receiverVoice: 'male',
    receiverRole: '駅員',
    place: '駅',
  },
  {
    englishSentence: 'Could you recommend a good restaurant nearby?',
    japaneseSentence: 'この近くで良いレストランを教えていただけますか？',
    japaneseReply: 'はい、角を曲がった所に美味しい店があります。',
    englishReply: 'Yes, there’s a good one just around the corner.',
    incorrectOptions: ['昨日は雨でしたか？', '週末に遊びますか？', '最近どうしていますか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '旅行者',
    receiverVoice: 'female',
    receiverRole: '地元の人',
    place: '街',
  },
  {
    englishSentence: 'Excuse me, could you take a photo of us?',
    japaneseSentence: 'すみません、私たちの写真を撮っていただけますか？',
    japaneseReply: 'はい、もちろんです。',
    englishReply: 'Yes, of course.',
    incorrectOptions: ['昨日は雨でしたか？', '週末は何をしましたか？', '最近どうしていますか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '旅行者',
    receiverVoice: 'male',
    receiverRole: '通行人',
    place: '観光地',
  },
  {
    englishSentence: 'I’m sorry, but this seat is reserved.',
    japaneseSentence: 'すみませんが、この席は予約席です。',
    japaneseReply: 'あ、失礼しました。',
    englishReply: 'Oh, sorry about that.',
    incorrectOptions: ['昨日は眠れましたか？', '週末に集まりますか？', '最近どうしていますか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '乗務員',
    receiverVoice: 'female',
    receiverRole: '乗客',
    place: '電車',
  },
  {
    englishSentence: 'Do you have any vegetarian dishes?',
    japaneseSentence: 'ベジタリアン向けの料理はありますか？',
    japaneseReply: 'はい、こちらのサラダがおすすめです。',
    englishReply: 'Yes, this salad is recommended.',
    incorrectOptions: [
      '昨日は映画を見ましたか？',
      '週末は忙しいですか？',
      '最近本を読みましたか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '客',
    receiverVoice: 'male',
    receiverRole: '店員',
    place: 'レストラン',
  },
  {
    englishSentence: 'Excuse me, is this line for the museum entrance?',
    japaneseSentence: 'すみません、この列は博物館の入口用ですか？',
    japaneseReply: 'はい、そうです。',
    englishReply: 'Yes, it is.',
    incorrectOptions: ['昨日は眠れましたか？', '週末に集まりますか？', '最近元気ですか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '旅行者',
    receiverVoice: 'female',
    receiverRole: '係員',
    place: '博物館',
  },
  {
    englishSentence: 'Excuse me, is it okay to park here overnight?',
    japaneseSentence: 'すみません、ここに一晩駐車しても大丈夫ですか？',
    japaneseReply: 'はい、問題ありません。',
    englishReply: 'Yes, that’s fine.',
    incorrectOptions: [
      '昨日は楽しかったですか？',
      '週末は忙しいですか？',
      '最近どうしていますか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '旅行者',
    receiverVoice: 'male',
    receiverRole: '警備員',
    place: '駐車場',
  },
  {
    englishSentence: 'Could you tell me when the next bus to the airport leaves?',
    japaneseSentence: '空港行きの次のバスはいつ出ますか？',
    japaneseReply: '十五分後に出ます。',
    englishReply: 'It leaves in fifteen minutes.',
    incorrectOptions: ['昨日は雨でしたか？', '週末に集まりますか？', '最近どうしていますか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '旅行者',
    receiverVoice: 'female',
    receiverRole: 'バス係員',
    place: 'バスターミナル',
  },
  {
    englishSentence: 'Can I borrow this book for two weeks?',
    japaneseSentence: 'この本を二週間借りられますか？',
    japaneseReply: 'はい、貸し出し可能です。',
    englishReply: 'Yes, you can borrow it.',
    incorrectOptions: [
      '昨日は楽しかったですか？',
      '週末は何をしましたか？',
      '最近本を読みましたか？',
    ],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '利用者',
    receiverVoice: 'male',
    receiverRole: '図書館員',
    place: '図書館',
  },
  {
    englishSentence: 'Excuse me, could you tell me where the pharmacy is?',
    japaneseSentence: 'すみません、薬局はどこにありますか？',
    japaneseReply: '二つ目の角を右に曲がってください。',
    englishReply: 'Turn right at the second corner.',
    incorrectOptions: ['昨日は雨でしたか？', '週末は忙しいですか？', '最近どうしていますか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '旅行者',
    receiverVoice: 'female',
    receiverRole: '通行人',
    place: '街',
  },
  {
    englishSentence: 'Could you please be quiet for a moment?',
    japaneseSentence: '少しの間静かにしていただけますか？',
    japaneseReply: 'はい、すみません。',
    englishReply: 'Yes, sorry.',
    incorrectOptions: ['昨日は眠れましたか？', '週末は集まりますか？', '最近どうですか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'female',
    senderRole: '先生',
    receiverVoice: 'male',
    receiverRole: '学生',
    place: '教室',
  },
  {
    englishSentence: 'Excuse me, where can I find the information desk?',
    japaneseSentence: 'すみません、案内所はどこにありますか？',
    japaneseReply: '正面にあります。',
    englishReply: 'It’s right in front.',
    incorrectOptions: ['昨日は雨でしたか？', '週末は買い物しますか？', '最近どうしていますか？'],
    audioEnUrl: null,
    audioJaUrl: null,
    imageUrl: null,
    senderVoice: 'male',
    senderRole: '旅行者',
    receiverVoice: 'female',
    receiverRole: '係員',
    place: '駅',
  },
];

export default problems;
