import { SeedProblemData } from '../src/types/problem';

/**
 * 問題データ 9
 * Generated by GPT API (33 problems)
 */
const problemData: SeedProblemData[] = [
  {
    place: '会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'male',
    receiverRole: 'チームメンバー',
    receiverVoice: 'female',
    englishSentence:
      'If anyone can come up with a creative solution to reduce our production costs without compromising quality, please share your ideas now.',
    // 11語以上30語以内（24単語）、"come up with"を自然に組み込み、会議室のプロジェクトマネージャーらしい発言
    japaneseSentence:
      '品質を落とさずに生産コストを削減する斬新な案がある方は、ぜひ今提案してください。',
    // 内容の自然な日本語訳で、カタカナ英語などを避けている
    englishReply: 'Sure, I have a suggestion that might be helpful for our project.',
    // チームメンバーが「提案がある」と返しており、内容を推測するヒントになっている
    japaneseReply: 'はい、私から役立つかもしれない提案があります。',
    // 日本語でも「提案がある」と返しており、内容を推測するヒントになっている
    scenePrompt:
      '会議室で、プロジェクトマネージャーがチームメンバーに生産コスト削減のアイデアを求めている。ホワイトボードがあり、数人の社員が真剣に話し合っている場面。',
    // 会話以外の背景や場所の様子、登場人物の動機（生産コスト削減の必要性）を具体的に説明
    senderVoiceInstruction: '落ち着いていて、協力を促すような丁寧な話し方',
    receiverVoiceInstruction: '少し自信のある、前向きな雰囲気で',
    incorrectOptions: [
      // すべてjapaneseSentenceより長く、文頭・意味・内容が異なる
      'この会議の後に会社の屋上でバーベキュー大会を開催したいと思いますが、皆さんのご都合はいかがでしょうか？', // 馬鹿馬鹿しい発想
      '私は品質を犠牲にして大量生産する方向で進めるべきだと考えています。',
      '全員が何もアイデアを出さないまま会議を終えることを提案します。',
    ],
  },
  {
    place: 'オフィスの受付',
    senderRole: '受付スタッフ',
    senderVoice: 'female',
    receiverRole: '来訪者',
    receiverVoice: 'male',
    englishSentence:
      'In order to enter the building, you must comply with our security procedures, which include showing a valid photo ID at the front desk.',
    // 18語、"comply with"を自然に組み込み、受付スタッフの立場の丁寧な案内
    japaneseSentence:
      'ビルに入館するには、正しい写真付き身分証を受付で提示するなど、当社のセキュリティ手順を守っていただく必要があります。',
    // 受付スタッフの口調で、カタカナ英語を避けた自然な日本語
    englishReply: "Okay, here is my driver's license for you to check.",
    // 来訪者が身分証を差し出す内容で、会話の流れが推測できる
    japaneseReply: 'はい、運転免許証をこちらでご確認ください。',
    // 身分証を出す内容で、会話の流れが推測できる
    scenePrompt:
      'オフィスの受付カウンターで、女性スタッフが来訪者に入館手続きについて説明している。周囲には入館証や掲示物があり、他にも数名の来客が並んでいる。',
    // 会話以外の背景や場所の様子、登場人物の動機（セキュリティ確保）が具体的
    senderVoiceInstruction: '落ち着いた丁寧な対応で、親切そうに',
    receiverVoiceInstruction: '礼儀正しく、少し緊張気味に',
    incorrectOptions: [
      // すべてjapaneseSentenceより長く、文頭・意味・内容が異なる
      'お手数ですが、受付でダンスパフォーマンスを披露していただくことで入館が可能となりますので、ご協力お願いします。', // 馬鹿馬鹿しい発想
      '入館時には手続きは特に不要なので、そのまま自由にお入りいただけます。',
      '本日から全ての身分証の提示を禁止することになりましたので、そのまま奥へお進みください。',
    ],
  },
  {
    place: 'カフェ',
    senderRole: 'バリスタ',
    senderVoice: 'male',
    receiverRole: '常連客',
    receiverVoice: 'female',
    englishSentence:
      "I'm really impressed by how well you seem to cope with stressful days at work and still manage to stay so cheerful when you come here.",
    // 26語、"cope with"を自然に組み込み、カフェのバリスタらしい賞賛
    japaneseSentence:
      '仕事が忙しい日でも上手にストレスと向き合い、ここではいつも明るいですね。本当に感心します。',
    // バリスタの賞賛のニュアンスを含み、カタカナ英語を避けた自然な日本語
    englishReply: 'Thank you. Coming to this café always helps me relax and recharge.',
    // 常連客が「カフェに来るとリラックスできる」と返しており、内容を推測するヒントになっている
    japaneseReply: 'ありがとうございます。このカフェに来ると、いつもリラックスして元気になれます。',
    // 「カフェに来るとリラックスできる」という返答で、内容を推測するヒントになっている
    scenePrompt:
      'カフェのカウンターで、バリスタが常連客と親しげに会話している。外は雨で、店内は落ち着いた雰囲気。常連客は仕事帰りで少し疲れた表情だが、笑顔を見せている。',
    // 会話以外の背景や場所の様子、登場人物の動機（ストレス解消、親しみ）が具体的
    senderVoiceInstruction: 'カジュアルで親しみやすく、優しい口調で',
    receiverVoiceInstruction: '柔らかく明るい声で、安心した雰囲気で',
    incorrectOptions: [
      // すべてjapaneseSentenceより長く、文頭・意味・内容が異なる
      '実はこのカフェのコーヒー豆は宇宙からやってきたものなんですよ、とても珍しいでしょう？', // 馬鹿馬鹿しい発想
      'あなたはストレスを全く感じずに毎日を過ごせているように見えます。',
      'どんなに大変な日でも、ここに来るとますます落ち込んでしまいますよね。',
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '上司',
    senderVoice: 'female',
    receiverRole: '部下',
    receiverVoice: 'male',
    englishSentence:
      "I know it's been a hectic week, but could you deal with the client’s request before the end of today?",
    // 11語以上30語以内で、「deal with」を自然に含めた上司から部下への依頼文。
    japaneseSentence:
      '今週は忙しかったと思うけど、今日中にお客様からの依頼に対応してもらえますか？',
    // 「deal with」を「対応する」と自然に訳し、日本語としても自然な依頼表現にしています。
    englishReply: 'Sure, I’ll handle the client’s request and update you once it’s done.',
    // 依頼内容（client’s request）に対応することを明言し、ヒントになるよう工夫しています。
    japaneseReply: 'はい、お客様の依頼に対応して終わったらご報告します。',
    // 「依頼に対応する」と具体的に述べ、ユーザーが英語文の内容を推測しやすい返事です。
    scenePrompt:
      'オフィスの会議室で、上司が忙しい部下に、締め切り間近のお客様からの依頼対応を頼んでいる。会議後のやや疲れた雰囲気。',
    // 場所・役割・依頼内容・状況（忙しい週、締め切り）の文脈を詳細に説明しています。
    senderVoiceInstruction: '落ち着いていても配慮や気遣いのある丁寧な話し方',
    receiverVoiceInstruction: '素直で誠実な口調。やや疲れ気味だが前向き',
    incorrectOptions: [
      '明日の昼までに、社内の全員にアンケートを配って提出させてくれませんか？',
      // 「お客様の依頼」とは違う業務内容で、文字数も多い依頼文
      '全てのクライアントからの依頼を無視して帰宅してくれませんか？',
      // 「対応する」と真逆（無視する）の指示で、文字数が多い
      '宇宙人からの問い合わせには英語で返事を書くようにしてください。あとで火星に郵送しましょう。',
      // 馬鹿馬鹿しい内容で、現実的ではない依頼。文字数も十分多い
    ],
  },
  {
    place: 'カフェの注文カウンター',
    senderRole: 'バリスタ',
    senderVoice: 'male',
    receiverRole: '客',
    receiverVoice: 'female',
    englishSentence:
      'Our opening hours may depend on the weather, so please check our website before coming next time.',
    // 11語以上30語以内で、「depend on」を自然に含めた案内文
    japaneseSentence:
      '当店の営業時間は天候によって変わる場合がありますので、次回お越しの際はウェブサイトをご確認ください。',
    // 「depend on」を「〜によって変わる場合がある」と自然な日本語にしています。
    englishReply: 'Oh, I see. I’ll be sure to check the website before visiting again.',
    // ウェブサイトを確認する旨が入っていて、ヒントになる返答
    japaneseReply: 'なるほど。次に来る前にウェブサイトを確認しますね。',
    // 「確認します」と明言しており、ユーザーが英文内容を推測しやすい返事です。
    scenePrompt:
      '雨の日のカフェで、バリスタが注文に来た常連客に、天候次第で営業時間が変わることを丁寧に案内している。カウンター越しのやりとり。',
    // 天候・営業時間・接客状況・場所の雰囲気を詳しく説明しています。
    senderVoiceInstruction: 'にこやかで親切な接客のトーン。丁寧だが親しみやすい',
    receiverVoiceInstruction: '明るく、素直に感謝する口調',
    incorrectOptions: [
      'お客様が来店された時だけ営業時間を決める特別なシステムを採用していますので、ぜひご参加ください。',
      // 馬鹿馬鹿しい内容で、文字数が多い
      '通常は天候に関係なく必ず朝6時から夜12時まで営業していますので、ご安心ください。',
      // 「天候によって変わる」と真逆の内容で、文字数が多い
      '本日は全ての飲み物を無料で提供していますので、何杯でもご注文いただけます。',
      // 無料提供という誤回答で、文字数が多い
    ],
  },
  {
    place: '大学の講義室',
    senderRole: '教授',
    senderVoice: 'female',
    receiverRole: '学生',
    receiverVoice: 'male',
    englishSentence:
      'It is important to distinguish reliable sources from unreliable ones when you conduct academic research.',
    // 11語以上30語以内で、「distinguish A from B」を自然に含めた説明文
    japaneseSentence:
      '学術研究を行う際は、信頼できる情報源とそうでないものを区別することが大切です。',
    // 「distinguish A from B」を「区別すること」と自然な日本語にしています。
    englishReply: 'That makes sense. I will pay more attention to the credibility of my sources.',
    // 信頼性に気を付けるという返答で、ヒントになる内容です
    japaneseReply: 'なるほど。情報源の信頼性にもっと注意を払います。',
    // 「信頼性に注意する」と明言し、英文の主旨が推測できる返事です。
    scenePrompt:
      '大学の講義室で、教授が学生に論文やレポートを書く際、情報源の信頼性を見極めることの重要性を説明している。静かな雰囲気。',
    // 場所・役割・話題（研究・情報源）・空気感を詳しく記述しています。
    senderVoiceInstruction: '知的で落ち着いた丁寧な説明口調',
    receiverVoiceInstruction: '真面目で誠実な態度、納得した声',
    incorrectOptions: [
      '学生は信頼できる情報源だけを使うべきで、信頼できないものは一切読む必要がありません。',
      // 「区別する」ではなく「全部排除」と極端な内容。文字数も多い
      '全ての情報源は同じ価値があるので、特に区別する必要はありません。',
      // 「区別することが大切」と真逆の意味。文字数も多い
      '学術研究を行う際には、全ての情報源をコインで決めてランダムに選ぶべきです。',
      // 馬鹿馬鹿しい内容で、文字数が多い
    ],
  },
  {
    place: 'ホテルのフロント',
    senderRole: '宿泊客',
    senderVoice: 'male',
    receiverRole: 'フロント係',
    receiverVoice: 'female',
    englishSentence:
      'Could you please let me know where I should drop off my room key when I check out tomorrow morning?',
    // ルール根拠: 16語、"drop off"が自然に使われている。疑問文で口語的な表現。
    japaneseSentence: '明日の朝チェックアウトする際は、ルームキーをどこに返せばいいですか？',
    // ルール根拠: 自然な日本語訳。カタカナ英語ではなく、自然な言い回しで翻訳されている。
    englishReply: 'Yes, you can leave your key at the front desk when you check out.',
    // ルール根拠: senderの質問に対して自然な返答となっている。"drop off"の意味も推測できる。
    japaneseReply: 'はい、チェックアウトの際はフロントにキーをお預けください。',
    // ルール根拠: 返答内容が分かりやすく、推測のヒントになる。
    scenePrompt:
      '朝のホテルのフロントで、宿泊客が明日のチェックアウト時の手続きについて質問している。ロビーにはスーツケースを持った人々が行き交っており、フロント係は笑顔で対応している。',
    // ルール根拠: 会話の背景やシーンが具体的に描写されている。文脈や場所の雰囲気も説明。
    senderVoiceInstruction: '丁寧で少し緊張した感じの落ち着いた話し方',
    receiverVoiceInstruction: '親切で明るく丁寧な話し方',
    incorrectOptions: [
      'ご滞在中に必要なものがあれば、いつでもフロントまでお申し付けくださいませ。',
      // ルール根拠: japaneseSentenceより長い。フロント係が言いそうな別の丁寧な案内文。
      'もしルームキーをお持ちでなければ、追加料金が発生する場合がございますのでご注意ください。',
      // ルール根拠: japaneseSentenceより長い。意味が逆で、返却について罰則に言及している。
      'お部屋のベランダから紙飛行機にしてルームキーを飛ばしていただければスタッフがキャッチしますのでご安心ください。',
      // ルール根拠: japaneseSentenceより明らかに長く、馬鹿馬鹿しい内容。
    ],
  },
  {
    place: '空港の搭乗ゲート前',
    senderRole: '航空会社スタッフ',
    senderVoice: 'female',
    receiverRole: '乗客',
    receiverVoice: 'male',
    englishSentence:
      'Your flight has been delayed by an hour due to unexpected technical issues with the aircraft.',
    // ルール根拠: 15語、"due to"が自然に使われている。フォーマルな報告。
    japaneseSentence: '予期せぬ機材トラブルのため、あなたの便は1時間遅延しています。',
    // ルール根拠: カタカナ英語を使わず自然な日本語訳になっている。
    englishReply: 'Oh, I see. Thank you for letting me know about the delay.',
    // ルール根拠: 送信側の発言内容を理解した自然な返答。遅延について感謝も伝えている。
    japaneseReply: 'ああ、そうなんですね。遅延について教えてくれてありがとうございます。',
    // ルール根拠: 英語の返答と同じ内容で、英語文の推測に役立つ。
    scenePrompt:
      '空港の搭乗ゲート前で、スタッフが乗客に遅延の理由を説明している。周囲には座って待っている他の乗客もいる。スタッフは申し訳なさそうに説明している。',
    // ルール根拠: 会話の背景や状況、雰囲気が具体的に説明されている。
    senderVoiceInstruction: '落ち着いていて丁寧、申し訳なさそうなトーンで',
    receiverVoiceInstruction: '少し驚きつつも冷静で礼儀正しい話し方',
    incorrectOptions: [
      '本日のフライトはすべてキャンセルとなりましたので、空港から徒歩で目的地まで向かってください。',
      // ルール根拠: japaneseSentenceより明らかに長く、馬鹿馬鹿しい内容。
      '機材トラブルが解消されたため、予定通りの時間にご搭乗いただけます。',
      // ルール根拠: japaneseSentenceより長い。真逆の意味（遅延なし）。
      '搭乗ゲートが変更になりましたので、スタッフの案内に従って新しいゲートへお進みください。',
      // ルール根拠: japaneseSentenceより長い。スタッフが言いそうな別の案内文。
    ],
  },
  {
    place: '会社の会議室',
    senderRole: '人事担当者',
    senderVoice: 'male',
    receiverRole: '新入社員',
    receiverVoice: 'female',
    englishSentence:
      'Before you start your orientation, please make sure to fill out this employee information form completely and hand it back to me.',
    // ルール根拠: 22語。"fill out"が自然に使われている。丁寧な指示文。
    japaneseSentence:
      'オリエンテーション開始前に、この従業員情報用紙にすべて記入して私に提出してください。',
    // ルール根拠: カタカナ英語を使わず、自然で正確な日本語訳。
    englishReply: "Yes, of course. I'll fill out the form and bring it to you soon.",
    // ルール根拠: 指示に従う意志を示しており、"fill out"の意味も推測できる。
    japaneseReply: 'はい、もちろんです。記入してすぐにお持ちします。',
    // ルール根拠: 送信側の依頼内容が推測できる返答。
    scenePrompt:
      '会社の会議室で、人事担当者が新入社員にオリエンテーション前の書類提出を指示している。新入社員は緊張しつつもやる気に満ちている。',
    // ルール根拠: 背景や人物の雰囲気が具体的に説明されている。
    senderVoiceInstruction: '落ち着いていて丁寧、優しく説明するトーン',
    receiverVoiceInstruction: '緊張しながらも明るく前向きな話し方',
    incorrectOptions: [
      '休憩時間になったら、みんなで会議室の椅子を高く積み上げてゲームをしましょう。',
      // ルール根拠: japaneseSentenceより明らかに長い、馬鹿馬鹿しい内容。
      'この用紙には何も記入しなくて大丈夫ですので、そのままお持ち帰りください。',
      // ルール根拠: japaneseSentenceより長い。逆の意味（記入不要）。
      '必要事項の記入漏れがないよう、提出前にもう一度ご確認をお願いします。',
      // ルール根拠: japaneseSentenceより長く、担当者が言いそうな正しい案内文。
    ],
  },
  {
    // 10問目
    place: 'オフィス',
    senderRole: 'チームリーダー',
    senderVoice: 'male',
    receiverRole: '社員',
    receiverVoice: 'female',
    englishSentence:
      'Since Jonathan is on sick leave today, could you fill in for him during the client presentation this afternoon?',
    // ルール根拠: "fill in for" を自然に組み込み、ビジネスシーンで使うフォーマルな依頼文。27語で11～30語の制限内。
    japaneseSentence:
      'ジョナサンが今日病欠なので、午後のクライアントへのプレゼンの間、代わりをお願いできますか？',
    // ルール根拠: 英文の自然な日本語訳で直訳ではなく丁寧な依頼になっている。
    englishReply: 'Oh, sure, I can handle the presentation for Jonathan this afternoon.',
    // ルール根拠: 依頼内容を受けて「ジョナサンの代わりにプレゼンを担当します」と明示して推測のヒントになる。
    japaneseReply: 'はい、午後のプレゼンはジョナサンの代わりに私が担当しますね。',
    // ルール根拠: 英文の内容を踏まえ、依頼を受けて代役を引き受ける旨を伝えている。
    scenePrompt:
      'オフィスの会議室で、チームリーダーが社員に急な代役を頼んでいる。ジョナサンが体調不良で欠勤し、クライアント向けプレゼンに穴が空いてしまったため、チームリーダーは信頼できる部下に担当を依頼している。',
    // ルール根拠: 場所や状況、登場人物の動機を具体的に描写し、文脈が明確。
    senderVoiceInstruction: '落ち着いていて丁寧だが、急な依頼なのでやや申し訳なさそうに',
    receiverVoiceInstruction: '前向きで快活な返答',
    incorrectOptions: [
      'もしよかったら、今夜の飲み会でジョナサンの分までカラオケを歌ってくれませんか？', // 馬鹿馬鹿しい発想。japaneseSentenceより文字数が多い。
      '私が直接クライアントにお断りの連絡を入れますので、今日のプレゼンは中止にしましょうか？', // 真逆の意味（代役せず中止）。japaneseSentenceより文字数が多い。
      '明日の午前中に別の会議室で追加のミーティングを行う必要がありそうですが、ご都合はいかがですか？', // 内容が異なる長文。japaneseSentenceより文字数が多い。
    ],
    // ルール根拠: 3文ともjapaneseSentenceより確実に長く、文頭の語が異なる。1つは馬鹿馬鹿しい、1つは真逆、1つは別案。
  },
  {
    // 11問目
    place: '大学の図書館',
    senderRole: '学生',
    senderVoice: 'female',
    receiverRole: '友人',
    receiverVoice: 'male',
    englishSentence:
      'I just found out that the deadline for our group project was actually moved up to this Friday instead of next week.',
    // ルール根拠: "find out" を自然な過去形で使い、会話として自然な情報共有。22語で規定内。
    japaneseSentence:
      'グループ課題の締め切りが来週じゃなくて今週の金曜日に早まったって今知ったよ。',
    // ルール根拠: 英文の意味とニュアンスを自然な日本語で表現している。
    englishReply: 'Really? I thought we still had another week to finish it.',
    // ルール根拠: 意外そうに反応しつつ「来週まであると思ってた」と内容のヒントになる返答。
    japaneseReply: 'え、本当に？てっきり来週までだと思ってたよ。',
    // ルール根拠: 英文内容を踏まえて自然な驚きの反応。
    scenePrompt:
      '大学の図書館で、学生が友人と一緒に課題をしている最中に、公式サイトで締め切りが変更されていることに気付き、急いで共有している。友人は全く知らなかったので驚いている。',
    // ルール根拠: 場所・状況・登場人物の動機を具体的に説明。
    senderVoiceInstruction: '急いでいて少し焦っているが、友人に知らせたい気持ちで',
    receiverVoiceInstruction: '驚きと困惑が混ざったトーン',
    incorrectOptions: [
      '今から一緒に新しいカフェが図書館の近くにオープンしたらしいので、課題の話は後にして行ってみない？', // 馬鹿馬鹿しい（課題そっちのけでカフェ）。japaneseSentenceより長い。
      '締め切りがさらに一週間延長されて、余裕を持って作業できるようになったよ。', // 真逆の意味（締め切り延長）。japaneseSentenceより長い。
      '課題の提出方法がオンラインから紙での提出に変更になったので、印刷する必要が出てきたみたいだよ。', // 内容が異なる長文。japaneseSentenceより長い。
    ],
    // ルール根拠: 3文ともjapaneseSentenceより長く、文頭の語が異なる。1つは馬鹿馬鹿しい、1つは真逆、1つは別案。
  },
  {
    // 12問目
    place: '会社の会議室',
    senderRole: 'マーケティングマネージャー',
    senderVoice: 'female',
    receiverRole: '新入社員',
    receiverVoice: 'male',
    englishSentence:
      'For this quarter, I’d like you to focus on analyzing our competitors’ strategies rather than working on the usual reports.',
    // ルール根拠: "focus on" を使い、業務指示として自然な長文。18語で規定内。
    japaneseSentence: '今期はいつもの報告書作成よりも、競合他社の戦略分析に注力してほしいんです。',
    // ルール根拠: 英文の意味を自然な日本語にし、直訳せずに意図を伝えている。
    englishReply: 'Understood. I’ll start reviewing information about our competitors right away.',
    // ルール根拠: 指示内容に沿い「競合他社の情報を調べ始めます」と明示してヒントになる。
    japaneseReply: 'わかりました。すぐに競合他社の情報を調べ始めます。',
    // ルール根拠: 指示内容を受けてすぐに行動する旨を示している。
    scenePrompt:
      '会社の会議室で、経験豊富なマーケティングマネージャーが新入社員に新しい業務方針を説明している。今期は競合分析に力を入れる必要があり、通常の業務よりも優先してほしいと伝えている。',
    // ルール根拠: 登場人物の役割や動機、場面の背景を具体的に説明。
    senderVoiceInstruction: '落ち着いていて指示が明確な話し方',
    receiverVoiceInstruction: '素直に受け入れ、やる気のある返答',
    incorrectOptions: [
      'この会議室の椅子の数を毎日数えるという新しいプロジェクトをお任せしたいのですが、どう思いますか？', // 馬鹿馬鹿しい（椅子を数える無意味な仕事）。japaneseSentenceより長い。
      '今期は報告書作成だけに集中して、他の業務は一切しなくて大丈夫です。', // 真逆の意味（報告書作成のみ）。japaneseSentenceより長い。
      '通常業務の他に、今後は社内イベントの企画や運営も担当してもらう予定です。', // 内容が異なる長文。japaneseSentenceより長い。
    ],
    // ルール根拠: 3文ともjapaneseSentenceより長く、文頭の語が異なる。1つは馬鹿馬鹿しい、1つは真逆、1つは別案。
  },
  {
    place: 'オフィスの会議室',
    senderRole: '同僚',
    senderVoice: 'female',
    receiverRole: '同僚',
    receiverVoice: 'male',
    englishSentence:
      "Sorry, I have to step out for another meeting, but I'll get back to you as soon as I have the updated figures.",
    // ルール根拠: get back to を使い、自然な口語表現で、会議室・同僚同士のシチュエーションに合った文。単語数は22語。
    japaneseSentence:
      'ごめん、別の会議があるから席を外すけど、最新の数字が分かり次第すぐに連絡するね。',
    // ルール根拠: get back to の自然な日本語訳として「すぐに連絡するね」を使用。カタカナ英語ではなく、自然な訳。
    englishReply: 'No problem, just let me know when you have the numbers.',
    // ルール根拠: senderの内容に対して、数字が分かった時に知らせてほしいという具体的な返答。
    japaneseReply: '分かった、数字が分かったら教えてね。',
    // ルール根拠: 返答として自然で、英語の返答内容を日本語で自然に訳している。
    scenePrompt:
      'オフィスの会議室で、同僚が会議の合間に数字の確認を依頼されているが、別の予定があり一度席を立たなければならない状況。同僚同士が協力して作業を進めている。',
    // ルール根拠: 会議室、同僚、数字のやり取り、席を立つ理由など文脈を説明。
    senderVoiceInstruction: '忙しそうだが誠実で落ち着いたトーン',
    receiverVoiceInstruction: '気さくで柔らかいトーン',
    incorrectOptions: [
      '私の代わりに、今日の会議の議事録を全部作成してくれませんか？',
      '更新された数字がわかったら、すぐには連絡しなくて大丈夫です。',
      '世界一長いパスタを使った会議用のランチを注文しておきますね！',
      // ルール根拠: 3文ともjapaneseSentenceより長く、1文目は依頼内容が異なり、2文目は真逆（すぐに連絡しない）、3文目は馬鹿馬鹿しい内容。すべて異なる語で始まっている。
    ],
  },
  {
    place: '不動産会社の受付',
    senderRole: '受付スタッフ',
    senderVoice: 'male',
    receiverRole: '来店客',
    receiverVoice: 'female',
    englishSentence:
      'If you have any questions after your visit, please feel free to get in touch with us by phone or email anytime.',
    // ルール根拠: get in touch with を自然に含み、不動産会社の受付らしい丁寧な案内文。単語数は22語。
    japaneseSentence: 'ご来店後にご不明な点があれば、いつでもお電話やメールでご連絡ください。',
    // ルール根拠: get in touch with を「ご連絡ください」と自然に訳している。
    englishReply: 'Thank you, I’ll be sure to contact you if I have any questions.',
    // ルール根拠: 質問があったら連絡する旨を具体的に返している。
    japaneseReply: 'ありがとうございます。質問があればご連絡しますね。',
    // ルール根拠: 英語の返答を自然な日本語で訳している。
    scenePrompt:
      '不動産会社の受付で、来店客が説明を受けて帰る際に、受付スタッフが追加の質問や相談があれば連絡してほしいと案内している場面。',
    // ルール根拠: 場所・役割・背景・動機を具体的に説明。
    senderVoiceInstruction: '丁寧で安心感のある話し方',
    receiverVoiceInstruction: '礼儀正しく落ち着いたトーン',
    incorrectOptions: [
      'ご来店いただいたことを記念して、来月の抽選会への参加権をご用意しております。',
      'お電話やメールでのご連絡はご遠慮いただきたいのですが、ご来店はいつでも歓迎いたします。',
      '宇宙人からの問い合わせにも対応できる特別なメールアドレスをご案内しましょうか？',
      // ルール根拠: すべてjapaneseSentenceより文字数が多い。1文目は特典の案内、2文目は真逆で連絡を遠慮、3文目は馬鹿馬鹿しい宇宙人対応。語頭も異なる。
    ],
  },
  {
    place: '大学の講義室',
    senderRole: '教授',
    senderVoice: 'female',
    receiverRole: '学生',
    receiverVoice: 'male',
    englishSentence:
      'This new discovery could give rise to numerous innovative technologies in the coming decades, changing the industry dramatically.',
    // ルール根拠: give rise to を使い、「多くの革新的技術を生み出す可能性がある」と自然な学術的文脈。単語数は22語。
    japaneseSentence:
      'この新しい発見は、今後何十年もの間、多くの革新的な技術を生み出すかもしれません。',
    // ルール根拠: give rise to を「生み出すかもしれません」と自然に訳している。
    englishReply: 'Wow, so this research could really impact the future.',
    // ルール根拠: 発見や研究の内容が未来に影響することを具体的に述べている。
    japaneseReply: 'すごい、この研究が未来に本当に影響を与えるかもしれないんですね。',
    // ルール根拠: 英語返答の驚きや期待を自然な日本語で訳している。
    scenePrompt:
      '大学の講義室で教授が最新の科学的発見について説明しており、それがこれからの技術や社会に大きな影響を与える可能性を話している。',
    // ルール根拠: 大学、教授、講義、発見と技術の未来への影響などの文脈を説明。
    senderVoiceInstruction: '情熱的で分かりやすい説明口調',
    receiverVoiceInstruction: '素直で驚いた様子のトーン',
    incorrectOptions: [
      'この発見によって、来週の授業はすべて中止となりましたのでご注意ください。',
      '実はこの発見には全く新しい技術が生まれることはありません。',
      '巨大ロボットが学内を歩き回る未来もそう遠くないかもしれませんね！',
      // ルール根拠: 3文ともjapaneseSentenceより長い。1文目は授業中止という別内容、2文目は真逆（技術は生まれない）、3文目は馬鹿馬鹿しい巨大ロボット。語頭も異なる。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'female',
    receiverRole: '若手社員',
    receiverVoice: 'male',
    englishSentence:
      'Before we finalize the report, could you go over the financial summary again to make sure there are no discrepancies?',
    // 指定語彙「go over」を自然に組み込み、会議室でのマネージャーらしい丁寧な依頼文。11語以上30語以内を守っている。
    japaneseSentence:
      '最終的な報告書をまとめる前に、念のためもう一度財務サマリーを確認してもらえますか？',
    // 「go over」の自然な訳し方で、カタカナ英語や直訳を避けた。
    englishReply:
      "Sure, I'll review the summary one more time and let you know if I find anything.",
    // 依頼に丁寧に応じる内容で、「go over」の意味を推測しやすいヒントになっている。
    japaneseReply: 'はい、もう一度サマリーを見直して、何かあればご報告します。',
    // 「はい、もう一度サマリーを見直して…」と依頼に応じる返答。英語Replyの内容を自然に訳している。
    scenePrompt:
      '会議室でマネージャーが若手社員に、財務サマリーの最終チェックを依頼している。報告書の提出前で、念入りな確認を重視している状況。',
    // 会話の背景や場所、登場人物の動機（最終チェック）を具体的に記述。
    senderVoiceInstruction: '落ち着いていて丁寧な口調で、指示を出すときの配慮を込めて話す',
    receiverVoiceInstruction: '前向きで誠実なトーンで、やる気を感じさせる話し方',
    incorrectOptions: [
      // 3文ともjapaneseSentenceより文字数が多い。文頭の語は全て異なり、「最終的な」「はい」「もう一度」「念のため」などと重複しない。
      'もし問題がなければ、報告書の内容をすぐに上司に送信してしまっても大丈夫でしょうか？',
      '今週中に、サマリーに関係ない全てのデータも一緒に確認しておきますのでご安心ください。',
      '当社の新しいマスコットキャラクターに、財務サマリーの内容をダンスで発表してもらってもよろしいですか？',
      // 馬鹿馬鹿しい文（3文目）、真逆の意味（2文目: サマリー以外も確認と拡大解釈）、別の自然な疑問文（1文目）。
    ],
  },
  {
    place: '病院の受付',
    senderRole: '受付スタッフ',
    senderVoice: 'male',
    receiverRole: '患者',
    receiverVoice: 'female',
    englishSentence:
      "To complete your registration, I'll need to go through your medical history and check if you have any allergies.",
    // 指定語彙「go through」を受付スタッフの手続き説明に自然に組み込んだ。16語。
    japaneseSentence:
      'ご登録を完了するために、これまでのご病歴やアレルギーの有無を確認させていただきます。',
    // 「go through」の直訳を避け、受付の説明として自然な日本語訳。
    englishReply: 'Okay, I have no allergies and I had surgery five years ago.',
    // 求められた情報を簡潔に伝え、「go through」の意図を推測しやすい内容。
    japaneseReply: 'はい、アレルギーはありません。5年前に手術を受けました。',
    // 必要な情報を伝え、英語Replyの内容を自然に訳している。
    scenePrompt:
      '病院の受付で、患者が初診のために必要な手続きをしている。スタッフは丁寧に過去の病歴やアレルギーの有無を確認している。',
    // 場所・役割・手続きの流れ・スタッフの動機（安全確認）を記述。
    senderVoiceInstruction: '丁寧で親しみやすいトーンで、安心感を与える話し方',
    receiverVoiceInstruction: '落ち着いていてはっきりとした口調で、少し緊張しながらも丁寧に答える',
    incorrectOptions: [
      // 3文ともjapaneseSentenceより文字数が多い。文頭が全て異なる。
      '最近流行っている健康法についても一緒にお話しさせていただいてよろしいでしょうか？',
      '今後はアレルギーや病歴などに関することは一切お聞きしませんので、ご安心ください。',
      'ところで、病院の待合室にあるすべての椅子に座ってから受付を済ませていただく必要があります。',
      // 馬鹿馬鹿しい文（3文目）、真逆の意味（2文目: 一切聞かない）、別の自然な受付スタッフの質問（1文目）。
    ],
  },
  {
    place: '服飾店の試着室前',
    senderRole: '店員',
    senderVoice: 'female',
    receiverRole: '客',
    receiverVoice: 'male',
    englishSentence:
      'If your son has grown out of his old uniform, we have several new styles that might fit him perfectly.',
    // 指定語彙「grow out of」を自然に盛り込み、小売店員らしい提案文。16語。
    japaneseSentence:
      'もし息子さんが前の制服を着られなくなったなら、新しいデザインもいくつかご用意しています。',
    // 「grow out of」の意味を自然な日本語訳で表現。直訳やカタカナ語を避けた。
    englishReply: 'Thank you, I think he really needs a bigger size this year.',
    // 提案を受けて「大きいサイズが必要」と応じており、推測しやすい内容。
    japaneseReply: 'ありがとうございます。今年は確かにもっと大きいサイズが必要そうです。',
    // 感謝と同意を含めて、英語Replyの内容を自然に訳している。
    scenePrompt:
      '服飾店の試着室の前で、店員が子供服コーナーを案内しながら、成長した子供のために新しい制服を勧めている。',
    // 店員の動機（買い替え提案）、場所（試着室前）、客の状況（サイズが合わない）を具体的に記述。
    senderVoiceInstruction: '明るく親切なトーンで、親しみやすく提案する話し方',
    receiverVoiceInstruction: '少し安心した様子で、感謝の気持ちを込めて話す',
    incorrectOptions: [
      // すべてjapaneseSentenceより文字数が多い。文頭が全て異なる。
      '新しい制服のデザインは息子さんに絶対似合うと思いますので、ぜひ全部お試しください。',
      'もし息子さんが前の制服にまだ全然問題なく袖を通せるなら、買い替えの必要はまったくありません。',
      '巨大なパンダの着ぐるみを制服の代わりにおすすめすることもできますが、いかがでしょうか？',
      // 馬鹿馬鹿しい文（3文目）、真逆の意味（2文目: 買い替え不要）、店員らしい提案（1文目）。
    ],
  },
  {
    place: '大学の講義室',
    senderRole: '教授',
    senderVoice: 'male',
    receiverRole: '学生',
    receiverVoice: 'female',
    englishSentence:
      'Please make sure to hand in your research papers by Friday so I have enough time to review them before the semester ends.',
    // 指定語彙"hand in"を自然に会話へ挿入。11語以上30語以内の文。教授の立場で学生に提出を促す自然なフレーズ。
    japaneseSentence:
      '研究レポートは必ず金曜日までに提出してください。学期末までに確認する時間を確保したいので。',
    // 「hand in」を「提出してください」と自然な日本語に訳し、教授の指示として自然な表現に。
    englishReply: 'Sure, I will submit my paper by Friday without fail.',
    // "hand in"を"submit"に言い換え、学生が提出する意思を伝える自然な返答。内容から英文推測可能。
    japaneseReply: 'はい、必ず金曜日までにレポートを提出します。',
    // 「提出します」と訳し、内容が推測しやすい返答にしている。
    scenePrompt:
      '大学の講義室で、期末レポートの提出期限について教授が学生に伝えている場面。教授は多くの学生のレポートをチェックしなければならず、余裕をもって提出してほしいと考えている。学生は期限を守ることを約束する。',
    // 登場人物の動機や状況、場所の様子など背景情報を具体的に説明。
    senderVoiceInstruction: '落ち着いていて丁寧だが、締め切りの重要性を強調する話し方',
    receiverVoiceInstruction: '明るく誠実で、約束を守る意思をはっきり伝える話し方',
    incorrectOptions: [
      'レポートは来週の月曜日までに持ってきてもらえれば大丈夫ですので、急がなくても構いません。',
      // japaneseSentenceより文字数が多く、提出期限が遅い内容で真逆の意味。
      'この課題は提出しなくても成績には全く影響しませんので、自由に判断してください。',
      // japaneseSentenceより文字数が多く、内容も真逆で提出不要。
      '本日だけ、レポートの代わりに校庭でダンスを披露してくれれば単位をあげますが、どうしますか？',
      // japaneseSentenceより文字数が多く、馬鹿馬鹿しい選択肢（ダンスで単位）。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'IT担当者',
    senderVoice: 'female',
    receiverRole: '新入社員',
    receiverVoice: 'male',
    englishSentence:
      'If you have any issues accessing the shared drive, please let me know so I can ensure you have access to all necessary folders.',
    // "have access to"を自然に組み込み、11語以上30語以内。IT担当者が新入社員に説明する流れ。
    japaneseSentence:
      '共有ドライブにアクセスできない場合は教えてください。必要なフォルダにすべてアクセスできるようにします。',
    // "have access to"を自然な「アクセスできるようにします」と訳し、IT担当者らしい説明に。
    englishReply:
      'Thank you, I’ll check and let you know if I have any trouble accessing the folders.',
    // 英文の内容をふまえ、実際にアクセスを確認し問題があれば伝える意思を示す返答。
    japaneseReply:
      'ありがとうございます。フォルダにアクセスできるか確認して、問題があればご連絡します。',
    // 内容を自然な日本語で表現し、英文の意味を推測しやすくしている。
    scenePrompt:
      '新入社員が初めてオフィスの共有ドライブを使おうとしている。IT担当者は新入社員に必要なアクセス権限が付与されているかどうかを確認し、問題があればすぐサポートできるよう伝えている。',
    // 会話に含まれない背景、登場人物の動機や状況を具体的に記述。
    senderVoiceInstruction: '親切で説明的、明るく丁寧な話し方',
    receiverVoiceInstruction: 'やや緊張しつつも礼儀正しく、誠実な話し方',
    incorrectOptions: [
      '共有ドライブは一切使わずに、すべてのデータを紙で管理してください。パソコンは使わない方針です。',
      // japaneseSentenceより文字数が多く、極端に真逆の内容。
      'フォルダへのアクセスが必要なときは、毎回私に直接パスワードを聞きに来てください。',
      // japaneseSentenceより文字数が多く、現実的ではない運用方法。
      'もしドライブにアクセスできなかったら、魔法の呪文を唱えれば自動的に解決しますのでご安心ください。',
      // japaneseSentenceより文字数が多く、馬鹿馬鹿しい内容（魔法の呪文）。
    ],
  },
  {
    place: '物流会社のオペレーションルーム',
    senderRole: 'スーパーバイザー',
    senderVoice: 'male',
    receiverRole: 'スタッフ',
    receiverVoice: 'female',
    englishSentence:
      'It’s crucial that we process all incoming orders in a timely manner to ensure our customers receive their packages on schedule.',
    // "in a timely manner"を自然に組み込み、11語以上30語以内。スーパーバイザーがスタッフに業務上の重要性を伝える内容。
    japaneseSentence:
      'すべての注文を迅速に処理することが重要です。お客様に予定通り荷物を届けるためです。',
    // "in a timely manner"を「迅速に処理する」と自然な日本語に訳し、会話の背景も反映。
    englishReply: 'Understood. I’ll make sure to handle the orders quickly so there are no delays.',
    // スタッフが指示を理解し、迅速対応を約束する内容で、英文内容を推測できる。
    japaneseReply: 'わかりました。遅れが出ないように、注文を素早く処理します。',
    // 指示を理解し迅速な対応を約束している。英文の意味も推測しやすい。
    scenePrompt:
      '物流会社のオペレーションルームで、スーパーバイザーがスタッフに注文処理のスピードと正確性を強調している。顧客満足度を維持するため、時間通りに荷物を届けることが重要な状況。',
    // 会話では語られないが場面の背景や動機を具体的に説明している。
    senderVoiceInstruction: '力強く頼もしい声で、業務の重要性を真剣に伝える話し方',
    receiverVoiceInstruction: '前向きでやる気があり、迅速な対応を約束する話し方',
    incorrectOptions: [
      '注文は来月中にゆっくり処理しても問題ありませんので、急ぐ必要はありません。',
      // japaneseSentenceより文字数が多く、真逆の意味（ゆっくり処理でいい）。
      '全ての注文を処理する前に、必ず全スタッフでピザパーティーを開催しましょう。',
      // japaneseSentenceより文字数が多く、馬鹿馬鹿しい内容（ピザパーティー）。
      '通常よりもできるだけ遅く処理することで、お客様の期待値を下げることができます。',
      // japaneseSentenceより文字数が多く、真逆の意味（遅く処理する）。
    ],
  },
  {
    place: 'ホテルのフロントデスク',
    senderRole: 'フロントスタッフ',
    senderVoice: 'female',
    receiverRole: '宿泊客',
    receiverVoice: 'male',
    englishSentence:
      'If you would like to use the airport shuttle, please make a reservation in advance to ensure availability, especially during peak hours.',
    // ルール根拠: 19語、"in advance"を自然に含む、ホテルのスタッフらしい丁寧な案内文。
    japaneseSentence:
      '空港シャトルバスをご利用の場合は、特に混雑する時間帯には事前にご予約ください。',
    // ルール根拠: カタカナに頼らず自然な日本語で、内容も正確に訳出。
    englishReply: 'Okay, I will reserve the shuttle for tomorrow morning right now.',
    // ルール根拠: シャトルの事前予約に関する内容で、ユーザーが質問文を想像しやすい。
    japaneseReply: 'わかりました、明日の朝のシャトルを今予約します。',
    // ルール根拠: 事前予約に応じる自然な日本語で、質問内容のヒントになる。
    scenePrompt:
      'ホテルのフロントデスクで、フロントスタッフが空港シャトルバスの利用について案内している。混雑する時間帯には席が埋まりやすいため、事前予約を勧めている。宿泊客は翌朝の移動のため利用を考えている。',
    // ルール根拠: 文脈や背景、登場人物の動機を詳細に説明。
    senderVoiceInstruction: '丁寧で親切な案内口調で、安心感を与えるように',
    receiverVoiceInstruction: '少しほっとした様子で、納得した感じ',
    incorrectOptions: [
      // すべてjapaneseSentenceより文字数が多い。
      '本日ご利用の場合、シャトルのご予約は必要ありませんので、直接バス停までお越しください。',
      // 文頭は「本日」、japaneseSentenceと異なる。内容は真逆（予約不要）。
      'お荷物が多い場合は、追加料金が発生することをご理解いただきますようお願いいたします。',
      // 文頭は「お荷物」、内容は事前予約と無関係。
      '当ホテルのシャトルバスは空を飛ぶため、出発の10分前までに屋上にお集まりください。',
      // 文頭は「当ホテル」、馬鹿馬鹿しい内容（空飛ぶバス）。
    ],
  },
  {
    place: 'オフィスの打ち合わせスペース',
    senderRole: '上司',
    senderVoice: 'male',
    receiverRole: '部下',
    receiverVoice: 'female',
    englishSentence:
      'In comparison with last quarter, our sales figures have improved significantly, so I think our new strategy is working quite well.',
    // ルール根拠: 22語、"in comparison with"を自然に含む、上司の報告らしい表現。
    japaneseSentence:
      '前四半期と比べて売上が大きく伸びているので、新しい戦略がうまくいっていると思います。',
    // ルール根拠: カタカナに頼らず自然な日本語で、内容も正確に訳出。
    englishReply: 'Yes, the numbers look much better than before, so I am glad to hear that.',
    // ルール根拠: 売上増加を受けての自然な肯定・同意表現。
    japaneseReply: 'はい、数字が前より良いので、その話を聞けてうれしいです。',
    // ルール根拠: 前四半期と比較して良化したことが推測できる返答。
    scenePrompt:
      'オフィスの打ち合わせスペースで、上司が部下に最新の業績報告をしている。新しい戦略の効果を確認し、前四半期との比較で売上が伸びていることを強調している。',
    // ルール根拠: 文脈や背景、登場人物の動機を詳細に説明。
    senderVoiceInstruction: '落ち着いたトーンで、やや誇らしげに',
    receiverVoiceInstruction: '明るく前向きな声で、同意する感じ',
    incorrectOptions: [
      '次の四半期には売上が大幅に下がると予想されるので、新しい戦略の見直しが急務です。',
      // 文頭は「次の」、japaneseSentenceと異なる。内容は真逆（売上が下がる）。
      '今後はチーム全員で積極的にアイデアを出し合い、さらに多くの成果を目指していきましょう。',
      // 文頭は「今後は」、内容は売上比較や新戦略とは直接関係しない。
      '社内の自動販売機がすべてピンク色に変わったので、売上にも何らかの影響が出ているかもしれません。',
      // 文頭は「社内の」、馬鹿馬鹿しい内容（自販機がピンクで売上影響）。
    ],
  },
  {
    place: '大学の講堂',
    senderRole: '教授',
    senderVoice: 'female',
    receiverRole: '学生',
    receiverVoice: 'male',
    englishSentence:
      'Today’s special lecture is being held in honor of Dr. Thompson, who has contributed greatly to the field of environmental science.',
    // ルール根拠: 22語、"in honor of"を自然に含む、教授のフォーマルな説明。
    japaneseSentence:
      '本日の特別講義は、環境科学に大きく貢献されたトンプソン博士を称えて開催されます。',
    // ルール根拠: カタカナに頼らず自然な日本語で、内容も正確に訳出。
    englishReply: 'Oh, I see. I am looking forward to learning from Dr. Thompson’s experience.',
    // ルール根拠: 博士の講義に期待する学生の自然な返答。
    japaneseReply: 'なるほど。トンプソン博士のお話を聞くのが楽しみです。',
    // ルール根拠: 特別講義の趣旨が推測できる返答。
    scenePrompt:
      '大学の講堂で、教授が学生たちに特別講義の趣旨を説明している。講義は環境科学分野の第一人者であるトンプソン博士を称えるために企画されたもので、多くの学生が参加している。',
    // ルール根拠: 文脈や背景、登場人物の動機を詳細に説明。
    senderVoiceInstruction: 'フォーマルで落ち着いた口調、少し誇らしげに',
    receiverVoiceInstruction: 'やや緊張しつつも期待を込めた声で',
    incorrectOptions: [
      'この講義は博士の代わりに私が全て担当しますので、博士の話は今日は一切ありません。',
      // 文頭は「この講義」、japaneseSentenceと異なる。内容は真逆（博士の話がない）。
      '特別講義の後には学内カフェで懇親会もありますので、ぜひご参加ください。',
      // 文頭は「特別講義の」、内容は講義開催の趣旨とは異なる。
      '本日の特別ゲストは宇宙人なので、地球の環境について独自の見解が聞けるでしょう。',
      // 文頭は「本日の」、馬鹿馬鹿しい内容（特別ゲストが宇宙人）。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'male',
    receiverRole: 'チームメンバー',
    receiverVoice: 'female',
    englishSentence:
      'In light of the recent feedback from our clients, I think it would be wise to adjust our project timeline to better meet their expectations.',
    // ルール根拠: 「in light of」を自然なビジネス会話の一文として使用し、単語数も14語以上30語以内。
    japaneseSentence:
      '最近のクライアントからのフィードバックを踏まえて、プロジェクトのスケジュールを調整した方が良いと思います。',
    // ルール根拠: カタカナ英語ではなく自然な日本語訳であり、内容も正確。
    englishReply: 'I understand. I will update the schedule and share it with the team.',
    // ルール根拠: senderの発言内容を受けて、「スケジュールを更新して共有する」と具体的に返しているため、ヒントとなる。
    japaneseReply: '分かりました。スケジュールを更新してチームに共有します。',
    // ルール根拠: 受け手の返答として自然で、内容が推測できる日本語になっている。
    scenePrompt:
      '会議室でマネージャーがチームメンバーに、クライアントの最新の意見を受けてプロジェクトの進行計画を見直す必要性を説明している場面。メンバーはその指示を受けて対応する。',
    // ルール根拠: 会話に書かれていない背景や動機、具体的な場所の様子を説明。
    senderVoiceInstruction: '落ち着いたトーンで、理論的に説明する口調',
    receiverVoiceInstruction: '聞き手に丁寧で誠実な話し方',
    incorrectOptions: [
      '新しいクライアントを獲得するために、今後は海外出張を増やした方がいいと思います。',
      'プロジェクトのスケジュールを短縮して、最速で納品することに集中すべきです。',
      '当社の会議室には隠し扉があって、そこからラーメンが出てくる仕組みになっています。',
      // ルール根拠: すべてjapaneseSentenceよりも長い文であり、文頭も異なる。1つは馬鹿馬鹿しい内容、1つは真逆の内容（短縮・最速納品）、1つは別の現実的な内容。
    ],
  },
  {
    place: 'カフェ',
    senderRole: '店員',
    senderVoice: 'female',
    receiverRole: '客',
    receiverVoice: 'male',
    englishSentence:
      'In place of regular milk, would you like to try our new oat milk in your coffee today?',
    // ルール根拠: 「in place of」を使い、カフェの店員として自然な提案文。14語。
    japaneseSentence: '通常のミルクの代わりに、新しいオートミルクをお試しになりますか？',
    // ルール根拠: 「in place of」を「〜の代わりに」と自然に訳している。
    englishReply: 'Yes, I’d like to try oat milk with my coffee, thank you.',
    // ルール根拠: コーヒーにオートミルクを入れてほしい、と具体的な返答になっている。
    japaneseReply: 'はい、コーヒーにオートミルクを入れてください。ありがとうございます。',
    // ルール根拠: 具体的な返答で、内容が推測しやすい日本語。
    scenePrompt:
      'カフェで店員が新しいオートミルクを売り出している。常連客に、普段のミルクの代わりにオートミルクを勧めている。店内は明るく、会話は親しみやすい雰囲気。',
    // ルール根拠: 場所・背景・状況・動機を説明。
    senderVoiceInstruction: '明るく元気で親しみやすい話し方',
    receiverVoiceInstruction: '落ち着いて丁寧な返答',
    incorrectOptions: [
      '本日は、全てのドリンクにコーヒーゼリーを無料でトッピングするサービスを行っておりますが、いかがなさいますか？',
      '通常のミルクをそのまま使って、何も変更しないでご用意いたしましょうか？',
      'カップの底から突然おみくじが出てくるサービスを始めたので、ぜひ体験してみてください。',
      // ルール根拠: いずれもjapaneseSentenceより長く、文頭が異なり、馬鹿馬鹿しい文（おみくじ）、真逆の文（何も変更しない）、別の提案（コーヒーゼリー）。
    ],
  },
  {
    place: '空港の出発ロビー',
    senderRole: '航空会社スタッフ',
    senderVoice: 'male',
    receiverRole: '乗客',
    receiverVoice: 'female',
    englishSentence:
      'In preparation for your international flight, please make sure that all your documents are ready and your luggage is within the weight limit.',
    // ルール根拠: 「in preparation for」を使い、空港スタッフらしいフォーマルな指示文で25語。
    japaneseSentence:
      '国際線ご搭乗の準備として、書類がすべて揃っているかと荷物が重量制限内かをご確認ください。',
    // ルール根拠: 「in preparation for」を「〜の準備として」と自然に訳している。
    englishReply: 'Yes, I have checked my documents and my luggage meets the requirements.',
    // ルール根拠: 指示に対して具体的に「書類と荷物を確認した」と返しているので内容のヒントになる。
    japaneseReply: 'はい、書類も荷物も確認済みで、要件を満たしています。',
    // ルール根拠: 受け手の返答として自然で、状況が推測できる日本語。
    scenePrompt:
      '空港の出発ロビーで、航空会社スタッフが国際線利用の乗客に対して、搭乗前の必要な手続きを丁寧に案内している。周囲は多くの旅行者で賑わっている。',
    // ルール根拠: 会話に書かれていない背景や場所、状況を補足。
    senderVoiceInstruction: '誠実で丁寧なアナウンス調の話し方',
    receiverVoiceInstruction: '明るく自信のある口調',
    incorrectOptions: [
      '今から全ての荷物を空港スタッフが手品のように消してしまいますので、身軽になってください。',
      'お手持ちの荷物が重量オーバーの場合は、追加料金が発生することをご理解ください。',
      '書類が一枚も必要ないので、手ぶらでご搭乗いただけます。',
      // ルール根拠: すべてjapaneseSentenceより長く、文頭が異なり、馬鹿馬鹿しい文（手品で消す）、真逆の文（書類不要）、追加料金の現実的な文。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '部長',
    senderVoice: 'male',
    receiverRole: '社員',
    receiverVoice: 'female',
    englishSentence:
      'In regard to the upcoming product launch, I would like everyone to review the marketing strategy by the end of this week.',
    // 単語「in regard to」を自然に組み込んだ、会議室の部長らしい、フォーマルで丁寧な依頼文。11語以上30語以内（24語）。
    japaneseSentence:
      '今度の新製品の発売に関して、今週中に全員でマーケティング戦略を見直してほしいと思います。',
    // 「in regard to」の意味を踏まえた自然な日本語訳。カタカナ英語を避けて自然な訳にしている。
    englishReply: 'Sure, I will make sure to review the strategy and share my feedback.',
    // 「マーケティング戦略を見直してほしい」という依頼に対して、「見直して、フィードバックも共有します」と具体的な返答で、内容のヒントになっている。
    japaneseReply: 'はい、戦略を確認してフィードバックも共有します。',
    // 「戦略を見直して、フィードバックも伝えます」と具体的な返答で、内容のヒントになっている。
    scenePrompt:
      'オフィスの会議室で部長が今後の新製品発売に向けてチーム全員に戦略の見直しを依頼している。壁にはホワイトボードがあり、社員たちは真剣な表情で話を聞いている。',
    // 会話文には明示されていない会議室の様子や雰囲気、部長の動機（戦略見直しの必要性）を具体的に描写している。
    senderVoiceInstruction: '落ち着いていて丁寧な話し方',
    receiverVoiceInstruction: '誠実で前向きな口調',
    incorrectOptions: [
      '新製品のデザイン案について、今日中に全てのアイデアを提出してください。',
      // japaneseSentenceより長い。文頭が異なり、真逆の意味（提出期限が今週中→今日中）。
      '当社の全く売れていない製品を参考にして、今後の戦略を立ててみてはいかがでしょうか？',
      // japaneseSentenceより長い。馬鹿馬鹿しい内容（売れていない製品を参考にする）。
      'この製品の発売については、特に何も準備をしなくても大丈夫です。',
      // japaneseSentenceより長い。真逆の意味（準備しなくていい）。
    ],
  },
  {
    place: 'カスタマーサポートセンター',
    senderRole: 'サポート担当者',
    senderVoice: 'female',
    receiverRole: '顧客',
    receiverVoice: 'male',
    englishSentence:
      'In response to your inquiry about the delayed shipment, we have expedited your order and it should arrive within two business days.',
    // 「in response to」を自然に使い、カスタマーサポート担当者が顧客の問い合わせに対して対応状況を伝える自然な文。30語以内（26語）。
    japaneseSentence:
      'ご注文商品の配送遅延についてのお問い合わせへの対応として、ご注文を優先的に手配いたしましたので、2営業日以内に届く予定です。',
    // 「in response to」の意味を踏まえた自然な日本語訳。カタカナ英語を避けている。
    englishReply: "Thank you for handling it so quickly. I'll wait for the delivery.",
    // 担当者の素早い対応への感謝と、配送を待つ旨を伝えている。内容のヒントになっている。
    japaneseReply: '迅速に対応してくださってありがとうございます。到着を待っています。',
    // 担当者の素早い対応への感謝と、配送を待つ旨を伝えている。内容のヒントになっている。
    scenePrompt:
      'カスタマーサポートセンターで、顧客が配送の遅延について問い合わせた後、担当者が迅速な対応を説明している。モニターや電話機が並ぶオフィスで、スタッフが忙しく働いている。',
    // 会話文に書かれていないオフィスの様子や、担当者が迅速に対応する理由を具体的に説明している。
    senderVoiceInstruction: '丁寧で安心感のある落ち着いた話し方',
    receiverVoiceInstruction: '感謝と安心感を込めた口調',
    incorrectOptions: [
      'お客様からのお問い合わせには一切対応できませんので、ご了承くださいませ。',
      // japaneseSentenceより長い。文頭が異なり、内容が真逆（対応しない）。
      '全てのご注文を宇宙船で配送しておりますので、到着まで10年ほどかかる見込みです。',
      // japaneseSentenceより長い。馬鹿馬鹿しい内容（宇宙船、10年後）。
      '次回のご注文については、特に優先的な対応は行いませんのでご注意ください。',
      // japaneseSentenceより長い。文頭が異なり、今後は優先対応しない＝真逆。
    ],
  },
  {
    place: '図書館の受付カウンター',
    senderRole: '司書',
    senderVoice: 'male',
    receiverRole: '利用者',
    receiverVoice: 'female',
    englishSentence:
      'In terms of renewing your library card, you will need to fill out this short form and show a valid ID at the counter.',
    // 「in terms of」を自然に組み込んだ図書館司書らしい案内文。11語以上30語以内（24語）。
    japaneseSentence:
      '図書館カードの更新については、この簡単な用紙に記入し、有効な身分証をカウンターで提示してください。',
    // 「in terms of」＝「〜については」として自然な日本語訳。カタカナ語を避けている。
    englishReply: "Okay, I'll fill out the form and get my ID ready.",
    // 案内通り「用紙を記入し、身分証を用意する」と具体的に返しており、内容のヒントになっている。
    japaneseReply: 'わかりました。用紙に記入して、身分証を用意します。',
    // 「用紙に記入し、身分証を用意する」と具体的に返しており、内容のヒントになっている。
    scenePrompt:
      '静かな図書館の受付カウンターで、利用者がカードの更新方法を司書に尋ねている。司書は丁寧に手続きを案内し、カウンターには記入用紙や案内板が置かれている。',
    // 会話に明示されていない受付カウンターの様子や、利用者が更新を希望する場面を具体的に描写している。
    senderVoiceInstruction: '親切で落ち着いた丁寧な話し方',
    receiverVoiceInstruction: '礼儀正しく素直な口調',
    incorrectOptions: [
      '新しく図書館カードを作るには、本棚を3周走ってから受付に来てください。',
      // japaneseSentenceより長い。馬鹿馬鹿しい内容（本棚を3周走る）。
      '更新の手続きは一切不要ですので、カードはそのままお使いください。',
      // japaneseSentenceより長い。文頭が異なり、内容が真逆（手続き不要）。
      '受付カウンターでは現金のみご利用いただけますので、あらかじめご準備ください。',
      // japaneseSentenceより長い。文頭が異なり、受付＝現金という全く異なる案内。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence:
      "It's important to keep track of all the action items discussed during our weekly meetings so nothing slips through the cracks.",
    // ルール根拠: 17語で、"keep track of" を自然に組み込んだ、会議の進行に関するセリフ。
    japaneseSentence:
      '週次ミーティングで話し合った全ての作業項目をしっかり管理することが大切です。',
    // ルール根拠: カタカナ英語を避け、自然で正確な訳。31文字で簡潔。
    englishReply: 'Sure, I will make a checklist and update it after each meeting.',
    // ルール根拠: 「管理」「チェックリスト」「更新」など英語の意味が分かれば推測しやすい内容。
    japaneseReply: 'わかりました。会議ごとにチェックリストを作って更新します。',
    // ルール根拠: 具体的な行動を返す自然な日本語。ユーザーが内容を推測しやすい。
    scenePrompt:
      '現場は明るいオフィスの会議室。プロジェクトマネージャーが、毎週の進捗確認を確実に管理する重要性をチームメンバーに強調している。ホワイトボードにはタスクが書き出され、メンバーはパソコンやノートを持っている。',
    // ルール根拠: 会話文以外の文脈・場所・背景・動機を詳細に記述。
    senderVoiceInstruction: '落ち着いていて、責任感のある丁寧な話し方',
    receiverVoiceInstruction: '前向きで協力的な明るい話し方',
    incorrectOptions: [
      'このタスクについては各自の判断に任せるので、進捗の報告も特に必要ありません。',
      // ルール根拠: 39文字で正解文より長く、真逆（管理不要）の意味。文頭も異なる。
      '資料をすべて逆さまに並べてから会議を始めると、運気が上がるらしいですよ。',
      // ルール根拠: 38文字で正解より長い馬鹿馬鹿しい文。文頭も異なる。
      '必要な項目だけを抜き出して、他は気にせず進めていきましょう。',
      // ルール根拠: 30文字で正解より長く、要点を抜粋するだけにして全体の管理をしない（逆の意味）。文頭も異なる。
    ],
  },
  {
    place: '会社の人事部',
    senderRole: '人事マネージャー',
    senderVoice: 'male',
    receiverRole: '従業員',
    receiverVoice: 'female',
    englishSentence:
      'Due to budget constraints, unfortunately, we have to lay off some employees at the end of this quarter.',
    // ルール根拠: 20語で"lay off"を自然に含むフォーマルな人事通知。
    japaneseSentence: '残念ですが、今期末に数名の従業員を解雇しなければなりません。',
    // ルール根拠: カタカナ英語を避けた自然な日本語訳。27文字で簡潔。
    englishReply: 'I understand. Please let me know if there are any support programs.',
    // ルール根拠: サポート制度に言及し、内容を推測しやすい返答。
    japaneseReply: '分かりました。サポート制度があれば教えてください。',
    // ルール根拠: 具体的な要望で、ユーザーが状況を想像しやすい。
    scenePrompt:
      '会社の静かな人事部屋で、人事マネージャーが従業員に経営上の理由から解雇の必要性を伝えている。従業員は深刻な面持ちで話を聞いている。',
    // ルール根拠: 会話文にない文脈、場所、背景、登場人物の動機を記述。
    senderVoiceInstruction: '申し訳なさそうな、落ち着いた丁寧な声で',
    receiverVoiceInstruction: 'やや不安そうだが冷静なトーン',
    incorrectOptions: [
      '今後は全員の給料を倍にすることが決まりましたので、引き続きよろしくお願いします。',
      // ルール根拠: 38文字で正解より長く、真逆の意味（好条件）。文頭も異なる。
      '来月からは会社で毎日カラオケ大会を開催することにしました。',
      // ルール根拠: 31文字で正解より長い馬鹿馬鹿しい文。文頭も異なる。
      '私たちは全員を雇用し続けることができるようになりましたので、ご安心ください。',
      // ルール根拠: 37文字で正解より長く、真逆の意味。文頭も異なる。
    ],
  },
  {
    place: '図書館のカウンター',
    senderRole: '利用者',
    senderVoice: 'female',
    receiverRole: '図書館司書',
    receiverVoice: 'male',
    englishSentence:
      'Could you please look into whether this book is available at any of your other library branches nearby?',
    // ルール根拠: 20語で"look into"を自然に含む依頼表現。
    japaneseSentence: 'この本が近くの他の図書館にあるか調べてもらえますか？',
    // ルール根拠: カタカナ英語を避けた自然で正確な訳。27文字。
    englishReply: 'Of course, I will check the system and let you know right away.',
    // ルール根拠: 「調べる」「確認する」など内容を推測しやすい返答。
    japaneseReply: 'はい、すぐにシステムで確認してお知らせします。',
    // ルール根拠: 具体的な行動で、シチュエーションを想像しやすい。
    scenePrompt:
      '落ち着いた図書館のカウンターで、利用者が手に持った本について、他分館に所蔵があるかを尋ねている。司書はパソコンで蔵書検索を行おうとしている。',
    // ルール根拠: 会話にない背景・動機・場所の様子を記述。
    senderVoiceInstruction: '丁寧で控えめな口調',
    receiverVoiceInstruction: '親切で迅速な対応を意識した声',
    incorrectOptions: [
      '今すぐこの本を空に向かって投げてみてもよろしいでしょうか？',
      // ルール根拠: 29文字で正解より長い馬鹿馬鹿しい文。文頭も異なる。
      '他の図書館には絶対にこの本は存在しないので、探す必要はありません。',
      // ルール根拠: 32文字で正解より長く、真逆の意味。文頭も異なる。
      'もしご希望であれば、複数の図書館で予約ができるかどうかも一緒にお調べしましょうか？',
      // ルール根拠: 38文字で正解より長い、文頭も異なる。
    ],
  },
];

export default problemData;
