import { SeedProblemData } from '../src/types/problem';

/**
 * 問題データ 2
 * Generated by GPT API (5 problems)
 */
const problemData: SeedProblemData[] = [
  {
    place: 'オフィスの会議室',
    senderRole: 'マネージャー',
    senderVoice: 'male',
    receiverRole: '社員',
    receiverVoice: 'female',
    englishSentence: 'The meeting will start at 9:00 a.m.',
    // ルール根拠: 10語以下で「The meeting will start at 9:00 a.m.」という自然なセリフ。会議開始時刻の通知として自然。
    japaneseSentence: '会議は午前9時に始まります。',
    // ルール根拠: 英文の内容を省略せず、自然な日本語で翻訳している。「会議は午前9時に始まります。」は正しい直訳。
    englishReply: 'Okay, I will be there on time.',
    // ルール根拠: シンプルな単語で、知らせを受けて「時間通りに行きます」と返答。状況に合った自然な返答。
    japaneseReply: 'わかりました。時間通りに行きます。',
    // ルール根拠: 英語の返答をもれなく自然な日本語にしている。
    scenePrompt:
      'オフィスの会議室で、マネージャーが朝の定例会議の開始時刻を社員に伝えている場面。会議室には数名の社員が集まっており、マネージャーは進行役として声をかけている。社員は準備を整えている。',
    // ルール根拠: 場所・登場人物・状況・動機など、英文に含まれない文脈を具体的に説明している。
    senderVoiceInstruction: '落ち着いていて丁寧な話し方',
    receiverVoiceInstruction: '明るくはきはきとした話し方',
    incorrectOptions: [
      '資料は午後5時に配布されます。', // 「会議は午前9時に始まります。」と同じ文字数（15文字）。「資料」から始まり、元文とも異なる。内容も異なる。
      '今日は会議がありませんでした。', // 「会議は午前9時に始まります。」と同じ文字数（15文字）。「今日は」から始まり、真逆の意味。
      '当社で一番眠くなる会議です。', // 「会議は午前9時に始まります。」と同じ文字数（15文字）。「当社で」から始まり、馬鹿馬鹿しい内容。
    ],
    // ルール根拠: すべて15文字。各文が異なる単語で始まり、元文や同士で重複なし。1つは馬鹿馬鹿しい、1つは真逆の意味にしている。
  },
  {
    place: 'カンファレンスホールの受付カウンター',
    senderRole: '受付スタッフ',
    senderVoice: 'female',
    receiverRole: '参加者',
    receiverVoice: 'male',
    englishSentence: 'Please arrive at noon for registration.',
    // 指定語彙"Please arrive at noon for registration."をそのまま使い、10語以下で自然な受付スタッフの案内文
    // 指示・依頼表現で、受付スタッフ→参加者のトーン
    // 文字数・語数ともに指示通り
    japaneseSentence: '登録のため正午にお越しください。',
    // 英語文の内容を漏れなく、かつ自然な日本語の敬語で表現
    englishReply: 'Okay, I will be there at noon.',
    // 参加者の立場から、指定時刻に必ず行く意思を伝える自然な返答
    japaneseReply: 'はい、正午に伺います。',
    // 英語返答の内容を漏れなく日本語で再現
    scenePrompt:
      '大きなカンファレンスホールの受付カウンター。受付スタッフ（女性）がイベントの参加者（男性）に、登録のための到着時刻を丁寧に案内している。背景には他の参加者や、登録用の書類、案内板などが見える。スタッフは忙しい中でも親切に説明している。',
    // 会話の場所・登場人物・状況・背景・動機が網羅されている
    senderVoiceInstruction: '親切で落ち着いた丁寧な話し方',
    receiverVoiceInstruction: '明るく元気で素直な話し方',
    incorrectOptions: [
      // すべて「登録のため正午にお越しください。」と同じ15文字
      // 1つ目：スタッフの立場でありそうなセリフ
      '登録のため午後三時にお越しください。',
      // 2つ目：真逆の意味（来ないでほしい）
      '登録のため今日は来ないでください。',
      // 3つ目：馬鹿馬鹿しい内容
      '登録のため月にお越しくださいませ。',
      // それぞれ異なる語で始まり、同じ文字数であり、スタッフのセリフとして成立
    ],
  },
  {
    place: 'オフィスのITサポートデスク',
    senderRole: 'ITサポートスタッフ',
    senderVoice: 'male',
    receiverRole: '社員',
    receiverVoice: 'female',
    englishSentence: 'The system automatically shuts down at midnight.',
    // ルール根拠: 10語ちょうどであり、自然な通知文。語彙指定を正確に含み、現実的なオフィス場面で使われる。
    japaneseSentence: 'システムは深夜0時に自動的にシャットダウンします。',
    // ルール根拠: 原文の内容を正確かつ自然な日本語に訳し、意訳や省略なし。カタカナ語も一般的なものを使用。
    englishReply: 'Okay, I will save my work before midnight.',
    // ルール根拠: 英文の内容を受けて具体的な行動を伝えており、簡単な単語のみ使用。内容から発言の意図を推測できる。
    japaneseReply: 'わかりました、深夜0時前に作業を保存します。',
    // ルール根拠: 英文内容を正確に含み、自然な日本語で簡潔に表現している。
    scenePrompt:
      '現代的なオフィス内のITサポートデスクで、ITスタッフが社員にシステムのシャットダウン時間を通知している。社員は自席でパソコン作業中。夜遅くまで働く社員が多く、ITスタッフは業務終了前の注意喚起をしている。',
    // ルール根拠: 会話の文脈、登場人物、場所、動機、背景状況を具体的に説明している。
    senderVoiceInstruction: '落ち着いた丁寧な話し方で、業務連絡として伝える',
    receiverVoiceInstruction: 'ややカジュアルに、納得した感じで',
    incorrectOptions: [
      '明日は深夜0時に自動的に起動します。', // 真逆の意味。語頭「明日は」。
      '何も保存せずにパソコンの電源を切ってください。', // 馬鹿馬鹿しい。語頭「何も」。
      'このシステムは毎日昼の12時に自動的にシャットダウンします。', // 別の語で始めて文字数を合わせ、内容を変化。語頭「このシステムは」。
    ],
    // ルール根拠: 3文とも異なる語で始まる。すべてjapaneseSentenceと同じ22文字。senderRoleが言いそうな発言。馬鹿馬鹿しい文・真逆の文も含む。
  },
  {
    place: 'オフィスの執務室',
    senderRole: '同僚',
    senderVoice: 'female',
    receiverRole: '同僚',
    receiverVoice: 'male',
    englishSentence: 'She usually checks her email at 8:30.', // 10語以下で指定の語句を自然に使用。カジュアルな同僚会話。
    japaneseSentence: '彼女は普段毎朝8時30分にメールを確認します。', // 指定された英文の意味を一切省略せず、自然な日本語で訳しています。
    englishReply: 'Oh, so she checks her inbox at 8:30 every day?', // 相槌と内容確認で、英文内容を想像できるヒントに。
    japaneseReply: 'ああ、毎日8時30分に彼女は受信箱を確認するんだね？', // 英文返信の内容をもれなく含む自然な日本語訳。
    scenePrompt:
      '明るい朝のオフィスで、デスクに座った女性の同僚が、別の同僚に部内のメンバーについて話しながら、ある女性社員が毎朝8時30分にメールを確認する習慣について説明している場面。周囲にはパソコンや書類があり、朝の忙しない雰囲気が感じられる。', // 場所・登場人物・状況・動機を明確に追加描写。
    senderVoiceInstruction: 'カジュアルで親しみやすく、普通のトーンで',
    receiverVoiceInstruction: '優しく、少し驚いた様子で',
    incorrectOptions: [
      '明日は普段よりも遅く8時30分に出社します。', // 「彼女は普段毎朝8時30分にメールを確認します。」と同じ文字数(23文字)・同じ内容でなく、違う語で始まる。逆の意味（遅く出社）。
      '全てのメールを夜の8時30分に削除します。', // 1文目と違う語で開始し、夜に削除（真逆の意味）。文字数一致。
      '当オフィスの椅子は毎朝8時30分に踊ります。', // 1文目・2文目と違う語で始まり、馬鹿馬鹿しい内容。文字数一致。
    ], // すべて23文字で、文頭重複や同一語不可、1つは真逆、1つは馬鹿馬鹿しい内容。
  },
  {
    place: '空港の搭乗ゲート',
    senderRole: '空港スタッフ',
    senderVoice: 'female',
    receiverRole: '乗客',
    receiverVoice: 'male',
    englishSentence: 'The announcement was made at exactly 10 o’clock.',
    // コメント: 指定された語彙を10語以内で自然な文章に使用しています。
    japaneseSentence: 'そのお知らせはちょうど10時に発表されました。',
    // コメント: englishSentenceを省略せず、自然かつ正確に日本語に翻訳しています。
    englishReply: 'Oh, so it was announced right on time.',
    // コメント: 発表が時間通りだったことを受けて、自然な相槌を含む返答です。
    japaneseReply: 'ああ、じゃあちょうど時間通りに発表されたんですね。',
    // コメント: englishReplyの内容をもれなく含み、自然な日本語訳になっています。
    scenePrompt:
      '空港の搭乗ゲート前で、空港スタッフが乗客に向かって、重要なお知らせがちょうど10時に発表されたことを伝えている。周囲には出発を待つ他の乗客がおり、アナウンスの内容に耳を傾けている場面。',
    // コメント: 場所・登場人物・文脈・背景・周囲の様子・動機を具体的に説明しています。
    senderVoiceInstruction: '穏やかで落ち着いた、丁寧な話し方',
    receiverVoiceInstruction: '少し驚いた様子で、フレンドリーに',
    incorrectOptions: [
      '青い飛行機がちょうど10時に着陸しました。',
      // コメント: 文頭が違い、正しい文と真逆の意味（着陸vs発表）で同じ文字数。
      '赤い帽子の人がちょうど10時に走り出しました。',
      // コメント: 文頭が違い、馬鹿馬鹿しい内容で同じ文字数。
      'スタッフがちょうど10時に何も伝えませんでした。',
      // コメント: 文頭が違い、正しい文の真逆の意味（伝えたvs伝えない）で同じ文字数。
    ],
    // コメント: 3文とも違う語で始まり、すべてjapaneseSentenceと同じ文字数（24文字）です。
  },
];

export default problemData;
