import { SeedProblemData } from '../src/types/problem';

/**
 * 問題データ 2
 * Generated by create-problems.ts (30 problems)
 */
const problemData: SeedProblemData[] = [
{
  place: 'クライアント企業の会議室',
  senderRole: '営業担当',
  senderVoice: 'male',
  receiverRole: 'クライアント担当者',
  receiverVoice: 'female',
  englishSentence: 'I\'d like to begin our product demonstration this morning.',
  japaneseSentence: 'それでは今朝の製品の説明を始めさせていただきます。',
  englishReply: 'Sure, I\'m ready to see the demonstration now.',
  japaneseReply: 'はい、準備できていますのでお願いします。',
  scenePrompt: '対面での会話。平日の午前中、クライアント企業の明るい会議室で、1コマ目は営業担当の男性が資料を手に立ち、これから新製品の使い方デモを始めるために説明を始めようとしている。2コマ目では、クライアント担当の女性が会議室のテーブル越しに着席し、男性の説明を前向きに受け入れる表情で返答している。まだデモは始まっておらず、会議室のテーブルにはパソコンや資料があるが、製品自体やデモの様子はまだ描かれない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "宇宙人が今朝パンケーキを焼いたらしいですが本当でしょうか。",
    "今朝の新しいサービスについてご説明いたします。",
    "古代エジプトの歴史について講演を始めますのでご注意ください。"
  ],
  difficultyLevel: null
},
{
  place: 'リビングルーム',
  senderRole: '母親',
  senderVoice: 'female',
  receiverRole: '子ども',
  receiverVoice: 'male',
  englishSentence: 'We really need to limit our devices use before dinner.',
  japaneseSentence: '夕ご飯の前は、ちゃんと電子機器の使用を控えないといけないね。',
  englishReply: 'Okay, I\'ll put my device away now.',
  japaneseReply: 'わかった、今しまうよ。',
  scenePrompt: '対面での会話。平日の夕方、明るいリビングルームで母親が立ってリビング中央にいる子どもに向かって真剣な表情で話しかけている。1コマ目では母親が家族の電子機器の使い方について注意を促している。2コマ目では子どもがリビングのソファに座り、手元のタブレットやスマートフォンを片付けようとしながら素直に返答している。まだ食事は始まっておらず、テーブルにも料理は並んでいない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "朝ご飯のあとに宿題をやるべきだと思いますか？",
    "大根の皮をむくときは宇宙服が必要だと思いますか？",
    "本棚の整理という作業は、だいたい週にどれくらいの頻度で行っていらっしゃいますか？"
  ],
  difficultyLevel: null
},
{
  place: '会社の会議室',
  senderRole: '同僚',
  senderVoice: 'female',
  receiverRole: '人事担当者',
  receiverVoice: 'male',
  englishSentence: 'Do you know if the new employee has any dietary restrictions?',
  japaneseSentence: '新しい社員に食事の制限があるか知っていますか？',
  englishReply: 'Yes, she\'s allergic to peanuts and dairy.',
  japaneseReply: 'はい、彼女は落花生と乳製品にアレルギーがあります。',
  scenePrompt: '対面での会話シーン。平日の昼、会社の会議室で女性の同僚が男性の人事担当者に新しい社員の食事制限について確認しようとしている。1コマ目では女性が資料を持ちながら男性に質問している様子。2コマ目では男性が真剣な表情で女性に説明している。まだ会議室のテーブルには食事や飲み物はなく、2人は資料以外のものを持っていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "宇宙人はやっぱりカレーが苦手だと思いますか？",
    "新しい社員はどこの出身なのか知っていますか？",
    "本日の天気予報は雨が降る予定となっておりますでしょうか？"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの会議室',
  senderRole: '同僚',
  senderVoice: 'female',
  receiverRole: 'プロジェクトマネージャー',
  receiverVoice: 'male',
  englishSentence: 'I\'m concerned about the potential disadvantages of this new proposal.',
  japaneseSentence: 'この新しい提案には、どんな不利な点があるのか心配です。',
  englishReply: 'I understand, what disadvantages are you thinking of?',
  japaneseReply: 'わかりました。どんな不利な点を考えていますか？',
  scenePrompt: '対面での会話。平日の午前中、オフィスの会議室。1コマ目では女性の同僚がテーブル越しに真剣な表情で男性マネージャーにプロジェクト提案のリスクについて話しかけている。2コマ目では男性マネージャーが女性の話を受け止め、穏やかな表情で返答している。まだ具体的なリスクや資料はテーブル上に出ていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "桜の開花時期は例年より早くなるのでしょうか？",
    "宇宙人は今日も地球でかくれんぼしているのでしょうか？",
    "この新しい計画においては費用が増加することになるのでしょうか？"
  ],
  difficultyLevel: null
},
{
  place: '会議室',
  senderRole: '同僚',
  senderVoice: 'male',
  receiverRole: '同僚',
  receiverVoice: 'female',
  englishSentence: 'We seem to have some disagreements about the project timeline.',
  japaneseSentence: 'どうやらプロジェクトの進め方について意見が食い違っているようですね。',
  englishReply: 'Yes, our opinions on the deadlines differ.',
  japaneseReply: 'はい、締め切りについて考えが違うみたいです。',
  scenePrompt: '対面での会話。平日の午前、オフィスの会議室で二人の同僚がテーブルを挟んで座っている。1コマ目では男性が真剣な表情で女性に向かい、意見の食い違いについて静かに指摘している。2コマ目では女性が落ち着いた表情で男性に返答している。まだ議論は始まったばかりで、テーブルには資料や飲み物は置かれていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "最近は新しい部署ができたと聞きましたが本当ですか？",
    "宇宙人が昨日会社に来て会議を仕切ったって本当ですか？",
    "ペンギンという動物が砂漠という過酷な環境で生活していくことが可能である理由について、あなたは何かご存知でしょうか？"
  ],
  difficultyLevel: null
},
{
  place: '自宅のキッチン',
  senderRole: '母親',
  senderVoice: 'male',
  receiverRole: '家族（子ども）',
  receiverVoice: 'female',
  englishSentence: 'I’m sorry, lunch is a complete disaster today.',
  japaneseSentence: 'ごめん、今日のお昼ご飯はめちゃくちゃになっちゃった。',
  englishReply: 'That’s okay, Dad. We can just order pizza.',
  japaneseReply: '大丈夫だよ、お父さん。ピザを頼めばいいよ。',
  scenePrompt: '対面での会話。土曜の昼、自宅のキッチンでのシーン。1コマ目では、男性（父親）が料理中に失敗し、キッチンのコンロ前で困った表情をしている。まだ家族は料理を食べていないし、テーブルには料理が並んでいない。2コマ目では、女性の子どもがキッチンのテーブル近くで父親に明るく声をかけている。まだピザは注文されておらず、テーブルには料理もピザもない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "宇宙人が突然現れて昼ご飯を持ち去ったんだって。",
    "ペンギンは南極で氷の上を滑って遊ぶらしいですね。",
    "昨日の晩ご飯というものはめちゃくちゃになってしまいました。"
  ],
  difficultyLevel: null
},
{
  place: 'カフェのテーブル',
  senderRole: '友人',
  senderVoice: 'female',
  receiverRole: '友人',
  receiverVoice: 'male',
  englishSentence: 'I made an amazing discovery—a new Italian restaurant downtown.',
  japaneseSentence: 'すごい発見をしたの。街の中心に新しいイタリア料理のお店を見つけたんだよ。',
  englishReply: 'Really? Where exactly did you find it?',
  japaneseReply: '本当？それってどのあたりで見つけたの？',
  scenePrompt: '対面での会話。土曜の昼、明るいカフェのテーブルで女性が友人男性に新しく見つけたイタリア料理店についてワクワクした様子で話しかけている。1コマ目は女性が身振りを交えて男性に話している場面、2コマ目は男性が興味深そうに女性の話を聞き、質問している。まだ料理や飲み物はテーブルに運ばれていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "ペンギンが砂漠でサーフィンしている映像を見たことがありますか？",
    "宇宙人が公園でラーメンを作っているのを見かけたことはありますか？",
    "昨日の夜の遅い時間帯に新しくオープンしたフランス料理のお店を偶然見つけたんですか？"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの会議室',
  senderRole: '営業部マネージャー',
  senderVoice: 'female',
  receiverRole: '営業チームのメンバー',
  receiverVoice: 'male',
  englishSentence: 'Our sales figures have increased dramatically since last quarter.',
  japaneseSentence: '先四半期から私たちの売上は大きく伸びています。',
  englishReply: 'That\'s great—what caused such a big jump?',
  japaneseReply: 'それはすごいですね。どうしてそんなに増えたんですか？',
  scenePrompt: '対面での会話。水曜の午前、オフィスの会議室で女性の営業部マネージャーがテーブル越しに男性チームメンバーへ向けて売上が伸びた理由を説明しようとしている。1コマ目は女性が資料を手にしながら真剣な表情で話し始めているシーン。2コマ目は男性が驚きと興味を持って女性に質問している場面。まだ男性は資料には手を伸ばしておらず、会議室のテーブル上には資料以外の物はない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "桜の花が今年もきれいに咲いていました。",
    "宇宙人が会社の会議に参加して驚きましたね。",
    "今月になって新しい社員が三人も新たに入社しましたね。"
  ],
  difficultyLevel: null
},
{
  place: 'カフェのテーブル席',
  senderRole: '友人',
  senderVoice: 'female',
  receiverRole: '友人',
  receiverVoice: 'male',
  englishSentence: 'Look, I got this new eco-friendly bag yesterday.',
  japaneseSentence: '見て、昨日この環境にやさしい袋を買ったんだ。',
  englishReply: 'Nice! I love the design and the color.',
  japaneseReply: 'いいね。デザインも色もすごく好きだよ。',
  scenePrompt: '対面での会話。土曜の昼、明るいカフェのテーブル席で、女性が新しいマイバッグを手に持ち、向かい側の男性友人に嬉しそうに見せている。1コマ目では女性がバッグを見せて話しかけているが、男性はまだ反応していない。2コマ目では男性が女性のバッグを見て笑顔で褒めている。まだ飲み物や食べ物はテーブルに運ばれていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "宇宙人が昨日パンケーキを焼いたらしいんだよ。",
    "友達が新しい靴を買ったって言ってたよ。",
    "図書館で静かに泳ぐ魚を見かけたことある？"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの会議室',
  senderRole: 'プロジェクトマネージャー',
  senderVoice: 'female',
  receiverRole: 'チームメンバー',
  receiverVoice: 'male',
  englishSentence: 'We based our proposal on recent developments in economics.',
  japaneseSentence: '私たちの提案は、最近の経済学の動きをもとに作成しました。',
  englishReply: 'That makes sense, given the current economic trends.',
  japaneseReply: '今の経済の流れを考えると納得できます。',
  scenePrompt: '対面での会話。水曜の午前、オフィスの会議室で行われる。1コマ目では、女性のプロジェクトマネージャーが会議テーブル越しに、資料を手に持ち真剣な表情で新しいプロジェクト提案の根拠を説明している。2コマ目では、男性のチームメンバーがテーブルを挟んで女性の説明を聞き、納得した様子で穏やかに返答している。まだホワイトボードやプロジェクターには何も映されておらず、テーブル上に飲み物やパソコンは置かれていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "夏休みには山登りよりも海水浴が人気となっています。",
    "私たちの提案は、過去の歴史学の動きを参考にしました。",
    "宇宙人という存在が経済学の授業を担当することに決定されました。"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの自席',
  senderRole: '営業担当',
  senderVoice: 'female',
  receiverRole: '取引先の担当者',
  receiverVoice: 'male',
  englishSentence: 'I\'ve enclosed the original contract in the envelope I sent.',
  japaneseSentence: '送った封筒に契約書の原本を同封しました。',
  englishReply: 'Great, I\'ll look for the enclosed contract.',
  japaneseReply: 'わかりました。契約書を探してみます。',
  scenePrompt: '平日の午前中、電話での会話シーン。1コマ目はオフィスの自席で女性営業担当が受話器を持ち、落ち着いた表情で相手に契約書の原本を封筒に同封したことを伝えている。彼女のデスクには書類やパソコンがあるが、封筒は見えない。2コマ目は取引先企業のデスクで男性担当者が電話を耳に当て、真剣な様子で返答している。デスクにはまだ契約書はなく、男性は書類を探し始めていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "宇宙人が今日も公園でキャッチボールしています。",
    "送った小包には古い写真を同封しました。",
    "野球の試合結果を新聞で確認しました。"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの休憩スペース',
  senderRole: '同僚',
  senderVoice: 'male',
  receiverRole: '同僚',
  receiverVoice: 'female',
  englishSentence: 'The new team member seems really energetic and enthusiastic today.',
  japaneseSentence: '新しいチームのメンバー、今日はすごく元気でやる気があるみたいだね。',
  englishReply: 'Yeah, I noticed her energetic attitude too.',
  japaneseReply: 'うん、私もその元気な様子に気づいたよ。',
  scenePrompt: '対面での会話。平日の昼休み、オフィスの休憩スペースで男性の同僚が立ったまま、コーヒーカップを手にして隣の女性同僚に新しいチームメンバーの印象を話している。1コマ目では男性が明るい表情で女性に話しかけている。2コマ目では女性が微笑みながら男性の話にうなずいて返事をしている。休憩スペースにはテーブルや椅子があり、周囲に他の社員もいるが、2人は立ち話をしている。まだ新しいメンバー本人は映っていないし、二人は座っていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "ペンギンは空を飛べるようになる日が来ると思いますか？",
    "新しい部署の仕事、今日は特に忙しい日だったんですか？",
    "図書館に置いてある本は毎週必ずすべてが新しい本と入れ替わるのでしょうか？"
  ],
  difficultyLevel: null
},
{
  place: '会議室',
  senderRole: 'プロジェクトマネージャー',
  senderVoice: 'female',
  receiverRole: 'チームメンバー',
  receiverVoice: 'male',
  englishSentence: 'We need to consider environmental impacts for this new project.',
  japaneseSentence: 'この新しいプロジェクトでは環境への影響を考慮する必要があります。',
  englishReply: 'Absolutely, I’ll prioritize environmental concerns in my tasks.',
  japaneseReply: 'もちろんです。自分の担当でも環境への配慮を最優先にします。',
  scenePrompt: '対面での会話。水曜の午前、明るい会議室でプロジェクトマネージャーの女性がテーブル越しにチームメンバーの男性に新プロジェクトの環境配慮の重要性を伝えている。1コマ目では女性が真剣な表情で男性に説明している。2コマ目では男性がうなずきながら前向きに返答している。まだ資料やパソコンはテーブルに出ていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "世界中の猫が同時にジャンプしたら地球は揺れますか。",
    "この新しいプロジェクトでは利益を最優先すべきですか。",
    "私は、いつの日か非常に大きなカボチャが空高く飛翔するその時がやって来ることを本当に信じていますか。"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの新しい会議室内',
  senderRole: 'オフィスマネージャー',
  senderVoice: 'male',
  receiverRole: '新入社員',
  receiverVoice: 'female',
  englishSentence: 'This new meeting room is fully equipped with the latest technology.',
  japaneseSentence: 'この新しい会議室は最新の設備がすべてそろっています。',
  englishReply: 'That’s great—so we can use video conferencing here?',
  japaneseReply: 'それはいいですね。ここでテレビ会議もできるんですか？',
  scenePrompt: '対面での会話シーン。平日の午前中、明るく広々とした新しいオフィスの会議室で、男性のオフィスマネージャーが立ちながら、設備について説明している。背景には大きな窓や最新の会議用モニター、きれいなテーブルと椅子が見える。1コマ目では男性が説明をしており、女性新入社員はまだ話していない。2コマ目では女性新入社員がやや驚きつつ興味深そうに質問している。まだテレビ会議は始まっていないし、誰も機器には触れていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "この古い図書館には珍しい本がたくさんあります。",
    "宇宙人がこの部屋で会議を開いたことがあるそうです。",
    "昨日の公園には犬という動物が全然いなかったそうですね。"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスビルのエントランス付近',
  senderRole: '同僚（先輩社員）',
  senderVoice: 'female',
  receiverRole: '新入社員',
  receiverVoice: 'male',
  englishSentence: 'In case of emergency, the exits are clearly marked here.',
  japaneseSentence: '万が一の場合は、出口がここにしっかり表示されています。',
  englishReply: 'Thanks, I\'ll remember where the exits are.',
  japaneseReply: 'ありがとうございます。出口の場所を覚えておきます。',
  scenePrompt: '対面での会話。平日の午前、オフィスビルのエントランス付近で、1コマ目は先輩社員の女性が新入社員の男性に非常口の場所を指し示しながら案内している。背景には自動ドアや案内表示が見える。2コマ目では新入社員の男性が女性に向き直り、感謝の気持ちを込めて返答している。まだ非常口へ実際に移動はしていないし、他の社員は会話に加わっていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "宇宙人がここで餃子を焼いて食べていますが本当でしょうか。",
    "火災の時には避難訓練が行われる予定ですか。",
    "大きなカバンが棚の上に置いてありますよね。"
  ],
  difficultyLevel: null
},
{
  place: '自宅のリビング',
  senderRole: '住人',
  senderVoice: 'female',
  receiverRole: 'インターネット業者の作業員',
  receiverVoice: 'male',
  englishSentence: 'I\'m experiencing really slow internet this morning at home.',
  japaneseSentence: '今朝、家でインターネットがとても遅いんです。',
  englishReply: 'I see, let me check your connection speed.',
  japaneseReply: 'わかりました。回線の速度を確認しますね。',
  scenePrompt: '対面での会話。平日の午前中、自宅のリビングで女性の住人が困った表情でインターネット業者の男性作業員にネットの遅さを相談している。1コマ目は女性がリビングで立って話しかけており、男性はまだ調査を始めていない。2コマ目では男性作業員がリビングで女性に向き合い、作業用バッグを持ちながら丁寧に説明している。まだ機器のチェックや作業は始まっていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "最近は夜にテレビが全然映らないんですか？",
    "宇宙人が朝ご飯を作りに来たことありますか？",
    "昨日の公園において犬が元気に走っていたんですか？"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの会議室',
  senderRole: '営業担当',
  senderVoice: 'male',
  receiverRole: '上司',
  receiverVoice: 'female',
  englishSentence: 'The customer expressed concerns about our delivery schedule.',
  japaneseSentence: 'お客様が私たちの納期について不安を示されていました。',
  englishReply: 'I see, what exactly did they mention?',
  japaneseReply: 'そうなんですね。具体的にはどんなことをおっしゃっていましたか？',
  scenePrompt: '電話での会話シーン。水曜の午前、1コマ目では営業担当の男性がオフィスの会議室でスマートフォンを耳に当て、やや困った表情で上司に顧客の不満を伝えようとしている。2コマ目では女性の上司が自席のデスクに座り、電話を手に落ち着いた様子で男性の話を聞いている。まだ具体的な内容の説明や指示は行われていない。会議室やデスク上には書類やパソコンがあるが、他の人は映っていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "宇宙人が昨日カフェでパンケーキを焼いていたそうですよ。",
    "営業担当が商品の値段に不満を持っていました。",
    "公園のベンチで猫が昼寝しているのを見かけました。"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの休憩スペース',
  senderRole: '同僚',
  senderVoice: 'male',
  receiverRole: '同僚',
  receiverVoice: 'female',
  englishSentence: 'The new exhibition at the museum was absolutely fascinating.',
  japaneseSentence: '新しい博物館の展示は本当におもしろかったよ。',
  englishReply: 'Really? What part did you find most interesting?',
  japaneseReply: '本当？どの部分が一番おもしろかったの？',
  scenePrompt: '対面での会話。平日の昼休み、明るいオフィスの休憩スペースで男性の同僚が立ち話をしている。1コマ目では男性が女性の同僚に向かって新しい展示会について熱心に話しかけている。2コマ目では、隣のテーブルに座る女性が興味を持って男性に質問している。まだ二人は展示会の詳細について話し始めていない。テーブルの上にはコーヒーカップや書類はない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "巨大なペンギンが会議室で踊っていたんだってさ。",
    "美術館の新しいカフェはとても人気だったよ。",
    "電車の遅延情報は毎日確認していますか。"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの自席',
  senderRole: '上司',
  senderVoice: 'female',
  receiverRole: '部下',
  receiverVoice: 'male',
  englishSentence: 'Could you organize these folders for the new project?',
  japaneseSentence: 'この新しいプロジェクト用の書類を整理してもらえますか？',
  englishReply: 'Sure, I’ll sort the folders right away.',
  japaneseReply: 'はい、すぐに整理します。',
  scenePrompt: '対面での会話。火曜の午前、明るいオフィスで、1コマ目は女性の上司が自席で書類の束を手に持ち、近くに立つ男性の部下に新しいプロジェクト用のフォルダ整理を依頼している。背景にはデスクやパソコン、棚があり、他の社員も少し見える。2コマ目ではその男性が上司の席のすぐそばで、真剣な表情で返答している。まだ男性は書類を受け取っておらず、整理も始まっていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "ペンギンは空を飛ぶことができるのですか？",
    "宇宙人は実在すると思いますがどう思いますか？",
    "この会議の開始予定時刻を後ほど別の時間に変更していただくことは可能でしょうか？"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの会議室',
  senderRole: 'マネージャー',
  senderVoice: 'female',
  receiverRole: 'チームメンバー',
  receiverVoice: 'male',
  englishSentence: 'Building a strong foundation is key to our project\'s success.',
  japaneseSentence: 'しっかりとした土台を作ることが、私たちのプロジェクトの成功の鍵です。',
  englishReply: 'Absolutely, the foundation sets the whole project\'s tone.',
  japaneseReply: '本当にそうですね。土台がプロジェクト全体の方向性を決めます。',
  scenePrompt: '対面での会話。水曜の午前、オフィスの明るい会議室。1コマ目では女性マネージャーが会議室で真剣な表情で男性チームメンバーに話しかけている。テーブルには資料やパソコンはまだ置かれていない。2コマ目では男性チームメンバーが同じ会議室のテーブル席で、女性の話を受けて前向きにうなずきながら返答している。まだ会議の議事録やプロジェクト資料などは広げられていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "冷蔵庫の中にある牛乳が、今日の天気を左右するらしいですね。",
    "宇宙人が毎晩ダンスを踊ることが、地球の平和の鍵らしいですよね。",
    "新しい資料を幅広く集めていくことが、私たちの今後の研究の更なる進展のための重要な鍵となります。"
  ],
  difficultyLevel: null
},
{
  place: '会議室',
  senderRole: '人事マネージャー',
  senderVoice: 'male',
  receiverRole: '新入社員',
  receiverVoice: 'female',
  englishSentence: 'Our founding principles focus on teamwork and innovation.',
  japaneseSentence: '私たちの設立の理念は、協力と新しい発想を大切にすることです。',
  englishReply: 'I see, teamwork was important from the start.',
  japaneseReply: 'なるほど、最初から協力が大事だったんですね。',
  scenePrompt: '対面での会話シーン。平日の午前中、明るい会議室で男性の人事マネージャーがテーブル越しに新入社員の女性へ会社の設立理念を説明している。1コマ目では男性が落ち着いた表情で女性に語りかけている。2コマ目では女性が向かい側で理解を示すように頷きながら返答している。まだ資料やパソコン、飲み物などはテーブルの上に置かれていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "経営方針の変更は社員の意見を最優先します。",
    "宇宙人がピザを発明したという説は本当でしょうか。",
    "図書館のご利用いただける時間帯は毎日午後五時までとなっております。"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの会議室',
  senderRole: '経理マネージャー',
  senderVoice: 'female',
  receiverRole: '営業部長',
  receiverVoice: 'male',
  englishSentence: 'We detected a potentially fraudulent transaction this morning.',
  japaneseSentence: '今朝、不審な取引を検知しました。',
  englishReply: 'A fraudulent transaction? Do you have details?',
  japaneseReply: '不審な取引ですか？詳しい内容はありますか？',
  scenePrompt: '電話での会話。水曜の午前中、1コマ目は女性の経理マネージャーがオフィスの会議室で真剣な表情でスマートフォンを耳に当て、不正取引について報告しようとしている。2コマ目は男性の営業部長が自分のオフィスデスクで電話を受け、驚きつつも冷静に詳細を尋ねる様子。まだ具体的な資料の提示や調査は始まっていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "宇宙人が朝ごはんを作りました。",
    "昨夜、不審なメールが届きました。",
    "新しい靴下を買いに行きました。"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの給湯室',
  senderRole: '同僚',
  senderVoice: 'male',
  receiverRole: '同僚',
  receiverVoice: 'female',
  englishSentence: 'Are you coming to the team gathering this Saturday afternoon?',
  japaneseSentence: '今度の土曜日の午後のチームの集まりに来る？',
  englishReply: 'Yes, I’ll be at the gathering for sure.',
  japaneseReply: 'うん、絶対に行くよ。',
  scenePrompt: '対面での会話。金曜の昼休み、明るいオフィスの給湯室で男性の同僚が女性の同僚に週末のチーム集まりへの参加を誘う。1コマ目では男性がカップを手に持ち、女性に優しく話しかけている。2コマ目では女性が笑顔で男性に返事をしている。まだどちらも飲み物を飲んでおらず、会話中に他の人は写っていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "宇宙人が土曜日にピザを配るって本当なのかな？",
    "映画館で新作の上映会があるって知ってる？",
    "春になったら桜が咲く場所を探したことある？"
  ],
  difficultyLevel: null
},
{
  place: 'カフェのテーブル席',
  senderRole: '友人',
  senderVoice: 'female',
  receiverRole: '友人',
  receiverVoice: 'male',
  englishSentence: 'Do you think we need any special gear for tomorrow\'s hike?',
  japaneseSentence: '明日のハイキングに何か特別な道具が必要だと思う？',
  englishReply: 'Just sturdy shoes and maybe a rain jacket.',
  japaneseReply: '丈夫な靴と、あとは雨が降るかもしれないから雨具くらいかな。',
  scenePrompt: '対面での会話。土曜の昼、明るいカフェのテーブル席で女性が男性の友人と向かい合って座り、週末のハイキングについて必要な装備を確認しようとしている。1コマ目では女性が少し心配そうに男性へ質問している。2コマ目では男性がリラックスした様子で女性にアドバイスを返している。まだハイキングの装備やコーヒーなどの飲み物はテーブルに出ていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "新しい宇宙人の友達が今日来るって本当なのですか？",
    "最近買った登山靴は履き心地が良いですか？",
    "ペンギンは空を飛ぶことができると思いますか？"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの会議室',
  senderRole: '上司',
  senderVoice: 'female',
  receiverRole: '部下',
  receiverVoice: 'male',
  englishSentence: 'Could you generate a sales report by this afternoon?',
  japaneseSentence: '今日の午後までに売上報告書を作ってもらえますか？',
  englishReply: 'Sure, I\'ll start generating the sales report now.',
  japaneseReply: 'はい、今から売上報告書の作成を始めます。',
  scenePrompt: '対面での会話シーン。火曜の午前中、明るいオフィスの会議室で、1コマ目は女性上司がテーブル越しに向かい合う男性部下に依頼の話をしている。女性は資料を手にして真剣な表情。2コマ目は男性部下が会議室のテーブル越しに女性上司へ前向きな返答をしている。まだ書類やパソコンはテーブル上に出ておらず、報告書作成作業も始まっていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "宇宙人は午後になると眠くなるって本当なのでしょうか？",
    "明日の午前中に会議資料を用意できますか？",
    "ペンギンは空を飛ぶことができると思いますか？"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの休憩スペース',
  senderRole: '同僚',
  senderVoice: 'female',
  receiverRole: '同僚',
  receiverVoice: 'male',
  englishSentence: 'Do you think our generation values work-life balance differently?',
  japaneseSentence: '私たちの世代は仕事と私生活のバランスを違ったふうに考えていると思う？',
  englishReply: 'Definitely, older generations seem to prioritize work more.',
  japaneseReply: 'うん、上の世代は仕事をもっと大事にしているように感じるよ。',
  scenePrompt: '対面での会話。平日の昼休み、オフィスの休憩スペースで女性の同僚がテーブル越しに男性の同僚へ話しかけている。1コマ目では女性がやや真剣な表情で男性に価値観について問いかけている。2コマ目では男性が女性の問いに考えながら答えている。まだ食事や飲み物はテーブルに置かれていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "ペンギンは空を飛ぶために毎日ジャンプしているって本当ですか？",
    "新しいカメラの使い方を誰かに教えてもらったことがありますか？",
    "海外旅行の計画というものは、友達と一緒に立てることが多いのでしょうか？"
  ],
  difficultyLevel: null
},
{
  place: 'カフェのカウンター前',
  senderRole: '同僚',
  senderVoice: 'male',
  receiverRole: '店員',
  receiverVoice: 'female',
  englishSentence: 'Hi, do you have any gluten-free lunch options today?',
  japaneseSentence: 'こんにちは、今日、小麦を使っていない昼食メニューはありますか？',
  englishReply: 'Yes, our chicken salad is gluten-free.',
  japaneseReply: 'はい、チキンサラダは小麦を使っていません。',
  scenePrompt: '対面での会話。平日の昼、明るいカフェのカウンター前で男性の同僚が店員に食事制限について相談している。1コマ目では男性がカウンター越しに店員へ質問している様子で、まだ注文はしていない。2コマ目ではカウンター内の女性店員が笑顔で答えている。まだ料理は提供されておらず、テーブルにも何も置かれていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "映画館で新作アニメの上映が始まったのをご存知ですか？",
    "宇宙人が今日のランチに来る予定は本当にあるのでしょうか？",
    "明日の夕食に魚を使った新しいメニューは他に何かございますでしょうか？"
  ],
  difficultyLevel: null
},
{
  place: 'オフィスの休憩スペース',
  senderRole: '同僚',
  senderVoice: 'female',
  receiverRole: '同僚',
  receiverVoice: 'male',
  englishSentence: 'I bought this cake to gratify everyone after a busy week.',
  japaneseSentence: '忙しい一週間のあと、みんなに喜んでもらいたくてこのケーキを買ってきました。',
  englishReply: 'That’s so thoughtful—thanks for bringing cake!',
  japaneseReply: '気が利くね。ケーキを持ってきてくれてありがとう。',
  scenePrompt: '対面での会話。金曜の午後、オフィスの明るい休憩スペースでのシーン。1コマ目では女性の同僚がテーブルの上にケーキの箱を置き、笑顔で向かいの男性に話しかけている。2コマ目では男性の同僚が驚きつつも嬉しそうな表情で女性に感謝の気持ちを伝えている。まだケーキは箱の中にあり、食べ始めていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "宇宙人が週末になるとピザを配るという噂を信じますか？",
    "新しい靴下を買うと運気が上がると聞いたことがあります。",
    "家族の幸せのために毎週金曜日には必ず花を買うと私は心に決めているのです。"
  ],
  difficultyLevel: null
},
{
  place: '会社の社員食堂のテーブル',
  senderRole: '同僚',
  senderVoice: 'male',
  receiverRole: '同僚',
  receiverVoice: 'female',
  englishSentence: 'Have you tried the grilled chicken sandwich here at lunch?',
  japaneseSentence: 'ここでお昼に焼き鳥サンドイッチを食べたことある？',
  englishReply: 'Yes, the grilled chicken is really tasty.',
  japaneseReply: 'うん、焼き鳥がすごくおいしいよ。',
  scenePrompt: '対面での会話。平日の昼、会社の社員食堂のテーブルで男性の同僚が女性の同僚にランチメニューについて話しかけている。1コマ目では男性が明るい表情で女性におすすめメニューについて尋ねている。2コマ目では女性が微笑みながら答えている。まだ食事はテーブルに運ばれておらず、2人の前に料理は並んでいない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "この近くに美味しいうどん屋さん知ってる？",
    "宇宙人が焼き鳥サンドを作れると思いますか？",
    "最近ペンギンが登場する映画をご覧になったことはありますか？"
  ],
  difficultyLevel: null
},
{
  place: '会議室',
  senderRole: '営業担当',
  senderVoice: 'female',
  receiverRole: '法務担当',
  receiverVoice: 'male',
  englishSentence: 'Do we need a guarantor for this new supplier contract?',
  japaneseSentence: 'この新しい仕入先との契約には保証人が必要ですか？',
  englishReply: 'No, a guarantor isn\'t required this time.',
  japaneseReply: 'いいえ、今回は保証人は必要ありません。',
  scenePrompt: '電話での会話シーン。火曜の午前、1コマ目は営業担当の女性が明るい会議室でスマートフォンを耳に当て、真剣な表情で契約内容について確認している。机には資料が数枚置かれているが、まだ契約書や保証人の書類は出ていない。2コマ目では法務担当の男性が自席のデスクで電話に応じている。オフィスの背景には書類棚やパソコンがあり、男性は落ち着いた様子で返答している。まだ女性は返答を聞いていないし、書類のやり取りも始まっていない。',
  senderVoiceInstruction: null,
  receiverVoiceInstruction: null,
  incorrectOptions: [
    "宇宙人が契約書にサインする場合あるのでしょうか？",
    "この新しい仕入先は海外企業ですか？",
    "雨の日は電車が遅れることが多いですか？"
  ],
  difficultyLevel: null
}
];

export default problemData;
