import { SeedProblemData } from '../src/types/problem';

const problems: SeedProblemData[] = [
  {
    englishSentence: 'Can we start the meeting now?',
    japaneseSentence: '今、会議を始めてもいいですか？',
    japaneseReply: 'はい、始めましょう。',
    englishReply: 'Yes, let’s start.',
    incorrectOptions: [
      '明日の資料は準備できましたか？',
      '週末に一緒に出かけませんか？',
      'この本を貸してくれますか？',
    ],
    senderVoice: 'male',
    senderRole: '上司',
    receiverVoice: 'female',
    receiverRole: '部下',
    place: '会議室',
  },
  {
    englishSentence: 'Could you review this document later?',
    japaneseSentence: 'この資料を後で確認していただけますか？',
    japaneseReply: 'はい、午後に確認します。',
    englishReply: 'Yes, I’ll check it this afternoon.',
    incorrectOptions: [
      '週末に映画を見に行きませんか？',
      'その新しいカフェに行きましたか？',
      '今日はどこで昼ご飯を食べますか？',
    ],
    senderVoice: 'female',
    senderRole: '部下',
    receiverVoice: 'male',
    receiverRole: '上司',
    place: '会社',
  },
  {
    englishSentence: 'When is the next team meeting?',
    japaneseSentence: '次のチーム会議はいつですか？',
    japaneseReply: '来週の火曜日です。',
    englishReply: 'It’s next Tuesday.',
    incorrectOptions: [
      '明日の天気はどうなりそうですか？',
      '最近新しい趣味を始めましたか？',
      '週末は何をする予定ですか？',
    ],
    senderVoice: 'male',
    senderRole: '社員',
    receiverVoice: 'female',
    receiverRole: '社員',
    place: 'オフィス',
  },
  {
    englishSentence: 'Could you share the report with me?',
    japaneseSentence: 'その報告書を私に共有していただけますか？',
    japaneseReply: 'はい、すぐに送ります。',
    englishReply: 'Yes, I’ll send it right away.',
    incorrectOptions: [
      '今週末に遊びに行きませんか？',
      '昨日の試合は見ましたか？',
      '新しい映画を一緒に見ませんか？',
    ],
    senderVoice: 'female',
    senderRole: '同僚',
    receiverVoice: 'male',
    receiverRole: '同僚',
    place: '会社',
  },
  {
    englishSentence: 'Do you have time for a call?',
    japaneseSentence: '電話する時間はありますか？',
    japaneseReply: 'はい、五分後なら大丈夫です。',
    englishReply: 'Yes, in five minutes is fine.',
    incorrectOptions: [
      '明日の昼にランチ行きませんか？',
      '最近読んだ本は面白かったですか？',
      '週末に買い物に行きませんか？',
    ],
    senderVoice: 'male',
    senderRole: '同僚',
    receiverVoice: 'female',
    receiverRole: '同僚',
    place: '会社',
  },
  {
    englishSentence: 'Please send me the updated file.',
    japaneseSentence: '更新されたファイルを送ってください。',
    japaneseReply: 'はい、送信しました。',
    englishReply: 'Yes, I just sent it.',
    incorrectOptions: [
      '今週末に旅行へ行きませんか？',
      '昨日は忙しかったですか？',
      '今度一緒に飲みに行きませんか？',
    ],
    senderVoice: 'female',
    senderRole: '部下',
    receiverVoice: 'male',
    receiverRole: '上司',
    place: '会社',
  },
  {
    englishSentence: 'When is the project deadline?',
    japaneseSentence: 'プロジェクトの締め切りはいつですか？',
    japaneseReply: '来月の十五日です。',
    englishReply: 'It’s the fifteenth of next month.',
    incorrectOptions: [
      '明日一緒に散歩しませんか？',
      'この映画をもう見ましたか？',
      '最近体調はどうですか？',
    ],
    senderVoice: 'male',
    senderRole: '部下',
    receiverVoice: 'female',
    receiverRole: '上司',
    place: '会社',
  },
  {
    englishSentence: 'Can we postpone the meeting to tomorrow?',
    japaneseSentence: '会議を明日に延期できますか？',
    japaneseReply: 'はい、可能です。',
    englishReply: 'Yes, that’s possible.',
    incorrectOptions: [
      '週末に何をする予定ですか？',
      'その服はどこで買いましたか？',
      '今度の休みに遊びませんか？',
    ],
    senderVoice: 'female',
    senderRole: '上司',
    receiverVoice: 'male',
    receiverRole: '部下',
    place: '会社',
  },
  {
    englishSentence: 'Did you check the client’s email?',
    japaneseSentence: 'クライアントからのメールを確認しましたか？',
    japaneseReply: 'はい、確認しました。',
    englishReply: 'Yes, I checked it.',
    incorrectOptions: [
      '今度の週末は暇ですか？',
      '明日は雨が降りそうですか？',
      '最近新しいゲームを試しましたか？',
    ],
    senderVoice: 'male',
    senderRole: '社員',
    receiverVoice: 'female',
    receiverRole: '社員',
    place: '会社',
  },
  {
    englishSentence: 'Could you prepare slides for tomorrow?',
    japaneseSentence: '明日のためにスライドを準備してもらえますか？',
    japaneseReply: 'はい、今日中に作ります。',
    englishReply: 'Yes, I’ll finish them today.',
    incorrectOptions: [
      '昨日はどこに行きましたか？',
      '今度の旅行は楽しみですね。',
      '週末に会いませんか？',
    ],
    senderVoice: 'female',
    senderRole: '上司',
    receiverVoice: 'male',
    receiverRole: '部下',
    place: '会社',
  },
  {
    englishSentence: 'Can we move the deadline forward?',
    japaneseSentence: '締め切りを前倒しできますか？',
    japaneseReply: 'はい、調整してみます。',
    englishReply: 'Yes, I’ll try to adjust it.',
    incorrectOptions: [
      '今度の週末に遊びませんか？',
      '最近新しい本を読みましたか？',
      '明日の天気はどうなりそうですか？',
    ],
    senderVoice: 'male',
    senderRole: '上司',
    receiverVoice: 'female',
    receiverRole: '部下',
    place: '会社',
  },
  {
    englishSentence: 'Did you finish the budget report?',
    japaneseSentence: '予算の報告書は終わりましたか？',
    japaneseReply: 'はい、完成しました。',
    englishReply: 'Yes, it’s completed.',
    incorrectOptions: [
      '昨日は楽しかったですか？',
      '新しい映画をもう見ましたか？',
      '週末は何をする予定ですか？',
    ],
    senderVoice: 'female',
    senderRole: '上司',
    receiverVoice: 'male',
    receiverRole: '部下',
    place: '会社',
  },
  {
    englishSentence: 'Please confirm the meeting schedule soon.',
    japaneseSentence: '会議の日程を早めに確認してください。',
    japaneseReply: 'はい、確認します。',
    englishReply: 'Yes, I’ll confirm it.',
    incorrectOptions: [
      '昨日の試合は見ましたか？',
      '週末にどこか行きませんか？',
      '最近どうしていますか？',
    ],
    senderVoice: 'male',
    senderRole: '上司',
    receiverVoice: 'female',
    receiverRole: '部下',
    place: '会社',
  },
  {
    englishSentence: 'Could you call the client today?',
    japaneseSentence: '今日、クライアントに電話してもらえますか？',
    japaneseReply: 'はい、すぐに連絡します。',
    englishReply: 'Yes, I’ll call right away.',
    incorrectOptions: [
      '明日遊びに行きませんか？',
      '昨日は雨が降りましたか？',
      '最近新しい服を買いましたか？',
    ],
    senderVoice: 'female',
    senderRole: '上司',
    receiverVoice: 'male',
    receiverRole: '部下',
    place: '会社',
  },
  {
    englishSentence: 'When will the results be ready?',
    japaneseSentence: '結果はいつ準備できますか？',
    japaneseReply: '明日には準備できます。',
    englishReply: 'They’ll be ready tomorrow.',
    incorrectOptions: [
      '今週末に出かけませんか？',
      '昨日は楽しかったですか？',
      '新しいレストランに行きませんか？',
    ],
    senderVoice: 'male',
    senderRole: '部下',
    receiverVoice: 'female',
    receiverRole: '上司',
    place: '会社',
  },
  {
    englishSentence: 'Can you book the meeting room?',
    japaneseSentence: '会議室を予約してもらえますか？',
    japaneseReply: 'はい、予約しておきます。',
    englishReply: 'Yes, I’ll book it.',
    incorrectOptions: ['昨日は眠れましたか？', '今週末に会えますか？', '最近どうしていましたか？'],
    senderVoice: 'female',
    senderRole: '上司',
    receiverVoice: 'male',
    receiverRole: '部下',
    place: '会社',
  },
  {
    englishSentence: 'Did you send the invoice yesterday?',
    japaneseSentence: '昨日、請求書を送りましたか？',
    japaneseReply: 'はい、送りました。',
    englishReply: 'Yes, I sent it.',
    incorrectOptions: [
      '昨日の夜は眠れましたか？',
      '今度映画を見に行きませんか？',
      '新しい本を買いましたか？',
    ],
    senderVoice: 'male',
    senderRole: '上司',
    receiverVoice: 'female',
    receiverRole: '部下',
    place: '会社',
  },
  {
    englishSentence: 'Please check the numbers again carefully.',
    japaneseSentence: '数字をもう一度よく確認してください。',
    japaneseReply: 'はい、確認します。',
    englishReply: 'Yes, I’ll check again.',
    incorrectOptions: [
      '今度の週末に遊びませんか？',
      '昨日の映画はどうでしたか？',
      '明日は暇ですか？',
    ],
    senderVoice: 'female',
    senderRole: '上司',
    receiverVoice: 'male',
    receiverRole: '部下',
    place: '会社',
  },
  {
    englishSentence: 'Can you finish this task today?',
    japaneseSentence: 'この作業を今日終えられますか？',
    japaneseReply: 'はい、終わらせます。',
    englishReply: 'Yes, I’ll finish it today.',
    incorrectOptions: [
      '明日映画を見に行きませんか？',
      '最近体調はどうですか？',
      '昨日は眠れましたか？',
    ],
    senderVoice: 'male',
    senderRole: '上司',
    receiverVoice: 'female',
    receiverRole: '部下',
    place: '会社',
  },
  {
    englishSentence: 'Could you join the call at three?',
    japaneseSentence: '三時の電話会議に参加していただけますか？',
    japaneseReply: 'はい、参加します。',
    englishReply: 'Yes, I’ll join it.',
    incorrectOptions: [
      '昨日は忙しかったですか？',
      '週末にどこか出かけませんか？',
      '最近新しい服を買いましたか？',
    ],
    senderVoice: 'female',
    senderRole: '上司',
    receiverVoice: 'male',
    receiverRole: '部下',
    place: '会社',
  },
  {
    englishSentence: 'When will the presentation be ready?',
    japaneseSentence: 'プレゼンはいつ準備できますか？',
    japaneseReply: '金曜日までに準備します。',
    englishReply: 'It’ll be ready by Friday.',
    incorrectOptions: [
      '昨日は映画を見ましたか？',
      '週末に集まりませんか？',
      '最近何をしていますか？',
    ],
    senderVoice: 'male',
    senderRole: '上司',
    receiverVoice: 'female',
    receiverRole: '部下',
    place: '会社',
  },
  {
    englishSentence: 'Could you send me the contract today?',
    japaneseSentence: '今日、契約書を送っていただけますか？',
    japaneseReply: 'はい、すぐに送ります。',
    englishReply: 'Yes, I’ll send it right away.',
    incorrectOptions: [
      '昨日は雨が降りましたか？',
      '今度の週末に遊びませんか？',
      '最近映画を見ましたか？',
    ],
    senderVoice: 'female',
    senderRole: '上司',
    receiverVoice: 'male',
    receiverRole: '部下',
    place: '会社',
  },
  {
    englishSentence: 'Do we need to update the plan?',
    japaneseSentence: '計画を更新する必要がありますか？',
    japaneseReply: 'はい、少し修正が必要です。',
    englishReply: 'Yes, some adjustments are needed.',
    incorrectOptions: [
      '今度一緒に映画を見ませんか？',
      '昨日は忙しかったですか？',
      '最近どうしていますか？',
    ],
    senderVoice: 'male',
    senderRole: '部下',
    receiverVoice: 'female',
    receiverRole: '上司',
    place: '会社',
  },
  {
    englishSentence: 'Please prepare the agenda by tomorrow.',
    japaneseSentence: '明日までに議題を準備してください。',
    japaneseReply: 'はい、準備します。',
    englishReply: 'Yes, I’ll prepare it.',
    incorrectOptions: [
      '昨日は何をしていましたか？',
      '週末に買い物しませんか？',
      '新しいカフェに行きましたか？',
    ],
    senderVoice: 'female',
    senderRole: '上司',
    receiverVoice: 'male',
    receiverRole: '部下',
    place: '会社',
  },
  {
    englishSentence: 'When will the final version be ready?',
    japaneseSentence: '最終版はいつ準備できますか？',
    japaneseReply: '来週の月曜日です。',
    englishReply: 'It’ll be ready next Monday.',
    incorrectOptions: [
      '昨日のドラマは見ましたか？',
      '週末は何をしましたか？',
      '最近どうしていましたか？',
    ],
    senderVoice: 'male',
    senderRole: '上司',
    receiverVoice: 'female',
    receiverRole: '部下',
    place: '会社',
  },
  {
    englishSentence: 'Could you summarize the main points?',
    japaneseSentence: '要点をまとめてもらえますか？',
    japaneseReply: 'はい、簡単にまとめます。',
    englishReply: 'Yes, I’ll summarize briefly.',
    incorrectOptions: ['昨日は眠れましたか？', '今度映画を見ませんか？', '週末は出かけますか？'],
    senderVoice: 'female',
    senderRole: '上司',
    receiverVoice: 'male',
    receiverRole: '部下',
    place: '会社',
  },
  {
    englishSentence: 'Did you receive the client’s feedback?',
    japaneseSentence: 'クライアントのフィードバックを受け取りましたか？',
    japaneseReply: 'はい、受け取りました。',
    englishReply: 'Yes, I received it.',
    incorrectOptions: [
      '昨日の映画は面白かったですか？',
      '週末にどこか行きませんか？',
      '最近新しい服を買いましたか？',
    ],
    senderVoice: 'male',
    senderRole: '社員',
    receiverVoice: 'female',
    receiverRole: '社員',
    place: '会社',
  },
  {
    englishSentence: 'Can you update the file by tonight?',
    japaneseSentence: '今夜までにファイルを更新できますか？',
    japaneseReply: 'はい、更新します。',
    englishReply: 'Yes, I’ll update it.',
    incorrectOptions: [
      '明日遊びに行きませんか？',
      '昨日は眠れましたか？',
      '最近どうしていますか？',
    ],
    senderVoice: 'female',
    senderRole: '上司',
    receiverVoice: 'male',
    receiverRole: '部下',
    place: '会社',
  },
  {
    englishSentence: 'Please send the minutes to everyone.',
    japaneseSentence: '議事録を皆に送ってください。',
    japaneseReply: 'はい、すぐに送ります。',
    englishReply: 'Yes, I’ll send them now.',
    incorrectOptions: [
      '昨日はどこに行きましたか？',
      '週末は楽しかったですか？',
      '最近何をしていますか？',
    ],
    senderVoice: 'male',
    senderRole: '上司',
    receiverVoice: 'female',
    receiverRole: '部下',
    place: '会社',
  },
  {
    englishSentence: 'When is the next client meeting?',
    japaneseSentence: '次のクライアントとの会議はいつですか？',
    japaneseReply: '木曜日の午後です。',
    englishReply: 'It’s Thursday afternoon.',
    incorrectOptions: [
      '昨日は雨が降りましたか？',
      '週末に何をしましたか？',
      '最近体調はどうですか？',
    ],
    senderVoice: 'female',
    senderRole: '部下',
    receiverVoice: 'male',
    receiverRole: '上司',
    place: '会社',
  },
  {
    englishSentence: 'Could you check the figures once more?',
    japaneseSentence: '数字をもう一度確認していただけますか？',
    japaneseReply: 'はい、確認します。',
    englishReply: 'Yes, I’ll check them.',
    incorrectOptions: [
      '昨日は眠れましたか？',
      '今度映画を見に行きませんか？',
      '週末に集まりませんか？',
    ],
    senderVoice: 'male',
    senderRole: '上司',
    receiverVoice: 'female',
    receiverRole: '部下',
    place: '会社',
  },
];

export default problems;
