import { SeedProblemData } from '../src/types/problem';

/**
 * 問題データ 2
 * Generated by GPT API (3 problems)
 */
const problemData: SeedProblemData[] = [
  {
    place: '会社の会議室',
    senderRole: '人事部長',
    senderVoice: 'female',
    receiverRole: '取締役',
    receiverVoice: 'male',
    englishSentence:
      'The board raised concerns about the candidate’s limited experience in regulatory compliance.',
    // コメント: 与えられた語彙をそのまま使い、10語以下で完結している。会議室での人事部長から取締役への発言として自然。
    japaneseSentence:
      '取締役会は、その候補者の規制順守の経験が限られていることに懸念を示しました。',
    // コメント: 英文の内容を省略せず、自然な日本語で正確に翻訳している。
    englishReply: 'Oh, I see. Should we reconsider our options?',
    // コメント: 「懸念が出た」という内容に対して、理解を示し、次の行動を相談する自然な返答。熟語や慣用句を使っていない。
    japaneseReply: 'なるほど。選択肢を再検討した方がいいでしょうか？',
    // コメント: 英文の内容をもれなく含み、自然な日本語になっている。
    scenePrompt:
      '大企業の会議室で、人事部長が取締役に新しい候補者について報告している。テーブルには書類やノートパソコンが並び、他の役員たちも出席している。人事部長は選考過程で見つかった懸念点について真剣に説明しており、取締役は今後の対応を考えている。',
    // コメント: 場所、登場人物、会話の背景や動機、状況の小道具などが具体的に説明されている。
    senderVoiceInstruction: '冷静で丁寧、かつ少し慎重なトーンで話す',
    receiverVoiceInstruction: '落ち着いていて誠実なトーンで、少し考え込むように答える',
    incorrectOptions: [
      '当社の新しい規制方針についてすぐに全社員へ説明会を開きますので、ご出席をお願いいたします。',
      // コメント: japaneseSentenceよりも長く、違う語で始まり、senderRoleが言いそうな内容。質問文ではなく、文頭に余計な接続語を付けていない。
      '従来の候補者には十分な規制順守の経験があると考えていますので、特に心配はしておりません。',
      // コメント: japaneseSentenceよりも長く、真逆の意味（懸念がない）になっている。文頭も異なる。
      '全ての候補者に規制違反の経歴があるかどうか、まずは宇宙人に調査を依頼する予定です。',
      // コメント: japaneseSentenceよりも長く、馬鹿馬鹿しい内容。文頭も異なる。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '人事部長',
    senderVoice: 'female',
    receiverRole: '経営幹部',
    receiverVoice: 'male',
    englishSentence:
      'Several managers expressed concerns about the long-term impact of remote hiring on team cohesion.',
    // コメント: 10語以下で、指定された語彙をそのまま自然に使っています。職場会議で使われるフォーマルなトーンです。
    japaneseSentence:
      '複数のマネージャーが、リモート採用がチームの結束に長期的に与える影響について懸念を示しました。',
    // コメント: 指定文の内容を一切省略せず、正確かつ自然な日本語訳にしています。
    englishReply: 'Oh, that is something we need to consider carefully.',
    // コメント: senderの発言内容を推測できる自然な返答で、簡潔な単語のみを使用し、熟語や難解な表現は使っていません。
    japaneseReply: 'ああ、それは慎重に検討する必要がありますね。',
    // コメント: 英文の内容を自然に日本語に訳し、内容をもれなく含んでいます。
    scenePrompt:
      '新しい人材のリモート採用について話し合うオフィスの会議室。人事部長がチームの結束に関するマネージャーたちの懸念を経営幹部に伝えている。会議室には数人の管理職が資料を手に集まり、真剣な雰囲気で議論が進んでいる。',
    // コメント: 場面の背景や場所、登場人物の動機、状況を具体的に説明しています。英文や和文に書かれていない文脈を補っています。
    senderVoiceInstruction: '落ち着いた口調で、慎重に言葉を選んで話す',
    receiverVoiceInstruction: 'やや驚いた様子で、真剣に返答する',
    incorrectOptions: [
      '最新のリモートワーク制度が導入されたことで、全ての部署が以前よりもさらに活発に連携できるようになったと多くの社員が答えています。',
      // コメント: japaneseSentenceより明らかに長文。意味は真逆（ポジティブ）。頭の語も異なります。
      '会議の前にチーム全員で一発芸大会を開催したいという声がいくつか上がっていますが、ご検討いただけますか？',
      // コメント: japaneseSentenceより文字数が長く、馬鹿馬鹿しい内容。頭の語も異なります。
      '最近の調査結果によると、リモート採用によってチームの結束力が大幅に強化されたと評価されています。',
      // コメント: japaneseSentenceより長文で、内容は真逆（強化された）。頭の語も異なります。
    ],
  },
  {
    place: '会社の会議室',
    senderRole: '財務部長',
    senderVoice: 'female',
    receiverRole: '経営幹部',
    receiverVoice: 'male',
    englishSentence:
      'Investors cited concerns about declining profitability following the hiring freeze.',
    // ルール根拠: 10語以内で構成。会社の会議室という場所、財務部長→経営幹部という役割に合ったビジネス上の自然な発言。フォーマルなトーンで、指定された語彙を含めている。
    japaneseSentence: '投資家たちは採用凍結後の収益性低下について懸念を示しました。',
    // ルール根拠: 省略や意訳をせず、英語原文の内容をもれなく正確に、自然な日本語に翻訳している。
    englishReply: "Oh, that's troubling. Did they mention any solutions?",
    // ルール根拠: 「それは困ったね」と感情を示しつつ、何らかの解決策が挙げられたか質問している。内容から、senderの発言が「懸念や問題提起」であることが推測できる。
    japaneseReply: 'ああ、それは困りましたね。何か解決策についても言及がありましたか？',
    // ルール根拠: 英語返信の内容をもれなく、日本語で自然な形に翻訳している。
    scenePrompt:
      '大手企業の会議室で、財務部長が経営幹部に対して、最近の採用凍結により投資家が収益性の低下を懸念していることを報告している場面。会議室には資料が広がり、真剣な雰囲気が漂っている。',
    // ルール根拠: 会話文に直接書かれていない背景や登場人物、状況、場所の雰囲気を具体的に説明している。
    senderVoiceInstruction: '落ち着いていて慎重な、やや低めの声でフォーマルに話す',
    receiverVoiceInstruction: 'やや驚いたトーンで、考え込むように話す',
    incorrectOptions: [
      '最近の投資家からは、採用活動の再開を強く要望する声が多く寄せられています。',
      // ルール根拠: japaneseSentenceより文字数が明らかに長い。内容も「再開を要望」という真逆の意味。
      '新たな投資家グループが、我が社の将来的な成長性に非常に期待を寄せていると伝えてきました。',
      // ルール根拠: japaneseSentenceより文字数が長く、文頭も異なり、senderRoleが言いそうな内容。
      '当社の採用凍結で利益が飛躍的に向上したと投資家から高い評価を受けています。',
      // ルール根拠: japaneseSentenceより長い。利益が下がったのとは逆の「向上した」とすることで馬鹿馬鹿しさを演出している。文頭も異なる。
    ],
  },
];

export default problemData;
