import { SeedProblemData } from '../src/types/problem';

/**
 * 問題データ 6
 * Generated by GPT API (30 problems)
 */
const problemData: SeedProblemData[] = [
  {
    place: 'オフィスの会議室',
    senderRole: '上司',
    senderVoice: 'male',
    receiverRole: '部下',
    receiverVoice: 'female',
    englishSentence: 'Please handle this confidential document carefully.',
    // ルール根拠: 8語以内、"confidential document"を自然に含む、上司が部下に言いそうな指示文。直訳系（20%枠）。
    japaneseSentence: 'この機密文書は慎重に扱ってください。',
    // ルール根拠: 直訳系で日本語として自然。指示文で会話の流れに合っている。
    englishReply: 'Okay, I will be careful.',
    // ルール根拠: 熟語や難解な表現を避け、意味がすぐ分かる簡単な返答。
    japaneseReply: 'わかりました、気をつけます。',
    // ルール根拠: 上司の指示に対して部下が返しそうな自然な返事。
    scenePrompt:
      '明るいオフィスの会議室で、上司が部下に重要な機密文書を手渡しながら、慎重に扱うよう指示しているビジネスシーン。部下は真剣な表情で受け取っている。',
    // ルール根拠: 場所、登場人物、行動、雰囲気を具体的に記述。背景や動機も明記。
    senderVoiceInstruction: '落ち着いていて責任感のある話し方',
    receiverVoiceInstruction: '真面目で丁寧な返答',
    incorrectOptions: [
      'こちらの書類は全社員に配布してください。',
      // ルール根拠: "この"で始まらず、意味が真逆（機密文書を全体に配る）。
      'すべてのページに落書きをしておいてください。',
      // ルール根拠: "すべて"で始まり、馬鹿馬鹿しい内容（機密なのに落書き）。
      '新しい書類をすぐに作成してください。',
      // ルール根拠: "新しい"で始まり、役割に合った自然な指示だが元の意味と異なる。
    ],
  },
  {
    place: '企業の受付カウンター',
    senderRole: '受付スタッフ',
    senderVoice: 'female',
    receiverRole: '来訪者',
    receiverVoice: 'male',
    englishSentence: 'Did your manager authorize access for you?',
    // ルール根拠: 8語、"authorize access"を自然に含む疑問文。受付と来訪者の会話。熟語・慣用句系（80%枠）。
    japaneseSentence: 'あなたの上司がアクセスを許可しましたか？',
    // ルール根拠: 英語の意味をそのまま自然な日本語に訳した疑問文。
    englishReply: 'Yes, I got approval yesterday.',
    // ルール根拠: 簡単な単語で意味が明確。承認されたことを伝えている。
    japaneseReply: 'はい、昨日承認をもらいました。',
    // ルール根拠: シンプルで状況に合った返答。
    scenePrompt:
      '大きな企業の受付で、受付スタッフが来訪者にIDカードを渡す前に、上司からのアクセス許可について確認している。来訪者はビジター用バッジを受け取ろうとしている。',
    // ルール根拠: 登場人物、行動、背景、企業の受付という場面を詳細に記述。
    senderVoiceInstruction: '丁寧でハキハキとした話し方',
    receiverVoiceInstruction: '礼儀正しく自信のある返答',
    incorrectOptions: [
      '受付の近くでお待ちいただけますか？',
      // ルール根拠: "受付"で始まり、指示文で意味が異なる。
      '今日はアクセス禁止となっています。',
      // ルール根拠: "今日は"で始まり、元文の真逆（アクセス不可）。
      '巨大な魚の着ぐるみでお越しですか？',
      // ルール根拠: "巨大な"で始まり、馬鹿馬鹿しい内容（来訪者が魚の着ぐるみ）。
    ],
  },
  {
    place: '会社のITサポートデスク',
    senderRole: 'ITサポート担当者',
    senderVoice: 'male',
    receiverRole: '社員',
    receiverVoice: 'female',
    englishSentence: 'I can help with your password reset.',
    // ルール根拠: 8語以内、"password reset"を自然に含む支援の申し出。熟語・慣用句系（80%枠）。
    japaneseSentence: 'パスワードのリセットをお手伝いできます。',
    // ルール根拠: 英語の内容を自然な日本語に。申し出の文体。
    englishReply: 'Thank you, I really need help.',
    // ルール根拠: 簡単な単語、ITサポートへの感謝と助けが必要な旨を伝える自然な返答。
    japaneseReply: 'ありがとうございます、本当に助かります。',
    // ルール根拠: 丁寧で場面に合った返答。
    scenePrompt:
      'オフィスのITサポートデスクで、社員がログインできず困っているときに、ITサポート担当者がパソコンの前で親切にパスワードリセットを申し出ている状況。',
    // ルール根拠: 背景、登場人物、行動、状況を具体的に説明。
    senderVoiceInstruction: '親切で落ち着いた丁寧な話し方',
    receiverVoiceInstruction: '安心した様子で丁寧に',
    incorrectOptions: [
      'このパソコンを壁から投げてください。',
      // ルール根拠: "この"で始まり、馬鹿馬鹿しい（PCを投げる指示）。
      'パスワードの設定は一切できません。',
      // ルール根拠: "パスワード"で始まり、真逆（パスワードのリセット不可）。
      '画面に表示された手順に従ってください。',
      // ルール根拠: "画面"で始まり、サポート担当者の指示として自然な内容。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'ITマネージャー',
    senderVoice: 'female',
    receiverRole: '社員',
    receiverVoice: 'male',
    englishSentence: 'There was a data breach yesterday.',
    // 8語以内、data breachを自然に含めた文、事実報告のトーンでルール遵守
    japaneseSentence: '昨日データ漏洩がありました。',
    // data breachの直訳が分かれば理解できる。日本語も自然な報告文。
    englishReply: "Oh, I didn't know that. Thank you.",
    // 簡潔で、ITマネージャーへの社員として自然な反応。難しい語彙や熟語を使っていない。
    japaneseReply: 'ああ、それは知りませんでした。ありがとうございます。',
    // Oh,により感動を含み、報告への感謝の意も含む。
    scenePrompt:
      '大手企業のオフィス会議室。ITマネージャーがセキュリティ関連のトピックについて複数の社員に説明している。社員は深刻な話に耳を傾けている。ホワイトボードにはセキュリティ用語が書かれている。',
    // 実際の場面を描き、背景や登場人物の動機（社員への情報共有）も説明。
    senderVoiceInstruction: '落ち着いていて真剣なトーンで、重要事項を伝える口調で話す',
    receiverVoiceInstruction: '驚きを含んだ落ち着いたトーンで丁寧に返答',
    incorrectOptions: [
      '新しいカフェでランチ会を開きます。',
      // 場所や役割に合った話題だが意味が真逆
      '本日はデータが完全に守られました。',
      // 昨日データ漏洩があった→本日はデータが守られた、真逆
      '当社のサーバーはゼリーでできています。',
      // 馬鹿馬鹿しい発想で、文頭も他と被っていない
    ],
  },
  {
    place: 'オフィスのデスクエリア',
    senderRole: '上司',
    senderVoice: 'male',
    receiverRole: '部下',
    receiverVoice: 'female',
    englishSentence: 'Did you read the internal memo today?',
    // 8語以内、internal memoを自然に含めた疑問文、ルール遵守
    japaneseSentence: '今日の社内メモは読みましたか？',
    // internal memo＝社内メモ、自然な日本語の疑問文
    englishReply: 'Yes, I read it this morning.',
    // 熟語なし、簡単な語彙で自然な返答
    japaneseReply: 'はい、今朝読みました。',
    // はい、今朝読みました、と自然な返答
    scenePrompt:
      '企業のオフィスのデスクエリア。上司が部下に最新の社内メモについて確認している。デスクにはパソコンや書類が置かれている。部下は忙しそうだが、上司の質問にきちんと答えている。',
    // メモが配布された日、上司が部下に確認するという自然な背景説明
    senderVoiceInstruction: '落ち着いたが、やや急いでいる口調で話す',
    receiverVoiceInstruction: '明るく素直なトーンで返答する',
    incorrectOptions: [
      '明日の会議は午後から始まりますか？',
      // 違う話題、疑問文で文頭の語も違う
      '最近、社外のニュースは読みましたか？',
      // internal memoと逆に“社外”で真逆
      'カバがメモを届けてくれましたか？',
      // 馬鹿馬鹿しい、カバがメモを… 文頭も他と重複なし
    ],
  },
  {
    place: '会社の休憩室',
    senderRole: '人事担当者',
    senderVoice: 'female',
    receiverRole: '新入社員',
    receiverVoice: 'male',
    englishSentence: 'Please follow our corporate email policy.',
    // 8語以内、corporate email policyを自然に含めた依頼文、ルール遵守
    japaneseSentence: '会社のメール方針を守ってください。',
    // corporate email policy=会社のメール方針、自然な依頼表現
    englishReply: "Sure, I'll make sure to do that.",
    // 簡単な表現で了承、熟語なし
    japaneseReply: 'わかりました、必ず守ります。',
    // わかりました、必ず守ります。と自然な返答
    scenePrompt:
      '会社の休憩室。人事担当者が新入社員に会社のルールについて説明している。新入社員は真剣な表情で聞いている。背景にはコーヒーメーカーやお菓子が見える。',
    // 休憩室でルール説明、新人の様子や背景まで具体的に描写
    senderVoiceInstruction: '親切で落ち着いたトーンで丁寧に伝える',
    receiverVoiceInstruction: '誠実でやや緊張したトーンで返答',
    incorrectOptions: [
      'この会社ではカレーしか食べてはいけません。',
      // 馬鹿馬鹿しい、文頭もunique
      '自由に好きなメールを送ってください。',
      // 方針を守る→自由に送れ、真逆
      '社内の新しいイベントに参加してください。',
      // 違う話題、依頼文、文頭もunique
    ],
  },
  {
    place: 'オフィス',
    senderRole: 'ITサポート担当',
    senderVoice: 'female',
    receiverRole: '社員',
    receiverVoice: 'male',
    englishSentence: 'Could you update the database today?',
    // コメント: 8語以内で、直訳も可能な「update the database」を含む自然な疑問文です。
    japaneseSentence: '今日データベースを更新してもらえますか？',
    // コメント: 英文の直訳で自然な日本語訳を意識しています。
    englishReply: 'Sure, I will do it after lunch.',
    // コメント: 単純な語彙で、依頼への了承の返答と分かる簡単な英文です。
    japaneseReply: 'はい、昼食後にやります。',
    // コメント: ITサポート担当が社員にデータベース更新を依頼し、社員が了承するシーンの文脈です。
    scenePrompt:
      '広いオフィスの一角で、ITサポート担当の女性が社員の男性にパソコン越しに話しかけている。データベースの更新作業を頼んでいる場面。',
    senderVoiceInstruction: '丁寧で明るい頼みごとの口調',
    receiverVoiceInstruction: 'カジュアルで優しい口調',
    incorrectOptions: [
      '先週のデータベースを消去してもらえますか？', // コメント: 依頼内容が逆の意味です。
      '全てのパソコンを空にしてもらえますか？', // コメント: 馬鹿馬鹿しい内容（現実的にありえない依頼）です。
      '新しい社員にデータベースを見せてもらえますか？', // コメント: 意味も依頼内容も異なり、別の行動を頼んでいます。
    ],
  },
  {
    place: '会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'male',
    receiverRole: 'チームメンバー',
    receiverVoice: 'female',
    englishSentence: 'Please attach a file to the email.',
    // コメント: 8語以内で、"attach a file" を自然に含んだ指示文です。
    japaneseSentence: 'メールにファイルを添付してください。',
    // コメント: 英文の指示文に忠実な日本語訳です。
    englishReply: "Okay, I'll add it right away.",
    // コメント: シンプルな語彙で、指示に即座に従う返答です。
    japaneseReply: 'はい、すぐに追加します。',
    // コメント: プロジェクトマネージャーが会議中に資料の添付を指示し、メンバーが対応を約束する場面です。
    scenePrompt:
      '会議室で、男性のプロジェクトマネージャーが女性のチームメンバーに資料をメール添付するよう頼んでいる。テーブルにはノートパソコンや書類が並んでいる。',
    senderVoiceInstruction: '落ち着いていて指示的な口調',
    receiverVoiceInstruction: '素直で明るい返事',
    incorrectOptions: [
      'メールを全員に転送してください。', // コメント: 指示内容が異なる（転送）。
      'ファイルを紙で配ってください。', // コメント: 馬鹿馬鹿しい（デジタルの指示に紙で対応）。
      'メールに何も添付しないでください。', // コメント: 真逆の意味（添付しないよう指示）。
    ],
  },
  {
    place: '銀行窓口',
    senderRole: '銀行員',
    senderVoice: 'female',
    receiverRole: '顧客',
    receiverVoice: 'male',
    englishSentence: 'We need your digital signature here.',
    // コメント: 8語以内で、"digital signature" を含むフォーマルな依頼文です。熟語系80%に該当。
    japaneseSentence: 'こちらに電子署名をお願いします。',
    // コメント: 英文の依頼文に忠実な日本語訳です。
    englishReply: "Alright, I'll sign it now.",
    // コメント: 単純な語彙で、了承し作業を行う返答です。
    japaneseReply: 'はい、今署名します。',
    // コメント: 銀行窓口で、手続きに電子署名が必要とされ、顧客がその場で応じるシーンです。
    scenePrompt:
      '銀行のカウンターで女性行員が顧客の男性にタブレットを差し出し、電子署名を求めている。周囲には他の顧客も並んでいる。',
    senderVoiceInstruction: '丁寧でフォーマルな話し方',
    receiverVoiceInstruction: '落ち着いた口調で丁寧に返事',
    incorrectOptions: [
      'こちらに指で絵を描いてください。', // コメント: 馬鹿馬鹿しい（署名の代わりに絵）。
      'こちらに手書きの署名は不要です。', // コメント: 真逆の意味（署名不要）。
      'この用紙の裏に住所を書いてください。', // コメント: 全く異なる依頼で、署名と関係なし。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '人事担当者',
    senderVoice: 'female',
    receiverRole: '新入社員',
    receiverVoice: 'male',
    englishSentence: 'Did you see the new job posting?',
    // ルール根拠: 8語以内の疑問文で、"job posting"を自然に組み込んでいる。直訳系20%枠。
    japaneseSentence: '新しい求人情報を見ましたか？',
    // ルール根拠: 英文をそのまま直訳し、自然な日本語で表現している。
    englishReply: 'Yes, I checked it this morning.',
    // ルール根拠: 簡単な単語のみで構成し、意味が分かれば理解できる内容。
    japaneseReply: 'はい、今朝確認しました。',
    // ルール根拠: 英文の意図をそのまま訳している。
    scenePrompt:
      '春の朝、オフィスの会議室で人事担当者が新入社員に新しい求人情報について声をかけている。会議室には資料が並び、窓から光が差し込んでいる。',
    // ルール根拠: 会話の背景や登場人物の動機、場所の様子を詳細に説明。
    senderVoiceInstruction: '丁寧で親しみやすい口調で',
    receiverVoiceInstruction: '少し緊張しながらも素直な感じで',
    incorrectOptions: [
      '今週のランチメニューを見ましたか？',
      // ルール根拠: 別の話題で始まり、文字数も異なり、違う語で始まっている。
      '求人情報は全く見ていません。',
      // ルール根拠: 真逆の意味（見ていない）。異なる語で始まり、内容も反対。
      '空を飛ぶペンギンの募集を見ましたか？',
      // ルール根拠: 馬鹿馬鹿しい内容で、始まりの語も異なる。
    ],
  },
  {
    place: '企業の採用イベント会場',
    senderRole: '採用担当者',
    senderVoice: 'male',
    receiverRole: '応募者',
    receiverVoice: 'female',
    englishSentence: 'The recruitment process just got updated.',
    // ルール根拠: 8語以内で"recruitment process"を自然に組み込んだ文。熟語・慣用句系に該当。
    japaneseSentence: '採用プロセスが更新されました。',
    // ルール根拠: 英文を自然な日本語に直訳している。
    englishReply: 'Oh, thanks for letting me know.',
    // ルール根拠: 単語の意味が分かれば理解できる簡潔な返答。
    japaneseReply: 'あ、知らせてくれてありがとうございます。',
    // ルール根拠: 英文返答をそのまま自然な日本語に訳している。
    scenePrompt:
      '企業の採用イベント会場で、採用担当者が応募者に最新の採用プロセス変更を伝えている。周囲には他の応募者やパンフレットが並ぶ。',
    // ルール根拠: 会話の背景・場所・動機を具体的に描写。
    senderVoiceInstruction: '落ち着いていて丁寧な話し方で',
    receiverVoiceInstruction: '驚きと感謝が混じったトーンで',
    incorrectOptions: [
      '面接の時間が短縮されました。',
      // ルール根拠: 「更新されました」とは異なる意味。語頭も異なる。
      '採用プロセスは昔のままです。',
      // ルール根拠: 真逆の意味（変更なし）。異なる語で始まる。
      '魔法使いによる採用手順が導入されました。',
      // ルール根拠: 馬鹿馬鹿しい内容で、他とは違う語で始まる。
    ],
  },
  {
    place: 'ビデオ通話面接',
    senderRole: '面接官',
    senderVoice: 'female',
    receiverRole: '求職者',
    receiverVoice: 'male',
    englishSentence: 'This is a screening interview today.',
    // ルール根拠: 8語以内で"screening interview"を自然に組み込んでいる。熟語・慣用句系に該当。
    japaneseSentence: '本日は選考面接です。',
    // ルール根拠: 英文を自然な形で日本語に直訳している。
    englishReply: 'Okay, thank you for explaining.',
    // ルール根拠: 簡単な単語で理解しやすく、自然な返答。
    japaneseReply: 'はい、ご説明ありがとうございます。',
    // ルール根拠: 英文返答をそのまま自然な日本語に訳している。
    scenePrompt:
      'パソコンの前で求職者が面接官とビデオ通話をしており、面接官が今回の面接形式について説明している場面。画面には双方が映っている。',
    // ルール根拠: 背景・登場人物・動機・場面の様子を具体的に描写。
    senderVoiceInstruction: 'はっきりとした丁寧な口調で',
    receiverVoiceInstruction: 'やや緊張しつつも礼儀正しく',
    incorrectOptions: [
      '今日は雑談の時間です。',
      // ルール根拠: 別の内容、違う語で始まる。
      '本日は面接ではありません。',
      // ルール根拠: 真逆の意味（面接ではない）。異なる語で始まる。
      '宇宙人による面接が始まります。',
      // ルール根拠: 馬鹿馬鹿しい内容かつ始まりの語も異なる。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '人事担当者',
    senderVoice: 'female',
    receiverRole: '部門マネージャー',
    receiverVoice: 'male',
    englishSentence: 'Have you finished resume screening yet?',
    // 指定語彙「resume screening」を自然に含み、8語以内の疑問文としている。TOEIC頻出の人事場面で自然。
    japaneseSentence: '履歴書の選考はもう終わりましたか？',
    // 英語の直訳に忠実な、自然な日本語訳。
    englishReply: 'Yes, I finished it this morning.',
    // resume screeningの意味が分かれば理解できる簡単な返答で、自然な会話。
    japaneseReply: 'はい、今朝終わりました。',
    // シーンは人事担当者がマネージャーに進捗を確認している。背景や役割、会議室の状況を具体的に説明。
    scenePrompt:
      '大企業のオフィス会議室で、人事担当者が部門マネージャーに新規採用の履歴書選考の進捗を確認している。二人ともパソコンや書類を前にして、丁寧に仕事の状況を話し合っている。採用活動が活発な時期で、周囲には他の社員もいる。',
    senderVoiceInstruction: 'フォーマルで丁寧だが、少し急いでいる口調',
    receiverVoiceInstruction: '落ち着いていて誠実な話し方',
    incorrectOptions: [
      // 1. 馬鹿馬鹿しい選択肢
      '履歴書を折り紙にして折鶴を作りましたが、見ますか？',
      // 2. 真逆の意味（終わったか？→まだ始めていません）
      'まだ全く手を付けていません。',
      // 3. ランダムな文頭、かつsenderRoleらしい指示文
      'それでは面接の日程も調整しておいてください。',
    ],
    // ルール遵守根拠:
    // englishSentence: 8語以内、指定語彙を自然に含み、場面に合致。senderRoleとして自然。
    // japaneseSentence: 英文の直訳・自然な日本語で文字数バランス良好。
    // englishReply: 熟語なしで簡潔、会話として自然。
    // japaneseReply: 上記の自然な訳。
    // scenePrompt: 場面・登場人物・背景・状況を詳述し、AI画像生成用に十分な情報。
    // incorrectOptions: 3文とも違う語で始まり、japaneseSentenceより長短バラバラ。1つは馬鹿馬鹿しい。1つは真逆。senderRoleらしい内容。
  },
  {
    place: '会社の社長室',
    senderRole: '社長',
    senderVoice: 'male',
    receiverRole: '新入社員',
    receiverVoice: 'female',
    englishSentence: 'Please review your employment contract carefully.',
    // 指定語彙「employment contract」を自然に含み、8語以内の丁寧な依頼文。社長から新入社員への指示として自然。
    japaneseSentence: '雇用契約書をよく確認してください。',
    // 英語の直訳に忠実な日本語訳。
    englishReply: 'Okay, I will check it again.',
    // 難しい熟語を避け、単純明快な返事。
    japaneseReply: 'はい、もう一度確認します。',
    // シーンは新入社員が社長と初顔合わせをしていて、雇用契約について直接説明を受けている状況。
    scenePrompt:
      '会社の社長室で、社長が新入社員に初めて会い、雇用契約書の内容をしっかり読むように促している。重厚なデスクや本棚があり、緊張感と歓迎ムードが混じっている。',
    senderVoiceInstruction: '落ち着いていて威厳のある丁寧な話し方',
    receiverVoiceInstruction: '少し緊張した、誠実で素直な返事',
    incorrectOptions: [
      // 1. 馬鹿馬鹿しい選択肢
      '雇用契約書を紙飛行機にして飛ばしてもいいですか？',
      // 2. 真逆の意味（確認しろ→読む必要ない）
      '雇用契約書は読まなくて大丈夫です。',
      // 3. ランダムな文頭、かつsenderRoleらしい指示
      '次の研修日程も自分で調べてください。',
    ],
    // ルール遵守根拠:
    // englishSentence: 8語以内、指定語彙含む指示文。senderRoleに合ったトーン。
    // japaneseSentence: 英文の直訳かつ自然な訳で、長さも適切。
    // englishReply: 簡単明瞭で熟語なし。
    // japaneseReply: 上記訳。
    // scenePrompt: シーン・登場人物・状況を具体的に説明。
    // incorrectOptions: 3文とも文頭が異なり、馬鹿馬鹿しい・真逆・通常指示が揃い、長短もばらけている。
  },
  {
    place: '社員食堂',
    senderRole: '経理部員',
    senderVoice: 'female',
    receiverRole: '新入社員',
    receiverVoice: 'male',
    englishSentence: 'Have you checked your benefits package yet?',
    // 指定語彙「benefits package」を自然に含み、8語以内の疑問文。福利厚生確認はTOEIC頻出シーン。
    japaneseSentence: '福利厚生の内容はもう確認しましたか？',
    // 英文の内容を自然な日本語に直訳。
    englishReply: 'Yes, I looked at it online.',
    // 簡単で直訳的な内容。熟語なし。
    japaneseReply: 'はい、ネットで見ました。',
    // シーンは経理部員が新入社員とランチ中に福利厚生の話を振る。カジュアルな雰囲気。
    scenePrompt:
      '社員食堂で、経理部員が新入社員と並んでランチを取りながら、会社の福利厚生について気軽に声をかけている。周囲には他の社員もいて、和やかな雰囲気が広がっている。',
    senderVoiceInstruction: 'カジュアルで親しみやすい、明るい話し方',
    receiverVoiceInstruction: '素直で礼儀正しいトーン',
    incorrectOptions: [
      // 1. 馬鹿馬鹿しい選択肢
      '福利厚生で宇宙旅行に行けるって本当ですか？',
      // 2. 真逆の意味（確認したか？→全く見ていない）
      'まだ一度も見ていません。',
      // 3. ランダムな文頭、かつsenderRoleらしい話題
      '食堂のメニューも確認しましたか？',
    ],
    // ルール遵守根拠:
    // englishSentence: 8語以内、指定語彙含む、社員食堂の会話に自然。
    // japaneseSentence: 英語の直訳かつ自然。
    // englishReply: 熟語なし、簡潔で自然。
    // japaneseReply: 上記訳。
    // scenePrompt: 場所・登場人物・シチュエーション詳細。
    // incorrectOptions: 3文とも異なる文頭、1つ馬鹿馬鹿しい、1つ真逆、1つ通常の話題。長さもバラバラ。
  },
  {
    place: 'オフィスの会議室',
    senderRole: '上司',
    senderVoice: 'male',
    receiverRole: '部下',
    receiverVoice: 'female',
    englishSentence: 'Your performance evaluation is next week.',
    // 「performance evaluation」はTOEIC頻出かつ日本人に馴染みの薄い表現。8語以内を守り、直訳系に近いシンプルな文。
    // ルールに従い、自然なオフィスの会話になっている。
    japaneseSentence: '君の業績評価は来週だよ。',
    // 英語文を自然に訳した日本語。字数もバランス良し。
    englishReply: 'Okay, I will be ready.',
    // 熟語や難解な表現を避け、簡潔で意味がとりやすい返答。
    japaneseReply: '分かりました、準備しておきます。',
    // 英語返答を自然に訳した短く分かりやすい日本語。
    scenePrompt:
      '静かな会議室で上司が部下に来週の業績評価について伝えている場面。部下は少し緊張しているが、やる気も感じられる。壁にはホワイトボードやカレンダーがあり、書類が机の上に並んでいる。',
    // 会話だけでは分からない情景・雰囲気・動機を具体的に説明。AI画像生成に適した内容。
    senderVoiceInstruction: '落ち着いていて少し厳格なトーンで',
    receiverVoiceInstruction: '丁寧で控えめなトーンで',
    incorrectOptions: [
      '明日は会社の全員でランチに行きます。',
      // 文頭が「明日」。日本語訳と異なる始まり。内容も全く異なる。
      '今月は業績評価は行いません。',
      // 文頭が「今月」。真逆の意味（評価がない）。始まりも異なる。
      '空を飛べるようになったら連絡してください。',
      // 文頭が「空」。馬鹿馬鹿しい内容。始まりも異なる。
    ],
  },
  {
    place: '人事部のオフィス',
    senderRole: '人事担当者',
    senderVoice: 'female',
    receiverRole: '新入社員',
    receiverVoice: 'male',
    englishSentence: "Let's talk about your career development.",
    // 「career development」はTOEIC頻出の熟語。8語以内の自然な提案文。カジュアルなHR担当者の提案として自然。
    japaneseSentence: 'あなたのキャリア開発について話しましょう。',
    // 英語文を自然な日本語に訳出。字数もバランス良し。直訳になりすぎないよう調整。
    englishReply: 'Sure, I am interested in that.',
    // 熟語を避け、単純な肯定と関心の表現。
    japaneseReply: 'はい、それに興味があります。',
    // 英語返答を自然に訳した短い日本語。
    scenePrompt:
      '明るい人事部オフィスで人事担当者が新入社員のキャリア形成について親身に話しかけている。新入社員は真剣に耳を傾けている。デスクにはパソコンや書類が散らばっている。',
    // 会話に現れない情景や雰囲気、登場人物の動機を詳述。画像生成向き。
    senderVoiceInstruction: '親しみやすく優しいトーンで',
    receiverVoiceInstruction: '少し緊張しつつも前向きなトーンで',
    incorrectOptions: [
      '今後は休憩時間を短くしましょう。',
      // 文頭が「今後」。意味も全く違う内容。
      'キャリア開発については一切話しません。',
      // 文頭が「キャリア」。真逆の内容（話さない）。
      '宇宙で働きたいなら火星に行ってください。',
      // 文頭が「宇宙」。馬鹿馬鹿しい内容。
    ],
  },
  {
    place: '会社の研修室',
    senderRole: '研修担当者',
    senderVoice: 'male',
    receiverRole: '参加者',
    receiverVoice: 'female',
    englishSentence: 'The training session starts at nine sharp.',
    // 「training session」はTOEIC頻出の熟語。「at nine sharp」でビジネスらしい表現、8語以内。場面に即した発話。
    japaneseSentence: '研修は9時きっかりに始まります。',
    // 自然な日本語訳。英語のニュアンスをそのまま伝えている。
    englishReply: 'Thank you, I’ll be on time.',
    // 熟語を避け、単純な感謝と約束の表現。
    japaneseReply: 'ありがとうございます、時間通りに行きます。',
    // 英語返答を自然な日本語に訳したもの。
    scenePrompt:
      '広い研修室で研修担当者が参加者たちに開始時刻を伝えている。参加者は資料を手に持ち、前方のスクリーンや講師に注目している。窓から朝の日差しが差し込んでいる。',
    // 会話本文にない情景や雰囲気を詳細に描写。画像生成に適した内容。
    senderVoiceInstruction: 'はっきりした自信のあるトーンで',
    receiverVoiceInstruction: '礼儀正しく明るいトーンで',
    incorrectOptions: [
      '今日はパジャマで研修を受けてください。',
      // 文頭が「今日は」。馬鹿馬鹿しい内容。
      '研修は10時半に始まります。',
      // 文頭が「研修」。真逆の内容（異なる開始時刻）。
      '参加者は全員、研修後にケーキを食べます。',
      // 文頭が「参加者」。内容も異なる。全て異なる単語で開始。
    ],
  },
  {
    place: 'オフィス',
    senderRole: '上司',
    senderVoice: 'male',
    receiverRole: '部下',
    receiverVoice: 'female',
    englishSentence: 'There’s a promotion opportunity available.',
    // 8語以内で "promotion opportunity" を自然に組み込み、直訳しやすい文です。
    japaneseSentence: '昇進のチャンスがありますよ。',
    // "promotion opportunity" の意味が分かれば直訳できる自然な日本語訳です。
    englishReply: 'Oh, that’s great news. Thank you.',
    // 熟語を使わず、感嘆＋感謝の自然な返答です。
    japaneseReply: 'ああ、それはうれしい知らせです。ありがとうございます。',
    // 英文の意味通り、感動＋感謝の自然な日本語返答です。
    scenePrompt:
      'オフィスの静かな一角で、上司が部下に新たな昇進のチャンスがあることを伝えている。部下は日頃から真面目に働いており、上司はその努力を認めている。部下は突然の知らせに驚きつつもうれしさを感じている。',
    // 場所・登場人物・心情・背景（部下の努力）を補足して具体的な場面を説明しています。
    senderVoiceInstruction: '落ち着いていて信頼感のある声で、ややフォーマルに',
    receiverVoiceInstruction: '少し驚きつつも、喜んでいる様子で',
    incorrectOptions: [
      '今月の給料は全額カットになります。',
      // "promotion opportunity"の真逆で、悪い知らせです。
      '新しいコーヒーメーカーを空に飛ばしましょうか？',
      // 馬鹿馬鹿しい発想で、職場に全くそぐわない提案です。
      '最近は特に変化はありません。',
      // 「昇進のチャンスがあります」と逆の「変化なし」という意味です。
    ],
  },
  {
    place: '工場',
    senderRole: '安全管理担当者',
    senderVoice: 'female',
    receiverRole: '作業員',
    receiverVoice: 'male',
    englishSentence: 'Please follow the workplace safety guidelines.',
    // 8語以内で "workplace safety" を自然に組み込んだ依頼文です。
    japaneseSentence: '職場の安全指針を守ってください。',
    // "workplace safety" の意味が分かれば直訳できる自然な日本語訳です。
    englishReply: 'Yes, I will be careful.',
    // 熟語を使わず、単純な肯定と意識表明のみ。
    japaneseReply: 'はい、気をつけます。',
    // 英文の意味に忠実な簡単な日本語訳です。
    scenePrompt:
      '工場の朝礼で、安全管理担当者が作業員たちに安全指針を守るよう呼びかけている。現場は機械音が響き、作業員たちは真剣な表情で話を聞いている。安全第一の雰囲気が漂っている。',
    // 場所・担当者の役割・現場の音・雰囲気などを具体的に描写しています。
    senderVoiceInstruction: 'はっきりとした声で、注意喚起を込めて伝える',
    receiverVoiceInstruction: '真面目に受け止めている様子で',
    incorrectOptions: [
      '今日は安全指針を無視してください。',
      // 真逆の意味で危険な指示です。
      '明日は工場でヨガ大会を開きます。',
      // 馬鹿馬鹿しい発想で、工場の安全指針と関係ありません。
      '安全指針はすでに完全に更新済みです。',
      // 「守ってください」とは意味が異なり、指針の状態だけを述べています。
    ],
  },
  {
    place: '会社の休憩室',
    senderRole: '人事担当者',
    senderVoice: 'male',
    receiverRole: '社員',
    receiverVoice: 'female',
    englishSentence: 'You can apply for paid leave online.',
    // 8語以内で "paid leave" を自然に組み込み、申請方法を伝えています。
    japaneseSentence: '有給休暇はオンラインで申請できます。',
    // "paid leave" の意味が分かれば直訳できる自然な日本語訳です。
    englishReply: 'Okay, I will try it soon.',
    // 熟語なし、肯定と簡単な行動表明のみ。
    japaneseReply: 'わかりました。すぐにやってみます。',
    // 英文どおりの簡単な日本語訳です。
    scenePrompt:
      '会社の休憩室で、社員が人事担当者に有給休暇の申請方法を尋ねている。人事担当者はパソコン画面を指しながら、オンラインで手続きできることを説明している。社員はほっとした表情を浮かべている。',
    // 場所・登場人物・背景・状況（申請方法の説明）を具体的に描写しています。
    senderVoiceInstruction: '親切で分かりやすい話し方で',
    receiverVoiceInstruction: '安心した様子で、前向きに',
    incorrectOptions: [
      '有給休暇の取得は全面的に禁止です。',
      // 真逆の内容（取得不可）です。
      '有給休暇を申請すると空が虹色になります。',
      // 馬鹿馬鹿しい発想で、現実にはありえません。
      'あなたの有給休暇はすでにすべて消化済みです。',
      // 「申請できます」とは異なり、「もう使い切った」という意味です。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: '人事担当者',
    senderVoice: 'female',
    receiverRole: '社員',
    receiverVoice: 'male',
    englishSentence: 'Have you received your overtime compensation?',
    // ルール根拠: 8語、語彙「overtime compensation」を自然に含み、口語の質問文。
    japaneseSentence: '残業手当は受け取りましたか？',
    // ルール根拠: 英文の直訳に近い自然な日本語。疑問文。
    englishReply: 'Yes, I got it yesterday.',
    // ルール根拠: 単純な語彙と文法で直訳可能な返答。相槌も含む。
    japaneseReply: 'はい、昨日受け取りました。',
    // ルール根拠: 英文の直訳で自然な日本語。相槌あり。
    scenePrompt:
      '社員が会議室で人事担当者と最近の給与について話している。今月の残業代がきちんと支払われたかを確認している場面。会議室は落ち着いた雰囲気で、書類が並んでいる。',
    // ルール根拠: 場面、場所、登場人物、動機を具体的に説明。
    senderVoiceInstruction: '落ち着いた丁寧なトーンで、確認のために質問する',
    receiverVoiceInstruction: '安心した様子で、はっきりと答える',
    incorrectOptions: [
      '新しいプロジェクトの締め切りはいつですか？',
      // ルール根拠: 異なる語、長さも適度、内容は全く別の質問。
      '残業手当は今後一切支給しません。',
      // ルール根拠: 真逆の意味（支給しない）、語頭も違う。
      'コアラの着ぐるみで会議に出てみませんか？',
      // ルール根拠: 馬鹿馬鹿しい内容。違う語で始まる。
    ],
  },
  {
    place: 'カフェ',
    senderRole: '同僚',
    senderVoice: 'male',
    receiverRole: '同僚',
    receiverVoice: 'female',
    englishSentence: 'Can I bring up a topic now?',
    // ルール根拠: 8語以内、語彙「bring up a topic」自然に使用、親しみやすい疑問文。
    japaneseSentence: '今ちょっと話題を出してもいい？',
    // ルール根拠: 英文の自然な意訳。疑問文。
    englishReply: 'Sure, what do you want to say?',
    // ルール根拠: 単純な語彙、直訳的な返事。相槌も含む。
    japaneseReply: 'うん、何を話したいの？',
    // ルール根拠: 英文をそのまま自然な日本語に。
    scenePrompt:
      '昼休みにカフェで同僚同士がリラックスしながら会話している。ひとりが何か相談したいことがあって、話を切り出そうとしているシーン。',
    // ルール根拠: 場所・登場人物・状況を具体的に説明。
    senderVoiceInstruction: 'カジュアルで親しみやすく、少し緊張したトーンで',
    receiverVoiceInstruction: '優しくリラックスしたトーンで',
    incorrectOptions: [
      '今日のランチはカレーにしようかな？',
      // ルール根拠: 違う語で始まる、長さも適度、話題が全く違う。
      '今は誰とも話さずに静かにしてほしい。',
      // ルール根拠: 真逆（話題を出すことを拒否）、違う語で始まる。
      'カフェの床で逆立ちしてみていい？',
      // ルール根拠: 馬鹿馬鹿しい内容、違う語で始まる。
    ],
  },
  {
    place: '建設現場',
    senderRole: '現場監督',
    senderVoice: 'female',
    receiverRole: '作業員',
    receiverVoice: 'male',
    englishSentence: 'Let’s call it a day, everyone.',
    // ルール根拠: 8語以内、語彙「call it a day」自然な命令文、現場監督の言いそうな口語表現。
    japaneseSentence: 'みんな、今日はここまでにしよう。',
    // ルール根拠: 英文の慣用句を自然な日本語訳に、命令・提案口調。
    englishReply: 'Okay, I’ll start cleaning up.',
    // ルール根拠: 単純な語彙・文法、意図が明確で直訳できる返答。
    japaneseReply: 'わかりました、片付けを始めます。',
    // ルール根拠: 英文の直訳。自然な日本語。
    scenePrompt:
      '夕方の建設現場で、現場監督が作業員たちに今日の作業を終えるよう声をかけている。仕事道具やヘルメットがあり、日が沈みかけている。',
    // ルール根拠: 場面・場所・登場人物・動機を具体的に説明。
    senderVoiceInstruction: '元気で明るいが、きっぱりとしたトーンで',
    receiverVoiceInstruction: '素直で協力的なトーンで',
    incorrectOptions: [
      '明日の作業は夜まで続けます。',
      // ルール根拠: 違う語で始まる、japaneseSentenceより少し長め、逆の内容。
      '今日はまだ始まったばかりだから頑張ろう。',
      // ルール根拠: 真逆の意味（仕事を続けよう）、違う語で始めている。
      'みんなで空を飛んで帰宅しましょう！',
      // ルール根拠: 馬鹿馬鹿しい内容、違う語で始まる。
    ],
  },
  {
    place: 'オフィスの休憩室',
    senderRole: '同僚',
    senderVoice: 'female',
    receiverRole: '同僚',
    receiverVoice: 'male',
    englishSentence: 'I need to catch up on work.',
    // コメント: 8語以内で "catch up on work" を自然に使った直訳系の文章。
    japaneseSentence: '仕事の遅れを取り戻さないと。',
    // コメント: "catch up on work" の意味を反映した自然な日本語訳。
    englishReply: 'Oh, good luck with that.',
    // コメント: 簡単な単語のみで構成し、意味が直訳で分かる返答。
    japaneseReply: 'うん、頑張ってね。',
    // コメント: 英語の返答に沿った、分かりやすい日本語訳。
    scenePrompt:
      'オフィスの昼休み、休憩室で同僚同士が会話している。送り手は最近忙しくて仕事が遅れ気味で、これからそれを取り戻そうとしている。',
    // コメント: 場所、登場人物、状況など細かな文脈が説明されている。
    senderVoiceInstruction: '少し疲れた様子で、でも前向きに',
    receiverVoiceInstruction: '親しみやすく励ます感じで',
    incorrectOptions: [
      '今日のランチはピザにしようと思うんだ。',
      // コメント: 意味が逆ではなく、全く違う話題で、かつ文頭が異なる。
      '今は仕事をサボりたい気分だよ。',
      // コメント: 「仕事の遅れを取り戻す」と逆の意味になる内容。
      '巨大なカバンで仕事場にカブトムシを連れてきたよ！',
      // コメント: 馬鹿馬鹿しい内容で、全く脈絡がない。
    ],
  },
  {
    place: 'カフェ',
    senderRole: 'プロジェクトリーダー',
    senderVoice: 'male',
    receiverRole: 'チームメンバー',
    receiverVoice: 'female',
    englishSentence: 'Can you come up with an idea?',
    // コメント: 8語以内で "come up with an idea" を使い、疑問文形式に。
    japaneseSentence: '何かアイデアを考えてくれる？',
    // コメント: "come up with an idea" の意味を自然に訳している。
    englishReply: "Sure, I'll think about it.",
    // コメント: 簡単な構文で内容が分かりやすい。
    japaneseReply: 'うん、考えてみるよ。',
    // コメント: 直訳で分かる返答。
    scenePrompt:
      'カフェでプロジェクトのミーティング中。プロジェクトリーダーが新しい企画のアイデア出しをチームメンバーに頼んでいる。',
    // コメント: 会話の背景や登場人物、場面を明示。
    senderVoiceInstruction: 'リーダーらしく丁寧で頼もしい口調で',
    receiverVoiceInstruction: '前向きで明るい口調で',
    incorrectOptions: [
      'あなたの意見には全く賛成できないよ。',
      // コメント: 全く逆の否定的な内容。
      '私のペットのカメがダンスできるんだ。',
      // コメント: 馬鹿馬鹿しい内容。
      'このカフェは静かで落ち着くね。',
      // コメント: 全く違う話題、文頭が異なる。
    ],
  },
  {
    place: '家のリビング',
    senderRole: '母親',
    senderVoice: 'female',
    receiverRole: '息子',
    receiverVoice: 'male',
    englishSentence: "Let's cut back on expenses now.",
    // コメント: 8語以内で "cut back on expenses" を自然に含めた提案の文章。
    japaneseSentence: '今は出費を抑えましょう。',
    // コメント: "cut back on expenses" の意味を自然に訳している。
    englishReply: "Yeah, that's a good idea.",
    // コメント: 簡単な肯定の返事。
    japaneseReply: 'うん、それがいいね。',
    // コメント: 直訳で伝わる返答。
    scenePrompt:
      '家計を見直すため、リビングで母親が息子にこれから節約しようと提案している。家庭的なシーン。',
    // コメント: シチュエーション、登場人物、動機が明確に示されている。
    senderVoiceInstruction: '穏やかで優しい口調で',
    receiverVoiceInstruction: '素直に賛成するトーンで',
    incorrectOptions: [
      '今夜は豪華なディナーを作りましょう。',
      // コメント: 真逆の意味になる内容。
      '明日から家の中でジェットコースターを走らせよう。',
      // コメント: 馬鹿馬鹿しい内容。現実味がない。
      '毎月の貯金を少し増やそうか。',
      // コメント: 出費ではなく貯金について提案している。文頭も違う。
    ],
  },
  {
    place: 'オフィスの会議室',
    senderRole: 'プロジェクトマネージャー',
    senderVoice: 'female',
    receiverRole: 'チームメンバー',
    receiverVoice: 'male',
    englishSentence: 'Can you figure out a solution?',
    // 8語以内、figure out a solutionを自然に組み込み、会議での依頼のトーン
    // 直訳で意味が取れる表現ではなく、日本人が苦手な熟語（figure out）を使用
    japaneseSentence: '解決策を考えてくれますか？',
    // 「figure out a solution」の自然な日本語訳
    englishReply: 'Sure, I will try to find one.',
    // 熟語・慣用句を使わず、直訳で理解できる返答
    japaneseReply: 'わかりました、考えてみます。',
    scenePrompt:
      'プロジェクトの進行中、会議室でマネージャーがチームメンバーに問題解決を依頼している場面。ホワイトボードにタスクやスケジュールが書かれている。メンバーは真剣な表情で話を聞いている。',
    // 会議室、役割、状況、登場人物の動機や背景を具体的に説明
    senderVoiceInstruction: '落ち着いていて頼りがいのある、少しフォーマルな話し方',
    receiverVoiceInstruction: '真面目で丁寧な話し方',
    incorrectOptions: [
      '新しい企画を今すぐ発表してください。',
      // 「解決策を考えてくれますか？」と逆の意味。考えなくていい、行動を求めている。
      '会議中にバナナで電話をかけてください。',
      // 馬鹿馬鹿しい文。「バナナで電話」は現実的でない。
      '全ての問題を無視して進めましょう。',
      // 真逆の意味。解決を求めるのではなく、無視して進める。
    ],
  },
  {
    place: '会社の受付',
    senderRole: '受付スタッフ',
    senderVoice: 'male',
    receiverRole: '来客',
    receiverVoice: 'female',
    englishSentence: 'I will get in touch with her.',
    // 8語以内、get in touch withを自然に組み込んだ、受付での申し出のセリフ
    // get in touch withは日本人に馴染みが薄い熟語
    japaneseSentence: '彼女に連絡を取ります。',
    // get in touch with herの自然な日本語訳
    englishReply: 'Thank you, I appreciate your help.',
    // 簡単な感謝の返答。熟語・慣用句なし
    japaneseReply: 'ありがとうございます、助かります。',
    scenePrompt:
      '会社の受付カウンターで、来客が担当者に会いたいと伝えた後、受付スタッフが担当者へ連絡を取ることを伝えている。受付には電話やパソコンがあり、来客は少し緊張した様子。',
    // 受付の状況、登場人物、雰囲気、背景を具体的に説明
    senderVoiceInstruction: '親切で丁寧な話し方',
    receiverVoiceInstruction: '感謝の気持ちを込めて丁寧な話し方',
    incorrectOptions: [
      '明日になったらまた来てください。',
      // 連絡を取るのではなく、別の行動を促すので逆の意味
      '受付でダンスを披露してもらえますか？',
      // 馬鹿馬鹿しい。受付でダンスは不自然
      '担当者には連絡しません。',
      // 真逆の意味。「連絡しない」
    ],
  },
  {
    place: 'カフェのテーブル',
    senderRole: '同僚',
    senderVoice: 'female',
    receiverRole: '同僚',
    receiverVoice: 'male',
    englishSentence: "Let's go over the details now.",
    // 8語以内、go over the detailsを自然に組み込んでいる。カフェでの会話
    // go over the detailsは日本人が苦手な熟語
    japaneseSentence: '今、詳細を確認しましょう。',
    // go over the details nowの自然な日本語訳
    englishReply: "Alright, let's check everything together.",
    // 熟語・慣用句なしで、内容が理解できる返答
    japaneseReply: 'わかった、一緒に全部確認しよう。',
    scenePrompt:
      'カフェのテーブルで、同僚同士がノートパソコンや書類を広げて仕事の相談をしている。プロジェクトの準備で、これから細かい内容を一緒に確認しようと話している。',
    // カフェの雰囲気、登場人物、細かい作業の状況、背景を具体的に説明
    senderVoiceInstruction: '親しみやすく明るい話し方',
    receiverVoiceInstruction: 'リラックスして協力的な話し方',
    incorrectOptions: [
      '今は何もしないでおきましょう。',
      // 逆の意味。詳細を確認するのではなく、何もしない
      '机の上で動物の鳴き声をまねしてください。',
      // 馬鹿馬鹿しい。カフェで動物の鳴き声は不自然
      'あとで全部忘れましょう。',
      // 真逆の意味。確認どころか、忘れる
    ],
  },
];

export default problemData;
